grafana/mimir

.github/workflows/test-build-deploy.yml, integration/backward_compatibility.go, integration/e2emimir/services.go
Mimir 2.0.0 guarantees backward compatibility with Cortex. After 2.0.0 we'll keep testing backward compatibility against Mimir previous versions, so in this PR I'm changing the integration test to run against Mimir 2.0.0.
**Draft PR** until Mimir launch. After that we can remove the "Docker login" step.
N/A
=> Update backward compatibility test after Mimir 2.0.0 launch

CHANGELOG.md, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary.jsonnet, operations/mimir/memberlist.libsonnet
This PR fixes passing of primary and secondary stores to `multi` KV config. These need to be passed via CLI, and not runtime config. 
=> Pass primary and secondary multiKV stores via CLI parameters.

pkg/mimirtool/config/inspect.go
This PR improves speed of tests in `github.com/grafana/mimir/pkg/mimirtool/config` package. Instead of each test doing JSON-unmarshalling of config files, we now do it once, and then make in-memory clone for each test.
This improves speed of tests in this package from `25.59s` to `3s` on my machine when running `go test -v -parallel 1 github.com/grafana/mimir/pkg/mimirtool/config`. (I'm running with `-parallel 1` to make tests slower. On my multicore machine they are normally plenty fast, but we see them being slow in CI).
=> Speed up tests in `github.com/grafana/mimir/pkg/mimirtool/config`

CHANGELOG.md, pkg/mimir/status.go, pkg/util/http.go
It was forced to be `text/plain` for some reason. Removed that forcing, and added an explicit setting of `text/html` in RenderHTTPResponse when it's not YAML (comment says it will render HTML, so it's safe).
A new take to https://github.com/grafana/mimir/pull/1265
=> Fix "Services' status" page content type

pkg/alertmanager/alertmanager_http.go, pkg/alertmanager/ring_status.gohtml, pkg/alertmanager/status.gohtml, pkg/api/handlers.go, pkg/api/index.gohtml, pkg/compactor/compactor_http.go, pkg/compactor/status.gohtml, pkg/distributor/ha_tracker_http.go, pkg/distributor/ha_tracker_status.gohtml, pkg/distributor/http_admin.go, pkg/distributor/ingester_stats.gohtml, pkg/mimir/status.go, pkg/mimir/status.gohtml, pkg/storegateway/blocks.gohtml, pkg/storegateway/gateway_blocks_http.go, pkg/storegateway/gateway_ring_http.go, pkg/storegateway/gateway_tenants_http.go, pkg/storegateway/ring_status.gohtml, pkg/storegateway/tenants.gohtml
Instead of having HTML in constants, extract them to `.gohtml` files, properly annotated with the type they expect to be rendering, and then embed them using the `//go:embed` directive.
Also standarize the usage across projects, variable for the HTML of page `foo` is called `fooPageHTML`, the template is `fooPageTemplate` and the struct that is being rendered is called `fooPageContents`.
None.
Not needed, only moving code.
=> Chore: extract HTML templates to .gohtml files

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_client.go, pkg/alertmanager/multitenant.go
Exposes existing configuration via yaml and CLI flags:
* Alertmanager GRPC Client config is re-used from dskit
* Alertmanager Concurrency is exposed to support running Alertmanager under heavier load
Tuning these parameters is useful when alertmanager is under heavy load
Fixes https://github.com/grafana/mimir-squad/issues/578
=> Add configuration for Alertmanager GRPC client and GET request concurrency

.github/workflows/publish.yml
Reconfigures the destination branch of the documentation sync so that the website publishes it automatically.
=> Redirect documentation sync to the website publishing branch

docs/sources/operators-guide/reference-http-api/index.md, pkg/api/api.go, pkg/mimir/status.gohtml
As @osg-grafana pointed out, this page is listing the status information about more than one service, so this is the correct spelling.
See: https://github.com/grafana/mimir/pull/1265#issuecomment-1047841452
_I don't think this deserves a changelog entry, right?_
=> Fix "Services' status" spelling

CHANGELOG.md, operations/mimir/README.md, operations/mimir/config.libsonnet, operations/mimir/ingester.libsonnet, operations/mimir/multi-zone.libsonnet
While setting up Mimir on my personal toy-cluster of one node, I got stuck scheduling the ingesters as they have the anti-affinity rules by default and it can't be easily removed without redefining the statefulset. There are similar configs for distributor, querier, etc.,
so I just added another one, and documented it a little bit.
None
=> mimir-jsonnet: allow disabling ingester anti-affinity

.github/ISSUE_TEMPLATE/documentation_request.md
Sometimes users just want docs: they don't want to report bugs or add a feature (well, docs are a feature, but you know what I mean).
Those issues have a slighly different structure, and they have to be labeled as `type/docs`.
This makes creating such requests easier.
None
=> Add "Documentation request" issue template

.github/workflows/test-build-deploy.yml
This PR removes secrets used to access build-image and mimir-prometheus repository, since these are now public. Secrets are not passed to workflows that are triggered by a pull request from a fork, which causes checks from external people to fail.
=> Remove unneeded secrets from workflow

CHANGELOG.md, cmd/mimir/help.txt.tmpl, cmd/mimir/usage.go
This PR updates dskit to commit [6d48ca07ade5.](https://github.com/grafana/dskit/commit/6d48ca07ade59022d5e1467c7f72cbfa01aecfa6). This fixes panic in `multi` KV store implementation when using runtime config to change primary KV store used by `multi`.
=> Update changelog, fix acl-token flags in help.

Makefile
This PR allows BUILD_IN_CONTAINER variable to be set by environment variable as well (in shell-profile script, or `BUILD_IN_CONTAINER=false make ...`) and not just as variable override (`make BUILD_IN_CONTAINER=false ...`)
=> Don't hardcode BUILD_IN_CONTAINER

operations/mimir/README.md, operations/mimir/jsonnetfile.lock.json
Not everyone has tens of gigabytes to play with, documenting this will reduce the friction of running mimir from scratch.
Also updated memcached lib, so now cpu_requests is configurable, ref: https://github.com/grafana/jsonnet-libs/pull/756
None
=> Document scaling in jsonnet, and update memcached

pkg/continuoustest/client.go, pkg/continuoustest/client_test.go, pkg/continuoustest/metrics.go, pkg/continuoustest/util.go, pkg/continuoustest/util_test.go, pkg/continuoustest/write_read_series.go, pkg/continuoustest/write_read_series_test.go
In this PR I'm adding support to query back written series (using range query) to write-read-series-test in mimir-continuous-test tool.
At each interval, after writing series the tool query back the time range successfully written until that point in time. The queried time ranges are:
- Last 1h
- Last 24h
- From last 23h to last 24h
- Random time range (up until the configured max query age)
**Out of the scope of this PR** (will be done in follow up PRs):
- Test instant query
- Query results cache disabled too
- Find the previously written samples at startup, so that it can continue write and read after a restart
- CHANGELOG
- Doc
N/A
=> Added range query support to write-read-series-test in mimir-continuous-test tool

Makefile, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin-compiled/rules.yaml
While reviewing #1533, I realized `operations/mimir-mixin-compiled/alerts.yaml` is not updated but CI isn't failing. Reason is that CI doesn't build and check `operations/mimir-mixin-compiled`.
I've also changed Makefile to build and format mixin using `mimir-build-image` to ensure all contributors use the same tooling versions. This causes a formatting difference. See the change in the dedicated commit: https://github.com/grafana/mimir/pull/1606/commits/92559202123ee7d5c271e65d57dcd325cd07e6fb
This PR fixes that.
N/A
=> Fix builded mixin

CHANGELOG.md, operations/mimir-mixin/dashboards/tenants.libsonnet
The dashboard only allows for selecting a single user, so we can cleanup the
legends and simplify the queries slightly. The secondary motiviation for this
change to make room to add some additional information to the series panels.
=> Dashboards: Remove per-user series legends from Tenants dashboard.

pkg/alertmanager/alertstore/local/store_test.go, pkg/alertmanager/multitenant_test.go, pkg/compactor/bucket_compactor_e2e_test.go, pkg/compactor/compactor_test.go, pkg/ingester/ingester_test.go, pkg/querier/blocks_finder_bucket_scan_test.go, pkg/querier/querier_test.go, pkg/ruler/manager_test.go, pkg/ruler/rulestore/local/local_test.go, pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/bucket_test.go, pkg/storegateway/gateway_test.go, pkg/storegateway/postings_codec_test.go, pkg/util/process/collector_test.go
A testing cleanup. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
Reference: https://pkg.go.dev/testing#T.TempDir
=> test: use `t.TempDir` to create temporary test directory

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/tenants.libsonnet
Changes the "Active series" panel on the "Tenants" dashboard to show:
- Current number of in-memory series for the tenant
- The current in-memory series limit (either from overrides or the default)
This information is extremely valuable to operators tasked with troubleshooting when tenants are hitting limits, or whether they are close to hitting limits. Looking at only active series often causes confusion because limits are applied to the number of in-memory series, not active series.
Fixes n/a
- n/a Tests updated
=> Mixin: Show in-memory series and the per-user limit on Tenants dashboard.

pkg/mimirtool/config/inspect.go, tools/doc-generator/main.go, tools/doc-generator/parse/parser.go
* In order to reuse the parse package in GEM we need to be able to inject the root blocks into the config. An alternative to this change is to introduce an interface 
```go
type RootBlocker interface {
IsRootBlock(reflect.Type) (name, description string, isRootBlock bool)
}
```
But I don't see that as a much better alternative - the implementations will be backed by the same logic as now.
* This also changes the signature of `parse.Config` to drop the `block *ConfigBlock` arg, which was always `nil` when passed from outside the package.
=> Make doc-generator root blocks injectable

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin-compiled/rules.yaml, operations/mimir-mixin/alerts/alerts.libsonnet, operations/mimir-mixin/alerts/blocks.libsonnet, operations/mimir-mixin/recording_rules.libsonnet, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/metrics.go
Add `user` label to ingested samples metrics:
* cortex_ingester_ingested_samples_total
* cortex_ingester_ingested_samples_failures_total
The motivation is that we need to be able to differentiate on the tenant when determining the percentage of samples getting dropped by our ingesters.
TODO:
Fixes #1531.
=> Add user label to ingested samples metrics

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin/dashboards/tenants.libsonnet
Fix to use the correct metric, and only show series which actually have
failures, making the panel easier to read when there are many rule groups.
=> Mixin: Fix "Failed evaluation rate" panel on Tenants dashboard.

docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, tools/doc-generator/parse/root_blocks.go
The GEM docs [have the `query_scheduler` as a root block](https://grafana.com/docs/metrics-enterprise/latest/config/reference/#query_scheduler_config) and it looks like something that should go into a root block for Mimir too, but was missed. This PR adds it.
=> Add `query_scheduler` root block to docs

docs/sources/migration-guide/migrating-from-cortex.md
- `-Y` isn't a valid flag for `yq`
- `--yaml-file` is a positional argument to `mimirtool config convert`
Signed-off-by: Josh Carp <jm.carp@gmail.com>
=> Fix typos in cortex migration guide.

CHANGELOG.md, pkg/cache/versioned.go, pkg/cache/versioned_test.go, pkg/frontend/querymiddleware/results_cache.go
Added a cache.Versioned wrapper and used it to bump the frontend's result cache version, which is needed to invalidate results that might have been cached by a previous version of the code.
Fixes https://github.com/grafana/mimir/issues/1625
=> Bump frontend results cache version

operations/k6/README.md, operations/k6/load-testing-with-k6.js
In this PR I'm upstreaming a k6 script that can be used to load test Mimir. It's the same script we used to load test it with 1 billion series back in time, except that I've reverted the default config to small scale (to avoid people accidentally overload a non properly scaled Mimir cluster) and added the ability to specify config via env variables.
I tested it locally, to ensure it works as expected.
N/A
=> Add k6 load testing script

operations/k6/README.md
Ref: https://github.com/github/linguist/blob/4ffcdbcbb60a74cbfbd37656bcc3fcea4eca8e26/lib/linguist/languages.yml#L5835-L5906
`sh` or others hightlight as shell, `console` is a different thing and it's not highlighted properly.
This is `console`:
```console
k6 run load-testing-with-k6.js -e K6_WRITE_HOSTNAME="localhost:80" -e K6_READ_HOSTNAME="localhost:80"
```
This is `sh`:
```sh
k6 run load-testing-with-k6.js -e K6_WRITE_HOSTNAME="localhost:80" -e K6_READ_HOSTNAME="localhost:80"
```
(Not a huge difference, but notice quoted strings are highlighted now)
=> Shell highlighting in k6/README.md

Makefile
The MAKEFILES variable is treated by Make as a whitespace separated
list of Makefiles to include. In this case, this was an undesired side
effect of wanting to find all Makefiles for linting.
Fixes #1646
Fixes #1647 
=> Fix recursive make invocations that were being confused by the MAKEFILES var

pkg/mimirtool/client/alerts.go, pkg/mimirtool/client/rules.go, pkg/mimirtool/commands/alerts.go, pkg/mimirtool/commands/analyse_grafana.go, pkg/mimirtool/commands/analyse_prometheus.go, pkg/mimirtool/commands/analyse_ruler.go, pkg/mimirtool/commands/bucket_validation.go, pkg/mimirtool/commands/remote_read.go, pkg/mimirtool/commands/rules.go, pkg/mimirtool/config/convert_test.go
mimirtool: Don't use the deprecated `ioutil` package.
=> mimirtool: Don't use ioutil

operations/mimir-mixin/docs/playbooks.md
This PR updates `MimirTenantHasPartialBlocks` playbook to use `markblocks` tool, instead of `gsutil rm`. `markblocks` is safer (it checks that block exists, only marks for deletion) and works with all Mimir-supported backends.
Requires https://github.com/grafana/mimir/pull/1640, update for `-allow-partial` flag.
=> Use `markblocks` in MimirTenantHasPartialBlocks playbook.

tools/markblocks/main.go
This PR enhances `markblocks` tool with `-allow-partial` option, which allows uploading into partial blocks, that is blocks which don't have meta.json file anymore. Compactor normally ignores partial blocks (waiting for block upload to finish), but it respects deletion marker in such blocks.
No changelog entry added, since `markblocks` was not part of any release yet.
=> markblocks: Allow uploads of mark files into partial blocks.

operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown.jsonnet, operations/mimir/memberlist.libsonnet
This addresses a timing issue with runtime configuration when migrating off of a multikv to memberlist. The issue was the runtime configuration changing at the same time as the normal configuration, which meant that pods could pick up the runtime configuration before being rolled out to, which would result in them swapping their primary back to the default of consul.
Adding `multikv_migration_teardown` allows the runtime configuration to stay the same, so when the configuration rollout is finished then the runtime configuration can be set later when it is safe to do so.
Here's `diff -u test-gossip-multikv-switch-primary-secondary-generated.yaml test-gossip-multikv-teardown-generated.yaml` showing just the store being set:
```diff
--- …
```
=> Address timing condition in memberlist migration teardown

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/about-versioning.md, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, operations/mimir-tests/test-defaults-generated.yaml, operations/mimir-tests/test-disable-chunk-streaming-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir-tests/test-query-sharding-generated.yaml, operations/mimir-tests/test-shuffle-sharding-generated.yaml, operations/mimir-tests/test-storage-azure-generated.yaml, operations/mimir-tests/test-storage-gcs-generated.yaml, operations/mimir-tests/test-storage-s3-generated.yaml, operations/mimir/ingester.libsonnet, pkg/storage/tsdb/config.go
Changed `-blocks-storage.tsdb.isolation-enabled` default to false and deprecated config option, as described in #1652.
Fixes #1652
=> Changed -blocks-storage.tsdb.isolation-enabled default to false and deprecated config option

development/tsdb-blocks-storage-s3/config/mimir.yaml, development/tsdb-blocks-storage-s3/config/runtime.yaml, development/tsdb-blocks-storage-s3/docker-compose.jsonnet
This PR extends docker-compose setup in `development/tsdb-blocks-storage-s3` to support `multi` KV store, and also adds example runtime-config section to show how to change it in runtime. Useful when debugging `multi` KV store support in Mimir.
=> Improve docker-compose setup to support multi KV

CHANGELOG.md, pkg/mimir/modules.go, pkg/mimir/modules_test.go
This PR moves initialization of multi KV runtime watcher into `initRuntimeConfig` function.
This fixes problem where Mimir-derived subproject overriding "ruler" init method wouldn't wire the runtime config watcher properly. This PR also fixes problem where ruler and querier wouldn't have runtime config watcher for multi KV installed for  `querier-store-gateway` KV.
=> Move initialization of multi KV runtime watcher into initRuntimeConfig function

pkg/continuoustest/manager.go, pkg/continuoustest/util.go, pkg/continuoustest/util_test.go, pkg/continuoustest/write_read_series.go, pkg/continuoustest/write_read_series_test.go
In this PR I'm adding logic to find previously written samples in mimir-continuous-test and recover from there at startup. The idea is that after a restart (eg. rollout new version or K8S re-scheduling) the continuous test tool should try to recover from previous state.
**What's done in this PR:**
- Detect previously written samples at startup (only contiguous samples matching the expected values are considered valid)
- If no data is found, then start remote writing samples from the current timestamp
- If the latest written sample time is older than `1h - 10m delta = 50m` then it acts as if no previous data has been found and starts writing from the current timestamp
**Out of scope of this PR:**
-  Query both with cache enabled and disabled
- Doc & CHANGELOG
N/A
=> Find previously written samples in mimir-continuous-test and recover from there at startup

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts.libsonnet, operations/mimir-mixin/alerts/continuous-test.libsonnet, operations/mimir-mixin/docs/playbooks.md
In this PR I'm adding 2 class of alerts on `mimir-continuous-test`:
1. `MimirContinuousTestNotRunning` firing when the test is not running properly
2. `MimirContinuousTestFailed` firing when the testing tool is running, but assertions are failing
Severity is `warning` for now, but plan is to raise it after gaining some confidence on the tool.
N/A
=> Added mimir-continuous-test alerts

operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin/dashboards/compactor.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Adds two panels to the compactor dashboard:
- Longest time since last successful run
- a stat panel which displays the amount of time since the most recent successful execution of the compactor replica with the longest delay (per compaction interval). 
- Last successful run per-compactor replica
-  a table panel which displays the compactor replicas, and for each, indicates the status of their most recent compaction.
- N/A
- N/A
=> mimir-mixins: dashboards: compactor: Add "last successful run" compactor panels

docs/sources/migration-guide/migrating-from-cortex.md
Notes the importance of setting the `ingester.ring.num_tokens` value for users migrating from the Cortex Helm chart using the default values. The Helm chart specifies 512 tokens by default but the GRafana Mimir Helm chart uses the Grafana Mimir process default.
=> Include note about `-ingester.ring.num_tokens`

go.mod, go.sum, vendor/github.com/prometheus/prometheus/template/template.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/old_head_chunks.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/modules.txt
This commit bumps the vendored version of mimir-prometheus to bring the
changes included in https://github.com/grafana/mimir-prometheus/pull/196
These changes affect the TSDB Head replay of memory mapped chunks
ensuring that if a memory mapped chunk is read but it has an unknown
encoding, it is discarded rather than returning a corruption error.
This change is a previous step towards releasing out of order support,
where a new chunk encoding is being released. 
This previous step would allow us to rollback between versions if we 
ever get to that point.
No related issue, simply bumping a vendored version.
=> Bump mimir prometheus to discard unknown chunks

CHANGELOG.md, operations/mimir-tests/test-disable-chunk-streaming-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir-tests/test-query-sharding-generated.yaml, operations/mimir-tests/test-shuffle-sharding-generated.yaml, operations/mimir-tests/test-storage-azure-generated.yaml, operations/mimir-tests/test-storage-gcs-generated.yaml, operations/mimir-tests/test-storage-s3-generated.yaml, operations/mimir/alertmanager.libsonnet
By default, we enforce a replication factor of 3 which the Alertmanager inherits. To ensure quorum is not lost during disruptions we set a pod disruption budget of `withMaxUnavailable(1)`.
N/A
=> Alertmanager: Set a Pod Disruption Budget

Makefile
This PR simplifies `push-multiarch-mimir` target to not build per-platform images individually, as `cmd/mimir/Dockerfile` doesn't `RUN` many commands that could fail under emulation.
(This is reason why we build per-platform images in `push-multiarch-build-image` first. If we only used multiarch build command, and it failed, restarting it would restart all platform builds. But in `push-multiarch-mimir` this risk is tiny.)
Note that `make push-multiarch-mimir` currently only works when `docs/Makefile` is deleted first. (https://github.com/grafana/mimir/issues/1646)
=> Simplify push-multiarch-mimir target.

cmd/mimir-continuous-test/main.go, pkg/continuoustest/manager.go
This is a simple PR to address the last TODO in `mimir-continuous-test`: allow to configure the tests run interval.
N/A
=> Allow to configure tests run interval in mimir-continuous-test

operations/mimir-mixin/docs/playbooks.md, pkg/continuoustest/client.go, pkg/continuoustest/client_test.go, pkg/continuoustest/write_read_series.go, pkg/continuoustest/write_read_series_test.go
In `mimir-continuous-test` tool we want to run queries both with results cache enabled (default) and disabled. This way we can both spot issues that could happen with result is loaded from cache (eg. bad results cached) and not loaded from cached (eg. data gets corrupted long after ingestion, eg. during compaction).
This PR runs each test query twice, both with cache enabled and disabled.
**Out of scope of this PR** (will be done in follow up PRs):
- Documentation
- CHANGELOG
N/A
=> Run each query both with results cache enabled and disabled in mimir-continuous-test tool

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin/dashboards/alertmanager.libsonnet
With the new Alertmanager architecture, we can have failure scenarios where requests fail at a distributor-level but not at an "instance level". In its current state, the dashboard can be deceiving.
This PR adds visibility to the `handleRequest` method of the distributor which is in charge of handling _all_ relevant requests before they get shipped to the relevant Alertmanager instances.
N/A
=> Mixin/Dashboards: Add Alertmanager Distributor QPS and Latency

CHANGELOG.md, operations/mimir-mixin/docs/playbooks.md
Both `MimirRequestErrors` and `MimirRequestLatency` can fire for Alertmanager components. Add a brief explanation of where/what to look when this happens for the Alertmanager.
N/A
=> Mixin/Playbooks: Add Alertmanager suggestions for `MimirRequestErrors` and `MimirRequestLatency`

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/alertmanager/multitenant.go
Improves CLI description of `-alertmanager.storage.retention`
Fixes #1701
Do I need a changelog entry for this?
=> Mimir: Improve documentation for `-alertmanager.storage.retention`

CHANGELOG.md, integration/single_binary_test.go, pkg/frontend/querymiddleware/results_cache.go
We add `component` label to all memcached clients, except the results cache. This makes memcached client metrics clash when running in single binary mode and results cache is enabled, leading to a panic. This PR fixes it.
Fixes #1698
=> Fixed panic when Mimir is running in single binary mode and results cache is enabled

operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin/dashboards/compactor.libsonnet
Attempts to improve compactor dashboard query readability through use of different Jsonnet syntax.
In some queries:
- Added whitespace
- Used key-map string replacement
No functionality was changed.
If this is deemed helpful, I can make similar changes in other dashboards, gradually.
=> mimir-mixins: dashboards: improve compactor dashboard query readability

.github/workflows/publish-technical-documentation.yml, .github/workflows/publish.yml, .github/workflows/test-build-deploy.yml
Pushes to main are published to the `next` directory and release
branches and tags are published to the a versioned directory.
The `Determine technical documentation version` step coerces the git
reference into a version string of the form `v.<major>.<minor>` which
matches the versioned documentation structure on the website.
Release branches are published to a `v.<major>.<minor>.x` directory 
on the website and the website orders these directories and determines
what is to become the "latest" directory automatically.
Release branches are only published if there is a release tag that, when
coerced using the same process as for the technical documentation version,
matches the release branch version. This ensures that docs on release branches
are only published after the actual release has …
=> Sync latest docs to support backporting documentation

pkg/continuoustest/write_read_series.go
At start, `mimir-continuous-test` tool catch up writes from last written samples (if it's not older than 50m ago). When doing this catch up, we may hit the ingestion rate limit on Mimir side (depends on the actual limits set). The testing tool already handles the case the write fails with a 4xx error, but it would be better to avoid it if possible. In this PR I'm introducing a simple write rate limit to reduce the likelihood we hit the rate limit on Mimir side.
N/A
=> Add write rate limit to mimir-continuous-test

.github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin-tests/.gitignore, operations/mimir-mixin-tests/run.sh, operations/mimir-mixin-tests/test-custom-labels-asserts.sh, operations/mimir-mixin-tests/test-custom-labels.libsonnet, operations/mimir-mixin-tools/screenshots/Dockerfile, operations/mimir-mixin-tools/screenshots/run.sh, operations/mimir-mixin-tools/serve/run.sh, operations/mimir-mixin/.gitignore, operations/mimir-mixin/alerts.libsonnet, operations/mimir-mixin/alerts/alertmanager.libsonnet, operations/mimir-mixin/alerts/alerts-utils.libsonnet, operations/mimir-mixin/alerts/alerts.libsonnet, operations/mimir-mixin/alerts/blocks.libsonnet, operations/mimir-mixin/alerts/compactor.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/recording_rules.libsonnet, operations/mimir-mixin/scripts/lint-playbooks.sh, operations/mimir-tests/build.sh, operations/mimir/README.md, operations/mimir/getting-started.sh
We just merged #1651 which adds support to customise the cluster label. We already had config options to customise the instance (eg. pod) and node labels.
However, are we relatively confident the labels customization is applied everywhere? It's very difficult to spot during code reviews, so I though if we could add any test. In this PR I'm proposing to introduce a basic test (in bash) checking if, after renaming cluster/instance/node labels, they're still used somewhere.
Thanks to these tests, I've spot several issues that I'm fixing in this PR too. In theory this PR should be a noop when mixin is compiled with default config, but you will see diff in `operations/mimir-mixin-compiled/alerts.yaml`. Reason is that fix these issues I changed the usage of hardcoded `instance` label with the …
=> Test and fix custom labels support in mixin

pkg/querier/blocks_store_queryable.go
Much like #1717, this mutex is unused.
=> Remove unused mutex from LabelNames method

RELEASE.md
I propose to publish the release schedule. 2.1.0 release has been delayed by 1 week because of conflicting GrafanaFest.
N/A
=> Publish release schedule

CHANGELOG.md, docs/sources/operators-guide/tools/mimir-continuous-test.md
I've completed the planned work on `mimir-continuous-test`. In this PR I'm adding a CHANGELOG entry and documentation page.
N/A
=> Added mimir-continuous-test doc and CHANGELOG entry

CHANGELOG.md, RELEASE.md, operations/mimir-rules-action/Dockerfile, operations/mimir-rules-action/README.md, operations/mimir-rules-action/action.yaml, operations/mimir-rules-action/entrypoint.sh
As discussed in https://github.com/grafana/cortex-rules-action/pull/21, in this PR I'm importing `mimir-rules-action` to the Mimir repo. The imported code and README is exactly the content of https://github.com/grafana/cortex-rules-action/pull/21, so I would suggest to review it there to see the actual diff compared to `cortex-rules-action`.
Plan is:
- Get this PR merged
- Switch Grafana Labs internal usage from `cortex-rules-action` to `mimir-rules-action`, to test it
- Deprecate `grafana/cortex-rules-action`
N/A
=> Imported mimir-rules-action

pkg/compactor/bucket_compactor.go, pkg/compactor/bucket_compactor_e2e_test.go, pkg/compactor/bucket_compactor_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go
Remove duplicate cortex_compactor_garbage_collected_blocks_total metric. It looks like the places that have updated it are updating cortex_compactor_blocks_marked_for_deletion_total. We should be able to remove it safely 
Fixes https://github.com/grafana/mimir/issues/105
=> Remove duplicate cortex_compactor_garbage_collected_blocks_total metric

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, operations/mimir-tests/test-defaults-generated.yaml, operations/mimir-tests/test-disable-chunk-streaming-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir-tests/test-query-sharding-generated.yaml, operations/mimir-tests/test-shuffle-sharding-generated.yaml, operations/mimir-tests/test-storage-azure-generated.yaml, operations/mimir-tests/test-storage-gcs-generated.yaml, operations/mimir-tests/test-storage-s3-generated.yaml, operations/mimir/store-gateway.libsonnet, pkg/storage/tsdb/caching_config.go
=> Changed -blocks-storage.bucket-store.chunks-cache.attributes-in-memory-max-items default from 0 to 50000

CHANGELOG.md, operations/mimir/README.md, operations/mimir/config.libsonnet, operations/mimir/multi-zone.libsonnet, operations/mimir/store-gateway.libsonnet
A tiny follow up on top of #1730. We're used to name the store-gateway with the dash in between and so the conversion to config options is `store_gateway`.
N/A
=> Rename config option introduced in PR 1730

development/tsdb-blocks-storage-s3/config/alertmanager.yaml, development/tsdb-blocks-storage-s3/config/mimir.yaml
This enables an alert sent from the Ruler to the Alertmanager not to fail when there is no configuration on the Alertmanager side. Instead, an alertmanager instance with the fallback configuration would be applied.
*Do I need a changelog entry?*
Fixes N/A
=> Dev Docker compose: Add `fallback_config_file` to the Alertmanager config

pkg/ruler/remotequerier.go
Preallocate slice capacity when converting `query-frontend` vector response in remote evaluation mode. 
Fixes N/A
=> ruler: preallocate slices when converting remote querier response

docs/sources/operators-guide/visualizing-metrics/installing-dashboards-and-alerts.md
Installing `jb` and `mixtool` per the docs prints a deprecation warning
and updates go.mod and go.sum files, if run from a go project. Update
the docs to use the recommended `go install` with a version.
Signed-off-by: Josh Carp <jm.carp@gmail.com>
=> Change mixtool and jb installation instructions

CHANGELOG.md, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This restores a tiny change from cortex-jsonnet to allow custom datasources for compiled dashboards: https://github.com/grafana/cortex-jsonnet/pull/407.
=> Allow custom data source in mixin dashboards.

docs/sources/tutorials/play-with-grafana-mimir/docker-compose.yml
Signed-off-by: Chee Hau Lim <ch33hau@gmail.com>
Fix `minio` in playground won't be started successfully
Fixes #1740
=> Update minio docker compose in the playgraound to clear the existing docker command

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/ingester/ingester.go, pkg/storage/tsdb/config.go
The default behavior remains unchanged.
We will use this new configuration flag to slowly enable the new chunk disk mapper in our production environments, without enabling the chunk write queue yet. Once it has been enabled everywhere and we are confident that it doesn't cause any issues we can remove the old chunk disk mapper from `mimir-prometheus` and we can also start to slowly enable the chunk write queue.
=> add option to use new (current in upstream Prometheus) chunk disk mapper

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/dskit/services/basic_service.go, vendor/github.com/grafana/dskit/spanlogger/spanlogger.go, vendor/github.com/hashicorp/memberlist/config.go, vendor/github.com/hashicorp/memberlist/label.go, vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/peeked_conn.go, vendor/github.com/hashicorp/memberlist/security.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/transport.go, vendor/github.com/hashicorp/memberlist/util.go, vendor/modules.txt
=> Update to latest dskit and memberlist fork

CHANGELOG.md, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/alertmanager-resources.libsonnet, operations/mimir-mixin/dashboards/alertmanager.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/reads-networking.libsonnet, operations/mimir-mixin/dashboards/reads-resources.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet, operations/mimir-mixin/dashboards/ruler.libsonnet, operations/mimir-mixin/dashboards/writes-networking.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet
The gateway component seems to be an enterprise component, so groups
that aren't running enterprise shouldn't need the empty panels and rows
in their dashboards. This patch adds a flag to drop gateway-related
widgets from the mixin dashboards.
Signed-off-by: Josh Carp <jm.carp@gmail.com>
=> dashboards: add flag to skip gateway

CHANGELOG.md, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/scheduler_processor_test.go, pkg/querier/worker/util.go, pkg/scheduler/queue/user_queues.go, pkg/scheduler/queue/user_queues_test.go
This is an approach alternative to #1742, to gracefully shutdown querier when using query-scheduler, which also supports query cancellation and querier shutdown when there's no enqueued query for the given querier.
The idea in this PR is pretty simple:
- Run the querier worker's loop in a dedicated context, called the "execution context"
- Cancel the execution context when the worker context gets cancelled (ie. querier is shutting down) **and** there's no inflight query execution (otherwise wait the inflight query to terminate)
When the querier shutdowns (at the beginning of the shutdown process) it sends a notification to the scheduler (see `schedulerProcessor.notifyShutdown()`). I did a small change in the scheduler's queue, to make sure it never forwards a new query to a shutting down …
=> Gracefully shutdown querier when using query-scheduler

pkg/ingester/ingester.go
Relates to https://github.com/grafana/mimir-ooo/issues/15
Make sure to always enable overlapping blocks if oooallowance is greater than 0
=> Enable overlapping blocks if ooo support is enabled

pkg/ingester/ingester.go
We identified a possible issue with the order of the conditions and we
think that checking that the ooo allowance is configured first makes
more sense.
Also added a TODO for a further optimization if we get too many too old
samples.
=> Update condition order in the ingester fast path

go.mod, go.sum, vendor/modules.txt
We merged https://github.com/jesusvazquez/thanos/pull/1 so now we can
update Thanos dependency to the latest commit of the out of order branch
in thanos fork.
=> Update thanos vendored dependency for ooo support

CHANGELOG.md, pkg/querier/worker/frontend_processor.go, pkg/querier/worker/frontend_processor_test.go, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/util.go
Like #1756 but for the case Mimir is running without query-scheduler.
Manual tests I've done:
- Shutdown a querier when there's no query running or enqueued --> terminates immediately
- Shutdown a querier when there's an inflight query only --> waits until the query completes and then terminate
- Shutdown a querier when there's an inflight query running and enqueued requests in the frontend --> waits until the query completes and then terminate. The enqueued requests stay in the frontend. If you restart the querier, it will process the enqueued requests
N/A
=> Graceful shutdown querier without query-scheduler

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/continuous-test.libsonnet, pkg/continuoustest/manager.go
I think I've been too much aggressive when I've set 1m default test interval for `mimir-continuous-test`. I think running the test every 5m is perfectly fine.
N/A
=> Increased default -tests.run-interval from 1m to 5m

pkg/querier/worker/frontend_processor_test.go, pkg/querier/worker/scheduler_processor_test.go, pkg/querier/worker/util.go
I've seen a flaky test:
```
--- FAIL: TestFrontendProcessor_processQueriesOnSingleStream (0.00s)
--- FAIL: TestFrontendProcessor_processQueriesOnSingleStream/should_immediately_return_if_worker_context_is_canceled_and_there's_no_inflight_query (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xfd44af]
goroutine 28 [running]:
testing.tRunner.func1.2({0x1082800, 0x18fe1f0})
/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x1082800, 0x18fe1f0})
/usr/local/go/src/runtime/panic.go:1047 +0x266 …
```
=> Fix flaky tests on querier graceful shutdown

.github/workflows/test-build-deploy.yml, Makefile, mimir-build-image/Dockerfile
This PR updates build-image base to `golang:1.17.8-bullseye` (Bullseye is latest [stable Debian release](https://www.debian.org/releases/)), and adds `skopeo` package to build-image (only available in bullseye and unstable).
This PR also updates Github Action jobs to use `ubuntu-latest` as a machine type.
> Note: The -latest virtual environments are the latest stable images that GitHub provides, and might not be the most recent version of the operating system available from the operating system vendor.
(from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on)
This PR is a preparation for next PR, which will build and push multiarch docker images to the repository. Update to `ubuntu-latest` is needed to make Docker's Buildx and QEMU …
=> Update build image and GitHub workflow

pkg/api/handlers.go
This PR removes duplicated `/api/v1/read` querier handler and explicitly sets allowed HTTP method. 
Fixes N/A
=> api: remove duplicated remote read querier handler

operations/k6/load-testing-with-k6.js
When using `K6_HA_REPLICAS > 1`, Mimir will accept all HTTP calls but a
part of those call will receive a status code `202`. The following
commit makes this status code as expected otherwise user receive the
following error:
```
reads_inat write (file:///.../mimir-k6/load-testing-with-k6.js:254:8(137))
reads_inat native  executor=ramping-arrival-rate scenario=writing_metrics source=stacktrace
ERRO[0015] GoError: ERR: write failed. Status: 202. Body: replicas did not mach, rejecting sample: replica=replica_1, elected=replica_0
```
At the end of the benchmark summary display errors:
```
✗ write worked
↳  20% — ✓ 23 / ✗ 92
```
Example of load testing:
```shell
./k6 run load-testing-with-k6.js \
-e K6_SCHEME="https" \
-e K6_WRITE_HOSTNAME="${mimir}" \
-e K6_READ_HOSTNAME="${mimir}" \
-e …
```
=> K6: Take into account HTTP status code 202

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/dskit/ring/http.go, vendor/github.com/grafana/dskit/ring/lifecycler.go, vendor/github.com/grafana/dskit/ring/lifecycler_metrics.go, vendor/github.com/grafana/dskit/ring/ring.go, vendor/modules.txt
In this PR I'm upgrading dskit to get https://github.com/grafana/dskit/pull/162
Part of #1750
=> Upgrade dskit

CHANGELOG.md, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go, pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
As discussed in #1750, in this PR I propose to not export Alertmanager counter metrics having both `user` and `integration` labels when their value is 0.
Currently these metrics are exposed for any integration, even if an user doesn't use that integration. Alertmanager supports 10 receiver integrations, and this leads to high cardinality metrics when Alertmanager is handling a large number of tenants. For example, if you run 3 Alertmanager replicas, you have 10k tenants, and each tenant configures 2 integrations, before the change we have in total `3 * 10k * 10 = 300k` metrics, while after the change we have `3 * 10k * 2 = 60k` metrics.
Part of #1750
=> Do not export per user and integration Alertmanager metrics when value is 0

.github/workflows/test-build-deploy.yml, integration/e2emimir/services.go
We're trying to find out why integration tests are flaky. This PR logs version of Mimir loaded into Docker and enables debug log for distributor.
Flaky runs:
- https://github.com/grafana/mimir/runs/6228928597?check_suite_focus=true
- https://github.com/grafana/mimir/runs/6229008323?check_suite_focus=true
=> Print version+arch of Mimir loaded to Docker.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/query.go
Continuing my effort to reduce cardinality of metrics exported by Mimir, I propose to remove the following metrics. They're not used in any of our dashboards or alerts, not even manually queried at Grafana Labs in recent times.
- `cortex_distributor_ingester_queries_total`
- `cortex_distributor_ingester_query_failures_total`
Part of #1750
=> Remove unused metrics cortex_distributor_ingester_queries_total and cortex_distributor_ingester_query_failures_total

CHANGELOG.md, operations/mimir/multi-zone.libsonnet
Allow customizing mimir cli flags per zone for the store gateway.
Copied the same solution as we have for ingesters.
Fixes N/A. Internal request to be able to turn off some flag for testing an individual store gateway zone.
-  krajo: this level of detail is not documented for ingesters either
=> Add support for store_gateway_zone args

CHANGELOG.md, pkg/storegateway/sharding_strategy.go, pkg/storegateway/sharding_strategy_test.go
This PR adds a protection to store-gateway to not drop all blocks if unhealthy in the ring, as proposed in #1805. There's still 1 case not addressed in this PR which is when the store-gateway is removed from the ring by another instance, due to the auto-forget feature (it happens after 10x hearbeat timeout periods, so it's less likely to happen compared to the case covered in this PR).
To fix the auto-forget case I need to do some refactoring first, so I will do the work in separate PRs.
Part of #1805
=> Add protection to store-gateway to not drop all blocks if unhealthy in the ring

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
The metrics `cortex_distributor_ingester_appends_total` and `cortex_distributor_ingester_append_failures_total` are quite high cardinality, but we're **not** using them (neither in dashboards, alerts or manual queries over last 30d at Grafana Labs). I'm wondering if we can safely just drop them.
My main argument is that in case of distributor failures you won't look at these metrics, but logs to get more insights about what's going on. Otherwise, is there any other use case where these metrics could be useful?
**Draft** because I want to ear opinions first.
Part of #1750
=> Removed cortex_distributor_ingester_appends_total and cortex_distributor_ingester_append_failures_total unused metrics

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/mimir/modules.go
I recently noticed we have `clientConfig` in `Ingester` but that's unused. I think it's a left over from chunks storage. We can safely remove it.
N/A
=> Chore: remove unused clientConfig from ingester

pkg/storegateway/bucket.go, pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_test.go
In this refactoring PR I'm forcing the removal of all blocks from `BucketStore` when it gets closed. To clearly see all places where it gets closed and signal the logic change, I've renamed `BucketStore.Close()` to `BucketStore.RemoveBlocksAndClose()`.
Given the current state of the store-gateway code, this change is expected to be a no-op. The reason is that we currently close the `BucketStore` only if it's empty (so there are no blocks) in `closeEmptyBucketStore()`. However, in a next PR I would like to change such logic and let close the `BucketStore` regardless it's empty or not, letting the `BucketStore` taking care of removing all blocks (releasing their resources) when it gets closed.
Part of #1805
=> Refactoring: force removal of all blocks when BucketStore is closed

pkg/storegateway/bucket_index_metadata_fetcher.go, pkg/storegateway/bucket_index_metadata_fetcher_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/sharding_strategy.go
To ease the resolution of #1805, I need to get to the point `ShardingStrategy.FilterUsers()` is only called in a single place inside the store-gateway. This PR does a refactoring to achieve it.
**A bit of history:**
`BucketStore` was originally vendored from Thanos and we didn't have control over it. Since blocks were not removed on `BucketStore.Close()`, before closing the `BucketStore` we had to call `BucketStore.SyncBlocks()` and make sure `SyncBlocks()` was removing all blocks.
Since we need to close a `BucketStore` for a tenant only when that tenant doesn't belong to the store-gateway shard anymore, to do achieve it we did some hacks to have the `MetadataFetcher` returning "no blocks" when the tenant wasn't belonging to the shard.
To do it we did introduce the following logic, …
=> Refactoring: simplify FilterUsers() logic in store-gateway

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, go.mod, pkg/ruler/remotequerier.go
Adapts ruler remote querier to make use of dskit `grpcclient.Config`, allowing to override, among others, maximum received/send message size options.
Fixes N/A
=> ruler: make use of dskit `grpcclient.Config` on remote evaluation client

operations/mimir/README.md
Without this example change, the rendering of the `mimir` library doesn't work properly.  Here we include the needed import statement to ensure that the object is rendered as desired.
Relates to #1369
=> Include `import` in jsonnet snippets

CHANGELOG.md, pkg/storegateway/bucket_index_metadata_fetcher_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/gateway_test.go, pkg/storegateway/sharding_strategy.go, pkg/storegateway/sharding_strategy_test.go
This PR should close the work to fix #1805. The change is minimal, most of code changes are tests: `ShardingStrategy.FilterUsers()` now can also return `error`. In case of error (store-gateway instance is unhealthy or missing in the ring) it will skip the blocks synching and will retry later. When the store-gateway instance will be healthy again (or re-registered to the ring) the ring topology will change and this will trigger another blocks sync.
Fixes #1805
=> Do not drop blocks in the store-gateway if missing in the ring

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/dskit/ring/basic_lifecycler.go, vendor/github.com/grafana/dskit/ring/lifecycler.go, vendor/modules.txt
In this PR I'm just upgrading dskit to get https://github.com/grafana/dskit/pull/165.
Part of #1766
=> Upgraded dskit to fix temporary partial query results when shuffle sharding is enabled and hash ring backend storage is flushed / reset

CHANGELOG.md, pkg/mimir/mimir.go, pkg/mimir/mimir_test.go
Allows other targets to start up even if an invalid alertmanager configuration
is passed in.
Fixes #1784
=> Alertmanager: Do not validate alertmanager configuration if it's not running.

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json, operations/mimir-mixin/dashboards/top-tenants.libsonnet
Adds the following rows to the "Top tenants" dashboard:
- By samples rate growth
- By discarded samples rate
- By discarded samples rate growth
These queries are useful for determining what tenants are potentially putting excess
load on distributors and ingesters (and if it increased recently).
=> Mixin: Additions to Top tenants dashboard regarding sample rate and discard rate.

pkg/compactor/compactor_test.go
Open and close files concurrently in compactor unit tests to expose bugs
that implicitly rely on ordering.
Exposes bugs such as https://github.com/prometheus/prometheus/pull/10108
=> Use concurrent open/close operations in compactor unit tests

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin/dashboards/tenants.libsonnet
Whilst diagnosing a recent issue, we thought it would be useful to show the
current ingestion rate limit for the tenant. As the limit is applied to
`cortex_distributor_received_samples_total`, the limit is shown on the panel
which displays this metric. ("Distributor samples received (accepted) rate").
Also added `ruler_max_rule_groups_per_tenant` while in the area.
We don't currently display the number of exemplars in storage on the dashboard
anywhere, so cannot add `max_global_exemplars_per_user` right now.
=> Mixin: Show ingestion rate limit and rule group limit on Tenants dashboard.

operations/mimir/querier.libsonnet, operations/mimir/query-frontend.libsonnet, operations/mimir/query-scheduler.libsonnet
This change extracts some of the jsonnet used to build query deployments
(querier, query-scheduler, query-frontend) such that it is easier to deploy
secondary query paths. The use case for this is primarily to develop a
query path deployment for ruler remote-evaluation, but there may be other
use cases too.
=> Jsonnet: Preparatory refactoring to simplify deploying parallel query paths.

pkg/api/api.go, pkg/api/handlers.go, pkg/frontend/querymiddleware/results_cache.go, pkg/mimir/modules.go
In this PR:
- Reference 'monolithic mode' instead of 'single binary' in logs and code.
- Lower "Worker address is empty in single binary mode" log to info, because I've seen several new adopters being confused by that (it's not really an issue, the automatic config typically works). I've also rephrased the log message to make it more clear about what's going on.
N/A
=> Reference 'monolithic mode' instead of 'single binary' in logs

CHANGELOG.md, operations/mimir/continuous-test.libsonnet
I would like to relax the `mimir-continuous-test` pressure when deployed with Jsonnet, based on the experience running it at Grafana Labs.
N/A
=> Relax mimir-continuous-test pressure when deployed with Jsonnet

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-config.json, operations/mimir-mixin-compiled/dashboards/mimir-object-store.json, operations/mimir-mixin-compiled/dashboards/mimir-overrides.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-scaling.json, operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/jsonnetfile.lock.json
The current dashboards offer the possibility to select a data source
among all prometheus data sources in the organization. Depending on the
number of data sources the list could be rather big (>10). Not all data
sources host Mimir metrics as such listing them is not helpful for the
users.
To be able to use this enhancement it is needed to merge the following PR https://github.com/grafana/jsonnet-libs/pull/774 as well as update jsonnetfile.lock.json
The error `RUNTIME ERROR: function has no parameter datasource_regex` is expected until then.
=> Allow custom data source regex in mixin dashboards

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, docs/sources/operators-guide/tools/mimirtool.md, operations/mimir-tests/test-defaults-generated.yaml, operations/mimir-tests/test-disable-chunk-streaming-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir-tests/test-query-sharding-generated.yaml, operations/mimir-tests/test-shuffle-sharding-generated.yaml, operations/mimir-tests/test-storage-azure-generated.yaml, operations/mimir-tests/test-storage-gcs-generated.yaml, operations/mimir-tests/test-storage-s3-generated.yaml, operations/mimir/distributor.libsonnet, operations/mimir/ruler.libsonnet, pkg/distributor/distributor.go, pkg/ingester/ingester_ring.go
In this I'm deprecating `-distributor.extend-writes` and setting it always to false, as proposed in #1854.
Fixes #1854
=> Deprecate -distributor.extend-writes and set it always to false

.github/workflows/publish-technical-documentation-next.yml
I assumed this was already done but the GitHub docs confirm that it is
required.
https://docs.github.com/en/github-ae@latest/actions/using-workflows/about-workflows#about-workflows.
This also configures `workflow_dispatch` so we can manually trigger the sync in the future.
=> Checkout the repository as part of the documentation sync

operations/mimir/config.libsonnet
While reviewing https://github.com/grafana/mimir/pull/1870, I reliased there are a couple of unused jsonnet config options for alertmanager. In this PR I'm removing them to cleanup the config.
N/A
=> Chore: cleanup unused alertmanager config in Mimir jsonnet

CHANGELOG.md, Makefile, operations/mimir-mixin-compiled/rules.yaml, operations/mimir-mixin/recording_rules.libsonnet, tools/check-rules.sh
This PR splits mimir_queries rule group into two, so that each group has less than 20 rules. This PR also adds check for number of rules per group, and fails if there are too many.
=> Split mimir_queries rule group so that it doesn't have more than 20 rules

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/blocks.libsonnet, operations/mimir-mixin/docs/playbooks.md
When store-gateways are overscaled some replicas might end up without any blocks sharded to them. This PR adds a warning alert to the monitoring mixin that detects this case.
=> Add alert for store-gateways without blocks

docs/sources/operators-guide/configuring/configuring-custom-trackers.md
=> Docs: Explain the runtime override of active series matchers

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/block/block.go, vendor/github.com/thanos-io/thanos/pkg/cache/groupcache.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/cacheutil.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/redis_client.go, vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go, vendor/modules.txt
Update our vendor of Thanos to pull in the most recent changes to the
Memcached client. In particular, these changes prevent the client from
starting many goroutines as part of batching before they are able to
make progress.
=> Update to latest Thanos for Memcached fixes

CHANGELOG.md, pkg/ingester/user_tsdb.go
While investigating #1891, I've noticed this log in each integration test:
```
2022-05-19T10:36:54.4321365Z 10:36:13 mimir: level=error ts=2022-05-19T10:36:13.797571821Z caller=ingester.go:1542 user=anonymous msg="failed to update cached shipped blocks after shipper initialisation" err="failed to read /tmp/mimir/tsdb/anonymous/thanos.shipper.json: open /tmp/mimir/tsdb/anonymous/thanos.shipper.json: no such file or directory"
```
When a new tenant TSDB and its blocks shipper are created in a ingester, there's no shipping meta file yet. We handled this case in the code, but error returned by `shipper.ReadMetaFile()` is wrapped since #1257: we need to unwrap it to correctly detect if it's a `os.ErrNotExist` error.
_I manually tested the change to ensure it works as expected now._
N/A
=> Fixed deceiving error log "failed to update cached shipped blocks after shipper initialisation"

integration/ruler_test.go
When running `TestRulerEvaluationDelay` I got it failing with this error:
```
ruler_test.go:314:
Error Trace:	ruler_test.go:314
Error:      	Not equal:
expected: 20
actual  : 18
Test:       	TestRulerEvaluationDelay
```
Reason is that there's a timing issue in the way we check the number of rule evaluations run (metric: `cortex_prometheus_rule_evaluations_total`). The tiny change in this PR ensures we always wait for 1 more evaluation, which should fix the flakyness occurring when the failing assertion is on the last sample (expected value `20`).
N/A
=> Fix TestRulerEvaluationDelay flakyness

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet, operations/mimir-mixin/docs/playbooks.md
The alert `MimirRulerMissedEvaluations` reports an incorrect value. It reports the rate of missed evaluations (which is a number from 0 to 1) as the percentage of missed evaluations (which should be a number from 0 to 100).
Also add a playbook for it, since that was missing.
=> Fix `MimirRulerMissedEvaluations` text and add playbook

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
do not trigger `MimirAllocatingTooMuchMemory` or `EtcdAllocatingTooMuchMemory` alerts if no container limits are supplied
Modifies `MimirAllocatingTooMuchMemory` and `EtcdAllocatingTooMuchMemory` to ignore container which have no limit defined.    
=> fix(mixin): do not trigger TooMuchMemory alerts if no container limits are supplied

integration/e2emimir/services.go
We can revert the distributor log level back to `warn` (changed to `debug` in https://github.com/grafana/mimir/pull/1793) because the integration tests issue has been spot and fixed in https://github.com/grafana/mimir/pull/1891.
N/A
=> Revert distributor log level to warn in integration tests

pkg/querier/querier.go, pkg/querier/querier_test.go
While reviewing #1909 I was checking if we have a validation for `-querier.query-store-after`. We do, but I think we can improve a bit the error message, which is what I'm proposing in this PR.
N/A
=> Improved error returned by -querier.query-store-after validation

docs/sources/operators-guide/running-production-environment/production-tips/index.md
While giving support to a community user, we found out we're not recommending fast disks for ingesters and store-gateways, but we should.
Fixes #1792
=> Docs: recommend fast disks for ingesters and store-gateways

operations/mimir-mixin-tools/screenshots/Dockerfile, operations/mimir-mixin-tools/screenshots/package-lock.json, operations/mimir-mixin-tools/screenshots/package.json
Running `make mixin-screenshots` on a arm64 machine fails with the following error when building `mixin-screenshots-taker` docker image:
```
npm notice
npm notice New minor version of npm available! 8.5.5 -> 8.10.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.10.0>
npm notice Run `npm install -g npm@8.10.0` to update!
npm notice
npm ERR! code 1
npm ERR! path /app/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! The chromium binary is not available for arm64.
npm ERR! If you are on Ubuntu, you can install with:
npm ERR!
npm ERR!  sudo apt install chromium
npm ERR!
npm ERR!
npm ERR!  sudo apt install chromium-browser
npm ERR!
npm ERR! …
```
=> mixin/tools: adapt screenshots dockerimage to support arm64

operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json, operations/mimir-mixin/dashboards/rollout-progress.libsonnet
The [mimir-distributed](https://github.com/grafana/helm-charts/tree/main/charts/mimir-distributed) creates stateful sets and deployments prefixed with the name of the helm chart release and "mimir-" (e.g. example-mimir-ingester, release-name-mimir-distributor)
The rollout progress dashboard does not account for these and is empty because of it.
This PR adds matchers around the sts and depl names.
=> mixin: Account for helm chart StatefulSets and Depl-s

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, operations/mimir-tests/test-defaults-generated.yaml, operations/mimir-tests/test-disable-chunk-streaming-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir-tests/test-query-sharding-generated.yaml, operations/mimir-tests/test-shuffle-sharding-generated.yaml, operations/mimir-tests/test-storage-azure-generated.yaml, operations/mimir-tests/test-storage-gcs-generated.yaml, operations/mimir-tests/test-storage-s3-generated.yaml, operations/mimir/config.libsonnet, operations/mimir/ingester.libsonnet, operations/mimir/shuffle-sharding.libsonnet, pkg/querier/querier.go
Use the same default value for ingester lookback as the "query ingesters
within" setting to reduce the number of things that need to be changed from their
defaults. This change also removes use of the
`-blocks-storage.tsdb.close-idle-tsdb-timeout` flag in jsonnet since the
value being used matches the default.
Follow up to #1915
=> Change shuffle sharding ingester lookback default config

CHANGELOG.md, operations/mimir-mixin/docs/playbooks.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/globalerror/errors.go, pkg/util/validation/errors.go, pkg/util/validation/errors_test.go, pkg/util/validation/limits.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
As a follow up of #1907, in this PR I'm improving error messages returned by `validation.ValidateMetadata()`. I've also changed the logic to not directly return a `httpgrpc` error, but a `ValidationError`, to keep it consistent with other validation functions.
N/A
=> Improved ValidateMetadata() errors

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
This PR adjusts `MimirGossipMembersMismatch`.
Alert is defined to compare number of memberlist members against number of alertmanager, compactor, distributor, ingester, querier, ruler and store-gateway jobs. Under normal operations, these numbers should match. During rollouts they often mismatch because of two reasons:
- memberlist_client_cluster_members_count relies on "leave cluster" message propagation, and may not be up to date
- jobs may be "up" before they had a chance to join the memberlist cluster
This is what it looks like on one of our clusters (diff between average memberlist_client_cluster_members_count and number of `up` metrics), with multizone setup for ingesters and store-gateways:
This PR extends "for" time before alert fires, and also modifies the expression to generate …
=> Make MimirGossipMembersMismatch less sensitive, and make it fire fewer alerts.

go.mod, go.sum, vendor/github.com/thanos-io/thanos/pkg/cache/groupcache.go, vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go, vendor/github.com/thanos-io/thanos/pkg/testutil/testutil.go, vendor/modules.txt
Update our vendor of Thanos so that memcache keys are grouped by the
server they are owned by before being split into batches.
Fixes #423
=> Update Thanos vendor for memcache improvements

cmd/mimir/main.go, pkg/util/fieldcategory/overrides.go, pkg/util/usage/usage.go
This PR moves the command line usage generation function into a separate package, and adds a function to set flag category overrides at runtime.
n/a
=> Move usage generation to separate package

CHANGELOG.md, docs/internal/contributing/README.md
- Documents the meaning of scope labels in CHANGELOG entries
- Updates changelog for #1934 
n/a
=> Document CHANGELOG scopes and update CHANGELOG for #1934

CHANGELOG.md, integration/querier_test.go, operations/mimir-mixin/docs/playbooks.md, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance_limits.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/ingester/user_tsdb.go, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go, pkg/util/globalerror/errors.go, pkg/util/limiter/query_limiter.go, pkg/util/validation/limits.go
Rephrases some limits errors, introduces the usage of error IDs, and adds playbooks similar to #1907
Error covered in this PR are ones in:
* `pkg/ingester/instance_limits.go `
* `pkg/ingester/limiter.go`
* `pkg/querier/blocks_store_queryable.go`
* `pkg/util/limiter/query_limiter.go`
n/a
=> Improve instance limits, ingester limits, query limiter, some querier errors

integration/backward_compatibility.go
Bumps backward compatibility testing after cutting release 2.1.0
=> Bump grafana/mimir image to 2.1.0 for backward compatibility testing

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
In similar spirit as https://github.com/grafana/mimir/pull/1913
The pods created by the helm chart follow a format of
`<helm_release_name>-mimir-<ingester|distributor|...>`.
This is a problem for all places that use the per_instance_label for
matching. The per_instance_label is mostly used in aggregations (sum by
(pod), count by (pod), ...). The networking panels are the only ones
that use it for matching.
=> Make networking panels pod matchers work with helm chart

CHANGELOG.md, integration/query_frontend_test.go, operations/mimir-mixin/docs/playbooks.md, pkg/frontend/querymiddleware/limits.go, pkg/frontend/querymiddleware/querysharding_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/util/globalerror/errors.go, pkg/util/validation/errors.go, pkg/util/validation/errors_test.go, pkg/util/validation/limits.go, pkg/util/validation/validate.go
Following what we've done in https://github.com/grafana/mimir/pull/1907, https://github.com/grafana/mimir/pull/1919, https://github.com/grafana/mimir/pull/1888, in this PR I'm adding the "max query length" to the errors catalogue.
N/A
=> Add max query length error to errors catalog

.github/workflows/publish-technical-documentation-release.yml
Tags in the mimir repo follow the format `mimir-2.0.0`. The Github action to publish documentation expected them to be `mimir-v2.0.0`. This resulted in the docs for 2.1 not being published (2.0 were likely synced manually as part of the release).
=> Adjust the name of the tag expected by documentation publishing

CHANGELOG.md, docs/sources/tutorials/play-with-grafana-mimir/index.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/config.libsonnet
In https://github.com/grafana/mimir/issues/1642 we received this feedback:
> In several dashboard the row Gateway is usable only if the deployment also have cortex-gw
That's right and it's not the first time I find myself saying to an user "gateway panels are expected to be empty for you". I think the gateway panels are deceiving for any OSS user because they will not run the gateway, and even if they run a gateway it's unlikely to expose metrics expected by our dashboards.
For this reason, I propose to disable gateway panels by default, so that they don't end up in the compiled dashboards. Thoughts?
N/A
=> Dashboards: disable gateway panels by default

pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/helpers/helpers.go, pkg/storegateway/testhelper/testhelper.go, pkg/util/test/copy.go
We want to pull in the `indexheader` package from Thanos so that we can add some experimental alternative implementations of `BinaryReader`. In order to also pull in the unit tests for this package, we need the replacements for `e2eutil.Copy` and `e2eutil.CreateBlock`. This change does two things:
1. Copy in `e2eutil/copy.go` and fix it up accordingly.
2. Move `CreateBlock` into a package to avoid circular imports.
The PR is structured into 4 commits to make reviewing the changes to the copied files easier.
Fixes n/a
- n/a Tests updated
- n/a Documentation added
- n/a `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Preparation of e2eutils for Thanos indexheader unit tests.

.github/workflows/helm-release.yaml, operations/helm/cr.yaml
Implements releasing the mimir-distributed(-beta) chart from operations/helm/charts to:
- helm-charts repo (releases)
- helm-charts github pages (index.yaml)
Internal mimir-squad number 668
=> Release mimir-distributed-beta to helm-charts repo

.github/workflows/helm-release.yaml, operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/Chart.yaml, operations/helm/charts/mimir-distributed/README.md
Rename the chart back to mimir-distributed for simplicity.
Bump the version to 2.1.0-beta.1 , but no other changes to test that helm tools provide the protection against accidental use.
Enable releasing chart from main as test on branch was successful.
Internal squad 668
=> Prepare mimir beta chart release

pkg/ingester/shipper.go, pkg/ingester/shipper_test.go, pkg/storage/tsdb/upload.go, pkg/storage/tsdb/upload_test.go
This PR modifies Shipper to avoid doing local copy of a block (using hardlinks) before uploading the block. Shipper was also updating its own copy of meta.json file. This has been replaced with new `tsdb.UploadBlock` method which uploads `meta.json` file from in-memory structure instead of using meta.json file from disk.
Why cannot we update local `meta.json` file for block loaded by ingester? TSDB library tries to reload the blocks at some points. When updating local `meta.json` file, shipper deletes old version first and then uses Replace call from temp file to `meta.json`. If TSDB library tried to reload the blocks while `meta.json` is missing, it would unload the block from memory instead (and possibly load it again later when finding the block again).
This PR copies `block.Upload` …
=> Remove hardlinking in Shipper code.

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/Chart.yaml, operations/helm/charts/mimir-distributed/README.md, operations/helm/charts/mimir-distributed/templates/distributor/distributor-svc-headless.yaml, operations/helm/charts/mimir-distributed/values.yaml
Use DNS-lookup based grpc client-side load balancing for distributor requests.
This required adding a new, headless service to support the `dns:///` grpc resolver.
Fixes #1987
=> [helm] use grpc round robin for distributor clients

pkg/storegateway/indexheader/binary_reader.go
Mistakenly left two lines when updating the provenance for the file.
=> Fix binary_reader.go header text.

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/Chart.lock, operations/helm/charts/mimir-distributed/Chart.yaml, operations/helm/charts/mimir-distributed/README.md, operations/helm/ct.yaml
See also: https://github.com/grafana/helm-charts/pull/1438
=> Workaround to keep using old memcached bitnami chart for now

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/Chart.yaml, operations/helm/charts/mimir-distributed/README.md, operations/helm/charts/mimir-distributed/values.yaml
Disable `distributor.extend-writes` and `ingester.ring.unregister-on-shutdown` by default.
Note we will remove `distributor.extend-writes` in version 2.1, but I've left that out of this PR since we haven't bumped the image to 2.1 yet. 
Fixes https://github.com/grafana/helm-charts/issues/1313
=> [helm] disable unregister on shutdown

.github/workflows/helm-release.yaml
Enable helm chart publication from release-X.Y branches. The plan is to publish 2.1 by cherry picking the latest 2.1-beta.X to the `release-2.1` branch. This way all source for 2.1 will continue to live on the release-2.1 branch.
=> Publish helm charts from release branches

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin/dashboards/queries.libsonnet, operations/mimir-mixin/dashboards/ruler.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet
There were a couple of usages of intervals of 1m for the `rate()` function within the mixin dashboards. That may lead to flaky panels when the scrape interval is 30s or 1m.
This PR replaces hardcoded values of the interval with `$__rate_interval` which ensures the interval is 4 times the scrape interval.
=> Replace hardcoded intervals with $__rate_interval in dashboards

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/globalerror/errors.go
Following what we've done to the ingesters' instance limits in https://github.com/grafana/mimir/pull/1888, this PR does something similar for the distributors and adds their limit errors to the errors catalogue.
N/A
=> Standardise error messages for distributor instance limits

tutorials
See #1979. The `tutorials/` symlink cause `docker-compose` to not work correctly in some environments and it already caused troubles to few people. I suggest to remove that link. The [play with Grafana Mimir tutorial](https://grafana.com/tutorials/play-with-grafana-mimir/) already says to `cd docs/sources/tutorials/play-with-grafana-mimir/`.
Fixes #1979
=> Remove tutorials/ symlink

CHANGELOG.md, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir-tests/test-autoscaling.jsonnet, operations/mimir/autoscaling.libsonnet, operations/mimir/mimir.libsonnet
In this PR I'm adding querier autoscaler support to jsonnet. The support has been tested at Grafana Labs (where it's already in-use in production), so in this PR I'm basically upstreaming what it's currently used at Grafana Labs.
_I plan to write doc in a follow up PR._
The best way to review the jsonnet test diff is:
```console
diff operations/mimir-tests/test-query-sharding-generated.yaml operations/mimir-tests/test-autoscaling-generated.yaml
```
```diff
812d811
<   replicas: 6
850,851c849,850
<         - -querier.frontend-client.grpc-max-send-msg-size=419430400
<         - -querier.max-concurrent=16
---
>         - -querier.frontend-client.grpc-max-send-msg-size=104857600
>         - -querier.max-concurrent=8
925d923
<         - -querier.max-query-parallelism=240
929,931d926
< …
```
=> Add querier autoscaler support to jsonnet

.github/workflows/test-build-deploy.yml, Makefile, docs/internal/how-to-update-the-build-image.md, mimir-build-image/Dockerfile
Adds helm-docs to the `make doc` target.
The mimir build image is also updated for this to work with it.
The documentation about updating the build image is also updated with more info and Linux specifics.
N/A.
=> Include helm-docs in build and CI

.github/workflows/helm-ci.yml, docs/internal/contributing/README.md, docs/internal/contributing/contributing-to-helm-chart.md, operations/helm/charts/mimir-distributed/README.md, operations/helm/charts/mimir-distributed/README.md.gotmpl
Documentation follow up for the move of mimir-distributed helm chart from the helm-charts repo.
Relates to https://github.com/grafana/mimir-squad/issues/668
=> Update contributing guides for the helm chart

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/admin-api/admin-api-dep.yaml, operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml, operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/distributor/distributor-dep.yaml, operations/helm/charts/mimir-distributed/templates/gateway/gateway-dep.yaml, operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml, operations/helm/charts/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/charts/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/charts/mimir-distributed/templates/ruler/ruler-dep.yaml, operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/tokengen/tokengen-job.yaml, operations/helm/charts/mimir-distributed/values.yaml
Add `extraEnvFrom` capability to all Mimir services to enable injecting
secrets via environment variables.
Enable `-config.exand-env=true` option in all Mimir services to be able
to take secrets/settings from the environment and inject them into the
Mimir configuration file.
Fixes https://github.com/grafana/helm-charts/issues/1314
- [N/A] Tests updated  - no baseline yet
- [N/A] Documentation added - no baseline yet
=> helm: Add extraEnvFrom to all services and enable injection into mimir config

docs/sources/operators-guide/visualizing-metrics/installing-dashboards-and-alerts.md
I just went through the mimir-mixin installation instructions (using `jb`) and didn't work. This PR fixes it:
- Mention `jb init`
- Install `@main` because `jb` looks for `master` by default and we don't have `master` branch in Mimir
N/A
=> Docs: fix mimir-mixin installation instructions

CHANGELOG.md
We value a lot documentation, but we're not giving credit to its improvements in the CHANGELOG. I propose to make documentation a first class citizen in CHANGELOG.
N/A
=> Docs: make documentation a first class citizen in CHANGELOG

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/admin-api/admin-api-dep.yaml, operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml, operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/distributor/distributor-dep.yaml, operations/helm/charts/mimir-distributed/templates/gateway/gateway-dep.yaml, operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml, operations/helm/charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml, operations/helm/charts/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/charts/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/charts/mimir-distributed/templates/ruler/ruler-dep.yaml, operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/tokengen/tokengen-job.yaml, operations/helm/charts/mimir-distributed/values.yaml
Enables setting environment and env injection in one place for
mimir + nginx.
Relates to https://github.com/grafana/helm-charts/issues/1284
- [N/A] Documentation added - does not exists see: https://github.com/grafana/mimir/issues/1945
=> Helm: add global.extraEnv and global.extraEnvFrom

operations/mimir/common.libsonnet, operations/mimir/query-frontend.libsonnet, operations/mimir/query-scheduler.libsonnet
I need to create a "discovery" service in a downstream project. I would like to introduce a new `newDiscoveryService()` utility to do it, so that I can just reuse it like we do for other `newXXX()` functions.
_This PR is expected to be a no-op._
N/A
=> Chore: introduced newDiscoveryService() util in jsonnet

operations/mimir-tests/build.sh, operations/mimir/README.md, operations/mimir/getting-started.sh
Update k8s-libsonnet used by Tanka to version 1.21. Previously used version 1.18 is no longer available in https://github.com/jsonnet-libs/k8s-libsonnet/
Trying to use later version (1.22) would run into issue https://github.com/grafana/mimir/issues/1825.
Fixes CI errors after recent change in https://github.com/jsonnet-libs/k8s-libsonnet/ when v1.18 was removed. See for example https://github.com/grafana/mimir/runs/6789049505?check_suite_focus=true
=> Initialize Tanka with k8s-libsonnet v1.21.

CHANGELOG.md, go.mod, go.sum, vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go, vendor/github.com/prometheus/prometheus/tsdb/chunks/queue.go, vendor/modules.txt
This PR updates `mimir-prometheus` to latest `main`. This includes two changes:
https://github.com/grafana/mimir-prometheus/pull/131
https://github.com/grafana/mimir-prometheus/pull/247
These should result is lower memory usage by async chunk mapper. (We have tested the changes in internal dev cluster to prove that they help).
=> Update Prometheus with async chunk mapper changes.

CHANGELOG.md, docs/configurations/demo.yaml, docs/sources/operators-guide/getting-started/_index.md
#862 made me realized that the getting started guide uses `local` storage for the ruler, which requires the directory to exists and doesn't support `mimirtool` to upload rules config. I recommend to switch to `filesystem` which fixes #862 and also work with `mimirtool`. I manually tested it.
Fixes #862
=> Fix ruler config in getting started guide

CHANGELOG.md, pkg/storegateway/indexheader/fileutil/mmap_generic.go
My previous change (#2019) assumed MAP_POPULATE was available on Darwin. This fixes the build.
=> Fix build for darwin platform.

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
Add extra alerts for ruler query path components and adapt current ones to avoid conflicting with regular query path. 
Fixes N/A
=> mixin: adapt alerts/playbooks to consider ruler query path components

pkg/mimir/mimir.go
The `/ready` will now include each service's state when there is at least one non-`Running` service (e.g. `Failed` or `Starting`). The same will be logged at debug level.
Previously output:
```
Some services are not Running:
Running: 11
Starting: 1
```
Current output:
```
Some services are not Running:
distributor-service: Starting
```
Fixes https://github.com/grafana/mimir/issues/1780
=> Return and log detailed services information on /ready

CHANGELOG.md, docs/sources/operators-guide/tools/mimir-continuous-test.md, pkg/continuoustest/manager.go, pkg/continuoustest/manager_test.go, pkg/continuoustest/write_read_series.go, pkg/continuoustest/write_read_series_test.go
Adds a new flag `-tests.smoke-test` to mimir-continuous-test. This flag will run the tests once and immediately exit.
The existing test was updated to support returning errors to the caller. In order to maximize the amount of useful debugging information returned, errors are collected in a slice and returned all at once rather than exiting at the first error.
Fixes #2042
=> mimir-continuous-test: Add smoke test mode

CHANGELOG.md, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir-tests/test-defaults-generated.yaml, operations/mimir-tests/test-disable-chunk-streaming-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir-tests/test-query-sharding-generated.yaml, operations/mimir-tests/test-shuffle-sharding-generated.yaml, operations/mimir-tests/test-storage-azure-generated.yaml, operations/mimir-tests/test-storage-gcs-generated.yaml, operations/mimir-tests/test-storage-s3-generated.yaml, operations/mimir/compactor.libsonnet
In this PR I'm upstreaming a jsonnet override we had internally at Grafana Labs: the `compactor` service. The service can be used to directly traffic directly to compactor (e.g. admin UI).
N/A
=> Jsonnet: add compactor service

CHANGELOG.md, pkg/ruler/compat.go
When remote operational mode is enabled, ruler reports failed rule evaluation metric only when `query-frontend` returns a `500` status code.   
This PR adapts it to consider all 5xx status codes. 
Fixes N/A
=> ruler: report failed eval on any 5xx status

pkg/alertmanager/multitenant_test.go
I'm sharing my feedback on https://github.com/grafana/mimir/issues/2044 and the [last comment](https://github.com/grafana/mimir/issues/2044#issuecomment-1152134837) made me change my mind. The current firewall we have protects HTTP proxy requests too, but we don't have a test to enforce it. This PR add such test case.
N/A
=> Test alertmanager firewall with HTTP proxy too

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/mimir/modules.go, pkg/ruler/remotequerier.go, pkg/ruler/remotequerier_test.go
During a rule group evaluation, if the remote query never completes for any
reason, then the rule group will become stuck and never evaluate again.
=> Ruler: Add timeout for remote rule evaluation queries.

CHANGELOG.md, pkg/continuoustest/write_read_series.go, pkg/continuoustest/write_read_series_test.go
Updates the `continuoustest` package to return an error if no valid query time range is found. This only impacts the operation when `-tests.smoke-test` is passed. 
This was an oversight during https://github.com/grafana/mimir/pull/2047
I found this issue during development of https://github.com/grafana/mimir/pull/2061.
The smoke-test failed due to an HTTP 401, but the process return code was still 0 since that error is silently ignored.
Related to https://github.com/grafana/mimir/issues/2060
=> [mimir-continuous-test] Fail on 4xx when in smoke-test mode

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/ingester/ingester.go, pkg/storage/tsdb/config.go
Relates to the changes in https://github.com/grafana/mimir-prometheus/pull/251
Adds a new TSDB Config flag to allow querying on overlapping blocks in the ingesters in case there are any in the filesystem.
The new out of order implementation will generate overlapping blocks and this flag makes it possible to revert back to a previous release in case something goes wrong.
Also, if there were any other usecases where overlapping blocks where present in the filesystem, this option will be of help to enable queries.
=> Optional setting to allow querying overlapping blocks

CHANGELOG.md, operations/mimir-tests/test-gossip-disable-consul-generated.yaml, operations/mimir-tests/test-gossip-generated.yaml, operations/mimir-tests/test-gossip-multi-zone-generated.yaml, operations/mimir-tests/test-gossip-multikv-generated.yaml, operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml, operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml, operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml, operations/mimir/alertmanager.libsonnet, operations/mimir/memberlist.libsonnet
This is a follow-up PR to https://github.com/grafana/mimir/pull/2102. It sets the gossip port and gossip label, which was previously missed.
N/A
=> Addendum to alertmanager respecting memberlist_ring_enabled

CHANGELOG.md, cmd/mimir/config-descriptor.json, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
In #1188 the config name of `active_series_custom_trackers` has been changed to `active_series_custom_trackers_config` by accident. The aim of this PR is to change it back to `ąctive_series_custom_trackers` while supporting the suffixed version for 2 releases.
When both are specified, the old config takes precedence.
=> Adding support for new config name

operations/mimir/memberlist.libsonnet
Accounts for the alertmanager being disabled before adding the gossip label. This is (yet another, sorry) follow up PR to https://github.com/grafana/mimir/pull/2102. Opening as a draft because I haven't verified this and don't want to cause further churn.
=> Jsonnet: Account for disabled alertmanager when adding memberlist gossip label

pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go
We need to get insight into errors returned by forwarding targets, this adds a metric to track the errors by tenant and status code.
=> Add metric for error codes resulting from forwarding requests

CHANGELOG.md, docs/sources/tutorials/play-with-grafana-mimir/config/grafana-provisioning-datasources.yaml, docs/sources/tutorials/play-with-grafana-mimir/docker-compose.yml
While checking https://github.com/grafana/mimir/discussions/1931, I've realised the Grafana Alerting UI doesn't work in the "Play with Grafana Mimir" tutorial, due to some changes done by Grafana in the meanwhile. This PR fixes it (I manually tested it).
Changes:
1. Always pull Grafana latest (so `9.0.0` as of today)
2. Add "Alertmanager" datasource and link it to "Prometheus" one
N/A
=> Fixed Mimir Alertmanager datasource in Grafana used by "Play with Grafana Mimir" tutorial

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml, operations/helm/charts/mimir-distributed/values.yaml
Introduce global.podAnnotations , let's the user version their extra envFrom to trigger a service
restart on changes.
Related to https://github.com/grafana/helm-charts/issues/1150 and https://github.com/grafana/helm-charts/pull/1181
- [N/A] Tests updated - next PR
- [N/A] Documentation added - part of https://github.com/grafana/mimir/issues/1945
=> Helm: Add global POD annotations

operations/helm/charts/mimir-distributed/ci/test-enterprise-configmap-values.yaml, operations/helm/charts/mimir-distributed/ci/test-oss-values.yaml, operations/helm/charts/mimir-distributed/templates/minio-secrets.yaml, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/admin-api/admin-api-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/distributor/distributor-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/gateway/gateway-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/mimir-config.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/minio-secrets.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/ruler/ruler-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/distributor/distributor-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/mimir-config.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/minio-secrets.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/ruler/ruler-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
Test that mimir.structuredConfig can be used to alter parts of the
application configuration.
Test that environment injection works from a secret.
Test that environment expansion works in Mimir/GEM.
Test that global POD annotations work.
Relates to:
#2017 
#2031 
#2099 
#2100 
- [N/A] Documentation added - it is input for https://github.com/grafana/mimir/issues/1945
=> Helm: test simplified configuration e2e

CHANGELOG.md, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/jsonnetfile.json, operations/mimir-mixin/jsonnetfile.lock.json, operations/mimir-mixin/recording_rules.libsonnet
Updates `grafana/jsonnet-libs` and exposes configuration to set the range of histogram recording rules.
The update includes ability to set the range for histogram rules. This is useful when the scrape interval of metrics from mimir is more than 30s. When ingesting every 1 minute for example the recording rules don't produce any data because x[1m] would capture only a single data point. And a single data point does not have any rate of increase or decrease, so rate(x[1m]) produces no data.
=> mimir-mixin: Configure range for histogram rules

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml
Set ingester availability zone to zone-default.
This is required to be able to start the multi-zone migration.
Relates to #2020
=> Helm: set ingester availability zone to zone-default

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, pkg/ingester/errors.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/util/globalerror/errors.go, pkg/util/validation/errors.go, pkg/util/validation/errors_test.go
Following what we've done in https://github.com/grafana/mimir/pull/1888, this PR adds common ingester push errors to the errors catalogue.
N/A
=> Add ingester push errors to errors catalogue

pkg/ingester/ingester.go
This PR adds back passing of `NewChunkDiskMapper` to TSDB options in `out-of-order` branch, where it was [accidentally removed](https://github.com/grafana/mimir/commit/0d42afbff1a067cbc448385601ef8afab05c86f2#diff-e1032332627c413a3010c66b54b22b6e9835cf152fa339e40cf0b11204f7241f).
=> Pass NewChunkDiskMapper option to TSDB in `out-of-order` branch.

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/configuring-shuffle-sharding/index.md, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, docs/sources/operators-guide/running-production-environment/scaling-out.md, integration/ingester_sharding_test.go, operations/mimir/shuffle-sharding.libsonnet, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/mimir/mimir.go, pkg/mimir/modules.go, pkg/querier/querier.go, pkg/querier/querier_test.go
This change deprecates the
`querier.shuffle-sharding-ingesters-lookback-period` option, instead
setting the lookback period from the value of the
`querier.query-ingesters-within` option. Outside of our own integration
tests, there's no situation where it's useful to set the lookback period
to a different value than the `query-ingesters-within` option.
This also adds a new option `querier.shuffle-sharding-ingesters-enabled`
that can be used to enable or disable shuffle sharding on ingesters on
the read path instead of using the lookback period for this.
Fixes #1810
=> Set shuffle sharding ingester lookback automatically

operations/k6/README.md, operations/k6/load-testing-with-k6.js
I'm using the K6 script to load test a Mimir cluster and I've noticed the default `HA_CLUSTER=100` caused 100x series to be generated than I would have expected. I suggest to change the default to 1.
N/A
=> K6 script: default HA clusters to 1

CHANGELOG.md, pkg/ruler/compat.go, pkg/ruler/compat_test.go
The `cortex_ruler_queries_failed_total` metric should increment whenever a rule evaluation query fails, for a reason not caused by user behavior. Before this change, errors would be ignored unless they are specifically of type`httpgrpc`. This means that many errors get lost, for example, connectivity errors coming from gRPC.
Note: I inverted the logic a little so it reads "count everything except... " which I thought was easier to read.
- n/a Documentation added
=> Ruler: Report wider range of errors from remote rule evaluation queries.

operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/config.libsonnet
The alert doesn't take into account the queries that now have ruler-
prepended to their name. This PR fixes it
=> Fix GossipMembersMismatch misfiring with remote ruler eval

docs/sources/operators-guide/monitoring-grafana-mimir/installing-dashboards-and-alerts.md
BUILD_IN_CONTAINER is used by default
No need to have separate instructions on how to build mixin's in a
container as it is the default method. Also therefore remove the
unnecessary dependencies.
=> Docs: Update mixin building instructions

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
Changes the `MimirRulerTooManyFailedQueries` alert severity to `critical`.
Currently there is no critical alert coverage for issues which occur on the ruler read path (regardless of operational mode). When using "Remote" operational mode, there are more services which could cause rule queries to fail. However, there are valid reasons they may fail when running in "Internal" mode too which should be investigated (e.g. cannot contact ingesters, store-gateways, ...).
Note that in both operational modes, the `cortex_ruler_queries_failed_total` does not get incremented for queries which fail for reasons due to user actions (hitting query limits, many-to-many joins, etc.), so the expectation is that this only fires for critical issues which need investigation.
- n/a Tests updated
- n/a …
=> Mixin: Change `MimirRulerTooManyFailedQueries` alert to `critical`

operations/helm/charts/mimir-distributed/templates/NOTES.txt, operations/helm/charts/mimir-distributed/values.yaml
Helm: explain nameOverride and fullnameOverride and warn about dashboards
Fix comment https://github.com/grafana/mimir/pull/2189#issuecomment-1164234139, missing "the"
Fixes https://github.com/grafana/helm-charts/issues/1426
Relates to https://github.com/grafana/mimir/pull/2189#issuecomment-1164234139
=> Helm: improve docstring for nameOverride and fullnameOverride

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/compactor.libsonnet
When this alert is evaluated in Mimir itself, it can cause false-positive rule
evaluation failures. This is because multiple alerts with the same name can
fire concurrently, causing duplicate series to be written.
I'm not 100% sure what the best action is here:
1. Make each alert have distinct names
- This isn't so nice as the _action_ for each alert is the same (i.e. same runbook)
2. Make each alert mutually exclusive so they never fire concurrently
- This would be a hard thing to test for and likely fragile
3. Give each alert an additional label
I went for (3) - open to opinions.
If we're happy with this option as a generic approach, then I'll work on a linter check to enforce it.
- n/a Tests updated
- n/a Documentation added
=> Mixin: Make each `MimirCompactorHasNotUploadedBlocks` alert distinct.

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/mimir/modules.go, pkg/querier/engine/config.go, pkg/ruler/remotequerier.go
=> Ruler: Remove -ruler.query-frontend.timeout and use -querier.timeout instead.

RELEASE.md
This PR updates RELEASE.md documentation for maintainers doing releases.
- In first commit it just breaks long lines, and adds more releases.
- Second commit expands our release notes: adds contributor stats and new contributors, and explains how to find that.
- Third commit clarifies procedure for doing cherry-picks, that preserves contributor stats in Github but also adds extra traceability to commit messages by linking the original commit message.
- (Additional commits will reflect review feedback 😄 and inevitable linter complaints)
Since this is internal document for maintainers and not end users, I don't consider it as "documentation", hence not engaging docs team.
- [na] `CHANGELOG.md` updated - the order of entries should be …
=> Updates to RELEASE.md

pkg/util/globalerror/errors.go, pkg/util/globalerror/errors_test.go, pkg/util/validation/errors_test.go
Change the error message template for per-tenant limits
Follows up on change discussed in https://github.com/grafana/mimir/pull/2150
=> Change the error message template for per-tenant limits

CODEOWNERS
Not all members of the @grafana/docs-squad team are responsible for technical writer review on Mimir docs.
=> Set CODEOWNERS to primary technical writer

go.mod, go.sum, pkg/storage/tsdb/upload_test.go, vendor/github.com/prometheus/prometheus/tsdb/block.go, vendor/github.com/prometheus/prometheus/tsdb/compact.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/head_wal.go, vendor/modules.txt
Vendor Prometheus to get this patch https://github.com/grafana/mimir-prometheus/pull/277/
=> Vendor latest mimir-prometheus/main

CODEOWNERS, docs/sources/operators-guide/architecture/components/ingester.md, docs/sources/operators-guide/configuring/about-versioning.md, docs/sources/operators-guide/configuring/configuring-out-of-order-samples-ingestion.md, go.mod, go.sum, pkg/storage/tsdb/upload_test.go, vendor/github.com/prometheus/prometheus/tsdb/block.go, vendor/github.com/prometheus/prometheus/tsdb/compact.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/head_wal.go, vendor/modules.txt
This PR just syncs main with r192. Vendoring of mimir-prometheus has the fix.
Edit: Since Mimir 2.2 will have these commits, we are adding these commits in the release so that we can test it out.
=> Update r192 with the out-of-order fix

CHANGELOG.md, operations/mimir-tests/test-consul-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-generated.yaml, operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml, operations/mimir/multi-zone.libsonnet
In operations/mimir, change `multi_zone_ingester_max_unavailable` to 25.
=> operations/mimir: Change multi_zone_ingester_max_unavailable to 25

docs/internal/contributing/contributing-to-helm-chart.md
This is a reminder for people how to check for new versions.
Came up on community slack.
=> Helm: add a step to contributing doc

CHANGELOG.md, pkg/compactor/bucket_compactor.go, pkg/compactor/compactor_test.go
I've seen a compactor failing to compact some blocks, but the reason is missing from logs because we're not logging the actual error (the error returned by `runCompactionJob()` is never logged).
Once the compaction fails, source blocks are left on disk for later investigation. While this is a nice thing, it triggers another issue: subsequent job executions (other jobs) may run out of disk space, because previous failing compaction run jobs (failed) are left on disk. This is an issue which is also happening on the cluster I'm investigating.
In this PR I propose to fix both.
N/A
=> Log compaction failure error and delete temporarily blocks from disk

operations/helm/charts/mimir-distributed/CHANGELOG.md
We did release some interim versions, but we switched to weekly releases
shortly after. Now having those beta versions in the changelog just make
it messy from release note point of view.
N/A
=> Helm: fix changelog to be continuous from 2.1 release

operations/helm/charts/mimir-distributed/CHANGELOG.md
Cherry pick https://github.com/grafana/mimir/commit/37376ee1287f36542648573ae707c5f74775e7fb
Helm: fix changelog to be continuous from 2.1 release (#2272)
We did release some interim versions, but we switched to weekly releases
shortly after. Now having those beta versions in the changelog just make
it messy from release note point of view.
N/A
N/A
=> Helm: fix changelog to be continuous from 2.1 release (#2272)

CHANGELOG.md, pkg/storegateway/indexheader/fileutil/mmap_386.go, pkg/storegateway/indexheader/fileutil/mmap_amd64.go, pkg/storegateway/indexheader/fileutil/mmap_arm64.go, pkg/storegateway/indexheader/fileutil/mmap_windows.go
This PR imports windows-related mmap code from Prometheus https://github.com/prometheus/prometheus/blob/main/tsdb/fileutil/ package to make `mimirtool` buildable on Windows.
**Note that target for this bugfix was set to `release-2.2`.**
Fixes https://github.com/grafana/mimir/issues/2258
=> Fix mimirtool build windows

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml, operations/helm/charts/mimir-distributed/values.yaml
The goal is provides a path for working around issues with nginx's DNS resolution that occur when the kube-dns pods are restarted in certain clusters (any cluster using conntrack for keeping state on UDP flows, typically).
Adding a local resolver as side container to the nginx can be used to workaround it.
* Add `extraContainers` feature for nginx so you can add sidecar containers to the deployment
* Add a new variable `nginx.nginxConfig.resolver` to the nginx component of the chart
This allows overriding the DNS resolver used by nginx. This is necessary to work around issues with UDP services that occur when kube-dns pods are restarted. This was happening also in other charts like loki. More details: https://github.com/grafana/helm-charts/issues/1058
With these features a workaround can …
=> Helm: Add extraContainers to nginx deployments and override to resolve for nginxConfig

docs/docs.mk
**[Remove Loki index file](https://github.com/grafana/mimir/commit/f90c1f307550148e3e87f0faa7336983ca7df5a3)**
This is no longer needed as the updated `grafana/docs-base` image has
the Mimir index file built in.
**[Ensure /docs/mimir redirects to $(DOCS_VERSION)](https://github.com/grafana/mimir/commit/050a62b0213f60c0220e904facb225676bd6442f)**
By default it redirects to "latest" which is desirable on the
published website.
Typically in development we would like it to redirect to "next".
=> Redirect `/docs/mimir` -> `/docs/mimir/$(DOCS_VERSION)` in local webserver

docs/sources/operators-guide/getting-started-helm-charts/_index.md
Simplifies the procedure, plus avoids the trap when the
name is handled in a unique way.
Ref: https://github.com/grafana/mimir/issues/2282
=> Hardcode the namespace and release name for getting started

go.mod, go.sum, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/modules.txt
This vendoring brings in https://github.com/grafana/mimir-prometheus/pull/283, which removes a couple of temporary patches made for out-of-order support that are no longer required.
=> Vendor latest mimir-prometheus

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
I was helping someone debug notifications being sent every min and we found that
these two fields are not used anywhere at all.
I am not sure of the deprecation and breaking change policy. Should I mark them
deprecated somehow and then remove them or just remove them right away since they
are not being used.
=> [ruler] Remove unused fields

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin/dashboards/ruler.libsonnet
If there're no failures in rule evaluations, it doesn't necessarily mean everything is just fine. Rules could be slow to evaluate and so we could miss some rule evaluation iterations. That's why we also have the alert `MimirRulerMissedEvaluations`.
Missed rule evaluations are not clearly visible in the "Mimir / Ruler" dashboard (they're just displayed on a per-tenant basis down the dashboard, in a row which is collapsed by default).
I propose to add it to the "Evaluations per second" panel, to make it more visible.
N/A
=> Added missed rule evaluations to the "Evaluations per second" panel in the "Mimir / Ruler" dashboard

operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin/dashboards/queries.libsonnet
A couple of changes to clarify the query results cache panels in "Mimir / Queries" dashboard:
- Renamed cache "Hit rate" to "Hit ratio" to keep consistency with the other dashboards
- Renamed "Miss rate" to "Missed query results per second" to clarify it's the number of missed query results per second and not a %
N/A
=> Clarify query results cache panels in 'Mimir / Queries' dashboard

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin/dashboards/queries.libsonnet
In #385 I've introduced "split_by_interval_and_results_cache" middleware, which then took over the old one:
https://github.com/grafana/mimir/pull/385/files#diff-79d26f5440b74049ba76e0fd11b44a321eaa0ea322a6d651d632341e81f6863aR188
However, this change has broken the "Intervals per Query" panel in the "Mimir / Queries" dashboard. This PR fixes it.
N/A
=> Fixed "Intervals per query" panel in the "Mimir / Queries" dashboard

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json, operations/mimir-mixin/dashboards/slow-queries.libsonnet
The loki data format changed in grafana 9.0. This broke the Slow Queries dashboard. 
This is what the resulting dashboard looks on Grafana v9.0.0-adfe4ef5pre (adfe4ef56)
The change _is not_ compatible with versions prior to Grafana 9.0
Fixes #2119
=> mixin: Convert "Slow Queries" dashboard to Grafana 9.0

CHANGELOG.md, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go
This PR is just #2050 (keeping original author commits) + addressing a couple of nits before merging. Contrary to #2050, I've reverted the change on OAuth2 proxy URL because, after adding a unit test on it, I've realized it's not protected by our firewall logic (we need to do changes in `prometheus/common` to set the dial context override on it too).
Fixes #2044
=> Get PR 2050 through the finish line

docs/sources/migration-guide/_index.md, docs/sources/migration-guide/migrating-from-cortex.md, docs/sources/migration-guide/migrating-from-thanos-or-prometheus.md, docs/sources/operators-guide/_index.md, docs/sources/operators-guide/architecture/_index.md, docs/sources/operators-guide/architecture/about-grafana-mimir-architecture/index.md, docs/sources/operators-guide/architecture/components/_index.md, docs/sources/operators-guide/configuring/_index.md, docs/sources/operators-guide/deploying-grafana-mimir/jsonnet/_index.md, docs/sources/operators-guide/monitoring-grafana-mimir/_index.md, docs/sources/operators-guide/monitoring-grafana-mimir/dashboards/_index.md, docs/sources/operators-guide/running-production-environment/_index.md, docs/sources/operators-guide/running-production-environment/scaling-out.md, docs/sources/operators-guide/securing/_index.md, docs/sources/operators-guide/tools/_index.md, docs/sources/operators-guide/using-exemplars/_index.md, docs/sources/release-notes/_index.md
Uses the `menuTitle` parameter of the `section` shortcode to reduce stuttering throughout the documentation.
Titles include "Grafana Mimir" as context when the page turns up on search engine results but when you are in the documentation, this is already implied.
=> Use menuTitle for more user-friendly lists of topics 

pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go
Remove the always-empty `meta.Thanos.Labels` from `relabelLabels `.
Follow-up on https://github.com/grafana/mimir/pull/2240 and cleanup more unneeded code.
=> Cleanup unused part of relabelLabels from store-gateway

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md, pkg/compactor/compactor.go
The comment https://github.com/grafana/mimir/issues/1291#issuecomment-1102999139 made me realise that the `-compactor.consistency-delay` description is incorrect. Mimir doesn't delete partial blocks unless they already have a deletion mark. Also the `PartialUploadThresholdAge` constant was inherited from Thanos but it's not really used by Mimir.
This PR fixed it.
N/A
=> Fix -compactor.consistency-delay description

CHANGELOG.md, pkg/alertmanager/alertmanager_test.go, pkg/alertmanager/state_replication.go, pkg/alertmanager/state_replication_test.go
In cortexproject/cortex#3925 the ability to restore alertmanager state from
peer alertmanagers was added, short-circuiting if there is only a single
replica of the alertmanager. In cortexproject/cortex#4021 a fallback to read
state from storage was added in case reading from peers failed. However, the
short-circuiting if there is only a single peer was not removed. This has the
effect of never restoring state in an alertmanager if only running a single
replica.
Fixes #2245
=> Restore alertmanager state from storage as fallback

CHANGELOG.md, pkg/ruler/manager.go, pkg/ruler/manager_test.go
Minimise the locking in DefaultMultiTenantManager to make "List Prometheus rules" API more responsive while synching rule groups.
Fixes #2283
=> Make "List Prometheus rules" API more responsive while synching rule groups

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This lets administrators see at a glance if requests are too low, which risks overloading nodes, or too high which wastes provisioning.
Example:
=> dashboards: add k8s resource requests to CPU and memory panels

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/parallel.go, pkg/frontend/querymiddleware/astmapper/parallel_test.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go, pkg/frontend/querymiddleware/querysharding_test.go
Functions `vector` and `time` can't be sharded, as they produce same set of series (with zero labels) and can't be concatenated later.
Additionally, functions that have a default `time()` argument, like `month()`, were not propagating the shardeability checks properly.
None, internal.
=> Fix sharding of `vector` and `time` functions

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/parallel.go, pkg/frontend/querymiddleware/astmapper/parallel_test.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go, pkg/frontend/querymiddleware/querysharding_test.go
Functions `vector` and `time` can't be sharded, as they produce same set
of series (with zero labels) and can't be concatenated later.
Additionally, functions that have a default `time()` argument,
like `month()`, were not propagating the shardeability checks properly.
(cherry picked from commit 27154b3f3bfbd684402e8b448741dc575470bb0a)
=> Fix sharding of `vector` and `time` functions (#2355)

.github/workflows/backport.yaml
**Why is the change needed, what does it improve?**
Adds automatic backporting of PRs with the `backport <release branch>` label.
This means that we can add the `backport release-2.2` to a PR and
after merging the PR grafanabot will open a new PR with the merge commit
cherry-picked to the `release-2.2` branch.
This makes cherry-picking commits onto release branches faster.
=> Add backport CI job

docs/sources/tutorials/play-with-grafana-mimir/config/mimir.yaml, docs/sources/tutorials/play-with-grafana-mimir/docker-compose.yml, integration/configs.go, integration/getting_started_with_grafana_mimir_test.go
Tutorial can't use common config yet as it will be released in 2.3.
This reverts the common config usage, and I'll create an issue to bring it back after releasing 2.3. Edit: issue https://github.com/grafana/mimir/issues/2377
Fixes https://github.com/grafana/mimir/issues/2374
=> Revert tutorial's common config usage

RELEASE.md
We should merge release into a branch of main, not main into a branch of
release, which would have the parents in the opposite order.
Also document that we merge back release into main after doing the
release candidates.
Ref: https://github.com/grafana/mimir/issues/2241
=> Update docs on how to merge release to main

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/chunks-cache/chunks-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/index-cache/index-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/metadata-cache/metadata-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/results-cache/results-cache-statefulset.yaml
- availability to pull image from private registry (like artifactory)
- missing resources block for memcachedExporter
Fixes #2320 
=> missing memcachedExporter resources + imagePullSecrets

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/Chart.yaml, operations/helm/charts/mimir-distributed/README.md
backport https://github.com/grafana/mimir/commit/df12d7b26ea0b8f311beb373528b15c23953eee6 from https://github.com/grafana/mimir/pull/2297
=> [release-2.2] Helm: bump minimum Kubernetes version for the helm chart

CHANGELOG.md, operations/mimir-mixin/dashboards/ruler.libsonnet
We're missing a lot of API routes for presumably a variety of reasons. Changing the regex to include the following routes:
Prometheus:
```
api_prom_api_v1_rules
api_prom_api_v1_alerts
api_prom_api_v1_status_buildinfo
prometheus_api_v1_rules
prometheus_api_v1_alerts
prometheus_api_v1_status_buildinfo
```
Mimir:
```
api_prom_rules
api_prom_rules_{namespace}
api_prom_rules_{namespace}_{groupName}
api_v1_rules
api_v1_rules_{namespace}
api_v1_rules_{namespace}_{groupName}
prometheus_rules
prometheus_rules_{namespace}
prometheus_rules_{namespace}_{groupName}
prometheus_config_v1_rules
prometheus_config_v1_rules_{namespace}
prometheus_config_v1_rules_{namespace}_{groupName}
```
=> Mixin: Add missing API routes to Ruler dashboard.

docs/sources/operators-guide/architecture/components/ingester.md, docs/sources/operators-guide/configure/configure-out-of-order-samples-ingestion.md, docs/sources/operators-guide/configure/configuring-out-of-order-samples-ingestion.md
This restructure is based on an offline feedback. It also now explicitly mentions that out-of-order is an experimental feature.
=> Restructure configuring out-of-order docs

development/tsdb-blocks-storage-s3/config/mimir.yaml, development/tsdb-blocks-storage-s3/docker-compose.jsonnet, development/tsdb-blocks-storage-s3/docker-compose.yml
This PR updates dev setup to use `memberlist` KV store by default, and fixes `join_members` field in mimir config to point to `distributor-1`. It also fixes "depends_on" field to use "distributor-1" after recent rename in #2154.
=> Update dev setup to use memberlist by default

CHANGELOG.md, pkg/storegateway/blocks.gohtml, pkg/storegateway/gateway_blocks_http.go, tools/listblocks/main.go
This PR extends listing of blocks with block stats (number of series, samples and chunks). This is done both at web page (exposed by store-gateway) and in `listblocks` CLI tool (requires new option `-show-stats`).
=> Show block stats when listing blocks.

README.md
The work to align with the style guide with regard to imperatives for tasks is going into release 2.3. This PR reverts some of the needed changes for that temporarily until we can get the links sorted out.
=> Revert changes from gerunds to imperatives.

CHANGELOG.md, operations/mimir-tests/test-defaults-generated.yaml, operations/mimir-tests/test-without-query-scheduler-generated.yaml, operations/mimir-tests/test-without-query-scheduler.jsonnet, operations/mimir/config.libsonnet
We recommend to deploy the query-scheduler component. The query-scheduler is disabled by default in the jsonnet. This PR enables the scheduler by default.
=> Enabled query-scheduler by default in jsonnet

CHANGELOG.md, pkg/ruler/remotequerier.go, pkg/ruler/remotequerier_test.go
This PR fixes a bug that makes ruler to consider all non-200 status codes as failed queries when running in remote operational mode.
Fixes N/A
=> ruler: return proper status error on remote querier

RELEASE.md
Updates the release instructions to replace manual cherry-picking with the bot introduced in #2359
=> Update release instructions for cherry-picking

CHANGELOG.md, pkg/ingester/client/client.go
When investigating a recent outage, it was annoying to check how long it took sending requests to ingesters via `cortex_ingester_client_request_duration_seconds` metric because buckets are capped to 1s. In this PR I propose to add 2 more buckets, covering the ranges 1s-4s and 4s-16s.
N/A
=> Add more buckets to cortex_ingester_client_request_duration_seconds histogram metric

CHANGELOG.md
=> Changelog entry for #2423

CHANGELOG.md, pkg/ingester/shipper.go, pkg/ingester/shipper_test.go
When a block upload appears to have failed, but later the shipper
discovers that the upload actually succeeded, the shipper does not
upload it again. But the ingester still reports the block as unhsipped.
This lead to a false positive alert (`MimirIngesterHasUnshippedBlocks`)
and stale value for `cortex_ingester_oldest_unshipped_block_timestamp_seconds`.
This PR changes the shipper to report an upload when it discovers
such a block. This helps with invalidating the cached shipper meta file
and reporting correct metrics.
Fixes https://github.com/grafana/mimir/issues/1997
=> Report previously failed shipped blocks in shipper

operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin/dashboards/compactor.libsonnet
Two recently added panels in the Compactor dashboard were not rendering properly:
- Longest time since last successful run
- Last successful run per-compactor replica
The issue was the use of the "Status" field.
The "Status" text field may no longer be calculated using the direct value of "1" as of Grafana 8.5.
A "One" field is created to serve this purpose.
Further, "Status" has been removed from "Longest time since last successful run" since it is not being used there anymore.
Fixes #2315
Assuming that mixins do not go into the CHANGELOG.md
=> fix: mixin compactor dashboard "last successful run" render issues in Grafana 8.5+

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, docs/sources/operators-guide/mimir-runbooks/_index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/globalerror/errors.go
Introduces a limit for the total size of the inflight push requests in the distributor `-distributor.instance-limits.max-inflight-push-requests-total-size`.
This limit is useful in combination with the existing `-distributor.instance-limits.max-inflight-push-requests`. The existing limit does not account for large requests that may be below the inflight requests count. The new limit is meant to protect the distributor against multiple large requests. 
By default the limit is disabled because it will limit memory utilization on existing Mimir installations.
Fixes https://github.com/grafana/mimir/issues/2226
=> Add distributor inflight request size limit

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go, vendor/modules.txt
In this PR I'm updating dskit to get https://github.com/grafana/dskit/pull/194.
N/A
=> Memberlist: disabled TCP-based ping fallback

CHANGELOG.md, integration/query_frontend_test.go, pkg/api/error/error.go, pkg/frontend/querymiddleware/codec.go, pkg/frontend/querymiddleware/codec_test.go, pkg/frontend/transport/roundtripper.go, pkg/frontend/v2/frontend_test.go
Handles the 429 status code when query sharding uses the prometheus codec.
Fixes https://github.com/grafana/mimir/issues/2169
=> Fix query sharding with too many requests error

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/util/validation/limits.go
Change default value for `-distributor.ha-tracker.max-clusters` to `100`.
Fixes https://github.com/grafana/mimir/issues/2173
=> Change default value for `-distributor.ha-tracker.max-clusters` to `100`

go.mod, go.sum, integration/single_binary_test.go, vendor/gopkg.in/yaml.v3/decode.go, vendor/modules.txt
After upgrading to gopkg.in/yaml.v3 in [#2468], @pstibrany noticed that int 0 is no longer a valid time.Duration value.
I've sent a PR to fix that: https://github.com/go-yaml/yaml/pull/876 and cherry-picked the change into the branch we're using in Mimir as the replacement.
No changelog is included as we _broke_ it in the immediately previous PR.
[#2468]: https://github.com/grafana/mimir/pull/2468
Relates to https://github.com/grafana/mimir/pull/2468
=> Fix parsing int 0 as duration in yaml

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
This PR adds new compactor endpoints for backfilling into Nginx configuration in Helm chart.
=> Helm: Add new compactor endpoints for backfill to nginx configuration.

Makefile, operations/mimir-mixin-tools/serve/run.sh
We have a command `make mixin-serve` which runs a Grafana locally and serves the dashboards from the compiled dashboards. The typically workflow is to run `make mixin-serve`, then do changes to dashboards and after each change run `make build-mixin` to see the changes live in Grafana.
Unfortunately, the workflow described above doesn't work and requires to re-run `make mixin-serve` after each `make build-mixin`. The reason is that we mount `operations/mimir-mixin-compiled/dashboards/` into the Grafana container, but that directory is deleted each time you run `make build-mixin`.
This PR fixes it, making `build-mixin` to only delete files and not directories, so that the directories tree is preserved and rebuilt dashboards are live reloaded in Grafana. I manually tested it.
_I also took …
=> Fix Grafana dashboards reload after rebuild

CHANGELOG.md, pkg/mimirtool/commands/bucket_validation.go
Validate that the object storage backend supports `Upload`s to existing
objects and will overwrite their contents.
Fixes #2490
=> mimirtool: validate that overwriting objects is supported

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin/dashboards/compactor-resources.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/reads-resources.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet
I propose to add RSS memory utilization (other than working set) for ingesters, store-gateways and compactors in our dashboards. The reason is that these 3 services make an extensive use of mmap and mmap cached pages may give a distorted view over the actual memory utilization (see https://github.com/grafana/mimir/issues/2466 for all the reasoning behind this).
I don't think we should stop using working set, because it's probably still the best approximation we have over the real memory utilization, but the "pod is using too much memory alarm" should probably trigger based on RSS rather than working set. For this reason, I propose to display RSS too.
I chose to display RSS side-by-side with working set, so that they're easier to visually compare (especially given there's the memory limit …
=> Dashboards: add RSS memory utilization panel for ingesters, store-gateways and compactors

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
This PR is a follow up of #2479. For the same reason of #2479, I propose to use RSS memory to alert on "ingesters using too much memory".
Part of https://github.com/grafana/mimir/issues/2466
=> Use RSS memory instead of working set memory in the MimirAllocatingTooMuchMemory alert for ingesters

operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/queries.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet
The panels showing per-pod metrics can have many lines. In such cases, sometimes I find it difficult to visually see outliers with values below the average, because the "area filling" gets very dark (the more series you have above you, the darker is the area behind you).
Some per-pod panels (e.g. networking) were already configured with no area filling, so in this PR I'm proposing to make it consistent across all dashboards and disable the area filling for all per-pod panels.
With the aim to make the visualization even more clear, I'm also proposing to use dashed lines for resources request/limit, to distingues them better.
**Before:**
**After:**
N/A
=> Dashboards: use dashed lines for resources request/limit and do not fill area in the per-pod panels

CHANGELOG.md, pkg/ingester/metrics.go, pkg/ingester/metrics_test.go
Adds tenant label to `cortex_ingester_tsdb_out_of_order_samples_appended_total`.
=> Add user label to ingester out-of-order appended samples metric

cmd/mimir/main.go, pkg/mimir/mimir.go, pkg/mimir/mimir_config_test.go
When projects based on Mimir try to inline Mimir's config, let's say:
```go
type customExtendedConfig struct {
MimirConfig   mimir.Config  `yaml:",inline"`
CustomStorage bucket.Config `yaml:"custom_storage"`
}
```
And we try to unmarshal a yaml that has a `custom_storage` field, we call `mimir.Config.UnmarshalYAML(*yaml.Node)` with the entire root node, and when it tries to decode it into `mimir.Config`, it fails because it doesn't know about `custom_storage`.
The first commit of this PR is a test showing that.
In order to solve it, I've extracted the `UnmarshalCommonYAML`, and changed the extended config to use a `type inlinedMimirConfig mimir.Config` so it wouldn't call mimir's custom unmarshaling. Then I implemented custom unmarshaling on the extended config, but I had to convert the …
=> Allow inlining `mimir.Config`

pkg/storegateway/blocks.gohtml, pkg/storegateway/gateway_blocks_http.go
This PR updates UI for controlling list of blocks. Most notably, it removes "Use ?split_count= query ..." hint, and provides text field instead. Links to enable/disable options were also replaced with HTML form elements.
Before:
After:
=> Store-gateway: use text field to control split count

operations/helm/charts/mimir-distributed/README.md, operations/helm/charts/mimir-distributed/README.md.gotmpl
Add release notes link.
Fix the upgrade from previous version text, since that complicated upgrade procedure is only applicable between 1.7 and 2.x versions.
=> Helm: update readme with 2.2 release notes link

CHANGELOG.md, go.mod, go.sum, vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go, vendor/modules.txt
This PR updates dskit to bring fix for issue https://github.com/grafana/dskit/issues/184.
=> Update dskit to fix empty ring issue after start

go.mod, go.sum, pkg/ingester/ingester.go, pkg/ingester/user_tsdb.go, vendor/github.com/prometheus/prometheus/storage/merge.go, vendor/github.com/prometheus/prometheus/tsdb/blockwriter.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/modules.txt
This PR vendors the latest mimir-prometheus that has a function to query the TSDB for chunks without merging overlapping or ordering them.
This PR uses that function in ingester. With out-of-order support, we will often find overlapping chunks. The querier already orders and merges overlapping chunks, so we can avoid doing it in ingesters.
=> Do not order and merge chunks in ingester for queries

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml, operations/helm/charts/mimir-distributed/values.yaml
1. Nginx wasn't using the `extraArgs` from the values file.
2. memcached had the `extraArgs` as an array, but they are used as a dictionary. This PR changes the type to a dictionary.
Fixes https://github.com/grafana/mimir/issues/2335
=> helm: Fix nginx and memcached extraArgs

integration/backward_compatibility.go, integration/backward_compatibility_test.go, integration/e2emimir/services.go
When overriding previous image versions, it is useful to also remap flags, as those images may have had different flag names.
This implements that feature by unmarshalling flag mappers from a JSON definition.
=> Support remapping flags for overriden images

CHANGELOG.md, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
In #2381  I've introduce a stricter `-alertmanager.external-url` validation to fix https://github.com/grafana/mimir/issues/2357, but I've been too strict and I unintentionally introduced a breaking change: `/path` is not supported anymore, while it should if it the intention it clear (which means if it starts with `/`). This PR fixes it.
N/A
=> Fix alertmanager external URL validation

pkg/compactor/block_upload.go, pkg/compactor/block_upload_test.go
This PR introduces block-validation status json file, and function to check block upload state. This block upload state is used by existing endpoints to verify if given operation (start block, upload file, finish block) can proceed or not. Validation status is not yet used, but will be used by new endpoint.
This PR also adds validation of filename and file length against meta.json when uploading single file.
=> Introduce validation progress and block state.

CHANGELOG.md, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir-tests/test-autoscaling.jsonnet, operations/mimir/autoscaling.libsonnet
In this PR I'm upstreaming the ruler-querier autoscaling jsonnet config we use at Grafana Labs.
N/A
=> Added ruler-querier autoscaling support

docs/sources/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/_index.md, docs/sources/operators-guide/get-started/_index.md, docs/sources/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs.md
This PR removes `http_listen_port` and `grpc_listen_port` fields from `server` config for the Agent.
See more details about the deprecation [here](https://grafana.com/docs/agent/v0.26/upgrade-guide/#breaking-change-deprecated-yaml-fields-in-server-block-removed).
=> Remove http_listen_port from server Agent config

CHANGELOG.md, pkg/distributor/distributor.go
This is mentioned to be removed in 2.3, so this is a good time to do it.
=> Remove `extend_writes` from Distributor YAML config

pkg/frontend/querymiddleware/results_cache.go, pkg/frontend/querymiddleware/results_cache_test.go, pkg/frontend/querymiddleware/roundtrip.go, pkg/frontend/querymiddleware/split_and_cache.go, pkg/frontend/querymiddleware/split_and_cache_test.go
Allow injection of CacheSplitter into querymiddleware
This is useful for when the caching strategy for the request
depends on something external, such as access control applied
to the query before it got to the querymiddleware.
=> Allow injection of CacheSplitter into querymiddleware

CHANGELOG.md, cmd/mimir/config-descriptor.json, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/ingester/ingester.go, pkg/mimir/mimir_test.go, pkg/mimir/modules.go, pkg/mimir/modules_test.go
Removes a deprecated config.
This is scheduled for 2.3, so it's a good moment to do this.
=> Remove active_series_custom_trackers from Ingester config

pkg/frontend/querymiddleware/astmapper/astmapper.go, pkg/frontend/querymiddleware/astmapper/astmapper_test.go, pkg/frontend/querymiddleware/astmapper/embedded.go, pkg/frontend/querymiddleware/astmapper/parallel.go, pkg/frontend/querymiddleware/astmapper/sharding.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go, pkg/frontend/querymiddleware/astmapper/subtree_folder.go
We use `parser.Node` in astmapper, but our input is the result of a `ParseExpr` which is an Expr, and we return an Expr.
By restricting this type, we remove a lot of type assertions (which were true anyway).
Relates to https://github.com/grafana/mimir/pull/2469
=> Use parser.Expr in frontend's astmapper

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/parallel.go, pkg/frontend/querymiddleware/querysharding_test.go
When both sides are constant scalar values, it doesn't make sense to shard them (plus it provides duplicate series).
No issue was created.
=> Don't shard binary ops of only constants

CHANGELOG.md, pkg/distributor/distributor_test.go
Decrease tests execution time
Results in my machine:
Before:
```bash
go test -count=1 ./pkg/distributor/...
ok      github.com/grafana/mimir/pkg/distributor        91.661s
?       github.com/grafana/mimir/pkg/distributor/distributorpb  [no test files]
ok      github.com/grafana/mimir/pkg/distributor/forwarding     0.470s
```
After:
```bash
go test -count=1 ./pkg/distributor/... 
ok      github.com/grafana/mimir/pkg/distributor        34.071s
?       github.com/grafana/mimir/pkg/distributor/distributorpb  [no test files]
ok      github.com/grafana/mimir/pkg/distributor/forwarding     0.171s
```
Fixes #2557
=> Optimize distributor tests

Makefile, tools/find-diff-or-untracked.sh
git diff does not take into account untracked files
Fix is to list untracked files and assert if there's any in path
Noticed when I accidentally generated an extra kube manifest with make check-helm-test.
N/A
=> make check tests should fail if untracked files found in golden record

pkg/frontend/querymiddleware/roundtrip.go, pkg/frontend/querymiddleware/split_by_instant_interval.go, pkg/frontend/querymiddleware/split_by_instant_interval_test.go
We plug the middleware only when splitting has been enabled in the config, so there's no need to pass the `splittingEnabled bool` too.
N/A
=> Chore: do not pass enabled flag to newSplitInstantQueryByIntervalMiddleware()

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/split_by_instant_interval_test.go
Ensure binary operation is not mapped if operands are not split. This is done by checking the `stats.GetShardedQueries()` metric.
=> Ensure binary operation is not mapped if operands are not split

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/split_by_instant_interval_test.go
This PR fixes three issues which are all correlated:
1. Fix pushdown of all vector selectors (I think this is a serious one)
2. Split binary operations when only one leg is splittable (i.e. only one leg has a range interval > split interval)
The query-frontend is **not** capable of fetching any samples to run a PromQL query directly from ingesters or store-gateways. This means that every single vector selector needs to be pushed down to queriers. The way this is implemented in the query sharding is using `subtreeFolder`. This PR fixes it using it for instant queries splitting too.
To fix this, I've changed the logic in `instantSplitter.mapCall()`. We need to make sure the expression range interval is detected as latest as possible, so I pushed it down to `instantSplitter.mapCallXXX()` …
=> Instant query split by interval: fix pushdown of all vector selectors and split binary operations when only one leg is splittable

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/split_by_instant_interval_test.go
Currently we need to change logic in 2 places when we add support to split more type of queries: both `isSplittable()` function and the actual `instantSplitter` logic.
I want to remove `isSplittable()` and let go every single query through the mapping logic. At the end of the mapping, we already check if it was successfully split or not, to decide whether it will be executed by the query-frontend (if was split) or just fully run it downstream (if wasn't split).
N/A
=> Remove upfront check whether an instant query is splittable or not

pkg/frontend/querymiddleware/astmapper/sharding.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go
While working on #2575 I've realized `isSubquery()` util, used by query sharding, doesn't correctly detect a subquery function call argument wrapped by parenthesis.
N/A
=> Fix isSubquery() when a parenthesis expression is between the function call and its argument

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go
`getRangeInterval()` makes me uncomfortable because it returns the 1st range interval found. Theoretically, due to how we use it, we should never call it with an `expr` that could have 2+ matrix selectors, but it's not enforced in the code.
In this PR I'm enforcing it, adding a check that will fail the mapping if we call it with an `expr` containing 2+ matrix selectors.
N/A
=> Add check to ensure we never parse multiple range intervals when mapping an instant query for splitting

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go
Similarly to #2575, `updateRangeInterval()` and `updateOffset()` functions make me uncomfortable because if, due to a bug, we call them with an `expr` containing multiple matrix or vector selectors we may end up with nasty bugs. I prefer to get them error out very clearly.
N/A
=> Enhance updateRangeInterval() and updateOffset() functions

operations/helm/charts/mimir-distributed/values.yaml
Reorganize chart values to avoid confusion, so that metaMonitoring values remains outside of enterprise features.
=> Move metaMonitoring values outside of enterprise features

cmd/mimir/main.go, docs/internal/contributing/README.md
Add `make help` tip to docs and remove useless type declare. I think adding a `make help` prompt to the documentation would be very helpful for contributors to start building mimir.
None
=> Add `make help` tip to docs and remove useless type declare

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/split_by_instant_interval_test.go
Fixes range splitting for `sum_over_time` and `count_over_time`, avoiding the overlaps in the ranges.
See the comment in the code that explains why we have to do this.
First commit is just adding the failing test case: now we run the tests with start aligned to a second, and start not aligned to a second. Honestly, I don't like the fact that with 3 nested tests Goland doesn't allow me run a specific testcase anymore, but I can't find a cleaner way to do this since we should test both.
Refers to a task of https://github.com/grafana/mimir-squad/issues/774
=> Fix overlapping time ranges when splitting instant queries

pkg/mimirtool/client/backfill.go
In `mimirtool`, use `block.MetaFilename` instead of "meta.json".
=> mimirtool: Use block.MetaFilename constant

pkg/compactor/block_upload.go
Fix compactor code to use `block.MetaFilename` constant, also improve language in a couple of comments.
=> compactor: Use block.MetaFilename constant

.github/workflows/compare-helm-with-jsonnet.yml
Also give meaningful names to steps that were called just "set -e" and "set +e".
Fixes https://github.com/grafana/mimir/issues/2607
=> Install go 1.18 for comparing helm vs jsonnet

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/split_by_instant_interval_test.go
**Note for reviewers:** please read the PR description containing the list of supported expressions before reviewing this PR.
This PR introduces the support of new range vector aggregators. This was done by taking into account 2 sources of data:
1) expressions that can be parallelized in the sharding AST mapper: https://github.com/grafana/mimir/blob/7f14ac6fc1094bceebbb0379c330db49b123577c/pkg/frontend/querymiddleware/astmapper/parallel.go#L25-L34
2) the list of Prometheus query functions: https://prometheus.io/docs/prometheus/latest/querying/functions/#functions
**Sharding AST mapper parallel expressions:**
By analyzing the expression list from the 1st point, the same result was concluded except for expressions sorting expressions:
* …
=> Add support for range vector aggregators

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/ha_tracker.go, pkg/ingester/instance_limits.go, pkg/ingester/limiter.go, pkg/querier/blocks_store_queryable.go, pkg/util/globalerror/errors.go, pkg/util/globalerror/errors_test.go, pkg/util/limiter/query_limiter.go, pkg/util/validation/errors.go
The error messages related to per-instance limits say the limit can be set on a per-tenant basis, which is wrong. For example:
```
the write request has been rejected because the ingester exceeded the samples ingestion rate limit (err-mimir-ingester-max-ingestion-rate). To adjust the related per-tenant limit, configure -ingester.instance-limits.max-ingestion-rate, or contact your service administrator.
```
In this PR I'm fixing it. As separate commits:
- [Renamed MessageWithLimitConfig() to MessageWithPerTenantLimitConfig()](https://github.com/grafana/mimir/commit/a75cdabdf906ce0901ec7c6cf36e6048c58cbcaa)
- [Fix error message for per-instance limits](https://github.com/grafana/mimir/commit/51bc2e9752c7dcaef8bc76bae7a5d54ea369b2b0)
N/A
=> Fix per-instance limits error messages

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
Currently if someone is migrating from cortex,
they set "fake" as the no_auth_tenant, but Helm installed nginx 
will try to inject "anonymous".
This commit fixes that and injects the value set in the mimir config
into X-Scope-OrgID.
Fixes #2563 
=> Helm: inject the no_auth_tenant as default in nginx

operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-overrides.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json, operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin/dashboards/compactor-resources.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overrides.libsonnet, operations/mimir-mixin/dashboards/reads-networking.libsonnet, operations/mimir-mixin/dashboards/reads-resources.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads-resources.libsonnet, operations/mimir-mixin/dashboards/rollout-progress.libsonnet, operations/mimir-mixin/dashboards/slow-queries.libsonnet, operations/mimir-mixin/dashboards/writes-networking.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet, operations/mimir-mixin/jsonnetfile.lock.json
I understand why we don't want to select all namespaces in the variables, as that would query too many metrics, bringing a useless amount of series to the frontend.
However, allowing "All" on the "cluster" variable, allows selecting the namespaces without having to select the cluster (which is often redundant), while it still requires selecting one specific namespace.
=> Allow "all" clusters in dashboard templating vars

pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_stats.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/split_by_instant_interval.go
Add instant splitting specific metric stats for instant query time splitting.
=> Add instant splitter metrics stats

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
When scraping metrics more than once per minute, the queue may have been empty in some intermediate scrapes, but this alert would still be triggered when the latest point is non-zero (for all the evaluations in the 5m range).
This is a quick solution to that without investing too many resources in developing a more sophisticated metric: we'll take a min_over_time of that last minute every time, and we won't alert if it went to 0 at some point in that minute (which is what we want).
Fixes https://github.com/grafana/mimir/issues/2625
=> Improve QueriesStuck alert by checking range min

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configure/about-tenant-ids.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, go.mod, pkg/compactor/compactor.go, pkg/mimir/mimir.go, pkg/mimir/modules.go, pkg/querier/blocks_store_queryable.go, pkg/storage/bucket/client.go, pkg/storage/bucket/delayed_bucket_client.go, pkg/storage/tsdb/users_scanner.go, pkg/storage/tsdb/users_scanner_test.go, pkg/storegateway/bucket_stores.go, pkg/usagestats/reporter.go, pkg/usagestats/seed.go, pkg/usagestats/seed_test.go
This PR is a first step to build the anonymous usage reporter as described in #1815.
In this PR I'm introducing the support for the cluster seed, stored in a dedicated prefix called `__mimir_cluster/`. The reason why I propose to use a dedicated prefix instead of storing the seed file in the root of the bucket is to have a prefix reserved for Mimir data in object storage. This also means that, starting from now, `__mimir_cluster` is no more a valid tenant ID.
Part of #1815
=> Added cluster seed support in preparation of anonymous usage reporter

docs/sources/operators-guide/mimir-runbooks/_index.md
Fix runbook `MimirTenantHasPartialBlocks` as compaction job log messages have changed.
=> runbooks: Fix MimirTenantHasPartialBlocks wrt. log messages

.github/workflows/helm-weekly-release-pr.yaml, .github/workflows/scripts/helm-weekly-release.sh, RELEASE.md
Adds a github actions job that creates a PR which updates the helm chart. https://github.com/grafana/mimir/pull/2622 is a PR created via the action.
The action runs at 12:00 UTC on Mondays and can also be triggered manually.
=> Automate weekly helm development release (without docs)

CHANGELOG.md, development/tsdb-blocks-storage-s3/docker-compose.jsonnet, development/tsdb-blocks-storage-s3/docker-compose.yml, docs/sources/operators-guide/configure/about-versioning.md, docs/sources/operators-guide/reference-http-api/index.md, integration/asserts.go, integration/e2emimir/services.go, pkg/api/api.go, pkg/compactor/tenant_deletion_api.go, pkg/compactor/tenant_deletion_api_test.go, pkg/mimir/modules.go
This PR moves the purger API endpoints to the compactor component.
There are two implementation decisions I made but am not entirely sure about:
* The endpoints are now under `/compactor`, not `/purger`.
* Internally, the endpoints were part of a seperate module: `TenantDeletion`. When transferring over the endpoints I merged them directly into the `Compactor` module instead of keeping the separate `TenantDeletion` module. My reasoning was that none of the other compactor API endpoints are part of a separate module.
Fixes #2190
=> Move purger API endpoints to compactor

pkg/mimir/mimir.go, pkg/mimir/modules.go, pkg/usagestats/report.go, pkg/usagestats/report_test.go, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go, pkg/usagestats/seed_test.go, pkg/usagestats/stats.go
In this PR I'm adding the logic to periodically send anonymous usage stats report. The report doesn't contain custom metrics yet (will be done in in the next PR). The default stats we send (and the frequency) are the exact same of the ones sent by Loki, to keep consistency.
Part of #1815
=> Periodically send anonymous usage stats report

cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, pkg/util/usage/usage.go
While reviewing #2633, I've realized `model.Duration` and few other data types are not correctly detected when building `--help`. This PR fixes it.
N/A
=> Fixed custom data type detection in --help and --help-all

.github/workflows/compare-helm-with-jsonnet.yml
Helm - jsonnet compare action was treating return code incorrectly
Relates to failed CI runs of https://github.com/grafana/mimir/pull/2666
=> Fix not getting error from helm-jsonnet compare

.github/workflows/compare-helm-with-jsonnet.yml, operations/compare-helm-with-jsonnet/helm/06-pods/kustomization.yaml, operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/chunks-cache/chunks-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/index-cache/index-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/metadata-cache/metadata-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/results-cache/results-cache-statefulset.yaml
Have default and allow setting security context for memcached exporter.
Request from GEM customer.
Mimir support esc 3505
=> Helm: allow setting security context for memcached exporter

pkg/distributor/distributor.go
I believe this comment is confusing. I noticed it because I've been trying to understand how the HA-deduping works and it didn't make sense to me until I realized this... The wording `checkReplica should only have returned an error if there was a real error` sounded to me like it would exclude the possibility that `checkReplica` returned an error simply because the current replica is not the elected replica.
=> remove confusing comment

GOVERNANCE.md
Re-orders team list to be alphabetical again.
NB: As per governance, Grafana Labs can update governance. That being said, I would prefer a few +1 just to make sure there's consensus, however uncontroversial this change should be.
=> Order team members alphabetically

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/mimirtool/config/descriptors/cortex-v1.11.0.json, pkg/mimirtool/config/descriptors/gem-v1.7.0.json, pkg/mimirtool/config/descriptors/gem-v2.3.0.json, pkg/mimirtool/config/descriptors/mimir-v2.3.0.json, pkg/mimirtool/config/inspect.go, pkg/util/usage/usage.go, tools/doc-generator/parse/parser.go
In the auto-generated config we have data types described as "list of X". Currently "X" is singular. I think plural is more correct, so I'm proposing to add an ending "s" like "list of strings" or "list of durations".
@dimitarvdimitrov Are the changes to the config conversion tool legit?
N/A
=> Add plurals to list config parameters

.github/workflows/compare-helm-with-jsonnet.yml
Change the Helm <> Jsonnet diff behavior to hide old comments instead of trying to edit an existing comment.
=> Hide stale jsonnet <> helm diff comments

CHANGELOG.md, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This PR allow to configure graph tooltip.
I’ve attached two screenshots, one is showing where is the option in the dashboard setting and the other one showing the result.
We can see the red vertical bar shared across all panels (but not the tooltips)
=> Dashboards: allow to configure graph tooltip

CHANGELOG.md, pkg/api/api.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Currently the HA-deduplication happens after the forwarding in the distributor, meaning that forwarding targets get the raw samples before deduplication. We'll want to move the HA-deduplication in front of the forwarding so that forwarding targets can also take advantage of the HA-deduplication.
This change also breaks up the distributor's giant `PushWithCleanup` method, which I think is a benefit because it's too large and hard to understand at the moment.
Fixes: https://github.com/grafana/mimir-squad/issues/784
=> implement HA dedupe as middleware

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/parallel.go, pkg/frontend/querymiddleware/astmapper/parallel_test.go, pkg/frontend/querymiddleware/astmapper/sharding.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go, pkg/frontend/querymiddleware/querysharding_test.go
We are seeing some queries with binary operations which get sharded, they legit from a correctness perspective, but perform badly because they have to transfer huge responses for partial queries from querier to query-frontend bcause one of the legs are not shardable or not aggregatable.
For example, consider this query:
```
max by(pod) (
max without(prometheus_replica, instance, node) (kube_pod_labels{namespace="test"})
*
on(cluster, pod, namespace) group_right() pod:container_cpu_usage:sum
)
```
Currently it gets sharded as:
```
max by(pod) (
max without(prometheus_replica, instance, node) (
concat(
max without(prometheus_replica, instance, node) (kube_pod_labels{namespace="test",shard="1"}
max without(prometheus_replica, instance, node) (kube_pod_labels{namespace="test",shard="2"}
max …
```
=> Query sharding: shard binary operations only if it doesn't lead to non-shardable vector selectors in one of the operands

CHANGELOG.md, tools/markblocks/main.go
This PR modifies `markblocks` tool to process multiple blocks concurrently. Markblocks still exits on first failure with status code 1.
=> markblocks now uploads markers for multiple blocks concurrently

CHANGELOG.md, integration/alertmanager_test.go, pkg/alertmanager/api.go, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
Changes the status code when alertmanager isn't configured for a tenant to `412 Precondition Failed` and logs an info message
Fixes #2265
=> Return status code `412` and log when alertmanager config is not found

CHANGELOG.md, development/tsdb-blocks-storage-s3/config/otel-collector.yaml, pkg/util/push/otel.go, pkg/util/push/push.go, pkg/util/push/push_test.go
Adds gzip compression support to OTLP (which is on by default).
=> Add gzip compression support to OTLP

CHANGELOG.md, go.mod, go.sum, vendor/github.com/prometheus/prometheus/tsdb/head_append.go, vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go, vendor/modules.txt
This commit updates the vendored version of mimir-prometheus.
The highlights are:
- Removed expensive atomic load call from head append, this should make the hot write path slightly more performant https://github.com/grafana/mimir-prometheus/pull/313
- Fixed out-of-order query bug that happened due to invalid LabelValues responses from the OOOHeadIndexReader that led to wrong query results. This should fix a known bug we had on queries when out of order was enabled. This issue was more common when query sharding was used together with out-of-order due to postings cache corruption. https://github.com/grafana/mimir-prometheus/pull/314
=> Bring latest changes from mimir-prometheus

CHANGELOG.md, go.mod, pkg/mimir/mimir.go, pkg/mimir/tracing.go, pkg/mimir/tracing_test.go
In the PR https://github.com/grafana/mimir/pull/1695 we upgraded the vendored Prometheus, which included a change to the tracing, migrating from opentracing to opentelemetry. This change broke the reporting of tracing spans from PromQL engine, which are particularly useful when investigating slow queries.
I think the clean way to fix it would be migrating Mimir (and so `weaveworks/common`) to opentelemetry library, but it's risky change to ensure we don't break backward compatibility and I would recommend to do it but carefully.
As a quicker fix, I'm proposing to introduce a bridge to implement the opentelemetry tracer interface but using opentracing (and jaeger client specifically) under the hood. The opentelemetry library provides the bridge for the opposite direction only, so I had to …
=> Fix reporting of tracing spans from PromQL engine

CHANGELOG.md, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go, pkg/mimirpb/timeseries.go, pkg/mimirpb/timeseries_test.go
This PR modifies forwarder to discard exemplars. In general we should perhaps introduce new option to allow/disable forwarding of exemplars, but for now this works.
=> Discard exemplars when forwarding them.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
After merging #2603, instance limits checks are done only after running HA deduplication. That's not correct. This PR moves instance limits checks into its own middleware, and makes it the first middleware to run.
=> Extract instance limits check into middleware, that runs before any other distributor middlewares

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/util/slice_operations.go, pkg/util/slice_operations_test.go
Breaks the relabel/drop_label rules out of the `PushWithCleanup()` method and moves them into a middleware which gets applied at an earlier stage in the distributor's request processing.
=> apply relabel and drop_label rules before forwarding rules in distributor

CHANGELOG.md, pkg/mimirpb/timeseries.go, pkg/mimirpb/timeseries_test.go
This PR is a follow-up to #2710. When doing deep copy of request without exemplars, computed buffer size used for copying request was bigger than necessary. At the same time, by nil-ing `Exemplars` field we thrown away previously allocated slice for exemplars, which could be reused.
=> Fix sizing of buffer and don't nil exemplars buffer.

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/query.go
Add a counter for tracking the number of chunks that could be entirely discarded
as duplicates of an existing chunk when querying ingesters. This is a requirement
of testing distributor <-> ingester timeout changes.
N/A
=> Add counter for chunks from ingesters entirely deduplicated

CHANGELOG.md, cmd/metaconvert/Dockerfile, cmd/mimir-continuous-test/Dockerfile, cmd/mimir/Dockerfile, cmd/mimirtool/Dockerfile, cmd/query-tee/Dockerfile, development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile, development/tsdb-blocks-storage-s3/dev.dockerfile, development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile, packaging/fpm/Dockerfile
Upgrades alpine from 3.16.0 to 3.16.2. The previous upgrade to 3.16.0 put 3.16 in some development files so I specified the full version again for consistency.
N/A
=> Chore: Upgrade alpine to 3.16.2

pkg/mimir/mimir.go, pkg/mimir/mimir_test.go
This PR fixes a bug where Mimir panics if started targeting a module which doesn't depend on the API ~~, as `t.API` is thus not initialized when accessed in `RegisterServiceMapHandler()`~~ by just erroring when starting with any internal module.
```
➜  mimir git:(main) ✗ ./mimir --config.file=demo.yaml -target=server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x19ca69d]
goroutine 1 [running]:
github.com/grafana/mimir/pkg/api.(*API).RegisterServiceMapHandler(0x0, {0x2571120, 0xc00084eb10})
/home/levi/Desktop/projects/grafana/mimir/pkg/api/api.go:410 +0x5d
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run(0xc0007fca00)
/home/levi/Desktop/projects/grafana/mimir/pkg/mimir/mimir.go:560 +0x2b3
main.main() …
```
=> Fix panic when starting Mimir targeting modules that don't depend on the API

CHANGELOG.md, pkg/mimirtool/version/version.go
Fixes a bug where version checking was broken
```
$ mimirtool version
Mimirtool, version 2.2.0 (branch: HEAD, revision: 65344e2ed)
go version:       go1.17.8
platform:         darwin/arm64
checking latest version... A newer version of mimirtool is available, please update to mimir-2.2.0
```
Also adds a link to the release
```
$ cmd/mimirtool/mimirtool version
Mimirtool, version 2.3.0 (branch: dimitar/fix-mimirtool-version-check, revision: 64c5aefa8)
go version:       go1.18.4
platform:         darwin/arm64
checking latest version... A newer version of mimirtool is available, please update to 2.2.0 https://github.com/grafana/mimir/releases/tag/mimir-2.2.0
```
=> Fix version checking in mimirtool

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
When I upstreamed the multi-zone support to jsonnet (https://github.com/grafana/mimir/pull/1352) I forgot to upstream the `RolloutOperatorNotReconciling` alert we're using at Grafana Labs. Doing it in this PR.
N/A
=> Added RolloutOperatorNotReconciling alert

CHANGELOG.md, docs/sources/operators-guide/configure/about-versioning.md
In this PR I'm adding the CHANGELOG entry about anonymous usage stats work (currently disabled by default). I will work on the documentation changes in a follow up PR.
Part of #1815
=> Add CHANGELOG entry about anonymous usage stats

CHANGELOG.md, docs/sources/operators-guide/reference-http-api/index.md, pkg/api/api.go, pkg/mimir/modules.go
Adds the `/prometheus`-prefixed `buildinfo` endpoint to the ruler. This endpoint is exposed by all other components (querier, query-frontend) that use the `<prometheus-http-prefix>`, except the ruler.
Fixes #2678
=> Add prometheus-prefixed buildinfo endpoint to ruler

CHANGELOG.md, docs/sources/operators-guide/tools/mimir-continuous-test.md, pkg/continuoustest/client.go
Added basic authentication support to mimir-continuous-testing for when Mimir is behind a gateway authenticating the calls.
Fixes #2105
=> mimir-continuous-test tool: Add basic authentication support

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/query.go
Add a counter for tracking the number of chunks that could be entirely discarded
as duplicates of an existing chunk when querying ingesters. This is a requirement
of testing distributor <-> ingester timeout changes.
cherry-pick of 8a13ad4995ef84eab7cb4340ce36610dee9cb15f
=> Add counter for chunks from ingesters entirely deduplicated (#2713)

operations/helm/charts/mimir-distributed/ci/test-enterprise-configmap-values.yaml, operations/helm/charts/mimir-distributed/ci/test-enterprise-values.yaml, operations/helm/charts/mimir-distributed/ci/test-oss-values.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/chunks-cache/chunks-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/index-cache/index-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/metadata-cache/metadata-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/results-cache/results-cache-statefulset.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
During the development of https://github.com/grafana/mimir/pull/2087 helm CI runs (call-lint-test / lint-test) started failing because pods could not be scheduled ([example](https://github.com/grafana/mimir/runs/7856053868?check_suite_focus=true)). The info at the end of the run which describes all pods showed the following for two pods:
```
Events:
Type     Reason            Age                 From               Message
----     ------            ----                ----               -------
Warning  FailedScheduling  11s (x13 over 10m)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
```
GitHub hosted runners only have 2 CPUs and 7GB of memory ([docs](https://docs.github.com/en/actions/using-github-hosted-ru …
=> Disable resource requests in Helm CI runs

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
Upgrades the nginx image used in the helm chart (non-enterprise) from `1.19-alpine` to `1.22-alpine`, which is the current stable version. Sanity tested with a local helm install and didn't run into any issues.
Related to https://github.com/grafana/mimir-squad/issues/819
=> Upgrade nginx image to 1.22-alpine

CHANGELOG.md, pkg/usagestats/report.go, pkg/usagestats/reporter.go, pkg/usagestats/reporter_test.go
While working on https://github.com/grafana/mimir/pull/2685 I realized it's not very good we regenerate a new report when we retry sending it after a failure. The main reason is that counter metrics are reset each time we generate a new report.
In this PR I'm proposing to resend the previously generated report when we resend it.
Part of #1815
=> Fix usage stats report resend logic to not generate a new report each time we retry sending it

operations/compare-helm-with-jsonnet/components/config/kustomization.yaml, operations/compare-helm-with-jsonnet/helm/03-labels/kustomization.yaml, operations/compare-helm-with-jsonnet/helm/06-pods/kustomization.yaml, operations/compare-helm-with-jsonnet/jsonnet/01-ignore/kustomization.yaml, operations/compare-helm-with-jsonnet/jsonnet/03-rename/kustomization.yaml, operations/compare-helm-with-jsonnet/jsonnet/04-labels/kustomization.yaml, operations/compare-helm-with-jsonnet/jsonnet/06-services/kustomization.yaml
After merging #2087 the differences between helm and jsonnet reduced slightly. In turn I had to add the query-scheduler to many exceptions like labels, annotations, irrelevant config and service names.
=> Add query-scheduler exceptions for jsonnet<>helm diff

Makefile, cmd/mimir/main.go, cmd/mimirtool/main.go, pkg/mimir/mimir.go, pkg/mimir/mimir_test.go, pkg/mimir/modules.go, pkg/mimir/modules_test.go, pkg/mimir/server_service_test.go, pkg/mimirtool/commands/bucket_validation.go, pkg/mimirtool/commands/rules.go, pkg/util/validation/validate.go
I'm working to add read-write deployment mode support to Mimir and I've found it's annoying to unit test because of the usage of the global Prometheus registerer. Long time ago we started a code cleanup to avoid using it and I think we're very close.
In this PR I'm removing the usage of `prometheus.{MustRegister,Register,DefaultRegisterer}` from `pkg/...`. This unblocks my work on read-write deployment mode.
N/A
=> Reduce usage of global Prometheus registerer

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
We just merged a PR https://github.com/grafana/mimir/pull/2683 to add HTTP-over-gRPC support to query-tee so we can finally use it for tee-ing remote rule evaluation too. When ruler remote evaluation goes through the query-tee, the ruler-query-frontend receive the request over plain HTTP (instead of HTTP-over-gRPC). In this PR I'm adding support for plain HTTP requests to ruler-query-frontend in the "Remote ruler reads" dashboard.
N/A
=> Added support to query-tee in front of ruler-query-frontend in the "Remote ruler reads" dashboard

CHANGELOG.md, pkg/distributor/distributor.go
Add per-tenant counters for total and received requests to provide visibility
into what an appropriate value for a per-tenant request limit might be.
N/A
=> Distributor: add per-tenant counters for total and received requests

CHANGELOG.md, integration/e2emimir/client.go, integration/ruler_test.go, pkg/querier/distributor_queryable.go, pkg/querier/querier.go
Addresses a bug in which alert states are not restored.
After starting the prometheus ruler tries to restore the "firing" state for all alerts that are active. The way it does this is by:
1. evaluating all groups twice ([code](https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor/github.com/prometheus/prometheus/rules/manager.go#L410-L432)):
* once so most evaluate to active or non-active
* once more to make sure that it has scraped enough metrics for alerts to be able to evaluate to active/non-active (in case of Mimir "to make sure that Mimir has ingested enough metrics for alerts to be able to ...")
2. compares the rule groups' "for" period to its for grace period ([code](https://github.com/grafana/mimir/blob/8fca3461c1e9f74cdbc98a8fc1fcfbbdcbbe24da/vendor …
=> Fix ruler alert state restoration 

CHANGELOG.md, docs/sources/operators-guide/architecture/components/query-frontend/index.md, pkg/querier/engine/config.go, pkg/querier/engine/query_tracker.go, pkg/querier/engine/query_tracker_test.go
Set unlimited max concurrency in PromQL engine and update test.
Fixes https://github.com/grafana/mimir/issues/1298
=> Set unlimited max concurrency in PromQL engine

docs/sources/operators-guide/mimir-runbooks/_index.md
This PR updates the Mimir runbook with information regarding the `compactor.partial-deletion-delay` flag.
=> updated runbook with partial block delay flag

pkg/distributor/distributor.go, pkg/distributor/ha_tracker.go, pkg/frontend/querymiddleware/roundtrip.go, pkg/util/metrics_helper.go, pkg/util/validation/validate.go
Switches from Mimir's own `DeleteMatchingLabels()` to client_golang's new `DeletePartialMatch()`.
Fixes #1764
=> Use `DeletePartialMatch()`

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/config.libsonnet
In this PR I'm adding a basic support for read-write deployment mode in the dashboards. Resources and networking dashboards are not addressed yet (will be done in a follow up PR).
Part of #2749
=> Dashboards: added support to experimental read-write deployment mode

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go
This creates a metrics middleware in the distributor which updates the metrics that should include all requests as they arrive, without any modifications.
It also adds tests to check whether the metrics get updated to the correct values in various scenarios where requests get modified by distributor middlewares.
Fix issue #2783
At first I intended to also implement the short-circuit which @56quarters has suggested [here](https://github.com/grafana/mimir/pull/2786#discussion_r950441966), but I figured this PR is already complicated enough as it is. Once it is merged the tests which get added by this PR should help with implementing that suggestion.
=> move certain distributor metrics into their own middleware

docs/sources/operators-guide/configure/configure-tsdb-block-upload.md, docs/sources/operators-guide/tools/mimirtool.md
In particular, called out the fact that we today don't validate blocks at upload time, though we do eventually intend to do this.
=> Made some tweaks to the documentation for the block upload functionality

CHANGELOG.md, go.mod, go.sum, vendor/github.com/prometheus/prometheus/tsdb/compact.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/modules.txt
Brings in this fix https://github.com/grafana/mimir-prometheus/pull/320/
=> Upgrade mimir-prometheus

CHANGELOG.md, docs/sources/operators-guide/configure/about-versioning.md, docs/sources/operators-guide/reference-http-api/index.md
Updated the docs to remove the experimental labels on the delete tenant API as we are promoting this to stable.
=> Removed the experimental labels on the delete tenant API.

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin/dashboards/reads.libsonnet
In https://github.com/grafana/mimir/pull/821 I migrated query-frontend to use the same memcached client as blocks storage, and this changed the metrics exposed by it too. This change was included in Mimir 2.0.0, but I kept querying the old metric in the panel called "Latency (old)" to offer a smoother transition for people migrating from Cortex. Given we're now releasing Mimir 2.3.0 (and so this proposed change will be included in 2.4.0), I think it's time to remove "Latency (old)" panel and just keep the Mimir metric.
N/A
=> Remove the "Cache - Latency (old)" panel from the "Mimir / Queries" dashboard

operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/lib/pdb.tpl
For #2711 we want to nest the graphite components under `graphite` in the values.yaml.
A problem we have is that some of named templates within the chart need to grab the raw values from the values.yaml in order to automatically set things like pod labels and annotations. And those named templates do not know how to work with nested values. There is already a helper `mimir.componentSectionFromName` which infers the _name_ of the section in the values from the component name. 
This PR changes `mimir.componentSectionFromName` to have a hardcoded YAML section for each component. 
The PR also introduces a change in how `mimir.componentSectionFromName` is used. It now returns the values as YAML instead of just the name of the section. So its result should be parsed with `fromYaml`
=> Add explicit component section mapping in Helm helper

pkg/frontend/querymiddleware/querysharding_test.go
Test that querysharding works correctly with aggregations on top of queries that don't select a metric name.
N/A
=> TestQueryShardingCorrectness: __name__!=""

operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/admin-api/admin-api-dep.yaml, operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml, operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/distributor/distributor-dep.yaml, operations/helm/charts/mimir-distributed/templates/gateway/gateway-dep.yaml, operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl, operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml, operations/helm/charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml, operations/helm/charts/mimir-distributed/templates/querier/querier-dep.yaml, operations/helm/charts/mimir-distributed/templates/query-frontend/query-frontend-dep.yaml, operations/helm/charts/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml, operations/helm/charts/mimir-distributed/templates/ruler/ruler-dep.yaml, operations/helm/charts/mimir-distributed/templates/smoke-test/smoke-test-job.yaml, operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/tokengen/tokengen-job.yaml
mimir.podLabels now includes the user defined podLabels for components.
This makes this template consistent with podAnnotations.
Fixes #2737 
- [N/A] Tests updated deferred to static checks
- [N/A  internal] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> Helm: include user podLabels for components in named template

CHANGELOG.md, cmd/mimir/config-descriptor.json, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go, pkg/util/validation/limits.go
This PR adds `forwarding_endpoint` to per-tenant limits, which takes precedence over forwarding-rule-specific endpoints. Endpoints in forwarding rules will be removed next.
=> Introduce single forward endpoint to simplify configuration.

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-config.json, operations/mimir-mixin-compiled/dashboards/mimir-object-store.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This appears to stem from missing features and confusion: it was originally set at 1m, and I think that was because Grafana at the time didn't have `$__range_interval`.
Grafana now lets you configure a scrape interval on your datasource, which is more likely to be correct for your environment than hard-coding it into these dashboards.
=> Dashboards: stop setting 15s "interval"

operations/helm/charts/mimir-distributed/templates/ingester/ingester-dep.yaml, operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml, operations/helm/charts/mimir-distributed/templates/validate.yaml
It's in the wrong place, preparing for multizone.
=> Helm: move ingester deployment validation to validate.yaml

CHANGELOG.md, docs/sources/operators-guide/monitor-grafana-mimir/requirements.md, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Add support for baremetal deployments for the *resources* dashboards.
The default remains `deployment_type: 'container'`, hence the mixin-compiled remains unchanged.
To test new dashboards update the configuration to `deployment_type: 'baremetal'` then build the mixins.
Relates #1642
=> Baremetal dashboards

pkg/mimirtool/client/client.go, pkg/mimirtool/commands/alerts.go, pkg/mimirtool/commands/rules.go
We introduced a bug https://github.com/grafana/mimir/pull/1822 causing `mimirtool rules load` and other commands not working if the API legimately return 404 (e.g. no rules configured yet). The bug was introduced wrapping the error returned by the API client and so the error equality check doesn't work anymore. This PR fixes it.
_No CHANGELOG entry because introduced after 2.2.0 and I want to cherry-pick this fix in 2.3.0._
N/A
=> Fix mimirtool commands issued to API returning 404

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, docs/sources/operators-guide/mimir-runbooks/_index.md, pkg/distributor/distributor.go, pkg/util/globalerror/errors.go, pkg/util/http.go, pkg/util/http_test.go, pkg/util/push/otel.go, pkg/util/push/push.go, pkg/util/push/push_test.go
Add messageSizeLargerErrFmt error to errors catalog.
Fixes #2432
=> Add messageSizeLargerErrFmt error to errors catalog

development/mimir-read-write-mode/config/grafana-agent.yaml, development/mimir-read-write-mode/config/mimir.yaml, development/mimir-read-write-mode/docker-compose.jsonnet, development/mimir-read-write-mode/docker-compose.yml
When working on https://github.com/grafana/mimir/pull/2838 I've found annoying that each replica in the local dev env customize the HTTP and gRPC port. We don't really need it, we just need the published port to be different.
In this PR I'm using the default HTTP (8080) and gRPC (9095) ports, and then using a different port for each replica when publishing them to the host (keeps the previous published port number).
N/A
=> Use default HTTP and gRPC ports in the read-write local dev env

CHANGELOG.md, integration/ingester_limits_test.go, integration/single_binary_test.go, pkg/alertmanager/alertstore/bucketclient/bucket_client.go, pkg/mimir/mimir.go, pkg/mimir/mimir_test.go, pkg/mimir/sanity_check.go, pkg/mimir/sanity_check_test.go, pkg/ruler/rulestore/bucketclient/bucket_client.go
While answering the question https://github.com/grafana/mimir/discussions/2698#discussioncomment-3464676 I've realized that if you set overlapping local directories for different purposes you could end up with weird behaviour (e.g. alertmanager deleting the alerts store content). These errors are quite difficult to detect, so in this PR I'm proposing to introduce a sanity check to ensure the configured filesystem directories don't overlap for different components (checking only the running components).
Thought: the logic encoded in this new check is non trivial, but that's one more reason why we should encode it instead of letting our users figuring out through a try-and-error process.
N/A
=> Add sanity check at startup to ensure the configured filesystem directories don't overlap for different components

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet, operations/mimir-mixin/jsonnetfile.json, operations/mimir-mixin/jsonnetfile.lock.json
This is now ["the default and primary way to visualize time series data"](https://grafana.com/docs/grafana/latest/visualizations/time-series/); the 'graph' panel has been deprecated.
Uses upstream change https://github.com/grafana/jsonnet-libs/pull/824
So far I have only changed the per-pod latency panels, as those are the ones where exemplars work.
=> Dashboards: use timeseries panel to show exemplars

CHANGELOG.md, integration/query_frontend_test.go, pkg/api/error/error.go, pkg/frontend/querymiddleware/codec.go, pkg/frontend/querymiddleware/codec_test.go
Fixes https://github.com/grafana/mimir/issues/2693.
Make sure we don't retry the 413 error.
=> Fix query sharding with too large entry query error

docs/sources/operators-guide/mimir-runbooks/_index.md
@replay wrote a new query for finding the top tenants on the top loaded ingesters in a cluster. This PR replaces the current two queries that we used to achieve the same during rebalancing of tenants' shards. 
=> Update runbook query for top tenants per ingester

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/NOTES.txt, operations/helm/charts/mimir-distributed/templates/gateway/gateway-svc.yaml, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/gateway/gateway-svc.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/gateway/gateway-svc.yaml
We opened 8080 by default default and this is kept as legacy.
NOTEX.txt assumed we open port 80 by default, this is fixed by encoding
80 in the values file.
Updated docstring.
Relates to: #2203
=> Helm: open port 80 on enterprise gateway

pkg/storegateway/bucket.go
I've seen some extremely slow requests go into this code and our tracing
ends at the previous level: "blockSeries() lookup series". This will help
figure out where the time is being spent.
N/A
=> Add tracing to store-gateway bucket index reader methods

Makefile
Fixes an issue where we had duplicate dist directives in our makefile which caused an issue while building release packages. This cleans up the hacked makefile I was running earlier and fixes the issue going forward.
=> Remove duplicate dist directive

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/charts/mimir-distributed/templates/role.yaml, operations/helm/charts/mimir-distributed/templates/rolebinding.yaml, operations/helm/charts/mimir-distributed/templates/securitycontextconstraints.yaml, operations/helm/charts/mimir-distributed/values.yaml
PodSecurityPolicy (PSP) was deprecated as part of kubernetes 1.25
This PR removed the PSP for versions higher than or equal to 1.25
Related to https://github.com/grafana/mimir/issues/2201
closes https://github.com/grafana/mimir/pull/2428
=> Helm: Remove PSP if kubernetes doesn't support it

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/README.md, operations/helm/charts/mimir-distributed/README.md.gotmpl, operations/helm/charts/mimir-distributed/templates/NOTES.txt
Update helm changelog after release branch merge to main.
Also add important note about people needing to pay attention to CHANGELOG.
=> Helm: update changlog and notes

development/mimir-microservices-mode/docker-compose.jsonnet, development/mimir-microservices-mode/docker-compose.yml, development/mimir-monolithic-mode/docker-compose.yml, development/mimir-read-write-mode/docker-compose.jsonnet, development/mimir-read-write-mode/docker-compose.yml, docs/sources/tutorials/play-with-grafana-mimir/docker-compose.yml
The environment variables for the root credentials of `minio` are no longer named `MINIO_ACCESS_KEY` and `MINIO_ACCESS_SECRET`, but are named `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` since the release on 2021-04-22.
This change introduces the new environment variable names and removes the deprecation notices.
Source:
https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#root-credentials
=> Fix deprecation warning for minio root-credentials

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet
Add a new panel to the store-gateway section of the "Mimir / Reads" dashboard for the total number of inflight object store requests from the store-gateways.
N/A
=> Add panel for inflight object store requests to reads dashboard

CHANGELOG.md, pkg/ruler/compat.go
Panic is on 2.3.0-rc0
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7126c0]
goroutine 108 [running]:
net/url.(*URL).String(0x0)
/usr/local/go/src/net/url/url.go:800 +0x40
github.com/grafana/mimir/pkg/ruler.DefaultTenantManagerFactory.func1({0x257e040, 0xc000139b80}, {0xc000945973, 0x9}, 0x0?, {0x25641e0, 0xc000607720}, {0x2577428?, 0xc0004f0050})
/__w/mimir/mimir/pkg/ruler/compat.go:273 +0x345
github.com/grafana/mimir/pkg/ruler.(*DefaultMultiTenantManager).newManager(0xc00083f900, {0x257e040, 0xc000139b80}, {0xc000945973, 0x9})
/__w/mimir/mimir/pkg/ruler/manager.go:219 +0x163
```
This happens because the parsing in dskit places a nil in the URL when
the value in YAML is an empty string. By …
=> Fix panic when ruler.external_url is set to empty string

go.mod, pkg/ruler/rulestore/config.go, pkg/ruler/rulestore/config_test.go
The idea of `rulestore.IsDefaults()` is to check whether the ruler has been configured by the user. However `reflect.DeepEqual()` checks all data within the Config struct, including things which are not actually config.
This change skips any fields within the config marked as `yaml:"-"`, which are not settable from yaml and therefore not config.
Using package `github.com/google/go-cmp/cmp`, which is documented as "not for use in production" since it panics when it cannot compare things. However we should catch that in unit testing, so should be ok.
(Note gRPC also uses this package).
Added a test which (artificially) induces the problem.
- NA `CHANGELOG.md` updated - not user-facing
=> ruler: ignore non-config values when checking defaults

CHANGELOG.md, pkg/mimir/mimir.go, pkg/mimir/mimir_test.go
See: https://github.com/grafana/mimir/issues/2867#issuecomment-1246449845
Fixes #2867
=> Fix sanity check done on configured filesystem directories when running Alertmanager in microservices mode

CHANGELOG.md, pkg/mimir/mimir.go, pkg/mimir/mimir_test.go
Cherry-picking the fix done in #2947.
N/A
=> Fix sanity check done on configured filesystem directories when running Alertmanager in microservices mode (#2947)

pkg/storegateway/bucket.go
I am concerned this could contribute to the store gateway latency.
Revert "Add tracing to store-gateway bucket index reader methods (#2879)"
This reverts commit 4e9ebc70be3b0e2bd5fe365c43a30cb12a990c3f.
=> This tracing is producing 720k spans in a single trace in the store-gw

docs/sources/operators-guide/configure/configuring-high-availability-deduplication.md, pkg/mimirtool/commands/rules.go
Fix spelling typo in "tenant" across codebase
None
- [ X ] Documentation added
=> Fix typo on tenant spelling

.github/CODEOWNERS, CODEOWNERS
There are a couple of issues with our CODEOWNERS:
- We have 2 of them
- `@mimir-maintainers` is invalid, it should actually be `@grafana/mimir-maintainers`
N/A
=> Fix CODEOWNERS

CHANGELOG.md, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir/autoscaling.libsonnet
[By default](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior), autoscaling allows to scale down to minReplicas in one go. This is
problematic in cases where the external metric source for autoscaling is
unavailable for longer than the stabilization window for scaling down.
That window is 5m by default.
If the scaling metric needs some time to start increasing (if for
example it's using sum(rate()) over longer periods), this scale down
will take longer to recover from. This PR allows to scale down only 10%
of replicas every 1m. This will give more time for the metric source to
scrape metrics and for the scaling metric to stabilize before we reach
minReplicas.
- …
=> Add scale down policies for autoscaling

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/nginx/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/nginx/nginx-v2-hpa.yaml, operations/helm/charts/mimir-distributed/templates/nginx/nginx-v2beta1-hpa.yaml, operations/helm/charts/mimir-distributed/templates/validate.yaml
The autoscaling/v2beta1 HorizontalPodAutoscaler is [removed in Kubernetes 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125) in favour of autoscaling/v2. This creates a different resource for the HPA if the kubernetes version is >=1.25.
I still haven't tested that the below works on 1.25, but the manifests seem to comply with the [API spec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec).
Keeping in draft until I can verify this works with 1.25
Related to https://github.com/grafana/mimir/issues/2201
=> Helm: add autoscaling/v2 horizontalPodAutoscaler for nginx

CHANGELOG.md, go.mod, go.sum, integration/querier_remote_read_test.go, vendor/github.com/weaveworks/common/httpgrpc/httpgrpc.proto, vendor/github.com/weaveworks/common/httpgrpc/server/server.go, vendor/github.com/weaveworks/common/middleware/logging.go, vendor/github.com/weaveworks/common/middleware/response.go, vendor/modules.txt
This PR fixes a 400 response while handling a streaming remote read request with an "Accept-Encoding" header.
Fixes https://github.com/grafana/mimir/issues/2929
=> Fix 400 response while handling streaming remote read

docs/internal/contributing/README.md, docs/internal/contributing/contributing-to-helm-chart.md
Some make targets require this to be installed otherwise they do the
wrong thing.
=> Mention gnu-sed for contributors on macOS

CODEOWNERS
Yesterday I fixed CODEOWNERS in https://github.com/grafana/mimir/pull/2960, but now we can't merge any PR touching `/docs/` without Ursula approval, even if we just change a single letter or changes to the internal doc. I propose to use our best judgement and wait for docs squad review when we real changes to the doc.
N/A
=> Fix docs requirement in CODEOWNERS

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/capped-large.yaml, operations/helm/charts/mimir-distributed/capped-small.yaml, operations/helm/charts/mimir-distributed/large.yaml, operations/helm/charts/mimir-distributed/small.yaml
#2722 replaced some podAntiAffinities with topologySpreadConstraints,
aiming to provide a quick getting-started experience. It is recommended
to run with podAntiAffinity in production though. So this PR updates the
sizing plans to reflect this recommendation.
Fixes https://github.com/grafana/mimir/issues/2681
=> Helm: add podAntiAffinity to the size plans

operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin/config.libsonnet
Make the config more consistent.
=> mixin: Consistently enclose all job_name regexes

development/mimir-monolithic-mode/config/mimir.yaml, development/mimir-monolithic-mode/docker-compose.yml
In #2957 I've enabled query-scheduler in the monolithic local dev env, but we don't expect people running the monolithic version to run the query-scheduler (given it's not part of `-target=all`), so in this PR I'm reverting the change to the local dev env.
This PR addresses the [feedback received here](https://github.com/grafana/mimir/pull/2957#discussion_r974338322).
N/A
=> Chore: do not run query-scheduler in monolithic local dev env

RELEASE.md
Since we're late on 2.3 release, Mimir maintainers agreed to postpone 2.4 release by 3 weeks. I will also shepherd it.
N/A
=> Marco will shepherd 2.4 release on 10th Oct 2022

pkg/querier/worker/worker.go, pkg/scheduler/schedulerdiscovery/discovery.go, pkg/util/servicediscovery/dns.go, pkg/util/servicediscovery/ring.go, pkg/util/servicediscovery/ring_test.go
In https://github.com/grafana/mimir/pull/2957 I've introduced an (optional) ring for the query-scheduler. The next step will be introducing support for "max query-scheduler active replicas" as part of the [read-write deployment mode support](https://github.com/grafana/mimir/issues/2749), but before that I would like to do a refactoring to simplify the diff of the next PR.
In this PR, as separate commits:
- [Move DNS watcher to pkg/util/servicediscovery/](https://github.com/grafana/mimir/commit/68cd173d2ae7841af5e5d4f9e0a7181c3295ca2a)
- [Renamed dnsWatcher to dnsServiceDiscovery](https://github.com/grafana/mimir/commit/18bbe069d39960d04039b98b76b6a1cc4fadc5a6)
- [Moved ring-based service discovery to pkg/util/servicediscovery/ and removed redundant notifications …
=> Chore: refactor service discovery implementation

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/distributor/forwarding/config.go, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go
This PR implements forwarding of requests via `httpgrpc.HTTP/Handle` method, instead of plain HTTP. To use this, forwarding URL must be in form of `httpgrpc://<host>:<port>/path`, where `<host>:<port>` will be used as address of gRPC server and path will be put into `url` field of `httpgrpc.HTTPRequest` message.
=> Distributor: Support for forwarding request via httpgrpc

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configure/about-versioning.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, integration/query_scheduler_test.go, pkg/frontend/v2/frontend_scheduler_worker.go, pkg/frontend/v2/frontend_test.go, pkg/querier/worker/worker.go, pkg/querier/worker/worker_test.go, pkg/scheduler/schedulerdiscovery/config.go, pkg/scheduler/schedulerdiscovery/config_test.go, pkg/scheduler/schedulerdiscovery/discovery.go, pkg/scheduler/schedulerdiscovery/ring.go, pkg/util/servicediscovery/dns.go, pkg/util/servicediscovery/ring.go, pkg/util/servicediscovery/ring_test.go
This PR is a follow up https://github.com/grafana/mimir/pull/2957. In https://github.com/grafana/mimir/pull/2957 I introduced the ring for query-scheduler. In this PR I'm adding support to configure a max number of query-scheduler instances effectively used. This setting is 0 by default, which means all available query-schedulers are used. However, in the read-write deployment we'll set this to 2, in order to use only 2 query-schedulers regardless how many backend replicas you're running.
**How it works**:
- Added `-query-scheduler.max-used-instances` config option (experimental). When > 0, the queries are enqueued on the configured max number of query-scheduler instances. It's only supported by query-scheduler ring discovery for now (there's a config validation check).
- The …
=> Add max query-scheduler instances support

CHANGELOG.md, pkg/frontend/v2/frontend_scheduler_worker.go, pkg/querier/worker/frontend_processor.go
While testing #3005 I've noticed that when the query-scheduler is shutting down the query-frontend and querier logs a stream of "error contacting scheduler". I noticed the hardcoded backoff used for retries is quite short, so I propose to increase it a bit.
N/A
=> Increase backoff period used to retry connections to query-frontend / query-scheduler

docs/sources/operators-guide/configure/about-versioning.md
In the list of experimental features we still have the old (now removed) `-blocks-storage.bucket-store.index-header-thread-pool-size` config param, instead of `-blocks-storage.bucket-store.index-header.map-populate-enabled`. The latter was already marked as experimental in the CHANGELOG.
N/A
=> Docs: fixed list of experimental features

CHANGELOG.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/distributor/forwarding/config.go, pkg/frontend/v2/frontend.go, pkg/ingester/client/client.go, pkg/querier/worker/worker.go, pkg/ruler/remotequerier.go, pkg/ruler/ruler.go, tools/doc-generator/parse/parser.go, tools/doc-generator/parse/root_blocks.go, tools/doc-generator/writer.go
Looking at #2996 made me realise the gRPC client config is duplicated a lot across the auto-generated config. In this PR I'm proposing to add a dedicated section for it.
As separate commits:
- [Define a block for the grpc client config documentation](https://github.com/grafana/mimir/commit/2f1f499b2d4a55d788d4bd7f26febeea931d62cd)
- [Improve gRPC clients config documentation](https://github.com/grafana/mimir/commit/6140c6b46d3e7f2a15ce7e0241de22ae0fcdf626)
N/A
=> Docs: improve gRPC clients config documentation

CHANGELOG.md, pkg/querier/worker/scheduler_processor.go, pkg/querier/worker/scheduler_processor_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/schedulerpb/custom.go
While testing https://github.com/grafana/mimir/pull/3005 I've noticed the querier logs a stream of "error processing requests from scheduler" when the query-scheduler terminates. I propose to detect such error and avoid logging it, given it's a normal condition.
I also suggest to reduce the "error contacting scheduler" level from error to warn, because it could happen while the query-scheduler is shutting down but before the service discovery detected it.
N/A
=> Do not log "error processing requests from scheduler" when the query-scheduler is shutting down

pkg/ruler/api_test.go, pkg/ruler/manager.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
`TestRuler_Rules` is flaky. The problem is that some ruler tests both start the ruler service **and** call `ruler.syncRules()`. The `ruler.syncRules()` is not concurrency safe, because of the rules config file mapper (it's not safe). The ruler logic is OK, but tests are not and they suffer some race conditions.
In this PR I'm removing any call to `ruler.syncRules()` from tests, just relying on the sync done by the ruler service itself and introducing a polling to wait until the desired condition is met.
Fixes #2803
=> Fix ruler flaky tests

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/astmapper_test.go, pkg/frontend/querymiddleware/astmapper/sharding.go
When sharding operations like `expr1 or expr2 or ... or expr_n`, the last expression has to be cloned `2^n` times by the `canShardAllVectorSelectors` check.
We can avoid that by caching the results of that function for each expr, making the execution time linear again.
Fixes an internal issue.
=> Fix exponential query sharding time of binops

pkg/util/validation/limits.go
This PR modifies `validation.ForwardingRule` to not include empty endpoint in the serialization output.
=> Don't include empty Endpoint when marshalling ForwardingRule.

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/astmapper_test.go, pkg/frontend/querymiddleware/astmapper/instant_splitting.go, pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go, pkg/frontend/querymiddleware/astmapper/sharding.go, pkg/frontend/querymiddleware/astmapper/sharding_test.go, pkg/frontend/querymiddleware/querysharding.go, pkg/frontend/querymiddleware/split_by_instant_interval.go
Adds a context check to expression mapping when running query sharding or instant query splitting.
Also a timeout of 10s is set on the context passed to the mapping. We don't expect this operation to last more than few milliseconds, so anything reaching 10s can be considered a bug or poor implementation.
I have manually checked that this works by commenting out the fix in #3027
Can't see how can I write a test for this, since this protects us from something we don't expect to happen.
Relates to #3027
=> Add a timeout to query sharding process

operations/helm/charts/mimir-distributed/scripts/bootstrap_kind_cluster.sh, operations/helm/charts/mimir-distributed/scripts/generate_enterprise_tenant_token.sh, operations/helm/charts/mimir-distributed/scripts/test_graphite_read_path.sh, operations/helm/charts/mimir-distributed/scripts/test_graphite_write_path.sh
This commit is adding two new scripts to:
- Bootstrap a new kind cluster with mimir-distributed installed.
- Generate an enterprise tenant token given a mimir-distributed
installation with enterprise enabled.
=> Add useful helm chart scripts

CHANGELOG.md, pkg/util/push/otel.go, pkg/util/push/push_test.go
=> Fix dropped metric panic with OTLP

CHANGELOG.md, pkg/frontend/querymiddleware/astmapper/astmapper_test.go, pkg/frontend/querymiddleware/astmapper/sharding.go
* Fix exponential query sharding time of binops
Backport of #3027:
When sharding operations like `expr1 or expr2 or ... or expr_n`, the last expression has to be cloned 2^n times by the `canShardAllVectorSelectors` check.
We can avoid that by caching the results of that function for each expr, making the execution time linear again.
(cherry picked from commit 0e45c39fa33ddefe0ceea402a6d15a21b46f4752)
=> Backport Fix exponential query sharding time of binops (#3027)

CHANGELOG.md, pkg/util/push/otel.go, pkg/util/push/push_test.go
* Fix dropped metric panic with OTLP
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
Co-authored-by: Arve Knudsen <arve.knudsen@gmail.com>
(cherry picked from commit 5c11f6b9933e0fc60994f8d09316dd86ea39ab0d)
=> Fix dropped metric panic with OTLP (#3040)

RELEASE.md
As Grafana Labs will test production workloads on the week of November 21st for the release 2.5.0, it may make sense to just postpone it a week.
N/A
=> Update 2.5.0 tenative release cut date

CHANGELOG.md, pkg/mimirtool/commands/remote_read.go
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
For example, an invalid URL `http://10.11.12.13:30090/prometheus/api/v1/read` returns `404`.
I'd expect an exit 1 and fatal log here, but it returns success instead.
```
$ go run cmd/mimirtool/main.go remote-read stats --address http://10.11.12.13:30090 --selector '{__name__!=""}'
INFO[0000] Created remote read client using endpoint 'http://10.11.12.13:30090/prometheus/api/v1/read'
INFO[0000] Querying time from=2022-09-27T08:48:54+03:00 to=2022-09-27T09:48:54+03:00 with selector={__name__!=""}
main: error: remote server http://10.11.12.13:30090/prometheus/api/v1/read returned HTTP status 404 Not Found: 404 page not found, try --help
exit status 1
```
**Actual Behavior**
```
$ go run cmd/mimirtool/main.go remote-read stats --address …
```
=> fix(remote-read): return err instead of nil

CHANGELOG.md, pkg/mimirtool/analyze/prometheus.go, pkg/mimirtool/commands/analyse_prometheus.go
Fixes: https://github.com/grafana/cortex-tools/issues/236
Signed-off-by: Furkan <furkan.turkal@trendyol.com>
Previous PR: https://github.com/grafana/cortex-tools/pull/237
Fixes https://github.com/grafana/cortex-tools/issues/236
cc @aknuds1
=> fix(analyse_prometheus): store errors instead of exit

pkg/ingester/ingester_test.go, pkg/ingester/label_names_and_values_test.go
Refactored these tests to use real TSDB instead of a mocked one, so changes to the code won't need changes in the tests, which have incomplete or unreal mocks.
Also dropped the LabelValueCardinality_ContextCancellation as that test wasn't testing any specific test where context cancellation would be taken into account.
Instead, added `TestCountLabelValueSeries_ContextCancellation` which tests that specific function, which is the slowest, to respect the context.
None, this work will make changes from https://github.com/grafana/mimir/pull/3044 and https://github.com/grafana/mimir/pull/3048 easier to review.
=> Refactor label value cardinality tests/benchmark

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/label_names_and_values.go, pkg/ingester/label_names_and_values_test.go
While reviewing https://github.com/grafana/mimir/pull/3044 I realized that there's a lot of work duplicated in that method:
When label values cardinality endpoint is being called with at least one matcher, we were passing that matcher to each `countLabelValueSeries` call.
This, in turn called `PostingsForMatchers` with the provided matchers plus an extra matcher fixing the label value.
This operation calculates the intersection of the postings for the provided matchers with the label value postings. As you can see, the "postings for the provided matchers" would be calculated for every label value found, which is quite inefficient, and gets worse as more matchers are provided.
This approach calculates those postings for the provided matchers in the first place, and then intersects them …
=> Use postings to calculate label values cardinality

CHANGELOG.md
I did a mistake earlier today. There's a duplicated CHANGELOG entry in main and 2.3.0. Let's keep it only in 2.3.0.
N/A
=> Remove duplicated entry from CHANGELOG

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/label_names_and_values.go, pkg/ingester/label_names_and_values_test.go
This reverts https://github.com/grafana/mimir/pull/3048
The benchmark fixed in https://github.com/grafana/mimir/pull/3080 shows that this implementation is much worse, see comment in https://github.com/grafana/mimir/pull/3048#issuecomment-1261160041
N/A
=> Revert "Use postings to calculate label values cardinality (#3048)"

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/Chart.lock, operations/helm/charts/mimir-distributed/Chart.yaml, operations/helm/charts/mimir-distributed/README.md
Backport: Helm: update agent-operator chart to 0.2.5 (#3009)
=> Backport: Helm: update agent-operator chart to 0.2.5 (#3009)

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configure/about-versioning.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, docs/sources/operators-guide/mimir-runbooks/_index.md, pkg/frontend/querymiddleware/limits.go, pkg/frontend/querymiddleware/limits_test.go, pkg/util/globalerror/errors.go, pkg/util/validation/errors.go, pkg/util/validation/errors_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
Add the ability to define a higher total query length limit on the
frontend , compared to the current shared limit between querier and
query-frontend.
Keep backwards compatibility.
Fixes https://github.com/grafana/mimir-squad/issues/889
=> Add MaxTotalQueryLength and fill it from MaxQueryLength if unset

integration/backward_compatibility.go
As part of the 2.3.0/2.3.1 release we want to add those versions to the backwards compatibility tests.
=> Add 2.3.1 to backwards compatibility test

pkg/ingester/ingester.go
Add an explicit event to the span when commit is finished which includes the time taken for the commit. Also switches to spanlogger instead of raw opentracing for a nicer interface with no nil checks.
N/A
=> Add explicit "commit completed" span log to ingester Push

pkg/ruler/api_test.go, pkg/ruler/compat_test.go, pkg/ruler/lifecycle_test.go, pkg/ruler/ruler_test.go, pkg/ruler/tenant_federation_test.go, pkg/util/validation/exporter_test.go, pkg/util/validation/limits_mock.go, pkg/util/validation/limits_test.go, pkg/util/validation/user_limits_handler_test.go
This PR does a refactoring in ruler tests, follow up a feedback received [here](https://github.com/grafana/mimir/pull/3088#discussion_r983560600) and [here](https://github.com/grafana/mimir/pull/3088#discussion_r983569287).
The diff is quite difficult to read, so suggest to review it commit-by-commit which should be way easier:
- [Removed ruleLimits from pkg/ruler and use the mock from pkg/util/validation instead](https://github.com/grafana/mimir/commit/21080f83f8116926f52205d2f0d90311bd522762) 
- [Removed buildAndStartRuler() in favour of buildRuler(..., withStart())](https://github.com/grafana/mimir/commit/26a2444d06ab1e2cc022046d1b178ef5be3bc039)
- [Renamed buildRuler() to prepareRuler()](https://github.com/grafana/mimir/commit/a6881c6f70cbd0c1852dcd5606ab55ce43c98294)
- [Moved default …
=> Chore: refactor ruler tests initialization

CHANGELOG.md, cmd/mimir/config-descriptor.json, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go, pkg/util/validation/limits.go, tools/doc-generator/parse/parser.go
It adds age filtering to the Distributor's forwarding functionality. The age filter can be configured so that samples which are older than a defined duration (for example `10min`) do not get forwarded.
=> Dont forward samples beyond a certain age

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, development/mimir-microservices-mode/config/mimir.yaml, docs/sources/operators-guide/configure/about-versioning.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/ruler/api_test.go, pkg/ruler/compat.go, pkg/ruler/compat_test.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go, pkg/ruler/store_mock_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_mock.go
I'm working on a tenants migration between two Mimir cluster and, as part of this migration, I need to selectively disable alerting rules for specific tenants. Instead of doing an hack in the ruler, I thought it could be generally useful having some advanced settings to forcefully disable recording and/or alerting rules evaluation on a per-tenant basis.
- I think the only risky change in this PR is that the new function `filterRuleGroupsByEnabled()` manipulates the rules configuration in place. I've done it in place to avoid memory allocations at all. I checked both the bucket and local storage implementations and I don't think it will introduce issues, because both of them return a fresh map/slice each time. However, GEM also uses a custom rules manager and, even if I …
=> Added support to forcefully disable recording and/or alerting rules evaluation

pkg/distributor/forwarding/forwarding.go, pkg/util/http.go
This PR adds extra log after incoming message in distributor has been unmarshalled, and adds tracing spans to distributor's forwarding code.
=> Improve traces in distributor

pkg/api/api.go, pkg/distributor/distributor.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/metrics.go, pkg/mimir/modules.go, pkg/util/push/otel.go, pkg/util/push/push_test.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
This is continuation of #2756, it changes discarded samples metric to avoid using `prometheus.DefaultRegisterer`. Opening as draft for discussion.
This also fixes interesting bug in monolithic mode: when distributor is cleaning metrics due to user being inactive, it currently also clears metrics created by ingester, even though ingester may still have TSDB open.
=> Remove use of DefaultRegistrer for discarded samples metric.

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
In the distributor component, wrap errors stemming from calling the `push` gRPC method on ingesters. If an errors stems from a timeout, that gets wrapped with a specific message.
I hope this will be useful in diagnosing write requests timing out in the ingester component (e.g. due to CPU starvation).
=> distributor: Wrap errors from pushing to ingesters

CHANGELOG.md, pkg/ingester/label_names_and_values.go, pkg/ingester/label_names_and_values_test.go
Adapts `labelValuesCardinality` to iterate postings in parallel to obtain label values total series count.
~~Additionally, an extra benchmark has been included to compare performance with the old implementation.~~  To do performance comparison the [recently refactored](https://github.com/grafana/mimir/pull/3080) `BenchmarkIngester_LabelValuesCardinality` has been used. 
The new implementation is about `2x-3x` faster in my testing.
Run the following command to verify the results:
```
go test -run=X -bench=BenchmarkIngester_LabelValuesCardinality -benchmem -count=5 -cpu=4 ./pkg/ingester/
```
Comparison:
```
name                                                                                             old time/op    new time/op    delta …
```
=> ingester: parallelize label values cardinality computation

CHANGELOG.md
In preparation for the 2.4 release cut, I've run `./tools/release/check-changelog.sh mimir-2.3.1...main` and added some missing PRs to the CHANGELOG. The remaining PRs not mentioned in the changelog are either not-user-facing changes (which we don't include in our CHANGELOG) or changes related to Helm (which have a dedicated CHANGELOG).
N/A
=> Add missing PRs to the CHANGELOG

operations/helm/charts/mimir-distributed/CHANGELOG.md
Feature should go after CHANGES
Agent operator update went into 3.1.0
=> Reorder helm changelog

CHANGELOG.md, docs/sources/operators-guide/configure/about-versioning.md, pkg/ruler/ruler.go
We're running the ruler's remote evaluation mode since some time at Grafana Labs. I think we can safely mark it as stable before cutting 2.4.
N/A
=> Mark ruler remote evaluation mode as stable

CHANGELOG.md, pkg/ruler/remotequerier.go, pkg/ruler/remotequerier_test.go
This PR adds backoff retry logic for ruler expression evaluation when running in remote operational mode. 
With this change we aim to mitigate evaluation errors derived from remote server transient conditions, such as those taking place during rollouts. 
Fixes N/A
=> ruler: use backoff retry on remote evaluation

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-object-store.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/object-store.libsonnet
In Grafana "rps" means "read / sec", while "reqps" means "req / sec". We have few panels incorrectly using "rps" instead of "reqps", which I'm fixing in this PR. Moreover, I'm adding "reqps" to the `qpsPanel()` too.
Pre-requisite of #3079
=> Dashboards: Use the "req/s" unit on panels showing the requests rate

operations/mimir-mixin/dashboards/dashboard-queries.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet, operations/mimir-mixin/dashboards/rollout-progress.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet
While working on https://github.com/grafana/mimir/issues/3079, I've got the need to have a common place where defining some queries used by multiple dashboards. In this PR I'm proposing to introduce a `.libsonnet` file to share them. Having a dedicated file for just 2 regexs looks overkilled, but we'll have many more queries there in #3079.
_I expect no change to compiled dashboards._
Pre-requisite of https://github.com/grafana/mimir/issues/3079
=> Chore: move common regex used by dashboards to a shared file

docs/sources/operators-guide/configure/configuring-zone-aware-replication.md
Documents the ingester client compression option when talking about multi-zone replication.
Ref: https://github.com/grafana/mimir/issues/2284#issuecomment-1261912474
=> Mention compression in multi-zone replication docs

CHANGELOG.md, operations/mimir-tests/test-query-scheduler-consul-ring-generated.yaml, operations/mimir-tests/test-query-scheduler-consul-ring.jsonnet, operations/mimir-tests/test-query-scheduler-memberlist-ring-generated.yaml, operations/mimir-tests/test-query-scheduler-memberlist-ring-read-path-disabled-generated.yaml, operations/mimir-tests/test-query-scheduler-memberlist-ring-read-path-disabled.jsonnet, operations/mimir-tests/test-query-scheduler-memberlist-ring.jsonnet, operations/mimir/config.libsonnet, operations/mimir/memberlist.libsonnet, operations/mimir/querier.libsonnet, operations/mimir/query-frontend.libsonnet, operations/mimir/query-scheduler.libsonnet, operations/mimir/ruler-remote-evaluation.libsonnet
In #2957 I've added query-scheduler ring-based service discovery. In this PR I'm adding support to enable it in our jsonnet.
The `query_scheduler_service_discovery_ring_read_path_enabled` is used to migrate to it. Migration is a two steps process: first enable the ring in the query-scheduler and set `query_scheduler_service_discovery_ring_read_path_enabled: false`, so that query-schedulers join a ring, but queriers and query-frontends still discovery the query-scheduler via DNS. Then you remove `query_scheduler_service_discovery_ring_read_path_enabled: false` to get queriers and query-frontends discovering the query-schedulers via ring.
I've checked the changes comparing these files, and they look good to me:
- Consul: `test-consul-generated.yaml …
=> Jsonnet: add query-scheduler ring-based service discovery support

CHANGELOG.md, pkg/util/log/wrappers.go
Previously, if there were multiple tenant IDs present in a request the `user` key value pair was dropped from the logger. Now it is included along with the multiple tenant IDs separated by a `|`.
N/A
=> Include multiple tenant IDs in loggers with context

.github/workflows/scripts/helm-weekly-release.sh, RELEASE.md, operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/continuous_test/continuous-test-dep.yaml, operations/helm/charts/mimir-distributed/templates/continuous_test/continuous-test-servmon.yaml, operations/helm/charts/mimir-distributed/templates/continuous_test/continuous-test-svc-headless.yaml, operations/helm/charts/mimir-distributed/values.yaml
Support different kind of authentication methods.
This is for better testing of #2778 and also parity with jsonnet which already has continuous test support.
=> Add continuous testing to helm chart

CHANGELOG.md, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir-tests/test-ruler-remote-evaluation-generated.yaml, operations/mimir-tests/test-ruler-remote-evaluation-migration-generated.yaml, operations/mimir/memberlist.libsonnet, operations/mimir/mimir.libsonnet
Sets `gossip_ring_member=true` for ruler queriers. This was a little tricky because the import ordering mattered.
Fixes #2849
=> Add gossip label to ruler queriers

Makefile, docs/internal/contributing/README.md
Depending on how docker is installed and configured but also the hardening applied to the workstation, docker might not be able to mount the code base properly in the container. As such, the user could end up with a error similar to the following:
```
❯ make lint
--8<--
>>>> Entering build container: lint-packaging-scripts
time docker run --rm --tty -i -v ~/.ssh/:/root/.ssh:delegated,z -v /workspace/github.com/grafana/mimir/.cache:/go/cache:delegated,z -v /workspace/github.com/grafana/mimir/.pkg:/go/pkg:delegated,z -v /workspace/github.com/grafana/mimir:/go/src/github.com/grafana/mimir:delegated,z grafana/mimir-build-image GOOS=darwin GOARCH=amd64 BINARY_SUFFIX="" lint-packaging-scripts;
Error: error preparing container 9c7c78b35ac936b65510dec180a81f6f38ea98e027d7049012f73f7ac31f885d for …
```
=> Allow to adjust mount options in Makefile

operations/mimir-mixin/dashboards/compactor.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview.libsonnet, operations/mimir-mixin/dashboards/queries.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet
I would like to extend the usage of `successFailurePanel()` utility, but the hardcoded `$.stack` inside it makes it harder. I propose to make `successFailurePanel()` to work like `queryPanel()`, so moving `$.panel()` and `$.stack` outside and thus making it more flexible.
This PR is expected to be a no-op.
N/A
=> Chore: refactor successFailurePanel() utility function in dashboards

operations/mimir/autoscaling.libsonnet
This allows an autoscaler object to have multiple triggers. This is a precursor to being able to autoscale on both CPU and Memory.
=> jsonnet: Add support for multiple triggers on autoscalers

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-overview.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin/dashboards/alertmanager.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview.libsonnet, operations/mimir-mixin/dashboards/queries.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet, operations/mimir-mixin/dashboards/ruler.libsonnet, operations/mimir-mixin/dashboards/tenants.libsonnet
In this PR I'm doing a small refactoring to our dashboards generation, to use a consistent color (red) to show errors and failures. I manually tested each of the affected panel and should be good.
N/A
=> Dashboards: Use a consistent color across dashboards for the error rate

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-overview.json, operations/mimir-mixin/dashboards/dashboard-queries.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview.libsonnet
I did a couple of mistakes in the status panel of the Overview dashboard:
1. I didn't correctly understood how "percentage" thresholds work in the status timeline panel. They're a % compared to other values. What we actually want are absolute values (in the range 0-1).
2. In the "Alerting notifications" queries I was summing 2 percentages and, you know, mathematically doesn't.
This PR fixes both.
N/A
=> Dashboards: fixed cluster status panel in the Overview dashboard

CHANGELOG.md, go.mod, go.sum, pkg/ruler/compat.go, vendor/github.com/prometheus/prometheus/rules/manager.go, vendor/modules.txt
Vendors https://github.com/grafana/mimir-prometheus/pull/328 and opts in to restore rule state for all new rule groups that get added after startup. For more details see #2888 
Fixes #2888 
- NA Tests updated - there are tests in prometheus for this. See https://github.com/grafana/mimir-prometheus/pull/328
=> Restore state for new rule groups after startup

CHANGELOG.md
I'm about to cut the release-2.4 branch. As first step, I'm going to cut the CHANGELOG as usual.
N/A
=> Cut CHANGELOG to prepare for 2.4.0 release

CHANGELOG.md, pkg/mimir/modules.go
Signed-off-by: Rohan Kumar <rohankmr414@gmail.com>
This PR adds `Overrides` module as a dependency `Flusher` to prevent panics on startup. Before removing chunks storage in #755, Flusher depended on `Store` which depended on `Overrides` module, this might be the reason behind panics
Fixes #2866
=> fix: add Overrides to Flusher dependencies to prevent panic on startup 

RELEASE.md, tools/release/notify-changelog-cut.sh
Adding a script to notify open PRs that the CHANGELOG has just been just. I've just run it.
N/A
=> Release: add notify-changelog-cut.sh script

Makefile
In this PR:
- Remove `.uptodate` from dist, so that every time we run `make dist` it actually re-builds the binaries
- Make it less verbose, not printing the commands executed
N/A
=> Chore: get 'make dist' always re-run and being less verbose

CHANGELOG.md, docs/sources/operators-guide/tools/mimirtool.md, pkg/mimirtool/client/rules.go, pkg/mimirtool/commands/rules.go
The following changes allow user delete all the rule groups in a namespace (including the namespace itself).
N/A
=> Added `mimirtool rules delete-namespace`

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go
This PR increased discarded samples metric for forwarded series that receive too old samples, and are otherwise not ingested. 
Fixes comment https://github.com/grafana/mimir/pull/3049#discussion_r984555654
=> Increase discarded samples metric if forwarded series receives too old samples

docs/sources/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs.md, operations/helm/charts/mimir-distributed/values.yaml
A few community members have asked if it's possible to send metamonitoring directly back to mimir. This PR adds examples of how to do this.
I also added an example in the helm values.yaml since this is where some people look for documentation first.
=> Add examples for sending Helm metamonitoring to Mimir

docs/sources/operators-guide/running-production-environment-with-helm/configuration-with-helm.md
Some autogenerated secrets get dots and dashes in the secret names, so the instructions don't work directly. Add a mention to docs of what the keys should be to avoid complications.
=> Helm docs: Mention format of secret keys for injecting credentials

CHANGELOG.md, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Fix legend showing `persistentvolumeclaim` when using `deployment_type=baremetal` for `Disk space utilization` panels
N/A
=> Fix Disk space utilization panels when deployment_type=baremetal

Makefile, docs/internal/contributing/contributing-to-helm-chart.md
We already have helm in the build image, so we might as well move the
golden records generation into the build image so that all contributors
get the same outputs regardless of their local helm version.
The tradeoff is the time it takes to run them. On my macOS it takes 3x the time
```
real	0m36.561s
user	0m0.062s
sys  	0m0.044s
```
vs
```
real	0m10.662s
user	0m12.030s
sys 	0m3.078s
```
=> Helm chore: Move build/check-helm-tests to build image

CHANGELOG.md, pkg/storegateway/indexcache/memcached.go
According to a `storegateway` memory profile from the ops cluster, the `strconv.FormatUint` function used in `seriesForRefCacheKey` is taking roughly `1.37%` of total allocated objects. That seems quite a lot for just an id generator function.
This PR adapts `seriesForRefCacheKey` to parse series ref id using a stack a buffer to avoid unnecessary allocations. 
Below are the benchmark results comparing against the old implementation:
Previous:
```
BenchmarkStringCacheKeys/series_ref-8         	14691523	        81.81 ns/op	      88 B/op	       2 allocs/op
BenchmarkStringCacheKeys/series_ref-8         	14615520	        81.87 ns/op	      88 B/op	       2 allocs/op
BenchmarkStringCacheKeys/series_ref-8         	14474442	        81.29 ns/op …
```
=> storegateway: avoid unnecessary allocation in `seriesForRefCacheKey`

docs/sources/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs.md, operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/NOTES.txt, operations/helm/charts/mimir-distributed/templates/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/metamonitoring/_helpers.tpl, operations/helm/charts/mimir-distributed/templates/metamonitoring/logs-instance.yaml, operations/helm/charts/mimir-distributed/templates/metamonitoring/metrics-instance.yaml, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/logs-instance.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/metrics-instance.yaml
As a follow up of #2984 
this PR sends metamonitoring metrics automatically to mimir if no URL is configured (and if metamonitoring is enabled)
=> Helm: Default to sending metamonitoring inside Mimir

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/metamonitoring/metrics-instance-usernames-secret.yaml
This fixes a regression caused by https://github.com/grafana/mimir/pull/2936.
Without this change, the agent operator is unable to find the usernames, because they aren't written to the secret correctly.
This bug was released in 3.2.0, and since this breaks metamonitoring completely, I suggest we cut a 3.2.1 release with this fix included.
=> [Helm]: Fix metamonitoring secret configuration

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/alertmanager-resources.libsonnet, operations/mimir-mixin/dashboards/alertmanager.libsonnet, operations/mimir-mixin/dashboards/dashboard-queries.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/ruler.libsonnet
Hide the alertmanager-im panels by default. I'm working on including more of the mixin by default for enterprise customers, and this panel sticks out as not useful outside of Grafana Cloud.
This is helpful for OSS and Enterpise users who don't have the Grafana Cloud specific service.
This PR also includes a couple changes to the way queries are templated, which make it possible to override them for GEM's self-monitoring feature. They should all be a no-op for non-GEM users.
=> Make the alertmanager instance mapper related panels optional

development/mimir-microservices-mode/dev.dockerfile
This PR updates delve version used by development/mimir-microservices-mode setup, because previous version is no longer compatible with Go 1.19.
=> Updates delve version used by development/mimir-microservices-mode setup

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md
Augment MimirQuerierAutoscalerNotActive runbook with some more advice:
* Check KEDA operator logs
* Check Prometheus pods
=> runbooks: Augment MimirQuerierAutoscalerNotActive runbook

operations/helm/charts/mimir-distributed/ci/offline/metamonitoring-values.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/logs-instance-usernames-secret.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/logs-instance.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/metrics-instance-usernames-secret.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/metrics-instance.yaml
This adds remote destinations so that we can test more of the logic in
metamonitoring. Specifically to expose the bug that #3170 fixed.
=> Helm: add remote destinations in metamonitoring offline test

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/config.libsonnet
Include query-scheduler among the ring members for the MimirGossipMembersMismatch alert, to stop it from firing.
Fixes #3194.
=> Alerts: Include query-scheduler for MimirGossipMembersMismatch

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
This alert fires when the expected number of ring members does not
match the running number for each component (one of `compactor`,
`distributor`, `ingester`, `ruler`, or `store-gateway`).
Fixes #1960
=> Add mixin alert for ring member mismatch

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Reverts grafana/mimir#3055
Resolves https://github.com/grafana/mimir/issues/3210
=> Revert "distributor: Wrap errors from pushing to ingesters"

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/metamonitoring/grafana-agent.yaml, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-agent.yaml
This PR makes it possible to configure the scrape interval for metamonitoring metrics. The default is 60s.
=> helm: make metamonitoring scrape interval configurable

operations/mimir-mixin/alerts/alerts.libsonnet, operations/mimir-mixin/dashboards/overview.libsonnet
On the Overview dashboard:
- Instead of using the hardcoded "Mimir" name, delegate to the `$._config.product` name.
- This affects:
- A panel title: "Mimir cluster health"
- An alert list panel filter which searches for alert names containing the text "Mimir".
- Note that the alert creation makes use of the product name as a prefix, so this should be more appropriate.
See https://github.com/grafana/mimir/blob/main/operations/mimir-mixin/alerts/alerts-utils.libsonnet#L10
=> mimir-mixins: dashboards: fix: use product name in overview dashboard instead of hardcoded "Mimir"

RELEASE.md, tools/release/common.sh, tools/release/create-draft-release-notes.sh, tools/release/create-draft-release.sh, tools/release/notify-changelog-cut.sh
Like #3164 but from a branch name which allows me to force push (we have a protection on branches with name matching `release*`). Copied from #3164:
I've created the **draft** release `2.4.0-rc.0` ([link visible only to maintainers until will be published](https://github.com/grafana/mimir/releases/tag/untagged-58fc54db72d7598c982d)) with a script, which I'm upstreaming in the PR.
What's in this PR:
- Few helper functions in `tools/release/common.sh`
- `tools/release/create-draft-release-notes.sh` to generate the draft release notes (it gets called by the release publishing script)
- `tools/release/create-draft-release.sh` to create (but not publish) the draft pre-release
N/A
=> Add script to publish the release

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml
Adjusts Nginx deployments `imagePullSecret` so it is the same as for other deployments. This will make chart deployments easier as only one `imagePullSecret` has to be added in `values.yaml` file instead of multiple ones, which can be annoying and confusing.
Fixes #3207
=> changed nginx imagePullSecret value reference

CHANGELOG.md, Makefile
When creating the packages on MacOS the `OS` applied on the package is not correct. The documentation says:
--rpm-os OS
The operating system to target this rpm for. You want to set this to ‘linux’ if you are using fpm on OS X, for example
See: https://fpm.readthedocs.io/en/latest/packages/rpm.html
Fixes #3216
=> [packages] Fix incorrect OS value set in Mimir v2.3.* RPM package

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
With our current HPA querier auto-scaling setup it takes sometimes more than a minute for us to detect that we need to scale up and request the additional querier replicas be created. This change allows more time for that to happen before the alert triggers.
- [ -] Tests updated
=> Update MimirSchedulerQueriesStuck alert and runbook to reflect querier auto-scaling

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, docs/sources/operators-guide/secure/securing-communications-with-tls.md, go.mod, go.sum, vendor/github.com/prometheus/exporter-toolkit/web/tls_config.go, vendor/github.com/weaveworks/common/server/server.go, vendor/github.com/weaveworks/common/server/tls_config.go, vendor/modules.txt
Allows the admin to configure the list of ciphers supported by Mimir services, and/or the minimum TLS version.
This is revisiting the change rejected in https://github.com/grafana/mimir/pull/2309#discussion_r913098472 on the basis that the documentation was user-hostile.
In this version, the cipher suite list is configured as a single string, patterned after the similar Kubernetes option.
Cipher names are as used by Go, at https://pkg.go.dev/crypto/tls#pkg-constants.
Updates weaveworks/common and prometheus/exporter-toolkit libraries.  
**NOTE** [the weaveworks/common PR](https://github.com/weaveworks/common/pull/256) is not merged yet; I wanted to get consensus on this change before doing that.
I didn't add a test specifically for these changes in Mimir; weaveworks/common unit tests …
=> TLS: make cipher suite list and min version configurable

CHANGELOG.md, Makefile
Cherry picking #3221 into release-2.4
=> Cherry pick #3221

CHANGELOG.md, pkg/ingester/ingester_activity.go, pkg/ingester/ingester_activity_test.go
Added custom stringer for `*client.QueryRequest` to minimize memory allocation on ingester activity tracker record generator.  
old:
```
BenchmarkRequestActivity-8   	 1284216	       927.5 ns/op	     984 B/op	      21 allocs/op
BenchmarkRequestActivity-8   	 1291141	       928.1 ns/op	     984 B/op	      21 allocs/op
BenchmarkRequestActivity-8   	 1289739	       928.9 ns/op	     984 B/op	      21 allocs/op
BenchmarkRequestActivity-8   	 1287590	       927.4 ns/op	     984 B/op	      21 allocs/op
BenchmarkRequestActivity-8   	 1287128	       934.3 ns/op	     984 B/op	      21 allocs/op
BenchmarkRequestActivity-8   	 1294728	       931.9 ns/op	     984 B/op	      21 allocs/op
BenchmarkRequestActivity-8   	 1291026	       928.1 ns/op …
```
=> ingester: reduce activity tracker memory allocation

CHANGELOG.md, operations/mimir-tests/test-query-scheduler-memberlist-ring-and-ruler-remote-evaluation-generated.yaml, operations/mimir-tests/test-query-scheduler-memberlist-ring-and-ruler-remote-evaluation.jsonnet, operations/mimir/query-scheduler.libsonnet, operations/mimir/ruler-remote-evaluation.libsonnet
In #3128 I've introduced support query-scheduler ring-based service discovery support to jsonnet. However, when the remove ruler evaluation is enabled, we need to run the `ruler-query-scheduler` on a different ring to not merge with `query-scheduler`. To do it, we use a different ring prefix. It was addressed for the `ruler-query-scheduler`, but not for the `ruler-querier` and `ruler-query-frontend`. This PR fixes it.
I've also added a specific test case which can be diffed as follows:
```
diff operations/mimir-tests/test-query-scheduler-memberlist-ring-generated.yaml operations/mimir-tests/test-query-scheduler-memberlist-ring-and-ruler-remote-evaluation-generated.yaml
```
The important thing to notice is that in this PR it sets the following CLI flags for `ruler-query-scheduler`, …
=> Fixed query-scheduler ring configuration for dedicated ruler's queries and query-frontends

tools/release/common.sh, tools/release/create-draft-release-notes.sh, tools/release/create-draft-release.sh, tools/release/create-pr-to-merge-release-branch-to-main.sh, tools/release/notify-changelog-cut.sh, tools/release/tag-release.sh
Following up an offline conversation I had with @pstibrany, I propose to add a pre-requisite check for all release scripts and require that the git clone only has 1 remote named "origin". This helps to keep the scripts easier instead of having to handle the case there are multiple remotes or the name is different than "origin".
N/A
=> Release: add pre-requisite check on git remote for all release scripts

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
Logs useful information about the query in the case of a failed query (context cancelled etc) - current logging information was making it hard for other engineers to debug issues.
https://github.com/grafana/mimir/issues/3146
Fixes #3146
=> Log failed query information in the query-frontend

CHANGELOG.md, operations/mimir-mixin-compiled/dashboards/mimir-overview.json, operations/mimir-mixin/dashboards/dashboard-queries.libsonnet, operations/mimir-mixin/dashboards/overview.libsonnet
Looking at the "Mimir / Overview" dashboard in production, I've noticed a good amount of queries fall into the "other" group. In this PR I'm adding dedicated grouping for "remote read", "metadata", and "exemplar" queries.
N/A
=> Add "remote read", "metadata", and "exemplar" queries to "Mimir / Overview" dashboard

CHANGELOG.md, pkg/compactor/bucket_compactor.go, pkg/compactor/job.go
Emit a histogram of the difference between `now` and the max time of a block being compacted as a number of seconds. This can be used to alert if compactors are not able to keep up with the number of blocks being generated. In this case, the delta will begin to fall into higher and higher buckets (> 24h).
N/A
=> Compactor: emit histogram of block max time delta to now

docs/sources/operators-guide/mimir-runbooks/_index.md
Customer was seeing out of order samples randomly in remote writes and rule evaluations. Add the case to the runbook for
easier troubleshooting.
Fixes support case 4030
=> out-of-order runbook update with use case

CHANGELOG.md
Truncating the queries past the retention period is not a CHANGE because user shouldn't notice anything, so it's an ENHANCEMENT. So this fixes that.
Ref: #3134
=> Nitpick: fix changelog entry kind for #3134

CHANGELOG.md, operations/mimir/config.libsonnet, operations/mimir/query-tee.libsonnet
I'm testing the read-write deployment mode in a dev cluster at Grafana Labs and I want to use the query-tee to tee read path traffic, but I don't need/want to set the node port on the service, so I'm making it optional.
N/A
=> The query-tee node port is now optional

pkg/ruler/compat.go, pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
In https://github.com/grafana/mimir/pull/3261 we updated the upstream Prometheus, which finally exposed `rules.SendAlerts()`. Since the function is the exact same of our `SendAlerts()` we can finally get rid of it and use the upstream one.
N/A
=> Chore: use upstream rules.SendAlerts()

CHANGELOG.md, pkg/compactor/blocks_cleaner.go, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/compactor.go
The problem is described in more detail in https://github.com/grafana/mimir/issues/2560. 
TL;DR: long-running periodic cleanup jobs for a single tenant no longer block the periodic jobs of other tenants
Fixes https://github.com/grafana/mimir/issues/2560
=> Make blocks cleanup in compactor more fair

CHANGELOG.md, pkg/api/api.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_activity.go, pkg/ingester/ingester_test.go, pkg/util/push/push.go, pkg/util/push/push_test.go, pkg/util/push/request.go, pkg/util/push/request_test.go
The ingester and distributor push functions have some  limit validations
on push requests that do not depend on the push request itself (e.g.
request rate or inflight requests). This PR makes parsing of request
happen only after the distributor and ingester have validated as many
of their instance limits as possible. This should reduce utilization
when the distributor and ingesters are under load.
Originally the issue was for the distributor only, but since their `PushWithCleanup` methods both confirm to the `push.Func` signature, I decided it is easier to change both of them.
I am submitting this PR as a draft because it complicates the code,
and only helps when requests in the distributor start taking a very long time and …
=> Parse push request after distributor, ingester validate limits

CHANGELOG.md, go.mod, tools/copyblocks/README.md, tools/copyblocks/main.go
We have a tool https://github.com/grafana/cortex-tools/tree/main/cmd/blockscopy to copy blocks between GCS bucket (it's GCS specific). I need to add more features to it (e.g. copy no-compact markers too), but first I would like to move it Mimir repo along with other tools. I've also rename it to `copyblocks` to keep consistency with the other tools we have (`listblocks`, `markblocks`).
If this PR will be accepted, I will open an issue to add support for all storage backends in this tool too and write its doc.
N/A
=> Import blockscopy too and rename it to copyblocks

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md
Fix TSDB retention mentioned in the "Recover source blocks from ingesters" runbook.
N/A
=> Fixed TSDB retention mentioned in the "Recover source blocks from ingesters" runbook

CHANGELOG.md, pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go
This PR modifies Distributor's forwarding feature to always include `X-Scope-OrgId` header with tenant when forwarding requests to the configured endpoint.
=> Include tenant in forwarded requests

pkg/distributor/distributor_test.go
Adds a regression test for https://github.com/grafana/mimir/issues/3210, ensuring that errors returned by ingesters keep their GRPC context when being returned back upstream.
https://github.com/grafana/mimir/issues/3214
=> Add regression test for distributor passing through GRPC statuses

pkg/compactor/bucket_compactor_e2e_test.go, pkg/compactor/compactor_test.go, pkg/distributor/distributor_test.go, pkg/distributor/query_test.go, pkg/frontend/querymiddleware/querysharding_test.go, pkg/frontend/querymiddleware/querysharding_test_utils_test.go, pkg/ingester/activeseries/active_series_test.go, pkg/ingester/activeseries/matchers_test.go, pkg/ingester/ingester_test.go, pkg/ingester/label_names_and_values_test.go, pkg/mimirpb/compat_test.go, pkg/querier/block_test.go, pkg/querier/blocks_store_queryable_test.go, pkg/querier/distributor_queryable_test.go, pkg/querier/iterators/chunk_merge_iterator_test.go, pkg/querier/partitioner_test.go, pkg/querier/querier_test.go, pkg/querier/tenantfederation/merge_exemplar_queryable_test.go, pkg/querier/tenantfederation/merge_queryable_test.go, pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go, pkg/storegateway/gateway_test.go, pkg/storegateway/indexheader/header_test.go, pkg/storegateway/indexheader/lazy_binary_reader_test.go, pkg/storegateway/indexheader/reader_pool_test.go
Use `labels.FromString` abstraction instead of assuming `labels.Labels` is a slice that we can construct directly. This will allow flexibility in the implementation.
All but one of the changes are in tests; none are performance-sensitive.
Similar PR upstream: https://github.com/prometheus/prometheus/pull/11048
- NA `CHANGELOG.md` updated - not user-visible.
=> Use labels.FromString abstraction

CHANGELOG.md, pkg/frontend/v2/frontend_scheduler_worker.go, pkg/frontend/v2/frontend_test.go
discovered by @pstibrany:
makes sure that the query-frontend properly terminates gRPC streams to the query-scheduler after the scheduler closes the connections on them
without this there was a goroutine and memory leak. In the attached screenshot you can see on the left side of each graph GEM running without this fix and on the right side of each graph GEM with this fix.
=> query-frontend: cancel stream to scheduler when streaming failed

CHANGELOG.md, integration/backfill_test.go, pkg/mimirtool/client/client.go
When provided with `--log.level=debug` and a request fails mimirtool should print out some part of the response for easier debugging. Instead it uses a scanner which only reads the first token from the response.
The first token is by default the first line. Which in some cases can be fairly useless.
This PR 
* changes the logged reported content to be the first 1024 bytes regardless of new lines.
* removes duplication of the error content (logging both `errMsg` and `msg`)
* increases the number of bytes to read from the body from 512 to 1024 for good measure.
=> Fix mimirtool error logging

pkg/ruler/ruler.go, pkg/ruler/ruler_test.go
Clean up the ruler tests a bit, such as making sure that arguments to `(require|assert).Equal` are in the right order (expectation first).
=> ruler: Clean up tests a bit

Makefile, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/_index.md, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/configure-autoscaling.md, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/configure-low-resources.md, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/configure-ruler.md, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/deploy.md, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/migrating-from-consul-to-memberlist.md
Ref: https://github.com/grafana/mimir/issues/1663
This renames the sections under "Deploy with jsonnet" (and that section itself) to use imperative instead of gerunds.
Aliases have been added for previous names.
Ref: https://github.com/grafana/mimir/issues/1663
=> Use imperative for "Deploy with jsonnet" docs

tools/release/common.sh, tools/release/create-draft-release-notes.sh, tools/release/create-draft-release.sh, tools/release/tag-release.sh
I just published Mimir 2.4.0 stable release (🎉 ) and I've found few issues with the release scripts when doing the stable release:
1. When comparing releases, we need to compare with the previous stable release (skipping candidate releases)
2. The sorting of release tags is not correct when using `sort -V`. I switched to `git tag --list --sort=taggerdate` which fixes it.
3. `tools/release/create-draft-release.sh` calls `tools/release/create-draft-release-notes.sh > /file.txt` so if error messages are sent to stdout they will not be visible in the console. I redirected all error messages to stderr instead.
The Mimir 2.4.0 release has been published with these updated scripts.
N/A
=> Release: fix create release scripts when publishing a stable release

integration/backward_compatibility.go
Last week we published Mimir 2.4.0 stable. In this PR I'm adding it to the backward compatibility tests.
N/A
=> Release: add Mimir 2.4.0 to backward compatibility tests

pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
The last usage of this function was removed by https://github.com/grafana/mimir/pull/3101
- NA `CHANGELOG.md` updated - not user-visible.
=> Remove unused GetLabels() function

RELEASE.md
We plan to publish 2.5.0 release candidate on 28th Nov. That date + 6 weeks would be Jan 9th. Since there are some holidays in between, which will slow down a bit Mimir development, I propose to add +1 week before cutting 2.6.0, so Jan 16th.
WDYT?
=> Release: propose date for Mimir 2.6.0 release candidate

CHANGELOG.md, docs/sources/operators-guide/secure/securing-communications-with-tls.md
This PR updates changelog to clarify new TLS server-side flags. It also removes duplicate flag in the documentation.
Ref: https://github.com/grafana/mimir/pull/2898/files#r1010509253
=> Clarify changelog and remove duplicate flag in the documentation.

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/mimir/mimir.go, pkg/mimir/mimir_test.go, pkg/querier/querier.go, pkg/querier/querier_test.go
Align the `-server.http-write-timeout` with `-querier.timeout` to 2m. Add validation for these values.
Fixes https://github.com/grafana/mimir/issues/3248
=> Align the `-server.http-write-timeout` with `-querier.timeout` to 2m

pkg/mimirpb/compat.go
This is a follow up PR for https://github.com/grafana/mimir/pull/2450
Replace custom point marshaling functions with the ones exposed in Prometheus `jsonutil` package. 
Fixes N/A
=> mimirpb: use jsonutil point marshal functions

.github/workflows/compare-helm-with-jsonnet.yml, .github/workflows/helm-ci.yml, .github/workflows/test-build-deploy.yml, CHANGELOG.md, Makefile, development/mimir-microservices-mode/dev.dockerfile, mimir-build-image/Dockerfile
Upgrade to Go [1.19.3](https://go.dev/doc/devel/release#go1.19.3), which is a security release.
=> Build: Upgrade to Go 1.19.3

CHANGELOG.md, pkg/storage/bucket/s3/config.go
While looking at https://github.com/grafana/mimir/issues/3337 and manually trying setting an invalid `-blocks-storage.s3.signature-version`, I've realized that the error message doesn't specify which are the supported signature versions. I think we should do it, to give a quick hint to the user.
N/A
=> Clarify which S3 signature versions are supported in the error "unsupported signature version"

CHANGELOG.md, docs/sources/operators-guide/mimir-runbooks/_index.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts-utils.libsonnet, operations/mimir-mixin/alerts/alerts.libsonnet
The experimental `RulerRemoteEvaluationFailing` alert has proven to work correctly at the ops cluster. 
This PR moves the alert definition to upstream. 
Fixes N/A
=> mixin: ruler emote eval failing alert

pkg/distributor/forwarding/forwarding.go, pkg/distributor/forwarding/forwarding_test.go
the http header needs to be canonicalized for the header lookup to work
=> canonicalize orgid header in forwarding

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
The query run by `MimirRulerRemoteEvaluationFailing` aggregated all rulers, so there's no `pod` label. This PR fixes the `MimirRulerRemoteEvaluationFailing` alert message accordingly. I've also took the chance to slightly rephrase it.
N/A
=> Fix MimirRulerRemoteEvaluationFailing alert message

CHANGELOG.md, docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/configure-autoscaling.md, docs/sources/operators-guide/mimir-runbooks/_index.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/alerts/autoscaling.libsonnet, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet, operations/mimir-mixin/mixin-compiled.libsonnet, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir-tests/test-autoscaling.jsonnet, operations/mimir/autoscaling.libsonnet
Add support for autoscaling distributors. Lay some groundwork to help making other components autoscale.
=> Distributor autoscaling

docs/sources/migration-guide/migrating-from-thanos-or-prometheus.md
The detailed steps on how to migrate the blocks from Thanos to Mimir isn't available and the current documentation also doesn't seems to be helpful. Therefor I have formulated the steps I have followed for migrating the blocks from Thanos to Mimir so that it would be helpful for people who are looking to move from Thanos.
=> Updated detailed steps for migrating blocks from Thanos to Mimir.

CHANGELOG.md, operations/mimir-mixin/dashboards/writes.libsonnet
This PR fixes query showing successful forwarded requests. Previous query could return no results if `cortex_distributor_forward_requests_total` metric didn't exist yet.
Before:
After:
=> Fix panel with forwarded requests if there are no errors yet.

CHANGELOG.md, pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go, pkg/storegateway/indexheader/binary_reader.go, pkg/storegateway/indexheader/header.go, pkg/storegateway/indexheader/header_test.go, pkg/storegateway/indexheader/lazy_binary_reader.go
More often than not we retrieve label values to filter them using a matcher later. If we pass in the matcher as a filter function, we can avoid moving some extra values.
This shows a -5% cpu improvement when this path is hit, and no change otherwise.
```
name                                                               old time/op  new time/op  delta
BucketIndexReader_ExpandedPostings/n="1"                           7.27ms ± 2%  7.24ms ± 2%    ~     (p=0.447 n=9+10)
BucketIndexReader_ExpandedPostings/n="1",j="foo"                   32.9ms ± 5%  32.5ms ± 1%    ~     (p=0.236 n=9+8)
BucketIndexReader_ExpandedPostings/j="foo",n="1"                   32.5ms ± 1%  32.5ms ± 2%    ~     (p=0.631 n=10+10)
BucketIndexReader_ExpandedPostings/n="1",j!="foo"                  28.3ms ± 2%  28.0ms ± 2% …
```
=> Add optional matcher to IndexReader.LabelValues

pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_reader.go, pkg/storegateway/bucket_test.go, pkg/storegateway/stats.go
Dimitar is doing a work to make the store-gateway `Series()` streaming based in https://github.com/grafana/mimir/pull/3355. One of the implementation difficulties is the fact that `bucketIndexReader` keeps per-query data inside, so in #3355 we're introducing an unload function. To remove the need of that unload function from the `bucketIndexReader` I think we can stop storing per-query data in `bucketIndexReader` (which always looked a bad smell to me).
In this PR (se separate commits):
- [Moved queryStats to dedicated file](https://github.com/grafana/mimir/commit/fb06a8aed509a06f09449f933a6b346deac94e8d)
- [Move query statistics out of bucketIndexReader](https://github.com/grafana/mimir/commit/995e5ea4aed665ca5b24bbef8176358d9a495d17)
- [Do not store preloaded series in …
=> Refactoring: do not store per-query data in bucketIndexReader

docs/internal/contributing/README.md
The contributing guide refers to `how-to-run-website-locally.md`, but this file was removed in https://github.com/grafana/mimir/pull/772. 
It seems that `make docs` is the easiest way to run the website locally now.
n/a
=> Remove reference to file that no longer exists in contributing guide.

CHANGELOG.md, pkg/mimirtool/analyze/grafana.go, pkg/mimirtool/analyze/prometheus.go, pkg/mimirtool/analyze/ruler.go, pkg/mimirtool/commands/analyse.go, pkg/mimirtool/commands/analyse_grafana.go, pkg/mimirtool/commands/analyse_prometheus.go, pkg/mimirtool/commands/analyse_ruler.go
This PR adds resiliency and concurrency in analyze Prometheus command. Removes duplicate codes and optimizes code. It reduces the working time considerably. Notably performance increment as you can see the following:
Fixes #3062
cc: @Dentrax @aysenrsrt
=> refactor: `mimirtool analyze prometheus`: add concurrency and resiliency

docs/internal/contributing/README.md, docs/internal/contributing/design-patterns-and-conventions.md, docs/internal/contributing/how-integration-tests-work.md, docs/internal/contributing/how-to-upgrade-golang-version.md, docs/sources/operators-guide/mimir-runbooks/_index.md
I noticed a couple of small typos as I've been reading through the documentation - this PR fixes them.
(none)
=> Fix some minor typos in the contributing guide and on the runbooks page

pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_reader.go, pkg/storegateway/stats.go, pkg/storegateway/stats_test.go
This PR is a follow up of #3396. In this PR I'm enforcing the usage of `safeQueryStats` in `bucketIndexReader`. To enforce it, I've introduced a function `update()` to manipulate the stats and `export()` to get a copy of the stats.
The "unsafe" version `queryStats` is still directly accessed in few places which we haven't refactored yet (e.g. chunks reader). These will be addressed in follow up PRs, as soon as we begin addressing the chunks reader.
This PR is on top of #3398.
N/A
=> Refactoring: enforce usage of safeQueryStats in bucketIndexReader

pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_postings.go, pkg/storegateway/bucket_index_postings_test.go, pkg/storegateway/bucket_index_reader.go, pkg/storegateway/bucket_test.go
This is a follow up PR to further reduce `bucket.go` file size. In this PR I'm moving all postings reading utilities to a dedicated file `bucket_index_postings.go`.
N/A
=> Refactoring: move postings reading utilities to dedicated file

CHANGELOG.md, pkg/storegateway/indexheader/binary_reader.go, pkg/storegateway/indexheader/binary_reader_test.go
When we're reading the index header, we're creating new labels.Label struct by allocating new strings all the time, but in most of the cases we just want to compare whether the label name has changed or not.
For that purpose, we can yolo the underlying buffer, avoiding that allocation.
There are two cases when we need to unyolo:
- When we create the entry in the offsets map (that reference will be stored)
- When we store the label value.
Benchmark results are quite promising:
```
name                                old time/op    new time/op    delta
BinaryReader_LargerBlock/benchmark    1.95ms ± 9%    1.17ms ± 5%  -39.99%  (p=0.008 n=5+5)
name                                old alloc/op   new alloc/op   delta
BinaryReader_LargerBlock/benchmark    1.06MB ± 0%    0.16MB ± 0%  -85.16% …
```
=> Use unsafe labels when reading the index header

CHANGELOG.md, pkg/compactor/bucket_compactor.go, pkg/compactor/bucket_compactor_test.go
Fixes an issue where a timestamp in milliseconds was subtracted from a timestamp in seconds, resulting in negative deltas being recorded instead of the actual delay between the block maxtime and "now".
N/A
=> Convert MaxTime to seconds when recording compactor lag

integration/getting_started_single_process_config_test.go, integration/getting_started_with_grafana_mimir_test.go, integration/otlp_ingestion_test.go, integration/read_write_mode_test.go, integration/util.go
I've [extracted Prometheus' minimum and maximum timestamp values to a single location](https://github.com/grafana/mimir/commit/0e5dad35cdf93635c2d88823230c3b1c878c4bfb) and updated all integration tests to use these instead of calculating them each time.
(none)
=> Integration test tidy up

pkg/storegateway/bucket.go
When the other side closed the stream, the store gateway continues
to try to send the hints. This attempt fails because the stream is
closed and the error from the attempt overwrites the original error.
That error will likely not have much useful information, but it is lost
nonetheless.
The possible errors lost are either here https://github.com/grafana/mimir/blob/aa5aa4e08a97eed478a8ddc0e765aebe2be66a8d/pkg/storegateway/bucket.go#L1010 or here https://github.com/grafana/mimir/blob/aa5aa4e08a97eed478a8ddc0e765aebe2be66a8d/pkg/storegateway/bucket.go#L1005
=> store-gateway: fix error handling in Series()

integration/read_write_mode_test.go
Builds on https://github.com/grafana/mimir/pull/3423, split from #3433.
The read-write mode integration test occasionally fails due to errors like "expanding series: empty ring" when querying for data. This PR adds a check that waits for the ingesters to become active before proceeding with the test.
#3363
=> Make read-write mode test robust to instance startup race condition.

go.mod, go.sum, integration/backward_compatibility_test.go, integration/distributor_forwarding_test.go, integration/getting_started_single_process_config_test.go, integration/getting_started_with_gossiped_ring_test.go, integration/getting_started_with_grafana_mimir_test.go, integration/ingester_limits_test.go, integration/ingester_sharding_test.go, integration/otlp_ingestion_test.go, integration/querier_label_name_values_test.go, integration/querier_remote_read_test.go, integration/querier_sharding_test.go, integration/querier_tenant_federation_test.go, integration/querier_test.go, integration/query_frontend_cache_test.go, integration/query_frontend_test.go, integration/query_scheduler_test.go, integration/read_write_mode_test.go, integration/ruler_test.go, integration/zone_aware_test.go, vendor/github.com/grafana/e2e/util.go, vendor/modules.txt
Builds on https://github.com/grafana/mimir/pull/3423, split from https://github.com/grafana/mimir/pull/3433.
The integration tests currently only check that range queries don't return an error - they don't check the query response. This PR pulls in https://github.com/grafana/e2e/pull/7 and then adds assertions on the query responses to the integration tests where we make range queries.
https://github.com/grafana/mimir/issues/3363
=> Verify range query result matches expected value in integration tests.

.github/workflows/test-build-deploy.yml, Makefile
Allows the team to opt in to changes in `doc-validator` linting.
=> Pin version of `doc-validator` tool in CI

CHANGELOG.md, pkg/storage/bucket/s3/config.go, pkg/storage/bucket/s3/config_test.go
* endpoint has prefixed with bucket name
Signed-off-by: u5surf <u5.horie@gmail.com>
To fix the issue of 3410, we should be added the validation of endpoint which has not prefixed with bucket name.
Fixes #3410
=> Add validation for newS3Config (#3410)

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
This PR fixes bug introduced in https://github.com/grafana/mimir/pull/3386: series and metadata should be properly sharded into ingesters. This PR also adds test to verify that each ingester only received series that "belong" to it based on ingester tokens.
=> Fix sending all series to all ingesters

CHANGELOG.md, operations/mimir-rules-action/entrypoint.sh
This PR fixes detailed output generated by `mimir-rules-action`, GitHub Actions does not support multiline output.
Adds `%0A` to the input record separator for generating single line output using `awk`.
<details>
<summary>Output Before Change</summary>
```text
Changes are indicated with the following symbols:%0A  + created%0A  - deleted
The following changes will be made if the provided rule set is synced:%0A+ Namespace: test%0A  + Group: mimir_api_1%0A  + Group: mimir_api_2%0A  + Group: mimir_api_3%0A  + Group: mimir_querier_api%0A  + Group: mimir_cache%0A  + Group: mimir_storage%0A  + Group: mimir_queries%0A  + Group: mimir_ingester_queries%0A  + Group: mimir_received_samples%0A  + Group: mimir_exemplars_in%0A  + Group: mimir_received_exemplars%0A  + Group: mimir_exemplars_ingested%0A …
```
=> Fix mimir-rules-action single line output

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/operators-guide/configure/about-dns-service-discovery.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/ruler/ruler.go
The missing schema leads to errors like `improperly formatted alertmanager URL "alertmanager.mimir.svc.cluster.local:8080/alertmanager" (maybe the scheme is missing?)`.
=> Add scheme to DNS service discovery docs

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alertmanager.libsonnet, operations/mimir-mixin/alerts/alerts-utils.libsonnet, operations/mimir-mixin/alerts/alerts.libsonnet, operations/mimir-mixin/alerts/autoscaling.libsonnet, operations/mimir-mixin/alerts/blocks.libsonnet, operations/mimir-mixin/alerts/compactor.libsonnet, operations/mimir-mixin/alerts/continuous-test.libsonnet
Adds runbook_urls to all the mimir alerts
Fixes #2303
=> add runbook urls for alerts

CHANGELOG.md, pkg/alertmanager/alertmanager_client.go, pkg/querier/store_gateway_client.go, pkg/ruler/client_pool.go
This increases the frequency of gRPC client healthchecks. These
healthchecks run asynchronously from gRPC requests. If the healthchecks
fail, all requests using this connection are interrupted.
This will help in cases when the store-gateways become
unresponsive for prolonged periods of time. The querier will more
quickly remove the connection to that store-gateways and retry on
another store-gateway.
Does the same for the ruler-ruler and alertmanager-alertmanager clients
for good measure.
=> Ruler, Querier, AM: Increase frequency of gRPC healthchecks

pkg/storegateway/indexheader/binary_reader.go
=> Remove unused index.Decoder field in BinaryReader

CHANGELOG.md, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/config.libsonnet
While reviewing the mixin, I noticed `MimirGossipMembersMismatch` doesn't work when Mimir is deployed in read-write mode because missing the required matchers. This PR fixes it.
I haven't checked all other alerts 1-by-1. We'll do it later on and open follow up PRs to eventually fix alerts to work in read-write deployment mode too.
Part of #3366
=> Fixed MimirGossipMembersMismatch alert when Mimir is deployed in read-write mode

RELEASE.md
The [RELEASE doc](https://github.com/grafana/mimir/blob/main/RELEASE.md) is great but also very verbose. I'm a big fan of checklists to follow instead, which I find quicker and easier. In this PR I'm proposing to add to the RELEASE doc the markdown of a checklist to copy-paste into a GitHub issue at the beginning of the release process. This is the checklist I've followed for 2.4.
N/A
=> Release: add release issue template to doc

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/alertmanager-resources.libsonnet, operations/mimir-mixin/dashboards/compactor-resources.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview-resources.libsonnet, operations/mimir-mixin/dashboards/reads-resources.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads-resources.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet
This PR introduces a refactoring to utility functions used to generate CPU and memory panels. The current problem is that we support both K8S and baremetal, but they have different queries. When running on K8S we filter by "container" while on baremetal we filter by "instance" (which is a node in practice). However, we shouldn't just use different queries but also different matchers whether the mixin is compiled to run on K8S or baremetal, which is what I'm doing in this PR.
I've also introduced a "Summary" row in the "Writes resources dashboard". The idea is that if you run microservices you both see data in "Summary" **and** per-component rows (e.g. "Distributor"), but if you run read-write you also see summary because there's no dedicated deployment for each component.
**Scope of this …
=> Improve 'Mimir / Writes resources' dashboard to work with read-write deployment mode

operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-resources.json, operations/mimir-mixin/config.libsonnet
This PR partially addresses this comment https://github.com/grafana/mimir/pull/3497#discussion_r1030538608, removing the Helm-compatible prefix matcher from queries if dashboards are compiled for baremetal.
I will address the double `.*.*` at the end of baremetal queries in a follow up PR (I need to do another refactoring before cleanly address this).
N/A
=> Do not build Helm-compatible matchers if dashboards are compiled for baremetal

pkg/storegateway/bucket.go, pkg/storegateway/bucket_chunk_reader.go, pkg/storegateway/bucket_test.go, pkg/util/pool/pool.go, pkg/util/pool/pool_test.go
While working on #3355 I needed to share the byte slabs between
multiple chunkReaders. This PR makes it possible.
=> Store-gateway: move chunk bytes pooling outside of chunk reader

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-overview-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/alertmanager-resources.libsonnet, operations/mimir-mixin/dashboards/compactor-resources.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview-resources.libsonnet, operations/mimir-mixin/dashboards/reads-resources.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads-resources.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet
Similarly to the PR https://github.com/grafana/mimir/pull/3497, in this PR I'm improving the  'Mimir / Reads resources' dashboard to work with read-write deployment mode too.
In details:
- Added "Summary" row to "Mimir / Reads resources" dashboard
- Fixed double `.*.*` suffix in the instance names regex used in baremetal dashboards
- Use `$._config.instance_names` and `$._config.container_names` in all CPU/memory/disk panels (networking panels will be addressed in a follow up PR)
- Use `containerGoHeapInUsePanel()` everywhere (instead of the deprecated `goHeapInUsePanel()`)
**Out of scope of this PR**:
- Add read-write support to compactor and alertmanager resources dashboards
**Screenshots of microservices deployment:**
**Screenshots of read-write deployment:**
Part of #3361
=> Improve 'Mimir / Reads resources' dashboard to work with read-write deployment mode

pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_reader.go
This is the last PR of a refactoring I've started a couple of weeks ago where I've moved `queryStats` outside of `bucketIndexReader`. In this last PR I'm removing `bucketIndexReader.mtx`.
N/A
=> Refactoring: removed mutex from bucketIndexReader

pkg/storegateway/bucket.go, pkg/storegateway/bucket_chunk_reader.go, pkg/storegateway/stats.go, pkg/storegateway/stats_test.go
This PR is a follow up of https://github.com/grafana/mimir/pull/3396. In this PR I'm moving `queryStats` out of `bucketChunkReader` (in #3396 I moved it out of `bucketIndexReader`). To make it happen conveniently, I've changed the `safeQueryStats.merge()` contract to do the merging in place.
N/a
=> Refactoring: remove queryStats from bucketChunkReader

.github/workflows/backport.yaml
Pin the version to before https://github.com/grafana/grafana-github-actions/pull/113 because we don't
want to have the same strict rules for PR labels.
It's also probably a better idea to pin the action to a version or a revision so we don't pull in similar bugs from `main`
=> backport GH action: pin to older version

.github/workflows/backport.yaml
PR https://github.com/grafana/mimir/pull/3511 didn't really pin the
action to the right version. This PR should do so
=> backport GH action: pin to older version follow-up

CHANGELOG.md, operations/mimir-tests/test-autoscaling-generated.yaml, operations/mimir-tests/test-autoscaling.jsonnet, operations/mimir/autoscaling.libsonnet
Ensure that auto-scaling thresholds in mimir-operations are integers.
We've sometimes made the mistake of setting non-integer KEDA thresholds due to this logic not enforcing the expectation of them being integers.
=> mimir-operations: Ensure integer auto-scaling thresholds

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-resources.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json, operations/mimir-mixin-compiled-baremetal/rules.yaml, operations/mimir-mixin/mixin-compiled-baremetal.libsonnet
This PR originates from a quick conversation I had with @wilfriedroset. The "pod" label name doesn't make sense when deploying Mimir on baremetal. "instance" looks a better default.
N/A
=> Dashboards: change default per-instance label name in dashboards compiled for baremetal

CHANGELOG.md, pkg/cacheutil/memcached_client.go, pkg/storegateway/indexcache/memcached_test.go
Extend `cacheutil.Cache` interface to support invalidation by adding the extra `Delete` method.
The necessity of this arises from the _Object Storage Resilience_ initiative for GEM, as we want to leverage all same memcached logic that is shared across components. 
However, current memcached implementation wasn't designed with invalidation in mind, so the additional method is necessary. 
Fixes N/A
=> cacheutil: added cache `Delete` method

integration/read_write_mode_test.go
This PR adds an integration test for recording rule evaluation in read-write deployment mode.
I'm not 100% convinced I've found a robust method to avoid race conditions between setting up the rule, pushing data and then checking the evaluation of the rule - very open to feedback and alternative suggestions.
I will add a separate test for alertmanager in a subsequent PR.
https://github.com/grafana/mimir/issues/3363
=> Read-write deployment mode: add integration test for recording rule evaluation

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json, operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json, operations/mimir-mixin-compiled/dashboards/mimir-compactor.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-ruler.json, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This PR reverts #2914. As explained in https://github.com/grafana/mimir/pull/3324#discussion_r1012704544, this panel is wrong among object store panels because it queries (a) a store-gateway specific metric which (b) tracks the number of inflight `Series()` requests in the store-gateway and not the number of inflight requests to the store-gateway.
N/A
=> Remove "Inflight requests" from object store panels

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-overview-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json, operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview-networking.libsonnet, operations/mimir-mixin/dashboards/reads-networking.libsonnet, operations/mimir-mixin/dashboards/writes-networking.libsonnet
Follow up the work done in https://github.com/grafana/mimir/pull/3497 and https://github.com/grafana/mimir/pull/3504, it this PR I'm addressing the "networking" dashboards. In details:
- Added "Summary" row both to "Writes networking" and "Reads networking" dashboards
- Changed "Inflight requests" and "TCP connections" queries to not match read-write deployment mode when building the panels for a specific component (e.g. "distributor"). This is the same pattern used for "Writes/Reads resources" dashboards too
**Example microservices deployment:**
**Example read-write deployment:**
Part of #3361
=> Improve networking panels to work with read write deployment mode

CHANGELOG.md, operations/mimir-mixin/dashboards/alertmanager-resources.libsonnet, operations/mimir-mixin/dashboards/compactor-resources.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/overview-networking.libsonnet, operations/mimir-mixin/dashboards/overview-resources.libsonnet, operations/mimir-mixin/dashboards/reads-networking.libsonnet, operations/mimir-mixin/dashboards/reads-resources.libsonnet, operations/mimir-mixin/dashboards/remote-ruler-reads-resources.libsonnet, operations/mimir-mixin/dashboards/writes-networking.libsonnet, operations/mimir-mixin/dashboards/writes-resources.libsonnet
This is a dashboards refactoring PR, with no diff in the compiled dashboards. I'm introducing some utillities to build resources and networking panels based on the component name (all such functions are suffixed with `ByComponent` for clarity).
Part of #3361
=> Refactoring: simplified dashboards resources and networking panels utilities

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/migration-guide/migrating-from-single-zone-with-helm.md, docs/sources/operators-guide/configure/reference-configuration-parameters/index.md, pkg/storage/tsdb/config.go
From time to time I see some people from OSS community changing TSDB block ranges period. I think we're not ready for that, given whenever we design features and default config we only think about the TSDB 2h block ranges period. This option was configurable only for testing purposes (e.g. we use it in integration tests) but in my opinion shouldn't be changed (at least I would love that we officially not support any value different than 2h).
For this reason, I'm proposing to hide it from the doc.
I know this PR is controversial, but I genuinely believe that doing so we do a step forward to help OSS community not shooting to their feet (cause if you change it you need to understand how things work internally and which other config options to change accordingly).
Thoughts?
N/A
=> Hide TSDB block ranges period config from doc and mark it experimental

pkg/storegateway/bucket.go
This is a refactoring PR which aims to simplify #3540. My take in this PR is that `s.mtx.RLock()` it not required to log to `spanLogger`.
N/A
=> Refactoring: simplify BucketStore.Series()

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go
This PR is expected to be merged on https://github.com/grafana/mimir/pull/3355 branch (not `main`).
While reviewing `preloadingBatchSet` I found a race condition on `p.err` which is both accessed by the `preload()` goroutine and the one calling `Err()`. I've reproduced it with `TestPreloadingBatchSet_Concurrency` (run it with `go test -race` to detect it).
The fix I propose also change a little bit the behaviour of `preloadingBatchSet`, making it work like the non preloaded version. The idea is that you can keep iterating on `Next()` until the actual batch that returned the error is hit; then `Next()` will return `false` and `Err()` the error. I've added some unit tests on the logic.
N/A
=> Fix preloadingBatchSet race condition and add unit tests

pkg/storegateway/bucket.go
Series() acquires a per-tenant lock when starting to read from a block.
The reason is to prevent a race between addBlock, removeBlock, and
reading from these blocks (for example a block is unloaded after Series()
has already selected it for querying; when accessing this block's
index header we will be using an mmaped file which was deleted from
disk). It needs to release this lock once it has opened an indexReader 
because blocks will wait for all open indexReaders to close before
being unloaded.
This PR moves this locking outside of Series() so we can use further
simplify the code in #3540 (see [comment](https://github.com/grafana/mimir/pull/3540#discussion_r1033623997))
=> store-gateways: extract read locking during Series

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go
This PR is expected to be merged on https://github.com/grafana/mimir/pull/3355 branch (not `main`).
This is really a nit. Since we expect chunks to be sorted by min time, I'm creating fixture batches with sorted chunks and adding a couple of explicit test cases to test it.
N/A
=> Improve TestMergedBatchSet

CHANGELOG.md, go.mod, pkg/util/push/otel.go, pkg/util/push/push_test.go
This doesn't accurately count the dropped samples. For example if a single metric with multiple samples is faulty, we get a single error rather than an error per sample.
But I believe its the best best-effort measurement.
Before we used to do `DatapointCount() - samplesInMap()`
The problem is the following:
1. target_info is a synthetic metric added in Prometheus, so the final samples could higher.
2. A single histogram datapoint in OTLP corresponds to many samples in Prometheus.
=> [otlp] Fix panic in dropped count (again!)

Makefile
Alternate title: improve the speed of our local builds by 30-40% with this one neat trick
Currently, our `Makefile` runs most targets (builds, tests etc.) within a container. To avoid needing to recompile everything for every `make` invocation, we [mount a directory](https://github.com/grafana/mimir/blob/2275d9b0a232ea964cb4809ab62e00a42b64fcb3/Makefile#L218) from the host machine into this container for [Go's cache](https://pkg.go.dev/cmd/go#hdr-Build_and_test_caching).
However, file I/O latency between a container and a macOS host's filesystem is relatively high with Docker Desktop on macOS hosts ([reference 1](https://github.com/docker/roadmap/issues/7), [reference 2](https://github.com/docker/for-mac/issues/77)). Despite recent improvements in Docker Desktop, this increased latency …
=> Improve speed of Golang-related Makefile targets when running on macOS

CHANGELOG.md, pkg/mimir/modules.go
It can be quite hard to find all the activity-tracker logs, I usually grep by `activity` but some customers have that in many queries that are being logged too. Grepping by `activity=` could do the trick sometimes, but also not always.
This adds a `module=activity-tracker` label to all the logs issues for the activity tracker, making it much easier to find them.
None
=> Tag all activity-tracker logs

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
Refactoring PR to rename the unloaded data structures. As separate commits:
- [Move unloaded structs to dedicated file](https://github.com/grafana/mimir/commit/6904b6e73819e543c31378b18dedc1c45a884711) 
- [Rename unloaded data structures](https://github.com/grafana/mimir/commit/b415772dff7b2ab4b7085c8813e8485576c679e5) 
- [Unexport fields](https://github.com/grafana/mimir/commit/bd964045ea28536cfbc5bd4de4e2723d79d00867)
N/A
=> Rename unloaded structs

pkg/storegateway/bucket.go
This PR only moves code out of the Series method. It moved two functions -
one that queries all blocks and one that updates metrics of the
store-gateway from the stats of each Series method call
=> store-gateway series: break up fetching of series into functions

pkg/storage/tsdb/config.go, pkg/storegateway/batch_series.go, pkg/storegateway/bucket.go, pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_stores.go, pkg/storegateway/bucket_test.go
Removes `-blocks-storage.bucket-store.batched-series-loading`. To disable streaming the user can set `-blocks-storage.bucket-store.batch-series-size` to `0`
Also renames some internal config options to make them positive instead of negative.
=> store-gateway streaming: Fix configuration options naming

CHANGELOG.md
I ran this command: `./tools/release/check-changelog.sh release-2.4...main`
It resulted in `138` missing PRs, so I went through each of them to check whether it needs to be added to the changelog. 
This is the output of the script, I added a comment to each line indicating what decision I made about it:
```
Found 219 PRs from 43 authors.
List of missing PR in the CHANGELOG.md:
- #3479: Add OTLP Endpoint to Helm NGINX configuration (#3479)
- #3546: store-gateways: extract read locking during Series (#3546)
- #3543: Refactoring: simplify BucketStore.Series() (#3543)
- #3518: Hide TSDB block ranges period config from doc and mark it experimental (#3518)
- #3510: Read-write deployment mode: add integration test for recording rule evaluation (#3510)
- #3526: Fix small typos in API reference …
```
=> add missing entries and release section to changelog in preparation for release

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go, pkg/storegateway/bucket.go, pkg/storegateway/series_refs.go
In this PR I'm removing `stats` from `seriesChunkRefsSet`. The tracking of stats was also broken (because we were not collecting stats in the top caller). This PR should fix it too, but since we don't have tests on stats yet it's hard to say. The point of this PR is however to remove `stats` from `seriesChunkRefsSet`.
N/A
=> Remove stats from seriesChunkRefsSet

pkg/storegateway/bucket.go, pkg/storegateway/bucket_chunk_reader.go
Few issues fixed in this PR:
- Initialise `chunkReaders.accumulatedStats` (stats are still ignored, will fix in a follow up PR)
- Call the `cleanup()` returned by `synchronousSeriesSet()` only once
- Close the chunk readers only once
N/A
=> Fix store-gateway unit tests

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
In this PR, as separate commits:
- [Move loaded structs to dedicated file](https://github.com/grafana/mimir/commit/85c202ec8054b1ae1011a9cb7f6562d745813bcf) 
- [Renamed 'loaded' structs](https://github.com/grafana/mimir/commit/793b222bba5d02da0c7ab1039381db4ac3e91b6c) 
- [Unexported struct fields](https://github.com/grafana/mimir/commit/8334ef003dd451bacb80d387d1f4d4d2782d858a) 
- [Formatted comments in seriesChunksSet.release()](https://github.com/grafana/mimir/commit/5867c17c502e17ccea8223bbce66b19ef897c2e3) 
- [Removed seriesChunks because unused](https://github.com/grafana/mimir/commit/2f70a4c18a31b439672ba1b08e023033f521f4aa). I initially wanted to use `seriesChunks` in `seriesChunksSet.series` but it turned out to be more complicated than expected because used by the …
=> Rename loaded structs

pkg/storegateway/batch_series.go, pkg/storegateway/series_refs.go
Instead of preallocating the size of the slice, allocate only the
capacity of it. This makes it easier to not return an overly long slices.
=> store-gateway streaming: stop preallocating seriesChunkRefsSet size

pkg/storegateway/batch_series.go, pkg/storegateway/bucket_chunk_reader.go, pkg/storegateway/series_chunks.go
Removing `stats` from `seriesChunksSet`. The stats were unused, while in this PR stats should be updated (but we're still lacking unit tests).
N/A
=> Removed stats from seriesChunksSet

CHANGELOG.md
I noticed too late that as long as the new version isn't released it should be marked as an `rc` in the changelog
Signed-off-by: Mauro Stettler <mauro.stettler@gmail.com>
=> mark version in changelog as rc

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
In this PR I propose to change `seriesChunkRefsIterator` `reset()` and `Done()` logic, aiming to make it slightly more consistent. The proposed changes are:
- `reset()` does **not** implicitly invoke `Next()`, so calling `reset()` is like creating a `newSeriesChunkRefsIterator()`
- `Done()` returns `false` before `Next()` is called for the first time if and only if `Next()` would call `true` the first time (which means `Done()` returns `true` if the underlying set is empty).
In this PR I've also handled the case a set is empty and unit tests for:
- `seriesSetWithoutChunks` (see changes to its `Next()`)
- `mergedBatchSet` (see changes to its `Next()`)
- `chainedBatchSetIterator` (see changes to its `Next()`)
N/A
=> Changed seriesChunkRefsIterator's reset() and Done() logic

CHANGELOG.md
Two items were listed as part of `2.5.0-rc.0` which aren't part of it
=> Fixing the changelog in main

pkg/storage/tsdb/metadata/meta.go
Brought in by #3288, but not used anywhere.
- NA `CHANGELOG.md` updated - not user-visible.
=> Remove unused GroupKey function

pkg/storegateway/batch_series_test.go
This adds tests for `loadingBatchSet`. They end up exercising `chunkReaders` too.
=> Streaming store-gateway: Add tests for loadingBatchSet

pkg/storegateway/batch_series.go, pkg/storegateway/batch_series_test.go
These tests use the e2e framework. The framework is not ideal for these
tests because the blocks it creates have a lot of variability. This
is also the reason why we cannot assert more exactly on the selected
chunk refs.
The next step for this will be to refactor
blockSeriesChunkRefsSetsIterator to be able to circumvent the coupling
that an indexReader has to a BucketStore and add further testing.
=> Streaming store-gateway: Add tests for blockSeriesChunkRefsSetsIterator

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, pkg/ruler/notifier.go
This PR addressed this comment https://github.com/grafana/mimir/pull/3432#discussion_r1036792258
This makes the flag consistent with the existing ruler alertmanager client flags. It is ok to merge this change because `-ruler.tls-enabled` is still not part of any release
=> Rename -ruler.tls-enabled to -ruler.alertmanager-client.tls-enabled

pkg/frontend/querymiddleware/roundtrip.go, pkg/frontend/querymiddleware/roundtrip_test.go, pkg/frontend/transport/handler_test.go
If the form was already parsed by a downstream middleware, we need to add it to that form too, otherwise it won't be available to upstream by just adding it to the url query.
This implement's @pstibrany's suggestion https://github.com/grafana/mimir/pull/3588#discussion_r1036930450 and copies all the tests from that PR.
Will make https://github.com/grafana/mimir/pull/3561 easier to review.
=> Add default "time" param to parsed form (if any)

pkg/storegateway/bucket.go, pkg/storegateway/bucket_chunk_reader.go, pkg/storegateway/bucket_test.go
Currently `newBucketChunkReader()` requires the chunks pool in input. This complicates the implementation of the streaming store-gateway, so in this PR I'm proposing to remove it and just pass the chunks pool to `bucketChunkReader.load()` which is where is required. Keep in mind `pool.BatchBytes` is concurrency safe.
N/A
=> Refactoring: do not pass the chunks pool to newBucketChunkReader()

CHANGELOG.md, pkg/mimir/mimir.go
If `/ready` is called and some services are not yet running, we currently log a message like the following:
```
level=debug ts=2022-12-02T01:52:02.411627554Z caller=mimir.go:859 msg="some services are not Running" services="unsupported value type"
```
(note the `unsupported value type` for `services`)
This PR fixes this so that we instead log the names and states of the services that are not running, for example:
```
level=debug ts=2022-12-02T02:28:15.070733296Z caller=mimir.go:862 msg="some services are not Running" services="store-gateway: Starting, compactor: Starting"
```
It would also be great to have a linter that catches issues like these, but that seems out of scope for this PR.
n/a
=> Fix "unsupported value type" logged when calling /ready and some services are not yet running.

pkg/distributor/distributor_test.go, pkg/ingester/client/compat.go, pkg/ingester/ingester.go, pkg/ingester/user_tsdb.go
* Remove unnecessary return values from `client.FromMetricsForLabelMatchersRequest`
* Document `Ingester.MetricsForLabelMatchers`
* Document `userTSDB.Querier`
=> Ingester: Simplify code a bit, plus document a couple of methods

pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
This is the next step to introducing our changes from #3355. This
commit adds the iterators (and tests for them) used over the data
structures we added in #3587.
=> store-gateway: add iterators for seriesChunks and seriesChunkRefs

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/compactor.libsonnet
There `component` label does not exist. However, there is no need to filter on component as cortex_compactor_blocks_marked_for_no_compaction_total is only sent by the compactor.
Partial fixes https://github.com/grafana/mimir/issues/3366
=> alerts: Fix MimirCompactorSkippedBlocksWithOutOfOrderChunks

pkg/distributor/distributor_test.go, pkg/util/validation/errors.go, pkg/util/validation/validate.go, pkg/util/validation/validate_test.go
Distributor always sorts labels at the relabeling stage, so this check would never have triggered an error.
Add a test to prove this.
Also fix another test which was nearly checking the sorting function.
And clarify a comment which mentions unsorted labels.
- NA `CHANGELOG.md` updated - not user-visible.
=> Distributor validation: stop checking series have sorted labels

pkg/storegateway/batch_series.go, pkg/storegateway/series_refs.go
Move these into files that are present on main, so it's easier to upstream them without conflicts later.
=> Streaming store-gateway: Move seriesHasher

pkg/storegateway/bucket_test.go, pkg/storegateway/postings_codec_test.go
in the streaming store-gateway work we need more control over what
series and samples are written to a test block. This PR makes it
possible for each test that creates a test block to write arbitrary
series and samples.
=> Store-gateway: Make e2e test setup more flexible

pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_stores_test.go
The current e2e testing framework allows to inject a bucket
implementation. Each end-to-end test then repeats mostly the same code
to set up the testing suite.
This PR moves the testing setup further up and allows each test to
either immediately get a ready test suite with sensible defaults _or_
to customize the test suite with the testing config.
This change will be needed for the streaming store-gateway work where we
want to run the whole e2e test suite also for the streaming
implementation.
=> store-gateway: more flexible e2e testing setup (pt.2)

CHANGELOG.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
Empty labels are stripped when the series reaches TSDB, so we should remove them earlier to keep things consistent.
- NA Documentation added - this is not user-visible; we are just stripping them earlier.
=> distributor: remove labels with empty values

pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
We are adding three iterators:
* `loadingSeriesChunkRefsSetIterator` is responsible for loading chunks
from the index
* `postingsSetsIterator` is responsible for batching postings so loading
series from the index doesn't load all labels and chunk refs from the
index in one go
* `limitingSeriesChunkRefsSetIterator` is responsible for limiting
series and chunks within a request
We are also adding a function to set up these three iterators for an
incoming Series() request for a block (`openBlockSeriesChunkRefsSetsIterator`).
> __Note to reviewers__: this PR uses the changes in https://github.com/grafana/mimir/pull/3644, so it's the base branch of this PR. After merging #3644, the base branch of this PR should change to `main` automatically
Co-authored-by: Marco Pracucci <marco@pracucci.com> …
=> Streaming store-gateway: add iterators for loading series from index

CHANGELOG.md, docs/sources/mimir/operators-guide/tools/mimirtool.md, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_stores_test.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
This pulls in the changes from https://github.com/grafana/mimir/pull/3645 and https://github.com/grafana/mimir/pull/3652
=> Merge main into dimitar/store-gateway-async-series

pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_test.go
This PR also removes the streaming implementation from
* `TestSeries_BlockWithMultipleChunks`, which I think is ok because we
already have unit tests for multiple chunks in our units
* `TestLabelNamesAndValuesHints` label values aren't using streaming
still anyway
* `TestSeries_ErrorUnmarshallingRequestHints` this should be independent
of how series are fetched (streaming or not)
pkg/storegateway now takes 109.121s to run on my machine compared to the
94.677s it took before
=> store-gateway: bucketStore tests with and without streaming

CHANGELOG.md, pkg/frontend/frontend_test.go, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go, pkg/frontend/v1/frontend_test.go, pkg/mimir/modules.go
Query-frontend uses the activity-tracker for the PromQL engine, but that is just for the sharded queries execution. Query-frontend does much more than that, and we should also track that.
This adds every HTTP request received by the Handler to the activity tracker.
Fixes (none)
=> Query-frontend: use activity tracker for requests

pkg/storegateway/bucket.go, pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_index_reader.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go, pkg/storegateway/stats.go
Starts measuring a few things (below). All are measured in p99 summaries.
* the time it takes to load the chunks for each batch (p99 summary)
* we can see how this changes with changes batch size
* the time it takes to load the index for each batch (p99 summary)
* we can see how this changes with changes batch size
* the time it takes to load the expanded postings at the beginning of the request (p99 summary)
* we can see whether this is something we should split or parallelize
* the time it takes to wait for the next preloaded batch (p99 summary)
* we can see how effective preloading is
also fixes a benign bug where postingsToFetch wasn't merged in queryStats
=> Add an iterator which measures durations of Next calls

CHANGELOG.md, pkg/alertmanager/multitenant.go, pkg/alertmanager/multitenant_test.go
When alertmanager.data_dir is set to a relative path (as in default configuration), templates are deleted and recreated on a regular basis.
This PR fix the issue.
Fixes #3591
=> Use absolute path of template to decide if we need to remove it

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/large-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/small-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/rolebinding.yaml, operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/rolebinding.yaml
This PR enables the rollout-operator serviceAccount to use podSecurityPolicies. 
Currently mimir has the possibility to use podSecurityPolicies for all components with the exception of the rollout-operator,
which makes the deployment of the rollout-operator impossible in an environment, where the use of podSecurityPolicies are active.
=> Rollout operator psp

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, pkg/querier/engine/config.go
Remove reference to query-frontend for flag -querier.max-concurrent, since it's (probably) not used by the query-frontend any longer.
@pstibrany observed that most likely the `-querier.max-concurrent` flag is not in use by the query-frontend since #2598, but its help string still says it has to be set also for the query-frontend.
TODO:
=> querier: Remove max concurrency reference to query-frontend

integration/read_write_mode_test.go
This PR adds two further integration tests for read-write deployment mode:
* querying from long-term storage
* alerting
One unexpected behaviour I ran into was that I needed to configure the Alertmanager URL in the alerting test. Should backend instances be configured to send alerts to themselves by default? (Is there any situation where this wouldn't be a reasonable default?)
On top of this, when no Alertmanager URL is configured, the alerts aren't sent anywhere and no warning is logged - should we perhaps log a warning when alerting rules are configured but the Alertmanager URL isn't set? 
#3363
=> Read-write deployment mode integration tests: querying from long-term storage and alerting rules

pkg/storegateway/indexheader/index/symbols.go, pkg/storegateway/indexheader/index/symbols_test.go
Removes a method used only by a single test.
Fixes a suggestion from the review of [#3639](https://github.com/grafana/mimir/pull/3639/files#r1042509225).
=> Remove Symbols.Size() method used only for tests.

docs/sources/mimir/operators-guide/run-production-environment/scaling-out.md
If we don't remove the instances form the ring before proceeding to the
next availability zone, then we risk losing redundancy for the blocks
that are replicated on these instances.
This PR updates the docs to mention forgetting the instances in the
store-gateway ring.
=> docs: update instructions for scaling down store-gateways

pkg/storegateway/bucket.go
The observations were observing nanoseconds (time.Duration)
instead of seconds.
=> store-gateway: fix expanded postings duration histogram

.github/workflows/helm-ci.yml, .github/workflows/test-build-deploy.yml, Makefile, mimir-build-image/build.sh
Same as #3527 + a fix for Linux hosts (see https://github.com/grafana/mimir/pull/3527#issuecomment-1330810445 and #3569)
I don't have permission to push an updated build image - could a maintainer please follow the instructions in https://github.com/grafana/mimir/blob/1806872c575eeaaaab132cce55cd157360cfdaca/docs/internal/how-to-update-the-build-image.md to build, push and update the image reference everywhere?
n/a
=> Improve speed of Golang-related Makefile targets when running on macOS (and don't break Linux hosts)

CHANGELOG.md, development/mimir-microservices-mode/config/grafana-agent.yaml, development/mimir-microservices-mode/config/prometheus.yaml, development/mimir-microservices-mode/docker-compose.jsonnet, development/mimir-microservices-mode/docker-compose.yml, docs/sources/mimir/operators-guide/mimir-runbooks/_index.md, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
Under certain circumstances, it can happen that ingester replicas have no tenant assigned even after the cluster has started ingesting real customer data. This adds an alert that triggers in this situation.
It also adds the compiled alerts to the Prometheus configuration for docker-compose microservices development mode, which is helpful when developing/testing alerts manually and simplifies the scraping config a bit.
Relates to #1959
=> Alert when an ingester replica does not have any tenant assigned

CHANGELOG.md, operations/mimir/config.libsonnet, operations/mimir/overrides-exporter.libsonnet, operations/mimir/shuffle-sharding.libsonnet
We scale past mega_user on a regular basis. We should give massive users an indicator of potential config that can be useful as they user higher AS counts. This is for non-insane-cardinality-users, just a large count of active series and accompanied growth.
=> We need larger user indicators

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
In #3681, we added an alert for idle ingesters. @pracucci suggested that we make this alert conditional on a cluster having ingested a certain number of time series already, to avoid triggering it in newly commissioned clusters with a low number of time series.
n/a
=> Alert on idle ingesters only after metric ingestion has started

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json, operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json, operations/mimir-mixin/dashboards/rollout-progress.libsonnet
Updates the 'Rollout Progress' mixin dashboard to use `$._config.job_names.distributor` for writes and `$._config.job_names.query_frontend` for reads when gateway is not enabled.
Before this change, panels would show 'No Data' (assuming the gateway wasn't enabled):
After this change, data appears as expected:
Fixes #3674
=> Revert to distributor and query-frontend metrics if gateway is not enabled

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/operators-guide/configure/about-versioning.md, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, pkg/storage/tsdb/config.go, pkg/storegateway/bucket_stores.go
Remove the ability to reject new requests once the number of in-flight object storage requests exceeds a configured limit. This setting didn't prove to be any help preventing store-gateway OOM kills.
N/A
=> Remove store-gateway rejecting gate experiment

pkg/storegateway/indexheader/encoding/factory.go, pkg/storegateway/indexheader/encoding/reader.go, pkg/storegateway/indexheader/encoding/reader_test.go
Previously, we created a separate pool of `bufio.Reader`s for each `DecbufFactory` (and we create a new factory for each index-header). This is unnecessary - we can share the same pool of buffers across all `Decbuf`s.
#3465 
=> Store gateway mmap removal: use a shared pool of buffers across all Decbuf instances

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/operators-guide/configure/about-versioning.md, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, pkg/storegateway/indexheader/encoding/encoding.go, pkg/storegateway/indexheader/encoding/encoding_test.go, pkg/storegateway/indexheader/encoding/factory.go, pkg/storegateway/indexheader/encoding/factory_test.go, pkg/storegateway/indexheader/encoding/reader.go, pkg/storegateway/indexheader/encoding/reader_test.go, pkg/storegateway/indexheader/header.go, pkg/storegateway/indexheader/header_test.go, pkg/storegateway/indexheader/index/postings.go, pkg/storegateway/indexheader/index/symbols.go, pkg/storegateway/indexheader/index/symbols_test.go, pkg/storegateway/indexheader/lazy_binary_reader_test.go, pkg/storegateway/indexheader/reader_pool.go, pkg/storegateway/indexheader/stream_binary_reader.go, pkg/storegateway/indexheader/stream_binary_reader_test.go
Add a pool of file handles to avoid the cost of opening and closing files for each operation that needs access to the index-header file (symbols and posting offsets). The default number of handles to keep per index-header is `1` to maintain parity with the existing mmap implementation (which keeps a single file handle for the index-header open for the duration of the reader).
See #3465
```
$ benchstat -delta-test=none old.txt new.txt 
name                                   old time/op    new time/op    delta
DecbufFactory_NewDecbufAtUnchecked-16    2.98µs ± 0%    0.86µs ± 0%  -71.12%
name                                   old alloc/op   new alloc/op   delta
DecbufFactory_NewDecbufAtUnchecked-16      232B ± 0%       48B ± 0%  -79.31%
name                                   old allocs/op …
```
=> Pool file handles used by StreamBinaryReader components

development/mimir-microservices-mode/Makefile, development/mimir-read-write-mode/Makefile
Fixes this problem: currently, you can modify the docker-compose.yml directly (which is supposed to be generated) without modifying the docker-compose.jsonnet template and have it still pass the CI/CD tests, which doesn't seem to be intended, because of this issue https://stackoverflow.com/questions/3931741/why-does-make-think-the-target-is-up-to-date where if the make command name is the same as the name of a file in that folder that already exists, it does not regenerate it and hence does not notice that the file has changed. So we use `.PHONY` to ensure that `make check` in our CI/CD will actually regenerate the file properly.
N/A. CI/CD issue only, doesn't affect users
=> Fix makefiles in development folder to properly check yml in CI/CD

pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go, pkg/storegateway/indexcache/cache.go, pkg/storegateway/indexcache/cache_test.go, pkg/storegateway/indexcache/inmemory.go, pkg/storegateway/indexcache/inmemory_test.go, pkg/storegateway/indexcache/memcached.go, pkg/storegateway/indexcache/memcached_test.go, pkg/storegateway/indexcache/tracing.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
* doesn't change how the default implementation caches series
* adds caching to the streaming implementation
* the streaming implementation caches the series for each batch
* part of the hash key is a reproducible hash of the postings list 
* each different set can be cached or not, so eviction from the cache of single batches doesn't affect the cacheability of the whole request by more than necessary
__possible problems:__
* default and streaming implementations cannot reuse each other's caches because they use different keys
=> streaming store-gateway: Add caching of series when skipChunks

CHANGELOG.md, packaging/deb/control/postinst
This pull request fix two things with the post-install of the Debian package:
- The environment path was wrong in one place
- The user creation was not working properly 
Fixes #3471 
Here is the complete old post-install script (after fpm process):
```
#!/bin/sh
after_upgrade() {
:
systemctl --system daemon-reload >/dev/null || true
debsystemctl=$(command -v deb-systemd-invoke || echo systemctl)
if ! systemctl is-enabled mimir >/dev/null 
then
: # Ensure this if-clause is not empty. If it were empty, and we had an 'else', then it is an error in shell syntax
else
$debsystemctl restart mimir >/dev/null || true
fi
}
after_install() {
:
#!/bin/sh
set -e
[ -f /etc/sysconfig/mimir ] && . /etc/default/mimir
case "$1" in
configure)
[ -z "$MIMIR_USER" ] && MIMIR_USER="mimir"
[ -z "$MIMIR_GROUP" ] …
```
=> Fix deb package post install

integration/backward_compatibility.go
This PR adds mimir-2.5.0 to backward compatibility test.
Part of release process: https://github.com/grafana/mimir/issues/3525
=> Add Mimir 2.5.0 to compatibility test.

RELEASE.md, tools/release/create-pr-to-merge-release-branch-to-main.sh, tools/release/merge-approved-pr-branch-to-main.sh
This PR adds a script for merging branch with approved PR to `main`, with a merge commit.
This is useful for merging release branch back to main. (But it should work for any branch with approved PR)
PR https://github.com/grafana/mimir/pull/3727 was merged using this script by calling `tools/release/merge-approved-pr-branch-to-main.sh merge-release-2.5-to-main`.
Benefit of this script is that it automates the task and doesn't require changing of repository permissions.
=> Add script for merging approved branch with merge commit

pkg/storegateway/indexheader/lazy_binary_reader.go
Remove an extra unneeded `time.Now()` call. Probably not a measurable performance improvement but I noticed it while poking through some unrelated profiling.
N/A
=> Only measure time taken to load an index-header once

pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_postings.go, pkg/storegateway/bucket_test.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
Adds tests for when running the streaming implementation with query
sharding and index cache. This is a follow-up of #3687
This PR also includes some changes to interfaces so that it's easier to mock the hash of a series.
=> streaming store-gateway: add tests for index cache with query sharding

pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/storegateway/series_refs_test.go, pkg/util/pool/pool.go, pkg/util/pool/pool_test.go, pkg/util/pool/tracking.go
Looking at streaming store-gateway profiles, I can see about 10% of memory allocated by `loadingSeriesChunksSetIterator.Next()`. There are two main memory allocations there:
- `make([]seriesEntry, nextUnloaded.len())`
- `make([]storepb.AggrChunk, len(s.chunks))`
In this PR I propose to use a memory pool for both of them (separate pools). To increase the chances the slice capacity is large enough to be reused, I've adopted the following strategies:
- `[]seriesEntry` allocate it based on the batch size (all real batches will have that size except the last one)
- `[]storepb.AggrChunk` use a slab (here the number of chunks is not predictable, so we can't use a good default)
I've introduced `pool.SlabPool` which is like `pool.BatchBytes` but works with generics and can never return `error` (so …
=> Reduce memory allocations for seriesChunksSet.series and its chunks slices

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json, operations/mimir-mixin-compiled/dashboards/mimir-tenants.json, operations/mimir-mixin/dashboards/tenants.libsonnet
Some panels in tenants dashboard use a hardcoded label to select metrics to display.
=> Make tenants dashboard compatible with all deployment types

CHANGELOG.md, operations/mimir/read-write-deployment/backend.libsonnet, operations/mimir/read-write-deployment/write.libsonnet
A tiny fix to read-write jsonnet to apply ingesters and store-gateways per-zone CLI flags overrides to read-write deployment mode too.
_This PR is expected to be a no-op._
N/A
=> Apply ingesters and store-gateways per-zone CLI flags overrides to read-write deployment mode

CHANGELOG.md, pkg/storegateway/partitioner.go, pkg/storegateway/partitioner_test.go
This commit fixes a partitioner metric and adds a new one
The partitioner currently exposes 4 counters
* `cortex_bucket_store_partitioner_requested_bytes_total`
* `cortex_bucket_store_partitioner_requested_ranges_total`
* `cortex_bucket_store_partitioner_expanded_bytes_total`
* `cortex_bucket_store_partitioner_expanded_ranges_total`
Currently, `cortex_bucket_store_partitioner_requested_bytes_total`
exposes the total sizes of all ranges independant of each other. This
represents their total size without merging any overlapping sizes.
This is not very useful information. This PR changes that metric to
report the number of bytes that would be fetched if the gap that the
partitioner fills is 0. This way you can use
`cortex_bucket_store_partitioner_requested_bytes_total` in combination
with …
=> partitioner: report more accurate metrics

pkg/storegateway/indexheader/encoding/encoding.go, pkg/storegateway/indexheader/encoding/encoding_test.go, pkg/storegateway/indexheader/index/postings.go, pkg/storegateway/indexheader/index/symbols.go, pkg/storegateway/indexheader/reader_benchmarks_test.go
Note to reviewers: this PR is made up of three main commits that build upon each other. I'd suggest reviewing each separately.
---
de7f5af improves the performance of loading index-headers with the mmap-less reader by 0-23%. This is due to removing an unnecessary allocation for every value of the postings offset table.
<details><summary>Benchmark results</summary>
```
name                                         old time/op    new time/op    delta
NewStreamBinaryReader/1Names1Values-10          122µs ± 8%     122µs ± 5%     ~     (p=0.690 n=5+5)
NewStreamBinaryReader/1Names10Values-10         124µs ± 4%     131µs ± 9%     ~     (p=0.056 n=5+5)
NewStreamBinaryReader/1Names100Values-10        138µs ± 2%     135µs ± 3%     ~     (p=0.056 n=5+5)
NewStreamBinaryReader/1Names500Values-10 …
```
=> Store gateway mmap removal: optimise index-header reader and symbol lookups

CHANGELOG.md, pkg/storegateway/indexcache/cache.go, pkg/storegateway/indexcache/cache_test.go
This PR solves two problems:
* a bug I just discovered - when we previously constructed the byte slice of the postings we were incorrectly setting the byte position of the octet from the posting
* it was 
```go
hashable[i+octet]   = byte(posting >> (octet * 8))
```
* it should be 
```go
hashable[i*8+octet] = byte(posting >> (octet * 8))
```
* avoids copying the postings into a byte slice altogether. Instead, it creates a new sliceHeader that it points to the data of the postings and adjusts the length and capacity.
It also changes the hashing functions from SHA1 (20B) + Blake2 (32B) to only Blake2 (32B). The memcached cache key is too small to fit both SHA1 and Blake2. In another change that will also remove the matchers hash from the key I will use Blake2 with 42B
=> streaming store-gateway: avoid copying postings when hashing them

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/gateway/gateway-dep.yaml
* use nginx-configmap.yaml's sha256sum when not isGEMGateway
* use mergeOverwrite instead of merge
Gateway's `checksum/config` not change after `gateway.nginx.config.file` modified when `gateway.enabledNonEnterprise` is true.
1. `nginx-configmap.yaml` should be used when `$isGEMGateway` is false (like nginx container).
2. use [mergeOverwrite](https://helm.sh/docs/chart_template_guide/function_list/#mergeoverwrite-mustmergeoverwrite) instead of merge to merge the parameters correctly, which old `$annotations` as "dest" and the new dict as "source".
n/a
=> Fixed helm gateway's checksum/config when using nginx

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/gateway/gateway-servmon.yaml
Gateway's nginx container not offer metrics for ServiceMonitor.
We should remove gateway's ServiceMonitor when using nginx ( as`.Values.gateway.enabledNonEnterprise` is true).
Fixes #3688
=> Disable helm gateway's serviceMonitor when using nginx

CHANGELOG.md, operations/mimir-tests/test-deployment-mode-migration-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml, operations/mimir/read-write-deployment/backend.libsonnet
While testing the migration from microservices to read-write mode, I've noticed the mimir-backend misses the overrides-exporter CLI flags. This PR fixes it.
N/A
=> Apply overrides-exporter CLI flags to mimir-backend

CHANGELOG.md, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/compactor.libsonnet
While testing the read-write deployment mode, we realised "MimirCompactorHasNotUploadedBlocks" alert may fire if a compactor replica has nothing to do. Since the compactor runs as part of the backend deployment, it's possible that not all replicas have a tenant assigned and so jobs to run.
In this PR I propose to fix the "MimirCompactorHasNotUploadedBlocks" alert checking whether the compactor replica has started some compactions in the last 24h (because this alert is designed to alert if no block is uploaded in the last 24h).
I've also checked other compactor alerts and they should be fine. I've added a comment to the query for the ones I've checked.
Part of https://github.com/grafana/mimir/issues/3366
=> Fix MimirCompactorHasNotUploadedBlocks to not fire if compactor has nothing to do

CHANGELOG.md, pkg/storegateway/indexheader/encoding/encoding.go, pkg/storegateway/indexheader/encoding/encoding_test.go, pkg/storegateway/indexheader/encoding/reader.go, pkg/storegateway/indexheader/encoding/reader_test.go, pkg/storegateway/indexheader/index/postings.go, pkg/storegateway/indexheader/index/symbols.go
This PR introduces a `Position()` method to `Decbuf`. This allows us to remove a number of confusing calculations involving the remaining length of a `Decbuf`. ([This](https://github.com/grafana/mimir/pull/3742#discussion_r1052108186) is one example of the confusion the current implementation can cause.)
I've tried to do this incrementally. I'd suggest reviewing each commit individually rather than trying to review the entire PR's changes in one go.
Relates to #3465, builds upon #3742.
=> Store gateway mmap removal: introduce `Decbuf.Position()` to simplify logic

CHANGELOG.md, pkg/distributor/distributor.go, pkg/scheduler/schedulerdiscovery/ring.go
Fixes an issue with distributors and query-schedulers where they were emitting metrics without a `cortex_` prefix which is expected in all our dashboards.
See https://github.com/grafana/mimir/pull/3771#discussion_r1055445430
=> Make sure lifecycler metrics have "cortex_" prefix

.github/workflows/compare-helm-with-jsonnet.yml
The `compare-helm-with-jsonnet` CI job occasionally fails while trying to download `yq`. 
This is a known issue with the `action-setup-yq` action, so this PR replaces it with the `fetch-gh-release-asset` action which we're using to fetch other release binaries in the same job. This action does not suffer from rate limiting as it uses the job's token (`GITHUB_TOKEN`) to make requests to the GitHub API.
https://github.com/frenck/action-setup-yq/issues/35
=> Use authentication to download `yq` to avoid build failures due to GitHub API rate limiting

Makefile
This PR adds the ability to disable generating Go files from protobuf definitions during a build.
This is useful for scenarios where we want to build the source code as-is, such as the [`mimirtool` Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mimirtool.rb). 
(Homebrew's build process creates a fresh clone of the repository before building `mimirtool`. However, after a fresh Git clone of this repository, file timestamps will reflect when Git wrote the file to disk, not when each file was last modified, so `make` will regenerate files unnecessarily. This introduces additional dependencies such as `protoc` to the formula's build process, and risks introducing difficult-to-reproduce issues where some files are sometimes regenerated with different contents …
=> Add flag to disable regenerating Go files from protobuf definitions during build.

CHANGELOG.md, operations/mimir-tests/test-deployment-mode-migration-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml, operations/mimir/read-write-deployment/utils.libsonnet
We migrated from the deprecated `v1beta1` PodDisruptionBudget in #3284, but we've since added Jsonnet support for read-write deployment mode, which is still using `v1beta1`. 
This PR switches the PodDisruptionBudgets in read-write deployment mode to use `v1` as well.
This fixes warnings like these:
```
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
Relates to #3284 and #937.
=> Use stable `v1` PodDisruptionBudget rather than deprecated `v1beta1` when deploying read-write deployment mode.

pkg/mimir/modules.go
Wrap error from `bucket.NewClient` in usage-stats module. The motivation is dealing with an error from initializing the usage-stats module, most likely originating from `bucket.NewClient`, but not knowing the context for sure.
Also use `UsageStats` string constant consistently.
=> usage-stats: Wrap bucket client error

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/operators-guide/configure/about-versioning.md, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, go.mod, go.sum, pkg/ingester/ingester.go, pkg/storage/tsdb/config.go, vendor/github.com/prometheus/prometheus/tsdb/block.go, vendor/github.com/prometheus/prometheus/tsdb/db.go, vendor/github.com/prometheus/prometheus/tsdb/head.go, vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go, vendor/modules.txt
Makes use of https://github.com/grafana/mimir-prometheus/pull/378 to allow forcing usage of postings for matchers cache in the Head. This is especially useful in combination with out-of-order ingestion, since we can reuse the postings for matchers calls done for OOOHead.
None
=> Experimental forcing of postings for matchers cache

operations/mimir/autoscaling.libsonnet
In operations/mimir/autoscaling.libsonnet, fix typo in comment. Also move `minReplicaCount` before `maxReplicaCount` to be consistent with min/max comment, improving readability a tad.
=> autoscaling.libsonnet: Fix typo in comment

operations/mimir/autoscaling.libsonnet
Fix typo in autoscaling Jsonnet comment.
=> autoscaling: Fix comment typo

CHANGELOG.md, docs/sources/mimir/operators-guide/mimir-runbooks/_index.md, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alertmanager.libsonnet
This adds an alert to detect alertmanager instances that don't own any tenants.
Fixes #1959
=> Alerts: Add alert that triggers for idle alertmanager instances

CHANGELOG.md, docs/sources/mimir/operators-guide/mimir-runbooks/_index.md, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/alerts.libsonnet
This PR adds an alert to help detect idling ruler instances in microservices mode that aren't evaluating any rule groups.
Note: The unrelated change in `CHANGELOG.md` recovers a line that I believe got lost in a previous merge.
Partially fixes #1959
=> Alerts: Add an alert to detect idling ruler instances

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, pkg/ruler/ruler.go
This change reflects how we operate the ruler at Grafana Labs.
The benefit is that alerts no longer retrigger when a ruler starts when
their "for" period is longer than the for-grace-period.
A possible drawback of having a reduced grace period means that upon a
restart the ruler will send queries to the ingesters (or long-term
storage, depending on the value of `ruler.for-outage-tolerance`)to query
the state of alerts. These queries are very light and do not show to be
an issue.
This PR also updates the docs around this flag, because I found them to 
be too brief.
Related to #2888
Fixes #3814
=> ruler: set default of for-grace-period=2m and update docs

CHANGELOG.md, RELEASE.md, docs/sources/mimir/operators-guide/tools/mimirtool.md
`mimirtool` is now available through Homebrew. This PR adds instructions for how to install `mimirtool` with Homebrew on macOS, and adds a note to the release checklist.
(none)
=> Add instructions for installing mimirtool with Homebrew.

CHANGELOG.md, pkg/querier/blocks_store_queryable.go, pkg/querier/blocks_store_queryable_test.go
Stops ignoring the `context.Canceled` error from store gateway interaction: this made the entire request fail as "consistency check" because that store gateway didn't have the block, isntead of actually failing as `context.Canceled` which isn't a server's fault (usually).
Fixes internal.
=> Do not fail as consistency check for canceled requests

pkg/storegateway/bucket.go, pkg/storegateway/bucket_chunk_reader.go, pkg/storegateway/bucket_test.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_chunks_test.go, pkg/util/pool/pool.go, pkg/util/pool/pool_test.go
This PR introduces a new global memory pool wrapped by `SlabPool` to replace the `BatchBytes`-wrapped pool that  `storegateway.chunkReader`s currently use. 
Benchmark results for
```
go test -run '^$' -bench 'BenchmarkBucket_Series|BenchmarkLoadingSeriesChunksSetIterator' -benchmem -count=3
```
are here: [benchmark_differences.txt](https://github.com/grafana/mimir/files/10293767/benchmark_differences.txt)
n/a
=> Use SafeSlabPool as memory pool for individual chunks' data

pkg/alertmanager/multitenant_test.go
Some minor cleanup in Alertmanager tests:
* Make `simpleConfigOne` and `simpleConfigTwo` into constants, for readability
* Use `require.NoError` instead of `assert.NoError`, to prevent tests from continuing after unexpected errors
=> Alertmanager: Some minor cleanup in tests

pkg/ingester/ingester.go
While checking the ingester code, I've noticed `ingesterClientFactory` is unused so I'm removing it.
N/A
=> Chore: removed unused ingester's ingesterClientFactory

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go
This tiny PR removes unnecessary error return value (which was always `nil`) from `tokenForLabels` method in distributor. No user-visible change.
=> Remove always-nil error return value from distributor method

CHANGELOG.md, operations/mimir-tests/test-deployment-mode-migration-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml, operations/mimir/read-write-deployment/read.libsonnet
In https://github.com/grafana/mimir/pull/3862 I forgot to upstream another change required to fix #3860 in the read-write mode, which is configuring `mimir-read` Kubernetes service as **headless**.
Fixes #3860
=> Fix mimir-read Kubernetes service

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/ci/offline/gateway-enterprise-values.yaml, operations/helm/charts/mimir-distributed/ci/offline/gateway-nginx-values.yaml, operations/helm/charts/mimir-distributed/values.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-dep.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-ingress.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-svc.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/nginx-configmap.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
* Forwards `/otlp/v1/metrics` to the distributor for the `gateway` NGINX deployment (different from the NGINX deployment that the `nginx` section creates)
* Changes the used service for the alertmanager from the regular service to the headless service. This is important because otherwise the NGINX doesn't work with the multi-zone alertmanager
* It also corrects the tests that generate the committed manifests to actually render the NGINX deployment.
Fixes https://github.com/grafana/mimir/issues/3830
=> Helm: use headless alertmanager,add OTLP endpoint in gateway NGINX

integration/querier_test.go, pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_postings.go, pkg/storegateway/bucket_test.go, pkg/storegateway/series_refs_test.go
See https://github.com/grafana/mimir/issues/3847
In the case __some matchers in the request try to select a non-existent label value__ this PR short-circuits the lookup in the cache and the bucket by using the index header first.
Why? Because sometimes the list of postings can be massive (up to 1MB of diff-encoded, snappy-compressed postings). Fetching and decoding these from the cache or the bucket takes a lot of effort for something we can tell by doing a lookup on the local disk.
This comes with the drawback that now we will do more lookups to disk. With the streaming binary reader this should not be a problem, but with the mmap binary reader this may lead to more frequent mmap page faults.
There is the detail that we also do a lookup in the index header on a cache miss …
=> Store-gateway: shortcut some cache and bucket ops when matching 0 series

CHANGELOG.md, operations/mimir/read-write-deployment/read.libsonnet
Fix mimir-read CLI flags precedence to have query-frontend overriding any flag conflicting with querier.
N/A
=> Fix mimir-read CLI flags precedence

CHANGELOG.md, operations/mimir-tests/test-deployment-mode-migration-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml, operations/mimir/read-write-deployment/config.libsonnet
In this PR I'm changing the default mimir_backend_data_disk_size from 100Gi to 250Gi, to match the default compactor disk size.
N/A
=> Changed default mimir_backend_data_disk_size from 100Gi to 250Gi

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
* Update publishing workflows to use PATs with fine-grained access control
* Fix typo
Co-authored-by: Ursula Kallio <ursula.kallio@grafana.com>
Co-authored-by: Ursula Kallio <ursula.kallio@grafana.com>
(cherry picked from commit b93ecbee90108a16ef4a18466c091738ff3e857a)
=> [release-2.2] Update publishing workflows to use PATs with fine-grained access control

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
* Update publishing workflows to use PATs with fine-grained access control
* Fix typo
Co-authored-by: Ursula Kallio <ursula.kallio@grafana.com>
Co-authored-by: Ursula Kallio <ursula.kallio@grafana.com>
(cherry picked from commit b93ecbee90108a16ef4a18466c091738ff3e857a)
=> [release-2.4] Update publishing workflows to use PATs with fine-grained access control

pkg/storage/bucket/azure/bucket_client.go, pkg/storage/bucket/azure/bucket_client_test.go, pkg/storage/bucket/client.go
In pkg/storage/bucket/azure, change NewBucketClient to not take a factory parameter, but leave this to a private implementation instead. Follows @pracucci's post-merge [advice](https://github.com/grafana/mimir/pull/3821#discussion_r1060010082) in #3821.
=> bucket/azure: Refactor NewBucketClient to not take a factory parameter

go.mod, go.sum, vendor/github.com/prometheus/prometheus/tsdb/querier.go, vendor/modules.txt
This PR updates `r220` to use https://github.com/grafana/mimir-prometheus/tree/mimir-r219, which contains bugfix for https://github.com/prometheus/prometheus/issues/11585.
=> Update r220 with mimir prometheus bugfix

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, cmd/mimir/help.txt.tmpl, docs/sources/mimir/operators-guide/configure/about-versioning.md, docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md, pkg/util/validation/limits.go
This marks the flag `query-frontend.max-total-query-length` as stable. This change is part of the transition away from the use of the ambiguous `store.max-query-length` flag to the dedicated flags `query-frontend.max-total-query-length` for the query-frontend and `querier.max-partial-query-length` for the querier, respectively.
n/a
=> mark `query-frontend.max-total-query-length` as stable

CHANGELOG.md, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
This PR fixes panic in distributor which happens when user writes invalid `metric_relabel_configs` into overrides like this:
```
overrides:
anonymous:
metric_relabel_configs:
-
```
This was accepted as valid runtime config file, but metric relabel configs translated to `[]*relabel.Config{nil}`. When distributor uses this, it panics (line numbers match main at ef085cdae5ae16413d6f3bd8af51811a7152b3c7):
```
2023/01/06 09:42:40 http: panic serving 172.18.0.5:42300: runtime error: invalid memory address or nil pointer dereference
goroutine 15715 [running]:
net/http.(*conn).serve.func1()
/opt/homebrew/Cellar/go/1.19.2/libexec/src/net/http/server.go:1850 +0x120
panic({0x1fbfd80, 0x37a5770})
/opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:890 +0x264 …
```
=> Check that metric_relabel_configs has non-nil configuration in runtime config

CHANGELOG.md, operations/mimir-tests/test-deployment-mode-migration-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml, operations/mimir/read-write-deployment/backend.libsonnet, operations/mimir/read-write-deployment/read.libsonnet
In https://github.com/grafana/mimir/pull/3864 I've changed mimir-read service to headless. This fixed rule evaluations balancing (gRPC) but I just realised HTTP balancing is imperfect, because it actually expects a non headless service. So, we need two services, and use the headless one for remote rule evaluation.
N/A
=> Fix mimir-read ingress service

CHANGELOG.md, cmd/metaconvert/Dockerfile, cmd/mimir-continuous-test/Dockerfile, cmd/mimir/Dockerfile, cmd/mimirtool/Dockerfile, cmd/query-tee/Dockerfile, development/mimir-microservices-mode/dev.dockerfile, development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile, development/mimir-monolithic-mode/dev.dockerfile, development/mimir-read-write-mode/dev.dockerfile, packaging/fpm/Dockerfile
Updates base images to [alpine 3.17.1](https://alpinelinux.org/posts/Alpine-3.17.1-released.html) which was recently released.
Fixes N/A
=> Update base images to alpine:3.17.1

docs/docs.mk
Use absolute path to ensure the same source mount path regardless of the directory in which `make docs` is run.
Fixes https://github.com/grafana/mimir/issues/3904
=> Fix make docs run from another directory

operations/mimir/read-write-deployment/backend.libsonnet, operations/mimir/read-write-deployment/write.libsonnet
This adds top-level container objects for mimir-write and mimir-backend components much like ingesters and store-gateways have top-level objects even though they are optionally run in multi-zone mode. This allows settings that apply to all zones to be easily applied.
N/A
=> Add top-level jsonnet containers for mimir-write and mimir-backend

CHANGELOG.md, docs/sources/mimir/operators-guide/architecture/components/alertmanager.md, pkg/alertmanager/alertmanager.go, pkg/alertmanager/alertmanager_template.go, pkg/alertmanager/alertmanager_template_test.go, pkg/alertmanager/alertmanager_test.go, pkg/alertmanager/api.go, pkg/alertmanager/api_test.go
As discussed in https://github.com/grafana/mimir/issues/2997#issuecomment-1369857932
Not sure about the naming :shrug:
Moved the custom template functions to a separate file for more clarity, tests are passing and generated URL seems to be working.
=> feat alertmanager: add new template function grafanaExploreURL

.gitignore, integration/compactor_test.go, pkg/compactor/compactor_test.go, pkg/compactor/split_merge_compactor_test.go, pkg/storage/tsdb/block/block.go, pkg/storage/tsdb/testutil/block_generator.go
Adds a unit test for the split and merge compactor operating on blocks containing native histograms.
Fixes https://github.com/grafana/mimir/issues/3714
=> Add integration test for compaction on native histograms

docs/sources/mimir/operators-guide/configure/about-configurations.md
Document that running `mimir -modules=true -config.file <file>` can be used to validate a configuration.
Fixes #2588
=> Document -modules=true as config validation cmd

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/capped-small.yaml
Each individual ingester should use the same size disk, regardless of which values file is being used.
N/A
=> Ensure that ingesters use properly sized disks for capped-small.yaml

CHANGELOG.md, docs/sources/mimir/operators-guide/reference-http-api/index.md, pkg/api/api.go, pkg/ingester/ingester.go, pkg/ingester/ingester_activity.go, pkg/util/metrics_helper.go, pkg/util/metrics_helper_test.go
This PR adds `/ingester/tsdb_metrics` endpoint to ingester for returning tenant-specific TSDB metrics. This is not intended for generic metrics scraping, but can be used as a troubleshooting tool.
=> ingester: Add `/ingester/tsdb_metrics` endpoint for returning tenant-specific TSDB metrics.

pkg/querier/batch/batch.go, pkg/querier/batch/chunk.go, pkg/querier/batch/chunk_test.go, pkg/querier/batch/merge.go, pkg/querier/batch/stream.go, pkg/querier/batch/stream_test.go, pkg/querier/querier_test.go, pkg/storage/chunk/chunk.go, pkg/storage/chunk/chunk_test.go, pkg/storage/chunk/prometheus_chunk.go
Add regression test for chunk stream merging to check that the order of merged chunks does not matter.
Rewrite the chunk.Batch data structure to remove extra allocations and slowdown.
Relates to #3478
=> Reproduce and fix chunks stream merge error

docs/sources/mimir/migration-guide/migrating-from-single-zone-with-helm.md, docs/sources/mimir/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/_index.md, docs/sources/mimir/operators-guide/deploy-grafana-mimir/migrate-to-unified-proxy-deployment/_index.md, docs/sources/mimir/operators-guide/deploy-grafana-mimir/upgrade-helm-chart-2.1-to-3.0/_index.md, docs/sources/mimir/operators-guide/run-production-environment-with-helm/_index.md, docs/sources/mimir/operators-guide/run-production-environment-with-helm/configuration-with-helm.md
Add redirect notice for documents moved from mimir to helm-chart docs.
We have considered using aliases, but they don't work due to going over version boundaries.
Fixes #3924 
=> Add redirect notice for documents moved from mimir to helm-chart docs

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/reference-configuration-parameters/index.md, integration/backward_compatibility.go, integration/e2emimir/services.go, pkg/distributor/distributor_test.go, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/mimirpb/compat.go, pkg/ruler/compat.go, pkg/util/validation/limits.go
Do not reject non histogram samples, rather just silently ignore histograms and increase the failed histograms counter. Remove previous global configuration.
Add unit tests to ingester_test to test silent ignore and also query of histograms.
Fix a bug in ruler/compat.go - slide index panic.
Fixes #3958
=> Add per tenant limit whether to accept native histograms or not

.github/workflows/helm-ci.yml, .github/workflows/test-build-deploy.yml, Makefile, mimir-build-image/Dockerfile
The current skopeo version in the build image is 1.2.2, this PR updates
it to 1.10.0.
The problem with 1.2.0 is pushing images to docker hub is failing
([example failing action](https://github.com/grafana/mimir/actions/runs/3925907397/jobs/6722744206))
```
time="2023-01-16T14:43:18Z" level=fatal msg="Error creating an updated image manifest: Error preparing updated manifest, layer \"sha256:3ada1def0d50fd1ba32033c6b57ec2f292576d71ecc8be33f4207967a0508184\": unsupported MIME type for compression: application/vnd.in-toto+json"
```
This problem is gone after upgrading skopeo to 1.10.0.
A caveat is that the latest release for debian is 1.2.2. So in this PR
we are also building skopeo from source.
=> Update skopeo version in build image

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/metrics.go, pkg/ingester/user_tsdb.go
This PR modifies ingester to allow querying of ephemeral storage. This is done by special label `__storage__` that ingester recognizes. It allows two values: `ephemeral` or `persistent`. If label is not in the matchers, ingester uses it as `persistent`. Any other values are rejected with error.
This PR also introduces new metrics:
* `cortex_ingester_queries_ephemeral_total` (based on existing `cortex_ingester_queries_total`)
* `cortex_ingester_queried_ephemeral_samples` (based on existing `cortex_ingester_queried_samples`)
* `cortex_ingester_queried_ephemeral_series` (based on existing `cortex_ingester_queried_series`)
This is part of https://github.com/grafana/mimir/issues/3884. Changelog entry will be added after feature is complete.
- [na] `CHANGELOG.md` updated - the order of entries …
=> Make ephemeral storage queryable

.github/workflows/helm-ci.yml, .github/workflows/test-build-deploy.yml, Makefile, mimir-build-image/Dockerfile
Follow-up of #3967
Building from source means that we don't get the /etc/containers
files that are usually installed when installing via a package manager.
`make install` has further dependencies. Instead, we can just use a
prebuilt image and copy what we need from it.
=> Build image: get skopeo from image instead of building from source

.github/workflows/helm-ci.yml, .github/workflows/test-build-deploy.yml, Makefile, mimir-build-image/Dockerfile
This PR updates skopeo to version 1.10.0 by building it from source and doing full make install.
Continuation of:
- https://github.com/grafana/mimir/pull/3967 (had missing config files)
- https://github.com/grafana/mimir/pull/3973 (missing libs)
Fixes pushing images from release branch. Image tested in this run: https://github.com/grafana/mimir/actions/runs/3940063316/jobs/6740797955 (r221-test branch)
=> Install skopeo 1.10.0 into build image

operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json, operations/mimir-mixin-compiled/dashboards/mimir-queries.json, operations/mimir-mixin/dashboards/queries.libsonnet, pkg/storegateway/bucket.go, pkg/storegateway/bucket_e2e_test.go, pkg/storegateway/bucket_index_reader.go, pkg/storegateway/bucket_store_metrics.go, pkg/storegateway/bucket_test.go, pkg/storegateway/series_chunks.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go, pkg/storegateway/stats.go, pkg/util/metrics_helper.go
While investigating https://github.com/grafana/mimir/issues/3940, I've realised there's room to improve metrics tracked by streaming store-gateway to better understand where `Series()` is actually spent. In this PR I'm proposing some changes to metrics. Since the streaming store-gateway is experimental, these are not breaking changes.
1. Introduce **`cortex_bucket_store_series_request_stage_duration_seconds`** to track how the time is spent in `Series()` when streaming store-gateway is enabled. Rationale:
- This metric should be graphed as a stack, so the some of all stages should be the total (significant) time spent by `Series()`. It has 3 stages: `expand_postings`, `fetch_series_and_chunks` and `send`.
- Do not track `cortex_bucket_store_series_get_all_duration_seconds` and …
=> Improve streaming store-gateway metrics

CHANGELOG.md, tools/tsdb-chunks/main.go
This PR adapts the tools/tsdb-chunks script to handle native histograms.
Fixes https://github.com/grafana/mimir/issues/3944
=> Adapt tools/tsdb-chunks to handle native histograms

CHANGELOG.md, tools/tsdb-index-health/main.go
This PR adapts the tsdb-index-health tool for blocks containing native histograms.
Fixes https://github.com/grafana/mimir/issues/3947
=> Adapt tsdb-index-health for native histograms

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet
We're experimenting with multiple querier scaled objects, querier-burst and querier-burst-backup. This adapts the mixin to support them on the dashboards.
This is how it looks with `hpa_name: 'keda-hpa-querier(-burst(-backup)?)?'`:
=> Mixin: support multiple querier scaled objects

pkg/ingester/ingester_test.go
Attempts to fix https://github.com/grafana/mimir/issues/3977
After diving into the code I realized that newBlock[0] is shipped but kept until retention expires so the oldest unshipped block is always newBlock[1]. 
My confusion came from thinking "what is the oldest block" and that was newBlock[0] but I had to question "what is the oldest unshipped block". After all I'm only human.
I ran this test locally hundreds of times and I think it was flakky because of the float64 notation in the prometheus metrics test. In cases like this it would always pass:
```
1674041474621 // newblock[0]
1674041474722 // newblock[1]
1674041474826 // newblock[2]
1.674041474e+09 // oldest unshipped block timestamp in float64 notation
```  
But in cases like this it would fail, thus the flakyness
``` …
```
=> Fix flaky test TestIngesterNotDeleteShippedBlocksUntilRetentionExpires

pkg/frontend/querymiddleware/limits.go, pkg/frontend/querymiddleware/limits_test.go, pkg/frontend/querymiddleware/querysharding.go, pkg/frontend/querymiddleware/querysharding_test.go, pkg/util/validation/limits.go, pkg/util/validation/limits_test.go
Disables query sharding when tenant accepts native histograms.
It's not foolproof as disabling native histograms accept can introduce problems, but that's what #3971  is about.
Fixes #3981 
=> Disable query sharding when tenant accepts native histograms

CHANGELOG.md, docs/sources/mimir/operators-guide/reference-http-api/index.md, pkg/api/api.go, pkg/api/handlers.go, pkg/api/handlers_test.go
Add `/api/v1/status/config` and `/api/v1/status/flags` endpoints for Prometheus compatibility but do not actually return Mimir configuration.
Fixes #3323
=> Implement no-op versions of Prometheus config and flags endpoints

pkg/util/validation/exporter/ring_test.go
This fixes a flaky test for the overrides-exporter ring. The flakiness arose from using the ring client of a service that was being stopped. The proposed fix is to use a ring client that is not in the process of being shut down.
Fixes #3994
=> Fix flaky test for overrides-exporter ring

CHANGELOG.md, docs/sources/mimir/operators-guide/mimir-runbooks/_index.md, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml, operations/mimir-mixin-compiled-baremetal/alerts.yaml, operations/mimir-mixin-compiled/alerts.yaml, operations/mimir-mixin/alerts/autoscaling.libsonnet
When KEDA scales down to 0, the HPA autoscaler becomes not active, and the alert is fired.
This updates the alert to avoid being triggered when scaling metric is 0.
None.
=> Update AutoscalerNotActive for minReplicas=0

pkg/mimir/mimir.go, pkg/mimir/modules.go
This introduces a new module named `ephemeral-checker`. 
It sets Mimir's `EphemeralChecker` property to the `Overrides` property, because we want that by default the overrides are used to configure ephemeral series.
Third parties can override that `EphemeralChecker` property to inject their own checkers. 
This PR implements what's described [in this comment](https://github.com/grafana/mimir/pull/3897#discussion_r1071331991)
=> introduce ephemeral checker service and make distributor service depend on it

CHANGELOG.md
All other commits weren't user-facing or were helm-chart specific.
See #3979
=> Add missing changelog entries for commits since Mimir 2.5

CHANGELOG.md, pkg/mimirtool/client/alerts.go, pkg/mimirtool/client/backfill.go, pkg/mimirtool/client/client.go, pkg/mimirtool/client/client_test.go, pkg/mimirtool/client/rules.go, pkg/mimirtool/commands/backfill.go, pkg/mimirtool/commands/rules.go, pkg/mimirtool/commands/rules_test.go, pkg/mimirtool/rules/compare.go, pkg/mimirtool/rules/compare_test.go
We have a customer reporting that synching 500+ rule groups is slow. They're right, given the synching operations are sequential. Even if each API call takes 500ms, synching 500 rule groups will take few minutes.
In this PR I'm adding `--concurrency` support to `mimirtool rules sync`. The new default concurrency is 8. The max configurable is 32.
I've manually tested it and speeds up the synching significantly.
Fixes #3990
=> Add --concurrency support to 'mimirtool rules sync' command

pkg/storegateway/bucket_index_postings.go, pkg/storegateway/bucket_index_reader.go
This is a proposed implementation of [this comment](https://github.com/grafana/mimir/pull/3848#issuecomment-1371179255) from #3848
=> store-gateway: ExpandedPostings shortcut: avoid LabelValues unless necessary

CHANGELOG.md, pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go
Queriers make multiple requests to store-gateways simultaneously. If one of these requests fails, or if the querier decides to stop processing the request (eg. due to a query limit being reached, or an invalid query), the querier will cancel all in-flight store-gateway requests.
Previously, the store-gateway would return an `Aborted` gRPC error if the request is cancelled by the caller. However, this would then be recorded in logs and metrics with `status="error"`.
`Canceled` is the preferred error for this scenario (the caller cancelling the request). Requests returning `Canceled` are also recorded in our logs and metrics with `status="cancel"`, which more accurately reflects what happened. (I was confused while diagnosing an alert by a high number of requests logged with …
=> Return `Canceled` rather than `Aborted` when a `Series` request to a store-gateway is cancelled by the calling querier.

pkg/util/log/log_test.go
The test didn't pass in my time zone (tm), this should fix it.
```
--- FAIL: ExampleInitLogger (0.00s)
got:
ts=1970-01-01T01:00:00+01:00 caller=log_test.go:31 level=info test=1
ts=1970-01-01T01:00:00+01:00 caller=log_test.go:33 level=info msg="test 3"
want:
ts=1970-01-01T00:00:00Z caller=log_test.go:31 level=info test=1
ts=1970-01-01T00:00:00Z caller=log_test.go:33 level=info msg="test 3"
```
None.
=> Fix ExampleInitLogger to work in UTC

CHANGELOG.md, docs/sources/mimir/operators-guide/configure/about-versioning.md
This PR fixes post-merge comments from #4013.
=> Fix post-merge comments from #4013

pkg/mimir/modules.go
We want third parties to be able to inject their own memberlist kv codecs. 
Right now the codecs get set when the memberlist kv store is initialized, this changes the initialization method so that it only adds the codecs needed by Mimir but it doesn't overwrite codecs that are already configured.
=> make it possible to inject memberlist kv codecs

cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/operators-guide/mimir-runbooks/_index.md, docs/sources/mimir/reference-configuration-parameters/index.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/ingester/instance_limits.go, pkg/ingester/limiter.go, pkg/ingester/metric_counter.go, pkg/ingester/metrics.go, pkg/ingester/user_tsdb.go, pkg/util/globalerror/errors.go, pkg/util/validation/limits.go
This PR
- introduces instance-limit for max number of ephemeral series in ingester (`-ingester.instance-limits.max-ephemeral-series`)
- introduces per-user series limit for ephemeral storage (`-ingester.max-ephemeral-series-per-user`)
- modifies "discard" reasons for discarded samples when ingesting ephemeral series (all reasons have "ephemeral-" prefix)
- introduces new error codes into error catalog:
* `err-mimir-max-ephemeral-series-per-user`
* `err-mimir-ingester-max-ephemeral-series`
* `err-mimir-ephemeral-sample-timestamp-too-old`
* `err-mimir-ephemeral-sample-out-of-order`
* `err-mimir-ephemeral-sample-duplicate-timestamp`
* `err-mimir-ephemeral-storage-not-enabled-for-user`
This PR does not update changelog, nor does it add documentation for newly introduced errors in the error …
=> Limits and errors for ephemeral storage

GOVERNANCE.md, MAINTAINERS.md
My future priorities will be on the alerting aspects of Mimir, so I think it is
right to reduce my maintainership accordingly and allow others to take my place.
Similarly, remove myself as a team member.
=> Reduce maintainership and step down as team member.

CHANGELOG.md, docs/sources/mimir/operators-guide/architecture/components/query-scheduler/index.md, docs/sources/mimir/operators-guide/configure/about-versioning.md, docs/sources/mimir/operators-guide/deploy-grafana-mimir/jsonnet/migrate-query-scheduler-from-dns-to-ring-based-service-discovery.md
In this PR:
- Mark query-scheduler ring-based service discovery as stable
- Document how to migrate from DNS-based to ring-based service discovery
Fixes #3473
=> Mark query-scheduler ring-based service discovery as stable and document migration

CHANGELOG.md, operations/mimir-tests/test-deployment-mode-migration-generated.yaml, operations/mimir-tests/test-helm-parity-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml, operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml, operations/mimir/config.libsonnet, operations/mimir/memberlist.libsonnet, operations/mimir/overrides-exporter.libsonnet, operations/mimir/read-write-deployment/config.libsonnet
This adds jsonnet config for the ring for overrides-exporters and enables it for the read-write deployment mode.
Do changes like this need a changelog entry?
#3806
=> Add switch to allow enabling overrides-exporter ring

tools/release/create-draft-release-notes.sh
=> Use a portable `sed` command for release notes

pkg/storegateway/bucket.go, pkg/storegateway/bucket_test.go, pkg/storegateway/gateway_test.go, pkg/storegateway/limiter.go, pkg/storegateway/series_refs.go, pkg/storegateway/series_refs_test.go
I started working on #3878. Before addressing it, I would like to fix how series limit is applied (currently disabled, but Yuri is working on enabling it). Currently the series limit is applied on each block. If a series is included in two blocks, it gets counted twice, which is not correct. In this PR I propose to apply the limit after the merge.
This change shouldn't practically impact the chunks limit, because chunks are loaded later in the chain of iterators anyway.
Part of #3878
=> Store-gateway: apply limits on merged series

docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
This was a comment on native histograms, but it seems to be inconsistent in other places elsewhere, removing from histograms branch.
Zenador
Co-authored-by: Ursula Kallio <ursula.kallio@grafana.com>
Fixes N/A
=> Consitent Notes format in documentation

.github/workflows/publish-technical-documentation-next.yml
Prevents errors such as those seen in https://github.com/grafana/mimir/actions/runs/3990037092/jobs/6843471055
=> Do not error when there is nothing to commit as part of a publish

docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
This removes the Jsonnet migration steps from the Helm "Migrate from Cortex" article.
This PR also introduces the docs styling changes suggested in https://github.com/grafana/mimir/pull/3929 
Fixes #3926
=> Docs: remove Jsonnet content from Helm's "Migrate from Cortex"

go.mod, go.sum, pkg/storegateway/bucket.go, pkg/storegateway/bucket_index_postings.go, pkg/storegateway/bucket_test.go, pkg/storegateway/indexheader/binary_reader.go, pkg/storegateway/indexheader/header.go, pkg/storegateway/indexheader/header_test.go, pkg/storegateway/indexheader/index/postings.go, pkg/storegateway/indexheader/lazy_binary_reader.go, pkg/storegateway/indexheader/reader_benchmarks_test.go, pkg/storegateway/indexheader/stream_binary_reader.go, vendor/github.com/prometheus/prometheus/model/labels/matcher.go, vendor/modules.txt
When a label has lots of values (for example `__name__` can have tens of thousands of values) and a matcher is looking for a prefix (for example, `__name__=~"keda_.*"`) we were listing all the values and applying the match function to all of them.
However, we know the offset of each 32nd label, so we know more or less where we can start searching for that prefix, and we know that label values are sorted lexicographically, so we know we should stop looking if we stop seeing that prefix.
This implements that optimization, and also adds benchmark cases for it (label `i` has 500k values, each one matching 50 series).
```
name                                                                        old time/op    new time/op    delta
BucketIndexReader_ExpandedPostings/n="X"-16 …
```
=> Optimize prefix matching

pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
Instead of logging status=failed for all failed queries, disambiguate those
queries which failed for being canceled or being too slow. This makes analysis
of log files much easier, particularly when looking at trends in failed queries.
This can be achieved by grepping the `err` field of the log of course, but
I believe these two cases are significant enough to warrant special attention.
For example - when looking for logs of failed queries, we may not be interested
in queries cancelled by the user, or may only be interested in timeouts, etc.
=> Query-frontend: Disambiguate logs for failed queries.

CHANGELOG.md, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json, operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json, operations/mimir-mixin-compiled/dashboards/mimir-reads.json, operations/mimir-mixin-compiled/dashboards/mimir-writes.json, operations/mimir-mixin/config.libsonnet, operations/mimir-mixin/dashboards/dashboard-utils.libsonnet, operations/mimir-mixin/dashboards/reads.libsonnet, operations/mimir-mixin/dashboards/writes.libsonnet
In mixin, add gateway auto-scaling panels to Reads and Writes dashboards.
I tested locally, with `make mixin-serve`, and the panels look fine.
=> Mixin: Add gateway auto-scaling panels to reads and writes dashboards

pkg/storegateway/bucket_test.go, pkg/storegateway/series_refs_test.go
This PR extends the existing test and benchmark for `ExpandedPostings()` to use the new streaming (mmap-less) index header reader.
I haven't modified the other tests that currently only use the mmap-based index header reader - that could be a follow up PR.
Resolves #4068.
=> Run `ExpandedPostings` test and benchmark with both streaming and mmap-based index header reader.

CHANGELOG.md, pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
This PR fixes omission when slice of ephemeral series was not returned to the pool.
=> Return slice with ephemeral series back to pool.

CHANGELOG.md, docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
This PR replace short flag names with long flag names in the runbook for better clarity.
Fixes #4050
=> Replace short flag names with long flag names in the runbook for better clarity

CHANGELOG.md, pkg/util/ephemeral/label_matchers.go, pkg/util/ephemeral/label_matchers_test.go, pkg/util/ephemeral/source.go, pkg/util/validation/limits_test.go
This PR fixes marshalling of `ephemeral_series_matchers` field in Limits. This fixes its output in `/runtime_config` endpoint.
=> Fix marshalling of `ephemeral_series_matchers`

CHANGELOG.md, pkg/frontend/transport/handler.go, pkg/frontend/transport/handler_test.go
This PR adds the value of the `User-Agent` HTTP header to query stats logs. This is useful for diagnosing the source of query traffic (eg. a sudden increase in traffic or the source of a very expensive query).
This is only valuable if the caller sets a meaningful user agent, but it's better than nothing. For example, Grafana does send something meaningful (eg. `Grafana/9.3.6`), but other consumers don't (eg. `promtool` sends the default Golang user agent).
Fixes #3970.
=> Include user agent in query stats logs

docs/sources/mimir/operators-guide/architecture/key-value-store.md
This PR clarifies the docs for memberlist, making it clear that memberlist is not supported for HA dedupe.
See https://grafana.slack.com/archives/C039863E8P7/p1674794022250729 for community question about this.
(none)
=> Clarify that memberlist cannot be used for HA dedupe.

CHANGELOG.md
The changelog entries for #4052, #4072 and #4091 were in the "mixin" section of the changelog when they should be in the main "Mimir" section. This PR moves them to the correct place.
#4052, #4072 and #4091
=> Move changelog entries for #4052, #4072 and #4091 to the correct section

docs/sources/mimir/operators-guide/architecture/components/ingester.md
I naively was under the impression that replication functions like other systems where replication can happen when an ingester rejoins a memberlist which is incorrect. I figure it might be worth clarifying in the docs.
N/A
=> [Docs] Clarify how ingester replication happens

go.mod, go.sum, vendor/github.com/thanos-io/objstore/CHANGELOG.md, vendor/github.com/thanos-io/objstore/inmem.go, vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go, vendor/github.com/thanos-io/objstore/providers/s3/s3.go, vendor/modules.txt
Upgrades `thanos-io/objstore` to the latest version. 
Only potentially user-impacting change is https://github.com/thanos-io/objstore/pull/41, but this seems safe and isn't user-visible (we'd need to make changes in `pkg/storage/bucket/s3` to expose it).
https://github.com/grafana/mimir/pull/4061#issuecomment-1403381053
=> Upgrade thanos-io/objstore so file store respects cancellation

CHANGELOG.md, cmd/mimir/config-descriptor.json, cmd/mimir/help-all.txt.tmpl, docs/sources/mimir/reference-configuration-parameters/index.md, pkg/storage/tsdb/caching_config.go, pkg/storage/tsdb/config.go
There's no benefit to changing the default and it's possible to introduce subtle performance problems by not using the default.
See https://github.com/grafana/mimir/pull/4074#discussion_r1089131960
=> Deprecate `blocks-storage.bucket-store.chunks-cache.subrange-size` flag

CHANGELOG.md, operations/mimir/autoscaling.libsonnet
This is the first step towards open-sourcing the jsonnet we use to run multiple querier deployments taking advantage of the spot nodes on different cloud providers.
=> jsonnet: Add weight param to querier newScaledObject

CHANGELOG.md, pkg/alertmanager/alertmanager_metrics.go, pkg/alertmanager/alertmanager_metrics_test.go
There are two metrics in the Dispatcher component of the upstream Alertmanager
we don't currently expose:
- `alertmanager_dispatcher_aggregation_groups`
- `alertmanager_dispatcher_alert_processing_duration_seconds`
I can't see any reasoning behind ommitting these, so I am assuming it was
perhaps just an oversight, and adding them in this commit. I've chosen not
to expose metrics per-user - we can consider this if a need arises.
The change also re-orders the code so all the Dispatcher metrics are grouped
together, and extends the unit test to get coverage on the existing metric
(`cortex_alertmanager_dispatcher_aggregation_group_limit_reached_total`).
=> Alertmanager: Expose missing upstream metrics from the dispatcher.

operations/helm/charts/mimir-distributed/CHANGELOG.md, operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/policies/policies.rego, operations/helm/policies/policies_test.rego, operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/large-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/small-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml, operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/podsecuritypolicy.yaml
This PR fixes using the chart with kustomization terraform provider:
```
Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceDiff: "policy/PodSecurityPolicy/perfana/mimir-distributed": is not namespace scoped but has metadata.namespace set
```
K8S itself just gives a warning on this, but some utilities reject it like above. There is no explicit rule against it in the K8S documentation.
N/A
=> Remove namespace from PodSecurityPolicy helm template

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release-helm-charts.yml, .github/workflows/publish-technical-documentation-release-mimir.yml
=> Update publishing workflows to use organization secret

pkg/frontend/transport/handler.go
Upgrade query-frontend log messages when waiting on in-flight requests to info level. Requested by @pracucci.
=> Query-frontend: Log with info level when waiting on in-flight requests

CHANGELOG.md
In CHANGELOG, annotate enhancement "Query-frontend: Wait for in-flight queries to finish before shutting down" with the second related PR (forgot this earlier).
=> CHANGELOG: Annotate enhancement with second PR

pkg/frontend/querymiddleware/cardinality.go, pkg/frontend/querymiddleware/cardinality_test.go
In the current version of cardinality estimation, estimates are bucketed into fixed-width time intervals. An estimate is reused if a subsequent query falls into the same bucket. This means that all estimates expire at the bucket boundary.
This PR uses consistent hashing based on the query string for the cardinality estimation cache key. With this in place, cache estimates expire at different points in time depending on the query string of the specific query.
Relates to #4108
=> Query-frontend: Use consistent hashing in cardinality estimation
