grafana/mimir

docs/sources/release-notes/v2.0.md

The link does not change, but the title of the Q&A has changed. Updating to reflect the new title.

Update Q&A title

---

README.md

Add link to community call doc.

Add link to community call doc.

---

docs/sources/operators-guide/architecture/components/_index.md

Use sentence case.

---

docs/sources/operators-guide/getting-started/_index.md

Edit the _Getting started with Grafana Mimir_ guide.

Rephrase "we" and "our"; structure options clearly.

---

.gitignore

Followup of https://github.com/grafana/mimir/pull/1601

Add metrics-activity.log to .gitignore

---

docs/sources/migration-guide/migrating-from-cortex.md

the correct name is mimir-distributed
fix documentation helm chart name
n/a

update helm chart name

---

CHANGELOG.md
operations/mimir/alertmanager.libsonnet
operations/mimir/compactor.libsonnet
operations/mimir/config.libsonnet
operations/mimir/distributor.libsonnet
operations/mimir/flusher-job-blocks.libsonnet
operations/mimir/ingester.libsonnet
operations/mimir/memcached.libsonnet
operations/mimir/mimir-manifests.jsonnet.example
operations/mimir/multi-zone.libsonnet
operations/mimir/querier.libsonnet
operations/mimir/query-frontend.libsonnet
operations/mimir/query-scheduler.libsonnet
operations/mimir/query-tee.libsonnet
operations/mimir/ruler.libsonnet
operations/mimir/store-gateway.libsonnet

Signed-off-by: Andrew Waters <andrew-waters@users.noreply.github.com>
Adds the ability to move microservices to a dedicated node selector
No issue, found and fixed

Add Node Selector via config

---

operations/mimir/README.md

Just tried this myself, the fields need to be hidden.
None

Fix jsonnet readme memcached scaling

---

CHANGELOG.md

I would like to clarify the CHANGELOG entry about #1596.
N/A

Clarify CHANGELOG entry about PR 1596

---

.gitignore

Adding the following files to .gitignore so that they don't pop up again.
* `.DS_Store` - macOS indexing
* `.vscode`- Visual Studio editor files
*  `coverage.txt` - Go coverage output

Add `.DS_Store`, `coverage.txt` and `.vscode/`  to `.gitignore`

---

pkg/continuoustest/client.go
pkg/continuoustest/client_test.go
pkg/continuoustest/util_test.go
pkg/continuoustest/write_read_series.go
pkg/continuoustest/write_read_series_test.go

In this PR I'm running instant queries too in the `mimir-continuous-test` tool.
N/A

Added instant queries support to mimir-continuous-test tool

---

README.md

The logo takes up too much of @bboreham's screen. How about 400px?

Limit width of Grafana Mimir logo

---

pkg/mimirtool/client/alerts.go
pkg/mimirtool/client/client.go
pkg/mimirtool/client/rules.go
pkg/mimirtool/client/rules_test.go
pkg/mimirtool/commands/alerts.go
pkg/mimirtool/commands/analyse_ruler.go
pkg/mimirtool/commands/rules.go

Rename `pkg/mimirtool/client.CortexClient` to `MimirClient`.

mimirtool: Rename CortexClient to MimirClient

---

development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
development/tsdb-blocks-storage-s3/dev.dockerfile

Fix typo in development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile. Also upgrade Alpine Linux in that and development/tsdb-blocks-storage-s3/dev.dockerfile.

tsdb-blocks-storage-s3-single-binary: Fix Dockerfile

---

operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml

Regenerate generated test YAML

---

docs/sources/migration-guide/migrating-from-cortex.md

Fix link to cortex-jsonnet monitoring mixin download

---

pkg/querier/blocks_store_queryable.go

Remove useless resultMtx mutex.
Fixes https://github.com/grafana/mimir/issues/1716
None

Remove useless resultMtx mutex

---

operations/k6/README.md
operations/k6/load-testing-with-k6.js

* Allow user to define which scheme to use when launching a load testing with k6
* Add default values to README

Improve load testing

---

operations/mimir-mixin/config.libsonnet

The path this comment refers to no longer exists. This change updates the comment to have the updated path.
n/a - this is a really small documentation fix and not worth filing an issue

Update docs on mimir-mixin job_names

---

CHANGELOG.md

Add changelog entry for #1728

---

docs/sources/operators-guide/visualizing-metrics/installing-dashboards-and-alerts.md

Add documentation about how to build mixin inside a container.

Docs: add alternative build method for mixins

---

pkg/distributor/ha_tracker.go

Make haTracker to use same receivers.
It turns out we have c and h, so maybe it's better to use h for both :(
I don't know if this is intentional, but if it is, please feel free to turn off my PR.
None

Make haTracker to use same receivers

---

pkg/distributor/distributor.go
pkg/distributor/forwarding/forwarding.go
pkg/distributor/forwarding/forwarding_test.go

- Remove useless rename 
- Remove useless parentheses
None

Remove useless renames and parentheses

---

pkg/mimir/modules.go

Removed double space in Log

---

CHANGELOG.md

As part of release shepherd duties for v2.1.0 updating changelog for correct placement of new features on main

Add 2.1.0-rc.0 header

---

RELEASE.md

List Johanna as 2.1.0 release shepherd

---

docs/sources/operators-guide/reference-http-api/index.md

An user got confused about the usage of `Set rule group` API (see https://github.com/grafana/mimir/discussions/1863). In this PR I'm proposing to improve its doc, based on the lessons learned while doing support.
N/A

Docs: clarify 'Set rule group' API specification

---

docs/sources/operators-guide/deploying-grafana-mimir/_index.md

Also serves as a test for publishing documentation on pushes to main.

Fix capitalization of Jsonnet and Tanka

---

.github/workflows/publish-technical-documentation-next.yml

TIL that if you edit the workflow in the GitHub UI, it will lint your workflow file and make sure that all the keys conform to the schema.

Fix manual workflow dispatch

---

go.mod
go.sum
vendor/github.com/grafana/e2e/service.go
vendor/modules.txt

See https://github.com/grafana/e2e/pull/3 for the description.
N/A

Fix flaky integration tests caused by 'metric not found'

---

CHANGELOG.md
docs/sources/operators-guide/running-production-environment/production-tips/index.md
operations/mimir-tests/test-defaults-generated.yaml
operations/mimir-tests/test-disable-chunk-streaming-generated.yaml
operations/mimir-tests/test-gossip-generated.yaml
operations/mimir-tests/test-gossip-multi-zone-generated.yaml
operations/mimir-tests/test-gossip-multikv-generated.yaml
operations/mimir-tests/test-gossip-multikv-switch-primary-secondary-generated.yaml
operations/mimir-tests/test-gossip-multikv-teardown-generated.yaml
operations/mimir-tests/test-gossip-ruler-disabled-generated.yaml
operations/mimir-tests/test-multi-zone-generated.yaml
operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
operations/mimir-tests/test-query-sharding-generated.yaml
operations/mimir-tests/test-shuffle-sharding-generated.yaml
operations/mimir-tests/test-storage-azure-generated.yaml
operations/mimir-tests/test-storage-gcs-generated.yaml
operations/mimir-tests/test-storage-s3-generated.yaml
operations/mimir/config.libsonnet
operations/mimir/store-gateway.libsonnet

Remove jsonnet configuration settings that match default values

---

docs/sources/operators-guide/reference-http-api/index.md

This PR fixes API reference page to show that `/ingester/ring` is also available on distributor component.
Related to https://github.com/grafana/mimir/issues/1917.

Ingester ring endpoint fix

---

operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json
operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json
operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
operations/mimir-mixin-compiled/dashboards/mimir-config.json
operations/mimir-mixin-compiled/dashboards/mimir-object-store.json
operations/mimir-mixin-compiled/dashboards/mimir-overrides.json
operations/mimir-mixin-compiled/dashboards/mimir-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json
operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json
operations/mimir-mixin-compiled/dashboards/mimir-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
operations/mimir-mixin-compiled/dashboards/mimir-scaling.json
operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json
operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json
operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json
operations/mimir-mixin-compiled/dashboards/mimir-writes.json
operations/mimir-mixin/dashboards/dashboard-utils.libsonnet

Updated to allow publishing the dashboards to the community
Signed-off-by: Patrick Oyarzun <patrick.oyarzun@grafana.com>

Add minimum Grafana version to mixin dashboards

---

docs/configurations/grafanacon-2022/mimir-values.yaml

This PR removes image override from demo file. It was only used to force arm64 image, but with 2.1.0 this is no longer necessary.

Remove image spec from demo file.

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/operators-guide/configuring/about-versioning.md
docs/sources/operators-guide/configuring/reference-configuration-parameters/index.md
pkg/storage/bucket/client.go

Follow up of #1686 to mark the feature as experimental.
n/a

Add bucket prefix to experimental features

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/grafana-tools/sdk/board.go
vendor/github.com/grafana-tools/sdk/datasource.go
vendor/github.com/grafana-tools/sdk/folder-permissions.go
vendor/github.com/grafana-tools/sdk/panel.go
vendor/github.com/grafana-tools/sdk/rest-dashboard.go
vendor/github.com/grafana-tools/sdk/rest-folder-permissions.go
vendor/github.com/grafana-tools/sdk/rest-team.go
vendor/github.com/grafana-tools/sdk/team.go
vendor/modules.txt

See https://github.com/grafana/cortex-tools/pull/248 for more context (this is the same change). 
The `grafana-tools/sdk` dependency will eventually be removed entirely from `analyze` commands.
Signed-off-by: hjet <hjet@users.noreply.github.com>

Use github.com/colega/grafana-tools-sdk fork

---

.github/workflows/publish-technical-documentation-release.yml

Cherry-pick of 7384937bd1f1a5df5e14782f370e97b975bfb0d3

Adjust the name of the tag expected by documentation publishing (#1974)

---

go.mod
go.sum
vendor/github.com/thanos-io/thanos/pkg/block/block.go
vendor/modules.txt

This PR updates Thanos, with single change: https://github.com/thanos-io/thanos/pull/5400

Update Thanos to latest main

---

CHANGELOG.md
operations/mimir/autoscaling.libsonnet

In this PR I'm adding a check to Mimir jsonnet to ensure query-scheduler is enabled when enabling querier autoscaling. This PR is a follow up of #2013.
N/A

Add a check to Mimir jsonnet to ensure query-scheduler is enabled when enabling querier autoscaling

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md

This should be automated, but now done manually.
N/A

Helm: release our first weekly

---

operations/mimir/compactor.libsonnet

Remove obsolete comment from jsonnet.
N/A

Chore: remove obsolete comment from jsonnet

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go
vendor/github.com/prometheus/prometheus/tsdb/chunks/queue.go
vendor/modules.txt

This PR is simply updating mimir/out-of-order with the latest changes of mimir-prometheus/out-of-order

Bump mimir prometheus in out-of-order

---

CHANGELOG.md

This PR fixes changelog entry from #2098.

Fix changelog entry from PR #2098.

---

docs/sources/operators-guide/deploying-grafana-mimir/_index.md

Fix outdated reference, thanks @dimitarvdimitrov for noticing.
N/A

Docs: fix reference to the mimir Helm chart

---

CHANGELOG.md
docs/sources/operators-guide/deploying-grafana-mimir/jsonnet/configuring-autoscaling.md
docs/sources/operators-guide/deploying-grafana-mimir/jsonnet/configuring-low-resources.md

In this PR I'm documenting how to configure queriers autoscaling with Jsonnet.
N/A

Documented how to configure queriers autoscaling with Jsonnet

---

pkg/api/memberlist_status.gohtml

Just fixing a tiny typo in the memberlist admin UI.
N/A

Fixed typo in memberlist admin UI

---

docs/configurations/grafanacon-2022/index.md

This PR adds link to the GrafanaCon 2022 talk to the configuration files.

Grafanacon 2022 config files: Include link to the talk itself.

---

docs/sources/operators-guide/configuring/configuring-shuffle-sharding/index.md

Docs: Document alertmanager shuffle sharding

---

go.mod
go.sum
pkg/ingester/ingester.go
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_append.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/modules.txt

This vendor update brings in this fix https://github.com/grafana/mimir-prometheus/pull/275 and this rename of a config https://github.com/grafana/mimir-prometheus/pull/276

Update to latest mimir-prometheus/main

---

pkg/ingester/user_metrics_metadata_test.go

Add unit tests for regression fixed in https://github.com/grafana/mimir/pull/2096
Fixes N/A

Add tests for user metadata in the ingester

---

docs/sources/operators-guide/getting-started-helm-charts/_index.md

Update getting started

---

CHANGELOG.md
docs/sources/operators-guide/architecture/components/ingester.md
docs/sources/operators-guide/configuring/about-versioning.md
docs/sources/operators-guide/configuring/configuring-out-of-order-samples-ingestion.md

Out of order support is coming as an experimental feature. 
This PR is suggesting some new files about it. It is the first time that I add new documentation to Mimir so please let me know about any suggestions or things you would change to make it clear.

Mimir documentation about out-of-order

---

docs/sources/operators-guide/mimir-runbooks/_index.md

Rename a title in the runbook.
As requested in https://github.com/grafana/mimir/pull/2221

Rename codified errors to errors catalog

---

docs/sources/operators-guide/mimir-runbooks/_index.md

This PR cherry-picks PR #2256 into release-2.2 branch to make sure that docs published for 2.2 release will have the correct term.

Rename codified errors to errors catalog (#2256)

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml
operations/helm/charts/mimir-distributed/templates/role.yaml
operations/helm/charts/mimir-distributed/templates/rolebinding.yaml
operations/helm/charts/mimir-distributed/templates/securitycontextconstraints.yaml
operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/charts/minio/templates/configmap.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/charts/minio/templates/deployment.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/charts/minio/templates/configmap.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/charts/minio/templates/deployment.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/charts/minio/templates/configmap.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/charts/minio/templates/deployment.yaml

Add Openshift support to helm chart. In scope for mimir-distributed helm chart 3.0 in https://github.com/grafana/mimir-squad/issues/623
N/A
N/A

helm: added OpenShift support (#2219)

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/ci/test-enterprise-configmap-values.yaml
operations/helm/charts/mimir-distributed/ci/test-oss-values.yaml
operations/helm/charts/mimir-distributed/values.yaml

Flip the default.
Last step in the configuration improvements.
Fixes #2018 
- [N/A] Documentation added - done separately https://github.com/grafana/mimir/issues/2172

Helm: default to ConfigMap in configStorageType value

---

docs/internal/contributing/README.md

Update documentation for contributors regarding the errors catalog.
N/A

Add some guidelines for contributors on how to add to the errors catalog

---

operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl

Use sentence case

---

pkg/alertmanager/multitenant.go

Really a tiny nit I noticed while testing #2317. Fixing the message of an Alertmanager log.
N/A

Fix alertmanager log message

---

pkg/mimir/mimir.go

I was passing by and I think this is cleaner and more readable than a switch.
None, just code cleanup.

Use a map for default flag values for server

---

docs/sources/operators-guide/mimir-runbooks/_index.md

Add some clarification to MimirTenantHasPartialBlocks.
Compaction retry vs block IDs.
Example GCS backend parameters.
Fixes N/A

runbook: more clarification to MimirTenantHasPartialBlocks

---

CHANGELOG.md
docs/sources/operators-guide/configuring/configuring-out-of-order-samples-ingestion.md

Signed-off-by: Ganesh Vernekar <ganeshvern@gmail.com>
(cherry picked from commit 9c101c2b52cf4b70829699b965737d5ad789837f)

Update docs for out-of-order feature (#2331)

---

docs/sources/migration-guide/migrating-from-thanos-or-prometheus.md

This PR cherry picks PR #2122 to release-2.2 branch.

Cherry-pick PR #2122 to release-2.2.

---

CHANGELOG.md
docs/sources/operators-guide/configuring/_index.md
docs/sources/operators-guide/deploying-grafana-mimir/getting-started-helm-charts/_index.md
docs/sources/operators-guide/deploying-grafana-mimir/getting-started-helm-charts/_index.md.bak
docs/sources/operators-guide/monitoring-grafana-mimir/_index.md
docs/sources/operators-guide/monitoring-grafana-mimir/dashboards/_index.md
docs/sources/operators-guide/running-production-environment/_index.md
docs/sources/operators-guide/securing/_index.md
docs/sources/operators-guide/using-exemplars/_index.md
pkg/storegateway/indexheader/fileutil/mmap_386.go
pkg/storegateway/indexheader/fileutil/mmap_amd64.go
pkg/storegateway/indexheader/fileutil/mmap_arm64.go
pkg/storegateway/indexheader/fileutil/mmap_windows.go

Merges changes from release-2.2, with rc.1 version back to main.
This had quite a lot of conflicts on the docs side, but I think I managed to makse some sense of it.
Ref: https://github.com/grafana/mimir/issues/2241
Supersedes: https://github.com/grafana/mimir/pull/2372

Merge release 2.2 to main

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/ci/test-enterprise-configmap-values.yaml
operations/helm/charts/mimir-distributed/ci/test-oss-values.yaml
operations/helm/charts/mimir-distributed/values.yaml

Pick 79e62141adf12d579ee70aef83a83c04397b66e2 from #2277

[Release 2.2] Helm: default to ConfigMap in configStorageType value 

---

RELEASE.md

We randomly picked the sheperd and 2.3.0 and Tyler was selected. This PR "announces" it.
N/A

Announce Tyler as 2.3.0 shepherd

---

docs/sources/tutorials/play-with-grafana-mimir/index.md

Fix UID for dashboard links
None

Fix UID for dashboard links

---

docs/sources/tutorials/play-with-grafana-mimir/index.md

Update mimir's tutorial to use Grafana 9.
- update how to configure your first recording rule and Configure your first alert rule.
- update the docker-compose commands
Fixes https://github.com/grafana/mimir/issues/2403

Update mimir's tutorial to use Grafana 9

---

docs/internal/contributing/how-integration-tests-work.md

Fix broken link of test integration framework. The old one was already 404.
None

Fix broken link of test integration framework

---

operations/mimir/memberlist.libsonnet

I want to experiment with different memberlist settings at Grafana Cloud. To ease the work, I want to make `memberlistConfig` easier to override.
N/A

Chore: make memberlistConfig overrideable in jsonnet

---

docs/sources/release-notes/v2.2.md

Fix link to out of order doc in release note 2.2

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Set Chart.yaml and CHANGELOG.md versions.
Bump image versions.

Create helm chart release candidate rc.1

---

operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml

Update the continuous test image to match mimir's version

Update continuout test image to match mimir

---

docs/sources/operators-guide/deploy-grafana-mimir/upgrade-helm-chart-2.1-to-3.0/_index.md
operations/mimir/README.md

The original PR #2291 was merged after #2343 was merged, but did not include its changes. So the upgrade guide got placed in the wrong directory.

Move helm upgrade guide

---

Makefile
pkg/distributor/ha_tracker.pb.go
pkg/distributor/ha_tracker.proto

- Fix a typo
- Remove useless pb `pkg/ring/kv/memberlist/kv.pb.go`
None

Fix typo and remove useless pb

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml

Helm: release 3.0.0

---

CHANGELOG.md
pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/util/validation/limits.go

- Drop exemplars in distributor for tenants where exemplars are disabled
- Add test for it
- Fix other tests
Fixes https://github.com/grafana/mimir/issues/697

Drop exemplars in distributor for tenants where exemplars are disabled

---

RELEASE.md
integration/backward_compatibility.go

Fix backwards compatibility test.
Highlight that it needs to be extended on release, not replaced.
Fixes N/A

fix compatibility test

---

RELEASE.md

The process is so documented that when something obvious is missing, we just skip it.

Document the binaries in stable release

---

pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/distributor/ha_tracker.go
pkg/distributor/query.go

- Fix some typos
- Refine import order
- Remove duplicate codes
None. Just reading the code.

Fix typos and remove duplicate codes

---

integration/e2emimir/services.go

Replaces the old MIMIR_EXTRA_ARGS which was a simple string that we added to the args provided to the image.
That approach didn't solve all use cases, since it was appending the flags after they've been mapped by the flagmapper, which means that same flags were appended for all image versions, making this incompatible with backwards compatibility tests.
Now we parse the MIMIR_EXTRA_FLAGS as JSON, merge it with all flags we have, and then we apply the flagmapper, if any, properly mapping the flags in case of backwards compatibility tests.
Also renamed _ARGS to _FLAGS since even though both are correct, in our code we call them `flags`.
Fixes an internal issue.

e2e tests: json-encoded MIMIR_EXTRA_FLAGS

---

CHANGELOG.md
docs/sources/operators-guide/reference-http-api/index.md
docs/sources/operators-guide/tools/mimirtool.md

Docs: mention mimirtool commands in HTTP API doc

---

Makefile
docs/docs.mk

[Add help for doc targets](https://github.com/grafana/mimir/commit/27dc3a4d33819d728c6caa15a583f703977c3218)
[Add help for license targets](https://github.com/grafana/mimir/commit/7c6caf521c1c417b3ae1ad2472cb2cc513b06b51)
[Add help for proto targets](https://github.com/grafana/mimir/commit/9bf2481d93924877779a85bd26264a0ec2b96626)
Part of https://github.com/grafana/mimir/issues/2499

Add help for doc, license and proto targets

---

.github/workflows/compare-helm-with-jsonnet.yml

Fix failing helm vs jsonnet compare in community PRs
Remove verbose comments on PRs
N/A

fix running helm vs jsonnet compare on outside PRs

---

RELEASE.md

Update release process document with Helm
N/A, action item from weekly meeting

Helm: update release process to include Helm

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/tests/build.sh
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml

Helm: weekly r196

---

integration/e2emimir/service.go

This helps in testing code paths that reply on a trace being sampled (or not). Similar to the one introduced with https://github.com/weaveworks/common/pull/237 (and which later had to be reverted with https://github.com/weaveworks/common/pull/247)

Add jaeger sampling config to e2e mimir containers

---

Makefile

Add help for lint and tests.
Part of https://github.com/grafana/mimir/issues/2499

Add help for lint and tests

---

docs/sources/migration-guide/migrating-from-thanos-or-prometheus.md
docs/sources/operators-guide/configure/configure-tsdb-block-upload.md
docs/sources/operators-guide/tools/mimirtool.md

This PR adds documentation for `mimirtool backfill` command.

Document mimirtool backfill command.

---

pkg/distributor/distributor_test.go

#2562 introduced a bug. Fixing in this PR.
N/A

Fix PR 2562

---

pkg/frontend/querymiddleware/astmapper/instant_splitting.go
pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go
pkg/frontend/querymiddleware/split_by_instant_interval_test.go

* Ensure subqueries are not split
* Add comment noting that getRangeInterval should return 0 for subqueries

Ensure instant subqueries are not split

---

Makefile

- [Add help for docker image commands](https://github.com/grafana/mimir/commit/283ea3279b6cc640e4ac6edf44e2adc3c0211356)
- [Add help for other commands](https://github.com/grafana/mimir/commit/af9917c904238bdb49e74ed026b969d2d18f23d9)
Fixes https://github.com/grafana/mimir/issues/2499

Add help for other commands

---

pkg/frontend/querymiddleware/astmapper/instant_splitting.go
pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go
pkg/frontend/querymiddleware/split_by_instant_interval_test.go

1) Update `getOffset` to follow the same logic as https://github.com/grafana/mimir/pull/2575 that returns all the offsets found and `assertOffset` that validates that only 1 offset was found
2) Add support for negative offsets: https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier
3) Update mapper and correctness unit tests

Add support for offset operator

---

pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go
pkg/frontend/querymiddleware/split_by_instant_interval_test.go

Add unit tests with @ modifier: https://prometheus.io/docs/prometheus/latest/querying/basics/#modifier

Add units tests with @ modifier

---

integration/backfill_test.go

* Fix backfill integration test comments
* Use `io` instead of the deprecated `ioutil` in backfill integration tests
* Make sure that expectation argument to `require.Equal` comes first

Fix backfill integration test comments

---

operations/helm/charts/mimir-distributed/templates/validate.yaml

Be a bit more verbose when reporting validation failure on memcached addresses
Relates to: #2579 

Improve validation failure message for memcached caches

---

pkg/frontend/querymiddleware/astmapper/instant_splitting.go
pkg/frontend/querymiddleware/astmapper/subtree_folder.go

In this PR I'm addressing feedback received here:
https://github.com/grafana/mimir/pull/2576#discussion_r932395316
N/A

Chore: introduce dedicated utility to walk PromQL AST

---

docs/sources/operators-guide/deploy-grafana-mimir/upgrade-helm-chart-2.1-to-3.0/_index.md

Explain memcached migration impact on `mimir.config` and `mimir.structuredConfig`
Improves: #2579 

Mention memcached impact on mimir config

---

operations/helm/charts/mimir-distributed/values.yaml

Improve the docstring to avoid confusion.
Related to support case number 3290

Helm: be more specific about container image and nginx values

---

pkg/frontend/querymiddleware/split_and_cache_test.go
pkg/frontend/querymiddleware/split_by_instant_interval_test.go

Update range and instant split tests to assert context query stats.
Based on comment: https://github.com/grafana/mimir/pull/2641#pullrequestreview-1061578398
Fixes https://github.com/grafana/mimir/pull/2641#pullrequestreview-1061578398

Update range and instant split tests to assert context query stats

---

pkg/usagestats/seed_test.go

I've seen this [flaky test in CI](https://github.com/grafana/mimir/runs/7723073225?check_suite_focus=true):
```
--- FAIL: TestInitSeedFile (0.00s)
--- FAIL: TestInitSeedFile/should_wait_for_'min_stability'_and_return_the_seed_file_if_it_exists_and_was_created_less_than_'min_stability'_time_ago (0.00s)
seed_test.go:269: 
Error Trace:	/__w/mimir/mimir/pkg/usagestats/seed_test.go:269
Error:      	"699.704µs" is not greater than or equal to "3s"
Test:       	TestInitSeedFile/should_wait_for_'min_stability'_and_return_the_seed_file_if_it_exists_and_was_created_less_than_'min_stability'_time_ago
FAIL
```
I thought I've already fixed in the previous PR, but wasn't actually fixed. We need to create the seed when the actual test case run starts, and not before that.

Fix cluster seed flaky tests

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_append.go
vendor/modules.txt

Upgrades mimir-prometheus to bring in some fixes for OOO.

Upgrade mimir-prometheus

---

.github/workflows/helm-ci.yml
docs/internal/contributing/contributing-to-helm-chart.md

Run conftest test and reorder a little

---

go.mod
go.sum
vendor/github.com/weaveworks/common/server/server.go
vendor/modules.txt

Update weaveworks/common library to v0.0.0-20220810113439-c65105d60b18 to include fix https://github.com/weaveworks/common/pull/250
Required by: https://github.com/grafana/mimir/pull/2683

Update weaveworks/common library to v0.0.0-20220810113439-c65105d60b18

---

MAINTAINERS.md

Over the past we days we've run a vote to add Dimitar as Mimir maintainer. The vote reached super majority (9 yes, 8 was required), so in this PR I'm adding Dimitar to the list of maintainers.

Add Dimitar as Mimir maintainer

---

.github/workflows/compare-helm-with-jsonnet.yml

This will guard against malicious updates from being used without our knowledge

Pin external github actions to known commits

---

CHANGELOG.md

This PR signals the start of the Mimir 2.3 release process! 
- [-] Tests updated
- [-] Documentation added

Update the changelog to signal the start of the 2.3 release

---

CHANGELOG.md
pkg/util/validation/validate.go

Registers `cortex_discarded_requests_total` as it wasn't previously registered.

Register `cortex_discarded_requests_total`

---

RELEASE.md

Add missing info about Helm release in RELEASE.md
N/A

Helm additions to RELEASE.md

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

We're adding commits on main, let's not mix up 3.1 future released and non
released stuff
N/A

Helm: bump version in CHANGELOG to signal start of release

---

CHANGELOG.md
operations/mimir-tests/test-extra-runtime-config-generated.yaml
operations/mimir-tests/test-extra-runtime-config.jsonnet
operations/mimir/alertmanager.libsonnet
operations/mimir/common.libsonnet
operations/mimir/compactor.libsonnet
operations/mimir/config.libsonnet
operations/mimir/distributor.libsonnet
operations/mimir/flusher-job-blocks.libsonnet
operations/mimir/ingester.libsonnet
operations/mimir/overrides-exporter.libsonnet
operations/mimir/querier.libsonnet
operations/mimir/query-frontend.libsonnet
operations/mimir/query-scheduler.libsonnet
operations/mimir/ruler.libsonnet
operations/mimir/store-gateway.libsonnet

This PR adds `$._config.configmaps` and `$._config.runtime_config_files`, used by all Mimir components. This makes it easy to add new config maps or runtime config files to all Mimir components.

jsonnet: Added $._config.configmaps and $._config.runtime_config_files.

---

operations/compare-helm-with-jsonnet/components/config/kustomization.yaml

Helm v jsonnet: ignore tokens_file_path in query-scheduler

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl

mulf is not one of the documented functions of Helm charts. See
https://helm.sh/docs/chart_template_guide/function_list/#math-functions
Fixes #2661 

Helm: do not use mulf

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/values.yaml

Corrects the changelog entry for query sharding. Also updates the docs on the `global` values and for which components they apply

Minor corrections in helm changelog and docs

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/bradfitz/gomemcache/memcache/memcache.go
vendor/modules.txt

Move to a Grafana fork of bradfitz/gomemcache, retaining the custom dialer from the previous 3rd-party fork and adding optimized parsing code from https://github.com/grafana/gomemcache/pull/1.
Note this is based off a slightly newer base, which adds a `Ping` method.
First described at https://github.com/grafana/mimir/issues/285#issuecomment-1041398539

Memcached client: optimize response parsing

---

pkg/distributor/distributor.go

It's internal to the distributor and unused outside of it.

Make Distributor.ForReplicationSet private

---

pkg/distributor/distributor_test.go

Add tests for per-tenant request metrics introduced in #2770

---

docs/sources/operators-guide/mimir-runbooks/_index.md

Improve ingester unhealthy runbook, to reflect there may be more than one affected ingester. Also fix a typo.

runbooks: Improve ingester unhealthy runbook

---

docs/sources/operators-guide/running-production-environment-with-helm/_index.md
docs/sources/operators-guide/running-production-environment-with-helm/configuration-with-helm.md

Start documenting helm in production.
Fixes #2172 

Helm: document configuration handling in production

---

docs/sources/operators-guide/reference-learning-resources/_index.md

This PR adds two latest Mimir-related blog posts to the learning resources page.

Add latest blog posts to learning resources.

---

.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
Makefile
mimir-build-image/Dockerfile

Adds kustomize to the build image, which will help with contributors running the helm / jsonnet comparison locally

Build image with kustomize

---

docs/internal/contributing/contributing-to-helm-chart.md

Tip about running ct lint with docker. I had trouble installing dependencies.
N/A

Helm: contributing, running ct lint with docker

---

CHANGELOG.md
operations/helm/charts/mimir-distributed/CHANGELOG.md

Cleans up some duplicated changelog entries from main merge

Cleanup duplicated 2.3 changelog entries by merge

---

CHANGELOG.md
docs/sources/release-notes/v2.3.md

- Creates merge to main for 2.3 release

Merge release 2.3.0 to main 

---

tools/trafficdump/processor.go

Fix panic in `trafficdump` tool.

trafficdump: Add nil checks to avoid panic.

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
operations/mimir-mixin/dashboards/tenants.libsonnet

Adds a row for the newly introduced per-tenant request rate metrics.
N/A

Include per-tenant distributor request rate in "Tenants" dashboard

---

operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/capped-large.yaml
operations/helm/charts/mimir-distributed/capped-small.yaml
operations/helm/charts/mimir-distributed/large.yaml
operations/helm/charts/mimir-distributed/small.yaml

Removes "active" from "active series" since this is a billing concept
and not actually how we size components.
N/A

Remove mention of "active series" in helm chart

---

docs/sources/operators-guide/running-production-environment-with-helm/configuration-with-helm.md

Fixes https://github.com/grafana/mimir/issues/2886

Fix yaml in "Manage the configuration of Grafana Mimir with Helm"

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/_helpers.tpl
operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml
operations/helm/charts/mimir-distributed/templates/role.yaml
operations/helm/charts/mimir-distributed/templates/rolebinding.yaml
operations/helm/charts/mimir-distributed/templates/securitycontextconstraints.yaml

Backport https://github.com/grafana/mimir/commit/34c61afa318fec6f8a077057402896994bc66433 from https://github.com/grafana/mimir/pull/2870

[release-2.3] Update release version and dashboard screenshots

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Update changelog to include everything for the next release.

Update Helm changelog.

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

Using r201 weekly for GEM as we don't have release candidate.

release helm 3.1.0-rc.0

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
cmd/mimir/config-descriptor.json
development/mimir-microservices-mode/dev.dockerfile
mimir-build-image/Dockerfile
pkg/compactor/shard_aware_deduplicate_filter.go
pkg/ingester/activeseries/active_series.go
pkg/ingester/activeseries/custom_trackers_config_test.go
pkg/mimir/modules.go
pkg/querier/error_translate_queryable.go
pkg/ruler/ruler.go
pkg/ruler/rulestore/local/local.go
pkg/storegateway/bucket.go
pkg/storegateway/bucket_e2e_test.go
pkg/util/gziphandler/gzip.go
pkg/util/log/wrappers.go
pkg/util/validation/validate.go
tools/listblocks/main.go

Upgrade to build with Go 1.19.1.

Build: Upgrade to Go 1.19.1

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-writes.json
operations/mimir-mixin/dashboards/writes.libsonnet

Update Writes dashboard for OTLP endpoint

Update Writes dashboard for OTLP endpoint

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

* Helm: move recent changelog entries to release 3.1

Helm: update changelog

---

.github/workflows/compare-helm-with-jsonnet.yml

Run the comparison and let github action fail instead of
capturing the error
Fixes #2591 

Enforce helm and jsonnet to match

---

RELEASE.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/templates/NOTES.txt

Adds a section for deprecation notices and migration instructions to the changelog. Mentions this section in NOTEX.txt (printed on helm upgrade/helm install) and README.md.
Also updates RLEASE.md with instructions to keep the deprecation notices up to date.

Add deprecation notices to helm chart

---

operations/mimir-mixin-compiled/dashboards/mimir-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-writes.json
operations/mimir-mixin/dashboards/dashboard-utils.libsonnet

Add an extra field in the dashboard JSON to work round https://github.com/grafana/grafana/issues/54472.
Fixes #2850

dashboards: fix legend showing on per-pod panels

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
operations/mimir-mixin/dashboards/rollout-progress.libsonnet
operations/mimir-mixin/dashboards/writes.libsonnet

In #2919 we added OTLP route support to distributor metrics. In this PR I'm adding it to gateway too.
N/A

Dashboards: add OTLP route support to gateway metrics too

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Uses the 2.3.0-rc.2 as the Mimir version for the helm charts

Update helm tags for Helm Release 3.1.0-rc.1

---

.github/workflows/compare-helm-with-jsonnet.yml

We cannot create comments in users' repositories.

Helm-jsonnet compare: do not use comments to communicate

---

CHANGELOG.md

This PR fixes changelog change that I accidentally merged in #2968.

Fix CHANGELOG.

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-queries.json
operations/mimir-mixin/dashboards/queries.libsonnet
pkg/frontend/querymiddleware/results_cache.go
pkg/frontend/querymiddleware/results_cache_test.go
pkg/frontend/querymiddleware/split_and_cache.go
pkg/frontend/querymiddleware/split_and_cache_test.go

- Add cortex_frontend_cache_missing_total metric
- Add cortex_frontend_query_result_cache_attempted_total metric
- Update dashboards
Fixes https://github.com/grafana/mimir/issues/2433

Add cortex_frontend_query_result_cache_skipped_total  metric

---

docs/internal/contributing/README.md
docs/internal/contributing/contributing-to-helm-chart.md

follows up on https://github.com/grafana/mimir/pull/2965/files

Fix language for gnu-sed on contributing guide

---

CHANGELOG.md
docs/sources/operators-guide/architecture/about-grafana-mimir-architecture/index.md
docs/sources/operators-guide/architecture/components/compactor/index.md
docs/sources/operators-guide/configure/about-versioning.md
docs/sources/operators-guide/configure/configure-metrics-storage-retention.md
docs/sources/operators-guide/configure/configure-object-storage-backend.md
docs/sources/operators-guide/configure/configuring-custom-trackers.md

In this PR:
- Documented how to configure the storage retention
- Re-organized a bit the ordering of configuration subpages, to show the most important first (storage and hash ring config)
Fixes #1700

Docs: added documentation on how to configure storage retention

---

operations/helm/policies/policies.rego
operations/helm/policies/policies_test.rego
operations/helm/policies/topology_spread_constraints_test.rego
tools/run-conftest.sh

A follow-up of #2722 to make sure that the labels used in TSC are present on pods. Also gives more examples for https://github.com/grafana/mimir/issues/2811
- na Tests updated
- na Documentation added
- na `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Test pod topology constraints label selectors

---

go.mod
vendor/modules.txt

Remove unused thrift go.mod replace

---

CHANGELOG.md
docs/sources/operators-guide/configure/about-versioning.md
docs/sources/operators-guide/reference-http-api/index.md

@wilfriedroset great job on #2864! For now, I would prefer to mark it experimental, so we're more free to do adjustments in the near future, if required.
N/A

Mark user limits api experimental

---

CHANGELOG.md
docs/sources/operators-guide/configure/configuring-zone-aware-replication.md

Docs: Fixed configuration option names in "Enabling zone-awareness via the Grafana Mimir Jsonnet"

---

CHANGELOG.md
pkg/util/push/otel.go
pkg/util/push/push_test.go

Fix dropped metric panic with OTLP (#3040)

---

CHANGELOG.md
docs/sources/operators-guide/get-started/_index.md

In this PR I propose to mention the anonymous stats tracking in the getting started guide.
N/A

Docs: mention the anonymous stats tracking in the getting started guide

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-reads.json
operations/mimir-mixin/dashboards/reads.libsonnet

Include rate of label queries on "Reads" dashboard

---

pkg/ingester/label_names_and_values_test.go

Benchmark was calling `ingester.Flush()`, so head was compacted, but the cardinality is calculated on the head, so benchmark was benchmarking on an empty head.
Also increased the number of series pushed into the head, to benchmark harder.
This would also explain the results I was getting in https://github.com/grafana/mimir/pull/3071
N/A

Fix label value cardinality benchmark

---

docs/sources/operators-guide/architecture/components/alertmanager.md
docs/sources/operators-guide/architecture/components/ruler/index.md
docs/sources/operators-guide/tools/mimirtool.md
pkg/mimirtool/commands/alerts.go

I've been collecting these for some time, so committing them now.
- Fix help text of `mimirtool alertmanager load`
- Mentions a detail about alertmanager URL in mimirtool
- Cross-references mimirtool rules and the github action
- Adds a reference to Prometheus docs for alertmanager config

Small additions/edits to ruler and alertmanager docs

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Updates the GEM and Mimir versions to reflect the recent releases

Update mimir versions for helm charts to GEM 2.3.0 and Mimir 2.3.1

---

docs/sources/operators-guide/tools/mimirtool.md

Correct mimirtool analyze documentation to match code beahvior
No issue opened

[docs] Correct mimirtool analyze doc to match the code

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
development/mimir-microservices-mode/dev.dockerfile
mimir-build-image/Dockerfile

This PR updates Go version in build image to 1.19.2

Update go to 1.19.2

---

docs/sources/operators-guide/configure/configuring-hash-rings.md

Document memberlist cluster label verification options: 
* `-memberlist.cluster-label`  
* `-memberlist.cluster-label-verification-disabled`
Fixes #3022

Docs: Added "Cluster label verification" section

---

operations/mimir-mixin/dashboards/dashboard-queries.libsonnet

This is a no-op refactoring PR, using only named variables in the common dashboard queries. I think it makes them easier to read.
N/A

Chore: use named variables in common dashboard queries

---

RELEASE.md
tools/release/tag-release.sh

Adding a script to tag the release.
N/A

Release: add a script to tag the release

---

CHANGELOG.md
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin/config.libsonnet

Reverts grafana/mimir#3195
See: https://github.com/grafana/mimir/pull/3195#issuecomment-1274997367

Revert "Alerts: Include query-scheduler for MimirGossipMembersMismatch"

---

operations/helm/charts/mimir-distributed/mixins/alerts.yaml
operations/helm/charts/mimir-distributed/mixins/rules.yaml
operations/helm/charts/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
operations/helm/charts/mimir-distributed/templates/metamonitoring/prometheusrule.yaml
operations/helm/charts/mimir-distributed/templates/metamonitoring/recording-rules.yaml
operations/helm/charts/mimir-distributed/values.yaml

- probably not correct
used purely for public hosting so I don't have to screw up a decent branch with my confused helm commits

Attempt at referencing rules and alerts within metamonitoring

---

docs/sources/operators-guide/mimir-runbooks/_index.md
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin/alerts/alerts.libsonnet

This is my first time adding an alert to Mimir, please review with care.
Signed-off-by: Mauro Stettler <mauro.stettler@gmail.com>

add alert for high error rate in Distributor's forwarding feature

---

docs/sources/operators-guide/run-production-environment/production-tips/index.md

Docs: mention gRPC compression in "Production tips"

---

ADOPTERS.md

Add OVHcloud to adopters list
N/A

Add OVHcloud to adopters list

---

RELEASE.md
tools/release/tag-release.sh

[release-2.4] Release: add a script to tag the release (#3161)

---

RELEASE.md
tools/release/create-pr-to-merge-release-branch-to-main.sh

In this PR I'm adding a script to create the PR to merge the release branch to main. The https://github.com/grafana/mimir/pull/3233 has been created using this script.
N/A

Release: add script to merge release branch to main

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

Now that we have mimir and GEM rc.0 images

Helm: release mimir-distributed 3.2.0-rc.0

---

tools/release/common.sh
tools/release/create-draft-release-notes.sh
tools/release/create-draft-release.sh

I just published `2.4.0-rc.1` with the scripts updated in this PR, which include a couple of changes:
1. Fix the calculation of number of PRs (see comment in the related line)
2. Do not include release notes if publishing a patch release
N/A

Release: improve release scripts

---

pkg/api/api.go

Update outdated comment. I found it when I read the code.

Update outdated comment

---

docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/deploying.md

Add a note for jsonnet deploying. If you miss it, you would fail to install mimir.
[Rendered](https://github.com/hi-rustin/mimir/blob/rustin-patch-docs-deploy/docs/sources/operators-guide/deploy-grafana-mimir/jsonnet/deploying.md)

Add a note for jsonnet deploying

---

operations/compare-helm-with-jsonnet/compare-kustomize-outputs.sh

Checks that kustomize is installed before running the checks and failing. Also provides a link where it can be found.

Check that kustomize is installed

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml
operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml
operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/query-scheduler/query-scheduler-dep.yaml

backport 3262 to release 2.4

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/_helpers.tpl

Trim return value of prometheusHttpPrefix and alertManagerHttpPrefix

---

docs/sources/tutorials/play-with-grafana-mimir/config/mimir.yaml
docs/sources/tutorials/play-with-grafana-mimir/docker-compose.yml
integration/configs.go
integration/getting_started_with_grafana_mimir_test.go

This reverts grafana/mimir#2376
Fixes https://github.com/grafana/mimir/issues/2377

Use common config in the tutorial again

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-queries.json
operations/mimir-mixin/dashboards/queries.libsonnet

Remove useless `Querier > Stages` panel. 
Fixes https://github.com/grafana/mimir/issues/3301

Remove useless `Querier > Stages` panel

---

docs/sources/release-notes/v2.4.md

Update 2.4 release notes with features promoted to stable and deprecated config options removed.
N/A

Update 2.4 release notes

---

CHANGELOG.md
docs/configurations/prometheus-frontend.yml
docs/sources/operators-guide/configure/configure-the-query-frontend-work-with-prometheus.md

This PR is based on #3252 and addresses the comments I've left there. The original author commit is preserved.
Closes #3252

docs: fix unsupported fields on query-frontend config

---

CHANGELOG.md
operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
operations/mimir-mixin/dashboards/tenants.libsonnet

Extends the Tenants dashboard to add more insights into the Read path
https://github.com/grafana/mimir/issues/3305
Fixes #3305

Add read path insights to tenants dashboard

---

pkg/frontend/querymiddleware/roundtrip.go
pkg/scheduler/scheduler.go

Remove useless arg from `newActiveUsersTripperware`.
Fix typo `eg.` -> `e.g.`
None
No need

Remove useless arg and fix typo

---

docs/internal/contributing/how-integration-tests-work.md
integration/configs.go
integration/e2emimir/services.go
integration/read_write_mode_test.go

This PR adds an integration test for read-write deployment mode.
I've set up something simple to start with, but very open to feedback on making the scenario more realistic (eg. mulitple read or write instances).
Given this is my first PR, there are a bunch of things I'm not 100% sure about which I'll call out in comments below.
#3363 

Read-write deployment mode integration test

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

GEM 2.4 came out, so we are doing another minor release with that image

Helm: release 3.3.0 with GEM 2.4.0

---

CHANGELOG.md
operations/mimir-mixin/dashboards/writes.libsonnet

The query modified in #3394 can be simplified. This PR does it.
N/A

Chore: simplify query used by 'Distributor Forwarding' request rate in the 'Mimir / Writes' dashboard

---

pkg/distributor/distributor.go

This PR fixes regression introduced in #2980, when middlewares used from `Push` function (gRPC handler) were recreated on each push request.

Don't rebuild middlewares on each push.

---

pkg/distributor/distributor.go
pkg/mimirpb/timeseries.go

Fixes nit reported in https://github.com/grafana/mimir/pull/3386#discussion_r1024035565

Use ReusePreallocTimeseries from ReuseSlice.

---

CHANGELOG.md

Just a typo fix: https://github.com/grafana/mimir/pull/3349#discussion_r1025275485

chore: fix PR number

---

operations/mimir-mixin-compiled/dashboards/mimir-overview.json
operations/mimir-mixin/dashboards/overview.libsonnet

In this PR I'm addressing the post-merge feedback received here: https://github.com/grafana/mimir/pull/3481#discussion_r1029111230
N/A

Improve phrasing in Overview dashboard

---

RELEASE.md

Signed-off-by: Mauro Stettler <mauro.stettler@gmail.com>

announce release shepherd of 2.5.0

---

pkg/mimirtool/client/rules.go
pkg/mimirtool/client/rules_test.go

Signed-off-by: songjiayang <songjiayang1@gmail.com>

fix mimir-tool rules delete method comment typo

---

docs/sources/operators-guide/reference-http-api/index.md

Fixes small typos in the API reference.

Fix small typos in API reference

---

pkg/querier/batch/chunk_test.go
pkg/querier/batch/stream.go
pkg/querier/batch/stream_test.go

Define semantics and implement a version that passes current tests.
Todo add tests with histograms.

Unit test fixes for native histograms

---

pkg/storegateway/batch_series.go
pkg/storegateway/batch_series_test.go

A minor PR to improve `TestDeduplicatingBatchSet`. I did these changes to the test while reviewing the `deduplicatingBatchSet.Next()` implementation.
N/A

Improve TestDeduplicatingBatchSet

---

pkg/storegateway/bucket.go

The great PR description in https://github.com/grafana/mimir/pull/3546 made me think we could rename `BucketStore.mtx` to clarify what it protects.
N/A

Chore: rename BucketStore.mtx to BucketStore.blocksMx to clarify what it protects

---

pkg/storegateway/bucket.go

This should fix at least a reason why store-gateway panics in the integration tests.
N/A

Fix panic due to not initialized resHints

---

Makefile

Reverts grafana/mimir#3527 as it doesn't seem to work on linux.
The issue seems to be that `weave` user we create in `build.sh` doesn't have permissions to write to freshly created volume.

Revert "Improve speed of Golang-related Makefile targets when running on macOS"

---

pkg/storegateway/batch_series_test.go

The fix is in two parts
- set the index cache
- properly build a promql matcher
I also renamed the test to be what it's actually testing
Further testing, including testing non-error cases, will be done in a
separate PR after I break the dependencies of blockSeriesChunkRefsSetsIterator

store-gateway streaming: fix TestBlockSeriesChunkRefsSetsIterator

---

CHANGELOG.md

I had to backport this manually because there was a conflict, followed the description [here](https://github.com/grafana/mimir/pull/3550#issuecomment-1331243655)

[release-2.5] add missing entries and release section to changelog in preparation for release

---

CHANGELOG.md

This is a manual cherry-pick of [PR](https://github.com/grafana/mimir/pull/3572) because the automated one failed [here](https://github.com/grafana/mimir/pull/3572#issuecomment-1331301369)

[release 2.5] mark version in changelog as rc

---

pkg/storegateway/bucket.go
pkg/storegateway/bucket_chunk_reader.go

I wanted to test loadingBatchSet. This was difficult because we have no
control over the chunks in the blocks, so it's difficult to assert on
what chunks we get.
With this PR I am making the chunkReader an interface so that it's
easier to inject chunks and check that chunkReaders (plural) and
loadingBatchSet are working correctly together.

streaming store-gateway: use an interface for chunkReader

---

docs/sources/release-notes/v2.5.md

I have skipped the section "Important changes" because I think actually there weren't any.
I have not added the section "Helm chart improvements" yet because I think I'll need a bit of help with that, as I don't have the overview of the helm chart improvements.

release notes 2.5

---

pkg/alertmanager/multitenant.go

Minor language fix in Alertmanager code comment.

Alertmanager: Minor language fix

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/operators-guide/configure/reference-configuration-parameters/index.md
docs/sources/release-notes/v2.5.md
pkg/alertmanager/multitenant.go
pkg/compactor/bucket_compactor_e2e_test.go
pkg/compactor/bucket_compactor_test.go
pkg/distributor/distributor_test.go
pkg/ingester/activeseries/active_series_test.go
pkg/querier/batch/chunk_test.go
pkg/querier/tenantfederation/tenant_federation.go
pkg/ruler/notifier.go
pkg/ruler/ruler_test.go
pkg/storage/series/series_set_test.go
pkg/storage/tsdb/block/block_test.go
pkg/storage/tsdb/block/index_test.go
pkg/storage/tsdb/upload_test.go
pkg/storegateway/bucket_stores_test.go
pkg/storegateway/indexheader/header_test.go
pkg/storegateway/indexheader/lazy_binary_reader_test.go
pkg/storegateway/indexheader/reader_pool_test.go
pkg/storegateway/series_chunks.go
pkg/storegateway/snappy_gob_codec_test.go

Another PR to merge main into streaming store-gateway branch. This should make the next rebase trivial.
N/A

Merge main into streaming store-gateway branch

---

.golangci.yml
integration/ruler_test.go
mimir-build-image/Dockerfile
pkg/frontend/querymiddleware/querysharding_test.go
pkg/ingester/instance_limits.go
pkg/mimir/modules.go
pkg/mimirtool/commands/bucket_validation.go
pkg/mimirtool/commands/rules.go
pkg/querier/cardinality_analysis_handler.go
pkg/ruler/compat.go
pkg/storage/tsdb/block/index.go
pkg/storage/tsdb/config.go
pkg/storegateway/bucket_e2e_test.go
pkg/storegateway/bucket_index_postings.go
pkg/storegateway/indexheader/header.go
pkg/util/activitytracker/activity_tracker_test.go
pkg/util/allowed_tenants_test.go
pkg/util/gziphandler/gzip.go
pkg/util/limiter/query_limiter.go
pkg/util/validation/errors.go
pkg/util/version/info.go

Switch from unmaintained `golint` to `revive` linter.
N/A

Switch linter from golint to revive and clean up newly found issues

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

Release a Helm 4.0.0 rc to go with #3525

Release Helm 4.0.0-rc.0

---

pkg/storegateway/bucket_stores.go
pkg/storegateway/gateway.go

Fix and add documentation comments on `storepb.StoreGatewayServer` implementation `StoreGateway` and `storepb.StoreServer` implementation `BucketStores`.

Fix/add documentation comments on StoreGateway service implementations

---

pkg/storegateway/bucket_chunk_reader.go

None would like to review a PR removing a mutex. If there's a mutex, it's very likely there's a very good reason. However, I can't find a good reason for `bucketChunkReader.mtx` so in this PR I'm proposing to remove it (please review this carefully).
I think the mutex was there to protect the access from `loadChunks()` to a set of chunks and statistics, but recent refactorings replaces both of them with a concurrency safe version:
- https://github.com/grafana/mimir/pull/3506: in this PR we changed `chunkBytes []*[]byte` with `*pool.BatchBytes` which is concurrency safe
- https://github.com/grafana/mimir/pull/3509: in this PR we changed `*queryStats` with `*safeQueryStats` which is concurrency safe
N/A

Refactoring: remove mutex from bucketChunkReader

---

CHANGELOG.md
operations/mimir-mixin-compiled-baremetal/alerts.yaml
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin/alerts/alerts.libsonnet

Update MimirMemoryMapAreasTooHigh to include read-write components.
Partial fixes #3366

alerts: Update MimirMemoryMapAreasTooHigh to include read-write components

---

docs/sources/mimir/operators-guide/architecture/bucket-index/index.md
docs/sources/mimir/operators-guide/architecture/components/compactor/index.md
docs/sources/mimir/operators-guide/architecture/components/distributor.md
docs/sources/mimir/operators-guide/architecture/components/query-frontend/index.md
docs/sources/mimir/operators-guide/architecture/components/query-scheduler/index.md
docs/sources/mimir/operators-guide/architecture/hash-ring/index.md
docs/sources/mimir/operators-guide/configure/configure-zone-aware-replication.md

While going through the Mimir docs I found some minor issues. This is an attempt of fixing the ones I encountered.
n/a

Docs: Minor fixes

---

docs/sources/mimir/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/_index.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/values.yaml

Add documentation on making sure user to use matches values.yaml when building their helm values.
Fixes https://github.com/grafana/mimir-squad/issues/797 (internal issues).

Add note about values.yaml mismatch prevention

---

.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
Makefile
mimir-build-image/Dockerfile

This PR adds jsonnet to build image and bumps the version of jsonnetfmt at the same time.
We also simplify Makefile code used to build multiarch build image.

Add jsonnet to build-image

---

docs/sources/mimir/migration-guide/migrating-from-cortex.md
docs/sources/mimir/operators-guide/tools/mimirtool.md

This PR clarifies the installation instructions for `mimirtool`.
Partially resolves some of the feedback in https://github.com/grafana/mimir/issues/3680.

Clarify installation instructions for mimirtool

---

docs/sources/mimir/operators-guide/architecture/components/alertmanager.md
docs/sources/mimir/operators-guide/architecture/components/ruler/index.md

It took me a bit of trial and error to figure out how to configure Ruler to send alerts to Alertmanager - this updates the docs to reflect how I _think_ we want it to be configured.
Relates to #3684 

Clarify how to configure Ruler to send alerts to Alertmanager

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
operations/mimir-mixin-compiled-baremetal/alerts.yaml
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin/alerts/alerts.libsonnet

fix MimirIngesterRestarts for read-write deployment
Partial fixes https://github.com/grafana/mimir/issues/3366

alerts: fix MimirIngesterRestarts for read-write deployment

---

CHANGELOG.md

PR #3710 accidentally duplicated an entry in the changelog due to a bad merge resolution during review.

Changelog: Fix mistake in changelog

---

.github/workflows/publish-technical-documentation-next-helm-charts.yml
.github/workflows/publish-technical-documentation-next-mimir.yml
.github/workflows/publish-technical-documentation-release-helm-charts.yml
.github/workflows/publish-technical-documentation-release-mimir.yml
.github/workflows/test-build-deploy.yml
docs/Makefile
docs/docs.mk
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md

Splits CI into separate workflows for each of the helm-charts and core project technical documentation publishing.
Need guidance on the branches and tags that the should be added to the helm-charts workflows.

Update CI to work with helm-charts and project docs separation

---

CHANGELOG.md
docs/sources/mimir/operators-guide/reference-http-api/index.md
pkg/api/api.go
pkg/api/handlers.go
pkg/api/handlers_test.go

Add `api/v1/status/config` API support.
Ref https://github.com/grafana/mimir/issues/3323

Add `api/v1/status/config` API

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Release 4.0 mimir-distributed chart
Fixes: N/A
these were already done in RC versions:

Helm: release and publish 4.0 mimir-distributed chart

---

CHANGELOG.md

Adding PRs #3697 #3666 #3687 #3728 #3739 #3606 #3611

Add missing PRs to changelog for streaming store-gateway

---

operations/mimir/multi-zone.libsonnet
operations/mimir/read-write-deployment/backend.libsonnet

In https://github.com/grafana/mimir/pull/3653 we introduced `multi_zone_store_gateway_unregister_on_shutdown` to control `-store-gateway.sharding-ring.unregister-on-shutdown`. Unfortunately I can't use it the way I want, because I want to control whether to apply it only on microservices store-gateway or read-write mimir-backend, while migrating from one to the other.
In this PR I'm removing `multi_zone_store_gateway_unregister_on_shutdown` and making `-store-gateway.sharding-ring.unregister-on-shutdown` overrideable instead.
_This is expected to be a no-op for the jsonnets tests in this repo._
N/A

Refactoring: make -store-gateway.sharding-ring.unregister-on-shutdown overrideable

---

docs/sources/mimir/operators-guide/architecture/bucket-index/index.md
docs/sources/mimir/operators-guide/run-production-environment/production-tips/index.md
docs/sources/mimir/operators-guide/tools/query-tee.md

Fixes some minor typos in the docs.
n/a

Fix some typos in the docs

---

pkg/frontend/querymiddleware/querysharding_test.go
pkg/frontend/querymiddleware/querysharding_test_utils_test.go
pkg/frontend/querymiddleware/sharded_queryable_test.go
pkg/ingester/ingester.go
pkg/ingester/ingester_test.go
pkg/querier/batch/batch.go
pkg/querier/batch/batch_test.go
pkg/querier/batch/stream.go
pkg/querier/distributor_queryable_test.go
pkg/querier/iterators/chunk_merge_iterator.go
pkg/querier/iterators/chunk_merge_iterator_test.go
pkg/storage/chunk/prometheus_chunk.go

Apply review comments from #3682

Apply review comments from #3682

---

pkg/storegateway/indexcache/cache.go
pkg/storegateway/indexcache/cache_test.go

Backport 3779 to r217

---

go.mod
go.sum
pkg/ingester/ingester.go
pkg/ingester/user_tsdb.go
pkg/storage/ephemeral/label.go
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/github.com/prometheus/prometheus/promql/parser/functions.go
vendor/github.com/prometheus/prometheus/promql/quantile.go
vendor/modules.txt

Adds a promql function `aggregate_counters()` which takes as input the aggregated and raw series of a metric.
It calculates the increase of all the raw series and adds them to the last value of the corresponding aggregated series.

[WIP] add function to aggregate counters

---

CHANGELOG.md

This PR updates the changelog to include #3742.
#3742

Add changelog entry for #3742.

---

integration/read_write_mode_test.go

This PR adds an integration test for the compactor in read-write deployment mode.
I'm not sure if this is the best way to exercise the compactor - given we're not trying to test its behaviour, but simply that it is configured correctly and able to run, this _seemed_ like the easiest way to do it. Very open to alternative suggestions.
Fixes #3363

Read-write deployment mode integration tests: compactor

---

CHANGELOG.md
pkg/storegateway/indexheader/index/postings.go

This PR addresses [a piece of feedback on #3742](https://github.com/grafana/mimir/pull/3742#discussion_r1052103456) that was not addressed before merging.
Part of #3465, relates to #3742

Store gateway mmap removal: address last remaining feedback on #3742

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

Updating mimir-prometheus to bring changes from https://github.com/grafana/mimir-prometheus/pull/377. See description there.
None

Shortcut postings for matchers for empty postings

---

docs/sources/mimir/operators-guide/secure/authentication-and-authorization.md

This PR fixes formatting of header name in the https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/ page.

Fix formatting of header name

---

pkg/storegateway/indexcache/memcached.go
pkg/storegateway/series_refs.go

This PR addresses these comments from #3839 
* https://github.com/grafana/mimir/pull/3839#discussion_r1060506145
* https://github.com/grafana/mimir/pull/3839#discussion_r1060508536
* https://github.com/grafana/mimir/pull/3839#discussion_r1060511030
* https://github.com/grafana/mimir/pull/3839#discussion_r1060513598
* https://github.com/grafana/mimir/pull/3839#discussion_r1060514249
* https://github.com/grafana/mimir/pull/3839#discussion_r1060515093
* https://github.com/grafana/mimir/pull/3839#discussion_r1060515326

store-gateway series caching: address comments from PR 3839

---

CHANGELOG.md
operations/mimir-tests/test-deployment-mode-migration-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
operations/mimir/read-write-deployment/write.libsonnet

See explanation in https://github.com/grafana/mimir/issues/3804#issuecomment-1371932856.
Fixes #3804

Fix mimir-write Kubernetes service to correctly balance route requests among mimir-write pods

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/recording-rules.yaml
operations/mimir-mixin-compiled-baremetal/alerts.yaml
operations/mimir-mixin-compiled-baremetal/rules.yaml
operations/mimir-mixin-compiled/rules.yaml
operations/mimir-mixin/alerts/alertmanager.libsonnet
operations/mimir-mixin/alerts/alerts.libsonnet
operations/mimir-mixin/config.libsonnet
operations/mimir-mixin/recording_rules.libsonnet

Add support for baremetal deployment for alerting rules and scaling recording rules

Mixin baremetal

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Noticed while preparing separate release notes for the helm charts docs.

Fix missing changelog entry.

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Found while generating release notes of chart 4.0
Issue: #3275

Fix wrong PR number in Helm changelog

---

.github/workflows/publish-technical-documentation-next-helm-charts.yml
.github/workflows/publish-technical-documentation-next-mimir.yml
.github/workflows/publish-technical-documentation-release-helm-charts.yml
.github/workflows/publish-technical-documentation-release-mimir.yml

The requisite secrets have already been created.

Update publishing workflows to use PATs with fine-grained access control

---

.github/workflows/publish-technical-documentation-next-helm-charts.yml
.github/workflows/publish-technical-documentation-release-helm-charts.yml

This branch is the staging site for testing the new Helm documentation pages.

Publish to Helm charts documentation development branch

---

docs/docs.mk

Podman (https://podman.io) supports running images as non-root users without the security implications of the Docker daemon.
If the podman executable is available, use it. Otherwise, fall back to docker.

Support daemonless containers

---

pkg/ingester/ingester.go

This PR extracts `pushStats` struct from `(*Ingester).PushWithCleanup` method. This is in preparation to have another copy of `pushStats` for ephemeral series.
Part of https://github.com/grafana/mimir/issues/3884

Extract `pushStats` from `PushWithCleanup`

---

operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl

Mimir helm documentation has moved, so link to its new home

Update link to helm chart documentation

---

pkg/distributor/distributor.go

This is a follow-up for comment https://github.com/grafana/mimir/pull/3889#discussion_r1065904690. This PR modifies distributor code to preallocate slices with correct lengths, based on scanning the indexes.

Prealloc correct slice lenghts in distributor push method

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Release 4.0.1 mimir-distributed chart
Fixes N/A

Update GEM image to 2.5.1 in Helm chart 4.0.1

---

pkg/ingester/ingester.go

This PR extracts `(*Ingester).pushSamplesToAppender` function from `(*Ingester).PushWithCleanup`. To write series to ephemeral storage, we want to call this function second time with different timeseries and appender and other parameters.
Related to https://github.com/grafana/mimir/issues/3884.

Extract pushSamplesToAppender method from PushWithCleanup.

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Update mimir-distributed 4.0.1 release notes

Update mimir-distributed 4.0.1 release notes

---

.github/workflows/helm-release.yaml
operations/helm/cr.yaml

Please see https://github.com/grafana/helm-charts/pull/2107

Remove helm chart signing

---

operations/mimir/autoscaling.libsonnet
operations/mimir/config.libsonnet
operations/mimir/read-write-deployment/config.libsonnet

Jsonnet already has an 'assert <assertion>' statement, there's no need to craft handmade 'if <assertion> then null else error'.
None, was just passing by.

Use assert statements instead of handmade checks

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/async_block_writer.go
vendor/github.com/prometheus/prometheus/tsdb/compact.go
vendor/modules.txt

This PR updates `mimir-prometheus` to latest main to bring in PR http://github.com/grafana/mimir-prometheus/pull/393.

Update mimir-prometheus to fix rare panic in compaction (both in ingester and compactor)

---

integration/overrides_exporter_test.go

Use `test.Poll` to fix a flaky integration test.
n/a

Overrides-exporter: fix flaky integration test

---

RELEASE.md

Nick offered to lead 2.6 release (thanks!). In this PR I'm also going to add 2.7 release to the schedule.
N/A

Announce next Mimir release shepherd

---

CHANGELOG.md
tools/tsdb-print-chunk/main.go

This PR adapts tsdb-print-chunk for native histograms.
Fixes https://github.com/grafana/mimir/issues/3949

Adapt tsdb-print-chunk for native histograms

---

operations/mimir-mixin-tools/screenshots/package.json

Ensure required `name` and `version` fields are in `package.json`.
Pointed out by security team scanning the Mimir repo.

Ensure package.json for screenshot tool is well-formed

---

pkg/compactor/shard_aware_deduplicate_filter.go
pkg/compactor/shard_aware_deduplicate_filter_test.go

Small code and documentation refactoring and improvements in shard_aware_deduplicate_filter.go

Small documentation improvements

---

pkg/ingester/ingester.go
pkg/ingester/ingester_test.go
pkg/mimirpb/compat.go
pkg/querier/batch/chunk_test.go
pkg/querier/iterators/chunk_iterator.go
pkg/querier/iterators/chunk_merge_iterator.go
pkg/storage/chunk/chunk.go
pkg/storage/chunk/chunk_test.go
pkg/storage/chunk/factory.go
pkg/storage/chunk/prometheus_chunk.go
pkg/util/chunkcompat/compat.go

Add float histogram support to ingester

Add float histogram support to ingester

---

CODEOWNERS

For those who only want notifications re the ruler or Alertmanager.
N/A

Update CODEOWNERS to include mimir-ruler-and-alertmanager-maintainers

---

docs/sources/mimir/operators-guide/configure/configure-otel-collector.md

Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>

[otlp] Docs: Highlight common issues with OTLP --> Prometheus

---

.github/workflows/snyk.yml

Hello, this PR adds a workflow to automate code scanning via Snyk. The Grafana Labs Security Engineering manages a Snyk tennent which will ingest these results. Adding this workflow will allow our Snyk Dashboards to be updated on every release and merge to the 'main' branch. If you have any questions, please reach out to '@security-team' or '#security-engineering'
[_Created by Sourcegraph batch change `ethan.smith/snyk-monitor-workflow`._](https://grafana.sourcegraph.com/users/ethan.smith/batch-changes/snyk-monitor-workflow)

Add Snyk Scanning workflow

---

CHANGELOG.md

Cut the changelog for 2.6.0-rc.0

---

docs/sources/mimir/release-notes/v2.6.md

Note that Helm chart is released separately now

---

pkg/storegateway/bucket_test.go

This PR addresses a couple of post-merge comments received on #4037. In particular, it fixes `TestBucketStore_Series_LimitsWithStreamingEnabled` test cases description and setup.
N/A

Fix TestBucketStore_Series_LimitsWithStreamingEnabled

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/storage/remote/codec.go
vendor/modules.txt

At https://github.com/grafana/mimir-prometheus/commit/38af345deab11d12a3a093d2fb366d8328020342
For https://github.com/prometheus/prometheus/pull/11881

Vendor update mimir-prometheus

---

CHANGELOG.md
pkg/storegateway/indexheader/binary_reader.go
pkg/storegateway/indexheader/index/postings.go

Addressing some late comments on https://github.com/grafana/mimir/pull/4055 and adding a changelog entry.

Address Marco's feedback on 4055

---

cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/reference-configuration-parameters/index.md
pkg/alertmanager/alertmanager_ring.go
pkg/alertmanager/multitenant.go
pkg/alertmanager/multitenant_test.go
pkg/compactor/compactor.go
pkg/compactor/compactor_ring.go
pkg/compactor/compactor_test.go
pkg/distributor/distributor.go
pkg/distributor/distributor_ring.go
pkg/distributor/distributor_test.go
pkg/mimir/mimir_test.go
pkg/mimir/modules.go
pkg/mimir/modules_test.go
pkg/ruler/lifecycle_test.go
pkg/ruler/ruler.go
pkg/ruler/ruler_ring.go
pkg/ruler/ruler_test.go
pkg/util/ring_config.go
pkg/util/validation/exporter/exporter_test.go
pkg/util/validation/exporter/ring.go
pkg/util/validation/exporter/ring_test.go

This extracts some commonly used ring config code. This does not yet(?) include the scheduler discovery code because of a subtle difference in doc strings.
Fixes #4053

Deduplicate ring config code

---

docs/internal/contributing/README.md

This adds a short section about how to run Mimir locally using the docker-compose setup, and two other minor additions.
No issue created for this.

Docs: Explain how to run Mimir locally using docker-compose

---

operations/helm/charts/mimir-distributed/values.yaml

This pr fixes a number of spelling and grammar mistakes in the helm charts values.yaml file. 
I didn't add anything to the changelog since it's not a bug fix or feature. It just something that you might notice when deploying the chart (like I did). 

helm: fix spelling and grammar mistakes in values.yaml

---

.github/workflows/test-build-deploy.yml

Update doc-validator workflow so that it no longer relies on old checkout mechanism

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Fixup helm chart changelog missing PR num

---

docs/sources/mimir/operators-guide/configure/configure-tsdb-block-upload.md

This PR removes an extra closing bracket on this page in the docs.
(none)

Fix typo on "configure TSDB block upload" page.

---

go.mod
go.sum
integration/util.go
vendor/github.com/prometheus/common/model/value.go
vendor/github.com/prometheus/common/model/value_float.go
vendor/github.com/prometheus/common/model/value_histogram.go
vendor/github.com/prometheus/common/model/value_type.go
vendor/modules.txt

A version of these have been tested on sparsehistogram branch.
Related to #3478 

Add histogram generator functions for e2e tests

---

pkg/util/validation/validate.go

Remove unused metric from code

---

integration/backward_compatibility.go

Add Mimir 2.6 to backwards compatibility testing

---

integration/store_gateway_limits_hit_test.go

The idea of the change proposed in this PR is to start querier and store-gateway after all series have been pushed, so that once they're marked as ready (and the test continues) it's guaranteed they already discovered all blocks from the storage.
As a side effect, this makes the test faster. It runs in 25s on my machine vs 60s of the previous version.
N/A

Try to improve integration test in #4100

---

docs/docs.mk

Inject redirect page to simulate grafana.com/docs/mimir redirecting to grafana.com/docs/mimir/latest

docs/docs.mk: fix redirection

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
development/mimir-microservices-mode/config/mimir.yaml
development/mimir-monolithic-mode-with-swift-storage/config/mimir.yaml
development/mimir-monolithic-mode/config/mimir.yaml
docs/sources/mimir/reference-configuration-parameters/index.md
integration/backward_compatibility.go
integration/e2emimir/services.go
pkg/frontend/querymiddleware/limits.go
pkg/frontend/querymiddleware/limits_test.go
pkg/frontend/querymiddleware/querysharding.go
pkg/frontend/querymiddleware/querysharding_test.go
pkg/ingester/ingester.go
pkg/ingester/ingester_test.go
pkg/util/validation/limits.go
pkg/util/validation/limits_test.go

Rename configuration parameter

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/docs.mk
docs/sources/mimir/operators-guide/architecture/query-sharding/index.md
docs/sources/mimir/operators-guide/configure/about-versioning.md
docs/sources/mimir/reference-configuration-parameters/index.md
pkg/frontend/querymiddleware/roundtrip.go

This adds documentation for the experimental cardinality estimation feature merged in #4121 and #4177.
Relates to #4108

Add documentation for cardinality estimation

---

docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md

Clarify and make explicit the requirements for multi zone migration for the helm chart.
Fixes: question about upgrade procedure

Helm: more explicit migration instructions about zone awareness

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.1.md
operations/helm/charts/mimir-distributed/CHANGELOG.md

Adds release notes for the 4.1 Helm chart release.
Adds a PR number to a PR in the changelog.

Helm: Add release notes for the 4.1 release

---

docs/sources/mimir/operators-guide/configure/configure-object-storage-backend.md

The region looks confuse without the number of region
fix documentation with a good and functional example.

fix region configuration example for s3

---

pkg/storage/tsdb/block/block.go
pkg/storage/tsdb/testutil/block_generator.go
pkg/storegateway/testhelper/testhelper.go

Minor typo and unused parameter fixes

---

pkg/ruler/compat.go
pkg/ruler/compat_test.go

Makes ruler recognize native histograms coming out of rules.
Fixes #4155

Support native histograms in ruler

---

integration/backward_compatibility.go
integration/e2emimir/services.go

Use RemoveFlagMapper

---

pkg/compactor/compactor_test.go
pkg/frontend/querymiddleware/cardinality_test.go
pkg/frontend/querymiddleware/querysharding_test.go

[Chore] Fix linter issue for golangci-lint 1.51.2

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile
mimir-build-image/Dockerfile
pkg/frontend/querymiddleware/cardinality_test.go

This PR is to update mimir go version to 1.20.1 and golangci-lint to version 1.51.2

Chore: update go version to 1.20.1

---

docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md

Update doc links to match the Helm chart and Mimir/GEM.
Fixes N/A

Update Mimir and GEM version in helm chart docs

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

In this PR I'm merging the mimir-distributed-release-4.2 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.
---
This completes the release of v4.2 of the Helm chart.

Merge mimir-distributed-release-4.2 to main

---

docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md

Backport 4296
Fixes version in docs and triggers publish of docs again

Backport: Update Mimir and GEM version in helm chart docs (#4296)

---

docs/sources/mimir/operators-guide/get-started/_index.md

Perform maintenance on this page.

Docs: Perform maintenance on Get started guide

---

docs/sources/mimir/operators-guide/architecture/components/store-gateway.md
docs/sources/mimir/references/glossary.md

Move Glossary reference to References section.

---

operations/helm/charts/mimir-distributed/RELEASE.md

Clarifies the release steps for the Helm chart.
(none)

Clarify Helm chart release instructions.

---

RELEASE.md

This PR updates Mimir release schedule, and adds @aldernero as shepherd for 2.7.0.

Update Mimir release schedule

---

docs/sources/mimir/migrate/migrate-from-thanos-to-mimir-with-thanos-sidecar.md

Move migration guide into newest dir structure.

---

go.mod
pkg/api/protobuf_codec.go
pkg/api/protobuf_codec_test.go
pkg/frontend/querymiddleware/codec_protobuf.go
pkg/frontend/querymiddleware/codec_protobuf_test.go
pkg/mimirpb/compat.go
pkg/mimirpb/compat_test.go
pkg/mimirpb/mimir.pb.go
pkg/mimirpb/mimir.proto
pkg/mimirpb/query_response_extra.go
pkg/mimirpb/query_response_extra_test.go
pkg/util/test/histogram.go
pkg/util/test/histogram_test.go

Syncs changes done to `mimirpb` package in `sparsehistogram` branch and also syncs other packages that break with this change.

Add native histograms to mimirpb

---

CHANGELOG.md
pkg/ruler/manager.go
pkg/ruler/manager_test.go

Ruler: load more tenants in parallel during startup

---

docs/sources/mimir/operators-guide/configure/configure-zone-aware-replication.md

Change language to match the math.

---

README.md

Fix typo in the docs URL for migrating from Cortex

---

docs/sources/mimir/operators-guide/get-started/_index.md

Fix port number values.

---

docs/sources/mimir/operators-guide/configure/configure-zone-aware-replication.md

Moves the "Note:" about the cross-zone traffic to the correct `# Costs` section of the docs.
N/A

Move "Note:" about cross-zone costs to "Costs"

---

pkg/compactor/compactor_test.go
pkg/compactor/split_merge_compactor_test.go
pkg/distributor/distributor_test.go

Syncs the updates in the unit tests for distributor and compactor done in `sparsehistogram` into `main` branch. 
Requires https://github.com/grafana/mimir/pull/4354 to be merged

Update distributor and compactor tests for native histograms

---

integration/ingester_test.go

This PR adds an integration test verifying the ingestion of float series, native histogram series, and mixed float/native histogram series.
Fixes https://github.com/grafana/mimir/issues/3715

Add ingester integration test for mixed float/native histograms series

---

integration/compactor_test.go

This PR adds integration tests for the compactor compacting blocks containing native histograms.

Integration tests for compacting native histogram blocks

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/operators-guide/configure/about-versioning.md
docs/sources/mimir/references/configuration-parameters/index.md
pkg/compactor/compactor.go
pkg/compactor/compactor_test.go
pkg/mimir/mimir.go
pkg/querier/blocks_store_queryable.go
pkg/storage/tsdb/config.go
pkg/storage/tsdb/config_test.go
pkg/storegateway/bucket_stores.go
pkg/storegateway/gateway_test.go
pkg/util/fieldcategory/overrides.go
pkg/util/flags.go
pkg/util/usage/usage.go

This PR cherry-picks #4409 onto `release-2.7` branch.

Cherry-pick #4409 into release-2.7 branch

---

CHANGELOG.md

This PR updates changelog in release-2.7 branch from version in `main`.

Update changelog for release 2.7

---

CHANGELOG.md

Move changelog entry for PR #4423 into main / unreleased section.

Fix changelog entry for PR #4423

---

operations/compare-helm-with-jsonnet/jsonnet/06-services/kustomization.yaml
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/large-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/small-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/distributor/distributor-svc-headless.yaml

Added http port for distributor-svc-headless.
Fixes #4392

Helm: added HttpListenPort in distributor-svc-headless

---

pkg/distributor/distributor.go

Fix docstring of `Distributor` type, since it was referring to a couple of interfaces it doesn't implement at this point.

distributor: Fix type docstring

---

docs/sources/mimir/operators-guide/configure/about-versioning.md

Cherry pick part of #4429 that is included in v2.7.
#4104

Add protobuf internal query result payload format to experimental features list for v2.7.

---

docs/sources/mimir/migrate/migrating-from-single-zone-with-helm.md

Remove file containing link to Helm docs.

---

RELEASE.md

This PR adds a note clarifying the version naming requirements during the Release Candidate phase of creating a new release.
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Update RELEASE.md with note about release candidate versioning

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Start Helm version 4.3.0, including GEM v2.7.0.

Helm: Update changelog with version 4.3.0

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.2.md

Missing warning.
Wrong versions in link.

Helm: fix issues in helm chart release notes for 4.2

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.3.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Release Helm chart v4.3.0, with Mimir v2.7.1 and GEM v2.7.0 (based on Mimir 2.7.1).

Release Helm chart v4.3.0

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.3.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Merge the [mimir-distributed-release-4.3](https://github.com/grafana/mimir/tree/mimir-distributed-release-4.3) branch into main.

Merge mimir-distributed-release-4.3.0 into main

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.2.md

Missing warning.
Wrong versions in link.

Backport: Helm: fix issues in helm chart release notes for 4.2 (#4536)

---

CHANGELOG.md
README.md

Fixes broken links
Fixes #4469

Docs: Fix broken links

---

docs/sources/mimir/operators-guide/monitor-grafana-mimir/collecting-metrics-and-logs.md

Odd spacing ahead of a full stop.
Minor formatting fix

Removed spurious spacing

---

docs/sources/mimir/references/configuration-parameters/index.md
docs/sources/mimir/references/configuration-parameters/index.template

Docs: Add and fix aliases for configuration-parameters

---

docs/sources/mimir/references/configuration-parameters/index.md
docs/sources/mimir/references/configuration-parameters/index.template

Cherry picks: be96df979f3c6bec4879b13d60d3490e9478befd 
Cherry picks: 7bf69c6e7f78935d337266fd0f688111112e7c82

Backport Docs: fix again broken reference configuration aliases (#4565)

---

docs/sources/mimir/operators-guide/tools/mimirtool.md

Hi all - I find a some typos in the docs "analyse" (more than once). Command line is "analyze"
Fix typos in the docs

Typo in the docs

---

CHANGELOG.md
docs/sources/mimir/operators-guide/mimir-runbooks/_index.md

Improves the MimirCompactorHasNotSuccessfullyRunCompaction runbook
Fixes #4608 
Also fixes indentation in the same runbook as it was a little incorrect.

[Docs] Extend runbook for MimirCompactorHasNotSuccessfullyRunCompaction

---

go.mod
vendor/modules.txt

Remove unused galaxycache replace inherited from Thanos

---

CODEOWNERS
MAINTAINERS.md

Last week we voted to add new maintainers to the project. Since the vote passed, in this PR I'm updating `MANTAINERS.md` and `CODEOWNERS`. I also invited all 4 new maintainers to have write privileges (request is pending, reason why `CODEOWNERS` validator still report an issue).
N/A

Add new maintainers

---

pkg/ruler/remotequerier_decoder.go

Sort the labels.  Also stop assuming it's a slice; use abstractions.
Fixes #4614 
I'm in two minds whether it belongs in the changelog.
Can't defend not adding a test, except I thought it's better to push the fix than wait until I can figure out the tests.

ruler remotequerier: sort labels received in json

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.lock
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/large-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/large-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/openshift-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/openshift-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/scheduler-name-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/scheduler-name-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/small-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/small-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml
operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml
operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/charts/rollout_operator/templates/serviceaccount.yaml

update rollout operator to 0.4.1
Fixes #4658
- [✓] Tests updated
- [✓] Documentation added
- [✓] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

update rollout operator to 0.4.1

---

CHANGELOG.md
cmd/metaconvert/Dockerfile
cmd/mimir-continuous-test/Dockerfile
cmd/mimir/Dockerfile
cmd/mimirtool/Dockerfile
cmd/query-tee/Dockerfile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
development/mimir-monolithic-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile

Updates Alpine to 3.17.3.
[Changelog](https://www.alpinelinux.org/posts/Alpine-3.17.3-released.html)
N/A

Update Alpine to 3.17.3

---

operations/helm/charts/mimir-distributed/templates/_helpers.tpl
operations/helm/charts/mimir-distributed/templates/nginx/_helpers.tpl

Fix a few typos in the helm chart template. Purposely not adding Changelog.

Helm: Fix few typos

---

pkg/distributor/distributor_test.go
pkg/ingester/ingester.go
pkg/mimirpb/compat.go
pkg/mimirpb/compat_test.go
pkg/querier/distributor_queryable_test.go
pkg/querier/timeseries_series_set.go
pkg/storage/series/series_set.go

Fixes https://github.com/grafana/mimir/issues/4488

Convert histogram proto directly to float where possible

---

CHANGELOG.md

- na Tests updated
- na Documentation added
- na `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Cut the changelog for 2.8.0-rc.0

---

development/mimir-microservices-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile

Required to be able to work with Go 1.20

Update to the latest version of delve (1.20.2)

---

docs/sources/mimir/references/http-api/index.md

Forgot to update the list of verbs supported in #4718 after review feedback.

Add DELETE verb to prepare-shutdown docs

---

docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md

Remove extraneous line.

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile
mimir-build-image/Dockerfile
pkg/storegateway/series_refs_test.go

To get a new build of Mimir for the weekly helm chart

Go: Upgrade to 1.20.3 (#4773)

---

CHANGELOG.md
operations/mimir-tests/test-autoscaling-generated.yaml
operations/mimir-tests/test-autoscaling.jsonnet
operations/mimir/autoscaling.libsonnet

[Ruler] Change ruler scale down period from 60s to 600s

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.3.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Helm: release 4.3.1 with fix for CVE-2023-24538

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.3.md
operations/helm/charts/mimir-distributed/CHANGELOG.md

Update release notes and changelog for Helm chart 4.3.1 on main

Helm: merge mimir-distributed-release-4.3 to main

---

pkg/storage/bucket/azure/config.go

I missed to remove this in previous deprecation removal PR: #4793. 

Remove msi-resource flag

---

CHANGELOG.md
docs/sources/mimir/release-notes/v2.6.md

Get updates to changelog and release notes

merge release branch 2.6 to main

---

CHANGELOG.md
packaging/nfpm/mimir/preremove.sh

Backport Packaging: fix preremove script preventing the upgrade #4801

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.2.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Helm: release 4.2.1 with fix for CVE-2023-24538

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.2.md
operations/helm/charts/mimir-distributed/CHANGELOG.md

Update main with the release of 4.2.1 via 4.3

Merge mimir-distributed-release-4.3 to main

---

RELEASE.md

Some improvements on release step from experience releasing mimir-2.8.0-rc0.
- na Tests updated
- na `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Update release.md to clarify the release steps

---

docs/internal/contributing/README.md

Fixes a small typo in the internal contributing docs.

Fix a small typo in the internal contributing docs

---

docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md

Deploying on OpenShift requires some extra steps. This PR documents them in the
"Run Grafana Mimir in production using the Helm chart" article.

helm docs: add OpenShift section

---

docs/sources/mimir/operators-guide/mimir-runbooks/_index.md

Docs: Lowercase anchor

---

docs/sources/mimir/operators-guide/secure/authentication-and-authorization.md

This PR fixes a layout issue on the authentication and authorisation page of the docs.
(none)

Authentication and authorisation docs page: nest remote write configuration sections under top-level remote write section

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile
mimir-build-image/Dockerfile

* Update Go to 1.20.4.
* CHANGELOG.md
* Update build image.
Signed-off-by: Peter Štibraný <pstibrany@gmail.com>
(cherry picked from commit ad3cb5578281a2b0ab4cde716afca62b41ecab62)

Update Go to 1.20.4 (#4902)

---

Makefile
development/mimir-microservices-mode/docker-compose.jsonnet
development/mimir-read-write-mode/docker-compose.jsonnet

Since we have jsonnet files in development folder too, we should format those too. 
Otherwise my editor is trying to format them in unrelated PRs all the time.

Check jsonnet in development folder

---

CHANGELOG.md
docs/sources/mimir/release-notes/v2.6.md

In this PR I'm merging the release-2.6 branch to release-2.7 branch. Please merge this PR using a **merge commit**

Merge release-2.6 to release-2.7

---

CHANGELOG.md
docs/sources/mimir/release-notes/v2.6.md
docs/sources/mimir/release-notes/v2.7.md

In this PR I'm merging the release-2.7 branch to release-2.8 branch. Please merge this PR using a **merge commit**

Merge release-2.7 to release-2.8

---

integration/backward_compatibility.go

Add 2.8.0 to backward compatible test

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Prepare mimir-distributed-4.4.0 changelog

---

docs/sources/mimir/operators-guide/architecture/components/alertmanager.md

Fixes a minor typo in the alertmanager docs.

Docs: Fix minor typo in alert manager docs

---

pkg/api/api.go

This change adds a Prometheus alertmanager link in the Mimir alertmanager UI.

Add a Prometheus alertmanager link in the Mimir alertmanager UI

---

development/README.md

This PR adds a basic README for the mimir dev environments, describing how to configure and run them, what UIs they expose, and how to debug them. The goal is to make getting oriented as a new contributor a bit quicker.

Docs: Add a readme for the Mimir dev environments

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

As in the title. I am not sure if we should create the PR to target mimir-distributed-release-4.4 or whether we should create the PR against main branch. Reviewers can suggest if I should do otherwise.

Update changelog to 4.4.1 because we skip 4.4.0

---

docs/sources/helm-charts/mimir-distributed/release-notes/v4.4.md

Mimir Distributed 4.4 [Release Note](https://github.com/grafana/mimir/blob/1eb3b0f25029f4d44efa1633c90fc95135fed61d/docs/sources/helm-charts/mimir-distributed/release-notes/v4.4.md)

Add mimir-distributed-4.4 release notes

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md

Wait for #4937 to get merged.
Please merge this only once the changes in `mimir-distributed-release-4.4` are good to trigger the release github action. 

Set final release version for mimir-distributed-4.4.1

---

integration/ruler_test.go
pkg/api/api.go
pkg/distributor/query.go
pkg/ingester/ingester.go
pkg/mimir/modules.go
pkg/querier/worker/scheduler_processor.go
pkg/ruler/compat.go
pkg/util/limiter/query_limiter.go

Improvements to various code comments.

Fix various code comments

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/release-notes/v4.4.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml

In this PR I'm merging the mimir-distributed-release-4.4 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge mimir-distributed-release-4.4 to main

---

docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md

Fix broken link in Helm run production

---

pkg/distributor/distributor.go

Fix the doc comment for `distributor.removeLabel` a bit.

distributor: Fix removeLabel doc comment

---

SECURITY.md

* Link to the bug bounty program since Mimir is in scope.
* Update the PGP fingerprint.
(aligned with https://github.com/grafana/grafana/pull/67985)

Docs: Update SECURITY.md

---

docs/sources/mimir/configure/configure-otel-collector.md

This PR updates the name of the page used in the table of contents.
(none)

docs: Use full name for "OpenTelemetry" for OpenTelemetry Collector configuration page table of contents entry

---

.github/workflows/sbom-report.yml
CODEOWNERS

Quick PR to add SBOM report generation on release. We (Security Engineering) have this running in grafana/grafana and grafana/loki. We are planning to expand this to all our OSS Projects. 

sbom workflow add

---

CHANGELOG.md
pkg/ruler/ruler.go
pkg/ruler/ruler_test.go

Backport https://github.com/grafana/mimir/pull/5115 to r239 branch.
N/A

Backport #5115 to r239 branch.

---

pkg/distributor/query.go
pkg/ingester/ingester.go
pkg/storage/tsdb/block/fetcher_test.go
pkg/storegateway/bucket_e2e_test.go

In the continuing saga of "don't assume it is a slice".

Some more uses of labels.EmptyLabels

---

Makefile
operations/mimir-tests/test-autoscaling.jsonnet

This path wasn't validated in CI, and my IDE was trying to reformat a file continuously.

Add operations/mimir-tests to jsonnet manifests

---

docs/sources/mimir/configure/configure-metrics-storage-retention.md
docs/sources/mimir/references/architecture/binary-index-header.md
docs/sources/mimir/references/architecture/bucket-index/index.md
docs/sources/mimir/references/architecture/components/compactor/index.md
docs/sources/mimir/references/architecture/components/store-gateway.md

The PR contains minor updates to the Mimir docs to improve clarity and correctness.

minor updates to docs

---

.github/workflows/issue_and_pr_commands.yml

Chore: Don't run issue_and_pr_commands for dependabot prs

---

CHANGELOG.md
operations/mimir-tests/test-consul-multi-zone-generated.yaml
operations/mimir-tests/test-deployment-mode-migration-generated.yaml
operations/mimir-tests/test-multi-zone-generated.yaml
operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
operations/mimir/images.libsonnet

Update the rollout-operator to the most recent version.
See grafana/rollout-operator#62

Jsonnet: Update rollout-operator to v0.6.0

---

CHANGELOG.md

This adds changelog entries for a bunch of user-facing PRs that didn't previously have one.

Add missing entries for 2.9 to CHANGELOG.md

---

CHANGELOG.md

This cuts the changelog for Mimir 2.9.
Related to #5112

Cut changelog for Mimir 2.9

---

CHANGELOG.md
operations/mimir-tests/test-env-vars-generated.yaml
operations/mimir-tests/test-env-vars.jsonnet
operations/mimir/alertmanager.libsonnet
operations/mimir/compactor.libsonnet
operations/mimir/distributor.libsonnet
operations/mimir/flusher-job-blocks.libsonnet
operations/mimir/ingester.libsonnet
operations/mimir/multi-zone.libsonnet
operations/mimir/overrides-exporter.libsonnet
operations/mimir/querier.libsonnet
operations/mimir/query-frontend.libsonnet
operations/mimir/query-scheduler.libsonnet
operations/mimir/read-write-deployment/read.libsonnet
operations/mimir/ruler-remote-evaluation.libsonnet
operations/mimir/ruler.libsonnet
operations/mimir/store-gateway.libsonnet

This PR adds per-container envmaps to Jsonnet. Using such map helps when configuring env variables at multiple places to prevent conflict, and to keep variables sorted in the output.

Jsonnet: add per-container map for environment variables.

---

.github/workflows/test-build-deploy.yml
Makefile
docs/internal/contributing/how-to-upgrade-golang-version.md
docs/internal/how-to-update-the-build-image.md

This PR backports #5184 to the 2.9 release branch.
(none)

Backport #5184 to release-2.9

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile
mimir-build-image/Dockerfile

This updates go to 1.20.5. 
The changelog entry is under 2.9 because this will be backported to the release branch.
Thanks to @charleskorn for pushing the new build image.
n/a

Update go to 1.20.5

---

.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
CHANGELOG.md
Makefile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile
mimir-build-image/Dockerfile

* Update dockerfiles to go 1.20.5
* Update build image, changelog
* Update go version in github workflows
(cherry picked from commit 45ca724c2b41c442e5730367e7984004a410b69e)
This backports #5185 to the 2.9 release branch.

Backport #5185 to release-2.9

---

ADOPTERS.md

Add SysEleven GmbH to Adopters

Add SysEleven to Adopters

---

CHANGELOG.md
pkg/querier/worker/frontend_processor.go

This PR backports #5199 to v2.9.
#5199

Backport #5199 to 2.9

---

docs/internal/contributing/pooling-buffers-for-grpc-messages.md

This PR adds notes from https://github.com/grafana/mimir/pull/5195#discussion_r1222972725 into a internal document, as suggested by https://github.com/grafana/mimir/pull/5195#discussion_r1224216413.

Write down notes about pooling buffers for grpc marshal/unmarshal.

---

pkg/ingester/client/streaming.go

In discussion with @codesome while working on https://github.com/grafana/mimir/pull/5182, we realised this variable name could be clearer.
(none)

Rename variable to better reflect intention.

---

CHANGELOG.md
operations/mimir-tests/test-autoscaling-generated.yaml
operations/mimir-tests/test-autoscaling.jsonnet
operations/mimir/autoscaling.libsonnet

This PR adds the auto scaler config to the mixin for the Alertmanager. The config has been battle-tested during the last few months at Grafana Labs.

Alertmanager: Add HPA config to jsonnet lib

---

CHANGELOG.md
operations/mimir/autoscaling.libsonnet

Fix missing scope that makes CI fail.
Fixes N/A

autoscaling.libsonnet: fix missing scope

---

operations/helm/charts/mimir-distributed/values.yaml
packaging/nfpm/mimir/runtime_config.yml

In the helm chart values.yaml and nfpm runtime config.

Doc strings: fix some invalid links

---

CHANGELOG.md
cmd/metaconvert/Dockerfile
cmd/mimir-continuous-test/Dockerfile
cmd/mimirtool/Dockerfile
cmd/query-tee/Dockerfile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
development/mimir-monolithic-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile

This base image contains fixes for
- [CVE-2023-1255](https://security.alpinelinux.org/vuln/CVE-2023-1255)
- [CVE-2023-2650](https://security.alpinelinux.org/vuln/CVE-2023-2650)

Update alpine to 3.18.2

---

docs/sources/mimir/tutorials/_index.md
docs/sources/mimir/visualize/grafana.md

Add top-level Visualize data TOC section.

---

CHANGELOG.md
pkg/ruler/manager.go
pkg/ruler/ruler.go

I spent the day investigating an issue in the ruler (root cause not found). I found a couple of missing information which would have been useful, so adding them in this PR:
- Log `syncRules()` start with info level
- Add a metric to track the whole `syncRules()` duration
N/A

Improve ruler observability on syncRules()

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md

Release mimir distributed helm chart 4.5.0
N/A
All prepared in RC.0

helm: release mimir-distributed 4.5.0

---

docs/sources/mimir/get-started/play-with-grafana-mimir/index.md

For reference, see (internal) https://raintank-corp.slack.com/archives/C0559HUERDF/p1687788295744019?thread_ts=1687787931.835929&cid=C0559HUERDF.

Docs: Shorten Play with Mimir in TOC and title

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/release-notes/v4.5.md

Last step of helm chart release 4.5
N/A
N/A

Merge mimir distributed release 4.5 to main

---

docs/sources/mimir/manage/run-production-environment/production-tips/index.md

Docs: Update production tips

---

Makefile
pkg/distributor/distributor.go
pkg/querier/blocks_store_replicated_set_test.go

This PR addresses the suggestion from @pracucci in https://github.com/grafana/mimir/pull/5342#pullrequestreview-1502974502
(none)

Replace use of ring.Read and add linting rule to enforce it's not used

---

pkg/util/limiter/utilization.go

This PR fixes compilaction issue on `main`.

Add missing import

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
operations/mimir-mixin-compiled-baremetal/alerts.yaml
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin/alerts/blocks.libsonnet
pkg/ingester/ingester.go
pkg/ingester/ingester_test.go
pkg/ingester/metrics.go
pkg/ingester/metrics_test.go
pkg/ingester/shipper.go
pkg/ingester/shipper_test.go

Fix MimirIngesterHasNotShippedBlocks alert (#5396)

---

CHANGELOG.md
pkg/util/limiter/utilization.go
pkg/util/limiter/utilization_test.go

Backport #5394 to r245

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-queries.json
operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
operations/mimir-mixin/dashboards/queries.libsonnet

This PR adds a dashboard panel for the metrics introduced in #5316.
(none)

Add 'rejected queries' panel to queries dashboard

---

CHANGELOG.md
pkg/ingester/client/streaming.go

This PR addresses some feedback from @dimitarvdimitrov on #5369: https://github.com/grafana/mimir/pull/5369#discussion_r1255667526
(none)

Remove unnecessary variable

---

docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-helm-chart-4.x-to-5.0.md

Helm-docs: add option of doing nothing in Helm 4.x to 5.0 migration path

---

CHANGELOG.md
docs/sources/mimir/get-started/play-with-grafana-mimir/index.md

This PR Changes the `_index.md` in `play-with-grafana` for correct tutorial directory. 
This PR Fixes tutorial directory prior to #5350

Docs: Change Play with Grafana directory for Get started in README

---

docs/internal/contributing/how-to-write-documentation.md

Fix https://github.com/grafana/mimir/issues/952

Docs: Update references with definitive information

---

docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md

Fixes broken instructions on Getting Started with the Mimir Helm Chart docs page, as described in https://github.com/grafana/mimir/issues/5154.
Attempted to mimic the related instructions in Run Production Environment With Helm page
https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/
Fixes #5154

issues/5154 Docs: Get started with mimir helm: add instructions for manually installing CRDs to enable metamonitoring

---

pkg/util/validation/exporter/exporter.go

This is a follow-up to https://github.com/grafana/mimir/pull/5376 and https://github.com/grafana/mimir/pull/5474. Instead of recomputing list of exported metrics on each `Collect` call (when metrics are collected), we can do it only once when overrides-exporter is initialized, and then reuse the list. This is good enough because configuration with enabled metrics is static and cannot change between `Collect` calls.

overrides-exporter: don't recompute exported metrics on each metrics collection

---

tools/undelete_block_gcs/main.go

This PR adds tool to undelete blocks on GCS.

WIP: undelete block on GCS

---

docs/proposals/query-blocking.md

Add a query blocking feature proposal.
The template used for this proposal is inspired by loki's LIDs: https://github.com/grafana/loki/tree/main/docs/sources/community/lids

Add query blocking proposal

---

docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md

This PR does a similar thing to https://github.com/grafana/mimir/pull/5653 and adds the version of the helm chart to the title. I'm suggesting this change after someone from the community raised that the migration guides are slightly confusingly named and it's difficult to find the migration guide for 3.x -> 4.0.

Docs: update helm 3.x to 4.0 migration guide

---

CHANGELOG.md
tools/querytee/proxy.go
tools/querytee/proxy_backend.go
tools/querytee/proxy_backend_test.go
tools/querytee/proxy_endpoint_test.go

An alternative approach is to always ignore TLS.

query-tee: Add option to skip TLS verification

---

pkg/ingester/activeseries/active_series_test.go

In https://github.com/grafana/mimir/pull/5665 we reduced active series tracker stripes from 512 to 128. Benchmarks didn't show any difference, but I've noticed we don't have a concurrency benchmark leveraging on the stripes, because the existing concurrency benchmark always use the same series, so always touching the same stripe.
In this PR I'm introducing a concurrency test using multiple series. I've compared 512 (before) vs 128 (after) stripes and there's no practical difference. I've run the benchmarks multiple times and always go some variance, sometimes a bit faster, sometimes a bit slower, but IMO due to "disturbance" and not by a real change in performance:
```
goos: darwin
goarch: amd64
pkg: github.com/grafana/mimir/pkg/ingester/activeseries
cpu: Intel(R) Core(TM) i7-9750H CPU @ …
```

Improve active series tracker concurrency benchmark

---

docs/sources/mimir/get-started/play-with-grafana-mimir/index.md

Add aliases for previous location of tutorial within Mimir as well as at https://grafana.com/tutorials/play-with-grafana-mimir/

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/references/configuration-parameters/index.md
pkg/mimir/mimir.go

Mark `shutdown-delay` as advanced rather than experimental

---

.github/dependabot.yml
CHANGELOG.md
Makefile
mimir-build-image/Dockerfile

Dependency: Update go version in Mimir to 1.21.0

---

docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md

to avoid errors on state diffing with large CRDs
Fixes #5550

isses/5550 docs: use kubectl create instead of kubectl apply

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/references/configuration-parameters/index.md
integration/distributor_high_concurrency_test.go
integration/distributor_test.go
pkg/distributor/distributor.go
pkg/mimir/mimir.go
pkg/mimirpb/timeseries.go
pkg/mimirpb/timeseries_test.go

Cherry-pick PR #5798 + PR #5805 into r251.

Cherry-pick PR #5798 and PR #5805 into r251

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/references/configuration-parameters/index.md
integration/distributor_high_concurrency_test.go
integration/distributor_test.go
pkg/distributor/distributor.go
pkg/mimir/mimir.go
pkg/mimirpb/timeseries.go
pkg/mimirpb/timeseries_test.go

This is cherry-pick of PR https://github.com/grafana/mimir/pull/5798 + PR https://github.com/grafana/mimir/pull/5805 onto r250.

Cherry-pick PR #5798 and PR #5805 into r250

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/references/configuration-parameters/index.md
integration/distributor_high_concurrency_test.go
integration/distributor_test.go
pkg/distributor/distributor.go
pkg/mimir/mimir.go
pkg/mimirpb/timeseries.go
pkg/mimirpb/timeseries_test.go

Cherry-pick PR #5798 and PR #5805 into r252.

Update r252 with #5798 and #5805

---

CHANGELOG.md
pkg/ingester/ingester.go
pkg/ingester/ingester_test.go
pkg/ingester/metrics.go
pkg/ingester/metrics_test.go

This updates branch `r252` with PR #5815.

Update r252 with PR 5815

---

CHANGELOG.md

This moves the changelog entry for #5778 from the "Mixin" section to "Grafana Mimir"

Fix changelog entry for PR 5778

---

CHANGELOG.md

Ref: https://github.com/grafana/mimir/issues/5849

Prepare Release 2.10-rc.0 CHANGELOG.md

---

CHANGELOG.md

Ref: https://github.com/grafana/mimir/issues/5849
(cherry picked from commit 0d87de7b6d960330835d64eb284d176ab2c7c3c9)

[release-2.10] Prepare Release 2.10-rc.0 CHANGELOG.md (#5856)

---

CHANGELOG.md

Removes the `main / unreleased` section from the CHANGELOG.md in the release-2.10
Ref: https://github.com/grafana/mimir/issues/5849

Remove unreleased section from release changelog

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/references/configuration-parameters/index.md
pkg/frontend/querymiddleware/roundtrip.go
pkg/util/validation/exporter/exporter.go
pkg/util/validation/exporter/ring.go
pkg/util/validation/limits.go

Removes the experimental mark from some features we now consider stable.
Ref: [Release 2.10](https://github.com/grafana/mimir/issues/5849)

Release 2.10: promote experimental features

---

CHANGELOG.md

Release 2.10: remove empty changelog sections

---

CHANGELOG.md

Changelog entry for #5903, Minio client update

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/references/configuration-parameters/index.md
docs/sources/mimir/release-notes/v2.10.md
docs/sources/mimir/release-notes/v2.9.md
pkg/frontend/querymiddleware/roundtrip.go
pkg/util/validation/exporter/exporter.go
pkg/util/validation/exporter/ring.go
pkg/util/validation/limits.go

In this PR I'm merging the release-2.10 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge release-2.10 to main

---

development/mimir-microservices-mode/goland/querier.run.xml

development: fix querier debug port after third ingester added

---

operations/helm/charts/mimir-distributed/RELEASE.md

clarify mimir-distributed helm chart release schedule
Related to customer question.

Helm: clarify release schedule

---

tools/delete-objects/README.md

Adds a `README` for the `delete-objects` tool.

Add usage doc for delete-objects

---

development/README.md
development/mimir-monolithic-mode/compose-up.sh
development/mimir-monolithic-mode/config/otel-collector-otlp-push-config.yaml
development/mimir-monolithic-mode/config/otel-collector-remote-write-config.yaml
development/mimir-monolithic-mode/docker-compose.yml

Add experimental support for testing otel collector together with Mimir.
For reproducing https://github.com/grafana/mimir/issues/5576
Related to #5576 
- N/A (internal doc updated) Documentation added

dev docker compose: add otel collector with prom remote write

---

packaging/nfpm/nfpm.jsonnet

Parsing the version makes nfpm issue a different filename so our script doesn't find it later.

[release-2.10] nfpm: version_schema=none

---

packaging/nfpm/nfpm.sh

Previous pre-releases failed to correctly move the files, and that went unnoticed. We can check for fails with `set -euo pipefail`.
Also fixed an `for ... ls` shellcheck replacing with globbing, and fixed some typos.
None.

nfpm.sh: improve robustness and nits

---

development/README.md
development/mimir-monolithic-mode/compose-down.sh
development/mimir-monolithic-mode/compose-up.sh
development/mimir-monolithic-mode/config/grafana-agent.river
development/mimir-monolithic-mode/config/otel-collector-otlp-push-config.yaml
development/mimir-monolithic-mode/config/otel-collector-remote-write-config.yaml
development/mimir-monolithic-mode/docker-compose.yml

Allow using profiles to select scrape/agent setup.
Add Grafana Agent flow as possible setup.
Related to #5956

dev docker compose: add Grafana Agent Flow as option

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/enterprise-https-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/large-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/openshift-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/small-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml
operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/compactor/compactor-statefulset.yaml

This PR allow to configure the compactor `podManagementPolicy`
None

Make compactor podManagementPolicy configurable

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Update the changelog to indicate that future PRs are not going into 5.1

Helm: cut release 5.1
