grafana/mimir

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
(cherry picked from commit e22be742e3638ec791a4d1586743d35bf91f8105)
> [release-2.2] Update publishing workflows to use organization secret (#4166)

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
(cherry picked from commit e22be742e3638ec791a4d1586743d35bf91f8105)
> [release-2.3] Update publishing workflows to use organization secret (#4166)

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
(cherry picked from commit e22be742e3638ec791a4d1586743d35bf91f8105)
> [release-2.5] Update publishing workflows to use organization secret (#4166)

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release.yml
Signed-off-by: Jack Baldry [jack.baldry@grafana.com](mailto:jack.baldry@grafana.com)
(cherry picked from commit https://github.com/grafana/mimir/commit/e22be742e3638ec791a4d1586743d35bf91f8105)
> [release-2.4] Update publishing workflows to use organization secret (#4166)

- pkg/mimir/mimir.go
- pkg/mimir/modules.go
Changes #4110 added a constructor to build the PrometheusCodec, using a prometheus.Registerer to register some metrics.
This means that downstream projects extending Mimir (GEM) can't use the PrometheusCodec properly anymore, since if they call the constructor they would try to register the metrics again.
This exposes the created PrometheusCodec in Mimir's root datastructure, just like QueryTripperware is exposed.
None.
> Expose querymiddleware.Codec instance

- CHANGELOG.md
- tools/tsdb-chunks/main.go
- tools/tsdb-chunks/main_test.go
- tools/tsdb-index-health/main.go
- tools/tsdb-index-health/main_test.go
- tools/tsdb-print-chunk/main.go
- tools/tsdb-print-chunk/main_test.go
This PR updates the following tools to deal with native histograms and also adds tests:
- tsdb-chunks
- tsdb-index-health
- tsdb-print-chunk
Fixes:
- https://github.com/grafana/mimir/issues/3944
- https://github.com/grafana/mimir/issues/3947
- https://github.com/grafana/mimir/issues/3949
> Update tooling for native histograms

- CHANGELOG.md
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_chunk_reader.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_chunks_test.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
This is a continuation of https://github.com/grafana/mimir/pull/4163 which upstreams another part of https://github.com/grafana/mimir/pull/3968
Currently all `seriesChunkRefs` have a slice of chunk refs. Each chunk ref contains the ID of the block to which it belongs and its chunk ref. The chunk ref is 64 bits, the first 32 of which contain the sequence number of its segment file and the last 32 bites contain the offset in this file. At the `loadingSeriesChunksSetIterator` we can have many chunks from different segment files or blocks in the same slice of `seriesChunkRefs.chunks`.
The changes in this PR add a level of separation for chunks. Now a `seriesChunkRefs` contains a slice of `seriesChunkRefsRange`. Each range belongs …
> Store-gateway: add separation of chunks into ranges

- CHANGELOG.md
- pkg/ingester/ingester_test.go
- pkg/ingester/user_tsdb.go
This adds a call to `db.CompactOOOHead` as part of `userDb.compactHead`, which means the OOO head is also compacted apart from the in-order head. As a consequence, compactions caused by idling DBs or forced head compactions will now also compact the OOO head, see code below:
https://github.com/grafana/mimir/blob/6852e9442b5f13c065e9f7818c727e72e9fcd774/pkg/ingester/ingester.go#L2196-L2203
Fixes  https://github.com/grafana/mimir/issues/4160
> Compact userTSDB's OOO head when compacting head

- pkg/frontend/querymiddleware/astmapper/astmapper.go
- pkg/frontend/querymiddleware/astmapper/sharding.go
ASTExprMapper was mapping every AST subtree elements except for the VectorSelector which is an Expr leaf of MatrixSelector, which required ExprMappers to handle them separately. This simplifies that.
None
> `ASTExprMapper` maps `MatrixSelector.VectorSelector`

- pkg/mimir/mimir.go
In recent versions of dskit we differentiate between "invisible" and "targetable" modules.
With this change we decide whether a module should be allowed to run based on if it is "targetable".
By default all "invisible" modules are not "targetable".
> allow targetable invisible modules to start

- CHANGELOG.md
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
In the mixin, change CPU/memory based scaling metric panels into showing desired replicas.
The same change is done for queriers in #3962.
Distributor panels after changes in this PR:
> Mixin: Change CPU/memory based scaling metric panels into showing desired replicas

- operations/helm/charts/mimir-distributed/CHANGELOG.md
This cuts the changelog for the Helm 4.1 release.
My next steps are to
* make a new branch `mimir-distributed-release-4.1` as of `main` after merging _this_ PR
* write release notes for helm (another PR)
* trigger a release for helm (another PR)
> Helm: cut changelog for 4.1 release

- CHANGELOG.md
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Fix CPU/memory based auto-scaling panels so labels differentiate between targets, the _Min_ label is dropped to reduce the amount of information in a single panel (same change was done for queriers in #3692).
I've tested the changes locally (`make mixin-serve`).
Based on #3962.
Fixes #4134.
> Mixin: Make CPU/memory based auto-scaling panel labels differentiate between targets

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/values.yaml
This updates
* the chart version, app version, home version
* image version of smoke_test, continuous_test, mimir, and GEM
* since the GEM release is slightly delayed, this release uses GEM version `2.5.1`
* all the other images use `2.6.0`
* Helm README
* Helm CHANGELOG with the actual images used
> Helm: do 4.1.0 release

- .github/workflows/publish-technical-documentation-release-helm-charts.yml
Our docs release didn't trigger for the 4.1 tag, so we're also adding
matching by branch name.
> Docs: Trigger helm docs release for branches too

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/user_tsdb.go
When ingester cannot do shipping or force-compaction due to TSDB being in unexpected state, current state of TSDB is now logged.
This is to better understand why the operation could not be performed.
> Log state of TSDB when ingester skips shipping or force-compaction

- pkg/storage/tsdb/index_cache.go
- pkg/storegateway/indexcache/remote.go
- pkg/storegateway/indexcache/remote_test.go
Rename the Memcached backend for the store-gateway index-cache since it's not Memcached specific and works with any dskit RemoteCacheClient.
See #4236
> Rename Memcached backend for index-cache

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/nginx-configmap.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
This adds configuration options to override the NGINX error log level and to optionally disable the NGINX access log since the default options can create a large volume of logs.
> Helm: add configuration options to override NGINX access and error logs

- pkg/api/api.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This moves the distributor push wrappers from the API configuration into the distributor configuration.
This move provides the advantage that now the push wrappers only must be initialized before the distributor, previously they had to be initialized before the API, which created dependency problems for external middlewares
Furthermore, it allows for multiple push wrappers to be added, instead of only a single one.
> move distributor push wrapper into distributor config

- CHANGELOG.md
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/ruler.libsonnet
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-autoscaling.jsonnet
- operations/mimir/autoscaling.libsonnet
Add query-frontend and ruler-query-frontend auto-scaling support to Jsonnet library, and corresponding panels to mixin.
> Jsonnet: Add (ruler-)query-frontend auto-scaling support

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-query-scheduler-memberlist-ring-and-ruler-remote-evaluation-generated.yaml
- operations/mimir-tests/test-ruler-remote-evaluation-generated.yaml
- operations/mimir-tests/test-ruler-remote-evaluation-migration-generated.yaml
- operations/mimir/ruler-remote-evaluation.libsonnet
This changes the configuration for `ruler-query-frontend` replicas such that the results cache configuration is present. Results caching itself is still disabled.
This is needed because the results cache is reused to store cardinality estimates (https://github.com/grafana/mimir/issues/4108).
#4108
> Configure results cache for ruler-query-frontend

- CHANGELOG.md
- tools/querytee/proxy.go
- tools/querytee/proxy_endpoint.go
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR contains a number of small changes to `query-tee`:
* Increases the default read timeout in `query-tee` to 150s, to accommodate the default querier and query frontend timeout of 120s
* Improves the error message logged when a request fails (eg. due to a timeout or DNS resolution issue) when comparing two backends
Currently, when an error occurs, we log a message like "skipped comparison of response because we got status code 0 from preferred backend's response", which is misleading (we didn't get a status code at all from the backend) and unhelpful (we don't log the error). With this change, we'll log the error and not mention anything about status codes.
* Changes the comparison behaviour when a response contains an error
Currently, if either response contains an error, we …
> query-tee improvements

- CHANGELOG.md
- docs/sources/mimir/operators-guide/configure/configure-object-storage-backend.md
Fixes documentation where storage config examples for azure and swift were not indented sufficiently.
No issue found for this problem.
> Fix documentation backend config indentation

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- docs/sources/mimir/operators-guide/architecture/query-sharding/index.md
- docs/sources/mimir/reference-configuration-parameters/index.md
- pkg/frontend/querymiddleware/roundtrip.go
This PR changes the way the cache client for the query-frontend is initialised for cardinality-based query sharding so that enabling result caching is not required any more.
It also aligns mismatched names between CLI flag and yaml config.
Part of #4108.
> Query-frontend: do not require result caching to be enabled for cardinality estimation, align flag names

- CHANGELOG.md
- tools/querytee/proxy_endpoint.go
Before this change, if a query request uses a HTTP POST and includes parameters in the request body, rather than as URL query parameters, query-tee would not log them when response comparison fails.
This change ensures we log the parameters regardless of whether they're in the URL or in the request body.
(none)
> query-tee: log query parameters from POSTed query requests when responses differ

- CHANGELOG.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin/alerts/alerts.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
In preparation for Redis support, Memcached specific cache metrics have been renamed and a "backend" label added (denoting Redis or Memcached).
See #4236
> Update dashboards and alerts for new cache metric names

- integration/query_frontend_test.go
- pkg/frontend/querymiddleware/codec_protobuf.go
- pkg/frontend/querymiddleware/codec_protobuf_test.go
This PR adds support for decoding native histograms in the new internal query result payload format in the query frontend. 
(Queriers already support encoding native histograms in the new format, this was added in https://github.com/grafana/mimir/pull/4153.)
I'd suggest reviewing each commit individually, as a refactoring step makes the overall diff difficult to follow.
I haven't added a changelog entry as I assume this will be covered by a single changelog entry when we merge native histogram support into `main`.
> Native histograms: add support for new internal query result payload format

- docs/sources/helm-charts/mimir-distributed/release-notes/v4.1.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v4.2.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
* Moves the changelog entry for #4230 to the correct section of the Helm chart changelog
* Adds release notes for v4.2 of the Helm chart
* Cherry picks https://github.com/grafana/mimir/pull/4220 to get this onto `main`.
Once this is merged, I'll then create a second PR to release v4.2.
(none)
> Prepare for v4.2 of Helm chart

- CHANGELOG.md
- pkg/ingester/ingester_test.go
- pkg/ingester/shipper.go
- pkg/ingester/shipper_test.go
This fixes a bug where the `OutOfOrderExternalLabel` was being added to all blocks instead of the ones coming
from OOO data, when the feature flag was enabled. This is a recent feature, introduced here: https://github.com/grafana/mimir/pull/4182.
There was a small typo in the shipper tests that prevented this bug to be caught.
> Ingester: fix OOO blocks labelling

- integration/querier_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
When I read "failed because some blocks were not queried", I wonder why were they not queried? It isn't clear to me what went wrong.
We explain in the [docs](https://github.com/grafana/mimir/blob/8fb2b79bcddb92b9a31f6db7a19390fae34d547c/docs/sources/mimir/operators-guide/mimir-runbooks/_index.md#L1677):
> This error occurs when the querier is unable to fetch some of the expected blocks after multiple retries and connections to different store-gateways.
So I suggest "failed to fetch some blocks" covers this and is easier to understand. The unique code `err-mimir-store-consistency-check-failed` lets the admin find the right point in the docs to read more.
- NA `CHANGELOG.md` updated - I don't think it is worth announcing this change.
> querier: simplify error message from block store consistency check

- pkg/ingester/ingester.go
Function `appendMetadata` was only ever called once; eliding it allows the call to `getOrCreateUserMetadata` to be hoisted out of the loop and save locking on every series.
The call to `GetMetricFamilyName` checked if the input was nil, which probably won't happen, but if it did we would rather ignore that input than store metadata under the metric name `""`.
- NA `CHANGELOG.md` updated - not user-visible
> ingester: elide two function calls in pushMetadata

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/nginx/_helpers.tpl
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/gateway/gateway-v2-hpa.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-v2-hpa.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-v2-hpa.yaml
This follows helm recommendation. The best practice is to upgrade releases using deprecated API versions to supported API versions, prior to upgrading to a kubernetes cluster that removes those API versions.
See https://helm.sh/docs/topics/kubernetes_apis/ for reference.
None
> Helm: relax HPA v2 version check to allow Kubernetes 1.23

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/README.md.gotmpl
- operations/helm/charts/mimir-distributed/values.yaml
Releases version 4.2.0 of the Helm chart, which includes GEM 2.6.0.
This is my first time releasing the Helm chart, so I'm not 100% clear if merging this to `main` is the right way to do this.
(none)
> Helm chart: do 4.2.0 release

- .github/workflows/compare-helm-with-jsonnet.yml
- .github/workflows/helm-ci.yml
- .github/workflows/issue_and_pr_commands.yml
- .github/workflows/test-build-deploy.yml
This makes the version of `actions/checkout` consistent across all jobs, and fixes [the deploy job](https://github.com/grafana/mimir/actions/runs/4278441487/jobs/7448351606), which is currently broken.
This issue was triggered as a result of upgrading Git in #4266, which brings in the change described in https://github.blog/2022-04-12-git-security-vulnerability-announced/.
#4266
> Bump `actions/checkout` in GitHub Actions workflows and fix broken deploy job

- .github/workflows/publish-technical-documentation-next.yml
Needs to match the publish-next-mimir secret which is centrally managed and rotated.
@osg-grafana, this fixes the pipeline failure you saw in https://github.com/grafana/mimir/actions/runs/4255598576/jobs/7403430101
> Fix publish-next-mimir-distributed PAT secret

- .github/workflows/publish-technical-documentation-release-helm-charts.yml
- docs/sources/helm-charts/mimir-distributed/release-notes/v4.2.md
Fix wrong syntax in .github/workflows/publish-technical-documentation-release-helm-charts.yml
Fix typo in 4.2 release note
N/A
> Helm: fix documentation release action and fix typo

- CHANGELOG.md
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
The `ruler-query-scheduler` queue size panel on the Tenants dashboard was empty because the query selected for `ruler-query-frontend` rather than `ruler-query-scheduler`.
Fixes #n/a
> Use ruler-query-scheduler metrics for queue length

- pkg/mimirtool/analyze/grafana.go
- pkg/mimirtool/commands/analyse_grafana_test.go
Reduce allocations in `ParseMetricsInBoard` by moving two regexps at pkg level and pre-allocating slices where possible.
To test the changes, I've copied an existing test into a benchmark.
Tested with:
`go test -run=^$ -bench=. -count=5 ./pkg/mimirtool/commands`
Benchmark comparison:
```
name                   old time/op    new time/op    delta
ParseMetricsInBoard-8    86.2µs ± 0%    80.5µs ± 0%   -6.57%  (p=0.008 n=5+5)
name                   old alloc/op   new alloc/op   delta
ParseMetricsInBoard-8    79.2kB ± 0%    67.6kB ± 0%  -14.72%  (p=0.008 n=5+5)
name                   old allocs/op  new allocs/op  delta
ParseMetricsInBoard-8     1.09k ± 0%     1.00k ± 0%   -7.82%  (p=0.008 n=5+5)
```
n.a.
> Mimirtool: reduce allocations in `ParseMetricsInBoard`.

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
This PR fixes #4310 delegating `cortex_ingester_memory_series` metrics tracking to TSDB. The reason why it fixes #4310 is because we don't track the per-TSDB registerer until after `tsdb.Open()` returned, so the spike during the WAL replay is not accounted. This also makes `cortex_ingester_memory_series` consistent with `cortex_ingester_memory_series_created_total` and `cortex_ingester_memory_series_removed_total` metrics.
Fixes #4310
> Fix cortex_ingester_memory_series metric tracking at startup

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/operators-guide/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/gateway_test.go
Since we're about to cut Mimir 2.7, I would like to enable the streaming store-gateway by default. The default batch size is 5000, the same value we run at Grafana Labs.
A couple of tests have changed because the streaming store-gateway implementation doesn't deduplicate chunks and doesn't have any optimization assuming chunks are in order.
N/A
> Enable streaming store-gateway by default

- .github/workflows/test-build-deploy.yml
GitHub has deprecated the use of `set-output` and `save-state` for security reasons, and will disable them in May ([source](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)). This affects the following actions that we use:
* `docker/setup-buildx-action@v1`
* `docker/setup-qemu-action@v1`
* `azure/setup-helm@v1`
* `actions/download-artifact@v2`
GitHub has also deprecated the use of Node.js v12-based actions ([source](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)), which for us only affects `upload-artifact@v2`.
This PR upgrades the actions we use that rely on these deprecated features.
(none)
- [n/a] `CHANGELOG.md` …
> Upgrade actions in GitHub Actions workflows to avoid deprecated features

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/ci/offline/gateway-enterprise-values.yaml
- operations/helm/charts/mimir-distributed/ci/offline/gateway-nginx-values.yaml
- operations/helm/charts/mimir-distributed/templates/nginx/_helpers.tpl
- operations/helm/scripts/build.sh
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/gateway/gateway-v2beta1-hpa.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/ingester/ingester-pdb.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/store-gateway/store-gateway-pdb.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-v2beta1-hpa.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/ingester/ingester-pdb.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/store-gateway/store-gateway-pdb.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/ingester/ingester-pdb.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/store-gateway/store-gateway-pdb.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/ingester/ingester-pdb.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/store-gateway/store-gateway-pdb.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-v2-hpa.yaml
**Helm: fix Kubernetes override for nginx HPA**
The template did not take into account the override "kubeVersionOverride".  Fix by using the mimir template implemented for this reason.
**Helm: fix missing Kubernetes version overrides in tests**
The golden record tests need a fixed version because helm uses the version
of the default context and can produce different results between
contributor's machine and the CI environment.
Add logic to test build to inject the minimal version if not found in the
values file. Mainly because we cannot have a version override in the
small and large values files.
Related to #4285 
> Helm: nginx HPA and tests kubeversion fixes

- .github/workflows/test-build-deploy.yml
Same as #4343: GitHub has deprecated the use of Node.js v12-based actions ([source](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)).
v2 of `actions/setup-go` uses Node.js v12, whereas v3 uses a supported version.
(none)
> Bump actions/setup-go to v3 to resolve Node.js 12 deprecation warning.

- pkg/ingester/ingester_test.go
This PR improves a flaky test: `TestIngesterWithShippingDisabledDeletesBlocksOnlyAfterRetentionExpires` in `pkg/ingester`.
This test fails for me ~50% of the time when running `go test -count=1 ./...` from the root of this repository.
The change here doesn't fix the root cause of the problem (the test races to make an assertion before the retention period expires), but makes it significantly less likely to occur.
See #4198 for an example of a test failure reported by a community member. The community member suspected the failure was due to running on an IBM Power machine, but I have also regularly experienced this test flaking on my ARM-based MacBook.
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, …
> Improve flaky `TestIngesterWithShippingDisabledDeletesBlocksOnlyAfterRetentionExpires`

- CHANGELOG.md
- operations/mimir/shuffle-sharding.libsonnet
The default shard size is configured in `$._config.shuffle_sharding`. Due to how our user class limits work, the default is also considered being the minimum, because user class limits are meant to increase limits. For this reason, in case someone increase the default shard sizes, I propose to honor them as minimum values when applying the upper classes limits.
N/A
> Jsonnet: honor the minimum shard size configured

- CHANGELOG.md
In #3411 I included a changelog entry for Mimirtool, but since it was a change in Mimir it's not really necessary. I originally added it to prevent confusion, but I could see it adding more as well.
Context: https://github.com/grafana/mimir/pull/3411#discussion_r1124206479
> Remove block validation mimirtool changelog entry

- pkg/frontend/querymiddleware/querysharding_test_utils_test.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/querier/matrix.go
- pkg/storage/chunk/chunk.go
- pkg/storage/series/series_set.go
- pkg/storage/series/series_set_test.go
- pkg/util/chunkcompat/compat.go
- pkg/util/modelutil/merger.go
- pkg/util/modelutil/merger_test.go
Main aim was to sync `pkg/storage` from sparsehistogram branch. Since it changes some function signature, I pulled in those changes from sparsehistogram branch as well.
> Support histograms in pkg/storage and update other breakages

- pkg/storegateway/bucket_test.go
- pkg/storegateway/testhelper/testhelper.go
- pkg/util/merger.go
- pkg/util/merger_test.go
- tools/tsdb-chunks/main_test.go
- tools/tsdb-index-health/main_test.go
- tools/tsdb-print-chunk/main_test.go
These are some minor changes in the `sparsehistogram` branch.
> Sync small miscellaneous changes from sparsehistogram branch

- CHANGELOG.md
- operations/mimir/query-sharding.libsonnet
We set `query_sharding_total_shards: 8` for all plans `big_user` and larger, but we were missing settings for the new `user_24M` and `user_32M`.
> Add query sharding settings for 24M and 32M plans

- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
Syncs ruler changes from `sparsehistogram` branch.
> Support native histograms in pkg/ruler

- operations/mimir-rules-action/entrypoint.sh
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`set-output` will stop working on June 1st and is currently warning
**This was tested on our internal workflow**
> `mimir-rules-action`: `set-output` is deprecated

- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
A proposal of an alternative approach to https://github.com/grafana/mimir/pull/4395
This allows extensions being complex types, where _complex_ means _not map[string]interface{} but a properly defined struct{}_
> Limits with Extensions

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/operators-guide/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/mimir/mimir.go
- pkg/querier/blocks_store_queryable.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/config_test.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/gateway_test.go
- pkg/util/fieldcategory/overrides.go
- pkg/util/flags.go
- pkg/util/usage/usage.go
As proposed in https://github.com/grafana/mimir/issues/4365, in this PR I'm deprecating the consistency delay feature. We're just announcing the deprecation, and then we'll remove it in 2 releases time.
In this PR:
- Announce it in CHANGELOG and doc
- Log a warn and track the metric `deprecated_flags_inuse_total` if you're setting the consistency delay
I haven't followed a path similar to `flagext.DeprecatedFlag` because it would just apply to people using CLI flags and not YAML config. An alternative could have been using a custom data type for deprecated config, but looks overkilled to me, while a simple check in `Validate()` serves the same purpose.
Part of #4365
> Deprecate consistency delay config option

- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
The normal workflow would look like:
var getter = validation.MustRegisterExtension[Ext]("ext")
// ...
if limits := getter(tenantLimits.ByUserID(id)); limits != nil {
// ...
}
However, validation.TenantLimits() may return nil tenant limits from ByUserID(). In order to avoid having to check that in every caller, we can just support nil value in the getter we create.
> Make extensions getter work with nil *Limits

- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
We now require the extension types to provide their default value through `Default() E` method.
This also means that all Limits have all extensions now.
Fixes nothing, superesedes https://github.com/grafana/mimir/pull/4417
> Limits extensions with default values

- CHANGELOG.md
- operations/mimir/alertmanager.libsonnet
- operations/mimir/config.libsonnet
This PR adds a `alertmanager_data_disk_size` and `alertmanager_data_disk_class` configuration option
> add am pvc config options

- CHANGELOG.md
The ephemeral storage has been removed, so we should remove any related CHANGELOG entry from the "unreleased" section. Then this PR will be cherry-picked in the release 2.7 branch (@aldernero).
N/A
> Cleanup ephemeral storage entries from CHANGELOG

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- go.mod
- integration/ruler_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_json.go
- pkg/frontend/querymiddleware/codec_json_test.go
- pkg/frontend/querymiddleware/codec_protobuf.go
- pkg/frontend/querymiddleware/codec_protobuf_test.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/transport/handler.go
- pkg/mimir/modules.go
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_decoder.go
- pkg/ruler/remotequerier_test.go
- pkg/ruler/ruler.go
This PR adds support for decoding the new internal query result payload format in the ruler, and encoding it in the query-frontend to send to rulers.
> New internal query result payload format: add support for remote rule evaluation path

- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/util/validation/limits.go
This PR addresses comment https://github.com/grafana/mimir/pull/4385#discussion_r1126898542 from PR review. `OutOfOrderTimeWindow` was the only method in `validation/limits.go` returning `model.Duration` instead of `time.Duration`.
> Return time.Duration from limits, instead of model.Duration

- CHANGELOG.md
- pkg/querier/remote_read.go
- pkg/querier/remote_read_test.go
This PR adds a reset to `frameBytesLeft` when streaming chunked read responses. Before this change, `streamChunkedReadResponses` would start writing one chunk per frame after the initial frame.
> Reset frameBytesLeft when cutting a frame in streamChunkedReadResponses

- docs/sources/mimir/operators-guide/configure/about-versioning.md
This PR adds the new internal query result payload format to the experimental features list.
As part of this feature (covering the querier -> query-frontend path) is included in v2.7, once this is merged I'll also backport the relevant part to the 2.7 release as well.
#4104
> Add protobuf internal query result payload format to experimental features list.

- CHANGELOG.md
- go.mod
- go.sum
- pkg/ingester/activeseries/matchers_test.go
- pkg/ingester/client/compat_test.go
- pkg/storage/sharding/label_test.go
- vendor/github.com/prometheus/prometheus/model/labels/regexp.go
- vendor/github.com/prometheus/prometheus/rules/alerting.go
- vendor/modules.txt
Updating the vendored mimir-prometheus to get two changes:
1. https://github.com/grafana/mimir-prometheus/pull/448
2. https://github.com/grafana/mimir-prometheus/pull/447
Fixes #4118
> Update vendored mimir-prometheus

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/operators-guide/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_ring.go
- pkg/ingester/ingester_ring_test.go
- pkg/mimir/mimir.go
> Deprecate readiness-check-ring-health config option

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/operators-guide/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/util/validation/limits.go
This PR replaces hard-coded 7 days (and 10 minutes for queries within OOO window) TTL for results cache, and makes these values configurable per tenant. This allows us to use lower values for users who want to use backfill feature.
Fixes (partially) https://github.com/grafana/mimir/issues/4383
> Make results cache TTL configurable and settable per tenant

- go.mod
- go.sum
- vendor/github.com/hashicorp/go-hclog/README.md
- vendor/github.com/hashicorp/go-hclog/colorize_unix.go
- vendor/github.com/hashicorp/go-hclog/colorize_windows.go
- vendor/github.com/hashicorp/go-hclog/exclude.go
- vendor/github.com/hashicorp/go-hclog/global.go
- vendor/github.com/hashicorp/go-hclog/interceptlogger.go
- vendor/github.com/hashicorp/go-hclog/intlogger.go
- vendor/github.com/hashicorp/go-hclog/logger.go
- vendor/github.com/hashicorp/go-hclog/stdlog.go
- vendor/github.com/hashicorp/go-immutable-radix/CHANGELOG.md
- vendor/github.com/hashicorp/go-immutable-radix/iter.go
- vendor/github.com/hashicorp/go-immutable-radix/node.go
- vendor/github.com/hashicorp/go-immutable-radix/raw_iter.go
- vendor/github.com/hashicorp/go-immutable-radix/reverse_iter.go
- vendor/modules.txt
Removing the `replace` directives for `hashicorp/go-immutable-radix` and `hashicorp/go-hclog` which are pinned to versions dating back to 2020. 
Affected packages:
```
go mod why github.com/hashicorp/go-immutable-radix
github.com/grafana/mimir/pkg/api
github.com/grafana/dskit/kv/memberlist
github.com/armon/go-metrics
github.com/hashicorp/go-immutable-radix
```
```
go mod why github.com/hashicorp/go-hclog
github.com/grafana/mimir/tools/doc-generator/parse
github.com/grafana/dskit/kv/consul
github.com/hashicorp/consul/api
github.com/hashicorp/go-hclog
```
> Remove replace directives in go.mod for hashicorp libs

- CHANGELOG.md
- pkg/querier/remote_read.go
- pkg/querier/remote_read_test.go
Enables Mimir's Prometheus remote read compatible API
https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#remote-read
to return native histogram samples.
Related to #3478
> Native histograms support in querier remote read

- integration/backward_compatibility.go
- integration/e2emimir/services.go
Enable ingestion of native histograms in integration tests
And remove flag via the mapper for backwards compatibility.
In preparation for incoming new e2e tests.
Related to: #3478 
> Enable ingestion of native histograms in integration tests

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/metrics.go
This PR introduces a new metrics, `cortex_ingester_tsdb_open_duration_second`, that measures the total time it takes to open all existing TSDBs. This time also includes the TSDBs WAL replay duration.
Moreover, the `cortex_ingester_tsdb_wal_replay_duration_seconds` metrics has been removed.
Part of https://github.com/grafana/mimir-squad/issues/1040
> Add `cortex_ingester_tsdb_open_duration_second` metrics

- pkg/querier/iterators/chunk_iterator.go
- pkg/querier/iterators/chunk_iterator_test.go
This PR makes `iterator.chunkIterator` consider itself exhausted after seeking past the end of its chunk. Before, the iterator would actually still be pointing at whatever sample it was pointed at before the call to `Seek`.
Fixes https://github.com/grafana/mimir/issues/4415
> Exhaust iterators.chunkIterator after seek shortcut

- integration/querier_test.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
This PR allows query sharding with native histograms. I also added the `-ingester.native-histograms-ingestion-enable-=true` to an existing integration test to make it fail without this change.
Fixes https://github.com/grafana/mimir/issues/3992
> Allow query sharding with native histograms

- pkg/mimirpb/compat.go
They add a performance penalty on the hot path and not flexible enough for tests. Ended up using separate functions on hot path and interface{} in tests.
> Remove generics from native histograms code

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/metamonitoring/kube-state-metrics-servmon.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/kube-state-metrics-servmon.yaml
Fix metricRelabelings for kube state monitor
The current version filters out statefulsets, since those metrics include a pod name that is of the ksm itself.
Fix is to check all values in the concatenated labels for a match.
Fixes N/A
> Helm: fix kube state metrics relabel

- CHANGELOG.md
- tools/tsdb-index/main.go
If any equal matcher is used, we can use it for getting postings, and massively speed up iteration of index.
> tsdb-index: use equal matcher to speed up listing

- pkg/frontend/querymiddleware/results_cache_test.go
This PR modifies `mkExtent` helper function to set 0 query time, and not use current time.
PR #4439 added `QueryTime` field to cached extents. Originally PR considered extents with `QueryTime=0` as too old, but that has changed before merging the PR. So using 0 is safe, and there are other tests that cover non-zero query times.
> Fix flaky TestSplitAndCacheMiddleware_StoreAndFetchCacheExtents test.

- docs/sources/mimir/references/http-api/index.md
Seems that it should start with /docs/
Ref: https://github.com/grafana/mimir/pull/4328
> Fix aliases for http reference docs

- operations/helm/charts/mimir-distributed/RELEASE.md
First cut the version in changelog then release, not the other way around.
Internal process improvement.
> Helm: fix order of steps in Helm release

- integration/backward_compatibility.go
Adds Mimir 2.7.1 to the list of backwards compatibility tests.
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
> Add release 2.7.1 to backwards compatibility integration test

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/openshift-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/tokengen/tokengen-job.yaml
Include mimir.PodAnnotations on the tokengen Job. This seems to have been an oversight since https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L66 mentions that this field is used for tokegen job but hasn't been wired up correctly.
```
```
> Include podAnnotations on tokengen job

- CHANGELOG.md
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin/dashboards/queries.libsonnet
The two panels for data fetched/sec and touched/sec currently show the
number of series, chunks or posting lists that the store-gateway
processes per second. They are also put on the same scale, but a single
posting list can have a lot bigger impact on query performance than a
single chunk.
Usually query performance and store-gateway resource usage are more
closely tied to the number of bytes processed per second rather than the
number of items processed.
So this PR makes a change to display the number of bytes per sec for
postings, chunks and series (both touched and fetched) instead of the
number of items.
> Queries dashboard: display store-gateway bytes/sec instead of items/sec

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- integration/e2emimir/client.go
- integration/query_frontend_test.go
- pkg/frontend/querymiddleware/roundtrip.go
This PR makes two related changes:
* it makes the protobuf format the default format for the query path
* it removes the experimental status on the `-query-frontend.query-result-response-format` flag
Note that this does not change the default or experimental status of the equivalent flag for the ruler-query-frontend -> ruler path, `-ruler.query-frontend.query-result-response-format`.
> Default to requesting protobuf format on query path, and remove experimental status on flag

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/ingester/ingester.go
- pkg/storage/tsdb/config.go
- vendor/github.com/prometheus/prometheus/tsdb/block.go
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/modules.txt
While investigating the performance issues in the Mimir ingesters, due to some customer queries like `label=~".*"` where the postings cache could significantly help but it doesn't help as much as I expected, I just realised that the settings I tuned for the postings cache in Mimir only apply to the TSDB head, but not the TSDB compacted blocks the customer queries also touch. So I've opened (and merged) a [PR in mimir-prometheus](https://github.com/grafana/mimir-prometheus/pull/458) to let the "postings for matchers" cache to be configurable for blocks too.
In this PR I'm updating mimir-prometheus and exposing the config (experimental).
N/A
> Add configuration options to configure the "postings for matchers" cache of each compacted block queried from ingesters

- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin/dashboards/queries.libsonnet
Align the panel headings here so it's clear they all refer to the same "streaming enabled" thing:
I've checked the first two panels in the row - they both use the `cortex_bucket_store_series_request_stage_duration_seconds_(bucket|sum|count)` metric
None
- ~~Tests updated~~
- ~~Documentation added~~
- ~~`CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`~~
This change is so small I don't think any of these are needed, but let me know if they are. I wasn't sure about the Changelog.
> Add "streaming enabled" to avg latency panel

- docs/sources/mimir/references/configuration-parameters/index.md
- docs/sources/mimir/references/configuration-parameters/index.template
The alias is relative to the URL path, not the filesystem path.
As in docs/sources/mimir/references/configuration-parameters/index.md is one step removed from the root, since it's rendered as /references/configuration-parameters, not directly as index.md which is two steps down in the filesystem.
> Docs: fix again broken reference configuration aliases

- CHANGELOG.md
- cmd/metaconvert/Dockerfile
- cmd/mimir-continuous-test/Dockerfile
- cmd/mimir/Dockerfile
- cmd/mimirtool/Dockerfile
- cmd/query-tee/Dockerfile
This PR populates the `/usr/share/zoneinfo` by installing timezones using `apk` on alpine.
Fixes #4582
Allows use of timezones for alertmanager.
> feat: add tzdata to alpine dockerfiles

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/compactor/block_upload.go
- pkg/compactor/block_upload_test.go
- pkg/compactor/blocks_cleaner_test.go
- pkg/compactor/compactor.go
- pkg/util/validation/limits.go
This PR makes validation of uploaded blocks configurable on a per tenant basis. This brings it in line with other block upload parameters like block upload enabled, and chunk checking during validation.
> Make block upload validation configurable per tenant

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/mimir/modules.go
- pkg/ruler/api_test.go
- pkg/ruler/manager.go
- pkg/ruler/tenant_federation.go
This PR bundles two changes because they are related and small
* reject creating federated rule groups when ruler tenant federation is
disabled. Currently, the rule groups would be silently ignored during
bucket syncs. This made the UX around creating federated rules confusing
because there was no feedback as to why the groups aren't evaluating
* log an info line on each sync when a federated rule group is skipped
because the feature is disabled
Technically the first is a breaking change, but I think no one would
depend on this behaviour.
> Ruler: validation and logging with disabled tenant federation

- CHANGELOG.md
- packaging/nfpm/nfpm.jsonnet
When running Mimir installed  with the packages we use apt/dnf. To correctly configure systemd with use  either `/etc/default/mimir` or `/etc/sysconfig/mimir`. Both files allow users to define environment variables used by Mimir when the process is started by systemd. It is generally used to define the loglevel or the path of the configuration file. While upgrading apt/dnf overwrite those files as they are not flagged as `config` with `noreplace`.
> Prevent package installation to overwrite configuration file

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
We collect the number of TSDB index bytes fetched as part of executing a query and include it in the query logs. However, we don't emit it as a metric even though we do this with other query statistics. This PR fixes that so that we do emit the number of index bytes fetched as a per-tenant metric.
N/A
> Emit TSDB index bytes fetched as metric

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/util/globalerror/errors.go
- pkg/util/validation/errors.go
- pkg/util/validation/limits.go
Add a new experimental limit to enforce the size of a query is under a certain number of bytes. This limit is enforced in the query-frontend and supports queries for multiple tenants. In this case, the lowest non-zero limit is enforced.
Fixes #4602
> Add query-frontend limit for length of query in bytes

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/util/globalerror/errors.go
- pkg/util/validation/errors.go
- pkg/util/validation/limits.go
cherry-pick of 117f0d68785b8a3ca07a8b1dda5a350b17cdc09b into r231
Add a new experimental limit to enforce the size of a query is under a certain number of bytes. This limit is enforced in the query-frontend and supports queries for multiple tenants. In this case, the lowest non-zero limit is enforced.
Fixes #4602
> Add query-frontend limit for length of query in bytes (#4604)

- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_refs_test.go
This PR add a benchmark for `openBlockSeriesChunkRefsSetsIterator` 
(which calculates postings and series for the Series() RPC).
It also includes an internal refactor to allow reusing the test cases
that `BenchmarkBucketIndexReader_ExpandedPostings` uses.
Related to https://github.com/grafana/mimir/issues/4593
> store-gateway: Add BenchmarkOpenBlockSeriesChunkRefsSetsIterator

- CHANGELOG.md
- operations/mimir/autoscaling.libsonnet
Add configurable autoscaling memory target utilization parameter for (ruler-)query-frontend and ruler components. This is useful so the autoscaler can trigger at a certain threshold before the memory request is hit.
> Jsonnet: Add configurable autoscaling memory target utilization

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview-networking.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json
- operations/mimir-mixin/config.libsonnet
The selector used in the mixin for pods started with `(.*-mimir-)`. However, using this helm chart in a wrapper chart name `mimir` and deploying the helm chart with release name `mimir` this regex would fail to find any pods. This PR changes the regex to `(.*mimir-)` so that helm releases with the name `mimir` will also function.
> fix(mixin): pod selector regex for deployments

- pkg/mimirpb/custom.go
This PR removes two unused methods.
These were originally used while encoding / decoding to and from the protobuf query payload format, but are no longer used.
> Remove unused methods

- pkg/ingester/shipper.go
I couldn't find any logs that indicate a successful block upload.
> Ingester: add logs for finishing block upload

- operations/k6/README.md
- operations/k6/load-testing-with-k6.js
This PR allows for the `load-testing-with-k6.js` K6 job to set the tenant_name. This enables writing to clusters that have authentication enabled, requiring a tenant name to be set for all writes.
No issue present at the moment. Please let me know if I should create an associated issue for this.
> Add ability to specify tenant ID through env variable

- development/mimir-microservices-mode/config/mimir.yaml
- development/mimir-microservices-mode/config/prometheus.yaml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/config/mimir.yaml
- development/mimir-monolithic-mode-with-swift-storage/config/prometheus.yaml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/config/mimir.yaml
- development/mimir-monolithic-mode/config/prometheus.yaml
- development/mimir-monolithic-mode/docker-compose.yml
- development/mimir-read-write-mode/config/mimir.yaml
Allow us to run our docker-compose setups with native histograms enabled.
Merging the remainder of https://github.com/grafana/mimir/pull/3505 in smaller chunks
The above don't seem relevant as this is just updating our development docker-compose files.
> Update docker-compose development configs for native histograms

- pkg/storegateway/indexheader/binary_reader.go
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/header_test.go
- pkg/storegateway/indexheader/index/postings.go
- pkg/storegateway/indexheader/stream_binary_reader.go
The index header estimates the length of each posting list by looking at
the offset of the next posting list. For all posting lists but the last
one this estimation is exact. For the last posting list, the index
header uses the table of contents from the index for the estimation.
To do the estimation of the last posting list the index header was using
the offset of the posting offset table. For reference this is the layout
in the Prometheus TSDB index ([docs](https://github.com/prometheus/prometheus/blob/fd8992cdbd6bf7274f2a815e4af64a0b8734841b/tsdb/docs/format/index.md))
```
│ ┌──────────────────────────────────────────────┐ │
│ │                 Symbol Table                 │ │
│ ├──────────────────────────────────────────────┤ │
│ │                    Series                    │ │
│ …
```
> Store-gateway: correctly estimate length of last posting list

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/util/validation/limits.go
Query sharding amplifies the number of partial queries executed by queriers, and so label matchers evaluated by ingesters and store-gateway. We've seen some edge cases where very complex regexp can spike the ingesters CPU significantly, up to the point of saturating the node CPU. Despite our efforts to optimise the regexp matcher (which in many cases are very effective), I would like to add an optional limit to query sharding, to skip it if the query contains a regexp longer than the configured limit.
- The regexp length is not synonymous of complexity, but evaluating the actual computatinal complexity of a regexp may be computationally expensive itself, so just checking the length is a simple approximation I suggest to begin with.
- I removed …
> Query-frontend: add -query-frontend.query-sharding-max-regexp-size-bytes

- CHANGELOG.md
- pkg/util/push/otel.go
I was doing a post-merge review of https://github.com/grafana/mimir/pull/4063 and I've noticed that the slices in `promToMimirHistogram()` are incorrectly pre-allocated.
N/A
> Fix promToMimirHistogram() slices pre-allocation

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/model/labels/matcher.go
- vendor/github.com/prometheus/prometheus/model/labels/regexp.go
- vendor/modules.txt
@Logiraptor did a fantastic job on https://github.com/grafana/mimir-prometheus/pull/463 to optimise regular expression label matchers with alternates, and I want to get it merged before the end of the week, so that it will be included in the next weekly release.
N/A
> Update mimir-prometheus to optimize regular expression label matchers with alternates

- pkg/querier/blocks_store_queryable.go
I find it useful to be able to read comments in side-by-side diff view.
> querier: reformat some wide comments

- CHANGELOG.md
- operations/mimir/config.libsonnet
Per #4619, instance limits for distributors can now be set as part of runtime configuration which allows them to be adjusted without restarting.
N/A
> jsonnet: Allow per-distributor limits to be set in runtime config

- CHANGELOG.md
- docs/sources/mimir/configure/configure-zone-aware-replication.md
It's valid to deploy Mimir to a single physical availability zone and still use zone-aware replication but the way the page at https://grafana.com/docs/mimir/latest/operators-guide/configure/configure-zone-aware-replication/ is worded today would lead you to believe that that is not the case as it only mentions separate AZs/Data centers/Racks.
It's also very valid to use the rollout-operator in this configuration but it's not well described.
This PR adds language to fix that.
Fixes #4630
> [Docs] Expand zone-aware replication page to cover single physical availability zone deployments.

- CHANGELOG.md
- operations/mimir/config.libsonnet
Update #4386 with deprecation removal and detail of changed configs.
> Remove deprecation in redis jsonnet

- pkg/querier/worker/frontend_processor.go
It came up as a warning in my IDE, that `"github.com/grafana/mimir/pkg/querier/stats"` was imported twice.
> querier: stop importing stats under two names

- CHANGELOG.md
- docs/sources/mimir/operators-guide/deploy-grafana-mimir-with-puppet/_index.md
A module is community maintained to deploy Grafana mimir using puppet. This commit is to add a documentation page on how to use it.
> Add documentation to deploy mimir to puppet

- CHANGELOG.md
- Makefile
Add `freebsd` to the target OS when generating binaries for a Mimir release.
We are using [nfpm](https://nfpm.goreleaser.com/configuration/) to
package it for debian based and redhat based OS. nfpm does not support
packaging for freebsd, as such for freebsd users this is the best we can
do.
Fixes #4652
> Generate binairies for freebsd

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
https://github.com/grafana/mimir/pull/4618 was merged without rebasing after https://github.com/grafana/mimir/pull/4603 and this broke the lint-helm CI on main. This PR regenerates the helm manifests, so CI passes again
> helm: fix out of sync CI

- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/header_test.go
- pkg/storegateway/indexheader/index/postings.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/reader_benchmarks_test.go
- pkg/storegateway/indexheader/stream_binary_reader.go
Related to #4593 
This PR introduces the `LabelValuesOffsets` method to `indexheader.Reader` and `indexheader.PostingsOfssetTableV(1|2)`. The method creates behaves the same was as `LabelValues` but instead of only the string values of each posting list, it returns the offsets in the index file of each posting list. This method is currently unused, but will be used once I make progress on #4593.
For `PostingsOfssetTableV1` I chose to copy the implementation of `LabelValues` since it is short and trivial.
For `PostingsOffsetTableV2` I extracted the traversal logic from `LabelValues` into a new method `postingOffsets` which takes a transformer, which is called with every matching posting list. The result of the transformer is appended to a slice. Both `LabelValues` and `LabelValuesOffsets` …
> store-gateway index header: return posting offset in LabelVales

- CHANGELOG.md
- pkg/api/error/error.go
- pkg/frontend/querymiddleware/retry.go
- pkg/frontend/querymiddleware/retry_test.go
Break out of the retry loop if the error has been decoded from a Prometheus error, or is a cancellation.
~Extra drive-by fix: don't log "context canceled" as an error in the querier.  This is noticeable when running `TestQueryFrontendErrorMessageParity/query_time_range_exceeds_the_limit`, for instance.~
Fixes #4637
> Query-frontend: don't retry queries which error inside PromQL

- CHANGELOG.md
- pkg/frontend/querymiddleware/cardinality.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/instrumentation.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/retry.go
See example trace:
This PR removes the `cardinalityEstimation.Do` and `querySharding.Do` spans which exactly parallel their parents.
It removes the spans for `ParseQueryRangeResponse`, turning each into an event on the parent span.
It adds an event to the `retry` span containing the error that triggered a retry.
And simplifies slightly the code for instrumentMiddleware.
> Improve querymiddleware tracing

- CHANGELOG.md
- pkg/ruler/manager.go
- pkg/ruler/manager_test.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_ring.go
- pkg/ruler/ruler_test.go
- pkg/ruler/tenant_federation_test.go
The ruler becomes active in the ring after all its services are started. When the ruler becomes ready it automatically starts "owning" rule groups. So other rules in the ring stop evaluating these rule groups because they now shard to the new ruler.
After becoming ACTIVE, the ruler proceeds to sync the rule groups for all the tenants that it own; to do that it needs to iterate the bucket and fetch the rule groups for all tenants. For larger cells with many tenants the time to iterate the bucket can exceed a minute. And this causes ruler to miss one iteration as a consequence alerts are auto solved. When the second alert arrives another alert notification is sent.
To solve this, instead of sync the rules after ruler becoming ACTIVE in the Ring, sync the rules when ruler JOINING the Ring, …
> Ruler: Sync rules when ruler JOINING the ring instead of ACTIVE

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/gateway/gateway-v2-hpa.yaml
- operations/helm/charts/mimir-distributed/templates/nginx/nginx-v2-hpa.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-v2-hpa.yaml
When averageUtilization is used as a [HPAv2 MetricTarget](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#metrictarget-v2-autoscaling), Kubernetes expects the type to also be Utilization. Currently, the usage of averageUtilization overrides the averageValue type and K8s defaults to a type of Utilization instead. This causes Helm to show drift, as the template wants averageValue but the applied resource has Utilization.
It is assumed that the intent is for the type to be Utilization given the usage of averageUtilization and the values file referring to percentage targets rather than absolute value targets. This PR sets the type to be Utilization, thus preventing spurious diffs when comparing the desired versus actual deployment state.
No issue raised.
> Helm: Set HPA default MetricTarget type to Utilization

- CHANGELOG.md
- pkg/storegateway/bucket.go
The store-gateway sends statistics about the involved index bytes
in each request in its response to the querier. These statistics
are later combined in the query-frontend and included in `query stats` logs.
My understanding is that the purpose of these stats is to
help gauge the cost of a query. Currently, the store-gateway reports
its fetched bytes. I propose to report touched bytes instead.
__Fetched index bytes__ are based on the number of bytes fetched from
the bucket. This excludes bytes fetched from the cache and includes bytes overfetched
because of an incorrect size estimation or when joining adjacent ranges
from the index object.
__Touched bytes__ are the sum of bytes that were directly necessary in 
order to serve the request. This means that they exclude bytes that we …
> store-gateway: report touched postings & series instead of fetched

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/ruler.libsonnet
Adds a description to the `Read from Ingesters - QPS` panel on the Ruler dashboard to explain why you would still see a value here even in remote ruler mode. Similar to the PR at https://github.com/grafana/mimir/pull/4629 but just adding the note to the dashboard too for maximum coverage as suggested by @dimitarvdimitrov here: https://github.com/grafana/mimir/pull/4629#discussion_r1154273468 
Fixes #4674
> [Mixin] Add panel description for Read QPS panel in Ruler dashboard.

- CHANGELOG.md
- pkg/mimirtool/client/client.go
- pkg/mimirtool/commands/analyse_prometheus.go
- pkg/mimirtool/commands/loadgen.go
- pkg/mimirtool/commands/remote_read.go
This PR adds a user agent header to mimirtool when interacting with Mimir or Prometheus servers. This is a change from the existing (default) user agent string of `Go-http-client/1.1`. Instead, it will be something like `mimirtool/2.7.1 (version=2.7.1, branch=logiraptor/set-mimirtool-ua, revision=92a468898)`.
We see many customers using mimirtool to optimize their metrics footprint in Grafana Cloud, but it's currently difficult to separate this use case from user queries. Adding this user agent makes it trivial, since the Mimir query frontend already logs user agents in the query stats logs.
It will most likely take a while for users to update to versions of mimirtool that include this change, but by getting this merged now we can point customers to upgrade when the issue arises.
- [N/A] …
> Set a well known user agent in mimirtool analyze prometheus

- CHANGELOG.md
- pkg/mimirpb/custom.go
- pkg/mimirpb/custom_test.go
Fix bug mentioned in slack: float histograms are sometimes wrongly interpreted as integer histograms (you can test the 1st commit to see the failing new test, and the 2nd and 3rd commits make that test pass)
N/A
> Fix IsFloatHistogram

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ruler/remotequerier.go
This PR makes the protobuf format the default for the rule evaluation path, and removes the experimental status on the `-ruler.query-frontend.query-result-response-format` flag.
> Enable protobuf query result payload format by default for rule evaluation path.

- CHANGELOG.md
- pkg/compactor/block_upload.go
- pkg/compactor/block_upload_test.go
Limits the byte size of block metadata when starting a block upload. This is to prevent a potentially abusive request OOMing the compactor.
N/A
> Limit the byte size of block metadata when starting a block upload

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
This PR adds deferred matchers to the exported interface of the
`bucketIndexReader` and adds an iterator which filters out series that do
not match the deferred matchers.
In practice this iterator will be unused because we are still
using the `selectAllStrategy` which doesn't omit any posting groups.
More strategies will be added in a later PR.
Related to https://github.com/grafana/mimir/issues/4593
> store-gateway: handle deferred matchers for Series()

- CHANGELOG.md
- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/ingester.go
Since we always calculate the hash to pass to `Appender.GetRef()` we can re-use that value and save time.
Profiles of ingesters using ActivityTracker show about 3.5% of CPU time goes into re-calculating the series hash.
```
goos: linux
goarch: amd64
pkg: github.com/grafana/mimir/pkg/ingester/activeseries
cpu: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
│  before.txt   │              after.txt              │
│    sec/op     │    sec/op     vs base               │
ActiveSeriesTest_single_series/50-4                             57.98n ±  5%   54.15n ±  3%   -6.61% (p=0.002 n=6)
ActiveSeriesTest_single_series/100-4                            57.82n ±  4%   52.32n ±  1%   -9.50% (p=0.002 n=6)
ActiveSeriesTest_single_series/500-4                            66.08n ± 13%   51.37n ±  4%  -22.27% …
```
> ingester: save time by reusing hash calculation in active series

- CHANGELOG.md
- cmd/mimir-continuous-test/main.go
Add a metric `mimir_continuous_test_build_info` in mimir continuous test metrics endpoint. Same as cortex_build_info, it allow to make sure all deployment are up-to-date
None
> Add build info metric to mimir continuous test

- CHANGELOG.md
- pkg/continuoustest/write_read_series.go
Selected ranges for read tests where missing coherency. This commit is here to add some and ensure we won't try to query data after the one that has been written for the random query range.
> Fix continous-test query ranges

- integration/compactor_test.go
- integration/distributor_forwarding_test.go
- integration/getting_started_single_process_config_test.go
- integration/getting_started_with_gossiped_ring_test.go
- integration/getting_started_with_grafana_mimir_test.go
- integration/ingester_limits_test.go
- integration/ingester_sharding_test.go
- integration/otlp_ingestion_test.go
- integration/querier_label_name_values_test.go
- integration/querier_remote_read_test.go
- integration/querier_sharding_test.go
- integration/querier_tenant_federation_test.go
- integration/querier_test.go
- integration/query_frontend_cache_test.go
- integration/query_frontend_test.go
- integration/read_write_mode_test.go
- integration/ruler_test.go
- integration/store_gateway_limits_hit_test.go
- integration/util.go
- integration/validation_separate_metrics_test.go
- integration/zone_aware_test.go
Add native histograms to integration tests where relevant.
Merging the remainder of https://github.com/grafana/mimir/pull/3505 in smaller chunks
The others don't seem relevant as these only update tests
> Update integration tests for native histograms

- CHANGELOG.md
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/querysharding_test_utils_test.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/frontend/querymiddleware/split_by_instant_interval_test.go
- Expand unit tests for query sharding native histograms (previously minimal tests, and a few of them were for conventional histograms)
- Fix bug mentioned in slack: summing a native histogram returns an empty result from query frontend with query sharding, but works as expected from prometheus and querier (you can test the 1st commit in the PR to see the failing updated tests, and then the 2nd commit makes those tests pass)
N/A
> Expand unit tests and fix bug for query sharding native histograms

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/graphite-proxy/graphite-web/graphite-web-dep.yaml
What this PR does:
Adds imagePullSecrets option for graphite-web deployment for the graphite-proxy, like in every other deployment.
> Added missing imagePullSecrets configuration to the graphite-web mimir helm chart

- pkg/mimirtool/commands/rules.go
- pkg/mimirtool/rules/parser.go
Fix a couple of typos in rules subcommand help output, plus a couple more in error messages.
> mimirtool: Fix typos in rules subcommand help and error messages

- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
This PR fixes JSON and YAML marshalling of Limits extensions to make them visible in `/runtime_config` endpoint.
No changelog entry, as this mechanism is not used by Mimir, only by enterprise version to add additional reloadable limits.
> Fix marshalling of Limits extensions

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/gateway/gateway-route.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/gateway/gateway-route.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-route.yaml
This PR fixes the wrong port mapping from the OpenShift route to the gateway service.
Fixes #4727
> Fix OpenShift route targetPort matching to service

- pkg/mimirpb/compat_test.go
- pkg/mimirpb/query_response_extra_test.go
- pkg/util/test/shape.go
We are using unsafe.Pointer to convert some data without copy. Add check for compatibility.
Inspired by @charleskorn .
Fixes N/A
Related to #4351 
Related to #4303 
> Add unit tests to verify Prometheus and Mimir are in sync on SampleHistogram and Label types

- docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
Reorder Getting Started guide to avoid needing complicated ingress setup at first. Also to run everything in kubernetes and not have to use docker at first.
We've tested the guide on @osg-grafana 's machine and this order and instructions make better sense.
Fixes https://github.com/grafana/mimir/issues/4616.
> Helm docs: make getting started less scary and self contained

- CHANGELOG.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
This extends the runbook for `MimirIngesterReachingTenantsLimit` to explain what controls per-tenant allocation size in ingesters and its correlation to the `max_tenants` parameter.
> Extend runbook for MimirIngesterReachingTenantsLimit

- CHANGELOG.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
This removes a suggested fix for the `MimirIngesterReachingTenantsLimit` alert because it's not generally applicable.
n/a
> Remove suggested fix for MimirIngesterReachingTenantsLimit

- development/mimir-microservices-mode/docker-compose.jsonnet
- pkg/mimirpb/timeseries.go
- pkg/util/push/push_test.go
We can avoid allocating an extra pointer just to put something into a pool if we store the pointer we got from the first pool in a second pool. Used the implementation of a pool from Prometheus for this.
```
goos: linux
goarch: amd64
pkg: github.com/grafana/mimir/pkg/util/push
cpu: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
│   old.txt   │            new.txt            │
│   sec/op    │   sec/op     vs base          │
PushHandler-16   1.635µ ± 8%   1.608µ ± 4%  ~ (p=0.289 n=10)
│  old.txt   │              new.txt              │
│    B/op    │    B/op     vs base               │
PushHandler-16   659.0 ± 0%   633.0 ± 0%  -3.95% (p=0.000 n=10)
│  old.txt   │              new.txt              │
│ allocs/op  │ allocs/op   vs base               │
PushHandler-16   17.00 ± 0%   16.00 ± 0% …
```
> Don't allocate an extra pointer in `mimirpb.ReuseSlice()`

- tools/release/notify-changelog-cut.sh
> Limit notified-changelog-cut PRs to only those that modify CHANGELOG.md

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_chunk_reader.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_chunks_test.go
One of the last parts of #3348 was to rename some of the structs for consistency. This PR does a couple of renames. It should be a noop in terms of functionality or performance.
* `seriesEntry` -> `seriesChunks`; this keeps the consistency with `seriesChunkRefs`
* `seriesChunksSlicePool` -> `chunksSlicePool`; this holds `[]storepb.AggrChunk`, so I think the rename makes sense
* `seriesEntrySlicePool` -> `seriesChunksSlicePool`; this change makes some of the diff confusing
* a few places in tests that were using `entry` for a variable name while holding `seriesEntry`. I renamed them to `series`
* `loadIdx.chunk` -> `loadIdx.chunkEntry` to have a bit more consistency with `seriesEntry` and may disabiguate what `entry` refers to …
> store-gateway: rename `seriesEntry` to `seriesChunks`

- .github/workflows/compare-helm-with-jsonnet.yml
- .github/workflows/helm-ci.yml
- .github/workflows/test-build-deploy.yml
- CHANGELOG.md
- Makefile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
- mimir-build-image/Dockerfile
> Go: Upgrade to 1.20.3

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin/dashboards/alertmanager.libsonnet
Display cortex_alertmanager_dispatcher_aggregation_groups on alertmanager dashboard
Relate to #4151
> dashboard: Display alertmanager aggregation groups metric

- CHANGELOG.md
- pkg/querier/metadata_handler.go
- pkg/querier/metadata_handler_test.go
This PR updates the `/api/v1/metadata` endpoint to return an empty object when no metadata is present. This matches Prometheus behavior and also makes this endpoint compatible with the [public prometheus client](https://github.com/prometheus/client_golang/blob/c36c6abb8deadeb44d1e795c21a58bbd5c85a6ae/api/prometheus/v1/api.go#L1383).
> Return an empty object when no metadata is found

- .github/workflows/compare-helm-with-jsonnet.yml
- .github/workflows/helm-ci.yml
- .github/workflows/test-build-deploy.yml
- CHANGELOG.md
- Makefile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
- mimir-build-image/Dockerfile
Signed-off-by: Arve Knudsen <arve.knudsen@gmail.com>
(cherry picked from commit 5d9f1048119156d2fbc3885d8b8b8bb59a858a35)
Manual backport of  #4773
> Go: Upgrade to 1.20.3 (#4773)

- CHANGELOG.md
- docs/sources/mimir/operators-guide/monitor-grafana-mimir/installing-dashboards-and-alerts.md
This PR introduces a new documentation about how to deploy mixin in Grafana and Mimir with terraform.
Full Disclosure: I'm working at OVHcloud and we are the maintainers of both [ovh/mimirtool](https://registry.terraform.io/providers/ovh/mimirtool/latest) and [ovh/mixtool](https://registry.terraform.io/providers/ovh/mixtool/latest) providers 🙏🏾
> Added documentation on how deploy mixin with terraform

- CHANGELOG.md
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/indexcache/remote.go
- pkg/storegateway/indexcache/remote_test.go
- pkg/storegateway/postings_codec.go
- pkg/storegateway/postings_codec_test.go
This is a follow-up of https://github.com/grafana/mimir/pull/4770. It adds cache collision  detection for cached posting lists. Since the cache key is is a hashed label, it can collide between different postings lists from the same block.
This PR uses the already existing encoding of matchers into posting list cache keys to check for collisions. It encodes the label for the posting list as an "equals" matcher and then compares it when it is retrieved.
__Notes to reviewers__: This PR ended up smaller than I expected, so could have been merged with #4770 too, but I figured reviewing may be easier if they are smaller. I think reviewing #4770 first may be easier to review. I am happy to make them one PR too.
https://github.com/grafana/mimir/issues/4523
> store-gateway: detect cache key collisions for Postings cache

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/distributor/distributor_test.go
- pkg/util/globalerror/errors.go
- pkg/util/validation/errors.go
- pkg/util/validation/limits.go
- pkg/util/validation/validate.go
- pkg/util/validation/validate_test.go
Memory protection from ingesting unreasonably huge samples. Classic sample is fixed size with a timestamp and value, but native histogram may contain 2^31 buckets.
Out of scope: validate histogram makes sense, only check valid histogram.
Relates to: #4542
> Add native histogram bucket limit

- CHANGELOG.md
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/indexcache/remote.go
- pkg/storegateway/indexcache/remote_test.go
- pkg/storegateway/postings_codec.go
- pkg/storegateway/postings_codec_test.go
When storing an ExpandedPostings cache item the key is the hashed matchers from the query. However, we do not check the stored values for cache collisions.
This PR adds cache collisions for ExpandedPostings. It stores the string of the request matchers with the item value and then rechecks it upon retrieval.
To ensure we don't misinterpret some cache item, this PR also changes cache key for expanded postings.
closes #4523 
> store-gateway: detect cache key collisions for ExpandedPostings cache

- CHANGELOG.md
- packaging/nfpm/mimir/preremove.sh
nfpm migration introduce a regression in the prerm step. This step is used by the OS for doing necessary cleaning before removing a package. The underlying script is called upon remove or upgrade of a package by passing an argument to it, argument being `remove` or `upgrade`. The script expect *only* `remove` and raises an error for anything else. Therefore when trying to upgrade the script would failed with such error:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
mimir
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/20.8 MB of archives.
After this operation, 5,796 kB of additional disk space will be used.
Do you want to continue? …
```
> Packaging: fix preremove script preventing the upgrade

- docs/sources/mimir/release-notes/v2.6.md
> Update 2.6 release notes with go bugfix

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
- operations/helm/charts/mimir-distributed/RELEASE.md
Instead of heaving to sed replace a bunch of links, make it parametric. Later when tech writer team introduces relref support between projects, this should be taken into account.
Bonus: fix link in vault integration doc.
N/A internal improvement
> Helm: version of Mimir and GEM documenation links is now parametric

- CHANGELOG.md
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_refs.go
This is a follow-up of #4797. This code is panicking because `stats` are `nil`. I am planning to backport this to r235
> store-gateway: fix stats recording in filtering...Iterator

- CHANGELOG.md
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/ruler.go
Cherry pick of 95b41a86ab6059c79a6f16537a8d7bf86973e8de
In order to validate a tenant hasn't exceeded their max number of rule groups, we iterate every existing rule group for that tenant and count them. This isn't great but we can avoid doing it entirely when the limit is disabled for that particular tenant.
See #4826
> Only load existing rule groups when enforcing group limit (#4828)

- development/mimir-microservices-mode/config/datasource-mimir.yaml
- development/mimir-monolithic-mode/config/datasource-mimir.yaml
- development/mimir-monolithic-mode/docker-compose.yml
- development/mimir-read-write-mode/config/datasource-mimir.yaml
- development/mimir-read-write-mode/docker-compose.jsonnet
- development/mimir-read-write-mode/docker-compose.yml
This PR adds grafana to the dev mimir-monolithic-mode and mimir-read-write-mode docker compose setups, pre-configuring it with a datasource for the query-frontend.
> Add grafana to dev mimir-monolithic-mode and mimir-read-write-mode docker composes

- CHANGELOG.md
- development/mimir-read-write-mode/docker-compose.jsonnet
- pkg/storegateway/indexcache/remote.go
Late feedback on https://github.com/grafana/mimir/pull/4861, so I decided to open a PR instead of commenting.
Zeropool is useful when we can't retain the pointer to put it back into the pool, but when we can it causes an unnecessary overhead of a second pool.
This saves some nanoseconds, without an allocations change
```
goos: linux
goarch: amd64
pkg: github.com/grafana/mimir/pkg/storegateway/indexcache cpu: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
│   main.txt   │               new.txt                │
│    sec/op    │    sec/op     vs base                │
StringCacheKeys/postings-16            1.011µ ±  0%   1.001µ ±  3%   -0.94% (p=0.033 n=10)
StringCacheKeys/series_ref-16          133.9n ± 13%   120.5n ±  9%   -9.97% (p=0.000 n=10)
StringCacheKeys/expanded_postings-16   418.0n …
```
> Don't use zeropool for postings cache key building

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/_helpers.tpl
- operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml
- operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/charts/mimir-distributed/values.yaml
Add option to configure the `storageClass` per zone when **zoneAwareReplication** is enabled.
When I enabled **zoneAwareReplication** for ingesters or store-gateway (should be the same for alertmanager), I notice that the `Persistent Volume` was not always created in the good zone (the pod one). 
Only 1 out of 3 Persistent Volume was accessible for the pod. 
Exemple: 
```
Pod: ingester-zone-a-0, Persistent Volume: zone-a -> OK 
Pod: ingester-zone-a-1, Persistent Volume: zone-b -> KO
Pod: ingester-zone-a-2, Persistent Volume: zone-c -> KO
Pod: ingester-zone-a-3, Persistent Volume: zone-a -> OK
```
To fix it I create one `Storage Class` per Zone and update the `volumeClaimTemplates` spec to use the `storageClassName` from the rollout. 
```
zones:
- name: zone-a
storageClass: sc-zone-a …
```
> Allow to select storageClass per zone

- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode/docker-compose.yml
- development/mimir-read-write-mode/docker-compose.jsonnet
- development/mimir-read-write-mode/docker-compose.yml
This change exposes the minio console on port 9001 in the dev-docker compose stacks, which helps with debugging storage related problems in a dev environment. Recent minio versions require the console to be explicitly enabled and exposed on a separate port from the API. Port 9001 [is suggested](https://min.io/docs/minio/linux/administration/minio-console.html#static-vs-dynamic-port-assignment), and does not appear to be in use in the 3 updated docker-compose stacks.
> Expose the minio console in dev docker-composes

- CHANGELOG.md
- operations/mimir-tests/test-deployment-mode-migration-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
- operations/mimir/read-write-deployment/backend.libsonnet
By default alertmanager URL is configured to point at alertmanager, but it's running in the backend deployment now.
> Fix alertmanager url in read-write deployment

- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
I would like to inject some rows after the `Distributor` row of the `Mimir / Writes` dashboard, unfortunately I have not found a cleaner solution than this. If there is a better way to do this, please let me know.
> Allow injection of dashboard rows after Distributor row in Mimir / Writes dashboard

- .github/workflows/compare-helm-with-jsonnet.yml
- .github/workflows/helm-ci.yml
- .github/workflows/test-build-deploy.yml
- CHANGELOG.md
- Makefile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
- mimir-build-image/Dockerfile
This PR updates used Go version to 1.20.4.
> Update Go to 1.20.4

- CHANGELOG.md
- operations/mimir-tests/test-deployment-mode-migration-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
- operations/mimir/read-write-deployment/backend.libsonnet
Instead of hardcoding alertmanager storage to `filesystem`, add the alertmanager_args which have correct configuration for alertmanager as well as the configured bucket storage.
Fixes https://github.com/grafana/mimir/issues/4891
> Jsonnet read-write/backend: add alertmanager_args

- development/mimir-microservices-mode/config/grafana-agent.yaml
- development/mimir-microservices-mode/config/otel-collector.yaml
- development/mimir-microservices-mode/config/prometheus.yaml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-read-write-mode/config/grafana-agent.yaml
This PR makes a number of changes to the `mimir-microservices-mode` and `mimir-read-write-mode` Docker Compose stacks:
* it makes the Grafana Agent, OTel Collector and Prometheus instances optional in `mimir-microservices-mode`
* it disables the OTel Collector and Grafana Agent instances by default in `mimir-microservices-mode`, fixing the triple scrape issue described in #4898
* it adds `container` labels to scrape targets, fixing the broken dashboards issue described in #4898
Fixes part of #4898
> Improve out-of-the-box experience with Docker Compose stacks for microservices and read-write mode

- CHANGELOG.md
- operations/mimir-tests/test-deployment-mode-migration-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
- operations/mimir/read-write-deployment/backend.libsonnet
- pkg/mimir/mimir.go
- pkg/mimir/mimir_test.go
The default alertmanager data dir `/data` contains `/data/tsdb`, when running mimir-backend, both modules run, and alertmanager deletes the `/data/tsdb` continuously (and complains about the `tokens` file).
The validation was missing the `Backend` module when adding `Alertmanager` paths.
Follow up on: https://github.com/grafana/mimir/pull/4907
> Fix alertmanager /data contain /data/tsdb

- CHANGELOG.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
This PR makes two versions of the alert
* one for single-zone deployments
* one for multi-zone deployments
They fire at different conditions
* single-zone
* only fire when there are more than one corrupted WAL; a single corrupted WAL means no data loss, so shouldn't be a critical alert
* multi-zone
* only fire when there are more than one zones affected with arbitrary corrupted WALs within them; same reasoning as above - only multiple zones cause data loss
> mixin: reduce sensitivity of MimirIngesterTSDBWALCorrupted

- pkg/storegateway/bucket_test.go
- pkg/storegateway/indexheader/index/postings.go
- pkg/storegateway/indexheader/index/postings_test.go
This is a follow-up of this comment https://github.com/grafana/mimir/pull/4667#issuecomment-1498855314
When there is a prefix in the matcher, such as `pod=~"querier.*"`, the postings offset table is optimized to only scan
the values that match this prefix. This reduces the duration of the whole lookup. PostingsOffsets also tries to
preallocate the size of the slice with matching values. When we have a prefix we can be more precise in estimating where
is the last value which matches the prefix.
The results are that we reduce allocated memory for LabelValues (and LabelValuesOffsets) by up to 90% in some cases.
> store-gateway: more precise estimations of LabelValues size

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/minio/create-bucket-job.yaml
`operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml` is used to create buckets for minio as post-install hooks of mimir-distributed helm chart. If new mimir-distributed helm chart is updated with a new minio subchart, it will prevent mimir-distributed chart upgrade because helm try to modify the job with new minio image. That wouldn't work because job spec is immutable.
Example upgrade error log:
```
client.go:429: [debug] error updating the resource "my-mimir-make-minio-buckets":
cannot patch "my-mimir-make-minio-buckets" with kind Job: Job.batch "my-mimir-make-minio-buckets" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, …
```
> Add dynicamic suffix to make-minio-buckets k8s job

- pkg/storegateway/bucket_test.go
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/header_test.go
- pkg/storegateway/indexheader/index/postings.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/reader_benchmarks_test.go
- pkg/storegateway/indexheader/stream_binary_reader.go
As part of #4593 I replaced the usages of `LabelValues() []string` with `LabelValuesOffsets() []PostingListOffset`
This PR is in internal clean-up, which removes the implementation of LabelValues from the postings tables and index header readers.
It also replaces a few tests and benchmarks to use the new implementation.
> store-gateway: remove internal LabelValues

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/model/labels/sharding_stringlabels.go
- vendor/modules.txt
Updates mimir-prometheus with support for stringlabels.
Includes changes from https://github.com/grafana/mimir-prometheus/pull/503
None, should unblock https://github.com/grafana/mimir/pull/3555 :rocket:
> Update mimir-prometheus to e5eb66f422

- CHANGELOG.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
The scenario with symbol table size exceeds has happened only twice in the last 3 years that we know of, but documenting it should reduce the time  needed for mitigation.
None
> Update runbook for MimirCompactorHasNotSuccessfullyRunCompaction

- CHANGELOG.md
- docs/sources/mimir/references/architecture/query-sharding/index.md
Docs are not clear whether remote read API uses sharding or not.
Ref: internal support case 5848
> Specify which APIs use query sharding

- docs/sources/mimir/references/architecture/components/ingester.md
This PR updates the ingester doc section on replication to also discuss availability in terms of majorities and minorities, since odd replication factors (2) could cause behavior that doesn't match the current docs. This change was prompted by #3844, where a user mentioned running with RF=2.
> Docs: Update ingester docs on replication and availability

- CHANGELOG.md
- pkg/alertmanager/alertmanager_metrics.go
- pkg/alertmanager/alertmanager_metrics_test.go
The upstream `prometheus/alertmanager` has recently been enhanced with new metrics:
- New `reason` label on `alertmanager_notifications_failed_total`
- `alertmanager_silences_maintenance_total`
- `alertmanager_silences_maintenance_errors_total`
- `alertmanager_nflog_maintenance_total`
- `alertmanager_nflog_maintenance_errors_total`
Since we recently upgraded alertmanager, these metrics are now available for us to consume.
This PR exposes these metrics in Mimir.
Fixes https://github.com/grafana/mimir/issues/4895
- I found no documentation listing each metric by name, but happy to update this if there is one! :smile:
> Alertmanager: Introduce new metrics from upstream

- operations/helm/charts/mimir-distributed/RELEASE.md
Improve the release.md for mimir-distributed helm chart.
- Split the Release process step of release candidate and final release to prevent accidentally publishing a release prematurely. 
- Tidy up the granularity of the release steps. Originally there were 15 steps with inconsistent step granularity. This PR simplify the step into 9 step for release candidate release and 6 steps for final release. Fine grained step is moved as bulleted list within numbered list.
- Add step on merging release branch to main.
- Add step for possible backport.
Rendered release.md
- [New release.md](https://github.com/grafana/mimir/blob/lamida/improve-helm-release.md/operations/helm/charts/mimir-distributed/RELEASE.md) (this PR)
- [Original release.md](https://github.com/grafana/mimir/blob/main/operations/hel …
> Improve helm release.md

- CHANGELOG.md
- go.mod
- go.sum
- integration/backfill_test.go
- pkg/api/api.go
- pkg/compactor/block_upload.go
- pkg/compactor/block_upload_test.go
- pkg/mimirtool/client/backfill.go
- vendor/github.com/opentracing-contrib/go-stdlib/nethttp/client.go
- vendor/github.com/opentracing-contrib/go-stdlib/nethttp/metrics-tracker.go
- vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go
- vendor/modules.txt
This PR disables HTTP timeout values on compactor's endpoint for uploading a file for a block. This is done to allow uploads of big files.
In the future we may want to introduce minimum upload rate instead of just disabling timeout.
Note that block upload feature is disabled by default, and must be enabled for tenant to use it.
This PR also changes `/api/v1/upload/block/{block}/files` endpoint to allow upload of files with unset `Content-Length` (chunked uploads).
> Disable HTTP timeout on block upload endpoint for uploading a file.

- CHANGELOG.md
- docs/sources/mimir/operators-guide/tools/mimirtool.md
- pkg/mimirtool/commands/analyse.go
- pkg/mimirtool/commands/analyse_prometheus.go
When configuring mimirtool via environment variables users might use the following:
```
MIMIR_ADDRESS=https://mimir:9090
MIMIR_TENANT_ID=default
MIMIR_API_USER=default
MIMIR_API_KEY=1234
```
It works as expected for `mimirtool analyze ruler` but not for `mimirtool analyze prometheus`.
The HTTP client for `analyze ruler` is done with
`github.com/grafana/mimir/pkg/mimirtool/client`, when for `analyze prometheus` it is done with only the address.
Depending on which prometheus the user wants to analyze the path is not the same. For a mimir based analysis user needs to provide `/prometheus`.
This commit allow to specify the path to use for a mimir based analysis. It also simplify the scripting around the tool.
Example:
```
source .secrets.env
mimirtool analyze grafana && \
mimirtool analyze …
```
> Allow to specify -prometheus-http-prefix for mimirtool analyze prometheus

- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_reader.go
Related to https://github.com/grafana/mimir/issues/4593
The 64KiB size estimation for series was inherited from Thanos. The PR which adds this to Thanos (PR 1985) didn't give any explanation for why 64KiB was chosen. Based on some rough estimation we think that we can bring this number down in order to reduce the volume of fetched data.
Citing @pracucci 
> Assuming a worst case scenario of 1 sample /sec, in a 24h block we have 744 chunks per series.
> The worst case scenario of each meta ref is 8*3=24 bytes, so 744*24 = 17856 bytes.
This PR also moves this constant to the tsdb package which contains similar constants.
> store-gateway: reduce series size estimation

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/util/validation/notifications_limit_flag.go
Mimir 2.6.0 introduce the support of webex notifications, however we cannot rate-limit webex notifications as it is not listed in `allowedIntegrationNames`. Hence users have the following error when starting mimir:
```
/usr/local/bin/mimir --log.level info --config.file=/etc/mimir/config.yml --runtime-config.file=/etc/mimir/runtime_config.yml
error loading config from /etc/mimir/config.yml: Error parsing config file: unknown integration name: webex
```
> Allow to rate-limit webex notifications

- CHANGELOG.md
- pkg/mimir/mimir.go
Makes `cortex_request_duration_seconds` a native histogram.
Fixes #4175
> Start using native histograms for cortex_request_duration_seconds

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-object-store.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled/dashboards/mimir-object-store.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/compactor.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/object-store.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
- operations/mimir-mixin/dashboards/ruler.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
On lightly loaded cluster, some dashboard have holes in their graph because query make a division by 0.
Migrate to timeseries panel, filter out NaN results and provide a sane default value.
It improve dashboard readability.
> Dashboard holes

- CHANGELOG.md
- docs/sources/mimir/operators-guide/tools/mimirtool.md
- pkg/mimirtool/commands/analyse.go
- pkg/mimirtool/commands/analyse_grafana.go
In shared environment, it is expected to have several teams within the same Grafana's organization. Team A might store its dashboard in folder A and Team B in folder B. Without filtering on folder we can have false positive on unused series.
This commit allow users to specify from which folders to keep the dashboards. The flag might be repeated as users might have several source folders
```
mimirtool analyze grafana --folder-titles "00 / Ready to use Prometheus dashboards" --folder-titles "01 / Dedicated Folder Team A"
mimirtool analyze grafana --folder-titles "00 / Ready to use Prometheus dashboards" --folder-titles "01 / Dedicated Folder Team B"
```
> Allow to filter based on folder for mimirtool anlyze grafana

- CHANGELOG.md
- docs/sources/mimir/operators-guide/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
This alert fires every time there is a store-gateway restart. This makes this alert very rarely actionable. Refetches themselves also aren't a problem. There are other alerts that will fire when store-gateways are unavailable (MimirRequestErrors) or overwhelmed (MimirSchedulerQueriesStuck).
I am not in a hurry to merge this and am interested in feedback.
> mixin: remove MimirQuerierHighRefetchRate

- pkg/ruler/manager.go
This PR propose a small refactoring of `DefaultMultiTenantManager` in order to make an [upcoming PR](https://github.com/grafana/mimir/pull/4975) easier to review.
The refactoring in this PR:
- Move the logic to concurrently call `syncRulesToManager()` into a dedicated function called... no surprise... `syncRulesToManagerConcurrently()`
- Move the logic to remove users from the manager into a dedicated function called `removeUsersIf()`. It takes in input a callback which is invoked for each user for which there's a ruler running and should be checked whether should be removed or not. This allows the upcoming PR to call it with a different logic.
N/A
> Refactoring: split DefaultMultiTenantManager.SyncRuleGroups() logic into multiple functions

- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
This PR propose a small refactoring of `DefaultMultiTenantManager` in order to make an [upcoming PR](https://github.com/grafana/mimir/pull/4975) easier to review.
The refactoring in this PR:
- Decouple listing tenants from listing rule groups in Ruler, moving listing rule groups to sync logic to `listRuleGroupsToSyncForUsers()` (which takes in input the list of tenants)
N/A
> Refactoring: decouple listing tenants from listing rule groups in Ruler

- .github/workflows/test-build-deploy.yml
This PR modifies the CI pipeline to pull images for integration tests in parallel.
Pulling them sequentially currently takes ~2 minutes and integration tests are often the last job to finish, so improving the speed of the integration test job should improve the overall CI pipeline duration.
(none)
> Pull images for integration tests in parallel in CI pipeline.

- .github/workflows/scripts/helm-weekly-release.sh
The weekly release calculates the next weekly semver by incrementing the minor version of the current release.
But it doesn't reset the patch version. Because of that the weekly release after 4.4.1 is 4.5.1 instead of 4.5.0 ([PR](https://github.com/grafana/mimir/pull/4970)). This PR fixes that.
> helm: fix weekly release version calculation

- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
This PR bundles two changes
* mentions that you may need to manually prune the Services and StatefulSets of the old non zone-aware deployments; this causes some double scraping and misfiring alerts
* mention how to find the list of node_exporter metrics necessary for metamonitoring
> Helm docs: multi-zone resources pruning; metamonitoring list of metrics

- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_refs_test.go
The binary (mmap) reader was removed earlier this year as part of issue #3465. All the test setup functions that refer to it actually use the file-based reader. But we still have some test matrices that try to test both. This PR removes them.
I recommend reviewing this ignoring whitespace changes.
> store-gateway: remove mmap reader from tests

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/storegateway/gateway.go
- pkg/storegateway/gateway_prepare_shutdown_http.go
- pkg/storegateway/gateway_prepare_shutdown_http_test.go
This PR improves the way shutdown markers for ingesters work. Namely it:
* Removes the shutdown marker while shutting down. The volumes used by ingesters are reused if an ingester is stopped (scaled down) but then later started again with the same name. Removing the marker during shutdown prevents the ingester from unregistering and flushing the next time it is stopped after having already performed its work for "permanently" shutting down.
* Prevents changes to the shutdown marker while the ingester is not running. This prevents the rollout-operator from calling the `prepare-shutdown` endpoint again while the ingester is already in the process of shutting down and about to remove the shutdown marker as noted previously.
N/A
> Ingester shutdown marker improvements

- .github/workflows/test-build-deploy.yml
This PR modifies the CI pipeline to split the integration tests over more runners (ie. run more in parallel).
Integration tests are often the last job to finish, so improving the speed of the integration test job should improve the overall CI pipeline duration.
(none)
> Split integration tests over more parallel runners.

- pkg/storage/tsdb/bucketcache/caching_bucket.go
- pkg/storage/tsdb/bucketcache/caching_bucket_test.go
This PR is a preliminary PR before https://github.com/grafana/mimir/pull/4975. In this PR I propose to add support to disable cache lookup to `CachingBucket`: when the cache lookup is disabled, the cache is not checked but the result of the bucket operation is still stored to the cache (eventually overriding the previous one). I've took the opportunity to do some refactoring to the `CachingBucket` tests, trying to clarify what each test case does.
To simplify the review, I've pushed each function change as an individual commit:
- [Add cache lookup disabled support to Iter()](https://github.com/grafana/mimir/commit/4e3b263f72b926e7fcc240d95ff14d5f93d2a61d) 
- [Add cache lookup disabled support to Exists()](https://github.com/grafana/mimir/commit/b064e64d03cf4e491468c4677f7f4c4a2aeac577) 
- …
> Add support to disable cache lookup to CachingBucket

- CHANGELOG.md
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/rollout-progress.libsonnet
This makes it possible to configure the names of additional services to be included in the Rollout Progress dashboard.
n/a
> Allow configuration of additional services in Rollout Progress dashboard.

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
Add configuration option to enable/disable deletion of alertmanager state from
object storage. This is useful when migrating alertmanager tenants from one
cluster to another, as it avoids a condition where the state object is copied
but then potentially deleted before the configuration object is copied.
> Alertmanager: Allow disabling of alertmanager state cleanup.

- pkg/frontend/querymiddleware/querysharding_test_utils_test.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/querier/distributor_queryable.go
- pkg/querier/partitioner.go
- pkg/querier/remote_read_test.go
- pkg/storage/series/series_set.go
- pkg/storage/series/series_set_test.go
This is a refactoring PR that renames `NewConcreteSeriesSet` to `NewConcreteSeriesSetFromUnsortedSeries` and introduces `NewConcreteSeriesSetFromSortedSeries`.
(this has been split out from https://github.com/grafana/mimir/pull/4886)
> Rename NewConcreteSeriesSet and introduce NewConcreteSeriesSetFromSortedSeries

- docs/sources/mimir/references/http-api/index.md
This PR fixes the issue where the table on [the HTTP API docs page](https://grafana.com/docs/mimir/latest/references/http-api/) appears behind the table of contents on the right side of the page on small screens:
https://github.com/grafana/mimir/assets/4017646/f3844f11-8884-47d5-a93b-5c5d441a99dc
(none)
> Fix issue where API endpoint table on HTTP API docs page appears behind table of contents

- CHANGELOG.md
- pkg/storegateway/bucket.go
encoding/gob has a bug when decoding string slices that are longer than 655360 items. This PR introduces a hard limit on the number of items in a cache item that we store.
Fixes #5014
> store-gateway: limit number of values in LabeValues cache items

- pkg/storage/tsdb/block/fetcher.go
- pkg/storegateway/bucket_index_metadata_fetcher.go
I'm investigating the object storage API calls issued by compactor and I noticed we have some unused code in `MetaFetcher`, which I'm removing in this PR. I think we can also merge the `BaseFetcher` with `MetaFetcher`, but I will eventually do it in a follow up PR once I have a better picture of the whole meta fetcher usefulness nowadays.
N/A
> Chore: removed unused code from MetaFetcher

- CHANGELOG.md
- pkg/storegateway/indexcache/remote.go
This PR addresses https://github.com/grafana/mimir/pull/5021#issuecomment-1551011489. It invalidates the cache for LabelValues results so that the store-gateway discards the corrupted cache items from #5014
> store-gateway: change LabelValues cache key

- .github/workflows/test-build-deploy.yml
- CHANGELOG.md
- Makefile
- pkg/mimirtool/commands/rules.go
- pkg/mimirtool/commands/rules_test.go
Changes the behaviour of `mimirtool rules check` to fail on duplicated rules when `--strict` is provided.
Also changed the output to use the logger instead of fmt, and added a test.
The output looks like this (on main before https://github.com/grafana/mimir/pull/5023 was merged):
```
$ go run ./cmd/mimirtool rules check --strict --rule-dirs ./operations/mimir-mixin-compiled
ERRO[0000] duplicate rules found                         duplicate_rules=2 error="rules should emit unique series, to avoid producing inconsistencies while recording expressions" namespace=alerts
ERRO[0000] duplicate rule                                label[severity]=warning metric=MimirRolloutStuck namespace=alerts
ERRO[0000] duplicate rule                                label[severity]=critical …
```
> mimirtool: fail on duplicate rules with --strict

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
Adds a config option to the query-frontend to specify a list of request headers to include in query logs.
For example, setting `-query-frontend.log-query-request-headers="X-Grafana-Org-Id"` and sending a query with `X-Grafana-Org-Id:1` results in query log lines that include `header_x_grafana_org_id=1`.
Fixes https://github.com/grafana/mimir/issues/4815
> Add query-frontend config option to log request headers in query logs

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/jsonnetfile.lock.json
This PR updates `grafana/jsonnet-libs/grafana-builder` to include https://github.com/grafana/jsonnet-libs/pull/988. This fixes the issue where cancelled requests can be shown in the same green as successful requests in throughput panels on dashboards.
(none)
> Show cancelled requests in grey in throughput panels on dashboards

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/compactor/syncer_metrics.go
- pkg/compactor/syncer_metrics_test.go
- pkg/querier/blocks_finder_bucket_scan.go
- pkg/querier/blocks_finder_bucket_scan_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/storage/tsdb/block/fetcher.go
- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket_index_metadata_fetcher_test.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/gateway_test.go
- pkg/storegateway/metadata_fetcher_metrics.go
- pkg/storegateway/metadata_fetcher_metrics_test.go
In 2.7 we announced the deprecation of `-compactor.consistency-delay` and `-blocks-storage.bucket-store.consistency-delay`. Since they're expected to be removed in the next release (2.9), I'm already opening a PR to remove them.
N/A
> Removed -compactor.consistency-delay and -blocks-storage.bucket-store.consistency-delay

- pkg/compactor/compactor_test.go
- pkg/compactor/shard_aware_deduplicate_filter.go
- pkg/storage/tsdb/block/fetcher.go
- pkg/storegateway/bucket_test.go
This is a refactoring PR while analysing how we can reduce the number of object storage `HEAD` API calls issued by the compactor. In Mimir we don't need `BaseFetcher` because it's just used by `MetaFetcher`, so we can just merge the two.
In this PR, as separate commits:
- [Removed block.NewRawMetaFetcher()](https://github.com/grafana/mimir/commit/37d5c3498f6d570b8c8a2f73e4e8c93bf32749a0) 
- [Removed BaseFetcher.NewMetaFetcher()](https://github.com/grafana/mimir/commit/3c41cb4608883328031e18d7882af4a37464f77f) 
- [Merge BaseFetcher and MetaFetcher](https://github.com/grafana/mimir/commit/72023b85dfc42142a438415a5da600c439df03e3)
N/A
> Refactoring: merge BaseFetcher and MetaFetcher

- CHANGELOG.md
- pkg/ruler/storage.go
While spending more time testing the event-based rules sync, I realised it may be desired to **not** cache the tenants listing.
The reason is that event-based rules sync do "invalidate" the per-tenant rule groups listing but the tenants listing is still cached, so when a tenant upload their first rule group the event-based sync will load it but the subsequent periodic sync may temporarily unload it because the tenant is not discovered when listing tenants.
Since caching tenants list is expected to have a very small impact on overall list bucket API calls reduction (most of them are due to rule groups listing, not tenants listing where we can list up to 1k tenants per API call) I simply propose to not cache the tenants listing.
N/A
> Ruler: do not cache tenants list bucket operations

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket_stores.go
Trying to find a postings strategy which takes fewer risks but more risks than `worst-case-small-posting-lists`
Related to https://github.com/grafana/mimir/issues/4593
> store-gateway: introduce more postings strategies

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/querier/blocks_store_queryable.go
- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/gateway_test.go
We, as Mimir maintainers, give the bucket index for granted but there's actually a configuration parameter to disable it. The bucket index is enabled by default since Mimir 2.0 and I'm not aware of any reason why anyone may want to disable it. Since keeping the support to run Mimir without bucket index involves some extra code in the querier and store-gateway, I propose to deprecate the configuration parameter and then remove it in Mimir 2.11.
Note: we'll have to change some integration tests to start using the bucket index everywhere, but we have to adapt them before 2.11.
N/A
> Deprecate -blocks-storage.bucket-store.bucket-index.enabled configuration parameter

- development/mimir-microservices-mode/config/mimir.yaml
Since consistency_delay was previously removed in #5050, this change removes it from mimir-microservices-mode.
> Removes consistency_delay setting from mimir-microservices-mode docker compose

- CHANGELOG.md
- cmd/metaconvert/Dockerfile
- cmd/mimir-continuous-test/Dockerfile
- cmd/mimir/Dockerfile
- cmd/mimirtool/Dockerfile
- cmd/query-tee/Dockerfile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
- development/mimir-monolithic-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
Updates Docker base images from `alpine:3.17.3` to `alpine:3.18.0`.
[3.18.0 release notes](https://alpinelinux.org/posts/Alpine-3.18.0-released.html)
> Update alpine to 3.18.0

- pkg/compactor/bucket_compactor.go
- pkg/compactor/bucket_compactor_test.go
- pkg/compactor/label_remover_filter.go
- pkg/compactor/label_remover_filter_test.go
- pkg/compactor/shard_aware_deduplicate_filter.go
- pkg/compactor/shard_aware_deduplicate_filter_test.go
- pkg/storage/tsdb/block/fetcher.go
- pkg/storegateway/bucket_index_metadata_fetcher.go
- pkg/storegateway/bucket_index_metadata_fetcher_test.go
- pkg/storegateway/metadata_fetcher_filters.go
- pkg/storegateway/metadata_fetcher_filters_test.go
- pkg/storegateway/metadata_fetcher_metrics.go
- pkg/storegateway/sharding_strategy.go
- tools/compaction-planner/main.go
- tools/list-deduplicated-blocks/main.go
While working on #5063 I found some dead code in the compactor, which I'm removing in this PR:
- [Removed unused Syncer.Partial()](https://github.com/grafana/mimir/commit/93fa3002123289856a73cc82fde50d6dc05a0224) 
- [Removed unexported blocks_meta_base_syncs_total metric](https://github.com/grafana/mimir/commit/5a9f28490ea10fa464c4432285d116d533028074) (was not exported)
- [Removed unused blocks_meta_modified metric](https://github.com/grafana/mimir/commit/069f38f388645cdb66a9bdc79d613f6608265200) (was not exported)
This PR will simplify #5063.
Part of #5056.
> Chore: remove dead code from compactor

- CHANGELOG.md
- go.mod
- tools/copyblocks/README.md
- tools/copyblocks/abs.go
- tools/copyblocks/bucket.go
- tools/copyblocks/gcs.go
- tools/copyblocks/main.go
Adds support for copying between two Azure Blob Storage buckets with the copyblocks tool. This tool previously only supported Google Cloud Storage buckets. I first moved the object storage calls behind a `bucket` interface and then added the Azure implementation.
Note:
- The only Azure authentication method supported is with the account name and key since that is required to generate the SAS token that must be passed in the copy call.
- Each copy on Azure has to be polled to see if it is done. I added backoff for these poll checks ~and didn't make them configurable to hopefully hide the complexity of this~ made them configurable.
- These changes (except some minor cleanup) were tested in a migration between development buckets. It went well!
Fixes N/A
> copyblocks: support copying between Azure Blob Storage buckets

- CHANGELOG.md
- pkg/compactor/bucket_compactor.go
- pkg/compactor/bucket_compactor_e2e_test.go
- pkg/compactor/compactor.go
- pkg/compactor/split_merge_compactor_test.go
- pkg/storage/tsdb/block/fetcher.go
- pkg/storage/tsdb/block/fetcher_test.go
- pkg/storage/tsdb/block/global_markers.go
- pkg/storage/tsdb/block/global_markers_test.go
- pkg/storage/tsdb/bucketindex/updater.go
The compactor issue a "object exists" API call for every block of each tenant every `-compactor.compaction-interval`. If you run a Mimir cluster with a large number of tenants (order of tens of thousands) and 1 year blocks retention, this can causes a very high number of API calls (order of hundred of millions per day). This PR removes such call.
The rationale of the change introduced in this PR is better explained [here](https://github.com/grafana/mimir/pull/5063/files#diff-949e4c7f50611c01ff05d35cfd88a3e0af9f07676c48acc02d0baf7193c86137R186-R207), but can be summarised as:
- Before this PR, we filtered out blocks marked for deletion after synching their metas. However, there's no need to do it that late, since we don't care about blocks marked for deletion, so in this PR I moved that …
> Compactor: do not issue object storage HEAD API calls to check if cached meta.json files still exist

- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
Use classic histograms in mimir-microservices-mode. This will allow dashboards that require classic histograms to continue working until prometheus support for scraping classic and native histograms is added.
> Use classic histograms in mimir-microservices-mode

- CHANGELOG.md
- pkg/ingester/client/custom.go
- pkg/ingester/ingester.go
This PR tidies up some changes introduced in #4886. It reduces some duplication between the streaming and non-streaming query path in the ingesters, and renames some methods to make them clearer.
Related to #4886
> Ingester query path refactoring: rename methods and reduce duplication

- docs/sources/mimir/get-started/about-grafana-mimir-architecture/index.md
Short explanation of the fact that series store samples in chunks, and their length.
> Docs: explain that series store samples in chunks

- pkg/ingester/activeseries/active_series_test.go
Several tests appeared to want colliding hash values, but only one had been fixed to work.
Use nicer label values created by pstibrany, and use them in every test that needs them.
> activeseries tests: check for hash collisions

- pkg/storage/tsdb/block/meta.go
While working on https://github.com/grafana/mimir/pull/5063 I noticed we have few structs inherited by Thanos but never used by Mimir. In this PR I'm proposing to cleanup them.
N/A
> Chore: remove unused ThanosMeta data

- docs/sources/mimir/references/architecture/components/store-gateway.md
This PR fixes the issue where the table of contents for the store-gateway docs page is displayed with unusual formatting:
This is caused by a missing heading in the hierarchy of headings, so this PR adds the missing heading.
(none)
> Add missing heading to store-gateway docs to fix broken page table of contents

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/util/validation/limits.go
This PR clarifies the docs for `ingestion_tenant_shard_size` in response to this question on the community Slack: https://grafana.slack.com/archives/C039863E8P7/p1685083701705699
(none)
> Clarify that value of ingestion_tenant_shard_size is not per-zone but across all ingesters.

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-object-store.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled/dashboards/mimir-object-store.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/object-store.libsonnet
This PR fixes an issue where some dashboard panels that show percentages have axes that go to 10000%, for example:
(none)
> Fix issue where dashboard panels that show percentages sometimes have axes that go from 0% to 10000%.

- CHANGELOG.md
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
This PR modifies `streamingChunkSeries` to share fields common to all series selected by the query. This reduces per-series memory consumption for series streamed from ingesters to queriers.
Relates to https://github.com/grafana/mimir/pull/4886
> Share values common to all streaming series selected in a query

- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-autoscaling.jsonnet
- operations/mimir/autoscaling.libsonnet
This PR adds support for specifying `metric_type` in the ScaledObject trigger. Values allowed by KEDA are `AverageValue` (default), `Value` and `Utilization`, see https://keda.sh/docs/2.9/concepts/scaling-deployments/#triggers for details.
> jsonnet: Support metricType in ScaledObject triggers

- pkg/querier/batch/batch.go
- pkg/querier/batch/batch_test.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/batch/merge.go
- pkg/querier/batch/merge_test.go
- pkg/querier/batch/non_overlapping.go
- pkg/querier/batch/non_overlapping_test.go
- pkg/querier/distributor_queryable_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/querier/distributor_queryable_test.go
- pkg/querier/iterators/chunk_merge_iterator.go
- pkg/querier/iterators/chunk_merge_iterator_test.go
- pkg/querier/matrix.go
- pkg/querier/partitioner.go
Implements the re-use of iterator for `batch.NewChunkMergeIterator`. Although querier uses two other chunk iterators, since this one is enabled by default (and I guess most commonly), I gave this one a try first.
~While this benchmark verifies the re-use of iterators is working for this one, it was not trivial to verify that at the query level, it is indeed passing down the used iterator for re-use - I need some help verifying this.~ See https://github.com/grafana/mimir/pull/5097#issuecomment-1567008742
Here are the benchmark results (without the chunk pool that was added and later removed from this PR):
```
benchmark                                                                                                        old ns/op     new ns/op     delta …
```
> Reuse iterator in `batch.NewChunkMergeIterator`

- pkg/mimirtool/commands/analyse_dashboards.go
- pkg/mimirtool/commands/analyse_grafana.go
- pkg/mimirtool/commands/analyse_rulefiles.go
- pkg/mimirtool/commands/analyse_ruler.go
Mimir's users might want to reuse mimirtool to industrialize metrics usage analysis. The current state require scripting to wrap everything around.
For example, users might want to do something like:
```bash
source mimirtool.env
mimirtool analyze grafana
mimirtool analyze ruler
mimirtool analyze prometheus  --prometheus-http-prefix="/prometheus"
```
By using vendoring it become simpler to create a one-liner or an API that analyze a tenant.
This commit is the first step toward this. It splits each analyzer in two func:
* `run` which is use by the command line, call the analyzer and produce an output file.
* `Analyzer*` which takes a few argument and actually does the analysis.
A second step for refactoring [analyse_prometheus](https://github.com/grafana/mimir/blob/main/pkg/mimirtool/command …
> Mimirtool: refactor analyzer to facilitate usage through vendoring

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/querier/querier.go
This PR deprecates the `-querier.iterators` and `-querier.batch-iterators` flags.
https://github.com/grafana/mimir/issues/5107
> Deprecate iterator configuration flags

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_ring.go
- pkg/ingester/ingester_ring_test.go
- pkg/mimir/mimir.go
- pkg/storage/tsdb/caching_config.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/config_test.go
This removes flags that were deprecated in 2.7.
Relates to #5112
> Remove deprecated flags for release 2.9

- CHANGELOG.md
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
This PR renames `streamingChunkSeriesConfig` to `streamingChunkSeriesContext`, as per [this suggestion](https://github.com/grafana/mimir/pull/5094#discussion_r1211346203) received after merging #5094.
Addresses feedback from #5094 received after merging.
> Rename `streamingChunkSeriesConfig` to `streamingChunkSeriesContext`

- pkg/storegateway/indexheader/binary_reader.go
- pkg/storegateway/indexheader/index/symbols.go
- pkg/storegateway/indexheader/index/symbols_test.go
- pkg/storegateway/indexheader/stream_binary_reader.go
* The symbol reference in prometheus' TSDB v1 index is an offset into the index file. In V2 it is the sequence number of the symbol.
While working on https://github.com/grafana/mimir/pull/5073 I noticed that the symbols offsets are slightly misaligned for V1 symbols. 
This PR fixes three bugs
* label names and values symbols caches were misaligned
* __label names cache__ was using the index header offset to store the cache items, but using the TSDB index to look them up (difference of 9)
* This results in mostly cache misses; but it also interacts with the other bug of returning symbols references relative to the start of the symbols table, not the whole index, so there can be incorrect values returned as well
* __label values cache__ was using the TSDB offset to lookup and store cache …
> store-gateway: fix TSDB index v1 symbols lookup and caching

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/indexheader/encoding/encoding.go
- pkg/storegateway/indexheader/encoding/reader.go
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/index/symbols.go
- pkg/storegateway/indexheader/index/symbols_test.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/stream_binary_reader.go
- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
Related to https://github.com/grafana/mimir/issues/4593#issuecomment-1550928468
A symbol in this context is a string stored in the TSDB index. Every timeseries in the TSDB index has a reference to the symbols in its labels instead of the actual strings. The symbols table (mapping from symbol reference to string) is also present in the index header that the store-gateway stores locally.
For series requests the current way of reading symbols is as follows: for each symbol (label name or label value)
* the lazy index header reader acquires a read lock on all index header readers and checks `time.Now()` ([code](https://github.com/grafana/mimir/blob/db5713d7c2fde8ac1c22f51919e43e7821060e8e/pkg/storegateway/indexheader/lazy_binary_reader.go#L168-L175))
* label names: these are already cached in …
> store-gateway: reduce syscalls for looking up symbols

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-dep.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
Updates nginx to 1.24, since it is the new nginx stable branch and 1.22 is now legacy (can be seen [here](https://nginx.org/en/download.html)).
I did a local deploy for a sanity test and it was uneventful.
[1.24 changelog](https://nginx.org/en/CHANGES-1.24)
> Helm: update nginx to 1.24

- CHANGELOG.md
- docs/sources/mimir/operators-guide/tools/mimirtool.md
- pkg/mimirtool/commands/rules.go
This PR adds two parameters (`namespaces-regex`, `ignore-namespaces-regex`) to the `mimirtool` diff and sync commands. This allows the user to ignore (or include) a set of namespaces based on patterns.
Especially useful for Grafana Cloud, where we provision rules for integrations. These can then be ignored by passing `--ignore-namespaces-regex='integrations-.*'`.
> feat: add namespaces-regex and ignore-namespaces regex to mimirtool

- .golangci.yml
`golangci-lint` is configured with a timeout of 5 minutes. However, this is occasionally not enough on CI ([example of a build that timed out](https://github.com/grafana/mimir/actions/runs/5172136060/jobs/9316193808), [example of the same commit passing after a retry](https://github.com/grafana/mimir/actions/runs/5172136060/jobs/9316466129)).
This PR increases the timeout to increase build stability to buy some time until we can investigate why linting is taking so long.
(none)
> Increase linter timeout

- CHANGELOG.md
- operations/mimir/config.libsonnet
- operations/mimir/querier.libsonnet
- operations/mimir/query-frontend.libsonnet
While reviewing querier jsonnet, I noticed there are config options to set querier and query-frontend replicas which follow a convention different than other stateless services (e.g. distributors where we just use overrides). To keep consistency with other stateless services, I propose to simply remove these config fields (e.g. we're not using them at Grafana Labs).
N/A
> Jsonnet: remove $._config.querier.replicas and $._config.queryFrontend.replicas

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/recording-rules.yaml
- operations/mimir-mixin-compiled/rules.yaml
- operations/mimir-mixin/config.libsonnet
- pkg/mimirtool/commands/analyse_rules_test.go
- pkg/mimirtool/commands/testdata/prometheus_rules.yaml
Instead of assuming there is a metric `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` which would be provided by the "Kubernetes mixin", use the underlying cAdvisor metric like we do for everything else.
(Also use `rate[1m]` which gives better information than `irate[5m]`)
- NA Documentation - we never documented the need for the upstream rule, so don't need to take that out.
> Mixin: remove dependency on upstream recording rules

- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/ingester.go
This PR changes the active series tracker to use series refs rather than hashes. This has the following advantages:
1. We no longer need to handle hash conflicts, since series refs are guaranteed unique by the tsdb.
2. It's now trivial to implement a `Contains(ref)` method on the active series tracker, which I will use to enhance the cardinality API so we can compute active series in the label values cardinality api. (This will be a follow up PR: #5135 )
I've run a local Mimir cluster and simulated series churn using the mimir-continuous-test tool, and active series appears to work just as before. 
For completeness, I ran the existing benchmarks and got the following:
<details><summary>Details</summary>
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/mimir/pkg/ingester/activeseries …
```
> Track active series by ref instead of hash

- .github/workflows/test-build-deploy.yml
- Makefile
- docs/internal/contributing/how-to-upgrade-golang-version.md
- docs/internal/how-to-update-the-build-image.md
This PR modifies our GitHub Actions workflow to load the build image tag from `Makefile`, rather than having it specified in multiple places.
If this works well, we could likely also use a similar technique to set the Go version for the `setup-go` step for the integration tests by checking the version of Go used in the build image.
(none)
> Retrieve build image from Makefile rather than duplicating it in GitHub Actions workflow file.

- CHANGELOG.md
- docs/sources/mimir/operators-guide/tools/query-tee.md
- tools/querytee/proxy_endpoint.go
- tools/querytee/proxy_endpoint_test.go
The query-tee doesn't proxy the content-type HTTP header. This breaks some integrations, such as Grafana Alerting.
> query-tee: proxy Content-Type response header

- .github/workflows/helm-ci.yml
helm-ci: do not hardcode build image version (#5187)
Based on #5184
(cherry picked from commit f59d4d988a4de314fbd10303593305c44d4079d6)
> Backport 5187 to release 2.9

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
I'm analyzing some queries and I would have found useful having the response size (bytes) as part of "query stats" log. In this PR I'm proposing it.
N/A
> Add "response_size_bytes" field to "query stats" log

- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/ingester.go
While doing a post-merge review of #5134 I noticed that we don't need anymore to retain a copy of series labels in the active series tracker, because it was just used to check for collisions (which we can't have anymore because the `ref` is unique).
N/A
> Do not retain a copy of series labels in the active series tracker

- pkg/ingester/client/streaming_test.go
This PR fixes a test that occasionally flakes due to a race condition.
(none)
> Fix flaky TestSeriesChunksStreamReader_ChunksLimits test.

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/querier/querier.go
Based on our testing at Grafana Labs, 128 seems to be a reasonable balance of memory consumption and CPU overhead of managing batches.
(none)
> Adjust default value of `-querier.streaming-chunks-per-ingester-buffer-size`

- CHANGELOG.md
- pkg/ingester/client/streaming_test.go
- pkg/util/globalerror/errors.go
- pkg/util/limiter/query_limiter.go
Refine error messages for per-tenant query limits, informing the user of the preferred strategy for not hitting the limit, _in addition to_ how they may tweak the limit. It's preferred to not increase these limits if possible, since they're designed to prevent Mimir instability. Affected limits:
* max_fetched_chunks_per_query
* max_fetched_chunk_bytes_per_query
* max_fetched_series_per_query
I've taken inspiration from the [runbooks](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/operators-guide/mimir-runbooks/_index.md#err-mimir-max-chunks-per-query) for the limits in question on the strategy (same for all three) for not hitting them.
> Querier: Refine error messages for per-tenant query limits

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/distributor/distributor.go
- pkg/ingester/client/buffering_client.go
- pkg/ingester/client/buffering_client_test.go
- pkg/ingester/client/client.go
- pkg/ingester/client/mimir_util.go
- pkg/mimirpb/timeseries.go
- pkg/util/pool/fast_releasing_pool.go
- pkg/util/pool/fast_releasing_pool_test.go
- pkg/util/pool/pool_test.go
When distributor receives a write request, distributor splits it into multiple smaller requests, and forward each of them to single ingester. In this step distributor needs to marshal protobuf messages. This PR adds pooling of buffers when doing this marshalling.
The actual pooling logic is implemented in a wrapper to `IngesterClient` (grpc interface for communicating with ingester).
Our benchmark in dev environment show about 7% reduction of CPU time with this change.
Result of benchmark in this PR shows reduction of allocations per `Push` call (for purpose of this benchmark, `Push` only calls message `Marshal`):
```
name                                                      time/op
WriteRequestBufferingClient_Push/push_without_pooling-10  7.18µs ± 0% …
```
> Pool buffers when sending write request

- pkg/api/api_test.go
- pkg/frontend/v2/frontend_test.go
- pkg/ingester/client/buffering_client_test.go
- pkg/mimir/mimir_test.go
- pkg/mimir/server_service_test.go
- pkg/scheduler/scheduler_test.go
- pkg/util/gziphandler/gzip_test.go
- tools/querytee/proxy.go
- tools/querytee/proxy_test.go
Trying to kill mac OS X firewall warning popup when running tests locally.
Still haven't found all the places :(
> Use localhost:0 as bind address when creating listening socket.

- pkg/mimirtool/commands/analyse_grafana.go
- pkg/mimirtool/commands/analyse_prometheus.go
- pkg/mimirtool/commands/analyse_ruler.go
This is the second step for refactoring mimirtool's analyzers. The purpose is to enable Mimir's users to reuse mimirtool to industrialize metrics usage analysis via vendoring in downstream applications.
With it the refactoring is complete and users can reuse it. Below is an example of a quick and dirty prototype
```go
package main
import (
"context"
"encoding/json"
"fmt"
"log"
"net/url"
"time"
"github.com/grafana-tools/sdk"
"github.com/grafana/mimir/pkg/mimirtool/client"
"github.com/prometheus/common/model"
mimirtoolClient "github.com/grafana/mimir/pkg/mimirtool/client"
analyzer "github.com/grafana/mimir/pkg/mimirtool/commands"
"github.com/prometheus/client_golang/api"
v1 "github.com/prometheus/client_golang/api/prometheus/v1"
"github.com/prometheus/common/config"
)
func main() {
ctx := …
```
> Refactor analyzer

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- integration/ingester_test.go
- pkg/distributor/distributor.go
- pkg/distributor/query.go
- pkg/mimir/modules.go
- pkg/querier/querier.go
This PR adds experimental support for querying the minimal set of ingesters required to reach quorum.
With `-querier.minimize-ingester-requests=false` (the default), queriers behave as they do today: they send a request to all ingesters in the tenant's shard, wait until quorum is reached and then cancel any outstanding unnecessary requests.
With `-querier.minimize-ingester-requests=true`, queriers instead initially only send requests to the minimum number of ingesters required to reach quorum, and initiate requests to further ingesters if any of the initial requests fail. (If enough requests fail that quorum is impossible, all requests are cancelled as before, and no further requests are made.)
This reduces querier and ingester resource utilisation on the happy path, at the cost of …
> Add option to query minimum set of ingesters

- pkg/compactor/blocks_cleaner.go
- pkg/compactor/blocks_cleaner_test.go
- pkg/storage/tsdb/bucketindex/updater.go
This PR introduces some changes to make it easier to track the progress of a cleanup job. This is useful when some portion of the cleanup job takes very long.
* add duration to the lgo lines for a failed cleanup job
* propagate `run_id` log label to per-user runs; this makes it easier to track a single run which starts overlapping with following runs
* add log lines at different stages of updating the bucket index and carrying out blocks deletion
* after fetching existing bucket index
* after marking blocks for deletion
* after fetching list of blocks
* after updating meta.json for new blocks
* after listing deletion markers
* after updating deletion markers for new blocks
* after cleaning up partial blocks
- [n/a] `CHANGELOG.md` updated - …
> compactor: add more log lines for blocks clean-up

- operations/helm/charts/mimir-distributed/README.md
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval_test.go
Fixes a TODO by restoring native histogram test cases for TestInstantQuerySplittingCorrectness now that native histograms can use the division operator.
Follow up to https://github.com/prometheus/prometheus/issues/12250
> Restore native histogram test cases for TestInstantQuerySplittingCorrectness

- operations/mimir/autoscaling.libsonnet
- operations/mimir/read-write-deployment/autoscaling.libsonnet
This PR exposes two helpers from the Jsonnet library to downstream consumers: `newQueryFrontendScaledObject` and `removeReplicasFromSpec`:
* `newQueryFrontendScaledObject` is useful when creating a parallel query path for testing query path changes
* `removeReplicasFromSpec` is useful when adding autoscaling to a deployment and was already duplicated in the Jsonnet library
(none)
> Expose `newQueryFrontendScaledObject` and `removeReplicasFromSpec` in Jsonnet library

- CHANGELOG.md
- pkg/frontend/querymiddleware/cardinality_query_cache.go
- pkg/frontend/querymiddleware/cardinality_query_cache_test.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
In #5212 I've added the optional and experimental support to lookup cardinality queries from the cache. However, we don't have a way to track the cache hit ratio specifically for the cardinality API endpoints. Reason is that today we measure the query-frontend cache hit ratio looking at the underlying memcache metrics (e.g. `thanos_cache_memcached_hits_total / thanos_cache_memcached_requests_total`) which are not split by request type / route (and not easy to do).
In this PR I propose to add a couple of new metrics which specifically track the query results cache cache hit ratio. I haven't changed the "Mimir / Queries" dashboard yet because I would like to see the new metrics deployed first before changing the dashboard (changes will be backward compatible).
- The new …
> Add cortex_frontend_query_result_cache_requests_total and cortex_frontend_query_result_cache_hits_total metrics

- docs/sources/mimir/references/http-api/index.md
Following up the cardinality query result cache support introduced in https://github.com/grafana/mimir/pull/5212, in this PR I proposed to do small changes to the cardinality API doc:
- Remove "realtime" but it's not guaranteed if cache is enabled
- Add a mention about the new query results cache support
- Move the inmemory/action description to a dedicated section, to help the reader to jump to the section of their interest
N/A
> Doc: improve cardinality API doc

- CHANGELOG.md
- pkg/distributor/distributor.go
#5202 introduced the option `-querier.minimize-ingester-requests` (default false) to minimize requests to ingesters. The subsequent PR #5136 used the "minimize requests" code for the cardinality queries and enabled it (hardcoded). I think would be better if we honor `-querier.minimize-ingester-requests` in the cardinality queries too, which is what I'm proposing in this PR.
N/A
> Honor -querier.minimize-ingester-requests configuration in the cardinality queries too

- Makefile
- mimir-build-image/Dockerfile
This PR updates golangci-lint to 1.53.2, to match the version that we use in internal repository and fix new issues reported by it.
> Update golangci-lint to 1.53.2

- pkg/ruler/compat_test.go
- pkg/ruler/ruler_test.go
I looked into #5244 and I'm not 💯 sure why `TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged` failed in CI. I haven't been able to reproduce it locally, not even adding few random sleeps here and there (I suspect a timing issue). The CI logs didn't help much because I can't distinguish logs between the 2 ruler instances in the test, so in this PR:
1. Use `test.Poll()` for `getLocalRules()` assertions
2. Add the instance ID as log field, so that we can better distinguish logs between ruler instances
Maybe fixes #5244
> Maybe fix TestRuler_NotifySyncRulesAsync_ShouldTriggerRulesSyncingAndCorrectlyHandleTheCaseTheTenantShardHasChanged flakyness

- go.mod
We're used to require the last 2 minor versions of golang. Since we build with 1.20, can we bump the minimum version from 1.18 to 1.19?
N/A
> Require golang 1.19

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/distributor/query_test.go
This PR adds support for request minimisation (aka "make requests to only two of three ingester zones to start with") for other query APIs:
* LabelNames
* LabelValuesForLabelName
* LabelNamesAndValues
* MetricsForLabelMatchers
* MetricsMetadata
* QueryExemplars
Relates to https://github.com/grafana/mimir/pull/5202
> Use ingester request minimisation for other query APIs

- .github/workflows/test-build-deploy.yml
- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/client/buffering_client_test.go
- pkg/ingester/ingester.go
- pkg/mimirpb/compat.go
- pkg/mimirpb/compat_slice.go
- pkg/mimirpb/compat_stringlabels.go
- pkg/mimirpb/compat_test.go
- pkg/mimirpb/timeseries.go
- pkg/mimirpb/timeseries_test.go
- pkg/querier/block_test.go
- pkg/storegateway/series_refs.go
This is porting Mimir to use https://github.com/prometheus/prometheus/pull/10991
~Still a bit experimental.~
~Requires a couple more changes in mimir-prometheus; currently overriding to branch `fixup-labels-usage3`.~
> Store series labels as a single string, to save memory

- pkg/storegateway/bucket_index_postings.go
- pkg/storegateway/bucket_index_postings_test.go
Excluding the `__name__` posting group resulted in increased API calls because the selected series were more sparse in the index. The reason for this is that series are first sorted by the `__name__` label if they don't have any labels that start with an uppercase letter. Selecting sparse series results in more API calls because the series are more likely to belong to different metric names and be spread across the TSDB index.
This PR modifies the `worst-case` strategy to always include `__name__`. I opted for including this change in the existing `worstCaseFetchedDataStrategy` as opposed to wrapping `worstCaseFetchedDataStrategy` in a new strategy because it will make testing a bit easier and there's no need for modularity because we're eventually aiming to have only a single strategy. …
> store-gateway: always include `__name__` posting group in selection

- CHANGELOG.md
- cmd/metaconvert/Dockerfile
- cmd/mimir-continuous-test/Dockerfile
- cmd/mimirtool/Dockerfile
- cmd/query-tee/Dockerfile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
- development/mimir-monolithic-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
This backports #5274 and #5276 to the 2.9 release.
> [release-2.9] Bump alpine to 3.18.2

- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
I generally prefer to not have the component(s) I am developing on in a container for ease/speed of iteration, hooking up debuggers etc.
Dependencies can remain in containers for ease of use, treating them as a black box.
Opening the memberlist ports for each service allows running an uncontainerized component against the containerized dependencies, with memberlist enabled.
This PR also opens the memcached port for the same reasons.
> development: microservices mode docker compose open memberlist ports

- pkg/querier/blocks_finder_bucket_scan_test.go
This PR fixes a flaky test, `TestBucketScanBlocksFinder_StopWhileRunningTheInitialScanOnManyBlocks` that could sometimes panic due to missing mock setup.
I believe this was introduced in #5063 - previously, we always called `Exists` first, but as of #5063, this is no longer true, so we need to mock `Get` as well. 
Fixes #5267
> Fix flaky test

- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alertmanager.libsonnet
- operations/mimir-mixin/alerts/alerts.libsonnet
- operations/mimir-mixin/alerts/autoscaling.libsonnet
- operations/mimir-mixin/alerts/blocks.libsonnet
- operations/mimir-mixin/alerts/compactor.libsonnet
- operations/mimir-mixin/alerts/continuous-test.libsonnet
Users install the mixin from main branch which points to the new manage/mimir-runbooks, but the latest documentation still has the old link to operators-guide/mimir-runbooks.
Even if we forget to update the link it will work after the next release due to aliases.
Community slack: 
It looks like the runbook url changed in the mixin
runbook_url: https://grafana.com/docs/mimir/latest/operators-guide/mimir-runbooks/#mimiringesterunhealthy
runbook_url: https://grafana.com/docs/mimir/latest/manage/mimir-runbooks/#mimiringesterunhealthy
That new url https://grafana.com/docs/mimir/latest/manage/mimir-runbooks/#mimiringesterunhealthy seems to be broken.
- N/A fixes inconsistency `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
> Mixins: use old aliased operators-guide/mimir-runbooks url

- .github/workflows/compare-helm-with-jsonnet.yml
- .github/workflows/test-build-deploy.yml
- Makefile
- development/mimir-microservices-mode/compose-up.sh
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/compose-up.sh
- development/mimir-read-write-mode/dev.dockerfile
- mimir-build-image/Dockerfile
This pull request aims to centralize the Go version settings in the Mimir project. To achieve this we retrieve the Go version always from mimir-build-image.
Previously, the Go version setting was scattered across different parts of the Mimir project, making it difficult to manage and update consistently. By centralizing the Go version definition in the Makefile, we establish a single source of truth for the project's Go version.
This change simplifies the process of updating the Go version in the future, as it can now be modified in just one place. Additionally, any component or module that needs to reference the Go version can retrieve it from the centralized location defined in the Makefile.
The next step could be implementing a linter to enforce the rule of forbidding the use of the Go …
> Chore: remove hardcoded go version

- integration/distributor_high_concurrency_test.go
- integration/e2emimir/client.go
This PR adds integration test for distributor with many concurrent writers.
Config flags from #5195 and #5137 are tested as well, to see if they affect correctness in any way.
> Add integration test for distributor with multiple concurrent clients

- pkg/storegateway/bucket_store_server_test.go
Some of the largest test cases of BenchmarkBucketStore_Series failed because the result is larger than the default gRPC message size of 4MiB. This PR sets the limit in tests to 1GiB.
> store-gateway tests: increase gRPC receive message size

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
While reviewing #5182 I realized that the spans we have in the store-gateway aren't very consistent and could use some more information. This PR does this. It leaves out the bucket_store_merge_all span, which is also somewhat incorrect, but that is being improved in #5182 (and I don't want to create extra conflicts with that PR).
For reference this is how the spans look like at present
> store-gateway: clean up spans

- pkg/mimirpb/timeseries.go
- pkg/mimirpb/timeseries_test.go
After reviewing the profile of one of the aggregators in ops, we have noticed that approximately `18%` of the total process allocations originate from the `(*PreallocTimeseries).SortLabelsIfNeeded` method, specifically when calling the `sort.Slice` function responsible for performing the sorting.
This appears to be primarily due to the fact that `sort.Slice` uses reflection to perform the sorting, which results in an overhead of additional allocations.
This PR replaces the usage of that call with its counterpart `sort.SortFunc`, which is type-oriented and therefore does not need to make use of `reflect` package internally.
Additionally, as part of this PR, a new bechmark named `BenchmarkPreallocTimeseries_SortLabelsIfNeeded`  is included to validate this change. The preliminary results …
> mimirpb: optimize label sorting in timeseries type

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v4.5.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/values.yaml
Make the 4.5.0-rc.0 release.
N/A
> Helm: release 4.5.0-rc.0

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/mimir/config.libsonnet
We're running the ruler storage cache in prod at Grafana Labs since we weeks and we're happy about it. In this PR I propose to upstream it to our OSS Jsonnet and Helm.
N/A
> Jsonnet / Helm: configure the ruler storage cache when the metadata cache is enabled

- docs/sources/mimir/migrate/_index.md
- docs/sources/mimir/send/_index.md
Fix #4508 
Note to reviewers, all of the build errors from `doc-validator` have been addressed and can safely be ignored.
> Doc: Add top-level Send metric data section.

- CHANGELOG.md
- pkg/distributor/query.go
- pkg/ingester/client/streaming.go
- pkg/ingester/ingester.go
This PR makes a number of small improvements to the traces emitted while querying:
* When streaming chunks is enabled, ingesters now emit events after sending all series labels and after sending all chunks, and these events include the number of series, chunks and batches of chunks sent, as appropriate.
* When streaming chunks from an ingester, queriers now emit a span specifically while streaming chunks from ingesters (ie. the time from when the first batch of chunks is read from the stream until the last batch is read from the stream)
* Queriers now emit a parent span for query calls to each ingester, with the span emitted for the gRPC call and the span introduced above as children. This parent span is emitted regardless of whether streaming is enabled or not.
This is what a trace of a …
> Improve traces for queries

- operations/helm/charts/mimir-distributed/templates/overrides-exporter/overrides-exporter-dep.yaml
- operations/helm/charts/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
Remove a newline in smoketest and overrides_exporter helm chart when global.extraEnv is set.
```
$ helm template . --set 'global.extraEnv[0].name'=k1 --set 'global.extraEnv[0].value'=v1
-----
apiVersion: batch/v1
kind: Job
metadata:
name: release-name-mimir-smoke-test
labels:
helm.sh/chart: mimir-distributed-4.5.0-weekly.243
app.kubernetes.io/name: mimir
app.kubernetes.io/instance: release-name
app.kubernetes.io/component: smoke-test
app.kubernetes.io/version: "r243"
app.kubernetes.io/managed-by: Helm
annotations:
"helm.sh/hook": test
namespace: "default"
spec:
backoffLimit: 5
completions: 1
parallelism: 1
selector:
template:
metadata:
labels:
helm.sh/chart: mimir-distributed-4.5.0-weekly.243
app.kubernetes.io/name: mimir
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: …
```
> remove newline when globalEnv is set

- docs/sources/mimir/configure/about-runtime-configuration.md
- Satisfies some external links to `about-runtime-configuration`
> fix: added documentation alias for `about-runtime-configuration`

- development/mimir-microservices-mode/config/prometheus.yaml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/config/prometheus.yaml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/config/prometheus.yaml
- development/mimir-monolithic-mode/docker-compose.yml
Now that the option to scrape both kinds of histograms is released in Prometheus, re-enable native histograms in our docker compose setups so we won't break our older dashboards and can still use the newer histograms.
Reverts change in https://github.com/grafana/mimir/pull/5080
> Scrape both classic and native histograms in docker compose

- pkg/storage/chunk/chunk_test.go
Going up to 2040 samples per chunk resulted in this test taking around five minutes to run with `-race`.
Since TSDB is currently hard-coded to stop at 120 samples, this seems unnecessary. Stopping at 216 takes it down to about 8 seconds.
> storage/chunk: TestChunk with smaller sizes

- CHANGELOG.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/client/client.go
This PR clarifies the docs for the `-ingester.client.*` configuration flags. These flags are used by both distributors and queriers, but the docs currently only mention distributors.
(none)
> Clarify that `-ingester.client.*` flags are used by both distributors and queriers

- CHANGELOG.md
- go.mod
- go.sum
- integration/ingester_test.go
- vendor/github.com/prometheus/prometheus/promql/engine.go
- vendor/modules.txt
This PR fixes the issue where queries that use the `timestamp()` function fail with an error like `execution: attempted to read series at index 0 from stream, but the stream has already been exhausted` if streaming chunks from ingesters to queriers is enabled.
This brings in the changes from https://github.com/grafana/mimir-prometheus/pull/506.
https://github.com/grafana/mimir/pull/4886
> Fix issue where queries that use the `timestamp()` function fail when streaming chunks from ingesters to queriers

- development/mimir-microservices-mode/compose-down.sh
- development/mimir-microservices-mode/compose-up.sh
- development/mimir-monolithic-mode-with-swift-storage/compose-down.sh
- development/mimir-monolithic-mode-with-swift-storage/compose-up.sh
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/compose-down.sh
- development/mimir-monolithic-mode/compose-up.sh
- development/mimir-monolithic-mode/docker-compose.yml
- development/mimir-read-write-mode/compose-down.sh
- development/mimir-read-write-mode/compose-up.sh
Adds bash fn to call 'docker compose' if 'docker-compose' is not available.
This pattern could be flipped, trying to call 'docker compose' first if it's available, since that is the new one. But I think most users are on systems still with `docker-compose`, plus the order doesn't _really_ matter.
Also address shellcheck warnings, adding quoting around shell variable expansion. 
> development: microservices mode docker compose scripts add compatibility for newer compose and address shellcheck linting

- pkg/querier/distributor_queryable_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
This PR prevents confusing "attempted to read series at index 0 from stream, but the stream has already been exhausted" errors from being returned when a streaming series is read multiple times. This should never happen in the real world, but we've already encountered one issue where the PromQL engine recreates iterators for each series multiple times.
(none)
> Guard against the same streaming series being read multiple times

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin/dashboards/queries.libsonnet
Fixes syntax of matchers used for measuring lazy-load gate latency
Related to #5313
> Correct matchers used in mixin panel introduced in #5313

- pkg/querier/distributor_queryable_streaming_test.go
This PR fixes an issue introduced by #5362. 
The original PR was built successfully by CI when the PR was raised, but a breaking change was introduced before #5362 was merged that did not retrigger the build for #5362.
#5362
> Fix breaking change introduced after #5362 was created

- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/client/client.go
This PR addresses https://github.com/grafana/mimir/pull/5375#discussion_r1246279037.
#5375
> Clarify that `-ingester.client.*` flags are used by rulers too

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- integration/distributor_high_concurrency_test.go
- integration/distributor_test.go
- pkg/distributor/distributor.go
- pkg/mimir/mimir.go
- pkg/mimirpb/timeseries.go
- pkg/mimirpb/timeseries_test.go
This PR removes `-distributor.write-requests-buffer-pooling-enabled` and `-timeseries-unmarshal-caching-optimization-enabled` flags that could be used to disable optimizations in distributor message marshalling. We're now using these optimizations in production for two weeks, and we haven't noticed any issues with them.
While these optimizations didn't visibly decrease CPU usage in our environment, they help to reduce memory allocation rate.
> Remove flags to disable optimizations

- CHANGELOG.md
- pkg/frontend/config.go
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/mimir/modules.go
- pkg/querier/error_translate_queryable.go
- pkg/querier/error_translate_queryable_test.go
Modify the querier to no longer convert HTTP 503 query failures to HTTP 500, but instead pass on the HTTP 503 (service unavailable) code. This code may be returned when the ingester rejects a query due to request limiting.
Also some things I came across while debugging:
* Fix some comments
* Rename `requestCh` to `requestsCh` for consistency/readability
I've tested manually locally and in cloud, to verify that the HTTP status code 503 gets returned to clients when read requests are rejected due to utilization based ingester limiting.
TODO:
> Querier: Pass on HTTP 503 status code

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/mimir/modules.go
- pkg/util/validation/limits.go
Moves `cache_unaligned_requests` into the limits, so that it can be overridden per-tenant.
Allows operators to turn this on for the rare tenants that will actually need it, without ballooning the cache for everyone else in a multi-tenant cell that does not need this.
Global parameter `cacheUnalignedRequests` was removed from `splitAndCacheMiddleware` in favor of access to limits helper functions.
Fixes #5253
> issues/5253 convert cache-unaligned-requests to per-tenant config

- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
`utilizationScanner.String()` was introduced in a initial implementation that supported multiple ways to detect CPU/memory utilization (proc, cgroup v1 and cgroup v2). However, we currently support only proc so there's no much value adding it to logs. Removing it to cleanup code.
N/A
> Chore: remove utilizationScanner.String()

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/golang/glog/glog.go
- vendor/github.com/golang/glog/glog_file.go
- vendor/github.com/golang/glog/glog_file_linux.go
- vendor/github.com/golang/glog/glog_file_other.go
- vendor/github.com/golang/glog/glog_file_posix.go
- vendor/github.com/golang/glog/glog_flags.go
- vendor/modules.txt
Upgrade indirect dependency github.com/golang/glog from v1.1.0 to v1.1.1.
Most importantly the upgrade to v1.1.1 [stops](https://github.com/golang/glog/commit/9c9801e69114b582b12aa7010c75fe2105ae23b3) Mimir tools such as `copyblocks` and `compaction-planner` from panicking when you pass the `-help` flag:
```
$ ./tools/compaction-planner/compaction-planner -help
[...]
panic calling String method on zero glog.vModuleFlag for flag vmodule: runtime error: invalid memory address or nil pointer dereference
```
> Upgrade to golang/glog v1.1.1

- cmd/mimirtool/main.go
backfil was added at the end and the helm text looks like this
<details>
<summary>Details</summary>
```
mimirtool --help
usage: mimirtool [<flags>] <command> [<args> ...]
A command-line tool to manage Mimir and GEM.
Flags:
--help                      Show context-sensitive help (also try --help-long and --help-man).
--log.level="info"          set level of the logger
--push-gateway.endpoint=PUSH-GATEWAY.ENDPOINT
url for the push-gateway to register metrics
--push-gateway.job=PUSH-GATEWAY.JOB
job name to register metrics
--push-gateway.interval=1m  interval to forward metrics to the push gateway
Commands:
help [<command>...]
Show help.
acl generate-header --id=ID --rule=RULE
Generate the header that needs to be passed to the datasource for setting ACLs.
alerts verify [<flags>]
Verifies …
```
> mimirtool: order command in help text alphabetically

- CHANGELOG.md
- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
Yesterday I enabled the CPU-based limiting in a production cell and I noticed requests to be limited right after the ingester startup, even if the 1m CPU utilization average (as computed by `rate(container_cpu_usage_seconds_total[1m])`) was way below the limit (about the half).
After some investigation, I realised that the limit triggered right after the limiter was started. We start the limiter after we replay the TSDB WALs in the ingester, and right before the ingester is ready to accept samples. Looking at logs of ingesters where the limit triggered, they all show the same pattern:
```
ts=2023-06-30T18:07:17.632955811Z caller=ingester.go:2210 level=info msg="successfully opened existing TSDBs"
ts=2023-06-30T18:07:17.633186146Z caller=mimir.go:834 level=info msg="Application started" …
```
> Add warmup period to CPU utilization moving average

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Today I was on-call and I noticed the alert `MimirIngesterRestarts` triggers more frequently than I expected. Turns out using `process_start_time_seconds` is not a good strategy because it will count re-schedulings and rolling updates. Instead, if we use `kube_pod_container_status_restarts_total` we also count container restarts, like OOMKilled or panics. This PR changes it.
I did a back test of the alert over the last 7d. The **old alert** query returned results these many times:
The **new alert** would have returned results only 1 case, which is legit because there were ingesters OOMKilled:
N/A
> Fix MimirIngesterRestarts to fire only when the ingester container is restarted

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
- pkg/ingester/shipper.go
- pkg/ingester/shipper_test.go
Earlier today we've got an issue for which I was expecting `MimirIngesterHasNotShippedBlocks` to fire, but it didn't. Turns out the reason is that the metric `thanos_shipper_last_successful_upload_time` is not exported anymore (it's tracked in the code, but not mapped in `tsdbMetrics`). This PR fixes it.
User-facing changes:
- Introduced `cortex_ingester_shipper_last_successful_upload_timestamp_seconds`
- Removed `cortex_ingester_shipper_dir_syncs_total` because useless (never used in our mixing)
- Removed `cortex_ingester_shipper_dir_sync_failures_total` because it was never incremented (never used in our mixin)
- The shipper `metrics` struct has been renamed to `shipperMetrics` and is now shared across all shipper instances. The metrics tracked are safe to be shared …
> Fix MimirIngesterHasNotShippedBlocks alert

- CHANGELOG.md
- tools/compaction-planner/main.go
- tools/copyblocks/main.go
- tools/doc-generator/main.go
- tools/list-deduplicated-blocks/main.go
- tools/listblocks/main.go
- tools/tsdb-compact/main.go
- tools/tsdb-index-health/main.go
- tools/tsdb-index-toc/main.go
- tools/tsdb-index/main.go
- tools/tsdb-symbols/main.go
The module github.com/golang/glog registers its own command line flags in the `init` function. As #4781 does for Mimir itself, drop glog command line flags from affected tools:
* tsdb-index-health
* tsdb-index-toc
* tsdb-compact
* doc-generator
* tsdb-index
* listblocks
* list-deduplicated-blocks
* tsdb-symbols
* copy-blocks
* compaction-planner
> tools: Remove glog command line flags

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin/dashboards/queries.libsonnet
In https://github.com/grafana/mimir/pull/5235 I've introduced new fine-grained metrics to measure the query results cache hit ratio. The new metrics allow to get a better measurement because: (a) they only track the cache lookup done by query results cache (e.g. excluding cache usage done by query cardinality estimator) and (b) they're split by `request_type`.
In this PR I'm improving the `Mimir / Queries` dashboard to use the new metrics, while keeping backward compatibility:
1. Use new metric in `Query results cache hit ratio`, fallback to the old one
2. Remove `Query results cache hit ratio` panel because (a) not much useful (b) not even correct, given it includes cache misses from query cardinality estimator
How the new dashboard row looks like:
NOTE: in the dev cluster where I took …
> Improve query results cache hit ratio in the 'Mimir / Queries' dashboard

- operations/helm/scripts/build.sh
This runs the helm command in parallel for each test setup concurrently. On my M1 Mac with OrbStack (Docker Desktop alternative) this brought down build time from 32s to 9s.
> Helm: render helm tests in parallel

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- integration/getting_started_with_grafana_mimir_test.go
- integration/otlp_ingestion_test.go
- integration/read_write_mode_test.go
- integration/util.go
- pkg/cardinality/request.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/generic_query_cache_test.go
- pkg/frontend/querymiddleware/labels_query_cache.go
- pkg/frontend/querymiddleware/labels_query_cache_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/util/time.go
- pkg/util/time_test.go
- pkg/util/validation/limits.go
Similarly to https://github.com/grafana/mimir/pull/5212, in this PR I'm adding the support to cache label names and label values responses. See details at: https://github.com/grafana/mimir/issues/5395
- I manually tested it and looks working as intended.
- I opted for a new configuration option to specify the labels query response cache TTL, instead of one in common with the cardinality API, because I think we can potentially cache a bit longer for cardinality APIs. Since these config options are still marked experimental (so we're not committing to them yet) I prefer to keep them separated while rolling out the feature.
Fixes #5395
> Add query results cache support for label names and label values APIs

- docs/sources/mimir/configure/configure-object-storage-backend.md
Fix a documentation example of Azure Blob Storage configuration. It currently refers to `SWIFT_ACCOUNT_KEY`, where the "SWIFT" prefix must surely be by mistake?
Please let me know in case the prefix should actually be intentional :)
> Documentation: Fix Azure Blob Storage configuration example

- Makefile
Running `make BUILD_IN_CONTAINER=false build-mixin` on macOS complains about `--relative-to`:
```
~/Repositories/Grafana/mimir
realpath: illegal option -- -
usage: realpath [-q] [path ...]
The mixin has been compiled to operations/mimir-mixin-compiled and archived to
~/Repositories/Grafana/mimir
realpath: illegal option -- -
usage: realpath [-q] [path ...]
The mixin has been compiled to operations/mimir-mixin-compiled-baremetal and archived to
```
This PR removes the use of `--relative-to`, as it doesn't seem necessary and allows engineers to run `build-mixin` on a macOS machine without using Docker.
(none)
> Remove use of `--relative-to` argument to `realpath`, so that `make build-mixin` works on macOS

- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
This fixes a bug where the `loadingSeriesChunkRefsSetIterator` would store a wrong series hash cache for a series. This happens because `fitlerSeries` assumes that the number of postings is the same as the number of series. It uses the postings to store the series hash in the series hash cache.
However, some series might be filtered out because they don't contain chunks within the time range. In this case the postings would not align with the series, so storing the hash would happen under the incorrect posting.
> Store-gateway querier streaming: prevent series hash cache pollution

- CHANGELOG.md
- operations/mimir/config.libsonnet
- operations/mimir/memcached.libsonnet
For some reason the Jsonnet implementation of the memcached deployment overwrites the default memcached StatfulSet. The upstream [memcached jsonnet library](https://github.com/grafana/jsonnet-libs/blob/master/memcached/memcached.libsonnet#L67-L83) implements this just fine and has the feature to chose between AntiAffinity and TopologySpreadConstraints. The only additional thing needed that the Mimir Jsonnet adds is the ability to add a node selector, which can be added to maintain this functionality.
> Allow Memcached StatefulSets chose between AntiAffinity and TopologySpreadConstraints

- CHANGELOG.md
- integration/asserts.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/distributor/query_test.go
- pkg/mimir/modules.go
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_test.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/querier/stats/query_metrics.go
- pkg/util/limiter/query_limiter.go
This PR addresses an issue @pracucci noticed in #5440: https://github.com/grafana/mimir/pull/5440#discussion_r1255427439
The root cause of this is that it doesn't make sense that the `Distributor` struct owns the `QueryMetrics` instance for a Mimir process - the `QueryMetrics` instance is not specific to ingester queries.
(none)
> Remove `QueryMetrics` instance from `Distributor` struct

- pkg/storage/tsdb/block/block.go
Minor improvement: Use `filepath.Join` for the local path instead of `path.Join` when downloading a block file.
> block: Use filepath.Join for local files

- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-to-kubernetes-version-1.25.md
> Helm: add Troubleshoot section to kubernetes 1.25 migration guide

- pkg/util/validation/exporter/exporter.go
- pkg/util/validation/exporter/exporter_test.go
Since the `Limits` type now supports extensions (see PR https://github.com/grafana/mimir/pull/4397), downstream projects can take advantage of this functionality to add their own limits by extending the current runtime config, however , such limits are not exposed by the `override-exporter` component.
This PR adds the ability to add extra metrics to the exporter so that downstream projects can also export these limits/defaults wherever required.
> overrides-exporter: add extra metrics support

- CHANGELOG.md
- operations/mimir/shuffle-sharding.libsonnet
This makes the target shard size and utilization percentage configurable in the pre-defined user classes. Useful to anyone who is setting tighter limits than a 100% series overhead.
This is a noop with current configuration settings, which match our previous target: 50% utilization and 100K series per ingester.
Fixes (internal issue)
> Jsonnet: configurable target shard size / usage

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
Add two ingester metrics tracking resource utilization calculated by utilization based limiter:
* `cortex_ingester_utilization_limiter_current_cpu_load`: The current exponential weighted moving average of the ingester's CPU load
* `cortex_ingester_utilization_limiter_current_memory_usage_bytes`: The current ingester memory utilization
> Ingester: Add resource utilization metrics

- CHANGELOG.md
- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
Change `pkg/util/limiter.UtilizationBasedLimiter` to get current wall time _after_ CPU time. My thinking is that if extracting the CPU time from /proc would be somehow delayed, the calculated CPU utilization would be too high (on account of elapsed wall time being too short vs. elapsed CPU time).
> UtilizationBasedLimiter: Get wall time after CPU time

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite/histograms.go
- vendor/modules.txt
Implement otlp exponential histogram downscaling to native histogram maximum scale.
Get https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24026
N/A  (customer)
> vendor update opentelemetry-collector prom remote write

- pkg/util/limiter/utilization.go
In `pkg/util/limiter.UtilizationBasedLimiter`, note that CPU utilization calculation is based on the monotonic clock (robust against wall clock changes).
> UtilizationBasedLimiter: Document monotonic clock usage

- tutorials
This PR removes `tutorials` file, which was preserved as symlink #1564 and later changed to file #2007, because old version of  [play with Grafana Mimir tutorial](https://grafana.com/tutorials/play-with-grafana-mimir/) referred to it. But that's not the case for some time.
> Docs: Remove hard-to-maintain file with single link

- CHANGELOG.md
- integration/querier_label_name_values_test.go
- pkg/cardinality/request.go
- pkg/cardinality/request_test.go
- pkg/frontend/querymiddleware/cardinality_query_cache.go
- pkg/frontend/querymiddleware/cardinality_query_cache_test.go
- pkg/frontend/querymiddleware/generic_query_cache.go
- pkg/frontend/querymiddleware/generic_query_cache_test.go
- pkg/frontend/querymiddleware/labels_query_cache.go
- pkg/frontend/querymiddleware/labels_query_cache_test.go
- pkg/frontend/transport/handler.go
- pkg/util/http.go
- pkg/util/http_test.go
We found a bug introduced in #5212 and #5426 which caused POST requests returning wrong results. The problem is that, when the cardinality and/or label names/values result cache is enabled, the caching middleware consumes the `http.Request` `Body` and so the body will be empty when later read to forward it to the query-scheduler or querier.
In this PR I propose a fix. The fix consists in consuming the Body and then replacing it with the original content. It's not a new approach, in fact we were already doing it in `Handler.ServeHTTP()` so I've re-used that code, moving it to a common utility function.
- The modified integration and unit tests fail with the previous buggy version
N/A
> Fix cardinality and label names/values requests handling on POST requests

- .github/workflows/test-build-deploy.yml
- docs/sources/mimir/get-started/play-with-grafana-mimir/index.md
- docs/variables.mk
- Remove aliases. The Mimir tutorials pages were never published by the website as can be seen by the removed snippet in this patch. Considering that, these aliases are for the wrong location and are not needed since this file is still published at /tutorials/play-with-grafana-mimir.
- Update mount to use "next" version. This is a more accurate tutorial because the tutorials relies on code in the `main` branch of the source repository and that is published as "next" not "latest".
- Add canonical URL. Although "next" documentation is not indexed, this is still required for when this page is part of a release so that search engines know that the /tutorials/ page is the canonical website page.
> Update Mimir tutorial mount

- docs/internal/contributing/how-to-convert-config-to-per-tenant-limit.md
Adds a doc to `docs/internal` about how to migrate global config options to tenant-specific config.
There are a ton of minor steps here particularly in regards to maintaining compatibility through the deprecation period for the old, global config option.
A playbook was suggested to make sure we didn't miss anything, as we will certainly need to do this again.
> docs: how to convert config to per tenant limit

- CHANGELOG.md
- operations/mimir/autoscaling.libsonnet
Allow adjustment of the targeted distributor CPU usage as a percentage of
requested CPU. Default is 100% to maintain existing behavior.
Action item from an incident.
> Allow configuration of targeted distributor CPU for autoscaling

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
To help debugging, support logging of samples EWMA CPU load is based on when enabling read path limiting. I'm making this logging configurable, behind an experimental flag.
> Ingester: Support logging of samples EWMA CPU load is based on

- CHANGELOG.md
- tools/copyblocks/README.md
- tools/copyblocks/abs.go
- tools/copyblocks/gcs.go
- tools/copyblocks/main.go
- tools/copyblocks/s3.go
copyblocks currently supports `GCS->GCS` and `ABS->ABS` server-side copies. This change adds:
- `S3->S3` server-side copy support
- client-side copy support for copies to be performed across services (source GET chained to destination PUT)
- the ability to toggle between server-side copies and client-side copies if both buckets are on the same service 
so the new support looks like `{ABS, GCS, S3} -> {ABS, GCS, S3}`.
Notably `--service` was replaced with `--source-service` and `--destination-service`, since the services may not be the same.
~I have not finished testing these changes against real buckets yet, so I'm opening this as a draft.~
Tests Performed:
The goal of this testing was line coverage by having each service be both a source and a destination in client-side copies and to …
> copyblocks: add support for S3-compatible buckets and object storage migration

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
Adds two new panels to the Tenants dashboard to have information about the tracked native histograms series and
buckets.
Proposal is to split the current top row: keep the series panel and move exemplars/samples to their own row.
Add native histogram tracking to the top row:
Fixes #5542
> native histograms: update tenants panel with tracking information

- go.mod
- go.sum
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester.go
- pkg/ingester/instance_limits.go
- vendor/github.com/weaveworks/common/grpc/cancel.go
- vendor/github.com/weaveworks/common/middleware/grpc_logging.go
- vendor/github.com/weaveworks/common/middleware/logging.go
- vendor/github.com/weaveworks/common/server/metrics.go
- vendor/github.com/weaveworks/common/server/server.go
- vendor/modules.txt
Not-ready and over-max-inflight can be emitted when the server is overloaded, in which case we don't want to spend more resource logging the fact. The problem will be visible in metrics.
Temporarily using a branch from upstream weaveworks/common, to check Mimir still passes CI.
Fixes #397
> ingester and distributor: don't log errors that cause OOMs

- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
In the current scenario, if the `validation.Limits` type is configured through the command line instead of being unmarshalled from YAML, the `setExtensionsDefaults` method is called to read and load the default values for the limits extensions. However, there is a possible scenario where these defaults might not have been loaded yet (for instance, when the default configuration is configured through a service dependency).
This PR stops calling the `setExtensionsDefaults` from the `RegisterFlags` method, and instead makes it publicly available, so that downstream projects can determine the exact moment when the registration of these defaults should take place.
> limits: export method to register extension defaults

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/ingester/ingester.go
- pkg/ingester/metrics.go
- pkg/ingester/user_tsdb.go
- pkg/util/globalerror/errors.go
- pkg/util/validation/validate.go
Add metrics to distributors and ingesters that are incremented when we reject requests due to hitting per-instance limits.
Related #5494 #397
> Add metrics for requests rejected due to per-instance limits

- pkg/mimirpb/timeseries_test.go
Some improvements to `pkg/mimirpb/timeseries_test.go`.
Split into three commits, in decreasing order of importance.
* `BenchmarkPreallocTimeseries_SortLabelsIfNeeded`: use realistic numbers.  Default max labels is 30; we don't expect series with thousands.
* `TestPreallocTimeseries_SetLabels`: simplify test data. Most of `mimirpb` deals in `LabelAdapter` not `Labels` so make this test consistent. As a side-effect this removes the import of Prometheus `labels` from the file.
* `BenchmarkPreallocTimeseries_SortLabelsIfNeeded`: test ordered labels too.  The idea is the function is faster than just sorting every time, so we should check if that is the case.
I tried a couple of changes to `SortLabelsIfNeeded` - using `slices.IsSorted`, and omitting the whole pre-check, but both were worse than …
> BenchmarkPreallocTimeseries_SortLabelsIfNeeded improvements

- CHANGELOG.md
- cmd/mimir/main.go
- pkg/util/ballast.go
- pkg/util/ballast_test.go
This PR changes ballast allocation to use smaller blocks instead of one large byte slice. Using single large byte slice can sometimes lead to ballast being contributing to the working set of component.
This PR implements "trivial solution" mentioned in https://github.com/grafana/mimir/issues/5564.
(Moved ballast allocation to exported function so that we can reuse it from Grafana Enterprise Metrics too.)
Fixes https://github.com/grafana/mimir/issues/5564
> Allocate ballast in smaller blocks.

- docs/sources/mimir/references/http-api/index.md
Similarly to what we did in #5232, in this PR I'm mentioning that the response for label names and values API could be picked up from the cache.
N/A
> Docs: mention query results cache for label names and values API

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
I just experienced the issue the remove rule evaluation was failing because the max gRPC message size was hit. In this PR I'm proposing to improve the `MimirRulerTooManyFailedQueries` runbook to mention it.
N/A
> Docs: improve MimirRulerTooManyFailedQueries runbook

- CHANGELOG.md
- docs/sources/mimir/manage/tools/query-tee.md
- tools/querytee/proxy.go
This PR adjusts the default value of `-proxy.compare-skip-recent-samples` for `query-tee` to avoid racing with rule evaluation, and updates the docs to include some explanation of this.
(none)
> Avoid racing with rule evaluation when comparing backends with query-tee

- integration/getting_started_with_grafana_mimir_test.go
- integration/otlp_ingestion_test.go
- integration/read_write_mode_test.go
- pkg/frontend/querymiddleware/labels_query_cache.go
- pkg/frontend/querymiddleware/labels_query_cache_test.go
- pkg/util/time.go
- pkg/util/time_test.go
The PR https://github.com/prometheus/prometheus/pull/12535 has been merged and vendored in https://github.com/grafana/mimir/pull/5549. We can now use upstream `MinTime` and `MaxTime`.
N/A
> Chore: use upstream Prometheus API v1 MinTime and MaxTime

- CHANGELOG.md
- operations/mimir/alertmanager.libsonnet
- operations/mimir/compactor.libsonnet
- operations/mimir/distributor.libsonnet
- operations/mimir/flusher-job-blocks.libsonnet
- operations/mimir/ingester.libsonnet
- operations/mimir/multi-zone.libsonnet
- operations/mimir/overrides-exporter.libsonnet
- operations/mimir/querier.libsonnet
- operations/mimir/query-frontend.libsonnet
- operations/mimir/query-scheduler.libsonnet
- operations/mimir/read-write-deployment/read.libsonnet
- operations/mimir/ruler.libsonnet
- operations/mimir/store-gateway.libsonnet
I have an use case to remove an env var from `distributor_env_map` but it's not easy to do because we don't prune it. This PR should make it trivial.
N/A
> Jsonnet: allow to remove an entry from the configured environment variable for a given component

- pkg/ingester/ingester.go
- pkg/storage/tsdb/config.go
I was doing a post-merge review of #5549 and I've found a bug: if we set the WALCompressionType in `RegisterFlags()` it will just be set to the default value, and not to the value set by the user. This PR fixes it. /cc @zenador @charleskorn 
N/A
> Fix WAL compression regression introduced in #5549

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/querier.go
- vendor/modules.txt
This PR updates `mimir-prometheus` to https://github.com/grafana/mimir-prometheus/commit/c8f5ad1492a4175b1b8f78da8489597f35fc0dd7, which brings optimization from https://github.com/grafana/mimir-prometheus/pull/518.
> Update mimir-prometheus to commit c8f5ad1492

- CHANGELOG.md
- pkg/querier/worker/scheduler_processor.go
This PR changes querier scheduler processor to handle closed connections when notifying query result to the frontend. 
As it is now, it is possible for the querier to use a closed connection before the pool detects and removes it internally, causing the affected query/shard to timeout. 
escalation ref: https://github.com/grafana/support-escalations/issues/6496
> querier: handle frontend connection errors when notifying query result

- pkg/distributor/distributor.go
- pkg/ingester/client/client.go
- pkg/ingester/client/metrics.go
- pkg/ingester/ingester_test.go
Removes use of the global prometheus.Registry without duplicate registration. Verified by starting in microservices and monolithic mode via docker-compose.
N/A
> Remove global response time histogram in ingester client

- CHANGELOG.md
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/lazy_binary_reader_test.go
This PR fixes deadlock in store-gateway which can happen when using experimental `-blocks-storage.bucket-store.index-header-lazy-loading-concurrency` option (introduced in #5313).
When this option is enabled, lazy loading uses blocking-gate to control number of goroutines performing the lazy-load. When multiple goroutines operating on the same block index enter `*LazyBinaryReader.load()` function at the same time, the following leads to deadlock:
- `*LazyBinaryReader.load()` is called with read-lock.
- Let's assume that one goroutine is able to get permit from `r.lazyLoadingGate.Start()`, but other goroutine is not (and blocks on `r.lazyLoadingGate.Start()` call)
- then the first goroutine (with the permit) is unable to proceed, because it tries to switch from read-lock to write-lock -- …
> Fix possible deadlock in store-gateway when using `index-header-lazy-loading-concurrency`

- CHANGELOG.md
- tools/ulidtime/main.go
This PR modifies `ulidtime` tool to add `-seconds` flag to print timestamp from ULID as Unix timestamp. `ulidtime` now also exits with status code 1 if any ulid cannot be parsed.
> ulidtime: add -seconds flag and exit code

- go.mod
- go.sum
- pkg/distributor/distributor.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/instance_limits.go
- pkg/util/log/log.go
- vendor/github.com/weaveworks/common/middleware/grpc_logging.go
- vendor/github.com/weaveworks/common/middleware/logging.go
- vendor/modules.txt
Not-ready and over-max-inflight can be emitted when the server is overloaded, in which case we don't want to spend more resource logging the fact.
The max-inflight errors will be recorded in metrics added in #5551.
Temporarily using a branch from upstream weaveworks/common, to check Mimir still passes CI.
Update on #5494 
> ingester: don't log errors that cause OOMs, using interface

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/jsonnetfile.lock.json
We just merged https://github.com/grafana/jsonnet-libs/pull/1038. In this PR I'm updating the vendored `mixin-utils` library and rebuilding the dashboards.
N/A
> Mixin: update vendored mixin-utils library

- cmd/mimir/help-all.txt.tmpl
- pkg/util/fieldcategory/overrides.go
- pkg/util/usage/usage.go
This PR changes the logic of the usage output to omit all fields that have been marked with the doc:"hidden" struct tag.
Fixes N/A
> usage: do not render `doc:"hidden"` fields in help usage output

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/writes.libsonnet
Add panels for distributors and ingesters rejecting requests due to hitting per-instance limits based on metrics added in #5551.
Related #5551
> Add per-instance rejections to Mimir / Writes dashboard

- CHANGELOG.md
- tools/tsdb-index-toc/main.go
This PR adds an estimate of the index-header size to the calculations performed by `tsdb-index-toc`. This assumes an index-header layout as described in the [Mimir documentation](https://grafana.com/docs/mimir/latest/references/architecture/binary-index-header/), and is labeled as an estimate. In addition it reports the total index size, and the index-header estimate as a % of the total index size. An example of the new output is below:
```bash
./tsdb-index-toc 01G6VNZB43M2M3Z4MVCA6T69PP/index
Index size:              63387634
Symbols table size:      356971
Series size:             51763202
Label indices:           36482
Postings:                10749856
Label offset table:      3953
Postings offset table:   477113
Index-header size (est): 834118
Index-header % (est):    1.316
```
The …
> Added index-header estimate to tsdb-index-toc

- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-helm-chart-2.x-to-3.0.md
Technically the migration guide is valid for any 2.x version of the helm chart and is not specific to 2.1 ([2.1 changelog](https://github.com/grafana/mimir/blob/a397d21dfb1e3162b9f5d0828a391166a2c621c7/operations/helm/charts/mimir-distributed/CHANGELOG.md#210)).
This PR makes the 4.x -> 5.0 and the 2.x -> 3.0 migration guides more consistent.
> Docs: update helm 2.x to 3.0 migration guide

- cmd/mimir/main_test.go
- pkg/util/fieldcategory/overrides.go
- pkg/util/usage/usage.go
This is a follow-up PR for https://github.com/grafana/mimir/pull/5630
Here we are adapting usage rendering logic to completely skip structs that have been marked as hidden, instead of only fields. 
Additionally, two global flags have been added to the overrides map, as non parsed fields are now skipped.
Fixes N/A
> usage: skip structs marked as hidden in usage help output

- CHANGELOG.md
- operations/mimir-tests/test-deployment-mode-migration-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
- operations/mimir/read-write-deployment/read.libsonnet
A small follow up on https://github.com/grafana/mimir/pull/5646, to not inherit GOMAXPROCS in mimir-read too.
N/A
> Jsonnet: do not inherit querier's GOMAXPROCS in mimir-read

- pkg/ingester/activeseries/active_postings.go
- pkg/ingester/activeseries/active_postings_test.go
- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/ingester.go
We're not tracking generic uint64 but a storage.SeriesRef. This isn't changing any logic.
Some cleanup before addressing https://github.com/grafana/mimir/issues/5649
> Use storage.SeriesRef in active series tracker

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/config.libsonnet
This PR adds `admin-api` to the `ring_members` array in the `job_names` of `config.libsonnet` where the alert populates the list of jobs to check against. It should mean that it functions as normal in OSS Mimir, but now should also work if it is a GEM deployment.
Fixes #5640
> [Mixin] Add admin-api to mixin ring_members to fix always firing MimirGossipMembersMismatch alert.

- CHANGELOG.md
- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/activeseries/custom_trackers_config_test.go
Three changes:
* Store stripe counts as uint32 - a range of 4 billion ought to be enough, on one ingester.
* Smaller slice for match counts - we prefer to optimise for all the times when matchers are not increasing. On a multi-tenant system this will be the vast majority.
* Reduce stripes from 512 to 128 - this reduces memory for small tenants by 75%. Benchmarks show no difference in access speed.
And extend the benchmark to include matchers.
```
goos: linux
goarch: amd64
pkg: github.com/grafana/mimir/pkg/ingester/activeseries
cpu: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
│   before.txt   │              after.txt              │
│     sec/op     │    sec/op     vs base               │
ActiveSeriesTest_single_series/50-4                                  55.46n ±  2%   54.00n ±  6%        ~ …
```
> Reduce memory usage of ActiveSeriesTracker

- CHANGELOG.md
- go.mod
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/instance_limits.go
- pkg/ingester/instance_limits_test.go
Create a base type for ingester per-instance limit errors. This allows us to decorate them with extra information for gRPC responses and our logging middleware (to prevent them from being logged, increasing resource usage).
Related #5581
Related #5551
Related weaveworks/common#299
> Create base error type for ingester per-instance errors and remove logging for them

- go.mod
- go.sum
- pkg/ingester/user_tsdb.go
- vendor/github.com/prometheus/prometheus/tsdb/head.go
- vendor/modules.txt
New callback passes a map with head series refs that we can use later to fix the active series tracker.
> Update mimir-prometheus and SeriesLifecycleCallback

- CHANGELOG.md
- operations/mimir/autoscaling.libsonnet
As spotted by @jhesketh [here](https://github.com/grafana/mimir/pull/5679#discussion_r1284452521) (thanks!) I did two mistakes in https://github.com/grafana/mimir/pull/5679, which I'm fixing in this PR:
- ruler-querier has no memory-based autoscaling
- `autoscaling_ruler_querier_cpu_target_utilization` was not applied
N/A
> Jsonnet: fix ruler-querier autoscaling target utilization

- CHANGELOG.md
- operations/mimir-tests/build.sh
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-custom-target-utilization.jsonnet
- operations/mimir/autoscaling.libsonnet
I've introduced autoscaler target utilization config support in #5679 and subsequent fix #5682. I have been able to make it wrong twice. In particular, autoscaler threshold must be an int, but I didn't round the compute value. In this PR I'm adding `std.floor()` everywhere we compute the HPA threshold, and I'm also adding a jsonnet test.
Note to reviews:
- I changed rounding for alertmanager threshold, to keep it consistent with the rest of jsonnet.
- I changed the script used to run jsonnet tests, so that a test can import another one.
Here is the compiled diff between `test-autoscaling.libsonnet`  and the new `test-autoscaling-custom-target-utilization.libsonnet`:
```
$ diff operations/mimir-tests/test-autoscaling-generated.yaml …
```
> Jsonnet: fix autoscaler target utilization config

- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
CPU and memory HPA queries of some components (e.g., distributors, alert manager,  ruler, query frontend) take in account resources utilization of terminated pods as well (because of the 5m stale period). As a consequence, from HPA perspective it looks like the resource utilization doubled, hence HPA wants to scale up 2 times.
This PR fixes the problem by intersecting the resource utilization with the `up` metrics, in such a way that only the resource utilization of pods that are up and running is considered.
> Fixing the HPA queries suffering the PromQL lookback period

- docs/sources/mimir/set-up/migrate/migrate-from-thanos-or-prometheus.md
Adds command to run for aws as the current script is only valid for gcs.
> add aws command to clean up thanos labels

- CHANGELOG.md
- operations/mimir/alertmanager.libsonnet
- operations/mimir/compactor.libsonnet
- operations/mimir/config.libsonnet
- operations/mimir/distributor.libsonnet
- operations/mimir/ingester.libsonnet
- operations/mimir/overrides-exporter.libsonnet
- operations/mimir/querier.libsonnet
- operations/mimir/query-frontend.libsonnet
- operations/mimir/query-scheduler.libsonnet
- operations/mimir/ruler.libsonnet
- operations/mimir/store-gateway.libsonnet
In Mimir Jsonnet, add common config object enabling adding configuration parameters for all Mimir components.
> Jsonnet: Add common config object

- CHANGELOG.md
- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
We're still testing the CPU limit in the `UtilizationBasedLimiter` and we observe a weird behaviour. Sometimes, the limiter tracks a CPU utilization which is absurdly high (e.g. 108946 sec cores on a 32 cores machine). We haven't found the root cause, but I have a theory. In this PR I'm proposing a fix for that theory.
The `UtilizationBasedLimiter.compute()` is called by a `time.Ticker`. We know that a `time.Ticker` may call the function two consecutive times under some edge conditions. For example, look at [this example](https://go.dev/play/p/B1wmVKqjvpF). It prints:
```
2009-11-10 23:00:01 +0000 UTC m=+1.000000001
2009-11-10 23:00:02.99 +0000 UTC m=+2.990000001
2009-11-10 23:00:03 +0000 UTC m=+3.000000001
2009-11-10 23:00:04.99 +0000 UTC m=+4.990000001
```
Given ☝️ , a theory I have is …
> Skip two consecutive CPU utilization updates in the UtilizationBasedLimiter

- integration/e2emimir/service.go
Chore: set Jaeger sampler to be probabilistic
During the otel migration, I noticed the current e2e tracing is actually always sampled, see [code](https://github.com/jaegertracing/jaeger-client-go/blob/master/config/config.go#L371), reading the commands, we actually want to have 50% sampling rate in order to test both sampled/unsampled cases. 
> Chore: set Jaeger sampler to be probabilistic

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin/dashboards/queries.libsonnet
While being on-call, I noticed that the "Blocks currently loaded" in the "Mimir / Queries" dashboard may be misleading, because by "loaded" you may think about "block index-header loaded". The panel actually shows the number of blocks owned by the store-gateway replica, and it's unrelated by the number of blocks whose index-header has been loaded.
In this PR I propose to rename the panel and add a panel description to clarify it.
N/A
> Dashboards: rename "Blocks currently loaded" to "Blocks currently owned" in the "Mimir / Queries" dashboard

- RELEASE.md
We're switching to a lower-cadence quarterly release cycle, this puts the next 2.10 release at the beginning of September, and I'll be shepherding it.
> Update RELEASE.md with new quarterly cadence schedule and new shepherd

- CHANGELOG.md
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled.jsonnet
- operations/mimir-tests/test-read-write-deployment-mode-s3-caches-disabled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-caches-disabled.jsonnet
- operations/mimir/config.libsonnet
As reported in #5683, the jsonnet compilation is broken when index, chunks or metadata caches are disabled because of some missing CLI flags in `$.store_gateway_args` which we reference when building `$._config.blocks_chunks_concurrency_connection_config`. This PR fixes it adding conditionals.
I've also added a jsonnet test. The comparison between `operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml` and `operations/mimir-tests/test-read-write-deployment-mode-s3-caches-disabled-generated.yaml` is [here](https://gist.github.com/pracucci/799fe2040e73a955d31b168f5109e840).
Fixes #5683
> Jsonnet: fix compilation when index, chunks or metadata caches are disabled

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/storegateway/gateway.go
- pkg/storegateway/gateway_ring.go
- pkg/storegateway/gateway_test.go
At Grafana Labs we have an use case where store-gateway auto-forget should be disabled. In this PR I'm proposing to add a config option to allow to disable it. The default behaviour has not changed (auto-forget is enabled).
N/A
> Add config option to disable store-gateway auto-forget feature

- cmd/mimir/main.go
- go.mod
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/storegateway/gateway_test.go
- pkg/storegateway/series_chunks_test.go
Increase required Go version in go.mod from 1.19 to 1.20, and stop using [`math/rand.Seed`](https://pkg.go.dev/math/rand#Seed) as it's deprecated, and seeding happens automatically at program start, from this version of Go (causes a linter failure). Also deprecated (and failing linter), replace `math/rand.Read` with `crypto/rand.Read`.
`rand.Seed` should only be necessary where deterministic behaviour is needed, in which case you can replace it with a local (explicitly seeded) generator; I could only find one test explicitly using seeded randomness (for reproducibility), so I converted that one to using a local, explicitly seeded, generator. I removed `rand.Seed` from other tests, where I can't see it making a difference. If it should turn out to be useful from implicit `rand` uses, we …
> Increase required Go version to 1.20 for better generics support

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_early_compaction_test.go
- pkg/ingester/ingester_test.go
- pkg/ingester/metrics.go
- pkg/util/globalerror/errors.go
- pkg/util/validation/limits.go
In this PR I propose to enforce the configured `-validation.create-grace-period` in the ingester too. The reason is that we've experienced an issue where a sample with a timestamp very far in the future has reached the ingester, and so screwed up the TSDB. We're still investigating the root cause (apparently looks like caused by few bit flipped) but in the meanwhile I would like to enforce the `-validation.create-grace-period` in the ingester too.
- I removed "0 to disable" from the `-validation.create-grace-period` CLI flag description because it wasn't true. 0 didn't disabled it. It's always enforced.
- I noticed that `-validation.create-grace-period` is not checked against exemplar timestamp in the distributor. I will do it in a follow up PR.
- I also manually tested …
> Enforce -validation.create-grace-period in the ingester too

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/validate.go
While working on https://github.com/grafana/mimir/pull/5712, I noticed that `-validation.create-grace-period` was not enforced for exemplars. In this PR I propose to enforce it for exemplars too.
The way I've implemented the check in this PR follows how we enforce the "timestamp too old": if the exemplar has timestamp too far in the future, then the exemplar is silently dropped and no error is reported back to the client (but a Mimir metric is tracked). I'm open to feedback tho.
N/A
> Enforce -validation.create-grace-period for exemplars too

- .github/dependabot.yml
Presently, Dependabot generates multiple pull requests for each dependency, per file. This results in a surplus of notifications. Please explore the recently introduced Dependabot feature designed to consolidate these individual pull requests into a single, more organized PR.
For further context, please refer to the following link: [Issue #7795](https://github.com/dependabot/dependabot-core/issues/7795).
> Security: Group docker update into one PR

- pkg/compactor/blocks_cleaner.go
Adding additional log to indicate when bucket index is being deleted for user with no blocks remaining.
> Add log line for deletion of bucket index when tenant has no blocks

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/enterprise-https-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/openshift-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
This PR allows the configuration of the podManagementPolicy for the store-gateway statefulset through the helm chart.
Fixes #5733
> Allow configuration of podManagementPolicy 

- CHANGELOG.md
- pkg/ruler/manager.go
The context passed to the remote ruler evaluation querier is passed all the way down from the root context of the `Ruler.starting` and `Ruler.run` methods. This context is cancelled when the ruler receives a SIGINT.
The remote ruler evaluation immediately aborts remote evaluations upon context cancelations. This results in failed rule evaluations. In addition to that, each ruler manager has a `Stop()` method which gracefully stops rule groups and waits for them to complete any ongoing evaluations.
An example of this is in this error emitted [here](https://github.com/grafana/mimir/blob/ff4a68a0e5cc2b183c7fdc82fd4c1be66ed5dcc2/pkg/ruler/remotequerier.go#L229) while remotely evaluating the rule's query
```
ts=2023-08-16T18:26:47.929746821Z caller=spanlogger.go:85 user=234002 …
```
> ruler: graceful shutdown during evaluations

- .github/workflows/scripts/run-integration-tests-group.sh
- .github/workflows/scripts/run-unit-tests-group.sh
- .github/workflows/test-build-deploy.yml
- .golangci.yml
- CHANGELOG.md
- Makefile
Change the tags used in CI to include `stringlabels`.
This uses less memory, especially in ingesters.  See #3555.
> CI: build with -tags stringlabels

- CHANGELOG.md
- tools/wal-reader/main.go
This PR adds new `wal-reader` tool to our toolset. WAL reader reads current state of the wal (latest checkpoint + segment files after checkpoint), and prints individual entries from it, as they are found.
> New tool: wal-reader

- docs/sources/mimir/configure/configure-otel-collector.md
Explains how the user can configure Mimir to accept exponential histograms. We have a similar page in the Cloud docs, but it should also be in the OSS docs. 
https://grafana.com/docs/grafana-cloud/monitor-infrastructure/otlp/otlp-format-considerations/#metrics
> Update configure-otel-collector page to explain how to accept exponential histograms

- docs/sources/mimir/references/architecture/components/store-gateway.md
Last week we merged https://github.com/grafana/mimir/pull/5702, adding the `-store-gateway.sharding-ring.auto-forget-enabled` config option. In this PR I'm mentioning it in the doc.
N/A
> Docs: mention -store-gateway.sharding-ring.auto-forget-enabled

- CHANGELOG.md
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
Added `cortex_ingester_tsdb_head_max_time_seconds` metric computed as `max(prometheus_tsdb_head_max_time_seconds)` for all TSDB Heads open in given ingesters.
This can be used to detect ingestion of sample with very high timestamp.
Related to #5712 and #5642.
> Add cortex_ingester_tsdb_head_max_time_seconds metric

- tools/copyblocks/README.md
Adds the build command to the copyblocks README and fixes a typo.
> copyblocks: added build command to readme

- CHANGELOG.md
- pkg/mimir/mimir.go
Applies the httpgrpc tracing middleware created in https://github.com/grafana/dskit/commit/0ef13fb65a5363eec6f14042d12554cf33cc8640.
This middleware increases the observability of http-over-grpc requests, which are all handled by the generic `httpgrpc.HTTP/Handle` method, by tagging the incoming `httpgrpc.HTTP/Handle` span with relevant opentracing http span tags, and by starting a child span mirroring the existing opentracing spans created for vanilla http requests.
This fixes the fact that all `httpgrpc.HTTP/Handle` tracing spans were identical, with no indication of which http request/endpoint type was being handled (e.g. /otlp/v1/metrics vs. /api/v1/push).
> apply enhanced server-side tracing for httpgrpc.HTTP/Handle method

- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/lazy_binary_reader_test.go
This PR modifies `LazyBinaryReader` in following ways:
- it renames `load` to `getOrLoadReader`. This method no longer requires read-lock, and returns either reader + "inuse" waigGroup, or error. WaitGroup must be used to indicate when operation has finished. `getOrLoadReader` also updates `r.usedAt`.
- previous `load1` method from https://github.com/grafana/mimir/pull/5605 was renamed to `loadReader`.
- `unloadIfIdleSince` now checks for `r.readerInUse` wait group
Idea of this PR was to concentrate use of `r.readerMx` lock in `getOrLoadReader`, and remove locking from individual `Reader` methods.
This was proposed in https://github.com/grafana/mimir/pull/5605#discussion_r1276721796
- [na] `CHANGELOG.md` updated - the order of entries should …
> Simplify locking in LazyBinaryReader.

- CHANGELOG.md
- pkg/compactor/bucket_compactor.go
- pkg/compactor/bucket_compactor_test.go
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/compactor/job.go
Verifies the time range of compacted block(s) matches the time range of the input blocks. Provides an extra layer of protection in Mimir in case of any bugs during block compaction. 
Fixes #816
> Verify time range of compacted block matches time range of input blocks

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- integration/distributor_high_concurrency_test.go
- integration/distributor_test.go
- pkg/distributor/distributor.go
- pkg/mimir/mimir.go
- pkg/mimirpb/timeseries.go
- pkg/mimirpb/timeseries_test.go
We see some data-races that may be related to distributor pooling buffers when writing messages for ingesters.
This PR reverts PR #5389. The change reintroduces back two options to disable optimizations:
- `-distributor.write-requests-buffer-pooling-enabled`
- `-timeseries-unmarshal-caching-optimization-enabled`
First one can help with data race (not yet sure).
> Revert PR 5389 to put back flags for disabling optimizations.

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/config.libsonnet
We run a custom compactor in a Mimir cluster, which is causing the `MimirGossipMembersMismatch` to fire. Like we did for other components, I suggest to just change the regex to match any compactor.
N/A
> Fix MimirGossipMembersMismatch when running customer compactor

- Makefile
The current make target fetch-build-image ensures that the build image is present locally after pulling it from DockerHub.
This PR changes the target to first check whether the image isn't present locally before doing `docker pull`. This speeds up the target and allows it to run without an internet connection.
> makefile: avoid docker pull on most make targets

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/distributor/distributor.go
We have found that this optimization causes race detector to report problems.
Until we fix the races, we're disabling the optimization.
> Disable distributor.write-requests-buffer-pooling-enabled by default

- LICENSING.md
- operations/LICENSE_APACHE2
This PR changes licensing for `operations/` with Helm chart, Jsonnet and mixin (alerts, dashboards) subdirectory to APACHE2. This is similar to what [Loki](https://github.com/grafana/loki/commit/a9d85de4aa5290cf2f8b2dca5d08645bbd0dc66c) (`production` subdir) and [Tempo](https://github.com/grafana/tempo/commit/37aeb4d1c9a66662dfe9e8655d199886739f52af) have done.
Fixes https://github.com/grafana/mimir/issues/5750
> Change licensing for operations/ subdirectory.

- CHANGELOG.md
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/lazy_binary_reader_test.go
`(*LazyBinaryReader).SymbolsReader` method reports that usage of "reader" is done, however it also returns `SymbolsReader` that still uses underlying indexheader reader.
This PR fixes that bug. First reported by @dimitarvdimitrov in https://github.com/grafana/mimir/pull/5608#discussion_r1279186745. 
> Fix bug in LazyBinaryReader.SymbolsReader

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
This PR fixes `cortex_ingester_tsdb_head_max_time_seconds` metric introduced in https://github.com/grafana/mimir/pull/5786.
`cortex_ingester_tsdb_head_max_time_seconds` is based on `prometheus_tsdb_head_max_time_seconds`, which however is NOT exported by TSDB library. TSDB library only exports `prometheus_tsdb_head_max_time` (without `_seconds` suffix). Metric with `_seconds` suffix is exported by Prometheus `main` package here:
https://github.com/grafana/mimir-prometheus/blob/32d87282addfaa2af9f7a6b953d17f3da6101d66/cmd/prometheus/main.go#L1194-L1201
~We fix Mimir metric by exporting the `prometheus_tsdb_head_max_time_seconds` on our own, registered into per-TSDB registry. Note that Prometheus metric exports it with seconds precision because of integer division, in Mimir we do float …
> Fix cortex_ingester_tsdb_head_max_time_seconds

- CHANGELOG.md
- operations/mimir/multi-zone.libsonnet
To speed up rollouts, this increases the number of max unavailable store-gateways from 50 to 1000 when lazy loading is disabled. (This is upstreamed from internal jsonnet at GL).
n/a
> Increase `multi_zone_store_gateway_max_unavailable` when store gateway lazy loading is disabled 

- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
This PR upgrades Delve to a version compatible with Go 1.21. Without this, starting either Docker Compose stack with debugging enabled fails.
(none)
> Upgrade Delve to a version compatible with Go 1.21.

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/storage/tsdb/config.go
Today I was setting `-blocks-storage.tsdb.head-chunks-write-buffer-size-bytes` and I've realised the auto-generated doc doesn't mention the min/max values accepted. This PR does it.
N/A
> Docs: clarify -blocks-storage.tsdb.head-chunks-write-buffer-size-bytes min and max values

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
- pkg/ingester/tenants_http.go
This PR adds alert that triggers when samples with timestamps more than 1h in the future are ingested.
We have seen this happen as a result of processing of corrupted messages in ingester. We would like to detect this situation sooner.
> Add alert when data too far in the future is ingested

- CHANGELOG.md
- pkg/ingester/client/buffering_client.go
- pkg/ingester/client/buffering_client_test.go
This PR fixes data race caused by using buffer-pooling ingester client, originally introduced in https://github.com/grafana/mimir/pull/5195. Before this PR the client would always return buffers to the pool. However in case of context cancellations buffers could still be enqueued for sending inside gRPC client, and returning them back to pool would cause data race.
> Fix buffer-pooling ingester client

- CHANGELOG.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
The `-validation.create-grace-period` is always enforced in distributors and ingesters, even when the configured value is 0. However, in the query-frontend we consider the value 0 as "disabled". In this PR I propose to align the behaviour between query-frontend and distributor/ingester.
The default value for this setting is 10 minutes, so the behaviour will not change for anyone unless they explicitly set a value of 0. If they explicitly set a value of 0, the distributor/ingester will not ingest any sample with timestamp > real-world time, so in practice there should be no sample in the future to query as well.
N/A
> Enforce -validation.create-grace-period in the query-frontend when the configured value is 0

- Makefile
- cmd/metaconvert/Dockerfile
- cmd/mimir-continuous-test/Dockerfile
- cmd/mimir/Dockerfile
- cmd/mimirtool/Dockerfile
- cmd/query-tee/Dockerfile
This PR adds `_race` version of binary targets (eg. `make cmd/mimir/mimir_race`) and single-platform Docker image targets  (`make cmd/mimir/.uptodate_race`).
> Add support for building binaries and docker images with enabled race detector

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/config.libsonnet
This PR changes the the `MimirRequestErrors` and `MimirRequestLatency` alerts to ignore the `/debug/pprof` endpoint.
We could likely extend this to cover other non-critical endpoints, such as the various admin UI pages, but I've left them out of this PR in the interest of keeping this change small.
<details>
<summary>Other endpoints that are likely non-critical</summary>
* `compactor_ring`
* `config`
* `debug_fgprof`
* `distributor_all_user_stats`
* `distributor_ha_tracker`
* `distributor_ring`
* `ingester_ring`
* `ingester_tenants`
* `ingester_tsdb_tenant`
* `memberlist`
* `overrides_exporter_ring`
* `query_scheduler_ring`
* `root`
* `ruler_ring`
* `runtime_config`
* `services`
* `store_gateway_ring`
* `store_gateway_tenants`
</details>
(none)
- [n/a] Documentation …
> Don't alert on failing or slow requests to `/debug/pprof` endpoint

- CHANGELOG.md
- pkg/mimirpb/compat_slice.go
- pkg/mimirpb/compat_stringlabels.go
- pkg/querier/timeseries_series_set.go
- pkg/querier/timeseries_series_set_test.go
The conversion from LabelAdapters to Labels is expensive, now the underlying data structure is not identical, so do the comparison without converting.
Code copied from old Labels implementation.
> querier: fix performance when ingesters stream samples

- CHANGELOG.md
- pkg/mimirpb/compat_slice.go
- pkg/mimirpb/compat_stringlabels.go
- pkg/querier/timeseries_series_set.go
- pkg/querier/timeseries_series_set_test.go
Backport of #5836 to r252
* querier: fix performance when ingesters stream samples
The conversion from LabelAdapters to Labels is expensive, now the underlying data structure is not identical, so do the comparison without converting.
Code copied from old Labels implementation.
* querier: add BenchmarkTimeSeriesSeriesSet and extend test
* CHANGELOG
* lint
> querier: fix performance when ingesters stream samples (#5836)

- .github/workflows/allowlist.json
This PR adds
- `github.com/google/uuid`
- `github.com/hashicorp/golang-lru/v2`
to **dependabot** allowlist. These are both tiny and stable libraries, that sometimes receive bugfixes.
> Add github.com/hashicorp/golang-lru/v2 and github.com/google/uuid to allowlist

- .github/workflows/publish-technical-documentation-release-helm-charts.yml
We released the Helm chart in #5492, but it did not even trigger docs update since path filter didn't match.
> Docs publish: allow triggering helm docs publish on chart version change

- .github/workflows/scripts/run-integration-tests-group.sh
- .github/workflows/test-build-deploy.yml
- Makefile
- go.mod
- go.sum
- integration/e2emimir/client.go
- integration/e2emimir/service.go
- integration/e2emimir/services.go
- integration/integration_memberlist_single_binary_test.go
- integration/querier_remote_read_test.go
- pkg/querier/querier.go
- vendor/github.com/grafana/e2e/service.go
- vendor/github.com/grafana/e2e/util.go
- vendor/modules.txt
This PR uses race-enabled Mimir when running integration tests. To make integration tests fail on data races we pass extra `GORACE` environment variable to make Mimir exit when data race is encountered. We had to modify HTTP client to use timeouts to detect when target service stopped.
There was one data race found with these tests in `querier.go` (see run https://github.com/grafana/mimir/actions/runs/5999120207?pr=5835). Other changes in integration tests were done to make tests pass when running slower.
This has some drawbacks:
- tests will be slower (https://go.dev/doc/articles/race_detector says that race-enabled binaries can be 2-20x slower). **Update: integration tests are about 15-20% slower on average, see next comment for timing.**
- we are no longer testing the image that's …
> Use race-enabled Mimir when running integration tests

- docs/sources/mimir/configure/about-runtime-configuration.md
After an internal conversation at Grafana Labs, we realised there's some misunderstanding around the `ingester_stream_chunks_when_using_blocks` note in the doc. In this PR I'm rephrasing based on a feedback received from @bboreham.
N/A
> Docs: clarify ingester_stream_chunks_when_using_blocks setting

- CHANGELOG.md
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
When dealing with a support case I was confronted with a trace where the trace ended in the frontend component, but actually the request was rejected in the scheduler. The problem is that we only trace requests that we successfully enqueued.
Internal ref: 7262
> scheduler: add trace span around enqueue

- CHANGELOG.md
- pkg/mimirtool/commands/analyse_grafana.go
`mimirtool analyze grafana` used to search for dashboards without any paging. The [Search API](https://grafana.com/docs/grafana/latest/developers/http_api/folder_dashboard_search/) has a default limit of 1000 and so folks with more than a 1000 dashboards are currently unable to use this tool. The API supports paging and so this PR updates mimirtool to try and fetch all pages with the default limit (1000).
> Add support for paging when searching for dashboards with mimirtool

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/config_test.go
The option `-blocks-storage.tsdb.max-tsdb-opening-concurrency-on-startup` was deprecated, and should be removed in 2.10
Relates to [Release 2.10](https://github.com/grafana/mimir/issues/5849)
> Remove deprecated `max-tsdb-opening-concurrency-on-startup` TSDB configuration.

- CHANGELOG.md
- pkg/mimirtool/analyze/grafana.go
- pkg/mimirtool/commands/testdata/apiserver.json
The current regex we use for extracting metric names from template variables that use the `label_values` function doesn't wuite work correctly because `label_values` can be used one of two ways:
1. It can be used with a label name such that it returns all label values across all metrics for that label, eg. `label_values(cluster)`
2. It can be used with a label name along with a metric expression such that only label values that appear on that metric are returned. eg. `label_values(kube_pod_info, pod)`. *Note that this can also involve metric expressions with additional filters, for example `label_values(kube_pod_info{"cluster"="cluster1"}, pod)`*.
The current regex we use incorrectly interprets label keys as metric names in the first situation, and doesn't handle metric expressions that …
> Fix regex for label_values metric extraction

- tools/release/check-changelog.sh
Makes check-changelog.sh ignore certain paths:
- Integration tests are never user-facing changes
- Helm has its own changelog
- CHANGELOG.md are not user-facing
- Docs describe what we're shipping
This reduces the number of PRs to review for 2.10 from 270 to 200.
Ref: [Release 2.10](https://github.com/grafana/mimir/issues/5849)
> check-changelog.sh: ignore certain paths

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
Renames the CPU scaling metric panel, and fixes the metric displayed (from `scaling metric + target metric` to `scaling metric / target metric`). The memory scaling metric will have no data until #5739 is merged.
> Fix CPU query for CPU scaling metric panel and add new panel for memory scaling metric

- .github/workflows/helm-ci.yml
After an upgrade of the kind HitHub action in grafana/helm-charts we ended up running with 1.26. This broke our CI because our manifests are expliticly pinned to 1.20. This lead to rendering outdated object versions (policy/v1beta1/PodSecurityPolicy)
After this PR https://github.com/grafana/helm-charts/pull/2618 we can now pin the k8s version in CI
> helm: pin kubernetes version to 1.20.8

- .github/dependabot.yml
The current group update doesn't work on dockerfile, see https://github.com/grafana/mimir/network/updates/716202916, and it is blocking the dependabot from running. Opened a [ticket](https://github.com/dependabot/dependabot-core/issues/7938) on dependabot/core, in the meanwhile remove group configuration for docker.
> Dependencies: Update dependabot.yml to remove group update on dockerfile

- CHANGELOG.md
- cmd/mimir/main_test.go
- pkg/frontend/v1/frontend.go
- pkg/frontend/v1/frontend_test.go
- pkg/mimir/mimir.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/scheduler.go
This PR adds two metrics that would have been useful during a recent performance investigation:
* it adds a histogram for the time taken to enqueue a request in the query-scheduler, and a corresponding metric for the query-frontend when the query-scheduler is not in use
* it exposes the `/sync/mutex/wait/total:seconds` metric exposed by the Go runtime (see https://github.com/golang/go/issues/49881)
(none)
> Add query-scheduler enqueue and Go mutex wait time metrics

- CHANGELOG.md
- pkg/mimirtool/backfill/backfill.go
- pkg/mimirtool/commands/remote_read.go
- pkg/mimirtool/commands/remote_read_test.go
When iterating over the samples returned by the remote read endpoint, the samples are grouped by series, e.g.:
```
{__name__="agent_build_info"} 1 1691474422539
{__name__="agent_build_info"} 1 1691474542539
{__name__="agent_build_info"} 1 1691474602539
{__name__="up"} 1 1691474422539
{__name__="up"} 1 1691474542539
{__name__="up"} 1 1691474602539
```
As long as all samples fall into the same block timespan (default is 2h and not configurable), this does not cause any issues. The same is the case if all series start at the same timestamp.
However if a block gets committed, the new minimum timestamp gets set to the lowest timestamp of the ingested samples up to now. If a series with an earlier starting timestamp exists in the remote_read response, this causes mimirtool to crash with an out …
> fix[mimirtool]: order samples when performing export

- CHANGELOG.md
- pkg/mimirtool/commands/analyse_grafana.go
* Add support for paging when searching for dashboards with mimirtool
(cherry picked from commit c7d8cb6d4b98b8782381cfab3d82ea8089375efe https://github.com/grafana/mimir/pull/5825)
> [release-2.10] Add support for paging when searching for dashboards with mimirtool

- CHANGELOG.md
- pkg/mimirtool/analyze/grafana.go
- pkg/mimirtool/analyze/grafana_test.go
The code didn't check whether `query_results` was matching before accessing the submatches, so it panicked when it didn't (in my case it didn't because it was a multiline query_results call).
I fixed that, and other issues around, adding unit tests.
Once in tests, I've added the query linked as _gross_ query, and fixed the metric name extraction when vector selector doesn't have the metric name part but only a `__name__` matcher.
None.
> mimirtool: analyze grafana fix metrics from tmpl

- CHANGELOG.md
- pkg/mimirtool/analyze/grafana.go
- pkg/mimirtool/commands/testdata/apiserver.json
* Fix regex for label_values metric extraction
* Exercise new functionality with a test
* Add changelog
(cherry picked from commit a03417fca779e7acca5cc9dfccf3d3d8406645ed https://github.com/grafana/mimir/pull/5832)
I'm backporting this to `release-2.10` because I want to backport https://github.com/grafana/mimir/pull/5911 which was made on top of it.
> [release-2.10] Fix regex for label_values metric extraction (#5832)

- CHANGELOG.md
- pkg/mimirtool/analyze/grafana.go
- pkg/mimirtool/analyze/grafana_test.go
mimirtool: analyze grafana fix metrics from tmpl
The code didn't check whether `query_results` was matching before accessing the submatches, so it panicked when it didn't (in my case it didn't because it was a multiline query_results call).
I fixed that, and other issues around, adding unit tests.
(cherry picked from commit fb8f9080a0032ac495dbb60af348559f1c011e29 https://github.com/grafana/mimir/pull/57)
> mimirtool: analyze grafana fix metrics from tmpl (#5911)

- .github/workflows/publish-technical-documentation-next.yml
- .github/workflows/publish-technical-documentation-release-helm-charts.yml
- .github/workflows/publish-technical-documentation-release-mimir.yml
- .github/workflows/test-build-deploy.yml
- .github/workflows/test-docs.yml
- docs/Makefile
- docs/README.md
- docs/make-docs
- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
- docs/variables.mk
- operations/helm/charts/mimir-distributed/RELEASE.md
This fixes links such as https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/monitor-system-health/#monitor-the-health-of-your-system:~:text=Collect%20metrics%20and%20logs%20without%20the%20Helm%20chart which come from using the information architecture in `main` rather than that of the version referenced by the Helm chart (`release-2.9`).
- Replace all Mimir docs links with `docs/reference` shortcode
Supports compile time link checking but requires specific build steps that still need to be properly automated.
At the moment, the `README.md` explains the steps.
For more information about the shortcode, refer to https://grafana.com/docs/writers-toolkit/write/shortcodes/#docsreference-shortcode.
- Fix links broken due to referencing wrong …
> Correctly build Mimir and Helm chart docs with link checking

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/limiter.go
- pkg/ingester/limiter_test.go
- pkg/ingester/metric_counter.go
- pkg/ingester/user_metrics_metadata.go
- pkg/ingester/user_tsdb.go
This PR refactors ingester errors creation in such a way that the latter is done in `ingester/errors.go`.
In particular:
- it gets rid of `ingester.Limiter.FormatError()` method, which is not needed anymore.
- all `newIngestErrXXX()` methods are moved from `ingester/ingester.go` to `ingester/errors.go`.
- all `formatMaxXXXError()` methods are moved from `ingester/limiter.go` to `ingester/errors.go`.
- all `AssertMaxXXX()` methods from `ingester/limiter.go` do not throw any error anymore, but return a `bool` representing the outcome of the check. Their names have been changed into `IsWithinMaxXXX()`.
> Refactor ingester errors creation

- pkg/storage/tsdb/block/index_test.go
Followup to https://github.com/prometheus/prometheus/pull/12054
Instead of hardcoding the chunk boundary, ignore chunks that contain time 600.
Instead of only checking the number of result chunks, verify that the right chunks are ignored and that there was ignore going on.
Fixes N/A
> block TestRewrite should not depend on chunk sizes

- pkg/storegateway/indexheader/stream_binary_reader_test.go
This test was using multiple TSDB heads in the same directory, so compaction between each and writing chunks to files would sometimes collide.
Fixes #5943
> store-gateway: fix race in TestStreamBinaryReader_CheckSparseHeadersCorrectnessExtensive

- go.mod
- pkg/storage/bucket/azure/bucket_client.go
- pkg/storage/bucket/azure/bucket_client_test.go
Pass config directly to `github.com/thanos-io/objstore/providers/azure.NewBucketWithConfig` instead of serializing it and calling `github.com/thanos-io/objstore/providers/azure.NewBucket`. Just a simple refactoring, no practical changes.
> Azure: Don't serialize config, pass it directly to Thanos

- pkg/storage/tsdb/block/block_test.go
The index file sizes depends on the number of chunks in it and that recently changed due to
https://github.com/prometheus/prometheus/pull/12054 This test shouldn't care about the exact number so let's just grab from the OS.
Related to #5927 
> block_test: do not hardcode index file size

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/querier.go
- vendor/modules.txt
Get the fix https://github.com/grafana/mimir-prometheus/pull/528
We have experienced spurious errors during head compaction on the labelvalues endpoint. This fixes the errors by
handling the case where 1) postings are read 2) head compaction clears series 3) stale postings are used to look up series.
Fixes N/A .
> Update mimir-prometheus to 20230907080713-7c067467a0fd

- CHANGELOG.md
This PR fixes changelog entry for PR #5752 to use common CLI flag format, instead of YAML field name.
> Fix changelog entry for PR #5752.

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
This makes the nginx proxy listen on IPv6.
It is also possible to make nginx listen with a single listener directive, but I chose this approach because that's exactly how it was done in Loki: https://github.com/grafana/loki/blob/main/production/helm/loki/templates/_helpers.tpl (Search for listen).
I don't believe this warrants a changelog entry, as it only fixes one aspect of IPv6 compatibility.
This makes the nginx proxy listen on IPv6 in addition to IPv4.
Relates to #3743
> Make nginx listen on IPv6.

- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/prometheus_test.go
- pkg/storegateway/series_refs_test.go
This is a prerequisite to #5927
Number of samples per chunk is changing in prometheus. Currently, only for native histograms, but also regular XOR chunks are capped at 1KiB.
This PR changes some tests to not rely on a hardcoded number of samples and also updates/removes some constants in the code. Instead it queries the blocks on disk using Prometheus code and compares this to what the store-gateway returns.
For chunk estimations I changed the tests to assert that the estimation is not off by more than 10% from the real number of chunks. I'd like to get a review from @charleskorn on whether this is an appropriate approach.
> store-gateway: stop relying on fixed number of samples per chunk

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
Currently, the errors returned by `Ingester.PushWithCleanup()` are created this way:
```
httpgrpc.Errorf(statusCode, err.Error())
```
This way, callers of `Ingester.PushWithCleanup()` cannot get any additional information about the error `err`, except its string representation. In order to fix this, this PR uses the already existing `validationError` struct to return errors. These errors can be unwrapped and compared by using `errors.Is()` and `errors.As()`.
This PR introduces a new struct, `errorWithCode` (implementing `builtin.error`, `grpc.grpcstatus`), that will be used as errot type returned by ingester.
Moreover, this PR renames `wrapWithUser()` function to `annotateWithUser()`, since it **doesn't wrap** the original error, and produces a new error having the same message annotated …
> Ingester should not return httpgrpc errors

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
This reverts commit 387a6300b09d38c64c37ede1006886b2c6d0d490.
We need to fix some additional things and will merge the reverted commit again.
> Revert "Ingester should not return httpgrpc errors (#5969)"

- CHANGELOG.md
- pkg/mimirtool/commands/analyse_grafana.go
The previous implementation applied the timeout for read requests to the entire command execution, which caused issues when fetching individual dashboards. Instead of protecting against individual long requests, the timeout was affecting the entire command execution, leading to timeouts during dashboard analysis.
To resolve this issue and improve the behavior of the `mimirtool analyze grafana` command, the following changes were made:
- Modified the `AnalyzeGrafana` function to accept a `readTimeout` parameter.
- Moved the body of the loop responsible for fetching dashboards to its own function called `analyzeDashboard`.
- Within `analyzeDashboard`,  create a child context for each dashboard request and cancel it before moving to the next iteration. This ensures that each context is …
> Update Grafana analysis timeout behavior

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/querier.go
- vendor/modules.txt
Backport of https://github.com/grafana/mimir/pull/5957
> [release-2.10] Update mimir-prometheus to 20230907080713-7c067467a0fd (#5957)

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/mimir/grpc_push_check.go
- pkg/mimir/grpc_push_check_test.go
- pkg/mimir/modules.go
This PR moves tracking of inflight push requests to gRPC handlers. We install 1) tap handle and 2) stats handler, and they work together to check if another push request is allowed, and track number of ongoing push requests.
Tap handle is called as soon as request headers are received, but before request body is read into memory. At that point we can check and reject request early, or accept it and increase ongoing requests. At this point no interceptor or stats handler has run yet, so if we reject request, the only record of request will be in `cortex_ingester_instance_rejected_requests_total` metric.
If tap handle allows the request to proceed, only then stats handlers and interceptors are called. Stats handler is also called after request has finished -- that is where we decrease …
> WIP: Track push inflight requests via grpc server handlers.

- packaging/nfpm/nfpm.sh
There's only one folder in packaging/nfpm/ which is `mimir`. `ls` complains if we try to list the non-existing folder, so let's check it before and remove the warning.
Improves the release process.
> release: only list dependencies when they exist

- CHANGELOG.md
- pkg/mimirtool/commands/remote_read.go
`filepath.Join` was used to join two part of a URL, resulting in encoded backslashes (`\` -> `%5C`) on Windows. This uses a more standard way of joining URLs.
Fixes #6009.
> Fix remote-read address joining in mimirtool

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/limiter.go
- pkg/ingester/limiter_test.go
- pkg/ingester/user_metrics_metadata.go
- pkg/ingester/user_metrics_metadata_test.go
In PR https://github.com/grafana/mimir/pull/5584 we introduced sampled logging of errors. The logic of sampling is implented in  the `Sampler` struct. The samplers are currently stored in the `samplers` field of `Limiter`.
This PR moves the `samplers` field from `Limiter` to `Ingester` (and renames it to `errorSamplers`), which is a more appropriate place for storing them.
Moreover, it improves the already existing tests `TestIngester_SampledUserLimitExceeded` and `TestIngester_SampledMetricLimitExceeded` by ensuring that samples errors get tracked by the `cortex_discarded_samples_total` counter.
Relates to #1900, #5894
> Move error samplers from Limiter to Ingester

- pkg/ingester/user_metrics_metadata_test.go
#5890 was merged too late after running its last CI, so much that `main` had drifted and 5890 introduced a compilation error
> ingester: fix TestUserMetricsMetadataRequest not compiling

- CHANGELOG.md
- pkg/ruler/notifier.go
Allows the ability to configure TLS for the alertmanager client in the Ruler, by reading secrets from Vault if present. This is now possible due to recent changes in `prometheus/common` that allow the passing of certificates and keys inline as part of the TLSConfig.
> Configure TLS for alertmanager client by reading from Vault

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/instance_limits.go
- pkg/ingester/instance_limits_test.go
- pkg/ingester/limiter.go
In PR https://github.com/grafana/mimir/pull/5584 we introduced the `safeToWrap` interface to annotate error types that can be safely returned by ingester. These errors can be safely wrapped with a userID and returned to the caller. On the other hand, it is not safe to wrap and return unsafe errors, and they are only annotated with a userID. The new function `wrapOrAnnotateWithUser()` implements this logic, and replaces both `wrapWithUser()` and `annotateWithUser()`.
Additionally, this PR marks some additional ingester errors as safe.
Relates to #6008
> Ensure that ingester returns safe errors

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- docs/sources/mimir/configure/configure-blocked-queries.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/frontend/querymiddleware/blocker.go
- pkg/frontend/querymiddleware/blocker_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/util/globalerror/errors.go
- pkg/util/validation/blocked_query.go
- pkg/util/validation/errors.go
- pkg/util/validation/limits.go
- tools/doc-generator/parse/parser.go
Add experimental query blocker
This commit implements the following proposal: #5029
> Query-frontend: Add experimental query blocker

- CHANGELOG.md
- pkg/distributor/distributor.go
In https://github.com/grafana/mimir/pull/5979 status codes 2xx were, erroneously, treated as error codes. Although unrealistic, this cases should be removed.
Moreover, in https://github.com/grafana/mimir/pull/5584 some entries in CHANGELOG were, erroneously, duplicated. They are removed by this PR.
> Don't treat 2xx status codes as error

- integration/backward_compatibility.go
2.3.0 was released one year ago, so we're removing backwards compatibility tests for versions older than that.
N/A
> Remove backwards compatibility tests for >1y

- pkg/ingester/ingester_test.go
This PR introduces a test that shows that, when a circuit breaker is setup for ingesters, and when an ingester hits a per-instance limit, the circuit breaker is triggered.
Circuit breakers are introduced in this [PR](https://github.com/grafana/mimir/pull/5650).
> Ingester: test hitting per-instance limits with circuit breaker

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/instance_limits.go
In https://github.com/grafana/mimir/pull/5979 we temporary allowed a creation of gRPC errors by using HTTP status codes. This is done by the `newErrorWithStatus()` function, which was supposed to replaced previous usages of `httpgrpc.Errorf()`. Unfortunately, by doing so, when a system contains a version of distributor prior to https://github.com/grafana/mimir/pull/5979, and a version of ingester compatible with that PR, the error cannot be recognized.
In order to fix this, this PR introduces another method, `newErrorWithHTTPStatus()`, which generates ingester error objects with the required HTTP status code, that can be recognized by distributors prior to https://github.com/grafana/mimir/pull/5979.
This is still a **temporary** solution, and it is expected to remove creation of errors …
> Allow ingester to return httpgrpc errors

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/metrics.go
- pkg/ingester/user_metrics_metadata_test.go
Enhanced Precision Alerting: Utilising Quantile Analysis for In-Flight Requests
Replaced gauge with summary metric, leveraging quantile analysis on Ingester in-flight requests, resulting in more precise alerts.
> Ingester: Add metric to track inflight requests

- CHANGELOG.md
- pkg/util/push/otel.go
- pkg/util/push/push_test.go
Fixes index out of range introduced https://github.com/grafana/mimir/pull/5693/files#diff-eb47b1b5619b45185602515d8d5274a06451058d43aaa9c85c9fc1a7222635c3R189 due to bad assumptions around shape of the data.
Sample log of the panic caused by not making the pre-allocated not long enough.
```
2023/09/15 16:56:46 http: panic serving 10.30.101.227:60402: runtime error: index out of range [56] with length 56
goroutine 1267 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x23c29a0?, 0xc001818288?})
/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1()
/go/src/github.com/grafana/mimir/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:155 +0x175
panic({0x23c29a0?, …
```
> chore: fix index out of range in metrics metadata

- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
- docs/sources/mimir/manage/monitor-grafana-mimir/collecting-metrics-and-logs.md
This is cherry-picking https://github.com/grafana/mimir/commit/bddb996ca7fb19f74bfac8e90ed156af90f4afd7
> [release-2.10] Backport: Docs: fix link to self hosted mimir integrations (#6092)

- CHANGELOG.md
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/bucket_test.go
Emit metrics about the number of blocks a store-gateway has loaded based on the duration of the blocks (bucketed into the block durations the compactor is configured to produce).
A common symptom of the compactor failing is store-gateways loading more 2h blocks that usual and degrading performance of the read path. Counting the number of blocks by duration allows us to detect when this happens.
N/A
> Count the number of blocks loaded by a store-gateway by duration

- CHANGELOG.md
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/frontend/v2/frontend_test.go
I'm investigating some query performance and I noticed we don't have any metric to see how long it takes to enqueue requests in the query-frontend when query-scheduler is in use. Im this PR I propose to track `cortex_query_frontend_enqueue_duration_seconds` also when query-scheduler is in use, so that we can track the enqueuing latency end-to-end.
N/A
> Track cortex_query_frontend_enqueue_duration_seconds metric even when query-scheduler is in use

- docs/internal/contributing/vscode-goimports-settings.json
File was a bit out of date and format flags were not taking effect. Updating based on latest settings.
> Update docs for VSCode Go import settings for Mimir

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
- vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
- vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram_meta.go
- vendor/modules.txt
Adds https://github.com/prometheus/prometheus/pull/12838
Follows #6101.
Includes mimir-prometheus https://github.com/grafana/mimir-prometheus/commit/16653689899cff61f4c779687e184c26e49b45c0 from 2023-09-01 and
https://github.com/prometheus/prometheus/pull/12874
Fixes #5576 
> Update mimir prometheus to a10cef685b49 (2023-09-01)

- CHANGELOG.md
- pkg/alertmanager/alertmanager_ring.go
- pkg/compactor/compactor_ring.go
- pkg/distributor/distributor_ring.go
- pkg/frontend/v2/frontend.go
- pkg/ruler/ruler_ring.go
- pkg/scheduler/schedulerdiscovery/ring.go
- pkg/scheduler/schedulerdiscovery/ring_test.go
- pkg/storegateway/gateway_ring.go
- pkg/util/validation/exporter/ring.go
Fixes an issue when using IPv6 where IPv6 addresses are not properly joined with ports resulting in the ring attempting to incorrectly use `::1:7496` instead of the proper `[::1]:7496` notation.
With this change it's fully possible to use Mimir within an IPv6 only network.
Fixes #3743
---
For those interested in trying this out, here is a shortened snippet of the configuration changes I needed to make in order to get IPv6 working.
```yaml
alertmanager:
sharding_ring:
instance_enable_ipv6: true
compactor:
sharding_ring:
instance_enable_ipv6: true
distributor:
ring:
instance_enable_ipv6: true
ingester:
ring:
instance_enable_ipv6: true
memberlist:
bind_addr:
- '::'
bind_port: 7946
cluster_label: mimir
query_scheduler:
service_discovery_mode: ring
ring:
instance_enable_ipv6: true
ruler:
ring: …
```
> ring: Use `net.JoinHostPort` to support IPv6 addresses

- README.md
- docs/sources/mimir/set-up/migrate/migrate-from-thanos-or-prometheus.md
This PR:
* fixes the link to 'migrating from Thanos or Prometheus' in the readme (it previously 404ed)
* updates the link to 'migrating from Cortex' in the readme (it previously went to the old page, which had a redirect set up)
* adds an alias for the new 'migrating from Thanos or Prometheus' page from the old path
Fixes #6114
> Fix link to 'migrating from Prometheus or Thanos' in readme

- CHANGELOG.md
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_stores.go
Use a hard-coded list of durations instead of requiring the store-gateway to be aware of compactor-specific configuration.
Related #6074
> Use hard-coded list of block durations in store-gateway

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/storage/tsdb/config.go
When we introduced the series hash cache, we initially set the default `-blocks-storage.tsdb.series-hash-cache-max-size-bytes` setting to a random number (1GB). In this PR I propose to upstream a config change we recently did at Grafana Labs and change the default setting to 350MB, which is enouch to store the hashes for all series queried from an ingester, assuming the 13h TSDB retention (default) and up to 2M in-memory series in the ingester.
N/A
> Change default -blocks-storage.tsdb.series-hash-cache-max-size-bytes from 1GB to 350MB

- CHANGELOG.md
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/main.go
- docs/sources/mimir/configure/about-versioning.md
We're running `-log.buffered=true` in production since few weeks and everything looks good. I propose to change the default to true, and also deprecate it, so that will be removed in 2 releases (plan is to always use the buffered logger).
N/A
> Change -log.buffered default to true

- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
Related to https://github.com/grafana/mimir/issues/4762
The existing logging can be noisy when the upgrade happens. This is because the eager loading snapshot file isn't found. This emits a log line for trying to read the file and then a log line for trying to delete it. This can be unnecessarily worrying especially when there are many tenants. This PR removes logging when the file isn't found and doesn't attempt deleting it.
It also removes the `tenant` log field since that's redundant with the user logger we're using.
```
ts=2023-09-25T19:57:41.797242382Z caller=reader_pool.go:104 level=warn user=123 msg="loading the list of index-headers from snapshot file failed; not eagerly loading index-headers for tenant" file=/data/tsdb/123/lazy-loaded.json err="open …
```
> store-gateway: reduce logging for not finding eager loading snapshot

- docs/sources/mimir/configure/about-anonymous-usage-statistics-reporting.md
- docs/sources/mimir/configure/about-runtime-configuration.md
GEM documentation has links to the absolute paths referenced in the comments in this PR. With the aliases in place, Hugo creates redirects, fixing the links.
> Update aliases with comments for clarity and add missing aliases to fix 46 broken links in GEM docs

- CHANGELOG.md
- go.mod
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/frontend/v2/frontend_test.go
This PR addresses a feedback received [here](https://github.com/grafana/mimir/pull/6087#pullrequestreview-1638980230). In this PR I proposes to track `cortex_query_frontend_enqueue_duration_seconds` by `query-scheduler` address, to have better visibility in case the slowdown is caused by a specific scheduler.
I've also took the opportunity to customise the `cortex_query_frontend_enqueue_duration_seconds` histogram buckets, to track 1ms latency too and removing any bucket bigger than 1s.
N/A
> Track cortex_query_frontend_enqueue_duration_seconds by query-scheduler

- CHANGELOG.md
- packaging/nfpm/mimir/mimir.logrotate
- packaging/nfpm/nfpm.jsonnet
In case users decide to store Mimir's logs out of journald (e.g. `/var/log/mimir.log`), we want to be sure that Mimir's logs won't fill up the disk.
N/A
> Add logrotate config

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-custom-target-utilization.jsonnet
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
This PR updates the memory scaling trigger for autoscaling components so that they treat OOMing containers as utilizing their entire memory request. It also adds a memory scaling trigger to ruler-queriers, which previously only scaled on CPU. Previously, if ruler-queriers OOMed and CPU usage went down, they would scale down, putting more memory pressure on the remaining ruler-queriers. 
This also updates the remote ruler reads dashboard to fix a panel query bug, and separates panels for ruler-querier CPU and memory scaling metrics.
(none)
`N/A` Documentation added
> Scale on OOMs for autoscaling components

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
This PR fixes the issue where the GossipMembersMismatch warning fires with a message like `Mimir instance  in prod-cluster/mimir-prod-01 sees incorrect number of gossip members.`
https://github.com/grafana/mimir/pull/1926 removed the per-instance labels in the alert query, so I'm updating the message to match. (The other option would be to add the per-instance labels to the alert query, but that seems to go against the intention of #1926.)
(none)
> Remove reference to per-instance labels in GossipMembersMismatch warning

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
When using `-ingester.limit-inflight-requests-using-grpc-method-limiter` option from PR https://github.com/grafana/mimir/pull/6073 and https://github.com/grafana/mimir/pull/5976, then requests rejected early don't count towards standard Mimir metrics like `cortex_request_duration_seconds_count`, and aren't visible on the dashboard.
This PR adds option to show rejected requests to Mimir Writes dashboard.
Without showing rejected requests:
With showing rejected requests:
> Add option to show rejected requests on Mimir writes dashboard.

- CHANGELOG.md
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/user_queues.go
This PR addresses some post-merge feedback on #6100,  https://github.com/grafana/mimir/pull/6100#issuecomment-1736897602:
> But your response prompted another question. Since the context is cancelled promptly, then do we need the extra cleanup in `cancelWaitingConnectionsForQuerier`? For all pending querier connections in `waitingQuerierConnections` we'd eventually hit [this condition](https://github.com/grafana/mimir/blob/a6d8fea3f302996073cb3d7e2868a72d1db833be/pkg/scheduler/queue/queue.go#L243-L247) and then remove the connection from `waitingQuerierConnections`
#6100
> Query-scheduler: remove unnecessary cleanup after graceful querier shutdown notification

- pkg/ingester/errors.go
- pkg/ingester/ingester.go
- pkg/ingester/user_tsdb.go
This PR gets rid of errors `errMaxSeriesPerMetricLimitExceeded` and `errMaxSeriesPerUserLimitExceeded`, which are redundant, and can be replaced with `globalerror.MaxSeriesPerMetric` and `globalerror.MaxSeriesPerUser`.
Related to https://github.com/grafana/mimir/issues/1900, https://github.com/grafana/mimir/issues/6008
> Get rid of errMaxSeriesPerMetricLimitExceeded and errMaxSeriesPerUserLimitExceeded

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- development/mimir-microservices-mode/config/mimir.yaml
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/ingester/ingester.go
- pkg/storage/tsdb/config.go
- vendor/github.com/prometheus/prometheus/tsdb/block.go
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/github.com/prometheus/prometheus/tsdb/head.go
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/github.com/prometheus/prometheus/tsdb/querier.go
- vendor/modules.txt
In this PR I'm updating `mimir-prometheus` to get https://github.com/grafana/mimir-prometheus/pull/533. It adds a config option to limit the `PostingsForMatchers()` cache size by bytes too. I'm also deprecating the "limit by number of items", cause the plan is that the "limit by bytes size" will replace it. Even if these config options are experimental, I'm not directly removing the "limit by number of items" config option rightaway, to smooth the transition at Grafana Labs.
_I've manually tested it and looks working as expected_ 🤞 
N/A
> Add config option to limit PostingsForMatchers() cache by size in bytes too

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/model/labels/regexp.go
- vendor/modules.txt
In this PR I'm updating mimir-prometheus to get https://github.com/grafana/mimir-prometheus/pull/536.
N/A
> Update mimir-prometheus to get 'alternations ending with .*' regexp optimization

- pkg/api/api.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_activity.go
- pkg/ingester/ingester_test.go
- pkg/util/push/push.go
- pkg/util/push/push_test.go
This PR changes the signature of the `push.Func` function from
```
type Func func(ctx context.Context, req *Request) (*mimirpb.WriteResponse(), error)
```
to
```
type Func func(ctx context.Context, req *Request) error
```
The main reason for this change is that all implementations of `push.Func()` actually return:
- `&mimirpb.WriteResponse()` in the case of no error, or 
- `nil` in the case of error.
This logic has been moved to the topmost callers of `push.Func()`, which are mostly `ingester.Push()` and `distributor.Push()`.
This refactoring is just a preliminary change needed for a bigger refactoring and improving of intester's and distributor's write path error handling.
Related to https://github.com/grafana/mimir/issues/1900, https://github.com/grafana/mimir/issues/6008
> Refactoring: change the signature of push.Func function

- operations/helm/charts/mimir-distributed/CHANGELOG.md
Fixes the broken link for nginx proxy migration that is near the top of the helm chart changelog. Looks like the grafana docs got reorganized?
None yet? I didn't create or look for one tbh
> Fix broken migration link in helmchart changelog

- CHANGELOG.md
- integration/ruler_test.go
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
Adds a new per-tenant metric `cortex_ruler_queries_zero_fetched_series_total` in ruler to track rules that fetched no series, so that users can add an alert on this metric to see if there is any late data affecting the rules, which could potentially result in alerts not firing when they should (we have had cases of that in the past). When they see this counter increase, they can search the logs for `fetched_series_count=0` to find the affected query. Since this metric relies on query stats, it needs to be enabled before the metric is available, similar to `cortex_ruler_query_seconds_total`.
~~Haven't added tests yet as I'm not sure if we want to take this approach (is enabling query stats too heavy? but I'm not sure how else to track this), but if we decide to go with this then I'll add …
> Add new metric in ruler to track rules that fetched no series

- cmd/mimir/config-descriptor.json
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/vault/auth.go
YAML is `user_pass` and `app_role` whereas CLI flags are `userpass` and `approle` - updating so they are both consistent
> Update Vault Auth YAML fields to be consistent with CLI flags

- docs/sources/mimir/manage/tools/mimirtool.md
- docs/sources/mimir/references/http-api/index.md
- pkg/mimirtool/commands/alerts.go
https://github.com/grafana/mimir/issues/6137 prompted me to document the behaviour of the `POST /api/v1/alerts` endpoint. This also adds an example of setting a template file via `mimirtool alertmanager load`, but now with a relative path allowed by the changes in https://github.com/grafana/mimir/pull/6138
> alertmanager: improve docs for updating tenant configuration

- .github/workflows/push-mimir-build-image.yml
- Makefile
- mimir-build-image/Dockerfile
https://github.com/grafana/mimir/pull/6180/files update build-image failed because bug of docker/login-action@v3, there is a similar ticket opened in repo https://github.com/docker/login-action/issues/606, ~~fallback github action~~ downgrade to docker/login-action v2 to unblock docker image update.
See failed build https://github.com/grafana/mimir/pull/6180
> Bump alpine/helm from 3.11.1 to 3.13.0 in /mimir-build-image

- CHANGELOG.md
- pkg/api/error/error.go
- pkg/api/error/error_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
Backport #6032 (Query-frontend: Don't retry on HTTP 503 from ingester limiting) to release 2.10 branch. It was suggested by @colega during the Mimir community call that we include this fix in the 2.10 series, so it can be included in the next patch version.
TODO:
> Backport PR 6032 (don't retry rejected queries) to release 2.10

- docs/proposals/query-blocking.md
This PR is a nit and only flag the query blocking proposal as accepted.
The related feature has been implemented via #5609 
N/A
> [proposal] Flag query blocking proposal as accepted

- .github/dependabot.yml
Make the dependencies in mimir-build-image update in group
Activate group PRs on one dockerfile, this is fixed by dependabotcore, tested PR in fork: https://github.com/ying-jeanne/mimir/pull/47. Group all dockerfiles' update is still not working.
> Dependencies: Group mimir-build-image dependencies

- CHANGELOG.md
- pkg/mimirtool/commands/alerts.go
- pkg/mimirtool/commands/alerts_test.go
- pkg/mimirtool/commands/testdata/alertmanager_template.tmpl
- pkg/mimirtool/commands/testdata/otherdir/alertmanager_template.tmpl
Makes sure templates sent to Mimir via the `mimirtool alertmanager load` command don't contain the full path, but instead only file name.
Fixes #6137
- ~~Documentation added~~ (N/A)
> mimirtool: Don't send template full path in 'alertmanager load'

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/nginx-configmap.yaml
Fixes inconsistency between legacy nginx and unified gateway nginx config.
Related to #5948 
> Helm: let the new nginx config under gateway config listen on ipv6

- CHANGELOG.md
- tools/trafficdump/main.go
- tools/trafficdump/model.go
- tools/trafficdump/parser.go
- tools/trafficdump/processor.go
This PR adds support for parsing OTEL requests to `trafficdump`.
> trafficdump: add support for parsing OTEL requests

- .github/workflows/push-mimir-build-image.yml
In the GitHub workflow for publishing the Mimir build image, make `gh pr comment` use PR number instead of `$PR_URL`. I'm not even sure if `$PR_URL` is set, it could look as if it should be `$PR_NUMBER`, which is unused.
`gh pr comment` supports both PR numbers and PR URLs. A PR number is clearly the more straightforward option.
> Make gh pr use PR number in build image publishing workflow

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/model/labels/regexp.go
- vendor/modules.txt
In this PR I'm updating mimir-prometheus to get another regexp optimization (https://github.com/grafana/mimir-prometheus/pull/537) focused on `?`.
N/A
> Update mimir-prometheus to get 'quest' regexp optimization

- CHANGELOG.md
- pkg/api/api.go
Otherwise the parameter is unuseable from yaml config: mimir-monolithic-mode-mimir-1-1
error loading config from ./config/mimir.yaml:
Error parsing config file: yaml: unmarshal errors:
mimir-monolithic-mode-mimir-1-1
line 4: field enable_otel_metadata_translation not found in
type api.Config
Related to: #5693 
> Fix visibility of enableOtelMetadataStorage

- go.mod
- go.sum
- vendor/github.com/grafana/regexp/README.md
- vendor/github.com/grafana/regexp/backtrack.go
- vendor/github.com/grafana/regexp/exec.go
- vendor/github.com/grafana/regexp/onepass.go
- vendor/github.com/grafana/regexp/regexp.go
- vendor/github.com/grafana/regexp/syntax/prog.go
- vendor/modules.txt
This reverts commit 88a5289fda1d938a9d4df33ab4bba81a1ab25f1f.
See [comment](https://github.com/grafana/mimir/pull/6223#issuecomment-1750831584) as to why.
> Revert "chore(deps): update github.com/grafana/regexp digest to 6b5c0a4 (main) (#6223)"

- pkg/api/api.go
- pkg/mimir/modules.go
This PR gets rid of the `/ingester/push` endpoint. This endpoint was introduced for testing and debugging, and has not been used. Moreover, it is not a part of the [documented public API](https://grafana.com/docs/mimir/latest/references/http-api/). Therefore, it will be removed.
Related to Related to https://github.com/grafana/mimir/issues/1900, https://github.com/grafana/mimir/issues/6008
> Get rid of /ingester/push endpoint

- CHANGELOG.md
This PR updates CHANGELOG.md to document the `/ingester/push/` endpoint de-release performed in a previous [PR](https://github.com/grafana/mimir/pull/6299).
> Update CHANGELOG.md to document /ingester/push de-release

- CHANGELOG.md
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
- pkg/querier/distributor_queryable_streaming_test.go
This PR makes a number of small improvements to ingester and store-gateway chunks streaming:
* it differentiates between ingester and store-gateway chunks streaming in errors and log messages
* it adds the number of series expected to "stream exhausted" errors
* it logs errors encountered while reading chunks to the querier logs, rather than just attaching them to a trace span
(none)
> Improve logging and errors when using ingester and store-gateway chunks streaming

- .github/workflows/push-mimir-build-image.yml
Modify GitHub workflow for publishing build image, so the job only has permission to read repo content and to modify the PR. It doesn't need any other GitHub permissions, so this increases security.
This will also give Dependabot permission to modify the PR, which it doesn't have previously (and breaks the workflow when executed for Dependabot PRs).
If you see [the documentation](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes), a GitHub workflow can specify non-default permissions for a job. Dependabot should have read-only permissions for the (automatic) GITHUB_TOKEN secret by default, but it should be possible to configure it to have specific write permissions. It should [not be …
> Restrict GitHub build image workflow permissions

- renovate.json
Configure Renovate to ignore github.com/grafana/goautoneg, since we are now using this instead of github.com/charleskorn/goautoneg. See `replace` directive in go.mod.
> Renovate: Ignore github.com/grafana/goautoneg

- CHANGELOG.md
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/main.go
- docs/sources/mimir/configure/about-versioning.md
- pkg/util/log/log.go
- pkg/util/log/log_test.go
This parameter is a _size_, not a _rate_.  Name it correctly. 
Also, I don't think we want processes to be able to output 25,000 lines instantaneously - that's what the rate limit was intended to avoid. Changed the default to 1,000.
> Fix name and default of log burst size

- pkg/querier/querier.go
Unexport `querier.NewQueryable`, since it's not used outside of the `querier` package (also not in our enterprise product). Not exporting the function signals to the reader that it's purely internal, reducing complexity.
> Unexport querier.NewQueryable

- renovate.json
AFAICT, the Renovate rule for ignoring our pinned (via `replace` directives) Go modules is configured wrong. Reading the `packageRules` [documentation](https://docs.renovatebot.com/configuration-options/#packagerules), I don't find a single mention of `packagePatterns`. Instead I find [`matchPackagePaterns`](https://docs.renovatebot.com/configuration-options/#matchpackagepatterns) and [`matchPackageNames`](https://docs.renovatebot.com/configuration-options/#matchpackagenames). I suggest we use `matchPackageNames` since we don't use actual patterns, but full module names.
Please point out if I'm missing something :)
> Renovate: Fix rule for ignoring pinned modules

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
Manual backport of #6325. Update golang docker tag to v1.21.3 (cherry picked from commit ed62c6eb7ee8efceda0081713e668265505ebe6e).
> [release-2.10] Backport chore(deps): update golang docker tag to v1.21.3 (main) (#6325)

- renovate.json
Enable `go mod tidy` in Renovate PRs to update Go dependencies. Should fix our current problem of these PRs not updating go.sum.
See [documentation](https://docs.renovatebot.com/configuration-options/#postupdateoptions) on the option.
> Renovate: Enable go mod tidy

- renovate.json
Since we activate renovate, it updates dependency whenever new version released, it could be noisy, instead we do update only on every Monday before 9am. And security update would be anytime.  based on this thread https://github.com/renovatebot/renovate/issues/1567 and related doc https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts
> Chore: Set renovate PRs only on monday before 9am UTC timezone

- CHANGELOG.md
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
This PR fixes the issue where a query executed with either form of chunks streaming enabled can fail with a `attempted to read series at index XXX from stream, but the stream has already been exhausted` error if streaming chunks fails for some reason (eg. hitting a limit), and the PromQL engine continues consuming series, ignoring the error when it is initially returned.
This _shouldn't_ happen (the PromQL engine should stop after the first failure), but https://github.com/grafana/mimir-prometheus/pull/540 is an example of a case where this didn't hold true.
This PR won't fix the issue of the PromQL engine not stopping, but it does improve the user experience to include the original error, rather than the generic `stream has already been exhausted` error.
(none)
- [n/a] Documentation …
> Continue returning previous error message if a chunks stream fails but the PromQL engine continues consuming series

- CHANGELOG.md
- pkg/querier/block.go
- pkg/querier/block_streaming.go
This PR applies https://github.com/grafana/mimir/pull/5836 to two additional places that could benefit from it.
This improves performance when using `stringlabels` (as Mimir does). Note that the existing benchmark includes iterating through all of the samples in the series, which is why there isn't a dramatic latency change in the results below:
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/mimir/pkg/querier
│ before.txt  │             after.txt             │
│   sec/op    │   sec/op     vs base              │
_blockQuerierSeriesSet_iteration-10   812.2m ± 0%   814.8m ± 0%  +0.32% (p=0.009 n=6)
│  before.txt  │             after.txt              │
│     B/op     │     B/op      vs base              │
_blockQuerierSeriesSet_iteration-10   8.426Mi ± 0%   7.694Mi ± 0%  -8.69% …
```
> Improve performance of labels comparison when querying store-gateways

- integration/e2emimir/client.go
- pkg/api/api.go
- pkg/continuoustest/otlp_writer.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
- pkg/distributor/otel.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/distributor/request.go
- pkg/distributor/request_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_activity.go
- pkg/ingester/ingester_test.go
This PR is another refactoring needed for improving of ingester's and distributor's error handling. The main changes are:
- the content of `util/push` has been moved under the `distributor` package: the reason for this is that the push interacts only with the distributor, so it makes sense to place the former in the `distributor` package.
- the distributor errors that are currently declared in the `distributorerror` package have been moved under the `distributor` package: the reason `distributorerror` was created was to prevent a circular dependency between `push` and `distributor` packages.
Part of https://github.com/grafana/mimir/issues/6008
> Get rid of util/push and distributor/distributorerror packages

- pkg/distributor/distributor.go
- pkg/distributor/otel.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
One of the previous refactorings ([PR](https://github.com/grafana/mimir/pull/6356)) moved the content of the `util/push` package under the `distributor` package. That PR also un-exported the `push.Func` function by renaming it into `distributor.pushFunc`. 
This PR exports the `distributor.pushFunc` because it is needed by `backend-enterprise`.
> Export distributor.pushFunc because it is needed externally

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/instance_limits_test.go
Ingester's `ingester.pushSamplesToAppender()`, called by `ingester.Push()`, appends samples and exemplars to the appender. The former distinguishes between:
- _soft errors_, which should allow `ingester.Push()` to continue its execution and to ingest all valid samples and exemplars, and to return the first encountered error only at the end, and 
- _other errors_, that should be returned immediately.
So far there was no precise way to determine which error is a soft error. This PR introduces `softError`, an interface that should be implemented by all the errors that shouldn't prevent `ingester.Push()` from going ahead. Only these errors will be considered as _soft errors_ by `pushSamplesToAppender()`.
Related to https://github.com/grafana/mimir/issues/6008
> Allow ingester.Push() to proceed on soft errors only

- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/docker-compose.yml
This PR increases the value of `JAEGER_REPORTER_MAX_QUEUE_SIZE` for all local development Docker Compose environments.
The previous value (the default, which is 100) could sometimes lead to spans being dropped. This manifests as child spans of dropped spans not being nested correctly when viewing a trace. For example:
(none)
> Increase JAEGER_REPORTER_MAX_QUEUE_SIZE for Docker Compose environments

- CHANGELOG.md
- pkg/mimir/modules.go
- pkg/querier/tenantfederation/merge_exemplar_queryable.go
- pkg/querier/tenantfederation/merge_exemplar_queryable_test.go
- pkg/querier/tenantfederation/merge_queryable.go
- pkg/querier/tenantfederation/merge_queryable_test.go
Adds new histograms for the number of tenants queried by exemplar, label name, label value, instant, or range queries.
N/A
> Emit histogram for number of tenants queried by federation

- .github/workflows/push-mimir-build-image.yml
Give "Build and Push mimir-build-image" GitHub workflow permission to push commits, since the current permission set isn't enough. See [example](https://github.com/grafana/mimir/actions/runs/6527802011/job/17723123228) of build that failed due to inability to push commit to PR head branch.
From reading the [reference documentation](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) on GitHub job permissions, I conclude that `contents: write` is necessary (upgrading from `contents: read`).
Also giving the commit push command an explicit branch to push to and from (`HEAD`), so we don't have to rely on the correct tracking branch.
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, …
> Give build image GitHub workflow permission to push commits

- CHANGELOG.md
This PR updates CHANGELOG.md  to document changes done in https://github.com/grafana/mimir/pull/6377.
> Update CHANGELOG to document new distributor.Push() errors

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/compactor.libsonnet
This adds a `critical` version of the `CompactorSkippedBlocksWithOutOfOrderChunks` alert. The idea is that if many out-of-order chunks are preventing blocks from being compacted, eventually the read path could be impacted since store-gateways would have to handle more numerous, smaller blocks. The critical alert signals that the reason for the out-of-order chunks should be investigated before the read path is affected.
This PR would give critical alerts for issues like https://github.com/prometheus/prometheus/issues/12873
> critical compactor alert for multiple out-of-order chunks

- CHANGELOG.md
- pkg/mimir/modules.go
Federation Queryable implementations need to include the `engine` label to differentiate metrics from the tenant federation ruler and tenant federation querier.
N/A
> Add `engine` label to federation metrics added in #6374

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This PR fixes a regression introduced by https://github.com/grafana/mimir/pull/6416, where we replaced usages of `grpc/status` with `gogo/status` for ingester's gRPC error creation. 
Namely, if an error created by `gogo`'s `status.Error()` is wrapped (for example by using `errors.Wrap()` or `fmt.Errorf("...%w...")`, the resulting error is not recognized by `status.FromError()`. In the case of grpc's `status.Error()` this was not the case, i.e., even wrapped errors were recognized by `grpc`'s `status.FromError()`. 
Therefore, the only place where ingester errors are wrapped (`Distributor.handleIngesterPushError()`) must be updated in such a way that even the wrapped gRPC errors coming from the ingester preserve their type and semantics.
Part of https://github.com/grafana/mimir/issues/6008
> Distributor: improve wrapping of gRPC errors returned by the ingester

- pkg/ingester/ingester.go
This PR just removes a redundant nil [recently introduced](https://github.com/grafana/mimir/pull/6324/files#diff-e1032332627c413a3010c66b54b22b6e9835cf152fa339e40cf0b11204f7241fR1229-R1231) in `Ingester.pushSamplesToAppender()`.
> Get rid of a redundant nil check in pushSamplesToAppender()

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
There are several very similar `new<X>ScaledObject` functions. This PR should be a no-op which cleans up several of them, consolidating into one `newResourceScaledObject` for objects that scale on CPU and memory resources. I've left `newRulerQuerierScaledObject` alone even though it is scaled on CPU and memory because it has the most inconsistent metric naming convention.
This PR also introduces a small fix for `memoryHPAQuery`, which would previously report no data if no containers were up -- now it will report 0 instead.
https://github.com/grafana/mimir/pull/5739#pullrequestreview-1640779359
> Dedupe scaled object creation functions

- CHANGELOG.md
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
This PR addresses some [post-merge feedback](https://github.com/grafana/mimir/pull/6345/files#r1363891539) from @pracucci on #6345.
#6345
> Return any previous error if a chunks stream fails but the PromQL engine continues returning series

- go.mod
- go.sum
- pkg/ingester/ingester.go
- pkg/ingester/user_tsdb.go
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/modules.txt
Upgrade mimir-prometheus to [97933fb7d38e](https://github.com/grafana/mimir-prometheus/tree/97933fb7d38e). The only change is that the `ctx` argument is dropped from `tsdb.DB.UnorderedChunkQuerier`.
> Upgrade mimir-prometheus to 97933fb7d38e

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/_helpers.tpl
> helm: quote checksum/config when using external config

- docs/sources/mimir/manage/mimir-runbooks/_index.md
This PR improves the runbook for the `EtcdAllocatingTooMuchMemory` alert.
(none)
> Add note about recreating pods to runbook for EtcdAllocatingTooMuchMemory alert

- tools/release/common.sh
- tools/release/create-draft-release-notes.sh
Fixes #4824
* Get the last release using `git describe` (thanks to @pstibrany)
* Get previous release using some bash/sed-fu (thanks to @pracucci)
To test use this script in your local mimir repo. This script has some logic with the one in the PR. Please make sure to switch to release-xxx branch you want to test.
```bash
SED=$(which gsed || which sed)
LAST_RELEASE_VERSION="mimir-2.10.0-rc.2"
ALL_RELEASE_TAGS=$(git tag --list 'mimir-[0-9]*')
SORTED_RELEASE_TAGS=$(echo "$ALL_RELEASE_TAGS" | $SED '/rc/b; s/\(.*\)/\1-xx.x/' | sort --version-sort | gsed 's/-xx.x//')
if [[ $LAST_RELEASE_VERSION =~ "-rc" ]]; then
PREV_RELEASE_TAG=$(echo "$SORTED_RELEASE_TAGS" | grep $(echo $LAST_RELEASE_VERSION) -B1 | head -1)
else 
PREV_RELEASE_TAG=$(echo "$SORTED_RELEASE_TAGS" | grep -v -- '-rc' | grep $(echo …
```
> Fix find_prev_release() in tools/release/common.sh returns incorrect tag

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/modules.txt
Upgrade to mimir-prometheus@d0d6240125f9, which brings in https://github.com/grafana/mimir-prometheus/pull/546, that fixes a bug affecting ingesters, where canceled queries may get cached (thus failing also consecutive requests, due to the poisoned cache entry).
> Upgrade to mimir-prometheus@d0d6240125f9

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/modules.txt
Upgrade r260's mimir-prometheus dependency to [693f219a88e224c96422be0e01aedfe14bfbfeab](https://github.com/grafana/mimir-prometheus/tree/693f219a88e224c96422be0e01aedfe14bfbfeab), which brings in https://github.com/grafana/mimir-prometheus/pull/546.
> Upgrade r260 to mimir-prometheus@693f219a88e2

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/header_test.go
- pkg/storegateway/indexheader/reader_pool.go
We have `-blocks-storage.bucket-store.index-header.eager-loading-startup-enabled=true` enabled in production since few weeks at Grafana Labs and there's no known issue. I propose to enable it by default. To enable it by default without incurring into config validation errors if someone has lazy loading disabled, I've changed a bit the logic to simply ignore it when lazy loading is disabled, instead of returning an error.
N/A
> Enable -blocks-storage.bucket-store.index-header.eager-loading-startup-enabled by default

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
This PR introduces an experimental CLI flag `-ingester.return-grpc-errors-only` that, when set to `true` makes `Ingester.Push()` return errors with gRPC codes only. The default value is `false`, which means that in some cases, `Ingester.Push()` creates gRPC errors with HTTP status codes, by using `dskit`'s `httpgrpc` package. This corresponds to the semantics of `Ingester.Push()` before this PR, i.e., by default the present PR does not change the semantics of `Ingester.Push()`. At the bottom of this PR description there is a table showing how all possible errors encountered during `Ingester.Push()` are returned to the caller depending on the `-ingester.return-grpc-errors-only` value.
Additionally, the push handler and `Distributor.Push()` have been updated to handle both versions of the …
> Make Ingester.Push() return pure gRPC errors

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/opentracing-contrib/go-grpc/client.go
- vendor/modules.txt
This PR fixes an issue where traces for server streaming gRPC calls sometimes incorrectly show the call as failing due to context cancellation.
This issue is caused by the race condition described in https://github.com/opentracing-contrib/go-grpc/pull/16. 
This PR switches Mimir to use a fork of opentracing-contrib/go-grpc until the PR above is merged.
(none)
> Fix issue where traces for server streaming gRPC calls incorrectly show the call as failing due to context cancellation

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/api/api.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/mimir/grpc_push_check.go
- pkg/mimir/grpc_push_check_test.go
- pkg/mimir/modules.go
This PR implements inflight checks in Distributor by using gRPC method limiter introduced in https://github.com/grafana/dskit/pull/377. This PR relies on unmerged dskit PR https://github.com/grafana/dskit/pull/392 (waiting for new gRPC-go release).
This PR also relies on clients passing the correct metadata headers for httpgrpc requests (using methods introduced in https://github.com/grafana/dskit/pull/391).
To be rebased on top of https://github.com/grafana/mimir/pull/6301, after it's merged.
> distributor: do inflight checks before reading request (for httpgrpc requests)

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/promql/engine.go
- vendor/github.com/prometheus/prometheus/promql/functions.go
- vendor/github.com/prometheus/prometheus/util/annotations/annotations.go
- vendor/modules.txt
Backports https://github.com/prometheus/prometheus/pull/13012 to r261.
N/A
> Backport to r261: https://github.com/prometheus/prometheus/pull/13012

- pkg/distributor/distributor_test.go
- pkg/distributor/push_test.go
This PR fixes a small bug that was found in `distributor_test`. Moreover, it verifies that the gRPC errors with code `codes.DeadlineExceeded` coming from the ingester are correctly translated by the distributor and the push_handler.
> Improve distributor_test

- pkg/distributor/distributor_test.go
This PR improves `distributor.TestStartFinishRequest` a bit, to check for inflight bytes and size during request execution. This is to make sure that proper values are tracked during the request.
This is enhancement of #6300.
> Improve distributor's TestStartFinishRequest test.

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/modules.txt
Patch r258 with `tsdb.PostingsForMatchersCache` [cache poisoning fix](https://github.com/grafana/mimir-prometheus/pull/546). Backport of https://github.com/grafana/mimir/pull/6446.
> Patch r258 with PostingsForMatchersCache fix

- operations/mimir/autoscaling.libsonnet
Change the parameter name for autoscaling configuration to match other parameters.
N/A
> Change scaleDownPeriod to scale_down_period in autoscaling jsonnet

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This PR makes distributor to pass size of WriteRequest in gRPC request metadata. That allows ingester to check for the size before reading request into memory.
Changelog will be added after implementing request size check on ingesters. (https://github.com/grafana/mimir/pull/6492)
> distributor: pass write request size via metadata

- CHANGELOG.md
- integration/ingester_test.go
- pkg/distributor/distributor.go
- pkg/distributor/query.go
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/util/grpc.go
This PR fixes multiple related issues:
* It fixes the issue where query requests that stream chunks but return no series are reported as cancelled rather than successful in traces and metrics reported by queriers ([77c191d](https://github.com/grafana/mimir/pull/6471/commits/77c191da45439fee37f77deaf8611c3e117ed86d))
* It also fixes a similar issue as above for other server streaming gRPC calls ([ae15605](https://github.com/grafana/mimir/pull/6471/commits/ae15605d94ad5c747c4590c7acdf5d1be50bf189))
* It fixes the issue where query requests that stream chunks and have some series are reported as cancelled ([5f6d927](https://github.com/grafana/mimir/pull/6471/commits/5f6d927ca20292103d07606cace8a41e623a30e3) for streaming from ingesters, …
> Fix issue where successful streaming gRPC requests are incorrectly reported as cancelled

- pkg/frontend/querymiddleware/generic_query_cache.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
- pkg/frontend/v2/frontend.go
- pkg/ingester/ingester.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/distributor_queryable.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/querier/tenantfederation/merge_metadata.go
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/indexcache/tracing.go
- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_refs.go
> Use more efficient spanlog.DebugLog in more places

- .golangci.yml
- CHANGELOG.md
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/blocks_store_queryable.go
- pkg/scheduler/scheduler_test.go
- pkg/util/grpc.go
- pkg/util/grpc_test.go
This PR addresses some feedback from #6471:
* it fixes further instances of misspelling "gRPC": [98e1719](https://github.com/grafana/mimir/pull/6505/commits/98e17197d0fa5b3c5b871a045f7dea6bd005eff3)
* it replaces further instances of the inefficient `level.Debug(spanLogger).Log(...)` pattern with `spanLogger.DebugLog(...)`: [c3c1437](https://github.com/grafana/mimir/pull/6505/commits/c3c14376b657b948eb53801725b38dd9b362947f)
* it adds a linting rule to forbid the direct use of `CloseSend()` on client streaming gRPC streams: [f04bb75](https://github.com/grafana/mimir/pull/6505/commits/f04bb7564ee623160f38099cf01751f97c0e5be6)
* it addresses the potential issue identified in https://github.com/grafana/mimir/pull/6471#issuecomment-1784316281:
* it cancels all outstanding store-gateways calls …
> Address post-merge feedback for #6471

- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues.go
fixes mistake in 0446fab466cff4cd8f1ea69177ad825cc2cef844 where the item placed in the queue was a `queue.requestToEnqueue.req`, which is interface type `queue.Request` masking concrete type `*scheduler.schedulerRequest`.
Then when dequeuing, we received `queue.Request`. If the `queue.Request` failed to be sent to a dispatcher, we would re-enqueue it at the front. But the cast to `queue.requestToEnqueue` would fail, as the we only had the inner type `queue.Request`, not the larger `queue.requestToEnqueue`.
this caused panic message:
```
panic: interface conversion: queue.Request is *scheduler.schedulerRequest, not queue.requestToEnqueue
goroutine 1886 [running]:
github.com/grafana/mimir/pkg/scheduler/queue.(*RequestQueue).tryDispatchRequestToQuerier(0xc001ea8c00, 0xc0022c1ec0, …
```
> fix interface conversion mismatch in query-scheduler

- renovate.json
Make Renovate ignore @charleskorn's opentracing-contrib/go-grpc fork, since it should be pinned until further notice.
> Renovate: Ignore opentracing-contrib/go-grpc fork

- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues.go
* fix interface conversion mismatch in query-scheduler
* adding test case for re-enqueueing after disconnected querier
> r262 backport enqueue after dequeue interface conversion fix

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/storage/buffer.go
- vendor/modules.txt
Updates mimir-prometheus to https://github.com/grafana/mimir-prometheus/commit/05b95612d This includes the fix for the ring buffer https://github.com/grafana/mimir-prometheus/commit/4696b46dd (https://github.com/prometheus/prometheus/commit/4696b46dd) cherry-picked on top of the currently used mimir-prometheus revision https://github.com/grafana/mimir-prometheus/commit/c2072c06b346. The cherry-pick in mimir-prometheus is safe because the bug had been in prometheus for 6 months now.
> r261: Update mimir-prometheus to 05b95612d

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
Upgrade build image to latest Node.js LTS, v20. We are currently on v14, which is deprecated and produces a huge warning while building the image.
> mimir-build-image: Upgrade to Node.js 20

- CHANGELOG.md
- docs/sources/mimir/send/native-histograms/_index.md
Add references to Prometheus issue in source for tracking. Add note about "le" and "quantile" label impact, but don't copy the whole text from Prometheus, we should link to the documentation.
Fixes N/A
> Update native histograms Send documentation

- .github/workflows/push-mimir-build-image.yml
In long term, we should check whether the workflow is initiated by a member, rather than solely confirming the author's membership status.
This modification is necessary in scenarios where an external contributor submits a PR to modify the mimir-build-image, even if the PR receives approval from a maintainer, the build image will not update automatically. In such instances, we would be required to either manually update the build image or have a member initiate the PR to ensure the update occurs.
To avoid this, we could check whether the workflow is triggered by a member, in order to able to  start the workflow manually
> Chore: Make only member of team able to run build image workflow

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/ingester/ingester.go
This reverts commit f737a96441f0dc76543e69f1eab0c5b2173ba596.
Since we [no longer need](https://github.com/grafana/mimir/pull/6408#issuecomment-1780796073) the experimental `-ingester.chunks-query-ignore-cancellation` flag (it was only necessary during an investigation, where we have found and fixed the root cause), it's time to remove it.
I'm keeping the part of the PR adding error wrapping, these are an improvement independently of the flag in question.
> Revert "Ingester.QueryStream: Add support for ignoring context cancellation for chunk queriers (#6408)"

- CHANGELOG.md
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
Scheduler processor (part of Querier) is creating gRPC client to frontend, to send result back, and it needs to use gRPC client settings for query-frontend.
Bug was introduced in https://github.com/grafana/mimir/pull/6445.
> Fix bug in scheduler processor

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR adds requests rejected by distributor to Mimir / Writes dashboard. This is useful in combination with `-distributor.limit-inflight-requests-using-grpc-method-limiter` option (#6300). Without this change, requests rejected by grpc method limiter would not be visible in the dashboards.
This is similar to https://github.com/grafana/mimir/pull/6132, but for distributor.
Before this PR:
After this PR:
Related to #6300.
> Show rejected distributor requests in the dashboard.

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/jsonnetfile.lock.json
This PR updates vendored `jsonnet-libs/grafana-builder` to revision cbcc611. The latter allows all Mimir dashboards to report gRPC codes as `status_code`s. 
**Note:** The biggest change introduced by this PR is that if a component starts producing responses with gRPC codes only, successful **`status_code`** labels of the corresponding server and gRPC client request duration metrics **will change from** respectively **`success` and `2xx` to `OK`**.
Part of https://github.com/grafana/mimir/issues/6008
> Allow dashboards to show gRPC codes as labels

- CHANGELOG.md
- pkg/ingester/ingester.go
This PR reverts "Check for errors when iterating through chunks or samples in response to a query (#6451)".
We think that combination of #6451 and #6469 introduced a bug, where queries executing during head compaction could fail with error when series is removed.
> Revert PR #6451

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/storage/merge.go
- vendor/modules.txt
For https://github.com/grafana/mimir-prometheus/pull/562
revert of https://github.com/grafana/mimir-prometheus/pull/549
Ref: #incident-2023-11-06-cortex-ops-01-block-to-the-future
> Vendor update mimir-prometheus at 237a77b48340

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/storage/merge.go
- vendor/modules.txt
For https://github.com/grafana/mimir-prometheus/pull/562 revert of https://github.com/grafana/mimir-prometheus/pull/549
Ref: #incident-2023-11-06-cortex-ops-01-block-to-the-future
(cherry picked from commit 4987dd5cda16668c0829e829b56ac82726004586)
> [backport r262] Vendor update mimir-prometheus (#6579)

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/storage/merge.go
- vendor/modules.txt
For https://github.com/grafana/mimir-prometheus/pull/562
revert of https://github.com/grafana/mimir-prometheus/pull/549
Ref: #incident-2023-11-06-cortex-ops-01-block-to-the-future
Backport of #6579 
(cherry picked from commit 4987dd5cda16668c0829e829b56ac82726004586)
> [backport r263] Vendor update mimir-prometheus (#6579)

- pkg/storegateway/bucket.go
This PR adds a trace span for loading the index reader during store-gateway requests. 
This is useful for diagnosing why store-gateway queries take longer than expected.
(none)
> Add trace span for time taken to load index reader for each block.

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
This PR replaces the MimirGossipMembersMismatch with two new warnings intended to be more reliable.
I will leave this PR as a draft until we've tested these changes at Grafana Labs.
(none)
> Improve signal-to-noise ratio of MimirGossipMembersMismatch warning by replacing it with two new warnings

- CHANGELOG.md
- pkg/distributor/query.go
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/distributor_queryable_streaming_test.go
This PR fixes an issue where queries can fail with an unhelpful error message like `canceled: attempted to read series at index 0 from ingester chunks stream, but the stream has failed: context canceled`.
This occurs when streaming chunks is enabled and the ingester or store-gateway connection is closed and removed from the pool when the ingester or store-gateway fails its healthcheck. 
With the fix in this PR, queries will still fail in this scenario, but they'll fail with a slightly more descriptive error message (`grpc: the client connection is closing`). There does not seem to be an easy way to include a clearer error message here without complicating the code further.
When that happens, the querier closes the connection for the ingester or store-gateway …
> Fix issue where queries fail with "context canceled" when ingester or store-gateway fails healthcheck

- pkg/distributor/distributor.go
This simple PR improves error status code extraction in `distributor.handleIngesterPushError()`.
In the previous implementation, we were checking:
- if error can be recognized by `httpgrpc.HTTPResponseFromError()` (which internally calls `status.FromError()`), and if not
- if error can be recognized by `status.FromError()`.
Hence, in some cases we were indirectly calling `status.FromError()` twice. This can be optimized by calling `dskit`'s `grpcutil.StatusFromError()` only once.
Part of #6008
> Distributor: improve extracting status code from ingester.Push() errors

- development/mimir-monolithic-mode/config/grafana-agent.river
- development/mimir-monolithic-mode/config/mimir.yaml
- development/mimir-monolithic-mode/docker-compose.yml
Enable sending exemplars from the Agent
Enable receiving exemplars in Mimir
Fix command line option for agent flow
> development: update grafana agent flow setup

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/queries.libsonnet
- operations/mimir-mixin/dashboards/ruler.libsonnet
- pkg/querier/blocks_consistency_checker.go
- pkg/querier/blocks_consistency_checker_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
Consistency checks are currently tracked per attempt. For example, this means that if there were two attempts to fetch some blocks and the first was partially siccessful and the second fetched the missing blocks, then the ratio of failed checks will be 50%. This is misleading because the second check succeeded and the query overall was successful. We graph this ratio in Mimir / Queries.
with this change I took the chance to refactor the consistency checker. One side effect of this change is that the upload and deletion marker grace periods will not be recalculated upon each retry. This means that if a request to the store-gateway takes long enough for a block to fall outside of the uploadGracePeriod, then that block won't be queried. The time between query-ingesters-within and …
> querier: track consistency check failures without retries

- CHANGELOG.md
- pkg/ingester/active_series.go
Turns out recomputing the response size over and over again is not such a great idea, who would have thought...
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/mimir/pkg/ingester
│   main.txt    │             branch.txt             │
│    sec/op     │   sec/op     vs base               │
Ingester_ActiveSeries/few_series-10         2.835µ ± 1%   2.428µ ± 1%  -14.36% (p=0.002 n=6)
Ingester_ActiveSeries/~10%_of_series-10   87320.9µ ± 0%   707.6µ ± 2%  -99.19% (p=0.002 n=6)
geomean                                     497.5µ        41.45µ       -91.67%
```
Follow up to #6536.
> /active_series: do not recompute response size

- CHANGELOG.md
- pkg/mimir/tracing.go
- pkg/mimir/tracing_test.go
I found that there's a bug in `OpenTelemetryTracerBridge.Start`, i.e. that the returned context doesn't contain a `go.opentelemetry.io/otel/trace.Span` although it should. This PR fixes it, and adds a test for it.
The practical effect of the bug is losing OpenTelemetry tracing events, e.g. in Prometheus, where code depends on fetching a span from the context (if no span is in the context, these events are discarded).
> OpenTelemetryTracerBridge.Start: Make returned context contain span

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
Increase the amount of time that distributors are scaled down over from 60 seconds to 600 seconds. This helps avoid scaling down too quickly when distributors are using less CPU than normal (such as when they are circuit breaking or load shedding).
N/A
> Increase scale down period for distributors

- CHANGELOG.md
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues.go
- pkg/scheduler/queue/tenant_queues_test.go
- pkg/scheduler/queue/tree_queue.go
- pkg/scheduler/queue/tree_queue_test.go
This PR introduces the recursive, multi-dimensional TreeQueue data structure for the query scheduler queue.
Previously introduced in Loki, this tree structure allows for fair round-robin dequeuing from arbitrarily-nested queue dimensions.
In this PR, we do _not_ implement the planned two-dimensional queuing, where we will queue requests by (tenant, query component) where query component is ingester, store-gateway, or both.
For now we just are doing a lift and shift from the existing data structure (just a mapping of tenant ID to a linked list queue) to an equivalent single-dimensional queue using a TreeQueue of depth 1, where the single queueing dimension. is still just the tenant ID
Subsequent PRs will introduce the second queueing dimension based on which components the query will hit. …
> query-scheduler multi dimension queueing data structures

- pkg/ingester/ingester_test.go
The tests make it seem like you need two write requests to ingest
an exemplar: one to create the series with a sample and one to
append the exemplar. Actually a single write request is enough, but
the content needs to be in order of sample and then exemplar.
Two new test cases added:
- single write request where there is a timeseries that has both a
sample and an exemplar in the same timeseries.
- single write request where there are two timeseries with the first
having a sample and the second the exemplar.
Currently Prometheus and Grafana Agent use the second form to send
exemplars, which is a bit wasteful.
Also added native histogram version of the tests.
Related to: https://github.com/prometheus/prometheus/pull/13113
- N/A `CHANGELOG.md` updated - the order of …
> Update ingester unit tests related to exemplars vs samples

- pkg/distributor/distributor_test.go
- pkg/distributor/query_test.go
Instead of adding more and more config fields to prepConfig, we now can pass a `configure(*Config)` function instead, that would set the desired fields.
This will make another PR I'm working on easier to review.
> Refactor distributor test preparation

- pkg/storage/chunk/json_helpers.go
Prometheus added one in https://github.com/prometheus/prometheus/pull/12598; we don't need to have one in Mimir now.
> Remove second implementation of Labels jsoniter encoder

- pkg/frontend/querymiddleware/codec_test.go
This PR fixes the `BenchmarkPrometheusCodec_DecodeResponse` benchmark: it currently fails with a `unknown response content type ''` error.
This was likely broken in #4153.
(none)
> Fix broken `BenchmarkPrometheusCodec_DecodeResponse` benchmark

- CHANGELOG.md
- pkg/mimirtool/analyze/grafana.go
Grafana support several Global variables but also allow users to define an `interval` templated variable. When using mimirtool on such case we might have the following error:
```
"query=histogram_quantile(0.70, sum by (le) (rate(rpc_server_duration_milliseconds_bucket{rpc_method=~\"$gRPC_method\", job=\"$job\"}[$rate_interval]))): 1:124: parse error: missing unit character in duration",
```
This commit add support for more user define variables matching the global ones.
See: https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#global-variables
We have the following global variables that are out of the scope of dashboards analysis:
* $__dashboard
* $__from and $__to
* $__name
* $__org
* $__user
* $timeFilter or $__timeFilter
* $__timezone
However those are …
> Support $rate_interval when parsing Query during dashboards analysis

- CHANGELOG.md
- pkg/util/limiter/utilization.go
- pkg/util/limiter/utilization_test.go
Modify the utilization based ingester read path limiter to base memory utilization on Go heap size instead of RSS from /proc/self/ (Linux procfs). The motivation is that we have experienced significant practical divergence between procfs and cAdvisor (container) memory measurements, and after a design discussion we've arrived at trying to track the Go heap size instead for simplicity.
> Ingester: Base memory utilization on Go heap size

- CHANGELOG.md
- pkg/frontend/transport/handler.go
This PR improves the error returned by query-frontends when they receive a query request while shutting down.
In particular, the error message is now clearer, and the HTTP status code will be 503 (service unavailable) rather than 500.
(none)
> Return a clearer message when a query-frontend receives a request after it has stopped, and return HTTP 503 rather than 500

- docs/sources/mimir/tutorials/play-with-grafana-mimir/index.md
Fix https://github.com/grafana/mimir/issues/5789 in the `2.9.x` release.
> Docs: Fix broken link and align text

- pkg/storegateway/bucket_test.go
- pkg/storegateway/postings_codec_test.go
- pkg/storegateway/prometheus_test.go
- pkg/storegateway/series_refs_test.go
See individual commits for more details.
* disable tsdb transaction isolation 
* commit appender periodically 
* reduce overhad from testify 
* re-use details when creating test block 
Before:
```
go test -count=1 -timeout=90s -run TestLoadingSeriesChunkRefsSetIterator ./pkg/storegateway/ 
ok      github.com/grafana/mimir/pkg/storegateway       28.387s
```
After:
```
go test -count=1 -timeout=90s -run TestLoadingSeriesChunkRefsSetIterator ./pkg/storegateway/ 
ok      github.com/grafana/mimir/pkg/storegateway       9.119s
```
> Speed up some store-gateway tests

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- integration/backward_compatibility_test.go
- integration/configs.go
- integration/getting_started_with_gossiped_ring_test.go
- integration/ingester_limits_test.go
- integration/querier_test.go
- integration/ruler_test.go
- operations/compare-helm-with-jsonnet/components/config/kustomization.yaml
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- pkg/mimir/mimir_test.go
- pkg/mimir/modules.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/gateway_test.go
In preparation for release 2.11, this PR performs the scheduled removals of the following deprecated configuration parameters:
* `-querier.query-ingesters-within`
* `-querier.iterators`
* `-querier.batch-iterators`
* `-blocks-storage.bucket-store.max-chunk-pool-bytes`
* `-blocks-storage.bucket-store.chunk-pool-min-bucket-size-bytes`
* `-blocks-storage.bucket-store.chunk-pool-max-bucket-size-bytes`
* `-blocks-storage.bucket-store.bucket-index.enabled`
I've separated each deprecation removal into its own commit so it might be easiest to review this PR one commit at a time.
> Remove deprecated configurations

- go.mod
- go.sum
- pkg/alertmanager/alertmanager.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/alert_group.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/alert_groups.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/alertmanager_status.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/cluster_status.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/gettable_alert.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/gettable_alerts.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/gettable_silence.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/gettable_silences.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/matchers.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/postable_alert.go
- vendor/github.com/prometheus/alertmanager/api/v2/models/postable_alerts.go
- vendor/github.com/prometheus/alertmanager/api/v2/restapi/operations/alertmanager_api.go
- vendor/github.com/prometheus/alertmanager/config/config.go
- vendor/github.com/prometheus/alertmanager/config/notifiers.go
- vendor/github.com/prometheus/alertmanager/dispatch/route.go
- vendor/github.com/prometheus/alertmanager/featurecontrol/featurecontrol.go
- vendor/github.com/prometheus/alertmanager/notify/discord/discord.go
- vendor/github.com/prometheus/alertmanager/notify/notify.go
- vendor/github.com/prometheus/alertmanager/notify/pushover/pushover.go
- vendor/github.com/prometheus/alertmanager/pkg/labels/matcher.go
- vendor/github.com/prometheus/alertmanager/timeinterval/timeinterval.go
- vendor/github.com/prometheus/alertmanager/types/types.go
- vendor/github.com/prometheus/alertmanager/ui/web.go
- vendor/github.com/rs/cors/README.md
- vendor/github.com/rs/cors/cors.go
- vendor/github.com/rs/cors/utils.go
- vendor/modules.txt
Upgrades the vendoring of Alertmanager to the latest tip of main.
n/a
> Update Alertmanager vendor

- docs/sources/mimir/set-up/migrate/migrate-from-thanos-or-prometheus.md
Fix #5663.
The current numbers were not rendering properly, nor did they follow the markup syntax at https://grafana.com/docs/writers-toolkit/write/markdown-guide/#numbered-lists.
The fix uses the correct syntax, and this builds fine locally.
> Doc: Align with Writers’ Toolkit wrt numbering

- pkg/scheduler/queue/queue.go
This PR adds logging for a scenario that should never happen, but if it were to happen, query-schedulers would silently drop queries.
(none)
> Warn if query-scheduler queue contains requests while shutting down

- CHANGELOG.md
- pkg/ingester/client/streaming.go
- pkg/querier/block_streaming.go
- pkg/querier/worker/scheduler_processor.go
- pkg/util/cancellation.go
- pkg/util/cancellation_test.go
This PR improves the errors returned from chunks streaming when the query context is cancelled.
When the query is cancelled, the querier cancels the context used for the query. This is frequently reported as `attempted to read series at index xxx from ingester chunks stream, but the stream has failed: context canceled`, which makes it sound like an issue with streaming chunks. 
In reality, the issue is often that the context was cancelled due because the caller cancelled the query, so this PR makes that clearer.
This change is imperfect: the clearer error message will only be returned if the code that first observes the `context.Canceled` error inspects the context with `context.Cause(ctx)`. This is now true for the chunks streaming code, but there's no guarantee the chunks streaming code …
> Include more information in "context canceled" errors returned from chunks streaming

- CHANGELOG.md
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
This PR fixes an issue where queriers can fail to send query results to query-frontends if the query is cancelled for some reason. This manifests as query-frontends timing out waiting for query results.
This can happen in two scenarios:
* the query-scheduler dies or the query-frontend cancels the query, causing the gRPC stream between the querier and the query-scheduler to be closed and triggering cancellation of the query
* there's a race between when the querier cancels the contexts for processors for schedulers that are shutting down [here](https://github.com/grafana/mimir/blob/14e4b3eea2c67a44da1d8aa90c53d12299006398/pkg/querier/worker/processor_manager.go#L87-L90) and when the querier cancels the execution context created in `newExecutionContext` …
> Always report query result to query-frontend, even when cancelled

- CHANGELOG.md
- pkg/querier/worker/frontend_processor.go
When a query returns an error value, check whether that error is actually a cancellation before acting.
I expect two effects: the worker won't log "context canceled", and it will process the next request immediately.
Could be the user closed the tab, or it's a sharded query and some other shard errored. Whatever the cause, cancellation is not an error.
> Query-frontend worker: don't treat cancel as an error

- pkg/distributor/otel_test.go
- pkg/distributor/push_test.go
Add benchmarks for `distributor.OTLPHandler`. Also fixing an issue in the tests, which is that verifier functions currently don't take the sub-test's `testing.T` argument, but instead the parent's. This becomes obvious when verifier functions fail, as the test runtime complains. Also use `require.NoError` instead of `assert.NoError` to avoid panics on unexpected errors.
> Distributor: Add OTLP handler benchmarks

- pkg/querier/worker/scheduler_processor.go
The querier will try sending a query's response to a frontend. If the sending fails, then the querier will remove the connection from the pool and immediately try to establish a new one.
When there are multiple queries, then the can remove each other's new connections which leads to a live lock until the retries expire. One reason why the sending can fail is that the client was cleaned up
* make retrying less aggressive to make livelocks less likely, but also to give time to whatever was causing to error to recover
* don't remove the query-frontend connection from the pool; if the connection is indeed faulty, then the [client pool](https://github.com/grafana/mimir/blob/c4c33cfa5dee26772bb5934b9e8365db40800893/pkg/querier/worker/scheduler_processor.go#L72) will clean it up ([within 6 …
> querier: backoff retrying to send responses to query-frontend

- docs/sources/mimir/visualize/native-histograms/_index.md
@krajorama, the term "previous" can indeed be removed per @beorn7.
> Docs: Remove "previous" from Classic histograms because they are still in existance

- CHANGELOG.md
- pkg/distributor/query.go
This PR fixes an issue introduced in https://github.com/grafana/mimir/pull/5342.
We shouldn't consider `PENDING` ingesters as unhealthy: in the case where new ingesters have just started due to a scale-up, we'll consider each zone with a `PENDING` ingester as unhealthy, and so if two zones have just scaled up and have `PENDING` ingesters, the query will fail.
Furthermore, we should attempt to query ingesters in the `PENDING` state: in the case where an ingester has just started, queriers may have only observed the ingester in the `PENDING` state, but distributors may have observed the ingester in the `ACTIVE` state and started sending samples, for example:
- New ingester in zone A starts, publishes `PENDING` state to ring
- Querier observes new ingester in `PENDING` state
- New ingester …
> Query ingesters in PENDING state

- CHANGELOG.md
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
This PR fixes the issue where a querier will cancel all inflight queries from a query-scheduler if the querier <-> query-scheduler stream is broken. 
This can happen if there is a networking issue, or the query-scheduler crashes.
This PR does not introduce any compatibility issues:
* a querier without the changes here talking to a query-scheduler with the changes here will behave as before: it'll cancel an inflight query when the query-scheduler cancels a query or the stream is otherwise broken
* a querier with the changes here talking to a query-scheduler without the changes here will behave as desired: it'll cancel an inflight query when the query-scheduler cancels a query, and not cancel an inflight query if the stream is otherwise broken
Addresses …
> Fix issue where querier cancels all inflight queries from a scheduler if the querier / scheduler stream is broken

- CHANGELOG.md
- docs/sources/mimir/send/native-histograms/_index.md
Due to https://github.com/grafana/agent/pull/5750
> docs: bump required agent version

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/references/configuration-parameters/index.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/rate_strategy.go
- pkg/distributor/rate_strategy_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/user_limits_handler.go
This PR is to add `distributor.ingestion-burst-factor`, when set it will override the `distributor.ingestion-burst-size`. When `distributor.ingestion-burst-factor` is set the burst size on the underlying token bucket for the ingest rate limiter to a multiple of the maximum ingestion rate a distributor can handle. This is to simplify setting the burst size to a multiple of the global rate limit. 
> Add option `distributor.ingestion-burst-factor`

- pkg/mimir/mimir.go
- pkg/mimir/mimir_test.go
- pkg/mimir/modules.go
This is small internal refactoring that renames field, init method and module name from "ring" to "ingester ring", since we now have many other rings too.
Fixes comment https://github.com/grafana/mimir/pull/6718#discussion_r1404103464.
> Rename "ring" to "ingester ring"

- CHANGELOG.md
- pkg/frontend/querymiddleware/split_and_cache.go
Add debug message to track tenants sending queries that are not able to benefit from caches.
The alternative would be to add a label `user` on `cortex_frontend_query_result_cache_skipped_total` metric but this could have a significant impact on cardinality.
N/A
> Add debug message to track tenants sending queries that are not able to benefit from caches.

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/bucket_store_metrics.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/stats.go
* don't double count streamingSeriesOtherDuration and streamingSeriesFetchSeriesAndChunksDuration when using querier<>store-gateway streaming
* replace streamingSeriesFetchSeriesAndChunksDuration with streamingSeriesWaitBatchLoadedDuration and only record it once
* remove cortex_bucket_store_series_refs_fetch_duration_seconds because it is tracking the time per block, not per request and isn't directly useful in diagnosing slow store-gateway requests; it is also not used in dashboards
* record send/encode duration for sending stats
* record send/encode duration even if sending/encoding fails
* calculate "other" time based on the total time of the request (for example now it includes reading the bucket index, waiting for the query gate)
> store-gateway: fix duration metrics

- docs/sources/mimir/release-notes/v2.11.md
This PR adds release notes for Mimir 2.11.0.
> Draft release notes for 2.11

- CHANGELOG.md
- pkg/continuoustest/util.go
- pkg/continuoustest/util_test.go
This PR improves the output of continuous-test when a query returns unexpected results. If a float sample does not match the expected value, continuous-test will now include a dump of all expected and received values, to aid in debugging failures.
One downside of this change is that failure messages could potentially become huge. The default value for `-tests.write-read-series-test.max-query-age` is 7 days, and continuous-test will select a random query time range that selects anywhere up to everything from now until that value. If this happens, and the test fails, continuous-test will write an error with 30,240 samples (7 days' samples with a 20s step). Given this should be a rare situation, and failures should be a rare occurrence, and debugging failures is otherwise difficult, I think …
> continuous-test: Include comparison of all expected and actual values when any float sample does not match

- operations/mimir/distributor.libsonnet
Following up https://github.com/grafana/mimir/pull/6774, I just realised it would be easier if I would also have `newDistributorContainer()` utility, so I'm adding it in this PR.
N/A
> Jsonnet: add newDistributorContainer() utility

- pkg/mimirtool/commands/analyse_dashboards.go
Synchonizes behavior output between `analyze dashboard` and `analyze grafana`.
The `analyze dashboard` command did not populate the `metricsUsed` field with metrics discovered from local dashboards. The `analyze grafana`, however, did that. After looking at the code, it seems it was only missing the copy metrics to the `metricsUsed` fields.
Originally implemented in #6653
> feat/add discovered metrics to metricsUsed

- CHANGELOG.md
- pkg/ingester/ingester.go
Now that https://github.com/grafana/mimir/pull/6766 has been merged with https://github.com/prometheus/prometheus/pull/13115, we can reinstate https://github.com/grafana/mimir/pull/6451. 
This was originally reverted in https://github.com/grafana/mimir/pull/6576.
> Un-revert #6451

- CHANGELOG.md
- operations/mimir-tests/test-node-selector-and-affinity-generated.yaml
- operations/mimir-tests/test-node-selector-and-affinity.jsonnet
- operations/mimir/distributor.libsonnet
As part of my on-going work to deploy distributors in multi-AZ, I need an easy way to configure node affinity rules. In this PR I'm proposing to add `distributor_node_affinity_matchers` so that different jsonnet files can append to it, and then the matchers are materialised by `newDistributorDeployment()`.
_In this PR I'm doing it only for distributors, but if experiment will be successful we can do it for all components._
The test I've added can be compared against `test-defaults-generated.yaml`:
```
$ diff operations/mimir-tests/test-defaults-generated.yaml operations/mimir-tests/test-node-selector-and-affinity-generated.yaml
434a435,448
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>             - …
```
> Jsonnet: add distributor_node_affinity_matchers setting support

- pkg/querier/worker/frontend_processor.go
This line was removed in #4648; I can only think it was due to a bad merge or similar.
Removing `continue` would mean we always reset the backoff after an error.
Note this file is only used if you are not using the query-frontend sheduler.
> Query-frontend worker: put back 'continue' removed in error

- CHANGELOG.md
- integration/ruler_test.go
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
We have a counter metric that tracks rules with zero fetched series. This PR excludes queries that are just `vector(number)` from being counted in there, as those are not expected to fetch any series and are not an indication of late data that may affect the rules.
Follow up to https://github.com/grafana/mimir/pull/5925
> Exclude vector queries from being counted in metric for rules with zero fetched series

- CHANGELOG.md
- pkg/ruler/remotequerier.go
This PR fixes an issue where the "failed to remotely evaluate query expression, will retry" message is logged without context such as the trace ID. This also fixes the issue where these messages are not recorded as trace events.
(none)
> Fix issue where failed remote rule evaluation errors are logged without context such as trace IDs

- operations/helm/scripts/build.sh
I tried to run `make BUILD_IN_CONTAINER=false build-helm-tests` because it's faster than running in the build image, but it failed on my machine because I'm using zsh instead of bash and `$BASHPID` is not defined (`set -u` at the beginning of the `build.sh` script causes to abort the script if it finds an usage of a non initialized variable). Googling it,[ I've found out here](https://unix.stackexchange.com/questions/484442/how-can-i-get-the-pid-of-a-subshell) that there may be an easy way to get the PID in a portable way, so I'm replacing it. This change fix it on my machine.
N/A
> Fix helm build script when running out of build-image in a non-bash shell

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/config.libsonnet
In this PR I'm proposing to extend the `job` label matchers used to match distributor and gateway, to include multi-zone deployments too. For the gateway, previously we were matching `cortex-gw|cortex-gw-internal`: in this PR I've simply changed it to `cortex-gw.*`.
This PR change is similar to the changes we already did to ingester and store-gateway job matchers, to match multi-zone deployments.
N/A
> Mixin: extend distributor and gateway job label matchers to include multi-zone deployments

- pkg/distributor/distributor_test.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/mimirpb/compat.go
Move util to format LabelAdaptor string to mimirpb package 
And call it from more places.
Note that some error strings change, because the metric name is pulled
to the front, e.g. `test{foo="bar"}` instead of `{__name__="test",foo="bar"}`.
- NA [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Move util to format LabelAdaptor string to mimirpb package 

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
Two PRs each removed parts of the code, but when they were both merged we need to also remove declarations that are no longer needed.
> fix up bad merge giving compile errors

- pkg/mimirtool/commands/alerts.go
- pkg/mimirtool/commands/analyse.go
- pkg/mimirtool/commands/backfill.go
- pkg/mimirtool/commands/remote_read.go
- pkg/mimirtool/commands/rules.go
we should probably unify them at some point because i just realized what a mess they are
> mimirtool: clarify what auth flags do

- pkg/ruler/api.go
Start a new span and use spanlogger for Ruler API calls.
N/A
- [NA] Tests updated.
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [NA] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Use spanlogger for Ruler API calls

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
Add a row in tenant dashboard to show informations about alertmanager activity
None
> [dashboards] Add panels for alertmanager activity of a tenant

- CHANGELOG.md
- operations/mimir-tests/test-node-selector-and-affinity-generated.yaml
- operations/mimir-tests/test-node-selector-and-affinity.jsonnet
- operations/mimir/alertmanager.libsonnet
- operations/mimir/common.libsonnet
- operations/mimir/compactor.libsonnet
- operations/mimir/continuous-test.libsonnet
- operations/mimir/distributor.libsonnet
- operations/mimir/ingester.libsonnet
- operations/mimir/multi-zone.libsonnet
- operations/mimir/overrides-exporter.libsonnet
- operations/mimir/querier.libsonnet
- operations/mimir/query-frontend.libsonnet
- operations/mimir/query-scheduler.libsonnet
- operations/mimir/read-write-deployment/backend.libsonnet
- operations/mimir/read-write-deployment/read.libsonnet
- operations/mimir/read-write-deployment/write.libsonnet
- operations/mimir/ruler-remote-evaluation.libsonnet
- operations/mimir/ruler.libsonnet
- operations/mimir/store-gateway.libsonnet
This PR is a follow up of #6782. In #6782 I've introduced `distributor_node_affinity_matchers` and successfully use it at Grafana Labs to simplify the jsonnet setup. In this PR I'm doing the same for every other Mimir component.
N/A
> Jsonnet: add node_affinity_matchers setting support for every Mimir component

- operations/mimir/ingester.libsonnet
- operations/mimir/multi-zone.libsonnet
- operations/mimir/store-gateway.libsonnet
This PR addresses a [comment received here](https://github.com/grafana/mimir/pull/6829#discussion_r1415911977), suggesting to rename `with_anti_affinity` to `withAntiAffinity`.
N/A
> Jsonnet: rename with_anti_affinity to withAntiAffinity

- CHANGELOG.md
- integration/configs.go
- integration/getting_started_with_gossiped_ring_test.go
- integration/read_write_mode_test.go
- integration/single_binary_test.go
- integration/store_gateway_limits_hit_test.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/gateway_test.go
backports https://github.com/grafana/mimir/pull/6808
> [r267] store-gateway: use bucket index instead of scanning the bucket

- docs/sources/mimir/send/native-histograms/_index.md
Native histogram is only supported in flow mode currently; static mode support is coming soon.
I'm sending in this PR based on a recent conversation in the #agent slack channel with @tpaschalis.
> Clarify grafana agent native histogram support

- pkg/frontend/querymiddleware/cardinality_query_cache.go
- pkg/frontend/querymiddleware/cardinality_query_cache_test.go
- pkg/frontend/querymiddleware/cardinality_test.go
- pkg/frontend/querymiddleware/generic_query_cache.go
- pkg/frontend/querymiddleware/generic_query_cache_test.go
- pkg/frontend/querymiddleware/labels_query_cache.go
- pkg/frontend/querymiddleware/labels_query_cache_test.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/results_cache_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
This PR makes it possible for GEM to inject its own cache key generation. This required splitting up the existing `genericQueryDelegate`  into two interfaces
```go
type tenantCacheTTL interface {
// ttl returns the cache TTL for the input userID.
ttl(userID string) time.Duration
}
```
and extending `CacheSplitter` to include LabelValues and Cardinality cache items
```go
// CacheKeyGenerator generates cache keys. This is a useful interface for downstream
// consumers who wish to implement their own strategies.
type CacheKeyGenerator interface {
// QueryRequest should generate a cache key based on the tenant ID and Request.
QueryRequest(ctx context.Context, tenantID string, r Request) string
// LabelValues should return a cache key for a label values request. The cache key does not need to …
```
> query-frontend: inject query cache keys for LabelValues/Cardinality requests

- pkg/frontend/querymiddleware/querysharding_test.go
Adds a unit test from https://github.com/grafana/mimir/pull/6504 to ensure that the results from `histogram_quantile` with and without query sharding have no significant differences. Before the fix in https://github.com/prometheus/prometheus/pull/13153 was vendored in https://github.com/grafana/mimir/pull/6766 , this unit test failed, now it passes.
Context: Mimir had a [bug](https://raintank-corp.slack.com/archives/C9KL8THCY/p1697642615621789) that sometimes occurs when summing (or other aggregation) the classic histogram (separate series per bucket) input into `histogram_quantile`, when query sharding on the input results in reduced precision which is normally insignificant, but may result in non-monotonicity in the histogram buckets.
N/A
> Add unit test to compare histogram_quantile results with and without query sharding

- pkg/ingester/client/streaming.go
Don't output this kind of message , which we tend to get by the hundred: 
```
ts=2023-12-04T11:58:07.821737148Z caller=spanlogger.go:109 method=SeriesChunksStreamReader.StartBuffering user=279486 level=error msg="received error while streaming chunks from ingester" err="context canceled"
```
Don't mark spans as errored either.
- NA [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> ingester client: context canceled is not an error

- CHANGELOG.md
- pkg/storage/tsdb/block/markers.go
- pkg/storegateway/blocks.gohtml
- pkg/storegateway/gateway_blocks_http.go
- pkg/util/listblocks/listblocks.go
- tools/listblocks/main.go
This PR introduces a new filter 'no-compact' in the admin UI for block filtering. Currently, we have various filters available for markers, but this addition extends functionality by enabling the display of blocks marked with 'no-compact'. Subsequent PRs will build upon this enhancement to provide users with the capability to mark blocks directly through the UI instead of CLI.
Test in local, how it looks like on UI
- na Tests updated.
- na Documentation added.
- na [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Store-gateway: Add no-compact column on store-gateway/tenants admin UI

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
We would like to track if there are users who send us samples with timestamps which are in the future, relative to wall clock time. 
This change doesn't need to be permanent, we can revert it in a few weeks from now.
> extend histogram cortex_distributor_sample_delay_seconds_bucket to track negative delays

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin/dashboards/rollout-progress.libsonnet
The Latency vs 24h was the last graph panel we have. Those are deprecated are are going away very soon.
This is how the panel look with the changes in this PR
> Mixin: remove last graph panel

- integration/e2emimir/client.go
This allows to inject more involved HTTP headers for testing proxies in front of Mimir for example.
> e2e mimir client: add ability to inject headers and roundtrippers

- CHANGELOG.md
- docs/sources/mimir/release-notes/v2.11.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/model/labels/regexp.go
- vendor/modules.txt
Sync to the newly created mimir-release-2.11 branch that includes 
https://github.com/grafana/mimir-prometheus/pull/572
https://github.com/grafana/mimir-prometheus/pull/571
> [release-2.11] sync with mimir-prometheus at f51e8aae4265

- .github/workflows/push-mimir-build-image.yml
This PR fixes the issue where backticks are incorrectly escaped in the comment posted on PRs by CI that modify the build image, [for example](https://github.com/grafana/mimir/pull/6868#issuecomment-1849265695):
> **Building new version of mimir-build-image**. After image is built and pushed to Docker Hub,  a new commit will automatically be added to this PR with new image version \`grafana/mimir-build-image:pr6868-e4be452cf9\`. This can take up to 1 hour.
(none)
> Fix formatting of comment posted during build image CI builds

- CHANGELOG.md
- pkg/querier/worker/scheduler_processor.go
This PR fixes #5341: trace spans created by queriers are not nested correctly.
Before this change:
After this change:
Note that the `HTTP GET - prometheus_api_v1_query_range` span is nested under the `querier_processor_runRequest` span.
The duplicate `HTTP GET - prometheus_api_v1_query_range` spans are a separate issue, I suspect this was introduced by https://github.com/grafana/dskit/pull/372.
Resolves #5341
> Fix issue where querier trace spans are not nested correctly

- pkg/util/http.go
- pkg/util/requestbuffers.go
- pkg/util/requestbuffers_test.go
Add some tests for `util.RequestBuffers`. Have to make a new file, since `pkg/util/http_test.go` has its own package and can't access `util` internals.
Also make sure that `bytes.Buffer` pointers in the backing array are nil-ed in `CleanUp`.
> util.RequestBuffers: Add tests

- CHANGELOG.md
- cmd/metaconvert/Dockerfile
- cmd/mimir-continuous-test/Dockerfile
- cmd/mimir/Dockerfile
- cmd/mimirtool/Dockerfile
- cmd/query-tee/Dockerfile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
- development/mimir-monolithic-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
This addresses [CVE-2023-5363](https://nvd.nist.gov/vuln/detail/CVE-2023-5363)
> [2.10] update alpine to 3.18.5

- pkg/storage/ingest/writer.go
I've spent some time testing how the write path behaves when the Kafka-compatible backend has partial or full outages, in particular focusing on the cluster metadata update period. In this PR I'm updating the comment about it with what I learned. TL;DR is that it's good to have a low max age, but we can safely increase the min age to the same value to also get the const load property (default min age is 5s, so I'm proposing to increase it from 5s to 10s).
N/A
> Kafka backend prototype: set metadata min age == max age

- docs/sources/mimir/release-notes/v2.10.md
This adds the release notes for 2.10.1-2.10.4, and adds a missing note for the bugfix in 2.10.5
> Update all release-2.10 release notes

- CHANGELOG.md
- operations/mimir-tests/test-automated-downscale-generated.yaml
- operations/mimir-tests/test-automated-downscale.jsonnet
- operations/mimir/ingester-automated-downscale.libsonnet
- operations/mimir/mimir.libsonnet
Similar to #6149, add the ability to have ingester statefulsets safely scaled down via the rollout-operator. This adds ingester versions of all the store- gateway configuration introduced in #6149.
N/A
- [NA] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> jsonnet: Add ability to have rollout-operator scale down ingesters

- operations/k6/load-testing-with-k6.js
This changes the k6 load testing script to pass authentication for remote writes via headers (same as we do for reads) instead of as part of the URL.
N/A
- [NA] Tests updated.
- [NA] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [NA] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> k6: Pass auth to write path via headers not URL

- operations/k6/load-testing-with-k6.js
This adds a project ID option to the k6 load testing script, so that k6 cloud load tests can be sent to projects other than the default project.
N/A
- N/A [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Add project ID option for k6 cloud tests

- development/mimir-microservices-mode/docker-compose.jsonnet
This PR adds a flag to enable remote rule evaluation in the microservices Docker Compose setup.
(none)
> Add flag to enable remote rule evaluation in microservices Docker Compose setup

- development/mimir-microservices-mode/ruler.sh
[#6536](https://github.com/grafana/mimir/pull/6536/commits/91c806cbcac6e8a7a5c269418b99c90f7761349e) changed the port for the ruler containers in the microservices Docker Compose setup to 8022 and 8023, but didn't update the `ruler.sh` helper script.
This PR updates the port in that script.
(none)
> Use correct port in ruler helper script for microservices Docker Compose setup

- pkg/storage/tsdb/block/block.go
- pkg/storage/tsdb/block/block_test.go
Add function to remove no-compact marker, this function could then be called from admin UI in order to mark/remove no-compact marker on the block. a follow up of this PR https://github.com/grafana/mimir/pull/6848
> Compactor: add function to remove no compact marker

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
If starting the ingester service (`Ingester.starting()`) fails for any reason, the corresponding ingester might be in the ring in an inconsistent state. For example, if an ingester receives the SIGTERM while opening TSDBs (replaying WAL), the TSDB opening intentionally doesn't stop, although the context is cancelled (to reduce the likelihood of on-disk corruptions). Nevertheless, the ring lifecycler gets started, and the ingester switches from `LEAVING` to `ACTIVE` state in the ring, although the `Ingester.starting()` function was interrupted due to the context cancellation. The ingester, although terminated, remains in the `ACTIVE` state because `Ingester.stopping()` wasn’t called after the failed `Ingester.starting()`.
This PR fixes the problem explained above, by explicitly stopping …
> Ingester remains in the LEAVING state if starting() terminates

- go.mod
- go.sum
- pkg/ingester/ingester.go
- pkg/mimir/modules.go
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/util.go
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
- vendor/github.com/twmb/franz-go/pkg/kadm/LICENSE
- vendor/github.com/twmb/franz-go/pkg/kadm/acls.go
- vendor/github.com/twmb/franz-go/pkg/kadm/configs.go
- vendor/github.com/twmb/franz-go/pkg/kadm/dtoken.go
- vendor/github.com/twmb/franz-go/pkg/kadm/errors.go
- vendor/github.com/twmb/franz-go/pkg/kadm/groups.go
- vendor/github.com/twmb/franz-go/pkg/kadm/kadm.go
- vendor/github.com/twmb/franz-go/pkg/kadm/logdirs.go
- vendor/github.com/twmb/franz-go/pkg/kadm/metadata.go
- vendor/github.com/twmb/franz-go/pkg/kadm/misc.go
- vendor/github.com/twmb/franz-go/pkg/kadm/partas.go
- vendor/github.com/twmb/franz-go/pkg/kadm/topics.go
- vendor/github.com/twmb/franz-go/pkg/kadm/txn.go
- vendor/modules.txt
This PR adds experimental support to the ingester to consume write requests from a Kafka topic. The configuration is the same as used in #6888 - it is hidden because it is _very_ experimental. For the same reason this PR doesn't include a changelog entry.
The consumption logic is following fairly basic manual kafka consumption (outside a consumer group) with a few twists:
1. unmarshalling and Push() invocation happen concurrently. Roughly 14% of the time spent serving a write request is in unmarhsalling it. Making these two work concurrently speeds up consumption.
2. the ingester is using a consumer group to persist how far it has consumed, so it picks up from there after a restart. But it doesn't consume in a consumer group - partition allocations is manual based on the ingester ID in …
> ingester: add experimental support for consuming records from kafka

- pkg/storage/ingest/reader.go
Follow-up of #6929
* check that the offset we're committing is certainly from the partition we're committing to
* process a fetch even when it contains some errors; this allows to process fetches with partial data
> ingest consumer: more granular error handling, committer sanity check

- CHANGELOG.md
- Makefile
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/querier/remote_read.go
- pkg/querier/store_gateway_client.go
- pkg/querier/store_gateway_client_test.go
- pkg/storegateway/bucket_store_server_test.go
- pkg/storegateway/storegatewaypb/custom.go
- pkg/storegateway/storegatewaypb/custom_test.go
Today I've been paged because of some 500 errors tracked by **querier**. After some investigation I learned that these 500 errors were caused by remote read queries being cancelled. Such requests should be tracked as 499 and not 500.
**Why requests are tracked as 500?**
There are two bugs:
1. In the remote read handler we don't check for context cancellation and and so we always return 500 on any error. In this PR I'm doing the smallest change to fix this specific issue, which is just checking for context cancellation. A better error handling would be required in the remote read handler, but I would defer to a follow up work.
2. TIL that when the context is cancelled while running a gRPC function, the error returned is **not** `context.Canceled` but a gRPC error with `codes.Canceled`. I …
> Fix context cancellation handling when request is canceled while querying store-gateway

- CHANGELOG.md
- pkg/mimirtool/commands/analyse_rulefiles.go
- pkg/mimirtool/commands/analyse_rulefiles_test.go
This field wasn't populated when rule files were analyzed.
Fixes #6952
> Fix .metricsUsed in mimirtool analyze rule-file

- CHANGELOG.md
There's no rc.0 yet, so it doesn't make sense to have changelog for rc.1
Also, removing unreleased part.
Ref: https://github.com/grafana/mimir/issues/6670
> [release-2.11] Condense changelog for rc.0

- CHANGELOG.md
- docs/sources/mimir/release-notes/v2.11.md
- pkg/mimirtool/commands/analyse_rulefiles.go
- pkg/mimirtool/commands/analyse_rulefiles_test.go
Backporting [Fix .metricsUsed in mimirtool analyze rule-file](https://github.com/grafana/mimir/pull/6953) to release-2.11
Pending to know the state of 2.11 to choose the proper CHANGELOG entry.
> [release-2.11] Fix .metricsUsed in mimirtool analyze rule-file (#6953)

- pkg/frontend/v2/frontend_scheduler_adapter.go
- pkg/scheduler/scheduler.go
This is to allow us to observe the effects of turning on multidimensional queueing, by breaking out the queue duration metric used in the our Mimir / Reads Latency (Time in Queue) panel as well as alerts.
Went back and forth on how to label this, but stuck with the idea that we shouldn't label the additional queue dimensions with a specific meaning in Mimir by doing something like "take the first additional queue dimension and assign it to a label named `query_component`.
Instead I am just concatenating and shipping the additional queue dimensions as is, and we can use the alerts & dashboards to assign meanings to the labels.
Open to feedback on that choice of approach!
> add additional queue dimensions to query scheduler queue duration histogram

- pkg/storegateway/bucket_chunk_reader.go
- pkg/storegateway/series_chunks.go
fine-grained chunks were removed in #5816 and #5875. These comments do not apply anymore
> store-gateway: remove obsolete comments for fine-grained chunks caching

- docs/sources/mimir/configure/about-versioning.md
As mentioned in https://github.com/grafana/mimir/pull/6673, the configuration parameters removed ahead of the 2.11 release were not also removed from `about-versioning.md`. This PR takes care of that.
> Delete docs on removed configuration parameters

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/v2/frontend_scheduler_adapter_test.go
- pkg/util/time.go
> fix and test label query optional time param parsing for additional queue dimensions

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/util/validation/limits.go
This PR adds a new override to enable / disable metric relabeling per tenant. This is useful to prevent duplicate relabel processing when distributors are embedded into multiple components, or to mitigate expensive relabel rules temporarily during an incident.
Fixes #6968
> Support disabling metric relabeling per tenant

- pkg/distributor/query.go
- pkg/ingester/client/streaming.go
- pkg/querier/block_streaming.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/error_translate_queryable_test.go
- pkg/querier/errors.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/limiter_test.go
- pkg/util/limiter/errors.go
- pkg/util/limiter/query_limiter.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
This PR improves usages of `validation.LimitError` errors. It addresses the following problems found in the code:
- In case of an unexpected behaviour, functions `limiter.AddSeries()`, `limiter.AddChunkBytes()`, `limiter.AddChunks()` and `limiter.AddEstimatedChunks()` return an error of type `validate.LimitError`. In some cases, the caller of those functions used to wrap the returned error into `validation.LimitError`, although it was not necessary. In order to prevent this, the signature of the above mentioned methods has been changed from `func AddXyz(...) error` to `func AddXyz(...) validation.LimitError`. This way we enforced that the only allowed errors returned by these functions are of type `validation.LimitError`. 
- Type `validation.LimitError` is now an interface, instead of a …
> Improve validation.LimitError usages

- CHANGELOG.md
- docs/sources/mimir/manage/tools/mimirtool.md
- pkg/mimirtool/commands/alerts.go
- pkg/mimirtool/commands/alerts_test.go
- pkg/mimirtool/commands/testdata/alertmanager_config.yaml
Seeking some direction from the maintainers and raising the PR for feedback.
We have encountered the same problem where getting the config synced for alert manager using `mimirtool` is quite cumbersome. Looking to fix the issue where the output of `mimirtool alertmanager get` cannot be used for `mimirtool alertmanager load` since the `get` command output a single file that contains both the config and the templates file. Furthermore, the output is not a valid yaml.
To be honest, I am not entirely sure what direction this should go hence this only contains a minimal working enhancement that works on my test setup. For example, 
```shell
./mimirtool alertmanager get --log.level="debug" --output-dir="am"
./mimirtool alertmanager load am/config.yaml am/*.tpl
```
Some of the obvious caveat:
* …
> Mimirtool: add --output-dir to alertmanager get

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir/autoscaling.libsonnet
- operations/mimir/read-write-deployment/autoscaling.libsonnet
Few months ago we rolled out some improvements to querier HPA at Grafana Labs. In this PR I'm proposing to upstream them.
The main idea of these changes is avoiding the querier HPA scales up too aggressively when it wouldn't be required. The main issue looks to be the number of desired replicas measured looking at the 75p number of inflight queries in the query-scheduler queue.
The number of enqueued requests can spike a lot if (a) we receive a sudden burst of queries or (b) read part is experiencing a temporarily (short) slow down. However, in many cases we process these queries even before new queriers are scaled up, but the metric is recorded and the scale up will happen anyway (to a very high number) not being much effective in the end.
The pattern described above is not the only one. …
> Jsonnet: improve querier HPA to scale up and down more gradually

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/mimirpb/timeseries.go
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
Makes `Distributor.push` shorter and hopefully cleaner.
None.
> Refactor `Distributor.push()`

- integration/backward_compatibility.go
Add 2.11 to the backwards compatibility tests.
> Add 2.11 to backwards compatibility test

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-slow-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
- operations/mimir-mixin/dashboards/slow-queries.libsonnet
This PR dusts off the Slow queries dashboard. it contains a couple of minor usability changes
* `org_id` label renamed to `user`
* `Time span`, `Step`, `Duration` fields are now parsed as time duration in seconds and can be properly sorted by (e.g. 2.1 s)
* bytes columns display as an IEC byte unit and can be sorted by (e.g. 1GiB)
* chunks and series counts are displayed as short numbers (e.g. 1.2K, 15M) 
* reorder `status` and `err` as earlier columns
* add human-friendly names to a few parameters (`Error`, `Start`, `End`, `Time`, `Completion date`)
* convert all numeric fields to numbers so they can be sorted by
> "Slow Queries" dashboard: make more fields sortable

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/v2/frontend_scheduler_adapter.go
re-reviewed these utils against the upstream prometheus implementation.
No behavior changes, just docstrings referencing the canonical implementation, and updating the signature of the instant query decoder to take a `time.Now` func like upstream does.
> prometheus codec time param parsing docstrings and emulating upstream prometheus behavior

- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/openshift-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/mimir-config.yaml
This leads to having to manually override the value of `blocks_storage.backend` when using something other than S3. This is already how the ruler and alertmanager storages work.
This shouldn't break existing installations because S3 is already the default in Mimir.
This was prompted by [this comment](https://github.com/grafana/mimir/discussions/1901#discussioncomment-7930669) by @ksingh-scogo (thanks!)
For example:
```yaml
mimir:
structuredConfig:
common:
storage:
backend: azure
azure:
account_key: "<YOUR KEY HERE>"
account_name: <ACKT_NAME>
endpoint_suffix: "blob.core.windows.net"
blocks_storage:
backend: azure ## Without this it doesn't work
azure:
container_name: mimir-dev-blocks
```
> helm: omit `backend: s3` when minio is disabled

- pkg/storage/ingest/DESIGN.md
- pkg/storage/ingest/config.go
- pkg/storage/ingest/partition_offset_reader.go
- pkg/storage/ingest/partition_offset_reader_test.go
- pkg/storage/ingest/partition_offset_watcher.go
- pkg/storage/ingest/partition_offset_watcher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/util.go
- pkg/storage/ingest/util_test.go
- pkg/storage/ingest/writer_test.go
This PR is another piece of the puzzle for the experimental support to ingest data through Kafka. In this PR I'm upstreaming `PartitionReader.WaitReadConsistency()`, which is the building block to add condition read-after-write support (this function will be used in a follow up PR).
The idea of `PartitionReader.WaitReadConsistency()` is pretty simple: wait until the last produced offset (at the time of the function call) has been consumed in each ingester. This function will be used in the ingester to wait before running a query which requires strong read consistency.
N/A
> Kafka ingestion experiment: add PartitionReader.WaitReadConsistency()

- pkg/storage/ingest/partition_offset_watcher_test.go
Earlier today I merged https://github.com/grafana/mimir/pull/6982, which introduces the test `TestPartitionOffsetWatcher_Concurrency`. The test panics if `lastNotifiedOffset == lastWatchedOffset` because `rand.In63n(0)` is not a valid input value:
```
panic: invalid argument to Int63n
goroutine 1684 [running]:
math/rand.(*Rand).Int63n(0xc000447470, 0x0)
/usr/local/go/src/math/rand/rand.go:122 +0x125
math/rand.Int63n(0xc0007a4960?)
/usr/local/go/src/math/rand/rand.go:443 +0x2f
github.com/grafana/mimir/pkg/storage/ingest.TestPartitionOffsetWatcher_Concurrency.func2()
/__w/mimir/mimir/pkg/storage/ingest/partition_offset_watcher_test.go:231 +0xb8
github.com/grafana/mimir/pkg/storage/ingest.runAsync.func1()
/__w/mimir/mimir/pkg/storage/ingest/writer_test.go:354 +0x82
created by …
```
> Fix panic in TestPartitionOffsetWatcher_Concurrency

- pkg/storage/tsdb/bucketindex/loader_test.go
I've noticed that `TestLoader_ShouldCacheIndexNotFoundOnBackgroundUpdates` is flaky while [running in CI](https://github.com/grafana/mimir/actions/runs/7398345777/job/20127331406?pr=7030) for another PR:
```
--- FAIL: TestLoader_ShouldCacheIndexNotFoundOnBackgroundUpdates (1.15s)
loader_test.go:442: 
Error Trace:	/__w/mimir/mimir/pkg/storage/tsdb/bucketindex/loader_test.go:442
Error:      	Received unexpected error:
Diff:
--- metric output does not match expectation; want
+++ got:
@@ -2,3 +2,3 @@
-cortex_bucket_index_loaded 0
+cortex_bucket_index_loaded 1
Test:       	TestLoader_ShouldCacheIndexNotFoundOnBackgroundUpdates
FAIL
```
The reason why `TestLoader_ShouldCacheIndexNotFoundOnBackgroundUpdates` is flaky is because the `loadAttempts` metric is increased before we read the bucket …
> Fix flaky TestLoader_ShouldCacheIndexNotFoundOnBackgroundUpdates

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
`prometheusCodec` provides the methods `DecodeRequest` and `EncodeRequest` to convert from an `http.Request` to a `querymiddleware.Request` and back. The conversion from an http request sets values in the request options, but these are not considered for the conversion back to an http request. As a consequence, the http request obtained by decoding and re-encoding is not equivalent to the original request in cases where custom headers were present on the initial request.
This PR adds http headers equivalent to the request options to fix this.
Fixes n/a
> [query-frontend] Set http request headers from querymiddleware request options

- pkg/ingester/ingester.go
- pkg/ingester/ingester_ingest_storage_test.go
- pkg/ingester/lifecycle_test.go
- pkg/mimir/runtime_config_test.go
- pkg/querier/api/consistency.go
- pkg/storage/ingest/partition_offset_reader_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
- pkg/util/testkafka/cluster.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
This is another step forward in the experimental ingest storage conditional read-after-write implementation. In this PR I'm introducing a per-tenant config option to set the default read consistency guarantee (used only when ingest storage is enabled). When the read consistency is set to `strong`, then in the ingester we wait until all the data has been replayed from Kafka up until that point before executing a query.
Notes:
- The per-query conditional support will be later upstreamed by @dimitarvdimitrov (work was done by him).
- In the ingester unit tests I've picked a simple path, just testing `QueryStream()`. Reason why I would suggest to not test every function for now is because we may change the strong consistency implementation later, moving it from the ingester to an upper layer …
> Add strong read consistency support in ingester for experimental ingest storage

- pkg/alertmanager/multitenant_test.go
In #5840 we've added `msteams` support to Alertmanager. Whenever we add support for a new receiver, we're used to test it in `TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled`. In this PR I'm adding it.
N/A
> Add 'msteams' to TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- development/mimir-microservices-mode/config/mimir.yaml
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
- pkg/ingester/active_series.go
- pkg/ingester/ingester_test.go
- pkg/querier/cardinality_analysis_handler.go
- pkg/querier/cardinality_analysis_handler_test.go
- pkg/util/validation/limits.go
To build a response for an `/active_series` request, queriers need to hold the full series set in memory for deduplication. For selectors that return a large set of series this can consume a lot of memory, as allocations are proportional to the size of the set.
This PR allows sharding these requests in the frontend such that each querier only needs to bring part of the series set into memory for deduplication. The frontend then interleaves the partial responses into a single set that is returned back to the client. It also introduces a response size limit for active series responses in queriers to prevent unbounded allocation and OOMs.
This PR also introduces a dedicated roundtripper for active series requests to bypass the generic cache. Since this endpoint is supposed to return "fresh" …
> Enable sharding for `active_series` requests

- pkg/ingester/owned_series.go
We log and update the metric when we periodically recalculate the owned series for tenants, but we missed the recalculation [triggered during service start](https://github.com/grafana/mimir/blob/f5d09550a503aeb1a4c6cfb9c2d6bdf077877270/pkg/ingester/owned_series.go#L85). This moves the log/metric update inside of `updateAllTenats` so that we have a record of all invocations.
N/A
> Move owned series check logging/metric inside of updateAllTenants

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
Fix max_fetched_series_per_query not applied to /series from ingesters in the querier.
The code is slightly inefficient as it checks for unique hashes twice, once in distributor.go and once in query_limiter.go. On the other hand the limiter uses a lock, so it makes sense to first merge the results from ingesters and throw out the duplicates before calling the limiter under lock.
I chose pkg/distributor and not pkg/querier for the placement to align with the limit check in the ingester streaming code in pkg/distributor/query.go
Fixes: reported directly.
- N/A [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Fix max_fetched_series_per_query not applied to /series from ingesters

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-tools/serve/run.sh
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
Have not figured out how to show the actual panel in the dashboards, because the metamonitoring helm chart seems to have the scrape interval too wide to graph with `[$__rate_interval]`, but if I open the panel in explore and hardcode the rate interval to to `[10m]` it looks like:
> new Mimir / Reads dashboard panel for scheduler queue duration, breakout by additional queue dimensions

- CHANGELOG.md
- operations/mimir-tests/test-automated-downscale-generated.yaml
- operations/mimir-tests/test-consul-multi-zone-generated.yaml
- operations/mimir-tests/test-deployment-mode-migration-generated.yaml
- operations/mimir-tests/test-multi-zone-generated.yaml
- operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
- operations/mimir-tests/test-multi-zone-with-store-gateway-automated-downscaling-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-caches-disabled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
- operations/mimir/multi-zone.libsonnet
This PR removes the CPU limit for rollout-operator pods created by Jsonnet.
This limit is not needed and unnecessarily limits the CPU utilisation of the rollout-operator under load.
(none)
> Remove default CPU limit for rollout-operator pod

- docs/sources/mimir/references/architecture/components/querier.md
Fixes the formatting in the querier component doc to have two top level bullet points to describe -querier.query-ingesters-within usage. 
Before the change, docs render as:
After the change, docs render as:
> Fix formatting in querier component doc

- docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
- operations/helm/charts/mimir-distributed/values.yaml
The location where Grafana Agent Operator CRDs is changing to a new folder as part of grafana/agent#6077. The old link still works, but it will stop working in a few days after all references to the old links have been removed.
> docs: update link to Grafana Agent Operator CRDs

- pkg/mimir/mimir.go
- pkg/mimir/mimir_test.go
The current validation added in #6940 also applies to the distributor and ends up blocking distributor startup unnecessarily.
> ingest: include gRPC status code validation only when running ingester

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
Improves the Query Scheduler Time in Queue breakout.
Currently it has too many series to be helpful at a glance, and it's not particularly effective to have 99th percentile and 50th percentile/average on the same panel, because the graph is scaled to accommodate the 99th percentile, and the 50th %ile and average get squashed at the bottom:
The new better version breaks it out into a row with 3 panels, one each for 99th percentile, 50th percentile, and Average:
Also extended the jsonnet function to allow all these panels to be build from the same function.
> Mimir / Reads dashboard query scheduler queue duration breakout improvements

- pkg/distributor/distributor.go
The invocation of the active series `ingesterQuery` through `forReplicationSet` can be canceled via its context if the quorum has been established otherwise. In these cases, we should not return an error from `ingesterQuery`.
Fixes n/a
> Handle `context.Canceled` in active series requests

- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/v2/frontend_scheduler_adapter.go
This contains four small changes related to the active series API:
- Make request queue scheduling dimension extraction aware of active series requests.
- Add the current json parser buffer to the error message in cases where a querier responds with an unexpected response.
- Log the error message.
- Do not pass along the `Accept-Encoding` header from the query-frontend to upstream services, because its value has been consumed in the query-frontend itself and its presence could lead to unexpected behaviour of upstream components.
Fixes n/a
> Small fixes for `/active_series`

- pkg/scheduler/queue/queue_test.go
Will be adding a benchmark test to prove out the effects of the query scheduler additional queue dimensions when there is a slow querier - factoring out some methods here first to make this more reusable and easier to understand.
> scheduler queue benchmark: factor out & clarify functions

- .github/workflows/update-make-docs.yml
- CODEOWNERS
- docs/docs.mk
- docs/make-docs
Updates the `make docs` procedure, consisting of the script and related Make scaffolding.
**For reviewers:**
1. Please ensure you can run `make docs` from the `docs/` directory.
1. Update repository access, please do one of the following:
1. Add @grafana/docs-tooling with write access to the repository. It is a group containing only myself but would additionally include any other Doc squad tooling maintainers in the future. Any changes to this groups membership would be communicated.
1. Add only my GitHub handle if that is easier for governance purposes. 
1. Ask me to remove the changes to CODEOWNERS and rely on my membership of the @grafana/mimir-maintainers group.
> Update `make docs` procedure and add workflow to keep it up to date

- pkg/querier/blocks_store_queryable.go
While reading the code I noticed this `if` doesn't actually do anything. Since the actual optimization of it is small I chose to keep the code somewhat simpler and remove it.
This has never worked, since being added in 2020, so I don't think we've had a regression at some point.
> querier: remove noop if

- CHANGELOG.md
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/querier.go
- pkg/querier/stats/query_metrics.go
Adds metrics to:
- count how many queries are executed in total for a particular source: ingesters vs store gateways
- count the total chunks read from a store gateway
- Counted in separate places for streaming and non-streaming fetches
> Add additional querier metrics

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
This PR adds an additional panel to the Reads and Remote Rule Reads dashboards, showing the query-scheduler queue length:
This is useful when responding to the `MimirSchedulerQueriesStuck` alert, as the alert is based on the queue length, which is not currently shown on these dashboards.
(none)
> Add query-scheduler queue length to Reads and Remote Ruler Reads dashboards

- operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml
The PR fixes a typo in the Helm chart's template from the Minio's create-bucket-job.
Fixes #7060
> Fix missing "annotation" key in create-bucket-job template of helm chart

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/roundtrip.go
At Grafana Labs we're running `-query-frontend.not-running-timeout` with 2s. In this PR I'm upstreaming the change to the default setting, as planned as part of this work. Given this change effectively enable the feature by default, I'm also taking the opportunity to move the config option out of experimental state.
N/A
> Change -query-frontend.not-running-timeout default value to 2s and mark it as advanced

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/distributor/distributor.go
This promotes `-distributor.reusable-ingester-push-workers` flag to `advanced` and sets a default value of 2000. This is the value we've been using on Grafana Cloud for a while and we've seen an improvement of up to 7% of CPU usage on the distributors.
Fixes https://github.com/grafana/mimir/issues/6776
> Use 2K reusable ingester push workers by default

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/mimir/mimir.go
- pkg/util/fieldcategory/overrides.go
This sets the `-server.grpc.num-workers` to 100 by default, and changes the category of that flag to `advanced`.
This is the value we've tested in Grafana Cloud for a while. We've observed an improvement of around 5% in ingester CPU compared to running without this flag set.
Note that this is not a limit, but the number of pre-allocated long-lived workers. When all workers are busy, a new goroutine will be spawned (previous default behaviour).
There was no public issue for this.
> Set -server.grpc.num-workers=100 by default

- pkg/querier/blocks_store_queryable_test.go
@charleskorn reported me that the `TestBlocksStoreQuerier_ShouldReturnContextCanceledIfContextWasCanceledWhileRunningRequestOnStoreGateway` [failed in a CI run](https://github.com/grafana/mimir/actions/runs/7454638805/job/20282329320?pr=7068#step:8:59) with the following error:
```
--- FAIL: TestBlocksStoreQuerier_ShouldReturnContextCanceledIfContextWasCanceledWhileRunningRequestOnStoreGateway (0.01s)
--- FAIL: TestBlocksStoreQuerier_ShouldReturnContextCanceledIfContextWasCanceledWhileRunningRequestOnStoreGateway/LabelNames() (0.00s)
panic: not enough mocked results [recovered]
panic: not enough mocked results
goroutine 687 [running]:
testing.tRunner.func1.2({0x203a880, 0x35a4490})
/usr/local/go/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1() …
```
> Make TestBlocksStoreQuerier_ShouldReturnContextCanceledIfContextWasCanceledWhileRunningRequestOnStoreGateway easier to debug when flaky

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- operations/mimir/config.libsonnet
- operations/mimir/store-gateway.libsonnet
- pkg/storage/tsdb/config.go
Follow-up to https://github.com/grafana/mimir/pull/5025. Internally we reduced the concurrency even when lazy loading was enabled. This upstreams those changes to the defaults.
Fixes N/A
> Reduce sync concurrency in store-gateway by default to reduce disk contention

- pkg/storage/ingest/partition_offset_reader_test.go
- pkg/storage/ingest/partition_offset_watcher_test.go
- pkg/storage/ingest/util_test.go
- pkg/storage/ingest/writer_test.go
A chore PR to slightly simplify `runAsync()` and `runAsyncAfter()` usage in ingest storage tests. Now, these functions directly add themselves to the `sync.WaitGroup`.
N/A
> Chore: simplify runAsync() and runAsyncAfter() usage in ingest storage tests

- pkg/storage/ingest/reader.go
A tiny PR to set `BrokerMaxReadBytes` on the Kafka reader (used by the new experimental ingest storage). The Kafka library suggests to set it to 2x `FetchMaxWait`.
N/A
> Ingest storage: configure BrokerMaxReadBytes on Kafka reader

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/ingester_test.go
- pkg/ingester/client/client.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
This PR does the following things:
- Sets `dskit`'s `server.Config.ReportGRPCCodesInInstrumentationLabel` to true, making ingester report gRPC status codes as `status_code` labels in the ``cortex_request_duration_seconds` metric by default.
- Report gRPC status codes as `status_code` lables in `cortex_ingester_client_request_duration_seconds` metric by default.
- Deprecates the `ingester.client.report-grpc-codes-in-instrumentation-label-enabled` CLI flag, and sets its default value to `true`. This CLI flag will be removed in Mimir 2.14.0, but the default behaviour of Mimir will be as the CLI flag were set to `true`.
Part of #6008
> Report gRPC status codes as labels in request duration metrics

- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
While working on https://github.com/grafana/mimir/pull/7142 and testing it locally using `development/mimir-ingest-storage` I frequently get mimir-write not starting successfully because Kafka is not ready after all the retries done by the Kafka reader (error: `failed to fetch last committed offset`). A simple solution looks configuring Mimir to wait until Kafka is ready, which is what I do in this PR (tested and fixes the problem).
N/A
> Ingest storage local dev env: configure Mimir components to start after Kafka is healthy

- CHANGELOG.md
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
When a metric with a non-ascii characters gets received the input validation correctly rejects it, but depending on the invalid character the serialization of the generated error message can fail, for example:
```
2024/01/16 17:24:39 ERROR: [transport] [server-transport 0xc05a8c21a0] Failed to marshal rpc status: code:400 message:"received a series with invalid metric name: 'invalid_metric_name_\xb0c' (err-mimir-metric-name-invalid)\n" details:{type_url:"type.googleapis.com/httpgrpc.HTTPResponse" value:"\x08\x90\x03\x12)\n\x0cContent-Type\x12\x19text/plain; charset=utf-8\x12!\n\x16X-Content-Type-Options\x12\x07nosniff\x1a\x80\x01received a series with invalid metric name: 'invalid_metric_name_\xb0c' (err-mimir-metric-name-invalid)\n"}, error: string field contains invalid UTF-8
```
This …
> remove non-ascii characters from invalid metric names in error message

- integration/e2emimir/client.go
- integration/query_frontend_active_series_test.go
- pkg/distributor/distributor.go
- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
- pkg/storegateway/storegatewaypb/custom.go
- pkg/util/grpc_error.go
- pkg/util/grpc_error_test.go
This PR addresses two issues I discovered while testing the active series API.
- Shard requests generated for incoming active series requests with method `GET` and a `selector` parameter in the query string were broken and did not include the modified shard selector. Therefore, the results would always contain the set of series duplicated as many times as there are request shards. 
- Handling `context.Canceled` is not sufficient for grpc related calls, we also need to handle `status.Code(err) == codes.Canceled`. Following up on a review comment, I have moved and reused code from `pkg/storegateway` which already solves this issue.
> `/active_series`: generate correct request shards for incoming `GET` requests,  handle gRPC errors

- operations/helm/charts/mimir-distributed/templates/gateway/gateway-dep.yaml
- operations/helm/charts/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/gateway-dep.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/nginx/nginx-dep.yaml
At the moment, the nginx-config configmap is mounted as folder, masking everything else that is located in `/etc/nginx`.
I'm trying to load a module in the `nginx.conf` with `load_module modules/ngx_http_js_module.so;`.
With the current setup, this fails with the following logs:
`/docker-entrypoint.sh: No files found in /docker-entrypoint.d/, skipping configuration
2023/05/09 11:46:27 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_js_module.so" failed (/etc/nginx/modules/ngx_http_js_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:1
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_js_module.so" failed (/etc/nginx/modules/ngx_http_js_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/nginx.conf:1`
With …
> [BUGFIX] Update nginx deployment to mount nginx.conf as file

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/jsonnetfile.lock.json
Update dashboards to drop unsupported step parameter in query targets.
Updates jsonnet-libs dependency to https://github.com/grafana/jsonnet-libs/commit/3d58bd591c278f3f342bc1e25399806c49ace104 to get https://github.com/grafana/jsonnet-libs/pull/1128
Related to #7152
Related to https://github.com/grafana/jsonnet-libs/pull/1128
- N/A [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> mimir-mixin: drop unsupported step target parameter

- operations/helm/charts/mimir-distributed/values.yaml
The documentation on the website was not that clear and it took us a while in order to find the http insecure_skip_verify option. Therefore we thought an Example would be good for future reference.
See Commit Message above
N/A
> Update values.yaml documentation and example

- RELEASE.md
This PR sets tentative dates for Mimir releases in 2024, which are the second Monday of March, June, September and December. Moreover, the PR sets the shepherds for releases Mimir 2.11.0 (already done) and Mimir 2.12.0 (the next one).
> Update RELEASE.md with tentative 2024 release schedule

- CHANGELOG.md
- integration/asserts.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- Rename `cortex_query_storegateway_chunks_total` to `cortex_querier_query_storegateway_chunks_total`
- Add metric to test cases
Follow-up to #7099
Addresses a comment from a previous PR: https://github.com/grafana/mimir/pull/7099#discussion_r1452507876
> Rename metric to cortex_querier_query_storegateway_chunks_total

- .github/workflows/test-build-deploy.yml
Change CI config to load and store the same cache key for all 4 groups of unit tests and another one for all 6 groups of integration tests.  Broadly the same set of files (mostly dependencies) will be compiled for every set of tests.
GitHub has a limit on the total amount of cache, which is about 1 day's worth in current usage.
https://github.com/grafana/mimir/actions/caches
> CI: use a single cache for tests

- go.mod
- go.sum
- integration/configs.go
- integration/query_frontend_test.go
- tools/pre-pull-images/main.go
- vendor/github.com/grafana/e2e/db/kafka.go
- vendor/github.com/grafana/e2e/images/images.go
- vendor/modules.txt
In this PR I'm adding the 1st integration test on the experimental ingest storage. The integration test I've added is a new variant of `runQueryFrontendTest()`, with a scenario running the ingest storage, query-scheduler and query-frontend with query stats.
I've updated `grafana/e2e` to get https://github.com/grafana/e2e/pull/17.
N/A
> Add integration test using ingest storage

- pkg/frontend/v2/frontend_scheduler_adapter.go
Don't want to lose this completely while we track down which request types we need to add timestamp parsing for.
But it was logging way too much and the message was a bit too alarming
Switching to debug and only logging the URL so we don't log any potentially sensitive request headers
> fix additional queue dimensions unsupported request logging

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
In a [previous PR](https://github.com/grafana/mimir/pull/7098) we did this breakout of one panel into three for the Reads dashboard but forgot to apply the same improvements for Remote Ruler Reads
> mimir ruler reads dashboard query scheduler queue duration breakout improvements

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/util/validation/limits.go
We're used to say everyone that the last 10m of data is not cached in the query results cache and that's what's configured in Helm and Jsonnet. However, the default value of `-query-frontend.max-cache-freshness` is 1m. In this PR I propose to change it to 10m.
N/A
> Changed -query-frontend.max-cache-freshness default value from 1m to 10m

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This PR fixes a possible panic introduced by #6970. In `prePushRelabelMiddleware`, when `MetricRelabelingEnabled` returns true, it would call to the `next` middleware in the chain, then call `CleanUp` in a defer. This results in `CleanUp` being called twice. Two conditions result:
1. Distributors can panic during marshaling because the WriteRequest has already been reset to zero length
2. Ingesters can ingest corrupt data because the Label values in the request may be unsorted. They are then stuck failing to compact blocks.
The existing middleware test was attempting to find this condition via the `cleanupCallCount` field, but unfortunately the test is too simple to reproduce the behavior of actual distributor middleware in a running Mimir cluster. To reproduce the issue in test, we can …
> Fix panic as a result of duplicate write request cleanup

- CHANGELOG.md
- cmd/mimir-continuous-test/main.go
- cmd/mimir/main.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/instrumentation.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
Currently, it's next to impossible to use Tempo's TraceQL to search for traces on specific queries, as TraceQL doesn't support searching on event attributes. [Here](https://github.com/grafana/tempo/issues/2313#issuecomment-1551490022) is a related comment pointing out this pain for Mimir. 
Since query params aren't really an event in time, and therefore don't benefit from the timestamp that span events/logs require, I propose that instead of logging query parameters as span events, we store them as span attributes (a.k.a. "tags"). This will make traces searchable by query information (e.g., query string and step size) via TraceQL, and removes some span logs whose timing has no significance.
Relates to https://github.com/grafana/tempo/issues/2313
- [N/A] …
> Write query parameters to span attributes instead of events

- pkg/storegateway/bucket.go
Log errors creating `indexheader.Reader` instances at "error" since it can indicate serious problems. This is often caused by loading of Readers being interrupted (context.Canceled, not serious) but can also be caused by store-gateways running out of disk space (a bad time).
Internal incident
> Increase log level for problems creating index header readers

- development/mimir-ingest-storage/config/example-rules.yaml
- development/mimir-ingest-storage/config/mimir.yaml
- go.mod
- go.sum
- integration/query_frontend_test.go
- integration/ruler_test.go
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
- pkg/ruler/rule_query_consistency.go
- pkg/ruler/rule_query_consistency_test.go
- vendor/github.com/prometheus/prometheus/rules/alerting.go
- vendor/github.com/prometheus/prometheus/rules/dependency.go
- vendor/github.com/prometheus/prometheus/rules/group.go
- vendor/github.com/prometheus/prometheus/rules/manager.go
- vendor/github.com/prometheus/prometheus/rules/origin.go
- vendor/github.com/prometheus/prometheus/rules/recording.go
- vendor/github.com/prometheus/prometheus/rules/rule.go
- vendor/modules.txt
This PR introduces conditional read-after-write (or strong read consistency) support for rule evaluations. This PR is based on https://github.com/grafana/mimir-prometheus/pull/587.
How it works:
- The Prometheus ruler evaluates whether each rule in a group is independent or not. A rule is independent if no other rule depends on it and it doesn't depend on any other in the group.
- The information whether a rule is independent or not is stored in the `RuleDetail` inside the context passed down to the ruler's query function.
- Mimir uses a custom query function. In this PR I've introduced a query function wrapper which reads the `RuleDetail` from the context and inject Mimir-specific read consistency requirement in the context.
- The Mimir-specific read consistency requirement is passed, …
> Add conditional read-after–write support to rules evaluation

- pkg/querier/worker/frontend_processor.go
- pkg/querier/worker/frontend_processor_test.go
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
- pkg/querier/worker/util.go
- pkg/querier/worker/util_test.go
If a gRPC server configured with `grpc_server_connection_max_age`, it closes the client's connections after a period of max_age + age_grace (refer to discussion https://github.com/grafana/mimir/issues/7023#issuecomment-1893752220).
At the moment there is nothing we expect a user to act on after the errors, the frontend- and scheduler-processors' client streams log, when the server resets the connection. This PR updates both processors, moving the logging to the debug level, to reduce any possible confusion.
_Sidenote: a more general solution, the gRPC folks suggested, is to implement an application specific lifetime management of the client stream. I.e. the stream's client should implement its own lifetime, to reconnect before the server drops it. So far, I'm not sure, it's worth the …
> querier: don't log errors on stream connection reset

- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
- pkg/ruler/compat.go
- pkg/ruler/rule_query_consistency.go
- pkg/ruler/rule_query_consistency_test.go
This PR is part of the experimental ingest storage. In this PR I've done a couple of improvements to read consistency observability:
- Log read_consistency in 'query stats' even when query details are not available (the two are unrelated so I don't think we should bind them in the query-frontend middleware)
- Log in a tracing span when the ruler requests strong read consistency
N/A
> Improve read consistency observability

- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/openshift-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/mimir-config.yaml
Reverts grafana/mimir#6999
The default is actually `filesystem`. So omitting `s3` results in a breaking change as reported in https://github.com/grafana/mimir/issues/7196
> Revert "helm: omit `backend: s3` when minio is disabled"

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-slow-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
- operations/mimir-mixin-tools/serve/provisioning-datasources.yaml
- operations/mimir-mixin-tools/serve/run.sh
- operations/mimir-mixin/dashboards/slow-queries.libsonnet
This fixes two issues with the dashboard and adds a new panel: Query wall time 
1. Some parsing errors in the logs table showed as columns. This PR prevents the parsing errors
**Previously**
**Now**
2. `query_wall_time_seconds` was hidden from the table
3. Adds three panels for query wall time
This also adds the ability to set up a Loki datasource for the local dashboards in `make mixin-serve`
> Slow queries dashboard: bug fixes and a new panel
