docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

I did NOT set the documentation versions as Mimir and GEM are not released yet.

Helm: release 5.1-rc.0

---

.github/workflows/push-mimir-build-image.yml

when using \` in pr comment, it is consider as inline code, use \\\\\\\` to escape. this PR is to fix the comment formatting, see [example](https://github.com/grafana/mimir/pull/5955#issuecomment-1709744298) 

chore: fix github action comments

---

CHANGELOG.md
cmd/metaconvert/Dockerfile
cmd/mimir-continuous-test/Dockerfile
cmd/mimir/Dockerfile
cmd/mimirtool/Dockerfile
cmd/query-tee/Dockerfile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
development/mimir-monolithic-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile

Update alpine image to 3.18.3 in release 2.9

---

pkg/querier/querier.go

only log query time clamp event if time was changed

---

docs/sources/mimir/configure/about-versioning.md

List `blocked_queries` in Experimental features
Relates to #5609

List blocked_queries in Experimental features

---

pkg/ingester/user_metrics_metadata.go
pkg/querier/metadata_handler.go
pkg/querier/metadata_handler_test.go

See below
Follow up on https://github.com/grafana/mimir/pull/5890

Follow up on comments on PR #5890

---

pkg/frontend/querymiddleware/limits.go
pkg/frontend/querymiddleware/limits_test.go

This PR improves the performance of `limitedParallelismRoundTripper` by reducing the number of goroutines spawned.
This change is based on https://github.com/grafana/loki/pull/9923.
(none)

Improve performance of `limitedParallelismRoundTripper`

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

Merge mimir-distributed-release-5.1 to main

---

docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
docs/sources/mimir/manage/monitor-grafana-mimir/collecting-metrics-and-logs.md

Integrations documentation was moved.
Fixes internal

Docs: fix link to self hosted mimir integrations

---

docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md

fix broken link in vault setup
Fixes internal issue

Helm: Docs: fix broken link in vault setup

---

pkg/util/push/push_test.go

This PR improves the `TestHandler_ErrorTranslation` test by adding some additional usecases currently not covered by the test.

Improve push handler's TestHandler_ErrorTranslation test

---

go.mod
go.sum
pkg/ingester/client/circuitbreaker.go
vendor/github.com/failsafe-go/failsafe-go/CHANGELOG.md
vendor/github.com/failsafe-go/failsafe-go/Makefile
vendor/github.com/failsafe-go/failsafe-go/circuitbreaker/circuitbreaker.go
vendor/github.com/failsafe-go/failsafe-go/codecov.yml
vendor/github.com/failsafe-go/failsafe-go/execution.go
vendor/github.com/failsafe-go/failsafe-go/executor.go
vendor/github.com/failsafe-go/failsafe-go/internal/util/util.go
vendor/github.com/failsafe-go/failsafe-go/policy.go
vendor/github.com/failsafe-go/failsafe-go/policy/execution.go
vendor/github.com/failsafe-go/failsafe-go/policy/policy.go
vendor/github.com/failsafe-go/failsafe-go/result.go
vendor/modules.txt

Bump github.com/failsafe-go/failsafe-go from 0.0.0-20230918014924-ee2f3b27e8d7 to 0.3.1
the dependbot PR #6116 

Dependency:  Update to failsafe version 0.3.1

---

pkg/querier/tenantfederation/merge_queryable.go

Simplify `pkg/querier/tenantfederation` code a bit. Based on input from @dimitarvdimitrov.

tenantfederation: Simplify code a bit

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
operations/mimir-tests/test-autoscaling-custom-target-utilization.jsonnet
operations/mimir-tests/test-autoscaling-generated.yaml
operations/mimir/autoscaling.libsonnet

Revert "Scale on OOMs for autoscaling components"

---

.github/workflows/push-mimir-build-image.yml

Remove stale comment from .github/workflows/push-mimir-build-image.yml.

Remove stale YAML comment

---

RELEASE.md
renovate.json

Main Branch Dependency Updates: This ensures that dependencies for the main branch are regularly updated, keeping our project's core codebase up to date with the latest improvements and features.
Security Updates for Last 2 Release Branches: We are prioritizing security by applying updates to the last two release branches, ensuring that our users are protected against potential vulnerabilities. This is working with some delays, see [here](https://github.com/ying-jeanne/mimir/pull/46)
This configuration has been thoroughly tested on the Mimir fork, which you can find at [Mimir Fork Renovate Configuration](https://github.com/ying-jeanne/mimir/blob/main/renovate.json).
- na Tests updated
- na Documentation added
- na `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, …

Security: Add renovate config in Mimir

---

renovate.json

renovate branch collides with renovate/ prefixed branches, rename the default branch prefix for renovate PR to deps-update/

Chore: Modify renovate default branch prefix

---

pkg/distributor/distributor.go

Since `distributor.forReplicationSet` is generic with respect to its callback function's return type, avoid returning `interface{}` from callback functions and use the real types instead. This makes for simpler code. There should be no behavioral changes.

Distributor: Use generic capabilities of `forReplicationSet`

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram_meta.go
vendor/modules.txt

This brings in https://github.com/prometheus/prometheus/pull/12838
Fixes https://github.com/grafana/mimir/issues/5576

Update mimir-prometheus to bd751619c7b7

---

renovate.json

We are temporarily reducing the rate of new PRs to ensure that our team can maintain high-quality code reviews and address issues efficiently. 

Chore: Lower rate limit for the version update

---

renovate.json

Add Renovate option `gomodUpdateImportPaths`, as discussed with @pstibrany. See [reference documentation](https://docs.renovatebot.com/configuration-options/#postupdateoptions).

Renovate: Add gomodUpdateImportPaths option

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
operations/mimir-tests/test-autoscaling-custom-target-utilization.jsonnet
operations/mimir-tests/test-autoscaling-generated.yaml
operations/mimir/autoscaling.libsonnet

Scale on OOMs for autoscaling components

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Helm: release 5.1.1

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
operations/helm/charts/mimir-distributed/CHANGELOG.md

Last step of release process to sync release notes and changelog to main.

Helm: merge mimir distributed 5.1 to main

---

docs/sources/mimir/set-up/migrate/migrate-from-cortex.md

Update migrate-from-cortex.md to fix word typo

---

development/mimir-monolithic-mode/config/grafana-agent.river
development/mimir-monolithic-mode/docker-compose.yml

Merge when Grafana Agent is actually out.
Fixes needed to properly handle native histograms.
N/A

Bump grafana agent  in dev docker compose

---

pkg/querier/tenantfederation/merge_queryable.go

Allow callers of tenantfederation.NewMergeQueryable to inject their own implementation of a tenant resolver. This is required for the cluster federation feature in GEM.
N/A

Allow injection of tenant.Resolver for tenantfederation queryable

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
operations/helm/charts/mimir-distributed/CHANGELOG.md

use **merge commit** not squash

Helm: merge helm 5.1.2 to main

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
vendor/modules.txt

Backport of #6446 to r259 as requested by @pracucci.

Upgrade r259 to mimir-prometheus@b523086b421d

---

pkg/ruler/ruler.go

Starting can fail for two reasons: 1) the process was sent SIGINT, 2) an actual error occurred while starting up; for example the KV store became unavailable
In those cases the ruler service's starting function may return an error. This automatically transitions the BasicService into a Failed state. This means that the stopping function is not ran. This in turn means that the subserices such as the lifecycler aren't stopped. In other words, the ruler doesn't remove itself from the ring and other rulers continue sharding rules to it.
This PR explicitly shuts down subservices when the startup failed to make sure at least the lifecycler is properly stopped.

ruler: gracefully stop subservices when starting fails

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/modules.txt

Updates mimir-prometheus.
See: https://github.com/grafana/mimir-prometheus/pull/547
N/A

Update mimir-prometheus vendor to debd4b196ec2

---

docs/sources/mimir/configure/about-versioning.md

related to https://github.com/grafana/mimir/issues/4762

store-gateway: mark eager loading as experimental

---

pkg/frontend/querymiddleware/split_and_cache.go

This removes a boolean parameter to a function which was always true

query-frontend: minor internal cleanup

---

.github/workflows/helm-release.yaml

Switch to using [github app](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps) for releasing the helm chart.
Fixes N/A

Helm: switch to github app for repo authz

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/github.com/prometheus/prometheus/promql/parser/ast.go
vendor/github.com/prometheus/prometheus/promql/parser/lex.go
vendor/github.com/prometheus/prometheus/promql/parser/parse.go
vendor/github.com/prometheus/prometheus/scrape/scrape.go
vendor/github.com/prometheus/prometheus/scrape/target.go
vendor/github.com/prometheus/prometheus/storage/buffer.go
vendor/github.com/prometheus/prometheus/storage/merge.go
vendor/github.com/prometheus/prometheus/storage/remote/azuread/azuread.go
vendor/github.com/prometheus/prometheus/storage/remote/read_handler.go
vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
vendor/github.com/prometheus/prometheus/template/template.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go
vendor/github.com/prometheus/prometheus/tsdb/errors/errors.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/github.com/prometheus/prometheus/tsdb/symbols_batch.go
vendor/github.com/prometheus/prometheus/tsdb/wal.go
vendor/github.com/prometheus/prometheus/tsdb/wlog/wlog.go
vendor/github.com/prometheus/prometheus/util/annotations/annotations.go
vendor/github.com/prometheus/prometheus/web/api/v1/api.go
vendor/modules.txt

Update mimir-prometheus to https://github.com/grafana/mimir-prometheus/commit/5f9db04c2d53 (with upstream prometheus https://github.com/prometheus/prometheus/commit/6518d6fde)

Update mimir-prometheus to `5f9db04c2d53`

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/github.com/prometheus/prometheus/promql/parser/ast.go
vendor/github.com/prometheus/prometheus/promql/parser/lex.go
vendor/github.com/prometheus/prometheus/promql/parser/parse.go
vendor/github.com/prometheus/prometheus/rules/group.go
vendor/github.com/prometheus/prometheus/scrape/scrape.go
vendor/github.com/prometheus/prometheus/scrape/target.go
vendor/github.com/prometheus/prometheus/storage/buffer.go
vendor/github.com/prometheus/prometheus/storage/merge.go
vendor/github.com/prometheus/prometheus/storage/remote/azuread/azuread.go
vendor/github.com/prometheus/prometheus/storage/remote/read_handler.go
vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
vendor/github.com/prometheus/prometheus/template/template.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go
vendor/github.com/prometheus/prometheus/tsdb/errors/errors.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/github.com/prometheus/prometheus/tsdb/symbols_batch.go
vendor/github.com/prometheus/prometheus/tsdb/wal.go
vendor/github.com/prometheus/prometheus/tsdb/wlog/wlog.go
vendor/github.com/prometheus/prometheus/util/annotations/annotations.go
vendor/github.com/prometheus/prometheus/web/api/v1/api.go
vendor/modules.txt

like https://github.com/grafana/mimir/pull/6529 but for r262
This includes the fix for the ring buffer whcih causes panics in the queriers https://github.com/grafana/mimir-prometheus/commit/4696b46dd (https://github.com/prometheus/prometheus/commit/4696b46dd)

r262: Update mimir-prometheus to 5f9db04c2d53

---

development/mimir-microservices-mode/config/grafana-agent.yaml
development/mimir-microservices-mode/docker-compose.jsonnet
development/mimir-microservices-mode/docker-compose.yml
development/mimir-monolithic-mode-with-swift-storage/config/grafana-agent.yaml
development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
development/mimir-monolithic-mode/config/grafana-agent.yaml
development/mimir-monolithic-mode/docker-compose.yml
development/mimir-read-write-mode/config/grafana-agent.yaml
development/mimir-read-write-mode/docker-compose.jsonnet
development/mimir-read-write-mode/docker-compose.yml

This pull request addresses configuration adjustments in the Grafana Agent. It's essential to update the development configuration to ensure the seamless startup of the agent. Committing my local changes to save time for others.
See related [ticket](https://github.com/grafana/agent/issues/1935) about the config

Chore: Update agent version and config in development

---

tools/grpcurl-query-ingesters/README.md
tools/grpcurl-query-ingesters/download-chunks-from-ingesters-query.json
tools/grpcurl-query-ingesters/download-chunks-from-ingesters.sh
tools/grpcurl-query-ingesters/main.go
tools/grpcurl-query-ingesters/response.go

Adding a simple hacky script + tool to download chunks from ingesters and dump them. It's a tool I've just written as part of an incident I was investigating.
N/A

Add tooling to easily download chunks from ingesters and parse it

---

docs/sources/mimir/manage/mimir-runbooks/_index.md

Fix runbook typos

---

Makefile

I propose to add `markblocks` tool to the list of tools for which we release the binary. It's a tool that may be useful for OSS community and GEM customers when dealing with corrupted blocks or compactor issues.
N/A

Release markblocks tool

---

tools/wal-reader/main.go

This fixes wal-reader: it will now replay very first segment, if there's no checkpoint.

wal-reader: load first segment if there's no checkpoint

---

CHANGELOG.md
docs/sources/mimir/configure/about-versioning.md

Follow-up to #6536. This adds the new endpoint to the list of experimental features.
Fixes n/a

Add active series API endpoint to list of experimental features

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

This is a copy of https://github.com/grafana/mimir/pull/6427, but with versions updated to 2.10.4 for both Mimir and GEM.

Helm release 5.1.3

---

CHANGELOG.md
docs/sources/mimir/configure/about-versioning.md

Merge mimir-distributed-5.1 branch (`mimir-distributed-5.1.3` tag) into `main`.
To be merged, not squashed.

Merge mimir-distributed-5.1.3 into main.

---

docs/sources/mimir/configure/about-anonymous-usage-statistics-reporting.md
docs/sources/mimir/configure/about-configurations.md
docs/sources/mimir/configure/about-dns-service-discovery.md
docs/sources/mimir/configure/about-ip-address-logging.md
docs/sources/mimir/configure/about-runtime-configuration.md
docs/sources/mimir/configure/about-tenant-ids.md
docs/sources/mimir/configure/about-versioning.md

Fix https://github.com/grafana/mimir/issues/4486.

Docs: Remove "About" from menuTitle for TOC

---

.github/pull_request_template.md

We continuously forget to update that file with the experimental features, hopefully this will help.
Also added periods after each list item.
N/A

Add `about-versioning.md` update to PR template

---

CHANGELOG.md

Fix changelog.
Followup to #6673 
- N/A [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

Fix changelog, flag not removed

---

docs/sources/mimir/configure/configure-native-histograms-ingestion.md

Two sentences ended up back to back.

docs: missed newline

---

CHANGELOG.md

This PR updates CHANGELOG.md in preparation for release 2.11.

Prepare release 2.11.0-rc.0 CHANGELOG.md

---

operations/mimir/distributor.libsonnet

In this PR I'm just doing a small jsonnet refactoring, introducing `newDistributorDeployment()` utility to create distributor deployment. Plan is to use it at Grafana Labs when experimenting with multi-AZ deployment for distributors too.
N/A

Jsonnet: add newDistributorDeployment() utility

---

renovate.json

Fix syntax error in `renovate.json`.
Fixes https://github.com/grafana/mimir/issues/6806

Fix syntax error in renovate.json

---

pkg/ingester/owned_series_test.go

This PR fixes flaky ring tests: when ring is updated, previously we simply waited 100ms to "make sure" that change was propagated to ring watcher. Now we monitor if ring watcher has actually received the value.

Fix flaky ring tests

---

pkg/frontend/querymiddleware/results_cache.go

Update docs on CacheKeyGenerator

---

CHANGELOG.md
cmd/metaconvert/Dockerfile
cmd/mimir-continuous-test/Dockerfile
cmd/mimir/Dockerfile
cmd/mimirtool/Dockerfile
cmd/query-tee/Dockerfile
development/mimir-microservices-mode/dev.dockerfile
development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
development/mimir-monolithic-mode/dev.dockerfile
development/mimir-read-write-mode/dev.dockerfile

This addresses [CVE-2023-5363](https://nvd.nist.gov/vuln/detail/CVE-2023-5363)

[2.9] update alpine to 3.18.5

---

CHANGELOG.md
docs/sources/mimir/release-notes/v2.9.md

[release-2.9] Update 2.9 changelog and release notes

---

pkg/distributor/distributor.go

I spotted this while reviewing another PR and wanted to knock off of the 94 lines this function already is

Distributor: simplify context propagation

---

pkg/querier/worker/scheduler_processor.go

A trivial PR to fix a typo in a error log message.
N/A

Fix typo in log message

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.1.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Release CVE fix for memcached-exporter

Helm: release 5.1.4

---

renovate.json

As prep for the 2.11 release, we're bumping the versions in the `renovate.json` file.

Adjust renovate.json for 2.11 release

---

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-slow-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
operations/mimir-mixin/dashboards/slow-queries.libsonnet

slow queries dashboard: rename loki_datasource

---

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
operations/mimir-mixin-compiled/dashboards/mimir-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-writes.json
operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
operations/mimir-mixin/dashboards/reads.libsonnet

mixin: make autoscaling dashboards ignore multiple series from keda metrics

---

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-slow-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
operations/mimir-mixin/dashboards/dashboard-utils.libsonnet

The change in #7028 didn't update the graph panels.

Slow queries dashboard: Fix loki datasource variable name

---

CHANGELOG.md
pkg/storegateway/bucket.go
pkg/storegateway/bucket_index_postings.go
pkg/storegateway/bucket_index_reader.go
pkg/storegateway/bucket_test.go
pkg/storegateway/indexheader/header.go
pkg/storegateway/indexheader/header_test.go
pkg/storegateway/indexheader/lazy_binary_reader.go
pkg/storegateway/indexheader/lazy_binary_reader_test.go
pkg/storegateway/indexheader/reader_benchmarks_test.go
pkg/storegateway/indexheader/reader_pool.go
pkg/storegateway/indexheader/reader_pool_test.go
pkg/storegateway/indexheader/stream_binary_reader.go
pkg/storegateway/series_refs.go

This PR reverts the merge of #6922. 
Some concerns were raised about the approach of #6922 [after it was merged](https://github.com/grafana/mimir/pull/6922#pullrequestreview-1781498012).
(none)

Revert #6922

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

This prepares the changelog for the next Helm release.

Prepare CHANGELOG.md for next helm release

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.2.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl
operations/helm/charts/mimir-distributed/values.yaml

This prepares the release of Helm chart version `5.2.0-rc.0`.

Helm chart release 5.2.0-rc.0

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md

This prepares the release of Helm chart version 5.2.0.

Helm chart release 5.2.0

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.2.md
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/README.md.gotmpl

In this PR I'm merging the mimir-distributed-release-5.2 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge mimir-distributed-release-5.2 to main

---

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet

fixes mistake here https://github.com/grafana/mimir/pull/7163#pullrequestreview-1830812299

mimir ruler reads dashboard query scheduler row - fix job matchers

---

CHANGELOG.md

The PR rephrases mentioning of the new `s3.sts-endpoint` configuration in the changelog, to be more concrete.
Relates to #6990 #6172

Changelog: rephrase the changes related to STS endpoint configuration

---

CHANGELOG.md

This pull request fixes a missing pull request number from the CHANGELOG.

Fix missing PR number from CHANGELOG.md

---

tools/add-license/.gitignore
tools/compaction-planner/.gitignore
tools/config-inspector/.gitignore
tools/copyblocks/.gitignore
tools/copyprefix/.gitignore
tools/delete-objects/.gitignore
tools/doc-generator/.gitignore
tools/grpcurl-query-ingesters/.gitignore
tools/list-deduplicated-blocks/.gitignore
tools/listblocks/.gitignore
tools/markblocks/.gitignore
tools/pre-pull-images/.gitignore
tools/query-step-alignment-analysis/.gitignore
tools/tenant-injector/.gitignore
tools/tsdb-chunks/.gitignore
tools/tsdb-compact/.gitignore
tools/tsdb-index-health/.gitignore
tools/tsdb-index-toc/.gitignore
tools/tsdb-labels/.gitignore
tools/tsdb-print-chunk/.gitignore
tools/tsdb-series/.gitignore
tools/tsdb-symbols/.gitignore
tools/ulidtime/.gitignore
tools/undelete-blocks/.gitignore
tools/wal-reader/.gitignore

Add gitignore files for mimir tools, so that locally built binaries don't get in the way of git.

Add gitignore files for mimir tools

---

pkg/querier/stats/query_metrics.go

Changes the way query metrics are named to make them easier to search for.
N/A

Name query metrics for easier discovery

---

CODEOWNERS

My technical writing skills might not be as strong as a writer but I know all the style rules and a _little_ bit about the project :wink:

Become temporary maintainer of docs until another technical writer is found

---

CHANGELOG.md

Clean up a few changelog entries

---

pkg/mimir/mimir.go
pkg/storage/tsdb/config.go
pkg/storage/tsdb/config_test.go

Remove unused logger argument passed to config validation methods.
N/A

Remove unused logger argument

---

CODEOWNERS

I don't believe they require the editing provided by a technical writer.

Remove docs writer from maintaining proposals

---

CHANGELOG.md

Add changelog entry for 7487

---

CHANGELOG.md

Prepare Release 2.12-rc.0 CHANGELOG.md

---

pkg/querier/block_streaming_test.go

The flaky test is caused by closing of the stream and receiving the error happening asynchronously. The error is received here on `s.errorChan`
https://github.com/grafana/mimir/blob/18c9df304a7f44894ad3ea390dc6e6d3286d2f1f/pkg/querier/block_streaming.go#L357-L359
But closing the sender happens in a goroutine started by `StartBuffering()`
https://github.com/grafana/mimir/blob/18c9df304a7f44894ad3ea390dc6e6d3286d2f1f/pkg/querier/block_streaming.go#L176-L192
other places in the test which assert on `mockClient.closed.Load()` use the same polling mechanism
Fixes https://github.com/grafana/mimir/issues/7545
- [n/a] …

querier: fix TestStoreGatewayStreamReader_ReceivedMoreSeriesThanExpected

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_append.go
vendor/modules.txt

Vendor mimir-prometheus to bring in changes from https://github.com/grafana/mimir-prometheus/pull/606.
Relates to https://github.com/grafana/mimir-squad/issues/1936

Vendor mimir-prometheus

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.2.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/ci/test-enterprise-configmap-values.yaml
operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/admin-cache/admin-cache-pdb.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/admin-cache/admin-cache-statefulset.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/admin-cache/admin-cache-svc-headless.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/chunks-cache/chunks-cache-pdb.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/chunks-cache/chunks-cache-statefulset.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/chunks-cache/chunks-cache-svc-headless.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/index-cache/index-cache-pdb.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/index-cache/index-cache-statefulset.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/index-cache/index-cache-svc-headless.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/metadata-cache/metadata-cache-pdb.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/metadata-cache/metadata-cache-statefulset.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/metadata-cache/metadata-cache-svc-headless.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/mimir-config.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/results-cache/results-cache-pdb.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/results-cache/results-cache-statefulset.yaml
operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/results-cache/results-cache-svc-headless.yaml

Manually backporting #7632 to Helm 5.2 and releasing 5.2.3

Helm 5.2.3 release

---

docs/sources/mimir/release-notes/v2.1.md
docs/sources/mimir/release-notes/v2.12.md
operations/helm/charts/mimir-distributed/values.yaml

chore: remove repetitive words

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/configure/configuration-parameters/index.md
docs/sources/mimir/release-notes/v2.12.md
pkg/querier/querier.go

This PR is a cherry-pick of https://github.com/grafana/mimir/pull/7638 into the `release-2.12` branch.
Part of #7542

Move -querier.minimize-ingester-requests from experimental to advanced

---

CHANGELOG.md
pkg/mimir/modules.go

Don't panic on nil query-frontend service when using downstream-url

---

CHANGELOG.md
docs/sources/mimir/set-up/jsonnet/deploy.md
operations/mimir-tests/build.sh
operations/mimir/getting-started.sh
pkg/frontend/transport/handler.go

This backports #7654 to `r279`.
Also included a backport of #7544 to make CI work.

[query-frontend] Close response body in request handler (#7654)

---

CHANGELOG.md

In this PR I'm merging the release-2.12 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.
Part of #7542

Merge release-2.12 to main

---

docs/sources/mimir/configure/configure-custom-trackers.md

Fix a couple of typos in docs/sources/mimir/configure/configure-custom-trackers.md.

Docs: Fix typos in configure-custom-trackers.md

---

tools/querytee/proxy.go
tools/querytee/proxy_backend.go
tools/querytee/proxy_backend_test.go
tools/querytee/proxy_endpoint.go
tools/querytee/proxy_endpoint_test.go

Use an interface for ProxyBackend and mock it out to make tests
deterministic.
Fixes: #7688

querytee: Fix flaky unit test

---

pkg/storage/ingest/reader.go
pkg/storage/ingest/reader_test.go

In https://github.com/grafana/mimir/pull/7695 I've added `cortex_ingest_storage_reader_last_committed_offset` metric. In this PR I'm proposing to also add `cortex_ingest_storage_reader_last_consumed_offset` metric, so that we have the full picture about a partition offsets from the reader perspective.
N/A

Add cortex_ingest_storage_reader_last_consumed_offset metric

---

pkg/mimir/modules.go

Move initialization of `QueryFrontendCodec` into separate module, so that GEM can initialize its modules in correct order.

Query-frontend-codec initialization

---

pkg/storage/ingest/reader.go
pkg/storage/ingest/reader_test.go

In https://github.com/grafana/mimir/pull/7701 I've added `cortex_ingest_storage_reader_last_consumed_offset` metric. This metric was expected to be initialized to -1 until the first record is consumed (similarly to `cortex_ingest_storage_reader_last_committed_offset`), but I missed it. In this PR I'm fixing it.
N/A

Fix cortex_ingest_storage_reader_last_consumed_offset metric initialization

---

pkg/distributor/distributor.go

We follow a simple logic: if we don't call next(), we should call pushReq.Cleanup(). However, there's nothing in the code ensuring that, which leads to bugs and fixes like:
- https://github.com/grafana/mimir/pull/7176
- https://github.com/grafana/mimir/pull/7755
A simple way to prevent that is to couple the `cleanupInDefer = false` to the `next()` call, and this does exactly that.
Note that `nextOrCleanup` is introduced just for convenience, and it's inlined.
Fixes future issues.

Make distributor's pushReq.Cleanup() calls safer

---

renovate.json

Update renovate.json to only maintain the last two minor releases
https://github.com/grafana/mimir/issues/7542

Update renovate.json to only maintain last two minor versions

---

CHANGELOG.md

Sneaky individual character addition to CHANGELOG

---

docs/sources/mimir/manage/mimir-runbooks/_index.md

The PR updates `mimir-runbook`, fixing a couple of typos in across the text.

Fix typos in text of mimir-runbook

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md

Helm: update release notes

---

pkg/streamingpromql/operator/aggregation.go

Addresses https://github.com/grafana/mimir/pull/7693#discussion_r1557064495
https://github.com/grafana/mimir/pull/7693

Add comment about potential hash collisions in streaming PromQL engine

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Last step of release process
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/RELEASE.md
**Use merge commit to merge!**

Merge mimir distributed release 5.3 to main

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Done manually to pin the continuous-test version .
N/A
N/A

Release mimir-distributed Helm chart 5.4.0-weekly.285

---

CHANGELOG.md

Changelog update for continuous test to account for change in flags

---

cmd/mimir-continuous-test/main.go
pkg/continuoustest/manager.go
pkg/continuoustest/manager_test.go
pkg/mimir/mimir.go

Fixes module not exiting on smoke-tests run [discussed here](https://github.com/grafana/mimir/pull/7869#discussion_r1562643103).

Stop module after smokes

---

pkg/ruler/api_test.go

This change moves an assertion on ruler API metrics to _before_ a mutation via the API has happened so that it doesn't depend on how fast change notifications are processed by the ruler sync logic.
Fixes #5660

Fix ruler API metric assertion flake

---

pkg/mimirpb/timeseries.go

See: https://github.com/grafana/mimir/pull/7935
N/A

Do not recycle Exemplars slices with a capacity > 10 (#7935)

---

.github/workflows/test-docs.yml
docs/docs.mk

Avoid `ERROR [en] REF_NOT_FOUND: Ref` errors.

pin docs image to avoid CI errors until fix in latest

---

.github/workflows/test-docs.yml
docs/docs.mk

Reverts grafana/mimir#7942
docs-base:latest should be fixed

Revert "pin docs image to avoid CI errors until fix in latest"

---

pkg/storage/ingest/reader.go

It might be helpful to have critical parts of the ingest-storage's strong consistency enforcement logged on the ingester's spans. This will show a better picture for where the end-to-end latency of such requests was spent.

storage/ingest: log tracing events while enforcing strong consistency

---

pkg/frontend/querymiddleware/codec.go

VS Code shows this as the only problem in the codebase.
Line was made redundant in #7536.
N/A

frontend: Remove impossible condition

---

pkg/alertmanager/alertmanager.go
pkg/ruler/remotequerier.go
pkg/storage/tsdb/block/block_generator.go

Correct some error handling reported at https://github.com/grafana/mimir/issues/7954.
Fixes #7954

Correct some error handling

---

docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md

Just a minor fix (or improvement) on the key names in an example shown in Monitor Health Section

fix(docs): Typo in Monitor System Health section

---

pkg/ingester/owned_series_test.go

follow-up on https://github.com/grafana/mimir/pull/8049#discussion_r1589425007

Add comment to TestOwnedSeriesIngesterRingStrategyRingChanged

---

docs/sources/mimir/references/http-api/index.md

This adds API documentation for the `/active_series` endpoint.
n/a

Add API docs for `api/v1/cardinality/active_series`

---

pkg/compactor/block_upload.go

Fixes a linter complaint I encountered while working on something else.
```
[{
"resource": "/Users/davidgrant/dev/mimir/pkg/compactor/block_upload.go",
"owner": "_generated_diagnostic_collection_name_#2",
"code": {
"value": "cond",
"target": {
"$mid": 1,
"path": "/golang.org/x/tools/go/analysis/passes/nilness",
"scheme": "https",
"authority": "pkg.go.dev",
"fragment": "cond"
}
},
"severity": 4,
"message": "impossible condition: nil != nil",
"source": "nilness",
"startLineNumber": 681,
"startColumn": 9,
"endLineNumber": 681,
"endColumn": 9
}]
```

Fix linter complaint in Compactor

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/promql/parser/printer.go
vendor/modules.txt

This includes the fix from https://github.com/prometheus/prometheus/pull/14015

Update mimir-prometheus to prometheus#14015

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/model/labels/regexp.go
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/timeseries.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/bstream.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/chunk.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go
vendor/modules.txt

Upgrade to latest mimir-prometheus. Relevant changes:
* [Fix FastRegexMatcher matching multibyte runes with dot matcher .](https://github.com/prometheus/prometheus/pull/14059)

Upgrade to latest mimir-prometheus

---

go.mod
go.sum
pkg/ingester/ingester_test.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

Backport of https://github.com/grafana/mimir/pull/8124
See https://github.com/grafana/mimir-prometheus/pull/633

r285: Update Prometheus to respect context cancellation

---

go.mod
go.sum
pkg/ingester/ingester_test.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

r286: Update Prometheus to respect context cancellation

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

r287: Update Prometheus to respect context cancellation

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/tsdb/index/index.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

r290: Update Prometheus to respect context cancellation

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

r288: Update Prometheus to respect context cancellation

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

r289: Update Prometheus to respect context cancellation

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/model/labels/matcher.go
vendor/github.com/prometheus/prometheus/model/relabel/relabel.go
vendor/github.com/prometheus/prometheus/tsdb/index/index.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/github.com/prometheus/prometheus/util/testutil/context.go
vendor/modules.txt

https://github.com/grafana/mimir-prometheus/commit/e5b85c151ba88cb148ca7257d88a6d9c5a34d202
Relevant PRs:
https://github.com/prometheus/prometheus/pull/14103
https://github.com/prometheus/prometheus/pull/14096
https://github.com/prometheus/prometheus/pull/14068
https://github.com/prometheus/prometheus/pull/13669

Update mimir-prometheus at e5b85c151ba8

---

go.mod
go.sum
pkg/api/handlers.go
vendor/github.com/grafana/dskit/middleware/grpc_stats.go
vendor/github.com/grafana/dskit/middleware/http_tracing.go
vendor/github.com/grafana/dskit/middleware/instrument.go
vendor/github.com/grafana/dskit/middleware/route_injector.go
vendor/github.com/grafana/dskit/server/server.go
vendor/modules.txt

This PR upgrades dskit to bring in https://github.com/grafana/dskit/pull/527.
(none)

Upgrade dskit

---

pkg/frontend/v1/frontend.go
pkg/scheduler/queue/queue.go
pkg/scheduler/queue/queue_test.go
pkg/scheduler/scheduler.go

just naming of types in `queue.go` and the associated docstrings

request queue naming and docstrings

---

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-resources.json
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin-compiled/dashboards/mimir-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json
operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
operations/mimir-mixin/dashboards/queries.libsonnet
operations/mimir-mixin/dashboards/rollout-progress.libsonnet
operations/mimir-mixin/dashboards/tenants.libsonnet
operations/mimir-mixin/dashboards/writes-resources.libsonnet

Before
After
This PR also adds a utility to make this easier. I decided to not add a changelog entry because this is too minor of a change.

mixin: add tooltip with all series on Queries dashboard

---

pkg/storage/ingest/reader.go

Follow-up on https://github.com/grafana/mimir/pull/8176#discussion_r1618514068

ingest storage: clarify metrics for batch fetching & processing

---

docs/sources/mimir/manage/mimir-runbooks/_index.md

The query was using cortex_distributor_replication_factor. This metric isn't emitted with ingest storage.
The 200K after replication threshold was fairly arbitrary, so I switched with another round number in the same ballpark - 70K before replication (assuming replication factor of 3).
I ran the two queries side-by-side for one namespace and they both return the same values. See screenshot

runbooks: update query in MimirIngesterReachingSeriesLimit

---

docs/sources/mimir/manage/mimir-runbooks/_index.md

This PR improves the docs for some of the query limit errors.
In particular, it clarifies which options are configured globally for all tenants and which are available in runtime configuration.
(none)

Clarify documentation for query limit errors

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/grafana/regexp/syntax/parse.go
vendor/modules.txt

Bring in https://github.com/grafana/regexp/pull/13

Update regexp library with bugfix

---

docs/internal/contributing/how-integration-tests-work.md

Minor syntactic fix in documentation.
None

Correct minor typo error

---

pkg/blockbuilder/blockbuilder.go

There are a couple of small ones here:
1. Fix an issue with handling the rebalancing after the final record consumed for a partition's cycle
That is, as we use `kgo.BlockRebalanceOnPoll` and manually manage the partition, the client polls, the consumer group should trigger the `kgo.Client.AllowRebalance` between the calls to poll.
2. Resolve some of the TODOs (and added more) to the `blockbuilder` package.
2. Added a note on the `allSamplesProcessed`

blockbuilder: don't block rebalance after consuming last record in partition's cycle

---

cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/configuration-parameters/index.md
go.mod
go.sum
pkg/alertmanager/multitenant.go
pkg/util/validation/limits.go
vendor/github.com/prometheus/alertmanager/silence/silence.go
vendor/modules.txt

This pull request backports #8249 to r293.

Backport #8249 to r293

---

CHANGELOG.md
operations/mimir-tests/test-automated-downscale-generated.yaml
operations/mimir-tests/test-compactor-concurrent-rollout-generated.yaml
operations/mimir-tests/test-consul-multi-zone-generated.yaml
operations/mimir-tests/test-deployment-mode-migration-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-0-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-5-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
operations/mimir-tests/test-multi-zone-generated.yaml
operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
operations/mimir-tests/test-multi-zone-with-store-gateway-automated-downscaling-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-caches-disabled-generated.yaml
operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
operations/mimir/rollout-operator.libsonnet

Adds zone-tracker usage whenever rollout-operator is in use.

Zone tracker operations addition

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Updates mimir-promteheus to bring changes from:
- https://github.com/prometheus/prometheus/pull/13286
- https://github.com/prometheus/prometheus/pull/14286

[r292] Update to mimir-prometheus w/ MemPostings locking improvements

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Updates mimir-promteheus to bring changes from:
- https://github.com/prometheus/prometheus/pull/13286
- https://github.com/prometheus/prometheus/pull/14286

[r293] Update to mimir-prometheus w/ MemPostings locking improvements

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Updates mimir-promteheus to bring changes from:
- https://github.com/prometheus/prometheus/pull/13286
- https://github.com/prometheus/prometheus/pull/14286

[r294] Update to mimir-prometheus w/ MemPostings locking improvements

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
vendor/modules.txt

Backporting https://github.com/grafana/mimir/pull/8337 to r294.
N/A

[r294] Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation fix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
vendor/modules.txt

Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation fix
N/A

[r291] Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation fix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
vendor/modules.txt

Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation fix.
N/A

[r292] Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation fix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
vendor/modules.txt

Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation and MemPostings fix.
N/A

[r290] Update to mimir-prometheus w/ PostingsForMatchersCache context cancellation and MemPostings fix

---

pkg/blockbuilder/blockbuilder.go

This PR comes with a couple of fixes to amend the refactoring #8329
1. Fix how we commit metadata, resolving what I mentioned in https://github.com/grafana/mimir/pull/8329/files#r1636250757
2. Fix a couple of typos in how we look up the partition's offset in the beginning of the cycle.

blockbuilder: fix metadata commit

---

CHANGELOG.md
go.mod
go.sum
pkg/distributor/otel.go
pkg/distributor/push.go
pkg/distributor/push_test.go
vendor/github.com/grafana/dskit/httpgrpc/httpgrpc.go
vendor/github.com/grafana/dskit/httpgrpc/server/server.go
vendor/modules.txt

What this PR does
This PR cherry-picks PR https://github.com/grafana/mimir/pull/8363 to r294 branch.
Cherry-pick was done manually, since there are incompatible changes on main.

Cherry-pick #8363 to r294

---

CHANGELOG.md
docs/sources/mimir/configure/about-ip-address-logging.md

Add missing bits of documentation about server.log-source-ips-full configuration parameter.

docs: Document option server.log-source-ips-full

---

CHANGELOG.md
go.mod
go.sum
pkg/storage/tsdb/block/index.go
vendor/github.com/prometheus/common/helpers/templates/time.go
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/model/labels/regexp.go
vendor/github.com/prometheus/prometheus/template/template.go
vendor/github.com/prometheus/prometheus/tsdb/block.go
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/index/index.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/github.com/prometheus/prometheus/web/api/v1/api.go
vendor/modules.txt

Updates to https://github.com/grafana/mimir-prometheus/pull/651

Update mimir-prometheus to 26c8bac

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/querier/tenantfederation/tenant_federation.go
pkg/util/validation/limits.go

cherry picked from commit 69c0f88d9174465d690e10d92552a7d9afa3cac2 #8400

[r295] Promote experimental features to stable

---

CODEOWNERS

Replaces my temporary ownership of the docs with the Technical Writer for metrics @tacole02.
They will also review GEM and Grafana Cloud Metrics PRs in other repositories.

Add Taylor as Metrics technical writer

---

pkg/alertmanager/multitenant_test.go

`TestMultitenantAlertmanager_zoneAwareSharding` is flaky (see [this issue](https://github.com/grafana/mimir/issues/3517)). One way I've found to reproduce it is introducing a sleep in the ring client async update look. Essentially, the ring client is updated asynchronously, so once the 2nd and 3rd instances are started, there's no guarantee that the 1st instance has updated the ring client view (even if it's very very unlikely because we use the in-memory consul mock in tests and the update is very quick). If that happens, then the 1st instance will sync alertmanager tenants using a stale view of the ring, causing the flaky test.
Despite this is a real issue, the reason why I'm not sure 💯 sure this fix the flaky test is because it's very very unlikely to happen. To reproduce it, I had to …

Maybe fix TestMultitenantAlertmanager_zoneAwareSharding flakyness

---

pkg/alertmanager/alertstore/bucketclient/bucket_client.go
pkg/alertmanager/alertstore/store_test.go

Alertmanager: Fix listing users when Grafana configurations are present.

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

helm: cut changelog for 5.4.0-rc.0

---

docs/sources/helm-charts/mimir-distributed/_index.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

This doesn't update the GEM version because we don't have an RC for GEM yet.
Also, the docs for 2.13.0 are not published, so pointing to next are the closest docs we have
Related to https://github.com/grafana/mimir/issues/8390

helm: release mimir-distributed 5.4.0-rc.0

---

docs/sources/mimir/set-up/migrate/migrate-from-thanos-or-prometheus.md

Improves the documentation readability and tone per comments mentioned in #7960

[ENHANCEMENT] Improve documents readability

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md

This includes a fix for nginx config in the gateway section (#8499)

helm 5.4.0: release candidate 1

---

pkg/distributor/ha_tracker.go

I was reading through this code today and decided to clean up the comments a bit, fixing some typos and making minor edits.
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.

Edit HA tracker comments for correctness and style

---

integration/querier_remote_read_test.go

@dimitarvdimitrov reported me that `TestQuerierStreamingRemoteRead` is flaky after recent changes. I reproduce it locally. The problem is that TSDB chunks cutting is based on a estimation, the estimation is computed based on samples timestamp, and due to rounding the chunks may be cut at slightly different times. The easiest way to fix flakyness is by simply running the test always with the same mocked time, which is what I'm doing in this PR.
N/A

Fix TestQuerierStreamingRemoteRead flakyness

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

This includes an updated image for Mimir (see #8539)

helm: release 5.4.0-rc.2

---

RELEASE.md

This is currently manual and is not included into any regular process. The Mimir release is a good candidate for a trigger for it.

release process: include instructions for updating cloud onboarding integration

---

docs/sources/mimir/references/architecture/components/alertmanager.md

Fixes a small mistake where `origin=api` shouldn't be in the example.

Fix example in docs

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

This includes an updated image for Mimir (see https://github.com/grafana/mimir/pull/8612)

helm: release 5.4.0-rc.3

---

docs/sources/mimir/release-notes/v2.12.md

Fixes a broken link in the v2.12 release notes.

Fix links in v2.12 release notes

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.4.md

This is a draft PR with release notes. I structured them from the highlights in the [changelog](https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed/CHANGELOG.md).
I tried to only keep the major features or potentially breaking changes. The release is light in changes, so I think that left the release notes brief. Open to feedback on including changes or excluding some.

helm 5.4.0: add release notes

---

tools/grpcurl-query-ingesters/README.md
tools/grpcurl-query-ingesters/download-chunks-from-ingesters.sh

I tried running this and ran into a few issues.

grpcurl-query-ingesters: update docs and import paths

---

CHANGELOG.md
packaging/nfpm/mimir/mimir.service

#8555 was merged, but there was one [unresolved comment](https://github.com/grafana/mimir/pull/8555/files#r1658851555) on which I think we had agreement. I'm carrying out the change here.
related to https://github.com/grafana/mimir/issues/8220

nfpm: increase TimeoutStartSec to 20min

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/_helpers.tpl
operations/helm/charts/mimir-distributed/templates/metamonitoring/grafana-agent.yaml
operations/helm/charts/mimir-distributed/values.yaml
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-agent.yaml

Add the following configs from the https://github.com/grafana/agent/blob/main/docs/sources/operator/api.md#grafanaagent-
- imagePullSecrets
- nodeSelector
- tolerations
- topologySpreadConstraints

Add support for imagePullSecrets, nodeSelector, tolerations and topologySpreadConstraints into helm chart

---

pkg/blockbuilder/blockbuilder.go

Temporary (or not) fix for the OOMs before we add an option to start consuming at the end (non-trivial because partitions can get rebalanced anytime). We might still have use of this config even when we have an option to start consuming at the end.

Add a lookback config when block builder finds no kafka commit

---

pkg/blockbuilder/tsdb.go

This one is a simple clean-up in the comments in `tsdb`. Nothing to review, really.

blockbuilder: clean up tsdb comments

---

docs/sources/helm-charts/mimir-distributed/_index.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

helm 5.4.0: cut final release

---

docs/sources/helm-charts/mimir-distributed/_index.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

In this PR I'm merging the mimir-distributed-release-5.4 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge mimir-distributed-release-5.4 to main

---

CHANGELOG.md
development/mimir-microservices-mode/config/mimir.yaml

Remove align_queries_with_step from Docker compose config

---

docs/sources/mimir/get-started/play-with-grafana-mimir/index.md

Modify some words in index.md for play-with-grafana-mimir docs
None

Modify play-with-grafana-mimir document

---

docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
docs/sources/mimir/get-started/_index.md

Mimir docs : enhance Alloy config in get started for Mimir. Also align with the prometheus config. Tested locally.
Related to #8489 

docs: enhance Alloy config in get started for Mimir

---

pkg/scheduler/queue/queue.go

Manual backport from #8794 
(cherry picked from commit c6c9f54dd9fae9461f6676cef0d0d54d16686595)

[r296] Remove `ItemCount` call from trySendNextRequestForQuerier (#8794)

---

pkg/scheduler/queue/queue.go

Manual backport of #8794 
(cherry picked from commit c6c9f54dd9fae9461f6676cef0d0d54d16686595)

[r295] Remove `ItemCount` call from trySendNextRequestForQuerier (#8794)

---

pkg/scheduler/queue/queue.go

Manual backport of #8794 
(cherry picked from commit c6c9f54dd9fae9461f6676cef0d0d54d16686595)

[r297] Remove `ItemCount` call from trySendNextRequestForQuerier (#8794)

---

tools/querytee/response_comparator_test.go

This PR addresses the post-merge feedback on https://github.com/grafana/mimir/pull/8749, specifically https://github.com/grafana/mimir/pull/8749#discussion_r1680609615.
(none)

Address post-merge feedback on #8749

---

RELEASE.md
operations/helm/charts/mimir-distributed/RELEASE.md
tools/release/create-pr-to-merge-release-branch-to-main.sh
tools/release/notify-changelog-cut.sh

Some rough edges that I encountered while doing https://github.com/grafana/mimir/issues/8390. This is mostly concerned with the helm release

release: update instructions

---

pkg/blockbuilder/blockbuilder.go
pkg/blockbuilder/blockbuilder_test.go

As we discussed in DM, this PR updates the #8823 getting rid of a separate `groupClient`. Having multiple kafka clients per instance adds unnecessary pressure to the broker, as the (group) client has to poll for the metadata and do the rebalance. 
Also, relying on lag of the group becomes trickier, because `kadm.Client.Lag` only returns the lag for the live group-members. That means, the consuming cycle, where we calculate the lag, has to take into account the group client's liveness, and readiness. Otherwise, the calls to lag calculation may return unexpected results.

blockbuilder: get rid of groupConsumer

---

pkg/streamingpromql/engine_test.go

This PR makes some changes I made while investigating https://github.com/grafana/mimir/issues/8889 permanent. 
In particular, it clarifies the assertions made in `TestRangeVectorSelectors`, adds some extra information to failure messages, and makes the expected `CounterResetHint` values explicit.
https://github.com/grafana/mimir/issues/8889

Clarify assertions in `TestRangeVectorSelectors`

---

CHANGELOG.md
go.mod
go.sum
pkg/streamingpromql/testdata/upstream/native_histograms.test
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/prompb/io/prometheus/write/v2/types.pb.go
vendor/github.com/prometheus/prometheus/prompb/io/prometheus/write/v2/types.proto
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/github.com/prometheus/prometheus/promql/promqltest/testdata/native_histograms.test
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/github.com/prometheus/prometheus/tsdb/wlog/watcher.go
vendor/modules.txt

This PR brings in the latest changes from https://github.com/grafana/mimir-prometheus/pull/669.
(none)

Upgrade Prometheus

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram_meta.go
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/modules.txt

prometheus/prometheus#14584
prometheus/prometheus#14598
Just in case someone syncs the other way and removes these.

r302: sync mimir-prometheus to GEM

---

CHANGELOG.md
tools/tsdb-series/main.go

This PR adds Json output to `tsdb-series` and also implements filtering of samples when computing per-series data-points per minute.

tsdb-series enhancements

---

pkg/frontend/v2/frontend_test.go

This one fixes flaky `TestFrontendStreamingResponse/context_cancelled_while_streaming_response` by making sure its testing goroutines are synchronized around cancelling of the streaming's context.
Fixes #8692

frontend/v2: fix flaky TestFrontendStreamingResponse

---

docs/sources/mimir/configure/configure-ingester-circuit-breakers.md

This PR adds a documentation on how to confugure ingester's circuit breakers.

Adding ingester circuit breaker documentation

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

This only updates the GEM version from 2.13.0 to 2.13.1

helm: release 5.4.1

---

docs/sources/helm-charts/mimir-distributed/_index.md

This PR fixes the missing link on https://grafana.com/docs/helm-charts/mimir-distributed/latest/.
N/A

Docs: fixes missing link

---

pkg/querier/worker/scheduler_processor.go

When working on strong consistency enforcement in the query-frontend I noticed that in `schedulerProcessor.createFrontendClient()` we setup gRPC instrumentation manually but it looks like identical to `grpcclient.Instrument()` (I can't see any difference).
N/A

Chore: use grpcclient.Instrument() in schedulerProcessor.createFrontendClient()

---

pkg/storage/ingest/util.go

We've discovered internally at GL with another user of franz-go that the tracing info can be a significant overhead for small records.
This shouldn't be the case for ingest storage, but to be on the safe side, I'm proposing this change now that we know it may be a problem.
While testing this internally I couldn't spot a significant change in the number of bytes transferred.

ingest storage: propagate only sampled traces

---

pkg/frontend/querymiddleware/astmapper/parallel_test.go

Fix error message in `pkg/frontend/querymiddleware/astmapper.TestFunctionsWithDefaultsIsUpToDate`, so it has the right formatting argument.

astmapper: Fix test error message

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_append.go
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/modules.txt

Update mimir-prometheus in r302 to revert https://github.com/prometheus/prometheus/pull/14525.
N/A

[weekly-r302] Cherry-pick TSDB Head series hash fix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_append.go
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/modules.txt

Update mimir-prometheus in r303 to revert https://github.com/prometheus/prometheus/pull/14525.
N/A

[weekly-r303] Cherry-pick TSDB Head series hash fix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_append.go
vendor/github.com/prometheus/prometheus/tsdb/head_read.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/modules.txt

Update mimir-prometheus in r304 to revert https://github.com/prometheus/prometheus/pull/14525.
N/A

[weekly-r304] Cherry-pick TSDB Head series hash fix

---

development/mimir-monolithic-mode/docker-compose.yml

development/mimir-monolithic-mode: update otel collector

---

pkg/querier/api/DESIGN.md

I've updated the DESIGN doc to explain how the strong read consistency works in the experimental ingest storage.
N/A

Document strong read consistency internals

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/configure/configuration-parameters/index.md
go.mod
go.sum
pkg/api/handlers.go
pkg/distributor/otel.go
pkg/distributor/otlp/helper_generated.go
pkg/distributor/otlp/metrics_to_prw_generated.go
pkg/distributor/otlp/number_data_points_generated.go
pkg/distributor/push_test.go
pkg/querier/error_translate_queryable_test.go
pkg/util/validation/limits.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
vendor/github.com/prometheus/prometheus/web/api/v1/api.go
vendor/modules.txt

Revert "[r306] OTLP: Convert start timestamps to Prom created timestamps"

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/frontend/v2/frontend.go
pkg/scheduler/scheduler.go

Removes a retired, non-operational flag

Remove additional-query-queue-dimensions-enabled flag

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

[Helm] Release 5.3.1

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/about-versioning.md
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/api/handlers.go
pkg/distributor/otel.go
pkg/distributor/push_test.go
pkg/util/validation/limits.go

In https://github.com/grafana/mimir/pull/9217 I forgot to add the flag that enabled the feature.

[weekly-r304] Created timestamp distributors flag

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/modules.txt

Fix panic in chunk querier with OOO.
https://github.com/grafana/mimir-prometheus/commit/78e8657d15de57967f90d328e04f5a4c56c1fbca is on main.

Vendor in Promtheus PR 14874 from mimir-promtheus at 78e8657d15de

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md

This brings in the release notes for the 5.3.1 patch.

Merge distributed release 5.3 to main

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md

This brings in the release notes for the 5.3.1 patch.

Merge distributed release 5.3 to distributed release 5.4

---

operations/mimir-rules-action/entrypoint.sh

I introduced a conditional check in https://github.com/grafana/mimir/pull/9244 that is incorrect. This PR fixes the change.

fix conditional in mimir-rules-action

---

development/tools/upload-block/README.md
development/tools/upload-block/upload-block.sh
tools/markblocks/main.go

This PR adds a script that will upload a block to a local development environment for testing and debugging.
(none)

Add tool to upload a block to local development environment

---

development/mimir-ingest-storage/config/mimir.yaml
development/mimir-microservices-mode/config/mimir.yaml

enable query-scheduler prioritize-query-components in dev env config

---

pkg/alertmanager/multitenant.go
pkg/alertmanager/multitenant_test.go

- Add grafana state size so we can implement proper limits

Alertmanager: Register grafana state size on sync

---

operations/helm/charts/mimir-distributed/templates/ruler-query-frontend/ruler-query-frontend-so.yaml

Fixes the smallest of typos in a scaledobject

fix a typo to make the scaledobject valid

---

operations/mimir/ingest-storage-ingester-autoscaling.libsonnet

Updates comments on ingester ScaledObject to match how HPA works. Previous comments were wrong. 

Update comments on ingester ScaledObject.

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/modules.txt

Includes this fix: https://github.com/grafana/mimir-prometheus/pull/700

Update mimir-prometheus in r307

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
vendor/modules.txt

Includes this fix: https://github.com/grafana/mimir-prometheus/pull/700

Update mimir-prometheus in r308

---

go.mod
go.sum
vendor/github.com/grafana/dskit/grpcclient/grpcclient.go
vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
vendor/modules.txt

Specifically pulls in https://github.com/grafana/dskit/pull/585
N/A

Update to latest commit of dskit main

---

go.mod
go.sum
vendor/github.com/prometheus/alertmanager/dispatch/dispatch.go
vendor/github.com/prometheus/alertmanager/notify/notify.go
vendor/github.com/prometheus/alertmanager/notify/webhook/webhook.go
vendor/github.com/prometheus/alertmanager/tracing/http.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/LICENSE
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/api.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/clienttrace.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/httptrace.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/gen.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/httpconv.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/internal/semconvutil/netconv.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace/version.go
vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go
vendor/modules.txt

This pulls in a small change to add tracing to webhooks.

Alertmanager: Update prometheus-alertmanager.

---

cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/scheduler/scheduler.go

Remove doc references to removed flag

---

CHANGELOG.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
operations/mimir-mixin-compiled/dashboards/mimir-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
operations/mimir-mixin-compiled/dashboards/mimir-writes.json
operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
operations/mimir-mixin/dashboards/reads.libsonnet

follow-up of #9412. who would have thought we have so many autoscaling queries

mixin: correct more autoscaling promQL joins

---

go.mod
go.sum
vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
vendor/github.com/grafana/dskit/ring/ring_status.gohtml
vendor/modules.txt

Update to dskit. Pulls in:
- https://github.com/grafana/dskit/pull/586
- https://github.com/grafana/dskit/pull/587

Update to latest dskit main

---

pkg/ingester/ingester_early_compaction_test.go

Add logs to `TestIngester_compactBlocksToReduceInMemorySeries_Concurrency` to have some clues to investigate why it's flaky.
Part of #5471

Add logs to TestIngester_compactBlocksToReduceInMemorySeries_Concurrency

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

helm: cut changelog for 5.5.0-rc.0

---

operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

~~_This one is waiting for GEM v2.14-rc.0 to be published._~~
Note: the docs for Mimir 2.14 aren't published yet. I've left the docs links as is, for now.

helm: release mimir-distributed 5.5.0-rc.0

---

pkg/storage/ingest/fetcher.go
pkg/storage/ingest/fetcher_test.go
pkg/storage/ingest/reader_test.go

Putting in this PR mostly so we collect explicit behaviour when particular errors happen and avoid the log lines `received an error we're not prepared to handle; this shouldn't happen; please report this as a bug`

kafka replay speed: handle more errors

---

CHANGELOG.md
pkg/streamingpromql/functions/rate_increase.go
pkg/streamingpromql/testdata/ours/native_histograms.test

https://github.com/grafana/mimir/pull/9518

Backport #9518 to r310

---

go.mod
go.sum
pkg/api/handlers.go
pkg/distributor/otlp/helper_generated.go
pkg/distributor/otlp/metrics_to_prw_generated.go
pkg/querier/error_translate_queryable_test.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
vendor/github.com/prometheus/prometheus/web/api/v1/api.go
vendor/modules.txt

Updating dependency to bring latest mimir-prometheus.
This brings:
- https://github.com/grafana/mimir-prometheus/pull/706

Update to latest mimir-prometheus

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.5.md

I wrote the notes based on 5.5.0-rc.0 changelog #9487. There aren't much of changes in the release and I tried to focus on those, that potentially affect the users.

helm: release notes for 5.5.0

---

CHANGELOG.md
pkg/streamingpromql/functions/rate_increase.go
pkg/streamingpromql/testdata/ours/functions.test
pkg/streamingpromql/testdata/upstream/name_label_dropping.test

This PR manually backports #9553 to r311.

Backport #9553 to r311

---

go.mod
go.sum
vendor/github.com/twmb/franz-go/pkg/kgo/compression.go
vendor/github.com/twmb/franz-go/pkg/kgo/config.go
vendor/github.com/twmb/franz-go/pkg/kgo/pool/bucketed_pool.go
vendor/github.com/twmb/franz-go/pkg/kgo/record_and_fetch.go
vendor/github.com/twmb/franz-go/pkg/kgo/source.go
vendor/modules.txt

update to latest https://github.com/grafana/franz-go/tree/v1.17.1 including:
* https://github.com/grafana/franz-go/pull/7
*  https://github.com/grafana/franz-go/pull/9

updated to latest `grafana/franz-go` fork

---

docs/sources/helm-charts/mimir-distributed/_index.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

This PR prepares Helm chart for the 5.5.0 release.
~~_Note it's still waiting for GEM v2.14.0 (scheduled earlier next week)_~~
Relates https://github.com/grafana/mimir/issues/9382

helm: Cut mimir-distributed release 5.5.0

---

docs/sources/helm-charts/mimir-distributed/_index.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

In this PR I'm merging the mimir-distributed-release-5.5 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.
Relates to https://github.com/grafana/mimir/issues/9382

Merge mimir-distributed-release-5.5 to main

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

This PR fixes the changelog by setting the correct memcached version and add the changelog for mimir 2.14.0

fix: add mimir upgrade in the changelog

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/modules.txt

Bring in https://github.com/grafana/mimir-prometheus/pull/717

[r312]Update mimir-prometheus with 'RANGEHEAD: not found' bugfix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/modules.txt

Bring in https://github.com/grafana/mimir-prometheus/pull/717

Update mimir-prometheus with 'RANGEHEAD: not found' bugfix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/modules.txt

pulls in grafana/mimir-prometheus#711

[r309] Cherry-pick prometheus#15120 to fix RANGEHEAD: not found

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/modules.txt

pulls in https://github.com/grafana/mimir-prometheus/pull/710

[r308] Cherry-pick prometheus#15120 to fix RANGEHEAD: not found

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/modules.txt

pulls in https://github.com/grafana/mimir-prometheus/pull/712

[r310] Cherry-pick prometheus#15120 to fix RANGEHEAD: not found

---

CHANGELOG.md
pkg/streamingpromql/benchmarks/benchmarks.go
pkg/streamingpromql/functions.go
pkg/streamingpromql/functions/common.go
pkg/streamingpromql/functions/common_test.go
pkg/streamingpromql/functions/math.go
pkg/streamingpromql/functions/native_histograms.go
pkg/streamingpromql/operators/function_over_instant_vector.go
pkg/streamingpromql/operators/function_over_instant_vector_test.go
pkg/streamingpromql/testdata/ours-only/native_histograms.test
pkg/streamingpromql/testdata/ours/functions.test
pkg/streamingpromql/testdata/ours/native_histograms.test
pkg/streamingpromql/testdata/upstream/functions.test
pkg/streamingpromql/testdata/upstream/name_label_dropping.test

MQE: Refactor functions over instant vectors to support scalar args and add clamp function

---

CHANGELOG.md
pkg/streamingpromql/functions.go
pkg/streamingpromql/functions/math.go
pkg/streamingpromql/testdata/ours-only/native_histograms.test
pkg/streamingpromql/testdata/ours/functions.test
pkg/streamingpromql/testdata/upstream/functions.test

MQE: Add support for clamp_min and clamp_max

---

operations/mimir-mixin/dashboards/tenants.libsonnet

We may want to render some extra panels when vendoring this in specific envs. This hook works just like the one introduced in #4886

Allow injecting more rows on the Mimir / Tenants dashboard

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/github.com/prometheus/prometheus/tsdb/testutil.go
vendor/modules.txt

At https://github.com/grafana/mimir-prometheus/commit/641277312a18a2de5f67ebfa40ef91ad05158663
For https://github.com/prometheus/prometheus/pull/15180

chore(deps): vendor update mimir-prometheus at 641277312a18

---

go.mod
go.sum
pkg/distributor/otlp/histograms_generated.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/histograms.go
vendor/modules.txt

Applying https://github.com/grafana/mimir-prometheus/pull/719

Applying mimir-prometheus#719 to r310

---

go.mod
go.sum
pkg/distributor/otlp/histograms_generated.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/histograms.go
vendor/modules.txt

Applying https://github.com/grafana/mimir-prometheus/pull/719

Applying mimir-prometheus#719 to r311

---

go.mod
go.sum
pkg/distributor/otlp/histograms_generated.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/histograms.go
vendor/modules.txt

Applying https://github.com/grafana/mimir-prometheus/pull/719

Applying mimir-prometheus#719 to r312

---

pkg/util/http.go

chore: add more spans around reading

---

pkg/blockbuilder/tsdb.go

Follows up to #8978. This is a clean-up PR that simplifies the internals of block-builder's TSDB wrapper.

blockbuilder: clean-up tsdb internals

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/prometheus/prometheus/rules/group.go
vendor/modules.txt

Brings in https://github.com/grafana/mimir-prometheus/pull/714

Update Mimir Prometheus to `e8c852a`

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Cherry-picking https://github.com/prometheus/prometheus/pull/15242.
N/A

[r312] Cherry-pick Prometheus PR 15242

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Cherry-picking https://github.com/prometheus/prometheus/pull/15242.
N/A

[r313] Cherry-pick Prometheus PR 15242

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Cherry-picking https://github.com/prometheus/prometheus/pull/15242
N/A

[r314] Cherry-pick Prometheus PR 15242

---

pkg/storage/ingest/config.go
pkg/storage/ingest/pusher.go
pkg/storage/ingest/pusher_test.go

@pracucci left me some feedback as part of #9739, this PR address it.

Adress review feedback left as part of #9739

---

CHANGELOG.md
pkg/distributor/validate.go
pkg/distributor/validate_test.go

Backport c7ce088730a6329e12c58bfbbc71fb8bb12ea22a from #9828

[r312] fix marshaling error on invalid label value

---

CHANGELOG.md
pkg/distributor/validate.go
pkg/distributor/validate_test.go

Backport https://github.com/grafana/mimir/commit/c7ce088730a6329e12c58bfbbc71fb8bb12ea22a from https://github.com/grafana/mimir/pull/9828.

[r314] fix marshaling error on invalid label value

---

CHANGELOG.md
pkg/distributor/validate.go
pkg/distributor/validate_test.go

Backport https://github.com/grafana/mimir/commit/c7ce088730a6329e12c58bfbbc71fb8bb12ea22a from https://github.com/grafana/mimir/pull/9828.

[r313] fix marshaling error on invalid label value

---

pkg/querier/querier_test.go

In querier tests, compare floats with epsilon instead of exact equality.

Querier tests: compare floats with epsilon

---

CHANGELOG.md
pkg/streamingpromql/operators/binops/or_binary_operation.go
pkg/streamingpromql/operators/binops/or_binary_operation_test.go
pkg/streamingpromql/testdata/ours/binary_operators.test

Backport #9874 to r315

---

CHANGELOG.md
pkg/streamingpromql/operators/binops/or_binary_operation.go
pkg/streamingpromql/operators/binops/or_binary_operation_test.go
pkg/streamingpromql/testdata/ours/binary_operators.test

Backport #9874 to r314

---

CHANGELOG.md
pkg/streamingpromql/operators/or_binary_operation.go
pkg/streamingpromql/operators/or_binary_operation_test.go
pkg/streamingpromql/testdata/ours/binary_operators.test

Backport #9874 to r313

---

CHANGELOG.md
pkg/streamingpromql/operators/binops/or_binary_operation.go
pkg/streamingpromql/operators/binops/or_binary_operation_test.go
pkg/streamingpromql/testdata/ours/binary_operators.test

Backport #9874 to r316

---

pkg/storage/ingest/fetcher.go
pkg/storage/ingest/fetcher_test.go

There's nothing special we have to do here. We only refresh the metadata so that maybe we exclude the dead broker from our list and then continue fetching.

ingester: anticipate BROKER_NOT_AVAILABLE errors

---

docs/sources/helm-charts/mimir-distributed/configure/configure-gem-federation-frontend.md

The docs depends on the code changes from https://github.com/grafana/mimir/pull/9673 and https://github.com/grafana/mimir/pull/9734.
I wasn't sure whether to also include instructions for setting up the ingress and/or whether the instructions shouldn't also deploy the GEM gateway for authn/z and forward to the federation-frontend. Curious to hear what y'all think.
related to https://github.com/grafana/mimir/issues/9672

docs: add docs for setting up federation-frontend with Helm

---

pkg/blockbuilder/scheduler/scheduler.go

Fix a spot where we weren't checking all available errors that come out of kadmin/kgo API calls.

Block-builder-scheduler: Check per-partition errors

---

docs/sources/mimir/manage/run-production-environment/scaling-out.md
docs/sources/mimir/set-up/jsonnet/migrate-from-microservices-to-read-write.md

Updates the Mimir docs to describe the new ingester downscaling procedures.
Followup to #8956.

Add ingester downscaling docs

---

pkg/distributor/ha_tracker.go

This PR improves logging during the sync operation of ha_tracker, making it easier to debug when the underlying store fails during key listing."
Fixes: No Issue
It relates with conversation [here](https://raintank-corp.slack.com/archives/C029912SXT8/p1731974290336369?thread_ts=1731969539.574319&cid=C029912SXT8)

Improve logging at ha_tracker sync operation

---

pkg/ingester/lifecycle_test.go

Increase ring heartbeat frequency to try and improve flaky downscale tests.
Fixes #9494

Ring downscale flaky test fix

---

pkg/mimirpb/timeseries.go

Cherry picking https://github.com/grafana/mimir/pull/10040 into `r318` branch.
N/A

[r318] Cherry pick TimeSeries slices pool memory fix

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

Backports https://github.com/prometheus/prometheus/pull/15426 to r314

[r314] Update mimir-prometheus to include prometheus#15426

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

This backports the following PRs:
- https://github.com/prometheus/prometheus/pull/15426
- https://github.com/grafana/mimir-prometheus/pull/751
- https://github.com/grafana/mimir-prometheus/pull/763

[r316] Update mimir-prom to add missing backports

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/modules.txt

This backports the following PRs:
- https://github.com/prometheus/prometheus/pull/15426
- https://github.com/grafana/mimir-prometheus/pull/751
- https://github.com/grafana/mimir-prometheus/pull/763

[r317] Update mimir-prom to add missing backports

---

development/mimir-ingest-storage/docker-compose.jsonnet
development/mimir-ingest-storage/docker-compose.yml
pkg/mimir/mimir.go
pkg/mimir/modules.go
pkg/usagetracker/tracker.go

Add usage-tracker module

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/discovery/registry.go
vendor/github.com/prometheus/prometheus/model/histogram/float_histogram.go
vendor/github.com/prometheus/prometheus/model/histogram/histogram.go
vendor/github.com/prometheus/prometheus/model/relabel/relabel.go
vendor/github.com/prometheus/prometheus/model/rulefmt/rulefmt.go
vendor/github.com/prometheus/prometheus/model/textparse/promparse.go
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/promql/info.go
vendor/github.com/prometheus/prometheus/promql/promqltest/test.go
vendor/github.com/prometheus/prometheus/rules/alerting.go
vendor/github.com/prometheus/prometheus/rules/recording.go
vendor/github.com/prometheus/prometheus/storage/interface.go
vendor/github.com/prometheus/prometheus/storage/labelvalues.go
vendor/github.com/prometheus/prometheus/storage/remote/azuread/azuread.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/float_histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go
vendor/github.com/prometheus/prometheus/tsdb/chunks/chunks.go
vendor/github.com/prometheus/prometheus/tsdb/compact.go
vendor/github.com/prometheus/prometheus/tsdb/db.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/github.com/prometheus/prometheus/tsdb/symbols_batch.go
vendor/github.com/prometheus/prometheus/tsdb/tsdbblockutil.go
vendor/github.com/prometheus/prometheus/web/api/v1/api.go
vendor/modules.txt

This includes just linted changes. Sending separately to avoid noise on important code changes.
Ref: https://github.com/grafana/mimir-prometheus/pull/777

Update mimir-prometheus to 120c71abae2

---

CHANGELOG.md
docs/sources/mimir/release-notes/v2.13.md

In this PR I'm merging the release-2.13 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge release-2.13 to main

---

pkg/usagetracker/tracker_store.go
pkg/usagetracker/tracker_store_snapshot.go
pkg/usagetracker/tracker_store_test.go

Still to be wired to Kafka/ObjectStorage.

UsageTracker: add methods to create & load snapshot

---

cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/usagetracker/tracker.go
pkg/usagetracker/usagetrackerpb/usagetracker.pb.go
pkg/usagetracker/usagetrackerpb/usagetracker.proto

This should publish the SeriesCreated event to Kafka, and consume it from there.

UsageTracker: publish and consume SeriesCreated events

---

tools/usage-tracker-load-generator/main.go

Add usage-tracker-load-generator.
N/A

Add usage-tracker-load-generator

---

cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/configuration-parameters/index.md

UsageTracker: make doc reference-help

---

pkg/usagetracker/tracker_store_test.go

One of the assumptions of trackerStore is that cleanup() is called at least once in each idleTimeout: this is needed to make sure that "minutes" timestamp doesn't get too old and starts looking as a newer one.
We didn't ensure this in the test, so weird stuff was happening.
Now we increase the timestamp one minute each time, and we set idle timeout to 1 minute, so we force the race conditions.

Fix TestTrackerStore_Cleanup_Concurrency

---

pkg/usagetracker/tracker.go
pkg/usagetracker/tracker_store_collector.go
pkg/usagetracker/tracker_store_test.go

This will export the number of activer series tracker for each tenant.

UsageTracker: register store as prometheus collector

---

pkg/scheduler/scheduler.go

context cancelled is less informative
@colega asked if this can be a real context cancellation. I think it can't because:
so the cancellation of the real request is tracked a few lines down here
https://github.com/grafana/mimir/blob/f8155dda490b0efd35c8a8e43d715c07d2bcb159/pkg/scheduler/scheduler.go#L543-L549
the error we get in the changes in this PR is controlled by the querier. The querier variable is the thing which gRPC passes to us  when a querier makes a connection to the query-scheduler.
https://github.com/grafana/mimir/blob/f8155dda490b0efd35c8a8e43d715c07d2bcb159/pkg/scheduler/scheduler.go#L421-L423
And then the querier would cancel the connection on its end only after waiting for all queries to finish here (code is complicated; [here is the …

query-scheduler: replace context.Cancelled with custom error

---

pkg/frontend/querymiddleware/request_validation.go

PR https://github.com/grafana/mimir/pull/10093 got merged without a rebase to pull in a changed method name - this updates

update call to method with changed signature

---

pkg/usagetracker/clock/minutes.go
pkg/usagetracker/clock/minutes_test.go
pkg/usagetracker/tracker_store.go
pkg/usagetracker/tracker_store_snapshot.go
pkg/usagetracker/tracker_store_test.go

This will make future changes easier.

UsageTracker: extract clock.Minutes

---

pkg/usagetracker/tenantshard/map_test.go

Let's make sure that we're retrieving the values we're storing.

UsageTracker: tenantshard: TestMapValues

---

tools/usage-tracker-load-generator/.gitignore
tools/usage-tracker-load-generator/main.go

Add replica ID and tenant ID to usage-tracker-load-generator.
N/A

Add replica ID and tenant ID to usage-tracker-load-generator

---

pkg/usagetracker/tracker_store.go

If a lot of requests arrive at the same time, we're going to to tentatively allocate too many too large maps.

UsageTracker: don't preallocate tenants tentatively

---

tools/usage-tracker-load-generator/main.go
tools/usage-tracker-load-generator/main_test.go

Pre-compute series hashes in usage-tracker-load-generator and fix random generator.

Pre-compute series hashes in usage-tracker-load-generator and fix random generator

---

RELEASE.md

Add some missing steps/info to RELEASE.md.

Add missing steps to RELEASE.md

---

renovate.json5

Update renovate to manage release-2.15 branch

---

go.mod
go.sum
pkg/distributor/otlp/helper_generated.go
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/model/exemplar/exemplar.go
vendor/github.com/prometheus/prometheus/model/labels/labels.go
vendor/github.com/prometheus/prometheus/model/labels/labels_dedupelabels.go
vendor/github.com/prometheus/prometheus/model/labels/labels_stringlabels.go
vendor/github.com/prometheus/prometheus/model/textparse/openmetricsparse.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus/normalize_name.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
vendor/github.com/prometheus/prometheus/tsdb/querier.go
vendor/modules.txt

This includes an important bugfix from https://github.com/prometheus/prometheus/pull/15684 (not including in the changelog as it was broken a week ago)
Also an enhancement in tsdb: https://github.com/prometheus/prometheus/pull/13880

Update mimir-prometheus to b500527

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Cut the Helm CHANGELOG in preparation for the 5.6.0 release candidate.
Relates to https://github.com/grafana/mimir/issues/10151

Helm: cut changelog for 5.6.0-rc.0

---

pkg/ruler/api_test.go

Extra information to debug #10294

Use test logger in Ruler API tests

---

.github/ISSUE_TEMPLATE/2-bug-report.yml
.github/ISSUE_TEMPLATE/3-documentation-request.yml

This is a follow-up to #9772
From the recently opened bug tickets I've noticed that important details, like the version of Mimir is missing. This PR updates the issue templates, adding more examples of the details we expect to see in the report. Hopefully this will reduce the amount of ping-ponging with the bug author.

Update issue template placeholders with more examples of the expected details

---

tools/release/notify-changelog-cut.sh

I see some people replying to these comments, but in reality the author wouldn't normally follow up

notify-changelog-cut.sh: clarify this is an automated action

---

renovate.json5

Renovate: only maintain latest two minor versions

---

go.mod
go.sum
vendor/github.com/grafana/dskit/ring/basic_lifecycler.go
vendor/github.com/grafana/dskit/ring/lifecycler.go
vendor/github.com/grafana/dskit/ring/ring.go
vendor/github.com/grafana/dskit/ring/ring_http.go
vendor/github.com/grafana/dskit/ring/ring_status.gohtml
vendor/modules.txt

Bump dskit to latest main. This only includes one commit since the last [renovate bump.](https://github.com/grafana/mimir/pull/10341).
https://github.com/grafana/dskit/pull/633
That change only brings in new toggles, but we do not enable them yet. Thus, this PR should not change behavior.
n/a

chore: Upgrade dskit

---

integration/backward_compatibility.go

Update backward_compatibility.go for 2.15

---

RELEASE.md

Adds a note to the release issue template to make sure that the release notes have been cherry-picked to the release branch _before_ tagging the release.

Add order of operations note to release issue template

---

RELEASE.md

Adds a note to check the user's role; without Admin access, the user will be forbidden from updating dashboards.

Add role check to release docs

---

pkg/streamingpromql/operators/functions/native_histograms.go

From https://github.com/grafana/mimir/pull/10211

MQE: Fix docstring location

---

development/mimir-microservices-mode/config/datasources.yaml

this is useful to use as a datasource when the Mimir cluster has an outage

mimir-microservices-mode: add prometheus datasource

---

CHANGELOG.md
cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
cmd/mimir/help.txt.tmpl
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/mimir/modules.go
pkg/ruler/remotequerier.go
pkg/ruler/remotequerier_test.go

#10375
(cherry picked from commit ffee57de406dd651dccf104db25ee93ec46a3c0e)

r316: ruler: cap the number of remote eval retries

---

pkg/mimir/modules.go

ruler: use max_retries_rate flag

---

.github/workflows/deploy-pr-preview.yml

Otherwise this can be parsed as a YAML tag

Fix syntax

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.6.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

 Helm chart 5.6 release candidate on Mimir 2.15.0-rc.0 

---

pkg/ruler/mapper.go
pkg/util/shard.go

Solves or suppresses existing violations of gosec g401 (none were used in a vulnerable way). This allows for enabling g401 on the codebase in the future.
n/a
<already covered by tests, does not need docs or changelog>

chore: Fix gosec g401 in a handful of spots

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

helm: Cut mimir-distributed release 5.6.0

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Fix CHANGELOG with stable release

---

.golangci.yml

Issues have been fixed or suppressed. https://github.com/grafana/mimir/pull/10446 https://github.com/grafana/mimir/pull/10470

Enable gosec G401

---

operations/helm/charts/mimir-distributed/RELEASE.md

Update release docs with instructions on getting technical docs updated

---

pkg/streamingpromql/functions.go
pkg/streamingpromql/testdata/upstream/functions.test
pkg/streamingpromql/types/limiting_pool.go

This PR fixes a few small issues I noticed while working on #10487.
I've broken these into individual commits for ease of review.
#10067

MQE: code cleanup

---

CHANGELOG.md

Fix #10484 CHANGELOG

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

This PR cherry-picks the changes https://github.com/grafana/mimir/pull/10466 into the main branch.
Relates to https://github.com/grafana/mimir/issues/10151

mimir-distributed: Fix CHANGELOG with stable release (#10466)

---

pkg/querier/tenantfederation/merge_queryable.go

Refactor mergeQueryable so it can be reused outside of Mimir.
N/A
Not a user-facing change.

Modify mergeQueryable to allow reuse

---

pkg/streamingpromql/functions_test.go

This PR addresses some feedback on the tests added in #10533.
#10067, #10533

MQE: address post-merge feedback on #10533

---

operations/mimir-mixin/dashboards/block-builder.libsonnet

Fix typo in block-builder dashboard: compactios->compactions.

operations/mimir-mixin/dashboards: Fix typo compactios->compactions

---

renovate.json5

Renovate: Fix config syntax error

---

tools/grpcurl-query-ingesters/README.md
tools/grpcurl-query-ingesters/download-chunks-from-ingesters.sh
tools/grpcurl-query-store-gateways/.gitignore
tools/grpcurl-query-store-gateways/README.md
tools/grpcurl-query-store-gateways/download-chunks-from-store-gateways-query.json
tools/grpcurl-query-store-gateways/download-chunks-from-store-gateways.sh
tools/grpcurl-query-store-gateways/main.go
tools/grpcurl-query-store-gateways/response.go

I needed this to debug some query responses. This is a rip-off of the grpcurl-query-ingesters tool.

tools: add grpcurl-query-store-gateways

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
operations/helm/charts/mimir-distributed/values.yaml

Allow the resources to be set for the smoke-test job
Fixes #10608

Allow resources to be set for smoke-test job

---

docs/sources/mimir/configure/about-versioning.md

Forgot to add some experimental features here:
- https://github.com/grafana/mimir/pull/10460
- https://github.com/grafana/mimir/pull/10484

Add two missing features to `about-versioning.md`

---

operations/helm/charts/mimir-distributed/values.yaml

helm: update comment for additional containers in federation-frontend pod

---

pkg/streamingpromql/operators/aggregations/topkbottomk/range_query.go

This PR addresses some refactoring feedback from #10614 that was intentionally deferred to a later PR.
#10614

MQE: address PR feedback on `topk` / `bottomk`

---

docs/proposals/reduce-multitenancy-cost.md

This PR marks the proposal as accepted.
N/A

Mark Tenancy multiplexing proposal as Accepted

---

docs/sources/mimir/configure/configure-object-storage-backend.md

Backend type definition for storage was missing for non-common scenarios.
This PR updated the example for Azure Blob Storage

fix: update azure blob storage documentation

---

docs/sources/helm-charts/mimir-distributed/configure/configure-autoscaling.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-autoscaling.md
docs/sources/mimir/set-up/jsonnet/configure-autoscaling.md
operations/helm/charts/mimir-distributed/values.yaml

This adds some docs for Helm. This started as an article to discourage from using GEM/Mimir as the source of autoscaling metrics, but it grew a bit.
This is a WIP procedure and I tried to indicate that. It think it's better to have this published than in a GH issue.
Related to https://github.com/grafana/mimir/issues/7367

helm docs: add configure-autoscaling.md

---

docs/sources/mimir/configure/configure-object-storage-backend.md

Reverts grafana/mimir#10682
if the problem is helm we should fix it in helm, not in the general docs

Revert "fix: update azure blob storage documentation"

---

.github/workflows/generate-docs-helm-tests-renovate-pr.yml

This is a subset of https://github.com/grafana/mimir/pull/10650 to test changes one step at a time due to bugs in the larger PR that are complex to debug.
This follows what is described in https://github.com/grafana/shared-workflows/tree/main/actions/get-vault-secrets.

Use GitHub app in generate-docs-helm-tests-renovate-pr.yml

---

.github/workflows/backport.yaml

This is the nearly the same as https://github.com/grafana/backend-enterprise/blob/master/.github/workflows/backport.yml as this workflow works: https://github.com/grafana/backend-enterprise/pull/8440

Use the app token in backport.yml

---

pkg/streamingpromql/engine_test.go
pkg/streamingpromql/functions.go
pkg/streamingpromql/functions_test.go
pkg/streamingpromql/operators/functions/absent.go
pkg/streamingpromql/operators/functions/absent_over_time.go
pkg/streamingpromql/operators/functions/absent_test.go
pkg/streamingpromql/testdata/ours/functions.test
pkg/streamingpromql/testdata/upstream/functions.test

MQE: Implement absent_over_time

---

pkg/streamingpromql/operators/aggregations/avg.go
pkg/streamingpromql/operators/aggregations/common.go
pkg/streamingpromql/operators/aggregations/quantile.go
pkg/streamingpromql/operators/aggregations/sum.go

MQE: Rename param for consistency

---

docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-helm-chart-4.x-to-5.0.md
docs/sources/helm-charts/mimir-distributed/release-notes/v3.2.md
docs/sources/helm-charts/mimir-distributed/release-notes/v4.0.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.0.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md

For https://github.com/grafana/website/issues/24017
Removes all relref shortcodes.
Created-By: reverse-changes
Repository: grafana/mimir
Website-Pull-Request: https://github.com/grafana/website/pull/24630

[v5.4.x] Remove relref shortcodes

---

CHANGELOG.md
pkg/storage/ingest/pusher.go
pkg/storage/ingest/pusher_test.go

Cherry-picking https://github.com/grafana/mimir/pull/10915 to r334.
N/A

[r334] Fix goroutines and memory leak in parallelStorageShards (#10915)

---

CHANGELOG.md

docs: Fix a few inconsistencies in the CHANGELOG before 2.16 release

---

docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-helm-chart-4.x-to-5.0.md
docs/sources/helm-charts/mimir-distributed/release-notes/v3.2.md
docs/sources/helm-charts/mimir-distributed/release-notes/v4.0.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.0.md
docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md

For https://github.com/grafana/website/issues/24017
Removes all relref shortcodes.
Created-By: reverse-changes
Repository: grafana/mimir
Website-Pull-Request: https://github.com/grafana/website/pull/24630

Remove relref shortcodes

---

renovate.json5

chore: Update renovate to keep release-2.16 branch up to date

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/tsdb/head.go
vendor/github.com/prometheus/prometheus/tsdb/head_wal.go
vendor/modules.txt

Update mimir-prometheus to pull in https://github.com/grafana/mimir-prometheus/pull/851

[r334] Update mimir-prometheus

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

Part of the Mimir 2.16 release: https://github.com/grafana/mimir/issues/10917

helm: Cut changelog for 5.7 RC

---

docs/sources/helm-charts/mimir-distributed/_index.md
docs/sources/helm-charts/mimir-distributed/release-notes/v5.7.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

In this PR I'm merging the mimir-distributed-release-5.7 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge mimir-distributed-release-5.7 to main

---

docs/sources/mimir/manage/run-production-environment/scaling-out.md

Fixes the indentation and styling by making the ordered and unordered list semantically recognised.
N/A

docs: tweak formatting of ordered and unordered list

---

pkg/streamingpromql/functions_test.go
pkg/streamingpromql/operators/functions/absent.go
pkg/streamingpromql/operators/functions/absent_over_time.go
pkg/streamingpromql/operators/functions/factories.go
pkg/streamingpromql/operators/functions/factories_test.go
pkg/streamingpromql/query.go

This PR refactors how operators for functions are created in MQE in preparation for the introduction of the query planner.
I've tried to build up this PR incrementally, I'd recommend reviewing each commit separately.
(none)

MQE: refactor function handling

---

pkg/alertmanager/state_replication_test.go

If the context cancellation is not caught by `state.running()`, the test can time out waiting to receive a message on `msgc`. This PR changes the test to check for state replication metrics instead of waiting for a message.
Fixes https://github.com/grafana/mimir/issues/10987

Alertmanager: Fix flaky TestMergeGrafanaState

---

docs/sources/mimir/release-notes/v2.16.md

Docs: Release notes for 2.16

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
vendor/github.com/grafana/dskit/ring/ring.go
vendor/modules.txt

Update to the latest dskit commit to pull in https://github.com/grafana/dskit/pull/672 which improves performance of ring operations in clients (queriers, distributors) when zone-awareness is enabled and an entire zone is not "ACTIVE".
Related https://github.com/grafana/dskit/pull/672

chore: update to latest dskit for ring performance fix

---

.github/workflows/helm-ci.yml
.github/workflows/test-build-deploy.yml
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/templates/validate.yaml
operations/helm/tests/openshift-values-generated/mimir-distributed/charts/rollout_operator/templates/deployment.yaml

https://github.com/helm/helm/pull/12879 modified merging values for sub-charts in a non-backwards compatible way.
NA
- [NA] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

fix(helm): followup PR 12879 in Helm

---

go.mod
go.sum
vendor/github.com/prometheus/prometheus/notifier/alert.go
vendor/github.com/prometheus/prometheus/notifier/alertmanager.go
vendor/github.com/prometheus/prometheus/notifier/alertmanagerset.go
vendor/github.com/prometheus/prometheus/notifier/manager.go
vendor/github.com/prometheus/prometheus/notifier/metric.go
vendor/github.com/prometheus/prometheus/notifier/util.go
vendor/modules.txt

Sync with mimir-prometheus@main to bring in https://github.com/grafana/mimir-prometheus/pull/865
N/A

Sync mimir-prom for 20250407

---

pkg/streamingpromql/optimize/ast/sort_labels_and_matchers_test.go

#11147 reports that `TestSortLabelsAndMatchers_Selectors` is flaky.
I'm not able to reproduce the flakiness locally, and the output from the original failed run isn't helpful to understand what went wrong. In this PR, I'm modifying the test so that failures will be easier to understand, as we'll get the matchers in text form rather than as pointers.
#11147 

Modify `TestSortLabelsAndMatchers_Selectors` to make it easier to debug flaky failures

---

CHANGELOG.md

This is the backport of https://github.com/grafana/mimir/pull/11155 into relelase-2.16

 Fix changelog for 2.16.0

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

[mimir-distributed-release-5.7] Update to 5.7 final release

---

CHANGELOG.md
pkg/frontend/querymiddleware/querysharding.go
pkg/frontend/querymiddleware/querysharding_test.go

Discovered during #11120
Related #10537

fix: Fix case where deadline exceeded errors could be cached

---

go.mod
go.sum
pkg/distributor/distributor.go
pkg/frontend/querymiddleware/running.go
pkg/ingester/client/streaming.go
pkg/querier/block_streaming.go
tools/querytee/proxy_endpoint.go
vendor/github.com/grafana/dskit/ring/replication_set.go
vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
vendor/modules.txt

Updates `dskit` to https://github.com/grafana/dskit/pull/679 and applies the required changes.
This doesn't change any behaviour.
These are efforts towards migrating Mimir from opentracing to opentelemetry.
- `-` Tests updated.
- `-` Documentation added.
- `-` `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- `-` [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

Update to dskit w/ spanlogger not embedding Span

---

pkg/streamingpromql/testutils/utils.go

Address nits in https://github.com/grafana/mimir/pull/10873#discussion_r2016037467

Address last nits from double_exponential_smoothing PR

---

pkg/streamingpromql/benchmarks/comparison_test.go

Actually create a query planner for the benchmarks to use.

MQE: Fix benchmark with query planner

---

operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Updates Helm chart to 5.6.1 with Mimir/GEM 2.15.2

Helm chart: Release version 5.6.1 with Mimir and GEM 2.15.2

---

CHANGELOG.md
pkg/ingester/ingester.go
pkg/ingester/reactivelimiter.go
pkg/util/math/ewma.go
pkg/util/math/ewma_test.go
pkg/util/math/median.go
pkg/util/math/median_test.go
pkg/util/math/windows.go
pkg/util/math/windows_test.go
pkg/util/reactivelimiter/blockinglimiter.go
pkg/util/reactivelimiter/prioritylimiter.go
pkg/util/reactivelimiter/reactivelimiter.go
pkg/util/sync/semaphore.go

Backport adaptive limiter activation

---

docs/sources/mimir/set-up/jsonnet/migrate-from-microservices-to-read-write.md

The prom QL expression was wronly formatted.

docs: fix step 3.2 in migration

---

pkg/distributor/distributor.go
pkg/distributor/influx.go
pkg/distributor/otel.go
pkg/distributor/push.go
pkg/distributor/push_test.go
pkg/distributor/request.go

This PR is an update of https://github.com/grafana/mimir/pull/11178 that better reports added `artificialDelay` as part of the `ServerTiming` header on push requests.
Check out for reviewer's notes on the code:

Report `artificialDelay` on `ServerTiming` header for push requests

---

docs/sources/mimir/configure/about-versioning.md

Make some fixes to docs/sources/mimir/configure/about-versioning.md regarding cluster validation functionality:
* Document `cortex_client_invalid_cluster_validation_label_requests_total` for `-query-frontend.client-cluster-validation.label`
* Document that server side functionality is also for HTTP, not just gRPC
* Document `cortex_server_invalid_cluster_validation_label_requests_total` metric
* Make description of `cortex_client_invalid_cluster_validation_label_requests_total` consistent

about-versioning.md: Fixes regarding cluster validation

---

pkg/storage/parquet/tsdbcodec/fixtures.go

Making these available. Not actually using them in a test yet because the first test I have is gonna call the BlockToRowsStream which is going to light up the race detector in tests.
Will handle that in a separate PR.

parquet mimir add first test fixtures

---

.github/workflows/generate-docs-helm-tests-renovate-pr.yml
.github/workflows/push-mimir-build-image.yml

Fix the critical template injection issue reported by zizmor ([doc here](https://woodruffw.github.io/zizmor/audits/#template-injection), [remediation doc here](https://securitylab.github.com/resources/github-actions-untrusted-input/)).
N/A

GitHub actions: fix template injection issue reported by zizmor

---

.github/workflows/backport.yaml
.github/workflows/compare-helm-with-jsonnet.yml
.github/workflows/generate-docs-helm-tests-renovate-pr.yml
.github/workflows/helm-weekly-release-pr.yaml
.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release-helm-charts.yml
.github/workflows/publish-technical-documentation-release-mimir.yml
.github/workflows/push-mimir-build-image.yml
.github/workflows/sbom-report.yml
.github/workflows/test-build-deploy.yml
.github/workflows/update-make-docs.yml

This PR updates several GitHub Actions to pin them to specific commit hashes instead of floating tags. This improves security and build reproducibility by ensuring the exact version of the action is always used.
**Updated Actions:**
* `bf30293`: Update [`docker/login-action`](https://github.com/docker/login-action) to commit hash (from tags [v3](https://github.com/docker/login-action/releases/tag/v3), [v3.4.0](https://github.com/docker/login-action/releases/tag/v3.4.0))
* `a0d8d7c`: Update [`anchore/sbom-action`](https://github.com/anchore/sbom-action) to commit hash (from tag [v0.18.0](https://github.com/anchore/sbom-action/releases/tag/v0.18.0))
* `f1fadde`: Update [`grafana/writers-toolkit/publish-technical-documentation`](https://github.com/grafana/writers-toolkit) to commit hash …

Pin GH actions to commit hashes

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release-helm-charts.yml
.github/workflows/publish-technical-documentation-release-mimir.yml

Set explicit permissions for all publish documentation workflows

---

pkg/storage/parquet/reader.go
pkg/storage/parquet/tsdbcodec/reader_test.go

chore(parquet): fix some spans, propagate context

---

.github/workflows/update-make-docs.yml

Limit permissions for workflow that updates `make docs`

---

pkg/storage/parquet/tsdbcodec/reader.go
pkg/storage/parquet/tsdbcodec/reader_test.go

parquet-mimir fix block to parquet row stream race

---

go.mod
go.sum
vendor/github.com/grafana/dskit/middleware/grpc_stats.go
vendor/github.com/grafana/dskit/server/metrics.go
vendor/github.com/grafana/dskit/server/server.go
vendor/modules.txt

Adding some observability on grpc connections: https://github.com/grafana/dskit/pull/685

Vendor latest dskit version

---

go.mod
go.sum
vendor/github.com/grafana/dskit/ring/partition_ring_watcher.go
vendor/modules.txt

Updates and vendor dskit to https://github.com/grafana/dskit/commit/1ca3f08a7c994cac2e2809dae1e5b9125a72cb6e.

Update and vendor dskit@1ca3f08a7c994cac2e2809dae1e5b9125a72cb6e

---

pkg/querier/blocks_store_queryable.go
pkg/querier/distributor_queryable.go

This is a follow up to https://github.com/grafana/mimir/pull/11136#discussion_r2071376796 that removes some unnecessary locking from code we don't expect to be called by multiple goroutines simultaneously.
#11136

Remove unnecessary locking in `Querier`s

---

.github/workflows/test-build-deploy.yml

Adds required permissions as per docs.
Follow up on https://github.com/grafana/mimir/pull/11388

CI: deploy: add permissions for DockerHub login

---

pkg/blockbuilder/blockbuilder.go
pkg/blockbuilder/metrics.go

Add a timing histogram for job completions. This is a nice number to have, and we may also use it for autoscaling.

Block-builder: Time job completion.

---

go.mod
pkg/mimir/modules.go
pkg/querier/parquet/cortex-poc/parquet_blocks_finder_bucket_index.go
pkg/querier/parquet/cortex-poc/parquet_queryable.go
pkg/storage/parquet/convert/convert.go
pkg/storage/parquet/convert/convert_test.go
pkg/storage/parquet/convert/merge.go
pkg/storage/parquet/convert/writer.go
pkg/storage/parquet/convert/writer_test.go
pkg/storage/parquet/schema/encoder.go
pkg/storage/parquet/schema/encoder_test.go
pkg/storage/parquet/schema/schema.go
pkg/storage/parquet/schema/schema_builder.go
pkg/storage/parquet/schema/schema_builder_test.go
pkg/storage/parquet/search/constraint.go
pkg/storage/parquet/search/constraint_test.go
pkg/storage/parquet/search/rowrange.go
pkg/storage/parquet/search/rowrange_test.go
pkg/storage/parquet/search/search.go
pkg/storage/parquet/tsdbcodec/fixtures.go
pkg/storage/parquet/util/bucket_read_at.go
pkg/storage/parquet/util/util.go

bring in  prometheus/parquet-common code up to 4e5ab684

---

.github/workflows/test-build-deploy.yml

this helps with flaky tests
related to https://github.com/grafana/mimir-squad/issues/2944

CI: retry integration and unit tests

---

pkg/parquetconverter/parquet_converter.go

[WIP] parquet-mimir enable prom common converter

---

go.mod
go.sum
vendor/github.com/grafana/dskit/middleware/http_cluster.go
vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
vendor/modules.txt

Upgrade to latest dskit, [10bc270c967b](https://github.com/grafana/dskit/commit/10bc270c967b7f86acbe7a2d42b8b5c81d97624b).

Upgrade to dskit@10bc270c967b

---

.github/workflows/test-build-deploy.yml
go.mod
go.sum
vendor/github.com/grafana/dskit/middleware/http_cluster.go
vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
vendor/modules.txt

Backport of https://github.com/grafana/mimir/pull/11425 (cherry picked from commit 520bc4186d1f329f065e000da8379251f0743b00).

[Backport r341] Upgrade to dskit@10bc270c967b (#11425)

---

.github/workflows/test-build-deploy.yml

Renames a CI step to be more descriptive.

Rename 'Deploy' CI step to 'Push Docker Images'

---

operations/helm/charts/mimir-distributed/values.yaml

Clarifies what `targetCPUUtilizationPercentage` and `targetMemoryUtilizationPercentage` do for each container.
closes https://github.com/grafana/mimir/issues/11449

helm: Clarify autoscaling in values.yaml

---

operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
operations/mimir-mixin-compiled-baremetal/dashboards/mimir-slow-queries.json
operations/mimir-mixin-compiled-gem/dashboards/mimir-slow-queries.json
operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
operations/mimir-mixin/dashboards/slow-queries.libsonnet

This is a new field recently added in #11110

dashboards: show samples processed as a short so it can be ordered by

---

CHANGELOG.md
go.mod
go.sum
pkg/frontend/frontend_test.go
vendor/github.com/grafana/dskit/middleware/http_cluster.go
vendor/modules.txt

* Upgrade to dskit@26335405716d
* Backport of #11549
---------
(cherry picked from commit 351392c22e5f2bfc94c761ae11d922aeba1db263)

[r339] Upgrade to dskit@26335405716d (#11549)

---

CHANGELOG.md
go.mod
go.sum
pkg/frontend/frontend_test.go
vendor/github.com/grafana/dskit/middleware/http_cluster.go
vendor/modules.txt

* Upgrade to dskit@18b79c4e9e07
* Backport of #11549
---------
(cherry picked from commit 351392c22e5f2bfc94c761ae11d922aeba1db263)

[r341] Upgrade to dskit@18b79c4e9e07 (#11549)

---

CHANGELOG.md
go.mod
go.sum
pkg/frontend/frontend_test.go
vendor/github.com/grafana/dskit/middleware/http_cluster.go
vendor/modules.txt

* Upgrade to dskit@f84dc58e0bd9
* Backport of #11549
---------
(cherry picked from commit 351392c22e5f2bfc94c761ae11d922aeba1db263)

[r344] Upgrade to dskit@f84dc58e0bd9 (#11549)

---

CHANGELOG.md
go.mod
go.sum
pkg/frontend/frontend_test.go
vendor/github.com/grafana/dskit/middleware/http_cluster.go
vendor/modules.txt

* Upgrade to dskit@4976ce2fd93c
* Backport of #11549
---------
(cherry picked from commit 351392c22e5f2bfc94c761ae11d922aeba1db263)

[r343] Upgrade to dskit@4976ce2fd93c (#11549)

---

docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/alertmanager-resources/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/alertmanager/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/compactor-resources/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/compactor/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/config/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/object-store/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overrides/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overview-networking/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overview-resources/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/overview/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/queries/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/reads-networking/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/reads-resources/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/reads/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/remote-ruler-reads-networking/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/remote-ruler-reads-resources/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/remote-ruler-reads/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/rollout-progress/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/ruler/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/scaling/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/slow-queries/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/tenants/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/top-tenants/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/writes-networking/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/writes-resources/index.md
docs/sources/mimir/manage/monitor-grafana-mimir/dashboards/writes/index.md

This PR adds descriptions for the dashboards under [Viewing Grafana Mimir Dashboards](https://grafana.com/docs/mimir/latest/manage/monitor-grafana-mimir/dashboards/) to provide users information about typical use cases and what each dashboard can be used to accomplish.
Fixes https://github.com/grafana/mimir-squad/issues/2704

adds use cases for mimir dashboards

---

CHANGELOG.md
pkg/blockbuilder/metrics.go
pkg/frontend/v2/frontend_scheduler_worker.go
pkg/querier/worker/scheduler_processor.go
pkg/scheduler/scheduler.go

Cherry-picked from commit e4df527dc2d92662586ee20cd49aa9f9da3d03b2 (ref #11455)

Fix client labels used for cortex_client_invalid_cluster_validation_label_requests_total (#11455)

---

development/mimir-ingest-storage/Makefile
development/mimir-microservices-mode/Makefile
development/mimir-read-write-mode/Makefile

Minor fix in Jsonnet installation instructions from several files.

Fix Jsonnet installation help for recent Go versions

---

go.mod
go.sum
vendor/github.com/grafana/dskit/middleware/grpc_stats.go
vendor/github.com/grafana/dskit/server/metrics.go
vendor/github.com/grafana/dskit/server/server.go
vendor/modules.txt

https://github.com/grafana/dskit/commit/643ba7cdabb1edc775ec044c2bdbe325561543fa

r345: Revert https://github.com/grafana/dskit/pull/685

---

.github/workflows/test-build-deploy.yml

Cherry-picks https://github.com/grafana/mimir/pull/11390, which fixes the deploy workflow

ci: Use shared workflow for Dockerhub login

---

go.mod
go.sum
vendor/github.com/ebitengine/purego/dlfcn.go
vendor/github.com/ebitengine/purego/dlfcn_darwin.go
vendor/github.com/ebitengine/purego/internal/fakecgo/go_libinit.go
vendor/github.com/ebitengine/purego/internal/fakecgo/libcgo.go
vendor/github.com/ebitengine/purego/internal/fakecgo/symbols.go
vendor/modules.txt

Updates github.com/ebitengine/purego to v0.8.3 to fix building of darwin/amd64 (https://github.com/golang/go/issues/73617)

Update module github.com/ebitengine/purego to 0.8.3

---

go.mod
go.sum
vendor/github.com/ebitengine/purego/dlfcn.go
vendor/github.com/ebitengine/purego/dlfcn_darwin.go
vendor/github.com/ebitengine/purego/internal/fakecgo/go_libinit.go
vendor/github.com/ebitengine/purego/internal/fakecgo/libcgo.go
vendor/github.com/ebitengine/purego/internal/fakecgo/symbols.go
vendor/modules.txt

(cherry picked from commit 44334c130c38613314fde44c56e6301e4d5b8905)
Backport from #11636

Update module github.com/ebitengine/purego to 0.8.3 (#11636)

---

CHANGELOG.md

Revert "Merge release-2.15 to main"

---

CHANGELOG.md

In this PR I'm merging the release-2.15 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.

Merge release-2.15 to main

---

.github/workflows/update-vendored-mimir-prometheus.yml

this is one example PR https://github.com/grafana/mimir/pull/11687 without these fixes

update-vendored-mimir-prometheus.yml: update PR template

---

go.mod
go.sum
pkg/distributor/otlp/metrics_to_prw_generated.go
pkg/streamingpromql/testdata/upstream/aggregators.test
pkg/streamingpromql/testdata/upstream/functions.test
vendor/github.com/prometheus/prometheus/config/config.go
vendor/github.com/prometheus/prometheus/promql/engine.go
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/github.com/prometheus/prometheus/promql/histogram_stats_iterator.go
vendor/github.com/prometheus/prometheus/promql/promqltest/testdata/aggregators.test
vendor/github.com/prometheus/prometheus/promql/promqltest/testdata/functions.test
vendor/github.com/prometheus/prometheus/rules/group.go
vendor/github.com/prometheus/prometheus/scrape/manager.go
vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
vendor/github.com/prometheus/prometheus/util/annotations/annotations.go
vendor/github.com/prometheus/prometheus/util/stats/query_stats.go
vendor/modules.txt

Brings changes from https://github.com/grafana/mimir-prometheus/pull/888 and  https://github.com/grafana/mimir-prometheus/pull/889

Update mimir-prometheus @ 2510b5041da25ef2134c140d17ecc78873459970

---

go.mod
go.sum
vendor/github.com/prometheus-community/parquet-common/convert/convert.go
vendor/github.com/prometheus-community/parquet-common/convert/merge.go
vendor/github.com/prometheus-community/parquet-common/convert/writer.go
vendor/github.com/prometheus-community/parquet-common/schema/encoder.go
vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go
vendor/github.com/prometheus-community/parquet-common/util/fixtures.go
vendor/modules.txt

upgrade prometheus parquet-common dependency

---

.github/workflows/update-vendored-mimir-prometheus.yml

This is one of the PRs with broken title https://github.com/grafana/mimir/pull/11763

actions: fix PR title of mimir-prometheus update PRs

---

go.mod
go.sum
pkg/frontend/querymiddleware/querysharding_test.go
pkg/streamingpromql/testdata/upstream/functions.test
vendor/github.com/prometheus/prometheus/model/textparse/nhcbparse.go
vendor/github.com/prometheus/prometheus/promql/functions.go
vendor/github.com/prometheus/prometheus/promql/parser/functions.go
vendor/github.com/prometheus/prometheus/promql/promqltest/testdata/functions.test
vendor/modules.txt

Brings changes form https://github.com/grafana/mimir-prometheus/pull/891
**Note**, that the changes introducing new promql functions -  ts_of_(min|max|last)_over_time. 
It's experimental, and TestQuerySharding_FunctionCorrectness was failing with `ts_of_(min|max|last)_over_time should be tested,` so I added them to `fnToIgnore`.
- [N/A ] Documentation added.
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.

Update mimir-prometheus @ 226f974e041bed1c679ebd12145f61216af581c6

---

.github/workflows/test-build-deploy.yml

Cherry-pick of https://github.com/grafana/mimir/pull/11390

CI: Use dockerhub credentials from vault (#11390)

---

CHANGELOG.md
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/distributor/ha_tracker.go

distributor: Mark Memberlist as stable for HA Tracker backend storage

---

pkg/storegateway/parquet_bucket_store.go

Adding few log statements to the existing code path with useful information to understand when and why we are returning 0 series.

parquet bucket store: add some debug logging

---

RELEASE.md

docs: Update release shepherd for 2.17

---

pkg/storegateway/parquet_bucket_store.go
pkg/storegateway/parquet_bucket_store_test.go

`chunksIt` is `nil` when `SkipChunks` is `true`.

fix(parquet store gateway): panic in Series call with SkipChunks

---

renovate.json5

Part of https://github.com/grafana/mimir/issues/12039

chore: Update renovate to keep release-2.17 branch up to date

---

CHANGELOG.md
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/distributor/ha_tracker.go

distributor: Mark etcd as deprecated for HA Tracker backend storage

---

integration/ingester_test.go

Adds another test case to cluster validation integration test that exercises the OTLP push path.
Ref: https://github.com/grafana/mimir/issues/12019

Update cluster validation integration test with OTLP push request

---

integration/alertmanager_test.go
integration/e2emimir/client.go
pkg/alertmanager/alertmanager.go
pkg/alertmanager/alertmanager_test.go
pkg/alertmanager/distributor_test.go
pkg/api/api.go

This PR cherry-picks https://github.com/grafana/mimir/pull/12014 into `r351`.

[r351] Alertmanager: Add an endpoint to get the full state #12014 #12078

---

go.mod
go.sum
vendor/github.com/grafana/dskit/ring/basic_lifecycler.go
vendor/github.com/grafana/dskit/ring/multi_partition_instance_ring.go
vendor/github.com/grafana/dskit/ring/partition_instance_lifecycler.go
vendor/github.com/grafana/dskit/ring/partition_ring.go
vendor/github.com/grafana/dskit/ring/partition_ring_editor.go
vendor/modules.txt

This updates dskit to bring the latest features needed for the usage-tracker branch. Updating main so I have to deal with less conflicts in the branch.
This has no user-facing changes.
None

chore: Update dskit

---

CHANGELOG.md
operations/mimir/ingest-storage-migration.libsonnet

The flags were added to Mimir here: https://github.com/grafana/mimir/pull/11291

Jsonnet: Add configs for new ingest storage migration options

---

.github/workflows/flaky-tests.yml

Reverts grafana/mimir#11901
i had it pinned to a branch

Revert "Update dimitarvdimitrov/shared-workflows digest to 0e7ecbf (main)"

---

development/mimir-monolithic-mode/config/otel-collector-otlp-push-config.yaml
development/mimir-monolithic-mode/config/otel-collector-remote-write-config.yaml
development/mimir-monolithic-mode/docker-compose.yml

For testing https://github.com/grafana/mimir/pull/12152

chore(localdev): bump otel collector and enable native histograms

---

pkg/distributor/validate.go
pkg/distributor/validate_test.go
pkg/ruler/compat.go
pkg/ruler/manager.go
pkg/ruler/ruler.go
pkg/util/validation/limits.go

For consistency, rename `pkg/util/validation.Overrides.ValidationScheme` to `NameValidationScheme`.

pkg/util/validation: Rename ValidationScheme override to NameValidationScheme

---

pkg/mimir/modules.go

Fix a copy/paste error from when MQE was added to the query-frontend.
Related #11417

chore: Fix configuration setting used in query-frontend error

---

pkg/parquetconverter/parquet_converter.go

Before this change we were launching the goroutines without checking if they died
```
go c.runBlockDiscovery(ctx)
go c.runBlockProcessing(ctx)
```
I've modified the code slightly to monitor them so we can see panics in case they were failing silently before.
Also brings new parquet-common which has some performance improvements.

feat(converter): monitor discovery and processing goroutines

---

docs/sources/mimir/_index.md
docs/sources/mimir/introduction/_index.md

This PR introduces a new introductory section in the Grafana Mimir documentation aimed at improving the onboarding experience for users. 
It includes the following updates:
- Added a new `introduction/_index.md` page that explains Grafana Mimir’s core concepts and key features and provides a general overview of metrics and their importance.
* Updated the documentation navigation cards in `docs/sources/mimir/_index.md` to include a link to the new introduction page, making it easier for users to discover foundational information about Grafana Mimir.
Fixes https://github.com/grafana/mimir-squad/issues/3175

Add new intro topic

---

go.mod
go.sum
vendor/github.com/prometheus-community/parquet-common/search/iterators.go
vendor/modules.txt

vendor parquet-common at 3e7764e with sparse data skip 

---

go.mod
go.sum
vendor/github.com/grafana/dskit/grpcutil/taphandle.go
vendor/github.com/grafana/dskit/ring/replication_set.go
vendor/github.com/grafana/dskit/server/server.go
vendor/modules.txt

Vendors dskit to bring in https://github.com/grafana/dskit/pull/733 and https://github.com/grafana/dskit/pull/734.

Vendor dskit

---

docs/sources/helm-charts/mimir-distributed/release-notes/v5.8.md
operations/helm/charts/mimir-distributed/CHANGELOG.md
operations/helm/charts/mimir-distributed/Chart.yaml
operations/helm/charts/mimir-distributed/README.md
operations/helm/charts/mimir-distributed/values.yaml

Part of https://github.com/grafana/mimir/issues/12039

[mimir-distributed-release-5.8] Update image versions, changelog, release notes for final release

---

operations/helm/charts/mimir-distributed/CHANGELOG.md

In this PR I'm merging the `mimir-distributed-release-5.8` branch to `main` branch. Please merge this PR using a merge commit or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.
Part of https://github.com/grafana/mimir/issues/12039

Merge distributed release 5.8 to main

---

cmd/mimir/config-descriptor.json
cmd/mimir/help-all.txt.tmpl
development/mimir-microservices-mode/config/mimir.yaml
development/mimir-microservices-mode/docker-compose.jsonnet
docs/sources/mimir/configure/configuration-parameters/index.md
pkg/querier/blocks_store_queryable.go
pkg/querier/blocks_store_replicated_set.go
pkg/querier/blocks_store_replicated_set_test.go
pkg/querier/querier.go

enable in-order store-gateway replica load balancing for parquet

---

go.mod
go.sum
integration/e2emimir/client.go
integration/getting_started_with_grafana_mimir_test.go
integration/influx_ingestion_test.go
integration/otlp_ingestion_test.go
integration/querier_test.go
integration/query_frontend_labels_query_optimizer_test.go
integration/read_write_mode_test.go
vendor/github.com/grafana/e2e/service.go
vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
vendor/github.com/prometheus/client_golang/prometheus/desc.go
vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
vendor/github.com/prometheus/client_golang/prometheus/labels.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/github.com/prometheus/client_golang/prometheus/push/push.go
vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
vendor/github.com/prometheus/common/expfmt/decode.go
vendor/github.com/prometheus/common/expfmt/fuzz.go
vendor/github.com/prometheus/common/expfmt/text_parse.go
vendor/github.com/prometheus/common/model/metric.go
vendor/modules.txt

Upgrade to prometheus/client_golang@[3692d7faba80](https://github.com/prometheus/client_golang/commit/3692d7faba80). I'm not aware of any changes affecting us.

Upgrade to latest prometheus/client_golang

---

go.mod
go.sum
vendor/github.com/prometheus-community/parquet-common/search/constraint.go
vendor/github.com/prometheus-community/parquet-common/search/iterators.go
vendor/modules.txt

bring in latest parquet-common with unmerged pr 107

---

pkg/streamingpromql/engine.go
pkg/streamingpromql/engine_test.go
pkg/streamingpromql/evaluator.go
pkg/streamingpromql/planning.go
pkg/streamingpromql/query.go

This PR adds trace spans for the three main stages of execution in MQE: planning, materialization, and evaluation.
I haven't added a changelog entry given this is not a user-visible change.
(none)

MQE: add trace spans

---

docs/sources/mimir/get-started/about-grafana-mimir-architecture/about-ingest-storage-architecture/index.md
docs/sources/mimir/get-started/about-grafana-mimir-architecture/index.md

This adds some missing content to https://github.com/grafana/mimir/pull/12453
i've left a few TODOs and comments around places of the content where i'm not sure about the best way to present some info.

Docs: overview of ingest storage architecture (pt. 2)

---

CHANGELOG.md

https://github.com/grafana/mimir/issues/12039

Update 2.17.1 changelog

---

docs/sources/mimir/configure/about-versioning.md

Follow-up to https://github.com/grafana/mimir/pull/12612 , just a small docs update

Apply review suggestion to about-versioning

---

docs/sources/mimir/references/architecture/mimir-query-engine.md

Adds more details to "Binary operations that produce no series" section of MQE docs
- ~[ ] Tests updated.~
- ~[ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.~
- ~[ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.~

MQE: improve docs for "Binary operations that produce no series"

---

CHANGELOG.md
docs/sources/mimir/manage/mimir-runbooks/_index.md
operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
operations/mimir-mixin-compiled-baremetal/alerts.yaml
operations/mimir-mixin-compiled-gem/alerts.yaml
operations/mimir-mixin-compiled/alerts.yaml
operations/mimir-mixin/alerts/alerts.libsonnet

This uses the metric added here: https://github.com/grafana/dskit/pull/703 + https://github.com/grafana/dskit/pull/685

Add `MimirHighGRPCConcurrentStreamsPerConnection` alert

---

CHANGELOG.md
operations/mimir-tests/test-automated-downscale-generated.yaml
operations/mimir-tests/test-automated-downscale-v2-generated.yaml
operations/mimir-tests/test-consul-multi-zone-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-0-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
operations/mimir-tests/test-multi-zone-distributor-generated.yaml
operations/mimir-tests/test-multi-zone-etcd-generated.yaml
operations/mimir-tests/test-multi-zone-generated.yaml
operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
operations/mimir-tests/test-multi-zone-with-store-gateway-automated-downscaling-generated.yaml
operations/mimir-tests/test-pvc-auto-deletion-generated.yaml
operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
operations/mimir/ingest-storage.libsonnet

It's currently removing block shipping in non-ingest-storage

jsonnet: Fix #12743 condition

---

pkg/frontend/querymiddleware/limits.go
pkg/streamingpromql/engine_test.go
pkg/streamingpromql/query.go

This PR improves the information logged in query traces when an error occurs:
* MQE will now log whether the query succeeded or failed, and if it failed, what the error was.
* Query-frontends will log the error returned by queriers, if any.
I've opted not to add a changelog entry given this only affects tracing.
(none)

Include more error information in query traces

---

tools/kafkatool/dump.go

Adds option to print WriteRequests as JSON when debugging Kafka dumps.

kafkatool: print write requests as JSON

---

go.mod
go.sum
vendor/github.com/prometheus-community/parquet-common/search/materialize.go
vendor/modules.txt

Brings latest parquet-common with minor changes

chore: upate parquet-common dependency

---

GOVERNANCE.md
MAINTAINERS.md

Vote passed awhile back with majority approvals no objections.
Welcome @jesusvazquez !

Add Jesús Vázquez as maintainer

---

integration/store_gateway_limits_hit_test.go

closes https://github.com/grafana/mimir/issues/12485
see https://github.com/grafana/mimir/issues/12485#issuecomment-3337732171 for more details

Fix flaky Test_MaxSeriesAndChunksPerQueryLimitHit

---

docs/sources/mimir/manage/monitor-grafana-mimir/deploying-monitoring-mixin.md

docs: fix 404 link for metamonitoring

---

CHANGELOG.md
pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/distributor/validate.go
pkg/distributor/validate_test.go

Adds warning log when a label value gets truncated or dropped.
Followup of #12627

distributor: Warn on truncated or dropped label value

---

pkg/frontend/querymiddleware/astmapper/sharding.go
pkg/frontend/querymiddleware/astmapper/sharding_test.go

Manually backport https://github.com/grafana/mimir/commit/626e9a1815a503d6a6957100596554ab5f666aa7 from https://github.com/grafana/mimir/pull/12921

[r362] Fix more issues where some binary expressions aren't sharded

---

AGENTS.md

This pull request adds a new documentation file, `AGENTS.md`, which provides comprehensive authoring guidelines for [Docs AI toolkit](https://github.com/grafana/docs-ai/tree/main) documentation. The document outlines standards for writing style, structure, terminology, formatting, and technical content, ensuring consistency and clarity across documentation.
Documentation standards and structure:
* Introduces detailed instructions for writing documentation in Markdown, including section organization, use of headings, front matter, and introductory content.
* Specifies language and style guidelines, such as using active voice, present simple tense, second-person perspective, and preferred terminology (e.g., "allowlist" instead of "whitelist").
Formatting and technical guidance:
* Provides …

Add AGENT.md for docs ai

---

pkg/parquetconverter/parquet_converter.go

To better understand what we enqueue

parquet-converter: add logs on enqueue
