- docs/sources/helm-charts/mimir-distributed/release-notes/v5.2.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
This includes the backport of #7199 in #7201
Closes https://github.com/grafana/mimir/issues/7196
> Helm: release 5.2.1

- CHANGELOG.md
- operations/mimir-tests/test-all-components-with-custom-max-skew-generated.yaml
- operations/mimir-tests/test-all-components-with-custom-max-skew.jsonnet
- operations/mimir/config.libsonnet
- operations/mimir/ruler.libsonnet
I have an use where I need to set the ruler-querier max skew differently than the querier. Right now they're coupled together. In this PR I propose to add a dedicated config option for the ruler-querier.
N/A
> Jsonnet: allow to configure ruler-querier max skew separately from querier

- integration/ca/ca.go
> downgrade integration test certificate elliptic curve algo for boringcrypto FIPS-only compatibility

- CHANGELOG.md
- integration/querier_tenant_federation_test.go
- pkg/frontend/querymiddleware/cardinality_query_cache.go
- pkg/frontend/querymiddleware/labels_query_cache.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
Today I noticed that the `op` label value reported by `cortex_query_frontend_queries_total` may be wrong because it uses `op="query"` for any non range query. This PR fixes it, using the same label values we use for caching metrics.
N/A
> Fix 'op' label values for cortex_query_frontend_queries_total metric

- pkg/distributor/distributor_test.go
- pkg/distributor/query_test.go
This PR is a prerequisite to the work that @pstibrany, @pracucci and I are doing to support a ring for partitions.
The major changes in this PR are:
* add the ability to specify ingester state by zone; this allows to have a different number of failing ingesters per zone; this is useful in testing the ring retry mechanisms
* add the ability to specify ingester ring state by zone
* add the ability to inject data into `mockIngester`s; this removes the need to push data to ingesters in order ot test query logic. This is necessary when testing ingest storage and removes the need to spin up a kafka-compatible backend and consume from it in order to assert on querying logic
[These are the kind of tests this PR enables](https://github.com/grafana/mimir/blob/1e69638e7a522ea9da2b2c64ec96804b8f0cde80 …
> distributor: make unit tests more flexible

- pkg/storage/tsdb/block/fetcher.go
In this PR I'm removing superfluous `errors.Cause()` usage in `pkg/storage`. This usage of `errors.Is(errors.Cause(), ...)` was introduced in https://github.com/grafana/mimir/pull/3288 when removing Thanos dependency.
The reason why `errors.Cause()` is superfluous is because `errors.Is()` already navigates the chain of wrapped errors, so we don't have to look at the `Cause()` of an error. I've checked all places where these errors are returned, and they're all correctly wrapped with `errors.Wrap()` (so `errors.Is()` is enough). In addition, for the errors returned by `ReadMarker()`, in other places in the code we just check the same errors using only `errors.Is()`, another signal that `errors.Cause()` is not needed.
_Note: this PR is part of a work I'm doing to completely remove …
> Chore: remove superfluous errors.Cause() usage in pkg/storage

- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/storegateway/bucket.go
- pkg/storegateway/gateway_test.go
We have few usage of `errors.Cause()` in the store-gateway and the querier which I believe being superfluous. The usage addressed by this PR is `status.FromError(errors.Cause(err))`. The actual `status.FromError()` implementation internally uses `errors.As()` (which navigates the chain of wrapped errors), so we shouldn't need `errors.Cause()`.
The `errors.Cause()` in `shouldStopQueryFunc()` was introduced by #4100 which also introduced the integration test `Test_MaxSeriesAndChunksPerQueryLimitHit`. The integration test passes on top of this PR. As a counter proof, of we completely remove the `status.FromError()` check from `shouldStopQueryFunc()`, then the `Test_MaxSeriesAndChunksPerQueryLimitHit` integration test fails.
_Note: this PR is part of a work I'm doing to completely remove …
> Remove errors.Cause() usage from store-gateway and its clients

- pkg/querier/cardinality_analysis_handler.go
In this PR I'm removing `errors.Cause()` from `respondFromError()`, which is only used by the cardinality analysis handler. The `errors.Cause()` was passed to `httpgrpc.HTTPResponseFromError()` which, in turn, passes the error to `grpcutil.ErrorToStatus()`. `grpcutil.ErrorToStatus()` ([see code](https://github.com/grafana/dskit/blob/main/grpcutil/status.go#L22-L36)) uses `errors.As()` (which navigates the chain of wrapped errors), so the `errors.Cause()` usage should be superfluous.
_Note: this PR is part of a work I'm doing to completely remove errors.Cause() from Mimir._
N/A
> Remove errors.Cause() usage from cardinality analysis handler

- pkg/distributor/distributor_test.go
This is a follow-up from https://github.com/grafana/mimir/pull/7205#discussion_r1465965281
> distributor: use pointers to mockIngester in tests

- Makefile
- pkg/distributor/distributor_test.go
- pkg/distributor/errors_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/ingester/client/circuitbreaker_test.go
- pkg/ingester/client/mimir_util_test.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester_test.go
- pkg/mimir/grpc_push_check_test.go
- pkg/querier/worker/scheduler_processor.go
- pkg/ruler/compat.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/gateway_test.go
- pkg/storegateway/limiter_test.go
- pkg/util/grpc_error_test.go
In the review of https://github.com/grafana/mimir/pull/7213 I've learned from @duricanikolic that:
> I have worked on the error handling improvement on the write path, and I ensured that most of the usages of the `status` packages there were from `gogo` instead of `grpc`. 
> What is the difference? 
> On one side, `gogo`'s `status` package allows you to easily add custom error details, which are crucial for the error handling on the write path. On another side, `status.FromError()` **doesn't use** `errors.As()` internally.
> Related to `grpc`'s `status` package, it is not easy to add custom error details, but `status.FromError()` uses `errors.As()` internally.
> In order to minimizes differences between different packages used, I then implemented …
> Do not use grpc/status.FromError() and gogo/status.FromError()

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/alertmanager_test.go
- pkg/alertmanager/multitenant.go
Some very simplistic follow-up from #6898
- Move the changelog entry to the right place
- Add documentation about experimental features on `about-versioning`
- New boolean flags tend to be suffixed with the word "enabled" if it makes sense
- Minor fix to the flag documentation to aling with the changelog
- I fixed my own typo from #6682 in the changelog
> Alertmanager: Support UTF-8 characters in matchers and labels small followup

- Makefile
- pkg/alertmanager/distributor.go
In Mimir we had very few places where we used `errors.Cause()`, which I've removed in https://github.com/grafana/mimir/pull/7212, https://github.com/grafana/mimir/pull/7213 and https://github.com/grafana/mimir/pull/7214.
In this PR I'm proposing to add a failling rule to ensure we don't use `errors.Cause()` anywhere in our codebase. I'm also addressing a last `errors.Cause()` which I've forgot earlier.
Why? `errors.Cause()` only work on errors wrapped by `github.com/pkg/errors`, while it doesn't work on errors wrapped by golang standard errors package. In Mimir we currently use `github.com/pkg/errors` but other vendors we depend on (e.g. Prometheus) just uses the standard `errors` package. I prefer to not question whether the `errors.Cause()` usage is safe or not: it's just easier to …
> Ensure we never use errors.Cause()

- tools/copyblocks/Dockerfile
This PR adds Dockerfile for `tools/copyblocks`. This allows manual builds of docker image, eg.:
```
make tools/copyblocks/.uptodate
```
or
```
make BUILD_IMAGE=grafana/mimir-build-image IMAGE_PREFIX=myrepo/ push-multiarch-tools/copyblocks/.uptodate
```
This also enabled building of docker image during releases or weekly builds.
(Asked internal IT to create new grafana/copyblocks repository for this to work.)
> Add Dockerfile for tools/copyblocks

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/rollout-progress.libsonnet
We have some cells where we have multiple deployments (10+) for the same workload. They make the rollout progress dashboard unreadable.
In this PR I'm extracting the `label_replace(...)` calls from the "Rollout progress" panel into an array in the config, so users can extend that with their workload matchers.
I also used this opportunity to:
- Replace `cortex_service` label with `workload`.
- Change query from regexp-matching on the metric name to kube_statefulset_... or kube_deployment_...: this is required for Adaptive Metrics to correctly process this metric name lookup.
With default configuration, this doesn't make any user-facing change.
Fixes an internal report.
> Extensible "Rollout progress" workload grouping

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/nginx-configmap.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
This PR is proposed to address issue #2845, which manifests as an HTTP 426 error when performing various operations with Mimir deployed in a Kubernetes namespace with Istio injection enabled.
This PR sets the `proxy_http_version` directive to 1.1 in the Nginx configuration of Mimir. This change allows Mimir's Nginx to work harmoniously with the Istio Envoy sidecar. In our modern system architecture, the use of HTTP/1.1 is becoming increasingly crucial for the effective operation of service mesh architectures like Istio. 
The issue addressed by this PR can be reproduced using the following steps:
1. Enable Istio injection in your Kubernetes namespace.
2. Start Mimir from Helm chart 3.1.
3. Perform various operations (Read/Write/Others).
**Expected behavior**: The Read/Write path should …
> Enable Nginx Proxy HTTP/1.1 in Mimir for Istio Envoy Sidecar Compatibility

- integration/ruler_test.go
Related to https://github.com/grafana/mimir/issues/4857
This test is flaky and it's always flaky with the same failure - the first sample's value is 4 instead of 2 here: 
https://github.com/grafana/mimir/blob/9313dfc583103f202644ab10a5966efe332be5bb/integration/ruler_test.go#L314
My hypothesis is that when `now.Add(-evaluationDelay)` is done the time range `[now.Add(-evaluationDelay), now]` may becomes so very slightly smaller than `evaluationDelay` (`5m`) when taken with the `1s` step. This results in sending a query which doesn't quite include the `5m` of samples, but `4.99999(9)m` of samples, which excludes the first sample with value `2` and returns `4` instead.
I couldn't get the test to fail locally, so I'm changing the assertion type to not abort the test on the first mismatch so …
> ruler: add more details to failures for TestRulerEvaluationDelay

- docs/sources/mimir/manage/mimir-runbooks/_index.md
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
- pkg/mimirpb/custom.go
- pkg/util/globalerror/errors.go
Currently, distributor's sample histogram validation does not check the schema number before reducing resolution. However, histogram samples with schemas outside the [-4..8] range should be rejected. This PR introduces that check.
Fixes #7230 
> Native histogram: validate schema number before reducing resolution

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- integration/alertmanager_test.go
- pkg/alertmanager/alertmanager_config_test.go
- pkg/alertmanager/multitenant.go
- vendor/github.com/prometheus/alertmanager/matchers/compat/metrics.go
- vendor/github.com/prometheus/alertmanager/matchers/compat/parse.go
- vendor/github.com/prometheus/alertmanager/notify/email/email.go
- vendor/modules.txt
This commit updates Alertmanager to commit cab8ecb, which includes pull request [#3686](https://github.com/prometheus/alertmanager/pull/3686). This pull request changes a number of metrics related to UTF-8 support from gauges to counters.
> Update Alertmanager to latest main

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- integration/alertmanager_test.go
- pkg/alertmanager/alertmanager_config_test.go
- pkg/alertmanager/multitenant.go
- vendor/github.com/prometheus/alertmanager/matchers/compat/metrics.go
- vendor/github.com/prometheus/alertmanager/matchers/compat/parse.go
- vendor/github.com/prometheus/alertmanager/notify/email/email.go
- vendor/modules.txt
This pull request updates the r275 branch with https://github.com/grafana/mimir/pull/7254 as discussed on Slack [here](https://raintank-corp.slack.com/archives/C9KL8THCY/p1706611104496719).
> Update Alertmanager to cab8ecb (#7254)

- tools/tsdb-chunks/main.go
- tools/tsdb-print-chunk/main.go
In #7219 we updated `mimir-prometheus` to https://github.com/grafana/mimir-prometheus/commit/c2a5e1599c5678514ab70be1723a1ebd0d6287da. Additionally, the PR adapted calls to prometheus' `chunkenc.Iterator.AtHistogram()` and `chunkenc.Iterator.AtFloatHistogram()` in `tools/tsdb-chunks` and `tools/tsdb-print-chunk` to reuse the memory of a histogram provided as an argument. Unfortunately, a bug illustrated by the following code was introduced:
```
it := ch.Iterator(nil) // an instance of chunkenc.Iterator
var (
h  *histogram.Histogram      // supposed to be reused in the loop, but it is never assigned a value
fh *histogram.FloatHistogram // supposed to be reused in the loop, but it is never assigned a value
)
for valType := it.Next(); valType != chunkenc.ValNone; valType = it.Next() {
switch …
```
> Reuse Histogram objects in tools/tsdb-chunks and tools/tsdb-print-chunk

- CHANGELOG.md
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_store_metrics.go
- pkg/storegateway/stats.go
Add an `out_or_order` label to the count of blocks queried by level and source. This helps with confirming the reason for non-compacted blocks being queried by the store-gateways.
N/A
> Include out-or-order label in blocks queried metric

- CHANGELOG.md
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/mimir/sanity_check.go
- pkg/ruler/rulestore/config.go
- pkg/ruler/rulestore/local/local.go
- pkg/ruler/rulestore/local/local_test.go
- pkg/ruler/storage.go
Add support for the `/config/api/v1/rules/{namespace}/{groupName}` in the ruler's "local" store.
Note, the changes ended up a bit more involved, than what we anticipated originally. That is, in order for "local" store to follow the `rulestore.RuleStore` interface, the backend must return the sentinel errors, defined along with the interface. This created a circular dependency between the `rulestore` and `local` packages due to how the configs were laid out. The choice the PR made to resolve that, is to move the `local`'s config outside the package, close to `rulestore.Config` (see the actual changes).
Fixes #6632
> rulestore/local: add support for GetRuleGroup endpoint

- CHANGELOG.md
- pkg/storage/tsdb/bucketindex/index.go
- pkg/storage/tsdb/bucketindex/index_test.go
- pkg/storage/tsdb/bucketindex/updater_test.go
- pkg/storegateway/stats.go
Follow-up to #7262 that adds a `out_of_order` field to the bucket index, allowing out of order information to be visible to store gateways, via their metadata fetching, for use in metrics.
> Add out of order field to block index

- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
This PR adds various changes to the `shardActiveSeriesMiddleware` middleware to improve performance when merging responses if sharding is enabled.
In order to validate the changes, an additional benchmark named `BenchmarkActiveSeriesMiddlewareMergeResponses` has been included, which was executed before and after.
Below is the comparative table of these results.
```
name                                                      old time/op    new time/op    delta
ActiveSeriesMiddlewareMergeResponses/num-responses-2-8      6.12µs ± 1%    7.60µs ± 0%  +24.10%  (p=0.008 n=5+5)
ActiveSeriesMiddlewareMergeResponses/num-responses-4-8      8.32µs ± 2%    8.81µs ± 1%   +5.86%  (p=0.008 n=5+5)
ActiveSeriesMiddlewareMergeResponses/num-responses-8-8      11.9µs ± 1%    10.7µs ± 1%  -10.33%  (p=0.008 …
```
> frontend: improve `shardActiveSeriesMiddleware` performance when merging responses

- CHANGELOG.md
- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
This PR improves two things related to `shardActiveSeriesMiddleware`:
1. It fixes a race condition in how the middleware streams snappy-compressed response.
The code uses `s2.Writer`, which isn't goroutine-safe. The middleware cannot reuse the `Writer` between concurrent requests. This is a fixup for #6784.
2. Remove flaky (and redundant) test.
Related to #7280. The `Test_shardActiveSeriesMiddleware_RoundTrip_ResponseBodyStreamed` test looks into the internal implementation details, specifically the size of the buffer pools and the implementations of jsoninter's streaming.
I don't think this test adds extra guaranties to the packages API, and I suggest we just remove it, rather than trying to stabilize it. 
cc @flxbk @ortuman as you seem to work on this part very recently
Fixes #7280
> querymiddleware: Fix race condition in shardActiveSeriesMiddleware

- pkg/mimirtool/client/client.go
- pkg/mimirtool/commands/analyse_prometheus.go
- pkg/mimirtool/commands/loadgen.go
- pkg/mimirtool/commands/remote_read.go
- pkg/ruler/remotequerier.go
- pkg/util/version/info.go
We've noticed, that the requests from GEM's ruler don't include the build information in the `User-Agent` header. After an internal discussion, we think that, even though this is somewhere specific to GEM, fixing it universally on the mimir's side wouldn't hurt.
> ruler: build user-agent header at runtime

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
`KubePersistentVolumeFillingUp` is not a Mimir alert, but it's a very common one when deploying Mimir in K8S. In this PR I propose to upstream a slightly modified version of an internal runbook we have at Grafana Labs for this alert.
Note: I've added @aknuds1 as `Co-authored-by` in the commit, because it did most of the work in the internal runbook and I don't want such credit to be lost.
N/A
> Add KubePersistentVolumeFillingUp runbook

- pkg/compactor/blocks_cleaner.go
- pkg/compactor/bucket_compactor.go
- pkg/compactor/bucket_compactor_e2e_test.go
- pkg/compactor/bucket_compactor_test.go
- pkg/compactor/compactor.go
- tools/compaction-planner/main.go
This PR removes obsolete and unnecessary parameter for NoCompactionMarkFilter.
https://github.com/grafana/mimir/pull/7299#discussion_r1478280436
> Internal: remove unnecessary parameter to NoCompactionMarkFilter

- integration/compactor_test.go
- pkg/compactor/compactor_test.go
- pkg/storage/tsdb/block/block_generator.go
- pkg/storegateway/bucket_stores_test.go
- tools/tsdb-chunks/main_test.go
- tools/tsdb-index-health/main_test.go
- tools/tsdb-print-chunk/main_test.go
While working on https://github.com/grafana/mimir/pull/7293 I've noticed that the 1st parameter passed to `GenerateBlockFromSpec()` is unused. In this PR I'm removing it.
N/A
> Chore: removed unused parameter from GenerateBlockFromSpec()

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ingester/client/circuitbreaker.go
- pkg/ingester/client/circuitbreaker_test.go
- pkg/ingester/client/client.go
This PR does the following things:
- it restricts the circuit breaker failure condition on ingester's deadline exceeded and per-instance limit errors
- it reduces the default value for `-ingester.client.circuit-breaker.cooldown-period` from `1m` to `10s`
> Open circuit breakers on timeouts and per-instance limit errors only

- pkg/mimirtool/commands/alerts.go
This commit does the same as we did for amtool in prometheus/alertmanager#3713. There is no need to register these metrics, so we use `compat.NewMetrics(nil)` instead of `compat.RegisteredMetrics`.
> Do not register compat metrics in mimirtool

- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/ingester/client/circuitbreaker.go
- pkg/ingester/client/circuitbreaker_test.go
This PR introduces a new error type, `client.ErrCircuitBreakerOpen`, that wraps Fail-safe's `circuitbreaker.ErrOpen` error and that provides the remaining delay after which a call to the corresponding client may be retried, via the `RemainingDelay()` function. 
In case of a `client.ErrCircuitBreakerOpen` error, calls to `/distributor.Distributor/Push` and `/api/v1/push/` endpoints will return errors with gRPC code `codes.Unavailable` and HTTP status code `503` respectively.
> Circuit breakers: add client.ErrCircuitBreakerOpen type

- CHANGELOG.md
- pkg/storegateway/bucket_stores.go
In the PR which added this metric #6074, the motivation was to help detect compactors which are falling behind. There is another metric `cortex_bucket_store_series_blocks_queried` added by @jhalterman in #7112 which serves better the purpose of detecting uncompacted blocks. The reason is that it has an explicit label for uncompacted blocks (`source`), and it also is more sensitive to recent blocks (assuming those are queried much more often than old uncompacted blocks).
> store-gateway: remove cortex_bucket_store_blocks_loaded_by_duration

- CHANGELOG.md
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
These changes improve the internals of the retries in `ruler.RemoteQuerier`. That is, the calls inside `Query` shouldn't retry, if it stumbles upon a well-known non-retriable errors.
Fixes #6609
> ruler: don't retry on non-retriable error

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
We got feedback that logging `status=success` in "query stats", when downstream replied with an unsuccessful response is confusing.
This PR improves "query stats" logging, making query-frontend to logs `status=failed` if the original response wasn't an HTTP 2xx. I.e. (formatted for readability):
```
level=info user=12345 msg="query stats" component=query-frontend
method=GET path=/api/v1/query
···
status=failed
err="downstream replied with Internal Server Error (500)"
```
cc @krajorama
> frontend/transport: Log non-2xx replies from downstream as unsuccesful

- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
In https://github.com/grafana/mimir/pull/7290#pullrequestreview-1862270232 @pracucci suggested adding snappy writer to the existing benchmarks of the middleware. This PR splits `BenchmarkActiveSeriesMiddlewareMergeResponses` into two categories: with and without snappy encoding.
After comparing the with/without results, and since it seems that, shard activity series is a part of some warm path in GEM, I decided it's worth it to pool snappy writer. Here are the results before and after the optimization:
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/mimir/pkg/frontend/querymiddleware
│ /Users/v/tmp/bench-1.txt │      /Users/v/tmp/bench-2a.txt      │
│          sec/op          │    sec/op     vs base               │
ActiveSeriesMiddlewareMergeResponses/encoding=snappy/num-responses-2 …
```
> querymiddleware: Pool snappy writer in shard activity series

- CHANGELOG.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
Fix typo beaching->breaching.
Fixes a typo
N/A
- [N/A] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> [Docs] Update migrate-from-single-zone-with-helm.md

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
Previously, disabling metric relabelling would also disable label sorting, which means unsorted labels may be passed to ingesters, which fail to compact later.
Fixes https://github.com/grafana/mimir/issues/7320
> Always sort labels in distributors

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
While reviewing the usage of the ingesters ring lifecycler, as part of the work we're doing to introduce an experimental ingest storage based on Kafka, I've noticed that we still have checks that were originally introduced (in Cortex) as part of the blocks transfer feature we had. The blocks transfer was a feature that allowed a shutting down ingester to transfer its blocks to another ingester before terminating the process. This feature was soon removed from Cortex and never existed in Mimir.
In this PR I propose to remove the checks we do on the ingester's state, that were introduced for the blocks transfer. This means that, after this PR, blocks can be compacted and shipper whatever is the state of the ingester in the ring (which shouldn't be an issue IMO) and same for the TSDB …
> Do not check for ingester ring state before creating TSDB, or compacting / shipping blocks

- pkg/compactor/bucket_compactor.go
In `BucketCompactor.runCompactionJob`, blocks and directories of blocks to compact get logged and included in error messages as `fmt.Sprintf("%v", blocksToCompactDirs)`. The problem with this simplistic string formatting is that it becomes difficult to tell the blocks/directories apart. I think comma separating the items makes for user-friendlier output (it's no fun getting confused when trying to diagnose an error).
As suggested by @pstibrany, I'm also dropping the directory path to the blocks in log/error messages, instead just outputting the block IDs themselves. Plus harmonizing log message field names as "blocks" and "block_count".
- [na] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, …
> Compactor: String format compaction plan as comma separated blocks

- CHANGELOG.md
- packaging/nfpm/mimir/mimir.service
remove reload from systemd file as mimir does not take into account SIGHUP.
It can be unnoticied as mimir will die upon receiving SIGHUP and systemd will pick it up and restart it.
> Packaging: remove reload from systemd file as mimir does not take into account SIGHUP

- CHANGELOG.md
- docs/sources/mimir/references/http-api/index.md
Remove marking of OTLP distributor endpoint as experimental. Since OTLP is now GA, it doesn't really make sense to consider it experimental any longer.
> Docs: No longer mark OTLP endpoint as experimental

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/api.go
Change `-distributor.enable-otlp-metadata-storage` flag to default to true, and deprecate it. The reason is the OTLP endpoint is considered GA, and we have been running with this flag enabled in Grafana Cloud for a long time. Confirmed with @gouthamve that dropping the ability to disable OTLP metadata conversion is OK at this point.
Also making sure to remove "OTLP ingestion path" from docs/sources/mimir/configure/about-versioning.md, which was omitted in an earlier [PR](https://github.com/grafana/mimir/pull/7348).
> Distributor: Make `-distributor.enable-otlp-metadata-storage` flag default to true, and deprecate

- CHANGELOG.md
- pkg/compactor/job.go
- pkg/compactor/job_test.go
This PR excludes out-of-order blocks when deciding if a job should be filtered based on whether the first level compaction wait period has elapsed. This ensures that out-of-order blocks, which may be uploaded late, do not prevent compaction for a job containing blocks that were uploaded earlier.
Fixes #7279
I ran this for a day with many OOO blocks being created, and did not observe any compactions being skipped due to OOO blocks.
> Do not consider out-of-order blocks when filtering compactable jobs

- CHANGELOG.md
- pkg/mimir/mimir.go
- vendor/github.com/grafana/dskit/spanprofiler/README.md
- vendor/github.com/grafana/dskit/spanprofiler/spanprofiler.go
- vendor/github.com/grafana/dskit/spanprofiler/tracer.go
- vendor/modules.txt
Similar to https://github.com/grafana/tempo/pull/3276 and https://github.com/grafana/loki/pull/11633 this PR updates the tracing setup by injecting span profiler into the Mimir's tracer. This should allow a user to focus only on the profiling samples, related to a particular trace.
Part of grafana/mimir-squad#1894
> mimir: Inject span profiler into tracer

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/ingester/ingester.go
- pkg/storage/tsdb/config.go
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/github.com/prometheus/prometheus/tsdb/head.go
- vendor/modules.txt
- Vendors the `main` branch from https://github.com/grafana/mimir-prometheus, which includes https://github.com/grafana/mimir-prometheus/pull/597
- Adds an experimental `blocks-storage.tsdb.timely-head-compaction` flag, allowing timely head compaction, which defaults to `false`.
Fixes #7306
> Add timely head compaction support

- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-autoscaling.jsonnet
- operations/mimir/autoscaling.libsonnet
Fixes an issue where the CPU parsing method sometimes returns an integer and sometimes returns a string.
N/A
> Fix type error in autoscaling jsonnet

- CHANGELOG.md
- docs/sources/mimir/references/http-api/index.md
- pkg/api/api.go
- pkg/compactor/blocks_cleaner.go
- pkg/compactor/blocks_cleaner_test.go
- pkg/compactor/compactor.go
- pkg/compactor/compactor_tenants.gohtml
- pkg/compactor/planned_jobs.gohtml
- pkg/compactor/planned_jobs_http.go
- pkg/compactor/planned_jobs_http_test.go
This PR adds admin page that displays compaction jobs computed from bucket index. This is same output as produced by `tools/compaction-planner` tool, without the need to provide all necessary configuration via CLI flags, since compactor already has all the required configuration.
Page allows to experiment with different merge shards and split counts, and it can also show which compactor is expected to own (and run) the job based on current state of the ring. (Screenshot was created with only one compactor in the ring)
> Add page for displaying compaction jobs computed from bucket-index.

- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer_test.go
@dimitarvdimitrov reported me that `TestPartitionReader_WaitReadConsistency` is flaky. We've seen it failing in [this CI run](https://github.com/grafana/mimir/actions/runs/7813347044/job/21312292344?pr=7309) because of:
```
--- FAIL: TestPartitionReader_WaitReadConsistency (0.00s)
--- FAIL: TestPartitionReader_WaitReadConsistency/should_return_after_all_produced_records_up_have_been_consumed (1.02s)
reader_test.go:128: produced 2 records
reader_test.go:137: consumed records: [record-1]
reader_test.go:148: started waiting for read consistency
reader_test.go:153: finished waiting for read consistency
reader_test.go:145: consumed records: [record-2]
writer_test.go:394: 
Error Trace:	/__w/mimir/mimir/pkg/storage/ingest/writer_test.go:394
/__w/mimir/mimir/pkg/storage/ingest/reader_test.go:132 …
```
> Fix TestPartitionReader_WaitReadConsistency flakyness

- CHANGELOG.md
- pkg/frontend/querymiddleware/shard_active_series.go
This makes sharded active series queries abort response streaming once the request context is cancelled. Without this, processing would continue in the background even after requests are cancelled by the client.
> active series: abort streaming on context cancelled

- pkg/ingester/ingester.go
- pkg/ingester/ingester_ingest_storage_test.go
This PR fixes tiny bug in `/ingester/prepare-partition-downscale` endpoint: `DELETE` method (= cancellation of downscale) will switch partition to `Active` state only if it was `Inactive`. Previously this could switch `Pending` -> `Active` too early, which is undesired.
This endpoint is supposed to work together with rollout-operator, and rollout-operator calls this endpoint with `DELETE` method regularly.
During tests, unrelated problem was discovered with initialization of usage stats metrics. This will be fixed in separate PR.
> prepare-partition-downscale: Switch to Active state only if partition is currently Inactive.

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
This PR makes usage-stats variables package-global to avoid panics when initializing them in multiple parallel tests at once.
Example panic:
```
panic: Reuse of exported var name: github.com/grafana/mimir/ingester_inmemory_series
[recovered]
panic: Reuse of exported var name: github.com/grafana/mimir/ingester_inmemory_series
goroutine 72 [running]:
testing.tRunner.func1.2({0x10460ac80, 0x14000a04290})
/opt/homebrew/opt/go/libexec/src/testing/testing.go:1545 +0x1c4
testing.tRunner.func1()
/opt/homebrew/opt/go/libexec/src/testing/testing.go:1548 +0x360
panic({0x10460ac80?, 0x14000a04290?})
/opt/homebrew/opt/go/libexec/src/runtime/panic.go:914 +0x218
log.Panicln({0x140008e62d0?, 0x31?, 0x14000819d40?})
/opt/homebrew/opt/go/libexec/src/log/log.go:446 +0x60
expvar.Publish({0x140004e7ec0, …
```
> ingester: Make usagestats vars package-global

- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
This makes the responses used in `BenchmarkActiveSeriesMiddlewareMergeResponses` more realistic.
Using the altered benchmark, it improves performance of the context cancellation check performed in `mergeResponses`.
```
pkg: github.com/grafana/mimir/pkg/frontend/querymiddleware
│   main      │              branch               │
│   sec/op    │   sec/op     vs base              │
ActiveSeriesMiddlewareMergeResponses/seriesCount=10_000/num-responses-4-10     19.05m ± 9%   19.14m ± 1%       ~ (p=0.818 n=6)
ActiveSeriesMiddlewareMergeResponses/seriesCount=10_000/num-responses-16-10    90.16m ± 2%   86.81m ± 2%  -3.72% (p=0.002 n=6)
ActiveSeriesMiddlewareMergeResponses/seriesCount=10_000/num-responses-64-10    422.4m ± 4%   401.8m ± 6%  -4.88% (p=0.002 n=6) …
```
> Make active series benchmark more realistic, improve performance of context cancellation check.

- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
This PR enhances format of activity log entries produced by query-frontend. I investigated a problem today using these logs, and I had to check the code to understand what the initial number means, especially because it was very short (it turned out to be tenantID). I'm also adding `User-Agent` header to the activity log, as this would have helped me to pinpoint the problem faster.
Before:
```
572 POST /prometheus/api/v1/query_range end=1707955800&query=count...
```
After:
```
user:572 UA:our-internal-query-tool POST /prometheus/api/v1/query_range end=1707955800&query=count...
```
- [na] …
> Query-frontend activity log enhancements

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/distributor/query_test.go
This PR, which builds on https://github.com/grafana/mimir/pull/7388, add partitions ring support to the following Distributor functions:
- `LabelNames()`
- `LabelNamesAndValues()`
- `LabelValuesForLabelName()`
- `Distributor.MetricsForLabelMatchers()`
- `Distributor.MetricsMetadata()`
- `Distributor.QueryExemplars()`
- I suggest to review tests with "hide whitespace changes" enabled
N/A
> Add partitions ring support to more Distributor querying functions

- pkg/distributor/distributor.go
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query_ingest_storage_test.go
- pkg/distributor/query_test.go
In this PR I'm adding partitions ring support to `Distributor.UserStats()`. Contrary to https://github.com/grafana/mimir/pull/7393 (which was straightforward) the main difference here is that with the ingest storage we have to account for replication in a slightly different way (see comments in the code).
- I suggest to review with "hide whitespace changes" enabled
N/A
> Add partitions ring support to Distributor.UserStats()

- CHANGELOG.md
- integration/querier_test.go
- integration/store_gateway_limits_hit_test.go
- pkg/compactor/split_merge_compactor_test.go
- pkg/compactor/split_merge_grouper.go
- pkg/compactor/split_merge_grouper_test.go
- pkg/compactor/split_merge_job.go
- pkg/compactor/split_merge_job_test.go
This PR changes the split_merge_grouper's check that's meant to filter recent blocks based on the `highestMaxTime`, to allow jobs where either the:
- maxTime is at least 1 full job range in the past, since users may not have uploaded recent blocks (described in [#7265](https://github.com/grafana/mimir/issues/7265)), but we don't want that to stop compaction from happening.
- max compaction level is 1, since filtering level 1 jobs is [handled separately](https://github.com/grafana/mimir/blob/015ddf691df2488d49013475c1c542a01dbcc3e6/pkg/compactor/bucket_compactor.go#L1002-L1018). This condition allows compaction to proceed more quickly than waiting on the above condition to be met for L1 blocks.
Together, these conditions address users who upload blocks sporadically, where currently …
> Improve compaction of sporadic blocks

- pkg/distributor/distributor.go
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/distributor_test.go
Similarly to previous PRs https://github.com/grafana/mimir/pull/7393 and https://github.com/grafana/mimir/pull/7402, in this PR I'm adding partitions support to `Distributor.ActiveSeries()`. This was an easy one. Just a bunch of tests.
- I suggest to review the diff with "hide whitespace changes"
- Removed the unused `forReplicationSet()`
N/A
> Add partitions support to Distributor.ActiveSeries()

- docs/sources/mimir/references/architecture/components/alertmanager.md
Added a note about using altermanager in monolithic deployment.
PS: I did read the writers-toolkit for links https://grafana.com/docs/writers-toolkit/write/links/. However, I noticed that the rest of the content uses relref. For the sake of consistency I used relref.
Fixes #https://github.com/grafana/mimir/issues/7405
> Note how to run Mimir Alertmanager as part of a monolithic deployment

- pkg/distributor/distributor.go
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/distributor/query_test.go
Similarly to previous PRs https://github.com/grafana/mimir/pull/7393 and https://github.com/grafana/mimir/pull/7402, in this PR I'm adding partitions support to `Distributor.LabelValuesCardinality()`.
Similarly to `UsageStats()`, for `LabelValuesCardinality()` we should track the counters on a per replication set basis in order to get a more accurate count, which is what I did in this PR.
- I suggest to review the diff with "hide whitespace changes"
- I renamed few data structs and functions with the aim of making them easier to read
- Since `LabelValuesCardinality()` was the last missing piece supporting partitions ring, I've been able to remove the deprecated `queryQuorumConfig()` and `getIngesterReplicationSetForQuery()`
N/A
> Added partitions support to Distributor.LabelValuesCardinality()

- integration/configs.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_ring.go
- pkg/ingester/ingester_ring_test.go
- pkg/mimir/mimir.go
- pkg/mimir/mimir_test.go
- pkg/storage/ingest/config.go
The ingest storage requires the zone to be configured on ingesters. It's a requirement on the read path, because we always use the zone-aware tracker to handle read-path quorum. In this PR I propose to add a config validation check.
N/A
> Require ingester zone to be configured when running ingest storage

- CHANGELOG.md
- pkg/compactor/compactor.go
- pkg/compactor/compactor_test.go
- pkg/mimir/mimir.go
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/indexcache/cache.go
- pkg/storegateway/indexcache/cache_test.go
- pkg/storegateway/indexcache/inmemory.go
- pkg/storegateway/indexcache/inmemory_test.go
- pkg/storegateway/indexcache/remote.go
- pkg/storegateway/indexcache/remote_test.go
- pkg/storegateway/indexcache/tracing.go
Instead of using a default TTL of 7d for all index-cache related entries, pick different TTLs based on metadata about the block. This allows entries related to blocks that will be deleted (OOO blocks, 2h, 12h) to expire and be eligible to be evicted sooner than they would otherwise.
This change only sets different TTLs for series entries in the cache since they account for most of the space in the cache.
N/A
> Set series cache TTL different based on block metadata

- pkg/storegateway/bucket.go
- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_chunks_test.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
While working through the `storegateway` code, I found myself being confused with how different parts rely on different "iterators", which all have somewhere similar names, e.g. `seriesChunkRefsSetIterator`, `seriesChunkRefsIterator`, and all implement the same (already defined) interface.
I understand the historic aspects of that, but since the package already has `genericIterator[S]` in some places, I wanted to clean this up a bit, and converge all iterator interfaces into a single `iterator[S]`.
This PR is a very mechanical refactor of the package, which doesn't change any of behaviours of the code.
cc @dimitarvdimitrov
n/a
> storegateway: Reduce number of overlapping iterator interfaces into single iterator[S]

- pkg/ingester/ingester.go
- pkg/ingester/ingester_ingest_storage_test.go
- pkg/ingester/ingester_test.go
- pkg/ingester/limiter.go
- pkg/ingester/limiter_test.go
- pkg/ingester/user_metrics_metadata_test.go
- pkg/ingester/user_tsdb_test.go
- pkg/mimir/modules.go
This PR modifies ingester's `Limiter` code to work with ingest store (partitions ring) as well as ingester ring. ~Based on top of https://github.com/grafana/mimir/pull/7411.~ Rebased on top of `main`.
> Modify ingester's limiter to work with ingest store.

- operations/mimir-mixin/dashboards/alertmanager-resources.libsonnet
- operations/mimir-mixin/dashboards/alertmanager.libsonnet
- operations/mimir-mixin/dashboards/compactor-resources.libsonnet
- operations/mimir-mixin/dashboards/compactor.libsonnet
- operations/mimir-mixin/dashboards/config.libsonnet
- operations/mimir-mixin/dashboards/object-store.libsonnet
- operations/mimir-mixin/dashboards/overrides.libsonnet
- operations/mimir-mixin/dashboards/overview-networking.libsonnet
- operations/mimir-mixin/dashboards/overview-resources.libsonnet
- operations/mimir-mixin/dashboards/overview.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
- operations/mimir-mixin/dashboards/reads-networking.libsonnet
- operations/mimir-mixin/dashboards/reads-resources.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads-resources.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
- operations/mimir-mixin/dashboards/rollout-progress.libsonnet
- operations/mimir-mixin/dashboards/ruler.libsonnet
- operations/mimir-mixin/dashboards/scaling.libsonnet
- operations/mimir-mixin/dashboards/slow-queries.libsonnet
- operations/mimir-mixin/dashboards/tenants.libsonnet
- operations/mimir-mixin/dashboards/top-tenants.libsonnet
- operations/mimir-mixin/dashboards/writes-networking.libsonnet
- operations/mimir-mixin/dashboards/writes-resources.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR adds checks to make sure that dashboard UID hasn't changed accidentally. These UIDs are often referred to from runbooks or other internal links, and changing them accidentally can break the links. ([Mimir CHANGELOG](https://github.com/grafana/mimir/blob/1dbb5529e83930836a7da1e34940ed220fa1df7e/CHANGELOG.md?plain=1#L1878-L1898) also refers to some of them).
> Add dashboard UI check to all dashboards using uid based on filename hash

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- development/mimir-microservices-mode/config/mimir.yaml
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/query_frontend_active_series_test.go
- integration/query_frontend_test.go
- pkg/frontend/transport/roundtripper.go
- pkg/frontend/v1/frontend.go
- pkg/frontend/v2/frontend.go
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/frontend/v2/frontend_test.go
- pkg/frontend/v2/frontendv2pb/frontend.pb.go
- pkg/frontend/v2/frontendv2pb/frontend.proto
- pkg/querier/cardinality_analysis_handler.go
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
- pkg/querier/worker/worker.go
- pkg/scheduler/scheduler_test.go
Some Mimir API endpoints can generate responses with a very large response body. Today, responses are transmitted from queriers to query-frontends via the non-streaming gRPC call
```
rpc QueryResult (QueryResultRequest) returns (QueryResultResponse) { };
```
In case of the `/series` and `/active_series` APIs, the (partial) responses generated by queriers can get so large that they cause the query-frontend handling the request to OOM on unmarshaling the `QueryResultRequest` containing the response. The following example profile from an internal cell demonstrates this behaviour:
While queriers need to accumulate the entire response in memory to be able to deduplicate results from ingesters, query-frontends do not need to bring the full response into memory in all cases. The "active series" …
> Add optional querier response streaming

- CHANGELOG.md
- tools/querytee/proxy.go
- tools/querytee/proxy_backend.go
- tools/querytee/proxy_backend_test.go
Allow using the value of X-Scope-OrgID for basic auth username in the forwarded request if URL username is set as `__REQUEST_HEADER_X_SCOPE_ORGID__`
> query-tee: use X-Scope-OrgID for basic auth

- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This is a fixup for #7413
When `show_rejected_requests_on_writes_dashboard` is set in the config, the code path in `writes.libjsonnet` fails with
```
2024/02/23 19:48:38 RUNTIME ERROR: Unexpected type object, expected array
operations/mimir-mixin/dashboards/writes.libsonnet:(139:20)-(151:22)
During manifestation
```
This is due to how I originally misinterpreted the `{}` in the `if C then {}` as condition C's block:
TIL (1) the `{}` is an actual object, inserted into the resulting JSON.
TIL (2) `jsonnet`'s linter doesn't catch a broken syntax, i.e. `[] + {}`, when this happens inside a dead code.
Note there are no assets to rebuild for the PR, because the mentioned config is unset in mimir. But the problem showed itself in the internal build.
Fixes n/a
> mimir-mixin: Fix "unexpected type object, expected array"

- go.mod
- go.sum
- vendor/github.com/thanos-io/objstore/CHANGELOG.md
- vendor/github.com/thanos-io/objstore/exthttp/transport.go
- vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
- vendor/github.com/thanos-io/objstore/providers/s3/s3.go
- vendor/github.com/thanos-io/objstore/providers/swift/swift.go
- vendor/modules.txt
Reverts grafana/mimir#7351.
The above PR introduced https://github.com/thanos-io/objstore/pull/86, which changes authentication behaviour for GCS to set `option.WithoutAuthentication` whenever a service account is not configured for the bucket client ([diff](https://github.com/thanos-io/objstore/pull/86/files#diff-6f1f01a82332f5074843c222ea2e28118de43aa1a516848fe5b7ef3ac18f8470R97-R98)). As a consequence, auth config set via `GOOGLE_APPLICATION_CREDENTIALS` is ignored.
> Revert "fix(deps): update github.com/thanos-io/objstore digest to a8d75c5 (main)"

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json
- operations/mimir-mixin/dashboards/compactor.libsonnet
- operations/mimir-mixin/dashboards/tenants.libsonnet
- operations/mimir-mixin/dashboards/top-tenants.libsonnet
This PR adds estimated compaction jobs based on bucket-index to Mimir dashboards:
* Compactor
* Tenant
* Top Tenants
> Add estimated compaction jobs based on bucket-index to Mimir dashboards

- CHANGELOG.md
- pkg/scheduler/scheduler.go
`cortex_query_scheduler_queue_duration_seconds` histogram buckets are capped to 10s, but a query could stay in the queue for longer. In this PR I propose to increase the bucket size up to 120s.
N/A
> Add more buckets to cortex_query_scheduler_queue_duration_seconds

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-autoscaling.jsonnet
- operations/mimir/autoscaling.libsonnet
This PR adds support for KEDA's `ignoreNullValues` option for [Prometheus scalers](https://keda.sh/docs/2.13/scalers/prometheus/). This defaults to `"true"` (ie. KEDA returns 0 if query produces no results), and can be set to `"false"` to make KEDA return errors instead. (KEDA expects field value to be string, so our jsonnet converts boolean to string).
> Support KEDA's ignoreNullValues field.

- pkg/querier/batch/batch.go
- pkg/querier/batch/batch_test.go
- pkg/querier/batch/chunk.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/batch/merge.go
- pkg/querier/batch/merge_test.go
- pkg/querier/batch/non_overlapping.go
- pkg/querier/batch/non_overlapping_test.go
- pkg/querier/batch/stream.go
- pkg/querier/batch/stream_test.go
- pkg/querier/querier_test.go
- pkg/storage/chunk/chunk.go
- pkg/storage/chunk/chunk_test.go
- pkg/storage/chunk/prometheus_chunk.go
Prometheus introduced a possibility to optionally reuse the memory area of the given histogram or float histogram to reduce allocation (https://github.com/prometheus/prometheus/pull/13340). 
In #7274  we adapted Mimir's `chunk.Iterator` interface in such a way that its `AtHistogram()` and `AtFloatHistogram()` methods follow the signature of the corresponding methods of Prometheus' `chunkenc.Iterator`, i.e., they now also contain optional arguments of type `*histogram.Histogram` and `*histogram.FloatHistogram` that allow memory allocation optimization. 
In #7219 we adapter signatures of `batch.iteratorAdapter.AtHistogram()` and `batch.iteratorAdapter.AtFloatHistogram()` by adding the optional argument of type `*histogram.Histogram` and `*histogram.FloatHistogram` needed for memory …
> Chunk iterators: Optimize histogram memory allocations

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/overview.libsonnet
This adds requests to the `/api/v1/cardinality/...` endpoints to the Overview dashboard. Series for requests in this category will only be displayed if there have been any requests in the selected time frame.
> Add cardinality API qps to Overview dashboard

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
This PR allow to configure whether or not the gateway's NGINX binds IPv6.
The primary reason to do that is to avoid to duplicate the whole configuration to remove the line `listen [::]:{{ include "mimir.serverHttpListenPort" . }};`
I've purposedely not done it for `nginx` as it is marked as deprecated.
Without this change the deployment of the gateway will fail with the following message if IPv6 is disable at the system level in the whole k8s cluster:
```
/docker-entrypoint.sh: No files found in /docker-entrypoint.d/, skipping configuration
2024/02/19 12:23:08 [emerg] 1#1: socket() :8080 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() :8080 failed (97: Address family not supported by protocol)
```
Fixes #7210
> Helm / Gateway: Allow to configure whether or not NGINX binds IPv6

- docs/sources/mimir/set-up/jsonnet/configure-autoscaling.md
I've found by chance that this section is quite outdated: https://grafana.com/docs/mimir/latest/set-up/jsonnet/configure-autoscaling/#what-happens-if-keda-is-unhealthy
It explains how KEDA worked in the past (KEDA <= v2.8) but this behaviour change on KEDA v2.9 (released a year ago). The PR updated the info the new current one and also adds a link the the high availability configuration from official docs
> fix: Update KEDA related information

- operations/mimir-mixin/alerts/alertmanager.libsonnet
- operations/mimir-mixin/alerts/alerts-utils.libsonnet
- operations/mimir-mixin/alerts/alerts.libsonnet
- operations/mimir-mixin/alerts/autoscaling.libsonnet
- operations/mimir-mixin/alerts/blocks.libsonnet
- operations/mimir-mixin/alerts/compactor.libsonnet
- operations/mimir-mixin/alerts/continuous-test.libsonnet
- operations/mimir-mixin/config.libsonnet
> mixin: add extra alert options

- docs/sources/mimir/manage/run-production-environment/production-tips/index.md
> Docs: Explain why types of caches should be separate

- integration/e2emimir/client.go
- integration/querier_remote_read_test.go
- integration/query_frontend_test.go
- pkg/querier/api/api.go
- pkg/querier/remote_read.go
- pkg/querier/remote_read_test.go
Currently remote-read has conflicting behaviours:
* when returning samples all internal errors are translated to HTTP 400
* when returning chunks all internal errors are translated to HTTP 500
This PR unifies error handling such that:
* all validation errors will return HTTP 400
* all promQL storage errors and all other errors will return HTTP 500
It also adds tests for this in two places
* integration tests: this comes with moving of some code to query remote read from an endpoint
* unit tests in pkg/querier
The PR also moves the content type string to pkg/querier/api since it's a complicated string that was repeated in a few places.
I couldn't really understand the [Prometheus docs](https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/) in terms of the expected return …
> querier: fix remote read error translation

- CHANGELOG.md
- docs/sources/mimir/configure/about-versioning.md
Deprecate the metric cortex_distributor_sample_delay_seconds
cortex_distributor_sample_delay_seconds has served it's purpose
in developing out of order ingestion, however the metric is not
useful in a multi tenant environment.
We'll remove it in 2.14 and may reintroduce it as a
native histogram / tenant if needed later.
Related to: #7154 
> Deprecate metric cortex_distributor_sample_delay_seconds

- CHANGELOG.md
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/mimir/modules.go
The setting has been made per-tenant and moved under limits configuration since Mimir 2.10
See #5312
> Remove the deprecated frontend.cache_unaligned_requests YAML config

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/recording-rules.yaml
- operations/mimir-mixin-compiled-baremetal/rules.yaml
- operations/mimir-mixin-compiled/rules.yaml
- operations/mimir-mixin/jsonnetfile.lock.json
- operations/mimir-mixin/recording_rules.libsonnet
Add native histogram recording rule for cortex_request_duration_seconds. This is one of two main histograms that are included in alerts. The new recording rule is required to be able to drop the classic histograms in the mixin.
Related to: #7154 
- N/a Documentation added.
> mixin: native histogram recording rule: cortex_request_duration_seconds

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
On the Tenants dashboard:
- Adds owned series to the "All series" panel
- Adds in-memory series and owned series per ingester panels
- Moves "Newest seen sample age" panel to the Distributor row
- Moves native histogram panels to the exemplars row (and renames the row)
One side-effect is that the owned series in the "All series" panel is drawn over the in-memory series line, but I think that's ok.
N/A
> [mimir-mixin] Add owned series to tenant dashboard

- CHANGELOG.md
- pkg/compactor/block_upload.go
- pkg/compactor/block_upload_test.go
When user tries to upload block with timestamps in microseconds instead of milliseconds, such timestamps are converted to very distant future dates. By including converted dates in the error message, we make this more clear.
(We have seen multiple support cases about this. Most recently https://github.com/grafana/mimir/discussions/7533).
> Block upload: include converted timestamp in the error message

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/promql/parser/parse.go
- vendor/modules.txt
Upgrade mimir-prometheus to latest main, containing the following change:
* [Cherry-pick "restore ability to match `__name__` multiple times in selector"](https://github.com/grafana/mimir-prometheus/pull/603)
This fixes a bug in  Mimir/Prometheus, where you can't have multiple `__name__` matchers between curly braces in a query. Said bug was introduced in https://github.com/grafana/mimir/pull/7475.
> Upgrade mimir-prometheus to latest main

- docs/sources/mimir/set-up/jsonnet/deploy.md
- operations/mimir-tests/build.sh
- operations/mimir/getting-started.sh
Initialize Tanka with 1.29, [since 1.21 is no longer available](https://github.com/jsonnet-libs/k8s-libsonnet) after [this commit.](https://github.com/jsonnet-libs/k8s-libsonnet/commit/90d0fae415cff9d0c089d60e9a478efee092c42e). This fixes `lint-jsonnet` check ([failure example](https://github.com/grafana/mimir/actions/runs/8157663593/job/22297862889?pr=7508)).
> Initialize Tanka with 1.29.

- development/mimir-microservices-mode/config/mimir.yaml
This is a follow-up to #7521, deleting the removed flag from the docker-compose config for the microservices mode.
> Remove `index_header_lazy_loading_enabled` docker-compose config

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
- pkg/util/gziphandler/gzip.go
The query-frontend uses the value supplied via `-server.http-write-timeout` (default `2m`) to close connections that have not finished writing the response by the deadline. The `/active_series` endpoint can generate large responses, the transmission of which can exceed that deadline. Therefore, this PR introduces a parameter to configure write timeouts for streaming responses (currently only applicable to the `/active_series` endpoint).
> [query-frontend] Set write deadline for `/active_series` requests

- pkg/ingester/ingester.go
- pkg/ingester/ingester_ingest_storage_test.go
- pkg/ingester/ingester_test.go
- pkg/ingester/owned_series.go
- pkg/ingester/owned_series_test.go
This PR modifies "owned series" service to make it work with partitions ring (if ingest storage is configured) as well as ingester ring.
> Make owned series service in ingester work with partitions ring.

- Makefile
- docs/sources/mimir/set-up/jsonnet/deploy.md
- mimir-build-image/Dockerfile
- operations/mimir-tests/build.sh
- operations/mimir/getting-started.sh
Manually backport https://github.com/grafana/mimir/pull/7557 to `r280`.
* chore(deps): update golang docker tag to v1.21.8 (main)
* Update build image version to pr7557-ae15c572b6
* Trigger CI
---------
Co-authored-by: pr00se <pr00se@users.noreply.github.com>
Co-authored-by: Yuri Nikolic <durica.nikolic@grafana.com>
(cherry picked from commit e0a86e6c54e6467b27c638e1655fec5a7fc4d658)
> Update golang docker tag to v1.21.8

- docs/sources/mimir/manage/monitor-grafana-mimir/requirements.md
This PR fixes a query-frontend flag reference that in the **Log labels** section of the requirements doc. The slow queries dashboard relies on log lines associated with the `-query-frontend.query-stats-enabled` parameter, not the `-query-frontend.log-queries-longer-than` parameter.
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
> Update requirements doc with correct frontend parameter

- docs/sources/helm-charts/mimir-distributed/release-notes/v5.2.md
- docs/sources/mimir/set-up/jsonnet/deploy.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/mimir-tests/build.sh
- operations/mimir/getting-started.sh
Releasing Helm chart 5.2.2
- Includes GEM image bump to 2.11.2
Also cherry-picked https://github.com/grafana/mimir/pull/7544 to fix CI
> [Helm] Release 5.2.2

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
This is a follow-up to #7553. I realised that the request context is not cancelled when the server write deadline is reached (see e.g. [here](https://github.com/golang/go/issues/59602)). To avoid doing unnecessary work we should cancel the request context once the deadline is reached.
This change only applies to the `/active_series` endpoint, the behaviour for other endpoints remains unchanged.
> [query-frontend] `/active_series`: cancel request context when write deadline is reached

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/metamonitoring/kube-state-metrics-servmon.yaml
- operations/helm/charts/mimir-distributed/values.yaml
As outlined in #7474, kube-state-metrics, which runs within the k8s cluster, may not expose its service on a (named) port, that Mimir expects. This PR updates the templates in a way, so an operator could overwrite the port, used in kube-state-metrics in the values.
Fixes #7474
> helm: Allow passing port of kube-state-metrics service to meta-monitoring

- pkg/continuoustest/client.go
- pkg/continuoustest/client_test.go
Related to experimental ingest storage, this PR updates mimir-continuous-test to query with read-after-write (strong read consistency) enabled.
n/a
> continuoustest: Query with strong read consistency enabled

- CHANGELOG.md
- integration/ruler_test.go
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
Added new test case in TestRulerMetricsForInvalidQueriesAndNoFetchedSeries
with only the invalid query scenario where the user has entered an
invalid regex, but without selecting all chunks so the chunks limit
doesn't apply.
Since only one error happens, the error is of type errors.errorString
and not fmt.wrapError, which means the code to detect user errors and
cannot type assert to type QueryableError which in turn means it's treated
as a GRPC error, which it is not.
See https://github.com/grafana/mimir/blob/fdf381290fba868d18762c9790ebf543f49d4cc7/pkg/ruler/compat.go#L164
Fix is restricted to local querier execution when GRPC errors are not exposed directly to the ruler.
Fix considers unwrapped errors as panics coming from the PromQL engine, most likely due to user error. Although it's …
> Fix for ruler not honoring user error with local querier

- CHANGELOG.md
This PR fixes some errors found in the CHANGELOG part related to the 2.12 Mimir release.
Part of #7542
> Fix release 2.12-related CHANGELOG errors

- docs/sources/mimir/release-notes/v2.12.md
Now the only linting issue reported by [Vale](https://grafana.com/docs/writers-toolkit/review/lint-prose/) on this file relate to passive voice.
I think we could also work on making the lists more parallel (https://developers.google.com/style/lists).
Notable changes:
1. **Use semantic line breaks:** [Semantic line breaks](https://sembr.org/) are better for future line based diffing in the GitHub UI and result in the same HTML output.
1. **Prefer "refer to" over "see":** https://grafana.com/docs/writers-toolkit/write/style-guide/style-conventions/#links-and-references
1. **Use U.S. English ("minimizing" not "minimising"):** https://grafana.com/docs/writers-toolkit/write/style-guide/inclusive-writing/#write-for-an-international-audience.
1. **Fix some typos**
1. **Use admonitions shortcodes …
> Lint release notes to better match the Grafana Labs style guides

- docs/sources/mimir/release-notes/v2.12.md
This PR prepares release notes for Mimir 2.12.
Part of #7542
> Preparing release notes for 2.12

- CHANGELOG.md
- pkg/continuoustest/client.go
- pkg/continuoustest/otlp_writer.go
- pkg/continuoustest/prometheus_writer.go
I've noticed that continues-test sets `user-agents` header only on the writer side. This PR updates the client, making sure the header is set on all requests.
n/a
> continuoustest: set user-agent for all requests

- CODEOWNERS
Remove technical writer as code owner for internal docs. When another writer takes over, this makes sure they don't get notifications for areas that they're not responsible for.
> Remove technical writer as code owner for internal docs

- pkg/storegateway/bucket.go
Add debug logging in store gateway of non-compacted blocks that are queried. This is useful for being able to investigate individual blocks that end up being unexpectedly queried.
> Log non-compacted blocks queried in store gateway

- CHANGELOG.md
- integration/ruler_test.go
- pkg/storage/tsdb/bucketindex/loader.go
- pkg/storage/tsdb/bucketindex/loader_test.go
Without a cached bucket index the querier will synchronously fetch the bucket index while the query is on hold. If the query is cancelled, then the error will be cached and future queries would return the error until the next periodic bucket index update (after 1 minute).
Fixes https://github.com/grafana/mimir/pull/7586#discussion_r1519814444
> querier: don't cache context.Canceled errors for bucket index

- docs/sources/mimir/manage/monitor-grafana-mimir/requirements.md
cAdvisor metrics also need the `instance` label to match what node_exporter and Mimir have
fixes https://github.com/grafana/mimir/issues/7570
> docs: clarify monitor-grafana-mimir/requirements.md

- CHANGELOG.md
- pkg/mimirtool/commands/loadgen.go
This one fixes the panic in `mimirtool loadgen`
```
› go run ./cmd/mimirtool/ loadgen --write-url='http://127.0.0.1:9009/api/v1/push'
2024/03/14 20:23:59 setting up write load gen:
url=http://127.0.0.1:9009/api/v1/push
parallelism: 10
active_series: 1000
interval: 15s
2024/03/14 20:23:59 query load generation is disabled, -query-url flag has not been set
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100c3892c]
goroutine 95 [running]:
github.com/prometheus/client_golang/prometheus.(*HistogramVec).GetMetricWithLabelValues(0x140008ef080?, {0x1400127be30?, 0x103e3f900?, 0x140015a4000?})
/Users/v/Documents/Code/grafana/mimir-main/vendor/github.com/prometheus/client_golang/prometheus/histogram.go:1165 +0x1c …
```
> mimirtool: fix panic in loadgen command

- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/mimir/grpc_push_check.go
- pkg/mimir/grpc_push_check_test.go
Following #7503 
We noticed that ingest storage may slip from in-flight requests limits, after the deprecated `LimitInflightRequestsUsingGrpcMethodLimiter (default true)` will be removed. These changes update the ingester in way, so the in-flight limits were enforced when ingest storage is used.
The changes also prevent double-counting of the limits, during the migration period, when the ingesters will be deployed with enabled ingest storage, but the distributors will keep using gRPC API.
Fixes n/a
> ingester: Enforce limits for Push requests coming via ingest.Store

- docs/sources/helm-charts/mimir-distributed/release-notes/v5.2.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
In this PR I'm merging the mimir-distributed-release-5.2 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.
> Merge mimir-distributed-release-5.2 to main

- CHANGELOG.md
- pkg/storegateway/bucket.go
The ambient time (`queryStats.streamingSeriesAmbientTime`) is used to observe the `"other"` stage duration in `BucketStore.recordStreamingSeriesStats` after running LabelNames, LabelValues and Series requests.
But `queryStats.streamingSeriesAmbientTime` is only populated for `Series` requests. This results in skewed `"other"` timings.
> store-gateway: record request ambient time for LabelNames and LabelValues

- pkg/mimir/grpc_push_check.go
- pkg/mimir/grpc_push_check_test.go
- pkg/mimir/modules.go
As a follow-up to the changes in #7621, as `ingester` and `distributor` implement the same interface now, we can simplify and clean up internals of the `grpcInflightMethodLimiter` a bit.
n/a
> mimir: simplify grpc in-flight limiter

- pkg/ingester/errors.go
- pkg/ingester/ingester.go
- pkg/ingester/owned_series.go
- pkg/ingester/owned_series_test.go
This PR moves initialization of owned-series service into its own "starting" method. Ingester now fully starts this service before starting lifecyclers. Compared to the state before this PR, this change doesn't really change much -- it just moves code into the service.
We have tried various approaches in this PR, but there are constraints that we need to maintain. 
1. We cannot change ingester to ACTIVE state in the ring, and then reject read or push requests, or we risk outages -- on read path, or write path (eg. during rollouts of multiple zones).
2. Furthermore we prefer to err on under-counting owned series (when ring doesn't have our instance, owned series service will compute 0 owned series), than having incorrect high count of owned series. When we undercount, we allow extra series …
> Owned series: modify owned series lifecycle

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/release-notes/v2.12.md
- pkg/querier/querier.go
This PR is needed for the release of Mimir 2.12.
Experimental CLI flag `-querier.minimize-ingester-requests` has been enabled by default and marked for deletion in Mimir 2.12 in https://github.com/grafana/mimir/pull/6174.
After a more detailed analysis, we realized that this CLI flag might be still needed. Therefore, this PR sets it as advanced.
Part of #7542 
> Move -querier.minimize-ingester-requests from experimental to advanced

- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ruler/compat_test.go
Following #7618, after a follow-up discussion, it makes sense to have an explicit mapping from ingester's `METHOD_NOT_ALLOWED` to an HTTP 5xx.
cc @pstibrany @pracucci 
n/a
> distributor, ruler: expect METHOD_NOT_ALLOWED from pusher

- CHANGELOG.md
- pkg/frontend/transport/handler.go
This closes the response body received by the frontend handler to free the resources associated with it. If this isn't done and the `response.Body` contains a non-noop `io.ReadCloser` it causes a memory leak.
> [query-frontend] Close response body in request handler

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/release-notes/v2.12.md
- integration/ingester_test.go
- integration/querier_test.go
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/distributor/query_ingest_storage_test.go
- pkg/distributor/query_test.go
- pkg/ingester/client/chunkcompat.go
- pkg/mimir/modules.go
- pkg/querier/querier.go
This PR is needed for the release of Mimir 2.12.
Experimental CLI flag `-querier.prefer-streaming-chunks-from-ingesters` has been enabled by default and marked for deletion in Mimir 2.12 in https://github.com/grafana/mimir/pull/6174.
This PR gets rid of this CLI flags.
As a consequence, distributor's configuration option `distributor.Config. PreferStreamingChunksFromIngesters`, that is currently always set to true, should also be removed.
Part of #7542
> Get rid of -querier.prefer-streaming-chunks-from-ingesters

- CHANGELOG.md
- pkg/frontend/transport/handler.go
* [query-frontend] close response body in request handler
(cherry picked from commit eaef37753546273732aa7fc3e10fc670d57a4963)
> [query-frontend] Close response body in request handler (#7654)

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Mention using `node_timex` metrics to diagnose clock skew in runbook.
> Mention using `node_timex` metrics to diagnose clock skew in runbook

- pkg/ruler/mapper.go
Adds a `user` label to some logs emitted by the ruler when it's available.
N/A
> Add user to log messages in the Ruler mapper when relevant

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/jsonnetfile.lock.json
Overview / Query / Sec panel uses 12 colors, but we only have 9 Adding 4 more picked from Grafana UI.
Related to #7678 
- N/A] Tests updated.
> Dashboards: add more non-error colors

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- pkg/ingester/client/ingester.proto
This PR updates regex that matches read-path related gRPC methods on ingesters. Some previously missing methods were added:
* `/cortex.Ingester/QueryExemplars`
* `/cortex.Ingester/LabelNames`
* `/cortex.Ingester/UserStats`
* `/cortex.Ingester/AllUserStats`
* `/cortex.Ingester/LabelNamesAndValues`
* `/cortex.Ingester/LabelValuesCardinality`
* `/cortex.Ingester/ActiveSeries`
All these are read-path queries, but were not accounted for in various dashboards.
> Dashboards: Update regex that matches read-path related gRPC methods on ingesters

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/overview.libsonnet
Instead of 12 different queries, use 2 in the "Queries / sec" panel. One for known routes combined with overrides for legend and color and one for "other".
This will help introducing native histogram version.
Related to #7154 
> dashboards: overview: reduce number of queries by 10

- CHANGELOG.md
- development/mimir-ingest-storage/config/mimir.yaml
- pkg/ingester/active_series.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_ingest_storage_test.go
- pkg/ingester/ingester_test.go
- pkg/ingester/owned_series_test.go
- pkg/storage/ingest/config.go
- pkg/storage/ingest/partition_offset_reader.go
- pkg/storage/ingest/partition_offset_reader_test.go
- pkg/storage/ingest/partition_offset_watcher.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/tsdb/config.go
- pkg/util/grpc_test.go
- pkg/util/time.go
- pkg/util/time_test.go
In this PR I'm proposing to have ingester replaying its partition at startup before it will join the ring and add itself as owner in the partition ring.
When an ingester starts up, either because it was scaled out or a restart occurred (crash, rescheduling, rolling update, …) it performs the following operations in order:
1. Replay its own partition from Kafka, until it’s guaranteed a maximum lag of X seconds
- To guarantee a maximum lag of `-ingest-storage.max-consumer-lag-at-startup` (max lag) seconds, the ingester loops on:
- Get the last committed offset and current local timestamp (CT) when last committed offset has been fetched (response got from Kafka)
- Replay up until the last committed offset
- Stop iterating if “now - CT” <= max lag
1. Start the ingesters lifecycler
- This will …
> Wait ingester to replay partition at startup

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/storage/bucket/s3/bucket_client.go
- pkg/storage/bucket/s3/config.go
- tools/doc-generator/parse/parser.go
This PR adds a new configuration `s3.bucket_lookup_type`, which allows altering the lookup style, the S3 client uses to access the bucket.
As it was raised in #7512 and #7673, minio S3 client's default behaviour is that the client uses virtual-hosted style lookup only for AWS S3. For other S3 compatible services, the client uses path-based style. This creates (or will create) issues to users, who deploy Mimir to S3 compatible services. That is, providers like Tencent, Alibaba, etc are deprecating path-based access to the buckets.
Fixes #7512 #7673
> s3: allow setting bucket lookup type

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/_helpers.tpl
- operations/helm/charts/mimir-distributed/templates/distributor/distributor-so.yaml
- operations/helm/charts/mimir-distributed/templates/query-frontend/query-frontend-so.yaml
- operations/helm/charts/mimir-distributed/templates/ruler/ruler-so.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/distributor/distributor-so.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/query-frontend/query-frontend-so.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/ruler/ruler-so.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/distributor/distributor-so.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/query-frontend/query-frontend-so.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/ruler/ruler-so.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/distributor/distributor-so.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/query-frontend/query-frontend-so.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler/ruler-so.yaml
updates the kedaAutoscaling CPU threshold calculation to use milliCPU instead of CPU cores.
Fixes #7473
> helm: fix kedaAutoscaling CPU threshold calculation

- pkg/storage/ingest/config.go
- pkg/storage/ingest/config_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
Today we had some struggles with Kafka in our test environment and I needed a way to temporarily consume the partition from "end" instead of "last-offset", in order to quickly recover the cluster. In this PR I'm adding a config option to specify from which position you want the partition reader to consume the partition at startup: "last-offset" (default), "start" or "end".
The default option ("last-offset") preserves the current behaviour, so logic hasn't changed. I'm just adding "start" and "end" as new options.
N/A
> Add option to specify from which position to consume a partition at startup

- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/util.go
- pkg/util/testkafka/cluster.go
In this PR I'm adding metrics to `partitionCommitter` in order to have some visibility. The following metrics have been added:
- `cortex_ingest_storage_reader_offset_commit_requests_total`
- `cortex_ingest_storage_reader_offset_commit_failures_total`
- `cortex_ingest_storage_reader_offset_commit_request_duration_seconds` (native histogram)
- `cortex_ingest_storage_reader_last_committed_offset`
N/A
> Add partitionCommitter metrics

- pkg/storage/ingest/reader_test.go
I've seen a flaky run of `TestPartitionReader_ConsumeAtStartup`:
```
--- FAIL: TestPartitionReader_ConsumeAtStartup (0.00s)
--- FAIL: TestPartitionReader_ConsumeAtStartup/should_consume_partition_from_end_if_position=end,_and_skip_honoring_max_lag (1.03s)
reader_test.go:466: produced 2 records before starting the reader
logging.go:33: level warn partition 1 msg starting consumption from partition end (may cause data loss) consumer_group test-group
logging.go:33: level info partition 1 component kafka_client msg immediate metadata update triggered why querying metadata for consumer initialization
logging.go:33: level info partition 1 msg partition reader is skipping to consume partition until max consumer lag is honored because it's going to consume the partition from the end …
```
> Fix TestPartitionReader_ConsumeAtStartup flakyness

- operations/mimir-mixin/dashboards/writes.libsonnet
- pkg/storage/ingest/reader.go
This PR adds `phase` label to `cortex_ingest_storage_reader_receive_delay_seconds` metric to differentiate end-to-end lag when ingesters are starting and catching up
> Distinguish between starting and running phases of ingest reader.

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin-tools/serve/provisioning-datasources.yaml
- operations/mimir-mixin/alerts.libsonnet
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
Following up https://github.com/grafana/mimir/pull/7695, in this PR:
- Added "Ingester (ingest storage - last consumed offset)" row to "Mimir / Writes" dashboard
- Added `MimirIngesterLastConsumedOffsetCommitFailed` alert
Example of the new row added to the Writes dashboard:
N/A
> Add partition commiter dashboard panels and alert

- CHANGELOG.md
- pkg/querier/tenantfederation/merge_queryable.go
This PR adds a native histogram to the mergeQuerier, which observes the time it takes for each upstream querier job to start. 
For users running many tenants, it is possible for the mergeQuerier to need to kick off many jobs ([code](https://github.com/grafana/mimir/blob/70504e61f1f0ed067a4d5a4dd24cbb82c930dc14/pkg/querier/tenantfederation/merge_queryable.go#L340)),  limited to only `tenant-federation.max-concurrent` jobs in parallel. Recording wait time at this point will hopefully give the user insight into whether `tenant-federation.max-concurrent` should be tuned.
- [N/A] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Add a histogram to observe wait time when kicking off mergeQuerier jobs

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
This PR adds clauses to some of our KEDA queries to guard against scenarios that could cause unintended scaledowns. This happens when the prometheus targeted by KEDA is down or unresponsive for some time, which could cause data that is used in KEDA queries to be missed. Without this data, when prometheus comes back up, these queries return lower averages for a while, which can cause unintended scaledowns.
An example of what this looks like from kubectl before, during, and after prometheus going down:
```
NAME                   REFERENCE                TARGETS                                             MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-distributor   Deployment/distributor   1046561m/1k (avg), 1633790418097m/2147483648 (avg)   10        40        29         171d …
```
> Add guard against missing samples in KEDA queries

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/nginx-configmap.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-requests-and-limits-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
This PR produces a clearer error under the circumstance when multiple X-Scope-OrgID headers are received by nginx and combined according to the [HTTP spec](https://www.rfc-editor.org/rfc/rfc9110.html).
This is valid HTTP, but Mimir does not support passing multiple tenants in this way, so the existing error is confusing:
```
tenant ID '...' contains unsupported character ...
```
After this PR, the error is:
```
Sending multiple X-Scope-OrgID headers is not allowed. Use a single header with | as separator instead.
```
Fixes https://github.com/grafana/mimir/issues/7700
> [Helm] Clarify error message when multiple tenant headers are present

- pkg/storegateway/indexheader/stream_binary_reader.go
This PR fixes a typo in the message logged by store-gateways when loading a sparse index-header from disk.
This change seemed minor enough to not require a changelog entry.
(none)
> Fix typo in log message

- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/results_cache_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
Our enterprise product needs to instantiate `DefaultCacheKeyGenerator`. Instead of exposing `codec`, I'm adding `NewDefaultCacheKeyGenerator` and hiding `interval`.
> Introduce New function for DefaultCacheKeyGenerator.

- pkg/frontend/querymiddleware/blocker.go
- pkg/frontend/querymiddleware/blocker_test.go
- pkg/frontend/querymiddleware/cardinality.go
- pkg/frontend/querymiddleware/cardinality_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/instrumentation.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/results_cache_test.go
- pkg/frontend/querymiddleware/retry.go
- pkg/frontend/querymiddleware/retry_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/frontend/querymiddleware/sharded_queryable_test.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
- pkg/frontend/querymiddleware/split_by_instant_interval_test.go
- pkg/frontend/querymiddleware/stats.go
- pkg/frontend/querymiddleware/stats_test.go
- pkg/frontend/querymiddleware/step_align.go
- pkg/frontend/querymiddleware/step_align_test.go
purely renaming
With the Prometheus codec completion work, we recently added the `LabelsQueryRequest` type, where previously the codec only had the `Request` type, which is only intended to represent Range and Instant query requests.
There are more similar types on the way as well (Examplars, Cardinality) & we need to disambiguate.
> disambiguate frontend types: rename frontend Request to MetricsQueryRequest

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
This PR adds new alerts useful when using ingest-storage:
* Alert when ingester is having troubles while reading from Kafka
* Alert when Ingester lag is above threshold (in “running” phase) or lag is increasing (applies to both starting / running phase)
* Alert when ingester is unable to process records and fails with errors (ie. ingester runs into “5xx” errors)
* Alert when we fail to enforce strong consistency
This PR also makes ingesters to ignore context cancellation as error when reading records from Kafka. This "error" is expected when ingesters are shutting down.
> Ingest-storage alerts

- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
Currently, the logic around the last consumed offset which is committed to the Kafka consumer group is a bit convoluted: we don't commit the last consumed offset, but the last consumed offset + 1, which is the offset at which we should start replaying at the next startup.
In this PR I'm clarifying the logic, committing the last consumed offset. Then, when we read it back at `PartitionReader` startup, if we found the committed last consumed offset we'll start replaying from offset + 1.
The logic in this PR is expected to be unchanged, except for the metric `cortex_ingest_storage_reader_last_committed_offset` which is now fixed and track the last consumed offset, instead of the last consumed offset + 1.
N/A
> Clarify logic around partition consumed offset

- .github/workflows/test-build-deploy.yml
Small chore PR to get rid of the "Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20" warnings when running CI in GitHub Actions. 
For more information: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Chore: update actions depending on Node.js 16 to versions depending on Node.js 20

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
In Grafana Cloud I'm rolling out an additional scaling metric, based on in-flight queries (like "querier"), for the ruler-querier. I will upstream the additional scaling metric to OSS jsonnet, as soon as we've done rolling out at Grafana Labs. In the meanwhile I would like to add the additional scaling metric to "Remote rule reads" dashboard.
In this PR you can find a couple of commits:
- [Refactoring: define autoScalingActualReplicas(), autoScalingDesiredReplicasByScalingMetricPanel(), and autoScalingFailuresPanel() jsonnet utility functions](https://github.com/grafana/mimir/commit/7e6ecb52f54a6b18e771d440e9fe411ad5f8bd03). This is a no-op (I've compiled the mixin after this refactoring and there was no change to the output. This refactoring is a pre-requisite of the next commit.
- [Add …
> Remote rule reads dashboard: add ruler-querier in-flight queries scaling metric panel

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
- pkg/util/globalerror/errors.go
Otherwise the ingester performs validation and returns an untyped error which we turn into 500x with little detail on the series as well.
Inspired by https://github.com/prometheus/prometheus/blob/25a8d576717f4a69290d6f6755b4a90cfaab08ff/model/histogram/histogram.go#L366  , but not a copy of.
Only checks integer native histograms as the float histograms coming out of PromQL and being written in recording rules have precision issues. E.g.
```
mimir-1-1        | ts=2024-03-26T17:14:11.049358108Z caller=group.go:529 level=warn
trace_id=0000000000000000509674846c935631 name=cluster_job:cortex_request_duration_seconds:sum_rate
index=0 component=ruler insight=true user=anonymous file=data-ruler/anonymous/krajo group=mimir_api_1
msg="Rule sample appending failed" err="rpc error: code = …
```
> Distributor: add bucket count validation to native histograms

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads-resources.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/remote-ruler-reads-resources.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
I'm working on some improvements to "Remote ruler" dashboards and I noticed the row titles are a bit confusing. The Mimir components have a specific name (e.g. ruler-query-frontend, ruler-query-scheduler, ...) so I think we should just use it.
Example of dashboards after these changes are applied:
N/A
> Dashboards: renamed rows in the "Remote ruler reads" and "Remote ruler reads resources" dashboards to match the actual component names

- operations/mimir-mixin/alerts/blocks.libsonnet
- operations/mimir-mixin/recording_rules.libsonnet
Address last recording rule which has a hardcoded range interval which is too small for scrape interval of `1m` by making it configurable using existing variables. 
Follow up PR for https://github.com/grafana/mimir/pull/7591#issuecomment-1997022142
> mixin make range interval configurable in recording rule

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Support for test-exporter was removed in #1133, however there was still left-over alert and runbook. This PR removes them.
> Remove test-exporter based alert and runbook.

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/util.go
- pkg/util/log/sampler_test.go
In this PR I'm doing changes to honor optional logging errors in pusherConsumer when experimental ingest storage is used. Previously, it was ignored.
N/A
> Honor optional logging errors in pusherConsumer

- CHANGELOG.md
- pkg/compactor/bucket_compactor.go
- pkg/compactor/job.go
- pkg/storage/tsdb/block/block.go
- pkg/storage/tsdb/block/fetcher.go
Add block compaction delay summary metric
(cherry picked from commit 96952cf7bbfbdbf5fa77f22032e834a12a8ac236)
Backports #7635 to r282. This couldn't be done automatically due to a conflict with the changelog.
> Backport 7635 to r282

- Makefile
- mimir-build-image/Dockerfile
This PR switches back to upstream faillint, since there's a [new release](https://github.com/fatih/faillint/pull/41#issuecomment-2032333247) that works with Go 1.22.
> Switch back to upstream faillint

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/shard_active_series.go
- pkg/frontend/querymiddleware/shard_active_series_response_decoder.go
- pkg/frontend/querymiddleware/shard_active_series_response_decoder_test.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
At certain times we've observed in ops huge spikes of allocations during the deserialization/processing of each of the query responses when merging the results in the shard active series frontend middleware, occasionally reaching values close to `~80%` of total allocations.
While this condition does not critically compromise the service, nor does imply a customer impact, such spikes translate into high CPU consumption that can negatively impact the TCO.
This PR aims to solve this problem through the implementation of a zero-allocation decoder, specifically adapted to the use case of said middleware, that borrows certain functions from the json-iter library, currently in use.
Broadly speaking, the way this new decoder works is by copying all contents of the response `data` key into an …
> frontend: use zero-allocation response decoder in shard active series middleware 

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- pkg/ingester/errors.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/metrics.go
- pkg/util/globalerror/errors.go
* Revert "Distributor: add bucket count validation to native histograms (#7736)"
This reverts commit fb7dbaaf6eff31e1535809b17fb6573b21ad9aad.
* Handle TSDB native histogram validation errors are soft errors
* add all testcases
* Count towards discarded samples metrics with new reason
---------
(cherry picked from commit 51c4088cc3b5087aabf72478dcc909d011ff64c0)
> [r284] Backport: Handle TSDB native histogram validation errors as soft errors (#7773)

- integration/backward_compatibility.go
Add 2.12 to backwards compatibility tests, and removes pre-2023 releases.
https://github.com/grafana/mimir/issues/7542
> Update versions used for backwards compatibility tests

- pkg/ingester/ingester.go
In this PR I'm attempting to address [a comment received here](https://github.com/grafana/mimir/pull/7486#discussion_r1533525204). The idea is to introduce another `services.Manager` in `Ingester` to "group" subservices started **before** partition reader (3 subservices).
N/A
> Refactoring: use services.Manager to start/stop subservices in ingester

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
Upgrade to Go security release [v1.22.2](https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M). It contains one security fix:
> http2: close connections when receiving too many headers
- [nx] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> mimir-build-image: Upgrade to Go v1.22.2

- CHANGELOG.md
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/manage/tools/mimirtool.md
- pkg/mimirtool/commands/rules.go
A few `mimirtool` commands accepted a `rule-files` flag: `rules diff`, `rules sync`, `rules prepare`, `rules lint`, and `rules check`. However, all these commands also accept a list of rule files as argument. Therefore, the flag is a duplicate which is inconsistent.
This flag originated in https://github.com/grafana/mimir/commit/9b206ce79198abbefae6b1868f12b193606cabaa. Back then, the list of rule files was only an argument for one command: `rules load`, and that command never got a `rule-files` flag. The rule files argument was added later to more commands, in https://github.com/grafana/cortex-tools/pull/125/files, but the existing `rule-files` flag was not removed.
This will be a breaking change for folks relying on `mimirtool` in scripts, for now the flag is only deprecated.
Fixes …
> mimirtool: deprecate rule-files flag

- CHANGELOG.md
- operations/mimir-tests/test-shuffle-sharding-partitions-enabled-generated.yaml
- operations/mimir-tests/test-shuffle-sharding-partitions-enabled.jsonnet
- operations/mimir/shuffle-sharding.libsonnet
This one updates the mimir operations, adding the support for the `-ingest-storage.ingestion-partition-tenant-shard-size` config, used with the "ingest storage" mode.
As discussed privately with @pracucci, we would like to have a way to gradually apply the new configuration across internal Mimir deployments. Thus, the jsonnet only applies the flag if the `mimir._config.shuffle_sharding.ingest_storage_partitions_enabled` is raised.
Also updated the calculated overrides, adding the support for `ingestion_partitions_tenant_shard_size` there.
> mimir: support for ingest-storage.ingestion-partition-tenant-shard-size

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- pkg/ingester/ingester.go
At Grafana Labs, we're running Mimir with `-ingester.error-sample-rate=10` since several months and we're happy with it. I think it's a reasonable default for Mimir, so I suggest to enable the ingester error sampling by default and promote the feature from experimental to advanced.
N/A
> Enable -ingester.error-sample-rate by default and promote from experimental to advanced

- operations/helm/charts/mimir-distributed/CHANGELOG.md
Step 1+2 from
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/RELEASE.md
> Helm: cut release candidate for 5.3

- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/docker-compose.yml
Bump prometheus version in local dev
2.50.1 has a bug related to native histograms scraping. Fixed in 2.51.1:
https://github.com/prometheus/prometheus/pull/13846
N/A
N/A
> Bump prometheus version to 2.51.1 in local dev

- operations/mimir/shuffle-sharding.libsonnet
This is a follow-up to #7804
We've noticed that the previous version always updated the generated ConfigMaps, with a `null` value of `ingestion_partitions_tenant_shard_size`, even when the `$._config.shuffle_sharding.ingest_storage_partitions_enabled` was unset. This PR improves this by making sure the nulls aren't end up in the resulting configs.
> mimir: don't export null "ingestion_partitions_tenant_shard_size" fields

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/mimirpb/compat.go
* Fix out of order exemplar error for native histograms
Port of https://github.com/prometheus/prometheus/pull/13021
When receiving multiple exemplars for a native histogram in mimir via remote write, sort them and only report an error if all are older than the latest exemplar as this could be a partial update.
cherry pick from https://github.com/grafana/mimir/commit/def7165e21508c15c4e436bf0a367e5d7ff542da
> [r282] backport Fix out of order exemplar error for native histograms pr 7640

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/values.yaml
Step 5 in
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/RELEASE.md
N/A
N/A
> Helm: prep 5.3.0-rc.0 and release notes template and docs

- docs/sources/helm-charts/mimir-distributed/release-notes/v5.3.md
* use consistent formatting for durations
* use "from X to Y" structure for consistency
* remove neutral reason for increasing cache timeouts; it doesn't provide any valuable information
* remove clarification for GEM gateway; the mentioned change applies to non-GEM gateway as well
> helm 5.3: release notes suggestions

- operations/helm/charts/mimir-distributed/values.yaml
The per-component docs were wrong in that the metrics aren't always read from the metamonitoring prometheus. THis used to be the case when autoscaling was first implemented but since then kedaAutoscaling.prometheusAddress has been added.
> helm: clarify keda docs

- .github/workflows/scripts/build-images.sh
- Makefile
After we moved the dockerfile from mimir-continuous-build to mimir folder, we no longer build the docker images during deploy, see one example https://github.com/grafana/mimir/actions/runs/8592984791/job/23563990901. Fix the issue in order to make the weekly release work.
> Release: Build continous-test image during release

- docs/sources/mimir/manage/tools/mimir-continuous-test.md
Reflects the new way of running mimir-continuous-test since we're deprecating the individual binary.
https://github.com/grafana/mimir/pull/7747
> mimir-continuous-test docs changes

- .gitignore
The config inspector was changed to be built instead of being used in `go run`. The binary now shows up as git untracked file.
> Add config inspector to gitignore

- pkg/storage/ingest/config.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/util.go
- pkg/storage/ingest/util_test.go
- pkg/storage/ingest/writer.go
This PR introduces two options:
* `-ingest-storage.kafka.auto-create-topic-enabled` (default true) to control whether Mimir can auto-create topic
* `-ingest-storage.kafka.auto-create-topic-default-partitions` (default 0) -- when `auto-create-topic-enabled` is true and ` auto-create-topic-default-partitions` is set to positive number, Mimir updates `num.partitions` setting on Kafka brokers before starting reading or writing to topic (and possibly auto-create the topic).
> Ingest-storage: control auto-creation of topic, and setting of default number of partitions for auto-created topics.

- CHANGELOG.md
- pkg/mimirtool/rules/rules.go
- pkg/mimirtool/rules/rules_test.go
During the weekend, while on-call, I supported an engineer at Grafana Labs which hit an edge case in `mimirtool rules prepare` command. The tool is used to add an aggregation label (defaults to `cluster`) to any aggregation and binary operator vector matcher of each rule.
The edge case we found is that when the aggregation label is already present in `group_left/right()` it shouldn't be added to `on()` too, because incorrect. A PromQL query with the same label both specified in `on()` and `group_left/right()` doesn't even parse (parsing it returns the error: `label "cluster" must not occur in ON and GROUP clause at once`).
As an example, consider the following **original query**:
```
count by(cluster, namespace) (label_replace(cortex_build_info, "cluster", "", "cluster", "(.*)"))
* …
```
> mimirtool rules prepare: do not aggregation label to on() clause if already present in group_left() or group_right()

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
In a downstream implementation a middleware peeks into the request by calling the `PrometheusCodec.DecodeMetricsQueryRquest()` method, and sometimes ignores and just passes the request to the next handler.
However, the call to `r.Form()` has left the body consumed and the body can't be decoded again.
Fixed that and added a test to make sure this doesn't happen again.
This doesn't change any behavior in Mimir itself, so no changelog entry is needed.
> Allow decoding metrics requests twice

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
Update the Chart.yaml to release -rc.0 as the final version.
For review: please double check that values.yaml already contains the stable version (2.12) of mimir and gem images.
> Helm: release mimir-distributed-5.3

- pkg/frontend/querymiddleware/shard_active_series_response_decoder.go
Return context cancellation cause when reading `data`/`error` fields content in shard active series decoder. 
Fixes https://github.com/grafana/mimir/issues/7861
> test: fix `Test_shardActiveSeriesMiddleware_mergeResponse_contextCancellation` flakiness

- operations/mimir-mixin/alerts.libsonnet
- operations/mimir-mixin/config.libsonnet
As discussed in the link PR comments this PR adds an option to not include experimental ingest-storage alerts. 
Fixes
Follow up PR for https://github.com/grafana/mimir/pull/7702#discussion_r1549679263
> chore: mixin conditionally load ingest storage alerts

- operations/mimir-mixin/jsonnetfile.lock.json
On my quest to make the mixin work with scrape interval of `1m` I found one more place with hardcoded range_interval of `1m`. I fixed it in the upstream repo. Now I need to update the mixin dependencies to pick up the fix.
Updating the mixin dependencies to pick up this fix  https://github.com/grafana/jsonnet-libs/pull/1190
> chore:mixin update deps to pick up upstream fix

- operations/mimir-mixin/config.libsonnet
Address hopefully last recording rule which has a hardcoded range interval which is too small for scrape interval of 1m by making it configurable using existing variables.
Fixes Follow up for https://github.com/grafana/mimir/pull/7768
> mixin: last rr make range interval configurable

- CHANGELOG.md
- operations/mimir-tests/test-compactor-concurrent-rollout-generated.yaml
- operations/mimir-tests/test-compactor-concurrent-rollout.jsonnet
- operations/mimir/config.libsonnet
This PR makes compactor's `max_unavailable` work with odd number of replicas.
> Make compactor's max_unavailable work with odd number of replicas

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
This change will cause us to page when a bucket index has not been updated by two compactor cleanup cycles (every 15 minutes) with a 5 minute buffer to avoid false-positives.
The update time of the index is checked when queriers perform queries so as soon as it exceeds the 1 hour max age, queries begin to fail. Thus we need to alert on the age of the index before it begins to fail queries.
N/A
> Mixin: Lower alerting threshold for BucketIndexNotUpdated alert

- pkg/distributor/distributor.go
- pkg/distributor/errors.go
I'm working to add support to tee writes both to ingesters and partitions, as part of the migration procedure to the new experimental ingest storage. The full implementation is in this PR: https://github.com/grafana/mimir/pull/7871
In this PR I'm proposing a preliminary refactoring to make https://github.com/grafana/mimir/pull/7871 easier (and possibly safer) to review. My n. 1 goal is to not introduce any regression in the path writing to ingesters.
If you review only this PR, the design may look weird. I suggest to review the design in https://github.com/grafana/mimir/pull/7871 (and leave any comment about the design there), and treat this PR just as a preliminary PR towards that design.
N/A
> Refactoring: introduce Distributor.sendWriteRequestToBackends()

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Add potential mitigations for stale bucket index alerts to the runbook.
Related #7879
> Add mitigations for `MimirBucketIndexNotUpdated` alerts to runbook

- pkg/mimir/modules.go
I'm working on a migration procedure from Mimir classic architecture to ingest storage. During the migration we'll have some Mimir components with ingest storage enabled, and others with ingest storage disabled. However, all components form a unique memberlist cluster, so we need to make sure that partition ring changes get propagated correctly. To make it happen, we need to make sure that the partition ring memberlist codec is always enabled.
History: when we introduced the partition ring, and it was still under development, we decided to not register the codec by default as a safety countermeasure. We're now testing the ingest storage since a while, so I think it's safe to enable the codec by default.
N/A
> Always enable partition ring codec

- integration/backward_compatibility.go
- integration/e2emimir/services.go
- integration/integration_memberlist_single_binary_test.go
- integration/querier_test.go
- integration/single_binary_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_ingest_storage_test.go
- pkg/ingester/ingester_partition_ring.go
- pkg/ingester/owned_series_test.go
- pkg/mimir/modules.go
- pkg/mimir/modules_test.go
I'm working on a migration procedure from Mimir classic architecture to ingest storage. During the migration we need to apply a different configuration to ingester ring KVstore (a different "key prefix") but not to the partitions ring.
Right now the ingester ring and ingester partition ring use the same KVStore config, so it's not possible to configure a different "key prefix" only for the ingester ring.
In this PR I'm proposing to allow to configure partitions ring KVStore independently from ingester ring. All in all, the ingester partition ring is a ring different than the ingester one, so I think it makes sense to keep its config decoupled.
N/A
> Allow to configure partitions ring KVStore independently from ingester ring

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This PR is a follow up of https://github.com/grafana/mimir/pull/7877.
I'm working to add support to tee writes both to ingesters and partitions, as part of the migration procedure to the new experimental ingest storage. The full implementation is in this PR: https://github.com/grafana/mimir/pull/7871
In this PR I'm proposing a send and last refactoring to make https://github.com/grafana/mimir/pull/7871 easier (and possibly safer) to review. My n. 1 goal is to not introduce any regression in the path writing to ingesters.
N/A
> Refactoring: introduce Distributor.sendWriteRequestToPartitions() and sendWriteRequestToIngesters()

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
At Grafana Labs, we're currently excluding 529 and 598 status codes from our SLOs because these codes are specifically used to signal rate limiting (529) and "client too slow sending the request" (598). However, these codes are not excluded by `MimirRequestsError` alert, so you could still get paged. In this PR I propose to exclude them from `MimirRequestsError` alert too.
N/A
> Alerts: exclude 529 and 598 status codes from failure codes in MimirRequestsError

- pkg/distributor/distributor.go
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/distributor_test.go
- pkg/storage/ingest/config.go
As part of the experimental ingest storage project, we're working on a migration path from a classic Mimir architecture (where distributors directly write to ingesters) to the ingest storage architecture (where distributors write to Kafka and ingesters consume from Kafka). In the migration procedure we designed, we need a way to tee writes both to ingesters and Kafka when the migration is on-going.
In this PR I'm proposing to add such feature to distributors. The code changes are relatively small, since we already support to either write to ingesters or Kafka (partitions). So what I'm doing in this PR is adding an option to do both at the same time (concurrently).
N/A
> Distributor: add support to tee writes to ingesters and partitions

- operations/helm/charts/mimir-distributed/CHANGELOG.md
Move `ENHANCEMENT` added in #7764 to correct section in helm chart `CHANGELOG.md`.
> Move changelog line to correct section

- CODEOWNERS
#7858 made me realise that we should give `grafana/alerting` ownership to `mimir-ruler-and-alertmanager-maintainers`. It still doesn't solve the problem of updating `grafana/alerting` which brings in other updated vendors, but it's a starting point.
N/A
> Give grafana/alerting ownership mimir-ruler-and-alertmanager-maintainers

- docs/sources/mimir/get-started/play-with-grafana-mimir/index.md
I've fleshed out the steps slightly, as this is my (and others') first time through, and one doesn't often know what is needed.
Adds a clarification to instructions which can be unclear the first time one does it.
As this is a demonstration recommended to new adopters,  a lot of first-time users
will be trying it.
/docs/sources/mimir/get-started/play-with-grafana-mimir/index.md #7844 in which I
failed to guess the right option, and had to ask
Fixes #7844
- [ x ] Documentation added.
> Add more steps to the play with grafana mimir page

- pkg/ingester/ingester_test.go
This change fixes occasional failures of `TestIngester_Starting` by removing the error type assertion from the test. The reason the error type assertion needs to be removed is that the type of error returned by `Ingester.starting()` varies based on how fast dependent services start up.
For example when starting with a context that has been canceled or has another error set for `ctx.Err()`, dependent services may complete starting but then immediately stop and go into the terminated state or their `run` method may return early. The `services.Manager` responsible for these dependent services handles service state transitions in a separate goroutine. This means that sometimes the `services.Manager` appears to start and stay running successfully,
allowing the expected error to be returned …
> Fix flakey TestIngester_Starting test

- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
This one simplifies the dev setup for ingest-storage by switching local Kafka from Zookeeper to KRaft. Zookeeper mode [is deprecated][1] in Confluent, and we aren't running Kafka this way either.
[1]: https://docs.confluent.io/platform/current/installation/docker/config-reference.html#required-ak-configurations-for-zk-mode
> Run kafka in kraft mode for ingest-storage development

- CHANGELOG.md
- pkg/distributor/distributor.go
The distributor currently exports `cortex_distributor_replication_factor` regardless whether ingest storage is enabled or not. This metric is deceiving when using ingest storage because it doesn't affect anything.
This PR exports `cortex_distributor_replication_factor` only when ingest storage is disabled. Additionally, the distributor now exports a single constant metric `cortex_distributor_ingest_storage_enabled` when ingest storage is enabled.
Some recording rules and dashboards rely on `cortex_distributor_replication_factor` and render incorrect results with ingest storage. I plan to correct them in follow-up PRs.
> distributor: conditionally export replication factor; export ingest storage metric

- .github/workflows/scripts/helm-weekly-release.sh
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/RELEASE.md
- operations/helm/charts/mimir-distributed/templates/continuous_test/continuous-test-dep.yaml
- operations/helm/charts/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-requests-and-limits-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/smoke-test/smoke-test-job.yaml
Use continuous test as a target of the mimir image instead of standalone image.
Simplifies the release process.
Related to #7747 
> Helm: use mimir continuous test as module

- pkg/mimirpb/timeseries.go
We're dealing with an issue causing some ingesters memory to skyrocket. We believe the issue is caused by very few requests with an insane number of exemplars per series. When such requests are pooled, the `TimeSeries.Exemplars` slice put back into the pool will have a large capacity. Next requests will reuse the TimeSeries from the pool, keeping the large Exemplars slice allocated and in-use even if other requests don't have an huge number of exemplars. This go on and on, until many (if not all) requests in the pool have an huge Exemplars slice, causing the in-use heap to increase.
N/A
> Do not recycle Exemplars slices with a capacity > 10

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
https://github.com/grafana/mimir/pull/7640 introduced a little regression: the metric `cortex_ingester_ingested_exemplars_failures_total` is not tracked anymore for exemplars discarded because OOO. This is misleading, because looking at the sum of successfully + failed ingested exemplars, you don't actually get the total number of exemplars processed. In this PR I fix it reverting back to the previous behaviour, and improving unit tests.
N/A
> Fix cortex_ingester_ingested_exemplars_failures_total metric tracking when exemplars are discarded because OOO

- CHANGELOG.md
- integration/distributor_test.go
- pkg/distributor/distributor.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
- pkg/mimirpb/timeseries.go
Must use p.clearUnmarshalData() to clear the cached marshall data if histograms are updated.
Sadly this case was not tested in the original PR #6535 .
Related to #6535 
> distributor: fix down scaling of native histograms with unmarshal cache

- docs/sources/mimir/manage/tools/mimirtool.md
There are two flags for the mimirtool command `rules prepare` missing in the docs
corrects the documentation
> Update docs of mimirtool

- CHANGELOG.md
- operations/mimir-tests/test-continuous-test-generated.yaml
- operations/mimir/continuous-test.libsonnet
After we switched CT to be a module in `mimir` binary, its default TCP port was changed to `:8080`. This PR updates the jsonnet to support these changes.
What do you think @dimitarvdimitrov @johannaratliff @56quarters?
Relates to https://github.com/grafana/mimir/pull/7747
> mimir: update http-metrics TCP port in continuous-test deployment

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR adds panels showing behaviour of ingester-autoscaling, as used with ingest-storage. While autoscaling configuration is not yet open-source (tbd), I'm already adding panels so that we can monitor and test it.
Here is panel in action:
> Add panel for ingester autoscaling, when using ingest-storage.

- pkg/ruler/manager_metrics_test.go
The metrics struct and its attributes have been public for a while but I believe this code has not been touched in a while.
This is the PR that originally made the metrics public https://github.com/prometheus/prometheus/pull/8778
Part of https://github.com/grafana/mimir-squad/issues/1845
- [ N/A] Tests updated.
- [ N/A ] Documentation added.
- [ N/A ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ N/A ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Rules: Stop copying metrics struct and use upstream Prometheus

- pkg/storage/bucket/gcs/bucket_client.go
Removes unnecessary yaml ser/deser cycle in GCS client creation. Thanos added a client initializer that makes this unnecessary.
> Remove yaml ser/deser cycle in GCS client creation

- integration/querier_test.go
This compactor was added in #6779 but isn't actually needed since we're testing monolithic mode which already includes the compactor component.
Coincidentally, this also seems to fix #7972
Fixes #7972
> Remove unneeded compactor in querier e2e test

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/querier/querier-so.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-autoscaling.jsonnet
- operations/mimir/autoscaling.libsonnet
This PR upstreams a change that we have been trialing at GL.
Some workloads have a very uneven distribution of queries. Some of the causes of this can be external alerting systems and reporting tools which run batch jobs once a day.
This results in an influx of queries at fairly regular intervals (~24h). Autoscaling can only respond so fast to incoming queries. In practice, it takes anywhere between 2 and 7 minutes to respond to queries and trigger a scaling event. As a result Mimir's query queues fill up and Mimir start returning HTTP 429 to new queries until queriers have had the time to scale out and accommodate the added load.
Scale preemptively. Automated workloads are also highly predictive. This PR uses the value of the inflight queries at the same time last week (6d23h30m instead …
> autoscaling: add querier predictive scaling

- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer_test.go
Code running in a goroutine (runAsync) shouldn't call require. (because that calls t.Fatal(), but you can't do that from a goroutine).
Also moved a function that was only used in a different test file.
> Ingest writer test nits

- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
This change fixes a metadata ingestion test flake caused by metadata being ingested when it should have been rejected. The conversion of global to local limits only counts the number of ingesters with tokens when determining how to divide the global limit. When there are no ingesters with tokens due to race conditions, 0 is used for the global limit which causes 0 to be used for the local limit which is interpreted as "unlimited".
Fixes #7979
> Fix metadata ingestion test flake

- CHANGELOG.md
- docs/sources/mimir/manage/tools/query-tee.md
- tools/querytee/proxy_endpoint.go
- tools/querytee/proxy_endpoint_test.go
- tools/querytee/proxy_metrics.go
This metric gives us a measurement of how individual queries compare between two backends in terms of latency (or duration).
> Querytee: Add metric to measure relative backend latency

- pkg/frontend/querymiddleware/shard_active_series_response_decoder.go
- pkg/frontend/querymiddleware/shard_active_series_response_decoder_test.go
This PR fixes a bug in the custom decoder of the active series middleware that causes double writing of the comma separator when the streamed buffer exceeds the one-megabyte threshold.
Fixes N/A
> frontend: active series experimental custom decoder bugfix

- .github/workflows/test-build-deploy.yml
It's a version tagged at the same commit as the existing short SHA.
* Update `doc-validator` image to use latest `reviewdog` with workaround for GitHub PR diff limit
> Use `grafana/doc-validator:v5.1.0`

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This PR updates the distributor's internals, that do the approximation of the number of in-memory series, for the `/api/v1/cardinality/label_values` API endpoint. Now, if the number of zones where ingesters run is larger than the replication factor (RF), the approximation falls back to the single zone logic. This seems more accurate, than returning the value of the largest zone.
Fixes #7738
> distributor: In-memory series approximation to take into account that number of zones may be large than RF

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/validate.go
- pkg/mimirpb/timeseries.go
- pkg/mimirpb/timeseries_test.go
- pkg/util/validation/limits.go
In this pull request, we propose safeguarding the write path by implementing a restriction on the number of exemplars/series per request. Exemplars exceeding this limit will be discarded, and these discards will be monitored through the cortex_discarded_exemplars_total metric.
> Distributor: Add limit for exemplar per series

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/ruler.libsonnet
This PR fixes an issue with the Ruler dashboard, where the "queue length" panel does not show the expected results.
`cortex_prometheus_notifications_queue_length` and `cortex_prometheus_notifications_queue_capacity` are both gauges defined [here](https://github.com/grafana/mimir/blob/48fafc805577b349bf83ec16d90325a3a8f3494f/vendor/github.com/prometheus/prometheus/notifier/notifier.go#L176-L187), so taking the `rate` of them will not produce the desired result.
(none)
> Fix "queue length" panel on Ruler dashboard

- pkg/frontend/querymiddleware/shard_active_series_response_decoder.go
- pkg/frontend/querymiddleware/shard_active_series_response_decoder_test.go
Backporting deb40d8450d824d5ad31225cdb524c7d93dfa90b from https://github.com/grafana/mimir/pull/7965
> [r288] frontend: active series experimental custom decoder bugfix (#7965)

- CHANGELOG.md
- pkg/ingester/ingester_ring.go
- pkg/ingester/ingester_ring_test.go
- pkg/mimir/mimir.go
- pkg/mimir/mimir_test.go
These changes fix an issue with mimir's config validation, where non-ingester modules fail on its config validation, when `-ingester.ring.token-generation-strategy=spread-minimizing` is set.
Fixes #7822
> Non-ingesters should not fail on its config validation

- CHANGELOG.md
- tools/querytee/proxy_endpoint_test.go
This fixes race conditions such as the one seen in https://github.com/grafana/mimir/actions/runs/8892796420/job/24417658697
It was caused by a latencyPair request consuming a response index before a prior request had a chance to consume it.
> Fix race condition in querytee test

- CHANGELOG.md
- pkg/distributor/distributor_test.go
- pkg/distributor/validate.go
Distributor: change reason to `too_many_exemplars_per_series_per_request` for metrics `cortex_discarded_exemplars_total`
the label value of too_many_exemplars_per_series could be confusing, clarify it by mentioning per request
> Distributor: change reason to too_many_exemplars_per_series_per_request for metrics cortex_discarded_exemplars_total

- CHANGELOG.md
- go.mod
- go.sum
- pkg/distributor/otel.go
- pkg/distributor/push_test.go
- vendor/github.com/prometheus/prometheus/discovery/metrics.go
- vendor/github.com/prometheus/prometheus/discovery/metrics_k8s_client.go
- vendor/github.com/prometheus/prometheus/model/labels/regexp.go
- vendor/github.com/prometheus/prometheus/promql/query_logger.go
- vendor/github.com/prometheus/prometheus/rules/alerting.go
- vendor/github.com/prometheus/prometheus/scrape/manager.go
- vendor/github.com/prometheus/prometheus/scrape/scrape.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus/normalize_label.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus/normalize_name.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheus/unit_to_ucum.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/histograms.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/otlp_to_openmetrics_metadata.go
- vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
- vendor/modules.txt
Upgrade to latest mimir-prometheus: [de14b0ea393d](https://github.com/grafana/mimir-prometheus/tree/de14b0ea393dbe5c3c93965e754120ea6d476909).
* [OTLP: Use PrometheusConverter directly](https://github.com/prometheus/prometheus/pull/14006)
* [otlp: Prometheus to own its own copy of the otlptranslator package](https://github.com/prometheus/prometheus/pull/13991)
* [Remove OpEmptyMatch from regex concatenations](https://github.com/grafana/mimir-prometheus/pull/615)
* [OTLP: Don't generate target_info unless at least one identifying label is defined.](https://github.com/prometheus/prometheus/pull/13991)
* [OTLP: Don't generate target_info unless there are metrics.](https://github.com/prometheus/prometheus/pull/13991)
The main changes are OTLP related, i.e. that Prometheus now has taken …
> Upgrade to latest mimir-prometheus

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/mimirpb/timeseries.go
- pkg/mimirpb/timeseries_test.go
Currently, the exemplars are sorted in ingesters. However, since we're already iterating through exemplars in the distributor, it would be more efficient to perform this ordering earlier in the process. By doing so, we could achieve the ordering just once instead of three separate times.
> Distributor: move the ordering exemplars from ingester to distributor

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/memcached/_memcached-statefulset.tpl
- operations/helm/charts/mimir-distributed/values.yaml
This PR adds a new resource in helm memcache template: `volumeClaimTemplate` to be able to configure the volume claim template for the memcache statefulset.
As reference, the `volumeClaimTemplate` is already used in [loki helm chart](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/memcached-chunks/statefulset-memcached-chunks.yaml#L156) and was used as reference.
Memcache volumes are useful to use SSD disks as an alternative to machine memory as storage, so it helps to reduce memory costs with nearly no degradation in performance.
As reference there is [grafana blog post](https://grafana.com/blog/2023/08/23/how-we-scaled-grafana-cloud-logs-memcached-cluster-to-50tb-and-improved-reliability/) about how it was useful to reduce Memcache cost for Loki. …
> feat(helm): Add volumeClaimTemplates to memcache

- Makefile
- mimir-build-image/Dockerfile
We're running jsonnet tests in CI with a very old version of Tanka. The old version of Tanka gets shipped with an old version of jsonnet, which doesn't support new jsonnet functions. In this PR I'm upgrading Tanka to unblock https://github.com/grafana/mimir/pull/8028 (requires `std.parseYaml`).
N/A
> Update Tanka in the mimir-build-image

- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
The Restricted Kubernetes policy doesn't actually specify its read-only restrictions.
> helm docs: clarify the chart can run on read-only filesystems

- pkg/alertmanager/alertspb/compat.go
- pkg/alertmanager/alertstore/bucketclient/bucket_client.go
- pkg/alertmanager/alertstore/local/store.go
- pkg/alertmanager/alertstore/local/store_test.go
- pkg/alertmanager/alertstore/store.go
- pkg/alertmanager/alertstore/store_test.go
- pkg/alertmanager/api_grafana_test.go
- pkg/alertmanager/api_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- pkg/mimir/modules.go
This PR enables Mimir to fetch the Grafana Alertmanager configuration on each config sync loop iteration if the compatibility routes are enabled.
This Grafana AM configuration will be merged with the existing Mimir AM config and the result will be applied to the Alertmanager on a per-tenant basis.
> Fetch Grafana Alertmanager configuration (sync loop)

- Makefile
- mimir-build-image/Dockerfile
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/recording-rules.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-baremetal/rules.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin-compiled/rules.yaml
- operations/mimir-mixin/.lint
Peter suggested to update `mixtool` in [this comment](https://github.com/grafana/mimir/pull/8030#pullrequestreview-2036088050). In this PR I'm doing it. `mixtool` has become way more picky with the linter, so I've added many exclusions. I think all exclusions make sense, except `panel-units-rule` that should be fixed, but it's low priority and I don't have bandwidth to do it right now.
- Review changes with "hide whitespace" enabled
N/A
> Update mixtool in mimir-build-image

- development/mimir-ingest-storage/compose-up.sh
- development/mimir-microservices-mode/compose-up.sh
- development/mimir-monolithic-mode/compose-up.sh
I had a bug but didn't notice because stringlabels build tag was not used in development/mimir-monolithic-mode. Facepalm.
This is just a quick and dirty fix without refactoring the scripts.
> Fix inconsistent mimir build in development dirs

- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir/ingest-storage-migration.libsonnet
- pkg/storage/ingest/config.go
- pkg/storage/ingest/config_test.go
- pkg/storage/ingest/reader.go
As part of the migration process from Mimir classic architecture to the experimental ingest storage, it would be very handy being able to customize the consumer group of each `ingester-zone-[abc]-partition` ingester (they're temporarily StatefulSets) so that when they will be migrated back to `ingester-zone-[abc]` the consumer group will be the same. In this PR I'm adding a config option to customize it, allowing to parametrise the `<partition>` ID.
I've updated the migration process codified in jsonnet to show how it will be used. This removes the manual step to copy consumer group offsets from `ingester-zone-[abc]-partition-<partition>` to `ingester-zone-[abc]-<partition>`.
N/A
> Add config option to override consumer group when experimental ingest storage is used

- operations/mimir/shuffle-sharding.libsonnet
Following #8028 this PR updates the default value of `ingest_storage_partitions_enabled` to mirror `$._config.ingest_storage_enabled`. Such configuration is what we're currently testing internally, as part of the migration of the workloads to the ingest storages.
> jsonnet: align ingest_storage_partitions_enabled with ingest_storage_enabled

- pkg/ingester/owned_series_test.go
The test case `change of state is not interesting` changes the state of an ingester in the ring. It then expects that the change is classified as "not interesting. "However, it changes the state by adding the ingester again into the ring. This also changes the RegisteredTimestamp of the instance in the ring. Timestamps are unix timestamps in seconds. So if   `change of state is not interesting` runs in a different unix second than `new instance added`, then the test will detect a change in the RegisteredTimestamp, which is an "interesting" change and the test will fail.
This PR fixes `change of state is not interesting` by changing only the state of the ingester.
> NB: The test assumes that its test cases run together. So each subtest requires the previous to have run. Otherwise, they all …
> Fix flaky TestOwnedSeriesIngesterRingStrategyRingChanged

- docs/sources/mimir/manage/monitor-grafana-mimir/requirements.md
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/slow-queries.libsonnet
This PR allows users to change the component label in loki logs as the name label is not always defined (e.g. for promtail users) as explained here https://github.com/grafana/mimir/issues/5558#issuecomment-2062501431
Helps fixing https://github.com/grafana/mimir/issues/5558 later
> Mixin: Add flexibility to slow queries component label

- CHANGELOG.md
- Makefile
- pkg/querier/api/consistency.go
- pkg/querier/api/consistency_test.go
- pkg/storegateway/bucket_stores.go
- pkg/util/extract_forwarded.go
In Mimir ingesters, 10% of object (and memory) allocations  come from gRPC `metadata.FromIncomingContext()`. `metadata.FromIncomingContext()` is called in few places. The problem of `metadata.FromIncomingContext()` is that it creates a copy of all metadata map, when we only want to lookup a single key.
Two years ago, `metadata.ValueFromIncomingContext()` was introduced in gRPC golang library exactly for this reason. The function is still marked as experimental but it was left untouched since was introduced 2 years ago. I propose to use it. If it will get removed, we can always revert back to `metadata.FromIncomingContext()`.
I've done the same in https://github.com/grafana/dskit/pull/502, which I'm vendoring in this PR.
N/A
> Reduce memory allocations in functions used to propagate contextual information between gRPC calls

- CHANGELOG.md
- pkg/util/requestbuffers.go
Currently, we are dealing with an issue that appears to point to a memory leak in the distributor. Similar to https://github.com/grafana/mimir/pull/7936, we believe the issue stems from certain requests containing an insane number of exemplars, causing the buffers used for unmarshalling those requests to unexpectedly grow.
This PR sets a maximum buffer size (originally set at 1MB but subject to review later) for objects returned to the pool, aiming to prevent large memory blocks from being retained.
Fixes N/A
> util: avoid pooling large buffers in `util.RequestBuffers`

- CHANGELOG.md
- pkg/mimirtool/analyze/grafana.go
- pkg/mimirtool/analyze/grafana_test.go
When parsing queries from grafana dashboards, use a replacer with a list of variables rather than a regex matcher.
The regex matcher works ok with ranges and subqueries, but is not working when the variables are used in other parts of the query (e.g. with `offset`).
This PR switches back to using a list of variables to be replaced, partially reverting the changes from #6657, but uses a `strings.Replacer` for better readability.
n.a.
> mimirtool: use strings replacer in dashboards queries analyzer

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/thanos-io/objstore/CHANGELOG.md
- vendor/github.com/thanos-io/objstore/objstore.go
- vendor/modules.txt
This PR upgrades thanos-io/objstore to bring in https://github.com/thanos-io/objstore/pull/117.
This fixes the issue where the `thanos_objstore_bucket_operation_failures_total` metric is incorrectly incremented if the call is cancelled, which should fix the issue where the `MimirStoreGatewayTooManyFailedOperations` alert fires when many store-gateway requests are cancelled.
(none)
> Upgrade thanos-io/objstore

- pkg/streamingpromql/benchmarks/benchmarks.go
- tools/benchmark-query-engine/main.go
This PR makes two small improvements to the benchmarks for the streaming PromQL engine:
* It removes the "single step range query" benchmark cases. These aren't particularly valuable given we also benchmark instant queries, and running the full benchmark suite already takes quite a while.
* It changes the behaviour of `tools/benchmark-query-engine` to apply the supplied filter when listing test cases (eg. running `benchmark-query-engine -list -bench "blah"` now shows only benchmarks matching `blah`, rather than all benchmarks).
(none)
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/m …
> Streaming PromQL engine: benchmarking improvements

- CHANGELOG.md
- pkg/streamingpromql/operator/aggregation.go
- pkg/streamingpromql/operator/aggregation_test.go
- pkg/streamingpromql/query.go
This PR modifies the behaviour of the streaming PromQL engine to not sort series in the aggregation operator, and instead sort the final matrix value. 
Matrix values are expected to be sorted by series labels, so we can't avoid sorting series altogether - but we don't need to sort intermediate results.
Sorting series in the aggregation operator is unnecessary:
* in the specific case of the aggregation operator, it's better to return series in whatever order minimises the number of incomplete groups held in memory, as this reduces peak memory utilisation in the case where the input series are sorted according to the output groups (and in the worst case, peak memory utilisation is no worse than what we have today)
* there may be another operator consuming the result of the aggregation, and …
> Streaming PromQL engine: sort series in matrix at end

- pkg/distributor/distributor.go
This exports the `distributor.NextOrCleanup` utility so it can be used in push wrappers injected by clients via [this config](https://github.com/grafana/mimir/blob/4d82008ffcbe5d4c36741b6afc3e5f2ce5aadd33/pkg/distributor/distributor.go#L210).
n/a
> Export `distributor.NextOrCleanup`

- docs/sources/mimir/manage/mimir-runbooks/_index.md
In this PR I'm proposing to add a new runbook for the experimental ingest storage. The runbook is not linked to a specific alert, but it's about a failure scenario that could happen because of different causes. It's something we somewhat experienced in one of test clusters, and the proposed solution is based on a couple of options we brainstormed so far.
N/A
> Docs: add runbook 'Ingester is overloaded when consuming from Kafka'

- pkg/distributor/distributor_ingest_storage_test.go
- pkg/storage/ingest/config.go
- pkg/storage/ingest/config_test.go
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
Currently we run 1 Kafka client per partition. This means that if we have 100 partitions, 100 distributors and a metadata refresh interval of 10s, distributors will issue `100 * 100 / 10 = 1000 req/s` to update cluster metadata. The cluster metadata is an expensive operation, and can put extra pressure to Kafka. The current approach doesn't scale.
In this PR I propose to run 1 Kafka client per producer by default, but allow to increase it via a new config option. When > 1 clients are configured, the `Writer` will simply shard partitions between clients.
N/A
> Reduce the number of Kafka clients used by producers

- CHANGELOG.md
- pkg/util/requestbuffers.go
reverting https://github.com/grafana/mimir/pull/8044 in favor of https://github.com/grafana/mimir/pull/8082
> reverts "util: avoid pooling large buffers in util.RequestBuffers"

- go.mod
- go.sum
- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/distributor/push.go
- vendor/github.com/grafana/dskit/multierror/multierror.go
- vendor/modules.txt
This PR replaces an already existing private interface `distributor.distributorError` 
```
type distributorError interface {
errorCause() mimirpb.ErrorCause
}
```
with a new, exported interface `distributor.Error`
```
type Error interface {
Cause() mimirpb.ErrorCause
}
```
Distributor middlewares are supposed to return errors implementing `distributor.Error` interface. This way distributor will correctly handle them.
> Distributor: export distributor.Error interface

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview-networking.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads-networking.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads-networking.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes-networking.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview-networking.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads-networking.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads-networking.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes-networking.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
The "TCP Connections" panel, displayed in our Networking dashboards, show the number of ingress connections via HTTP or gRPC (we don't support other ingress protocols). However, Mimir does make a bunch of egress connections too, which are not visible through this panel (and it's not something tracked directly by Mimir).
I propose to rename the "TCP Connections" panel to "Ingress TCP Connections" to make it more clear.
N/A
> Dashboards: renamed "TCP Connections" panel to "Ingress TCP Connections"

- pkg/frontend/v1/frontend.go
- pkg/frontend/v1/frontend_test.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues.go
- pkg/scheduler/queue/tenant_queues_test.go
- pkg/scheduler/scheduler.go
This is part of an effort to
a) make this code more understandable and easier to work on and
b) prepare for the upcoming changes to the queuing structure and algorithm.
These changes are mostly about naming and docstrings to accurately describe what is happening;
several comments were outdated or just wrongly interpreting what is happening.
The main functional change is where I encapsulated the handling of all querier connection/disconnection/shutdown signals in the `dispatcherLoop` when we read `<-q.querierOperations` into a single `processQuerierOperation`.
Previously we assumed that we must attempt to dispatch queries after a querier operation because it _may_ have triggered a reshard - now I actually report whether a reshard happened so we can skip attempting to dispatch if we do not …
> refactor: query-scheduler control flow cleanup

- pkg/ingester/client/mimir_util.go
This PR improves the performance of accumulating chunks from ingesters in queriers.
`AccumulateChunks` is called with a slice of chunks from each ingester to build up a final slice containing all unique chunks from all queried ingesters.
The call pattern typically looks like this:
1. `chunks := []Chunk{}`
2. `chunks = AccumulateChunks(chunks, ingester1Chunks)`
3. `chunks = AccumulateChunks(chunks, ingester2Chunks)` 
Without the change in this PR, we'll unnecessarily spend a bunch of time copying `ingester1Chunks` into the empty `chunks` in step 2. Instead, we can just return `ingester1Chunks` as-is, and avoid a bunch of allocations and time spent moving bytes around.
I haven't bothered with a changelog entry as the overall impact is small (this was significant enough to show up in some …
> Don't allocate an unnecessary slice when accumulating chunks

- pkg/storegateway/bucket_test.go
@charleskorn mentioned that this test is consistently failing. The problem was that the first call in the goroutine wasn't blocking when the client doesn't read the response. Even though responses are streaming there are buffers in gRPC, so the store-gateway can send the response without having to wait for the client to receive it.
After increasing the size of the response, so that the buffers aren't enough, the test didn't terminate. The reason was that we were trying to gracefully shut down the server before cancelling the client request first. This was because of the order of t.Cleanup's and defers. I changed the usages from t.Cleanup to defers to be more consistent with the rest of the file and also reordered the init steps so that they work with both defers and t.Cleanup's.
> store-gateway: fix flaky TestBucketStore_Series_TimeoutGate

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/api.go
- pkg/distributor/distributor.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/ingester/client/client_test.go
- pkg/querier/remote_read.go
- pkg/util/http.go
- pkg/util/http_test.go
- pkg/util/requestbuffers.go
- pkg/util/requestbuffers_test.go
- tools/trafficdump/parser.go
This PR adds a new experimental CLI parameter called `-distributor.max-request-pool-buffer-size` that allows enforcing a maximum size in bytes for the pool buffers used for decompressing request bodies in both Prometheus and OTLP handlers. By default, this is set to `0`, which means no maximum will be enforced (same behavior as currently).
Additionally, a new metric named `cortex_distributor_uncompressed_request_body_size_bytes` has been included in order to provide visibility on the average of uncompressed body payload, thus allowing for an informed decision to be made when setting the previously mentioned maximum.
Fixes N/A
> distributor: allow enforcing maximum buffer size for write request pool

- Makefile
- mimir-build-image/Dockerfile
Upgrade mimir-build-image to go 1.22.3. Go 1.22.3 includes [security fixes](https://go.dev/doc/devel/release).
n/a
> Upgrade mimir-build-image to go 1.22.3

- pkg/streamingpromql/operator/pool.go
This PR removes some unnecessary methods that clear the contents of slices and replaces them with the `clear` builtin, which does the same thing.
Given this is a very small change with no user impact I haven't bothered to add a changelog entry.
(none)
> Streaming PromQL engine: use clear builtin rather than our own implementations

- pkg/util/requestbuffers_test.go
The test makes use of a `sync.Pool` under the hood, which apparently does not consistently ensure that when requesting a new item, the item returned is always the one that was previously returned to the pool.
To avoid this effect, it has been decided to revert to using a type fakePool, as was done previously before the https://github.com/grafana/mimir/pull/8082 change was introduced.
To validate that the test is no longer flaky, the following command has been executed: 
```
go test -v ./pkg/util -run TestRequestBuffers -count 1000000 -failfast -timeout 60m
```
Fixes N/A
ref: https://github.com/grafana/mimir/actions/runs/9057849698/job/24882485441?pr=8114#step:8:79
> fix flaky `TestRequestBuffers`

- pkg/mimirpb/errors.go
This PR exports `mimirpb.IsClientErrorCause()` function, that distinguishes between `mimirpb.ErrorCause`s corresponding to client and server errors. Currently, `mimirpb.BAD_DATA` is the only `mimirpb.ErrorCause` corresponding to client errors.
This PR makes no semantical change, it just exports the error cause check already used within `mimirpb.IsClientError()`.
> mimirpb: export IsClientErrorCause() function

- CHANGELOG.md
- cmd/mimirtool/main.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/mimir/runtime_config.go
- pkg/mimirtool/commands/config.go
- pkg/mimirtool/commands/runtimeconfig.go
- pkg/mimirtool/commands/runtimeconfig_test.go
- pkg/mimirtool/commands/testdata/runtimeconfig/invalid.yaml
- pkg/mimirtool/commands/testdata/runtimeconfig/valid.yaml
Add a `runtime-config verify` sub-command to `mimirtool`.
To facilitate said sub-command, and also Grafana Enterprise Metrics, refactor logic for creating a `github.com/grafana/dskit/runtimeconfig.Manager` into a new function `NewRuntimeManager`. This manager is used for validating runtime config.
> mimirtool: Add runtime-config verify sub-command

- pkg/storage/ingest/config.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
We currently commit consumer group offsets every 1s. When running at scale, the rate of requests is pretty high. I would like to relax it, so making it configurable in this PR.
N/A
> Allow to configure Kafka OffsetCommit interval

- CHANGELOG.md
- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/owned_series_test.go
- pkg/ingester/user_tsdb.go
Couples updates to owned series with updates to active series. If a series is no longer owned, it is no longer counted as an active series. The exception to that is during early head compaction: the series are still active even if they are removed from the head.
Fixes https://github.com/grafana/mimir/issues/7976
> ingester: reduce active series when series change owner

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
You can use \`ref\` URIs in admonitions (or any shortcodes) because they are inline and not subject to the issues noted in the [\`admonition\` shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/#code-shortcode:~:text=to%20core%20understanding.-,WARNING,For%20more%20information%2C%20refer%20to%20Markdown%20Reference%20Links%20in%20Shortcodes.,-Examples).
The \`ref\` URIs perform the same pattern matching as \`docs/reference\` but don't require the use of reference-style links and the destinations are ordinary (full) URLs that can include version substitution. Unlike \`docs/reference\`, the implementation doesn't use \`relref\` so you don't have to be careful with omitting trailing slashes and the links will follow redirects.
Documentation: …
> [mimir-distributed-release-5.2] Replace docs/reference shortcode with ref URIs

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/model/labels/matcher.go
- vendor/modules.txt
Reverting https://github.com/prometheus/prometheus/pull/14068 because it is causing unforseen complications with LBAC in GEM.
Followup to #8144
> Remove label selector string quoting from mimir-prometheus

- CHANGELOG.md
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/bucket_stores_test.go
Backport https://github.com/grafana/mimir/commit/9e2f4b7d8aba65ed52d70e02e12438b3f73a3815 from https://github.com/grafana/mimir/pull/8149
> [r289] Fix race between timeout gate timing out and delegated gate returning successfully

- pkg/distributor/distributor.go
- pkg/distributor/errors.go
- pkg/frontend/v2/frontend.go
- pkg/ingester/errors.go
- pkg/ingester/ingester_test.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/storegateway/bucket.go
- pkg/storegateway/storegatewaypb/custom.go
- pkg/util/globalerror/grpc.go
- pkg/util/globalerror/grpc_test.go
This PR refactors the `globalerror` package in such a way that it exports the following functions:
- `ToGRPCStatusError()`, that returns an error corresponding to a gRPC status built out of the given parameters: the gRPC status' code and details are passed as parameters, while its message corresponds to the original error. The resulting error is of type error, and it can be parsed to the corresponding gRPC status by both gogo/status and grpc/status packages.
- `WrapErrorWithGRPCStatus()`, that wraps a given error with a gRPC status, which is built out of the given parameters: the gRPC status' code and details are passed as parameters, while its message corresponds to the original error. The resulting error is of type `globalerror.ErrorWithStatus`. This function replaces the previously …
> Improving globalerror package

- CHANGELOG.md
- pkg/querier/stats/stats.go
- pkg/querier/stats/stats_test.go
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
Fixes a panic in Querier services caused by request-processing goroutines that are still running for a short time after their contexts are canceled and are continuing to modify query stats while querier's scheduler attempts to marshal them.
Like so:
1. scheduler processor [invokes](https://github.com/grafana/mimir/blob/97ac27a2a04169bc528fabc6bf3d2431fa97c208/pkg/querier/worker/scheduler_processor.go#L272) the querier handler.
2. the querier handler (way down the call tree) forks off goroutines to do things. Those goroutines increment query stats. (like [here](https://github.com/grafana/mimir/blob/b896aeddd0d74c9d46d90b12ccd8e9f80a4076a9/pkg/querier/blocks_store_queryable.go#L881-L883))
3. the handler context is canceled for whatever reason. (connection to frontend dies, timeout, ...)
4. …
> Query scheduler: Fix a panic in stats marshaling

- docs/sources/mimir/references/architecture/components/store-gateway.md
Per #4280, we removed use of mmap. This change removes references to it in architecture documentation. It also removes references to features that have been removed such as not using the bucket index.
Fixes #8145
> docs: Remove references to mmap in store-gateway

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
Earlier today we've found an issue in a staging environment causing the ingestion from Kafka to be stuck (due to a deadlock). It took a long time to figure it out and none of the existing alerts fired. This alert may have helped.
N/A
> Add MimirIngesterStuckProcessingRecordsFromKafka alert

- docs/sources/mimir/configure/configure-object-storage-backend.md
This adds a note to the docs informing users that buckets are not automatically created in storage backends, as this had led to some confusion.
Fixes #2113
> Add note to docs clarifying storage buckets have to be created manually

- development/mimir-microservices-mode/config/mimir.yaml
Largely lifted from GEM.
This config allows several things to be tested much faster in a local dev environment when starting with a blank slate.
Also fixes old consul config that did not work because we don't use consul.
Tested several times in local environment to get working values.
Values are largely set based on ability to easily send queries that are only for ingesters or only for store-gateways, e.g. query_store_after set to 10m so there's buffer where sending queries for the last 5m won't touch the store-gateways.
> mimir microservices mode config for faster feedback loop

- CHANGELOG.md
- pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
The existing code would only evaluate the at modifier for vector selectors, but subquery expressions also can have it. There are no other expression types in promQL which can take the `@` modifiers.
> query-frontend: correctly replace `@` modifier for split queries

- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-enable-cluster-label-verification/_index.md
Add documentation to migrate mimir helm installation to enable cluster label verification. The rendered doc is [here](https://github.com/grafana/mimir/blob/lamida/helm-enable-cluster-label/docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-enable-cluster-label-verification/_index.md).
Fixes #2865
> Add documentation for helm memberlist cluster label migration

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-scaling.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-scaling.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-tools/serve/run.sh
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/scaling.libsonnet
Grafana 10+ (maybe even earlier) comes with two versions of table plugins: "Table" and "Table (old)". The later one is deprecated, and messes up with the dashboards that use it in Grafana 11.
---
Note that, similar to #7413, I don't think it's worth it trying to resolve that in [grafana-builder](https://github.com/grafana/jsonnet-libs/tree/5115551d40369897f98595cc3d8fc368abf60d5d/grafana-builder) at this point. Instead, we should consider completely revisiting how dashboards are built, moving to [grafonnet](https://grafana.github.io/grafonnet/index.html), imho (+1 to https://github.com/grafana/jsonnet-libs/issues/1010).
---
This PR updates the dashboards, that use a Table panel, to follow the newer plugin's JSON model. Below screenshots are from Grafana 11, showing the updated version of …
> mimir-mixin: update dashboards to not use deprecated "Table (old)" plugin

- CHANGELOG.md
- pkg/mimirtool/client/client.go
- pkg/mimirtool/client/rules_test.go
- pkg/mimirtool/commands/env_var.go
- pkg/mimirtool/commands/rules.go
[ENHANCEMENT] Add `mimir-http-prefix` option to introduce a prefix for Mimir URL when use legacy routes.
clean up some mimirtool bugs, adding mimir-http-prefix for mimir client when use legacy routes 
Fixes #8018
> [ENHANCEMENT] Add `mimir-http-prefix` option to introduce a prefix for Mimir URL when use legacy routes.

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
This PR builds on https://github.com/grafana/dskit/pull/527 to add the route name to `query stats` log lines emitted by query-frontends.
This is useful when searching or analysing these log lines, particularly for APIs where the URL varies based on the request (eg. the label values API, where the URL is `/prometheus/api/v1/label/{name}/values`).
For example (notice the `route_name` value):
```
ts=2024-05-28T06:56:25.614545465Z caller=handler.go:374 level=info user=anonymous traceID=0c6048d9d2833e7a msg="query stats" component=query-frontend method=GET path=/prometheus/api/v1/query route_name=prometheus_api_v1_query user_agent=Grafana/10.1.5 status_code=200 response_time=4.493ms response_size_bytes=4139 query_wall_time_seconds=0.003131375 fetched_series_count=15 fetched_chunk_bytes=1429 …
```
> Include route name in query stats log lines emitted by query-frontends

- pkg/alertmanager/sender.go
This PR modifies the logging in the `Sender` struct to use go-kit instead of alerting's [Logger](https://github.com/grafana/alerting/blob/e545a06ed7d0986992a361d15f44e20276438106/logging/log.go#L5-L22) interface, making it consistent with the rest of the codebase.
It also adds a no-op `SendEmail()` method, which implements alerting's [EmailSender](https://github.com/grafana/alerting/blob/e545a06ed7d0986992a361d15f44e20276438106/receivers/email.go#L24-L26) interface.
Related PR: https://github.com/grafana/mimir/pull/8066
> Alertmanager: Make sender use go-kit logger and add no-op e-mail sender

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
This PR cherry-picks https://github.com/grafana/mimir/pull/8194 onto r292.
Original description: Add insight=true to ingest-storage log messages when data can't be ingested due to client errors (#8194)
> Cherry-pick PR 8194 onto r292

- CHANGELOG.md
- cmd/mimir/main.go
We are trying to automatically set GOMAXPROCS based on the number of CPUs that an ingester pod requests in Kubernetes. We're going with 2x the requested cores. The reason for this is that the default values of GOMAXPROCS is NumCPU. When running on large nodes and only utilizing a small % of the underlying node results in high scheduling overhead.
Sometimes the setting of GOMAXPROCS might exceed the number of cores of the node. We also don't want to restrict the nodes on which pods run. In those cases setting GOMAXPROCS to a higher value than NumCPU has the opposite effect - it increases scheduling overhead instead of reducing it.
Clamps the value of GOMAXPROCS to runtime.NumCPU. The idea of this PR is to basically make automating the GOMAXPROCS setting in deployment tooling easier by …
> Clamp GOMAXPROCS when higher than runtime.NumCPU

- CHANGELOG.md
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operator/instant_vector_selector.go
- pkg/streamingpromql/operator/range_vector_selector.go
- pkg/streamingpromql/operator/selector.go
- pkg/streamingpromql/query.go
This PR adds support for cancelling queries (with `Query.Cancel()`) and configuring a timeout for queries (with `EngineOpts.Timeout`) in the Mimir query engine.
(none)
> Mimir query engine: support query cancellation and timeout

- docs/sources/mimir/manage/mimir-runbooks/_index.md
This PR improves the documentation for `err-mimir-sample-duplicate-timestamp` to include a scenario where this can be caused by multiple alerting rules with the same alert name.
(none)
> Add note about possible cause of `err-mimir-sample-duplicate-timestamp` for `ALERTS_FOR_STATE` metric emitted by rulers

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
ruler-querier is autoscaled based on CPU, memory and queries. The scaling metric based on queries has been recently introduced (#8060). When I introduced it, I didn't noticed that CPU and memory scaling metrics have no `cortex_` prefix but the queries one does. In this PR I'm fixing this inconsistency, removing the `cortex_` from the queries one too.
N/A
> Jsonnet: remove cortex_ prefix from ruler-querier HPA scaling metric

- pkg/ingester/ingester.go
- pkg/storage/ingest/config.go
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/util.go
- pkg/util/log/sampler_test.go
This is a follow-up to #8194. This PR adds fallback sampler for client errors when using ingest-storage.
> Ingest-storage: Add fallback sampler for client errors

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
The metric was only used to remove false positives for Mimir clusters with no tenants. using the zone with most series should still be a decent approximation for this.
cortex_distributor_replication_factor is no longer emitted when using ingest storage (Kafka).
> mixin: Remove usage of cortex_distributor_replication_factor from MimirIngesterInstanceHasNoTenants

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir/ingest-storage.libsonnet
In this PR I'm upstreaming a config I've tested in our test envs: set `-ingest-storage.kafka.consumer-group-offset-commit-interval=5s` in ingesters when running experimental ingest storage. I introduced this config option in https://github.com/grafana/mimir/pull/8135. The default value is 1s, I'm increasing it to 5s, which means `OffsetCommit` rate will decrease by a 5x factor.
N/A
> Jsonnet: set -ingest-storage.kafka.consumer-group-offset-commit-interval=5s

- .github/workflows/scripts/build-images.sh
- .github/workflows/test-build-deploy.yml
- CHANGELOG.md
- Makefile
- cmd/mimir/Dockerfile
- cmd/mimir/Dockerfile.alpine
Make distroless the default base image for grafana/mimir. To minimize the change, i just switched dockerfiles and changed makefile, pipeline stayed mostly untouched.
- n/a Tests updated.
> Build: Make distroless image default and publish mimir-alpine

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/mimirpb/timeseries.go
Don't discard time series in distributor with invalid exemplars, just drop affected exemplars. Backport of https://github.com/grafana/mimir/pull/8224.
> Distributor: Don't drop time series with invalid exemplars (#8224)

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/api_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- pkg/util/validation/limits.go
- vendor/github.com/hashicorp/go-hclog/README.md
- vendor/github.com/hashicorp/go-hclog/intlogger.go
- vendor/github.com/hashicorp/go-hclog/logger.go
- vendor/github.com/prometheus/alertmanager/silence/silence.go
- vendor/modules.txt
This pull request adds support for silence limits https://github.com/prometheus/alertmanager/pull/3852.
> Support limits for silences

- CHANGELOG.md
- go.mod
- pkg/api/api.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
Fixes #8185 , as discussed there are 2 possible ways to solve this:
- pass a error handling function to handler, have 2 different implementation for otlp and normal push request
- replicate the handler function for otlp and normal push request.
This PR is using the 2nd solution since it allows us to have more different logics for otlp endpoint in the future.
> Distributor: make OTLP endpoint return marshalled proto bytes as response body for errors

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/alertmanager/multitenant.go
- pkg/util/validation/limits.go
- vendor/github.com/prometheus/alertmanager/silence/silence.go
- vendor/modules.txt
This pull request updates `--alertmanager.max-silences-count` to include expired silences. It vendors https://github.com/prometheus/alertmanager/pull/3862.
> Update --alertmanager.max-silences-count to include expired silences

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir/autoscaling.libsonnet
In this PR I'm upstreaming a change we did long time ago in Grafana Labs to improve distributor HPA to only take in account ready pods when computing the actual CPU and memory utilization.
N/A
> Jsonnet: Improve distributor HPA

- CHANGELOG.md
- pkg/compactor/compactor.go
This adds a separate metric to count how many times a compaction failed due to an out of space error.
We need to be able to alert on out of space conditions with higher criticality than we alert on compaction failures because generic compaction failures can happen due to various transient issues such as network lag and we wouldn't want to get alerted on every network lag, an out of space condition is usually not transient and it usually requires an operator to resolve the problem so it makes sense to separate that metric from other compaction failures.
> add metric to track out-of-space errors

- development/common/config/nginx.conf.template
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/gateway/nginx-configmap.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/ingress.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-requests-and-limits-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-ruler-dedicated-query-path-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/nginx/nginx-configmap.yaml
- pkg/api/api.go
Exposes the `/multitenant_alertmanager/configs` endpoint in the gateway nginx configuration. On `main` this would return a `404` while in this branch a file gets downloaded.
Partly #6025
> Expose /multitenant_alertmanager/configs endpoint

- CHANGELOG.md
This PR moves the changelog entry for #6898 to the correct place.
#6898
> Fix changelog entry order

- docs/sources/mimir/manage/mimir-runbooks/_index.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
- pkg/util/globalerror/user.go
This PR is a follow up of https://github.com/grafana/mimir/pull/8077. As mentioned in https://github.com/grafana/mimir/pull/8077:
> The splitting is a best-effort. If a single Timeseries or Metadata entry is bigger than the allowed max size (about 16MB) then the result record will still be rejected by Kafka. I want to treat such case as a client-side error, so that the client will not indefinitely try to push a WriteRequest which will consistently fail. To keep this PR smaller, I will do this change in a follow up PR.
In this PR I'm changing the write path to return 400 HTTP status code if a WriteRequest can't be written to Kafka even after splitting. It's expected to be a rare event, but it could happen on edge cases. When it happens, we don't want the client to infinitely retry sending …
> Return 400 status code if a write request is too large to be ingested via Kafka even after splitting

- Makefile
- pkg/distributor/otlp/generate.sh
Fix generating of OTLP code:
* Change `make check-generated-otlp-code` to instruct the user to run `make generate-otlp` and not just `generate-otlp`
* Fix pkg/distributor/otlp/generate.sh so it doesn't emit a warning on Linux
Currently pkg/distributor/otlp/generate.sh emits the following warning on Linux:
```console
which: no gsed in (/usr/lib/go/bin:/home/arve/.gem/ruby/3.0.0/bin:/home/arve/.volta/bin:/home/arve/go/bin:/home/arve/.local/bin:/opt/go/1.17.8/bin:/home/arve/.cargo/bin:/home/arve/.gem/ruby/3.0.0/bin:/home/arve/.volta/bin:/home/arve/go/bin:/home/arve/.local/bin:/opt/go/1.17.8/bin:/home/arve/.cargo/bin:/home/arve/.cargo/bin:/opt/google-cloud-cli/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/li …
```
> otlp: Fix generating of OTLP code

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads-resources.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes-resources.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This PR fixes the disk space utilization panels which are not working when running with a kube-state-metrics version >= 2.10 because of missing kube_persistentvolumeclaims_labels metrics
Fixes #7515
> fix(mixins): disk space utilization panels

- CHANGELOG.md
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
This PR adds support for tracking active queries to the Mimir query engine.
(none)
> Mimir query engine: track active queries

- CHANGELOG.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/operators/binary_operation.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR improves the performance of binary operations for queries where the right side has fewer series than the left side.
Benchmark results for a query where the left side (`a_2000`) has 2000 series, and the right side has one series:
```
│ original.txt  │             after.txt              │
│    sec/op     │   sec/op     vs base               │
Query/a_2000_-_b_2000{l="1234"},_instant_query/streaming-10                            6.917m ±  4%   6.327m ± 1%   -8.53% (p=0.002 n=6)
Query/a_2000_-_b_2000{l="1234"},_range_query_with_100_steps/streaming-10              10.391m ±  6%   9.670m ± 1%   -6.94% (p=0.002 n=6)
Query/a_2000_-_b_2000{l="1234"},_range_query_with_1000_steps/streaming-10              47.98m ±  4%   46.55m ± 1%   -2.98% (p=0.041 n=6)
```
Latency and peak memory …
> Mimir query engine: improve performance for case where right side of binary operation has fewer series than the left side

- CHANGELOG.md
- pkg/querier/querier.go
- pkg/streamingpromql/benchmarks/comparison_test.go
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
This PR builds upon https://github.com/grafana/mimir/pull/8230 to add reporting of the per-query estimated peak memory consumption. 
The estimate is reported as a metric and in a `query stats` event added to the query's trace span.
Note that for consistency with the metrics added in https://github.com/grafana/mimir/pull/7898,  I've used the prefix `cortex_streaming_promql_engine...` for the metric name. I'll change the name to reflect the new name for the engine in a separate PR.
(none)
> Mimir query engine: report estimated peak memory consumption as a metric and in traces

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- integration/querier_test.go
- pkg/mimir/mimir_test.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/streamingpromql/benchmarks/comparison_test.go
- pkg/streamingpromql/compat/fallback_engine.go
- pkg/streamingpromql/compat/fallback_engine_test.go
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- tools/benchmark-query-engine/compare.sh
- tools/benchmark-query-engine/main.go
We've started referring to the new query engine as the "Mimir query engine" rather than the "streaming query engine", and the existing query engine as "Prometheus' query engine".
This PR updates the metrics emitted by the engine and the values of the `-querier.promql-engine` CLI flag to match this new preferred name.
I haven't renamed the `streamingpromql` package as that will be disruptive to in-progress PRs - we can change this later if it really annoys us.
Follow up to https://github.com/grafana/mimir/pull/8270
> Mimir query engine: rename metrics and CLI flag values to match new name

- CHANGELOG.md
- docs/sources/mimir/configure/about-anonymous-usage-statistics-reporting.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
Usage stats already include in-memory series. This PR also adds active series to reports. Active series give information closer to the users' needs, whereas in-memory series are more related to how the system handles load. Active series in combination with in-memory series also help estimate churn.
> usage stats: report active series

- CHANGELOG.md
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/storage/ingest/pusher.go
This PR adds `insight=true` label to push handlers when we're logging push error with 4xx status code.
This applies to both Prometheus and OTLP handlers. This PR also fixes some issues with updated OTLP handler found in https://github.com/grafana/mimir/pull/8227
> Add insight=true to push handlers

- pkg/alertmanager/alertmanager_test.go
This commit fixes the silence tests, using the exact same tests in prometheus/alertmanager to avoid regressions due to modules, but using the `New` function in `pkg/alertmanager/alertmanager.go` to ensure the correct limits are set.
~It bumps `go.mod` to commit [`db27a98`](https://github.com/grafana/prometheus-alertmanager/commit/db27a988d43e3a6fc7dcb1c182c50eb7e3c72be8) which is a no-op as Mimir does not vendor tests, but its meant to indicate we are using the fix from [prometheus/alertmanager#3866](https://github.com/prometheus/alertmanager/pull/3866).~
The changes to `go.mod` are no longer needed as https://github.com/prometheus/alertmanager/pull/3866 is included in https://github.com/grafana/mimir/pull/8200.
> Fix silence tests

- CHANGELOG.md
- pkg/util/objtools/s3.go
- tools/copyblocks/main.go
This one updates `copyblocks` package's `s3` client to allow configuring the part-size for multipart uploads.
Also, enable `pprof` endpoints in `copyblocks` tool.
> copyblocks: Configure s3 upload part size

- CHANGELOG.md
- operations/mimir-tests/test-automated-downscale-generated.yaml
- operations/mimir-tests/test-compactor-concurrent-rollout-generated.yaml
- operations/mimir-tests/test-consul-multi-zone-generated.yaml
- operations/mimir-tests/test-deployment-mode-migration-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-0-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir-tests/test-multi-zone-generated.yaml
- operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
- operations/mimir-tests/test-multi-zone-with-store-gateway-automated-downscaling-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-autoscaled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-caches-disabled-generated.yaml
- operations/mimir-tests/test-read-write-deployment-mode-s3-generated.yaml
- operations/mimir/rollout-operator.libsonnet
These features will be re-added once it's rolled out everywhere in our cloud. For now, it's easier to defer addition here until internal rollouts are finished.
> Revert configmaps permissions and use-zone-tracker

- CHANGELOG.md
- pkg/querier/querier.go
- pkg/querier/stats/query_metrics.go
- pkg/streamingpromql/benchmarks/comparison_test.go
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/binary_operation_test.go
- pkg/streamingpromql/pooling/limiting_pool.go
- pkg/streamingpromql/pooling/limiting_pool_test.go
- pkg/streamingpromql/query.go
- pkg/util/limiter/query_limiter_test.go
This PR builds on https://github.com/grafana/mimir/pull/8230, and adds incrementing the `cortex_querier_queries_rejected_total{reason="max-estimated-memory-consumption-per-query"}` metric when a query is rejected for exceeding the per-query memory consumption limit.
(none)
> Mimir query engine: report queries rejected due to hitting the memory consumption limit in the `cortex_querier_queries_rejected_total` metric

- CODEOWNERS
Requesting to add myself to CODEOWNERS for go.mod, so.sum and vendor/ so that
Alertmanager maintainers have a representative to approve vendoring updates.
> Add myself to CODEOWNERS for dependencies.

- CHANGELOG.md
- pkg/mimirtool/rules/compare.go
- pkg/mimirtool/rules/compare_test.go
This PR builds on https://github.com/grafana/mimir/pull/8295. While testing https://github.com/grafana/mimir/pull/8295 I've noticed that the rule group config is not re-synched if you only change `query_offset` or `evaluation_delay`. That's because we don't check these fields in the comparison.
This PR fixes it.
N/A
> mimirtool rules sync: fix sync when query_offset or evaluation_delay change

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
You can use \`ref\` URIs in admonitions (or any shortcodes) because they are inline and not subject to the issues noted in the [\`admonition\` shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/#code-shortcode:~:text=to%20core%20understanding.-,WARNING,For%20more%20information%2C%20refer%20to%20Markdown%20Reference%20Links%20in%20Shortcodes.,-Examples).
The \`ref\` URIs perform the same pattern matching as \`docs/reference\` but don't require the use of reference-style links and the destinations are ordinary (full) URLs that can include version substitution. Unlike \`docs/reference\`, the implementation doesn't use \`relref\` so you don't have to be careful with omitting trailing slashes and the links will follow redirects.
Documentation: …
> Replace docs/reference shortcode with ref URIs

- pkg/ingester/circuitbreaker.go
- pkg/ingester/circuitbreaker_test.go
This PR removes a redundant configuration introduced in #8180. 
> Ingester circuit breakers: remove unnecessary configuration

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-slow-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-slow-queries.json
- operations/mimir-mixin/dashboards/slow-queries.libsonnet
This allows us to switch to the ruler query path for slow query investigation.
> Add `component` variable to "Slow queries" dashboard

- Makefile
- mimir-build-image/Dockerfile
Upgrades `mimir-build-image` to `go1.22.4`. Go 1.22.4 includes [security fixes](https://go.dev/doc/devel/release).
> Upgrade mimir-build-image to go1.22.4

- development/mimir-microservices-mode/config/mimir.yaml
- pkg/scheduler/queue/query_component_utilization.go
- pkg/scheduler/queue/query_component_utilization_test.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Adds two channels to the `RequestQueue` to handle notifications for queries being sent to the querier, then being completed/canceled.
This is to ensure accurate tracking of the query component utilization and the corresponding metric `cortex_query_scheduler_querier_inflight_requests` - the `RequestQueue` will need this information to make dequeuing decisions once the new queue structures are ready.
There are many workable ways to do this, but the main points are we must:
* always increment anything sent to a querier or attempted to be sent to a querier
* always decrement for anything completed, canceled, or that failed to be sent to a querier
We also cannot add anything to the internal `querierInflightRequests` tracking map until we are ready to increment the utilization, because later if …
> Query Scheduler: fix inflight request tracking

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
@codesome this one fixes a couple of TODOs in the `blockbuilder`
1. Make sure consumer consumes up to the known lag, which fixes the empty fetches.
2. Move consumption interval to config.
3. Fix the logic around how `currEnd` is calculated inside the cycle (still needs checking, but at least it makes it so builder  created the actual blocks).
4. Refactor the internals of TSDB to make unit-testing simpler.
> blockbuilder: consume partitions up to their lag

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/promql/promqltest/testdata/native_histograms.test
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Updates mimir-promteheus to bring changes from:
- https://github.com/prometheus/prometheus/pull/13286
- https://github.com/prometheus/prometheus/pull/14286
Fixes an internal issue.
> Update mimir-prometheus to incl MemPostings improvements

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
- pkg/mimir/modules.go
- pkg/storage/tsdb/block/meta.go
@narqo 
We follow a simple approach: upload the blocks as soon as they are created. Since we need the blocks to be uploaded before we do a kafka commit, there is no point of using the shipper code.
> BlockBuilder: Uploads of blocks once they are compacted

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/grafana/dskit/cache/memcached_client.go
- vendor/github.com/grafana/dskit/middleware/logging.go
- vendor/github.com/grafana/dskit/spanprofiler/tracer.go
- vendor/modules.txt
Specifically, pulls in https://github.com/grafana/dskit/pull/530 to fix an issue where we may inadvertently cache things forever.
Related https://github.com/grafana/dskit/pull/530
> Update to latest dskit commit

- CHANGELOG.md
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR makes use of https://github.com/prometheus/prometheus/pull/14038 to assert that the error messages returned by binary operations are as expected when multiple matching series are found on one side of a one-to-one match.
Note that Prometheus' engine and Mimir's engine return different but equivalent error messages: Mimir's engine includes more detail in all cases.
Addresses TODO from https://github.com/grafana/mimir/pull/8096
> Mimir query engine: extend binary operation tests to assert on error messages

- CHANGELOG.md
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
While making use of `RegisterInstantVectorFunctionOperator` in an internal project, I noticed that we didn't completely rename everything to include the word "factory" where appropriate.
This PR clarifies those names.
#8256
> Mimir query engine: complete renaming from #8256

- Makefile
- mimir-build-image/Dockerfile
GitHub Actions has started rolling out [a new runner image](https://github.com/actions/runner-images/blob/ubuntu22/20240609.1/images/ubuntu/Ubuntu2204-Readme.md), which uses Docker v26. 
[The previous runner image](https://github.com/actions/runner-images/blob/ubuntu22/20240603.1/images/ubuntu/Ubuntu2204-Readme.md) used Docker v24.
Older versions of Skopeo are not compatible with Docker v25+ (see [this comment](https://github.com/containers/skopeo/issues/2251#issuecomment-1991834580)), which causes CI failures if the integration tests run on a runner with the new image ([example](https://github.com/grafana/mimir/actions/runs/9476587636/job/26110030171?pr=8346#step:11:11)).
This PR bumps Scopeo to the latest available version.
(none)
- …
> Bump Skopeo in build image to latest version

- CHANGELOG.md
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
- pkg/querier/remote_read.go
- pkg/util/http.go
Add logging of the start, end time and matchers for remote read requests in query stats and activity tracker.
Fixes https://github.com/grafana/mimir-squad/issues/2064
> Remote read is first class: query stats and activity tracker

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
- pkg/distributor/errors_test.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
Errors produced by distributors are of type `distributor.Error`. Depending on a use case, they are mapped to the corresponding gRPC and/or HTTP errors:
- `distributor.Push()` converts them to errors with a gRPC status (by using gogo's `status` package) and, therefore, gRPC status codes.
- `distributor.handler()` converts them to HTTP errors with HTTP status codes. 
- `distributor.otlpHandler()` converts them to an HTTP response, encoding a gRPC status, gRPC status code and HTTP status code.
In case of `distributor.Push()`, there is a method that does mapping between `distributor.Error` implementations and gRPC status codes ([here](https://github.com/grafana/mimir/blob/32c668c2722f4db97c20eeb97dc985b39cabd3b6/pkg/distributor/errors.go#L257-L287)). Similarly, there is another method that …
> Distributor: improve error handling in otlp and push handler

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/tsdb.go
@narqo this moves some logic out of `consumePartition` and into the `nextConsumeCycle`. Main aim of this is to make `consumePartition()` simpler where it just starts consuming from the partition until the given cycle end time. We also pass the block start and end times, and the last seen record as part of arguments.
We now do all the heavy lifting in nextConsumeCycle, where we call `consumePartition()` in parts when it is lagging. We calculate the timestamps appropriately.
> BlockBuilder: Refactor the consume cycle logic

- development/common/config/nginx.conf.template
- integration/alertmanager_test.go
- integration/configs.go
- integration/e2emimir/client.go
- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/distributor.go
- pkg/alertmanager/distributor_test.go
- pkg/alertmanager/merger/experimental_receivers.go
- pkg/alertmanager/merger/experimental_receivers_test.go
- pkg/alertmanager/multitenant.go
- pkg/api/api.go
Grafana Alertmanager has an extended version of the /receivers API that we would like to provide compatibility for. This API is however not in upstream Prometheus Alertmanager, and so the proposal is to add this API strictly under an experimental banner, and not change the existing /receivers API to maintain strict compatability with upstream.
> Alertmanager: Implement experimental extended /receivers API.

- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
In #8180 and #8285 we introduced ingester server-side circuit breakers. In #8315 we split circuit breakers related to the push request from those related to the read requests. In both cases, when a circuit breaker is open, ingesters return an instance of `ingester.circuitBreakerOpenError` (with error cause `mimirpb.CIRCUIT_BREAKER_OPEN`), which is then mapped to a gRPC error and returned to other Mimir components via rpc calls.
The PRs mentioned above didn't explicitly handle `ingester.circuitBreakerOpenError` to gRPC error mapping, so depending on the request type and the way ingester is configured, these errors might be mapped to `codes.Internal` or `codes.Unavailable` gRPC errors. Since distributor always translates errors with error cause `mimirpb.CIRCUIT_BREAKER_OPEN` to a …
> Ingester: map circuitBreakerOpenError to codes.Unavailable

- CHANGELOG.md
- go.mod
- go.sum
- pkg/distributor/otel.go
- pkg/distributor/push_test.go
- vendor/github.com/grafana/dskit/httpgrpc/httpgrpc.go
- vendor/github.com/grafana/dskit/httpgrpc/server/server.go
- vendor/modules.txt
PR https://github.com/grafana/mimir/pull/8227 introduced sending of binary HTTP response bodies to OTLP requests. Unfortunately our `httpgrpc.Server` implementation tries to use such response bodies as error message in `status.Status` objects, and marshalling such object then fails.
This PR fixes that by adding support for specifying different error message to use in `status.Status` object (PR in dskit TBD), and fixing OTLP handler to use this support.
> Fix reporting of HTTP error messages with binary body content

- CHANGELOG.md
- pkg/api/error/error.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/frontend/transport/handler_test.go
Make place for a remote read roundtripper that would wrap limits and blocking checks.
Update the format of how we log the remote read query matchers in query stats and activity tracker. This will enable having the same string in the logs and also the query blocker.
Relates to https://github.com/grafana/mimir-squad/issues/2148 (internal, make remote read first class)
> Remote read first class: workflow structure

- CHANGELOG.md
- docs/sources/mimir/manage/tools/mimirtool.md
- pkg/mimirtool/commands/rules.go
- pkg/mimirtool/commands/rules_test.go
Adds the ability to save a rule to a file via `mimirtool rules get`. The command in the current state only prints the rule out to console and the format is not a valid rule file for `mimirtool rules load`. Adds two new flag `--save-file` and `--output-dir`, which may seem to be a bit of over engineering but the hope is that we build on from here and have a "save all rules" ability which allows an easy one-liner backup in the future.
Fixes #7054 
**NOTE**
This is a copy of #7247 - I had to do some git trickery make it work and the pull request ended up being butchered. I'll try and port over all the context.
> feat: add save to directory option for mimirtool rules get

- operations/mimir-tests/test-compactor-concurrent-rollout-max-unavailable-percent-generated.yaml
- operations/mimir-tests/test-compactor-concurrent-rollout-max-unavailable-percent.jsonnet
- operations/mimir/config.libsonnet
This PR adds comment to `cortex_compactor_max_unavailable` field about using a percentage value. PR also adds test showing that using percentage works and is rendered into YAML correctly.
Note that using percentage requires https://github.com/grafana/rollout-operator/pull/153.
> Using cortex_compactor_max_unavailable as percentage

- CHANGELOG.md
- pkg/frontend/querymiddleware/instrumentation.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
In this PR I propose to add `TestMiddlewaresConsistency`. This test will help us to ensure that we'll not forget to add a new query-frontend middleware (in the future) to each type of request. If a middleware is specific to a type of request, then the test allows to define exclusions from the check (e.g. `splitAndCacheMiddleware` is intentionally only used by range queries).
All middlewares are excluded for remote read because we're still working on making it a first class citizen.
N/A
> Add TestMiddlewaresConsistency

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/backward_compatibility.go
- integration/backward_compatibility_test.go
- integration/e2emimir/services.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
Krajo and I are building remote read limits enforcement in the query-frontend. We're doing it through subsequent PRs, but we don't want to roll it out until it's finished and properly tested. In this PR I'm proposing to introduce a temporarily config option (`-query-frontend.remote-read-limits-enabled`) to enable remote read limits enforcement conditionally (disabled by default). The config option will be removed once the work is completed.
N/A
> Add temporarily config option -query-frontend.remote-read-limits-enabled

- CHANGELOG.md
- operations/mimir-tests/test-pvc-auto-deletion-generated.yaml
- operations/mimir-tests/test-pvc-auto-deletion.jsonnet
- operations/mimir/mimir.libsonnet
- operations/mimir/pvc-auto-deletion.libsonnet
This PR upstreams a change we've been using internally at Grafana Labs for some time now: automatically deleting stale PVCs after scaling down compactors, store-gateways or read-write mode backends.
This relies on the [beta PVC auto-deletion feature in Kubernetes](https://kubernetes.io/blog/2023/05/04/kubernetes-1-27-statefulset-pvc-auto-deletion-beta/), which is enabled by default in Kubernetes 1.27. 
This mirrors the similar change to the Helm chart (#6106), but does not include ingester or alertmanager PVCs as we have not yet tested this ourselves.
I've left auto-deletion disabled by default to mirror the Helm chart and also not cause issues for anyone on an old version of Kubernetes.
(none)
- [n/a] …
> Jsonnet: automatically remove stale PVCs after scaling down compactors, store-gateways and backends

- CHANGELOG.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
When testing https://github.com/grafana/mimir/pull/8374 I've found that that `-querier.max-query-lookback` and `-compactor.blocks-retention-period` are not enforce in the query-frontend if only 1 of the 2 are set. This PR fixes it.
N/A
> Fix -querier.max-query-lookback and -compactor.blocks-retention-period enforcement in query-frontend when one of the two is not set

- Makefile
- mimir-build-image/Dockerfile
- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/sender_test.go
- pkg/distributor/otel_test.go
- pkg/distributor/push_test.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/ingester/ingester_test.go
- pkg/mimirpb/compat_test.go
- pkg/mimirpb/timeseries_test.go
- pkg/querier/api/consistency_test.go
- pkg/storegateway/indexcache/cache.go
- pkg/storegateway/indexcache/inmemory.go
- pkg/streamingpromql/functions/common.go
- pkg/streamingpromql/operators/function_over_instant_vector_test.go
Upgrade to golangci-lint v1.59.1.
> mimir-build-image: Upgrade golangci-lint

- CHANGELOG.md
- pkg/compactor/bucket_compactor.go
- pkg/compactor/compactor_test.go
This PR adds histograms to track duration of succcesful compaction jobs, and number of blocks per job.
This PR also adds `block_count` field to several log messages, most importantly `compaction job succeeded`, as knowing number of compacted blocks is often useful when tweaking compactor parameters (esp. split groups).
> Add histograms to track duration of compaction jobs, and number of blocks per job.

- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/model_extra_test.go
follow-up of https://github.com/grafana/mimir/pull/8342
This PR extends the cloning of headers in all `WithXXX` methods for instant and range query requests.
Fixes N/A
> frontend: clone headers in `WithXXX` query request methods

- pkg/frontend/querymiddleware/cardinality_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/step_align.go
In #8374 I've an use case where `WithStartEnd()` may return error. In this PR I propose to add `error` return support to `WithStartEnd()`. We already use the same pattern in `WithQuery()`, reason why I don't think this change is much contentious.
N/A
> Add return error support to MetricsQueryRequest.WithStartEnd()

- pkg/frontend/querymiddleware/roundtrip.go
Make it more explicit that injection is only applied to instance and range queries.
Follows #8342
Related to https://github.com/grafana/mimir-squad/issues/2148
> Make extra middleware injection more specific

- pkg/frontend/querymiddleware/model_extra_test.go
#8379 and #8392 were merged few seconds apart, and they had conflicting changes causing CI to fail. This PR fixes it.
N/A
> Fix unit tests after conflicting PRs merged

- CHANGELOG.md
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/main.go
- docs/sources/mimir/configure/about-versioning.md
This was deprecated in 2.11 and is being removed for the 2.13 release
> Remove buffered logger flag

- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/frontend/transport/handler.go
In this PR I propose to enforce `limitsMiddleware` for remote read requests too.
Before this PR, `-query-frontend.max-query-expression-size-bytes`, `-query-frontend.max-total-query-length` and `-querier.max-query-lookback` were not enforced for remote read requests in the query-frontend. After this PR, they're enforced in the query-frontend. If a remote read request contains only 1 out of N queries failing because of the limit, the whole remote read request will be rejected (as of today it's quite difficult to only fail 1 out of N queries).
The main change in this PR is about introducing support to manipulate the remote read queries before they're passed to downstream (querier). This is needed by the `-querier.max-query-lookback` enforcement done by `limitsMiddleware`.
N/A
> Query-frontend: enforce limitsMiddleware for remote read requests

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/querier/tenantfederation/tenant_federation.go
- pkg/util/validation/limits.go
* ruler tenant federation support
* limiting max-tenants for federated queries
* enabling/disabling recording & alerting rules per tenant 
I looked mostly at features that have been added a long time ago (~2 years for ruler changes) and that have been at use extensively by the community (multi-tenant ruler) or at Grafana Labs (enabling/disabling rule evaluations & max-tenants limit for federated queries).
This PR also fixes a typo and adds the PR number for a changelog entry
Related to https://github.com/grafana/mimir/issues/8390
> Promote experimental features to stable

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
Today, if an error occurs in the query-frontend middlewares, the "query stats" log contains `status_code=0`. However, we actually return a valid HTTP response to the client, with a legit status code, so we should log the actual `status_code`.
This PR fixes it.
N/A
> Fix the response status code logged in 'query stats' on error

- CHANGELOG.md
- pkg/frontend/querymiddleware/blocker_test.go
While working on https://github.com/grafana/mimir/pull/8372 we noticed that `queryBlockerMiddleware` unit tests were just covering range queries. In this PR I'm adding instant queries and remote read requests too. I've introduced a new dedicated for remote reads because we don't receive a query expression but just label matchers.
N/A
> Chore: improve queryBlockerMiddleware unit tests

- CHANGELOG.md
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
In this PR I'm adding `op=remote_read` support to `cortex_query_frontend_queries_total` metric and adding remote read cases to `TestTripperware_Metrics`. It's important to note that Mimir doesn't use the step when executing a remote read request, so all logic around step-alignment should be (intentionally) skipped for remote reads.
N/A
> Add 'op=remote_read' support to cortex_query_frontend_queries_total metric

- CHANGELOG.md
- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
- pkg/storegateway/indexheader/snapshotter.go
- pkg/storegateway/indexheader/snapshotter_test.go
- pkg/util/test/leak.go
The PR updates `indexheader` in a way so `ReaderPool` preserved the blocks found in the pre-shutdown snapshot. ~~That it, when `ReaderPool` persists its own set of blocks to `lazy-loaded.json`, it also amends the set with the blocks, it eagerly loaded (or still loading) on startup. The changes make sure we only persist "fresh" blocks, so idle blocks will be evicted from the snapshots, eventually.~~
Fixes #8255
> indexheader: keep pre-shutdown snapshot between restarts

- .golangci.yml
- pkg/mimir/mimir.go
Enable `loggercheck` linter in golangci-lint, and fix a caught error. `loggercheck` makes sure that arguments to logging calls are paired.
> golangci-lint: Enable loggercheck linter

- pkg/frontend/querymiddleware/limits_test.go
While working on https://github.com/grafana/mimir/pull/8374 we noticed that we don't test `limitsMiddleware` against instant queries. In this PR I'm doing it. Specifically:
- `TestLimitsMiddleware_MaxQueryLookback`: create a new `TestLimitsMiddleware_MaxQueryLookback_InstantQuery` because the assertions for instant queries are different than range queries and remote reads
- `TestLimitsMiddleware_MaxQueryExpressionSizeBytes`: added instant queries
- `TestLimitsMiddleware_MaxQueryLength`: doesn't apply to instant queries because we run the check against the input query time range (and instant queries don't have a time range)
N/A
> Chore: add instant query to query-frontend limitsMiddleware tests

- docs/sources/mimir/configure/configure-spread-minimizing-tokens/index.md
This PR enriches the existing "Migrate ingesters to spread-minimizing tokens" documentation with some missing parts. In particular:
- It clarifies that it is necessary to disable ingester's read path shuffle-sharding before the migration, and specifies when it is possible to re-enable it once the migration is completed.
- It states that it is necessary to delete the files where ingesters used to store the old tokens before the migration. 
> Update the spread-minimizing token migration documentation

- CHANGELOG.md
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/frontend/querymiddleware/stats.go
- pkg/frontend/querymiddleware/stats_test.go
- pkg/ingester/client/compat_test.go
Query-frontend: add length, time_since_min_time and time_since_max_time statistics to the query stats logs.
These are generated by the `queryStatsMiddleware` and this PR will enable this middleware for remote read requests.
There are two decisions made by the PR:
- since a remote read request contains multiple queries, we define the overall start, minT and end, maxT times as the minimum and maximum of the individual query times. The assumption is that one remote read contains related queries.
- Mimir ingesters to not take into account the query step hint from remote read requests. To avoid making decisions and updating metrics based on the ignored step hint, we clear the step hint from the request before other middlewares.
Related to https://github.com/grafana/mimir-squad/issues/2148 …
> Remote read first class: query stats middleware

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ingester/activeseries/custom_trackers_config.go
- pkg/ingester/activeseries/custom_trackers_config_test.go
- pkg/mimir/runtime_config_test.go
- pkg/mimirtool/config/inspect.go
- pkg/ruler/api.go
- pkg/ruler/compat.go
- pkg/ruler/ruler.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_map.go
- pkg/util/validation/limits_map_test.go
- pkg/util/validation/limits_test.go
- pkg/util/validation/notifications_limit_flag.go
- pkg/util/validation/notifications_limit_flag_test.go
- tools/doc-generator/parse/parser.go
Introduces a new limit named `ruler_max_rules_per_rule_group_by_namespace` which allows one to specify which namespaces do we want to be different to have a different limit in terms of rules per group.
With this change, we now have a hierarchy for this limit as follows:
1. Per tenant limit for the given namespace.
2. Default limit for the given namespace.
3. Per tenant limit set by RulerMaxRulesPerRuleGroup
4. Default limit set by RulerMaxRulesPerRuleGroup
This is part 1 of the change, and I need to extend the same level of support to the other limit related to rule groups of `MaxRuleGroupsPerTenant`.
**Marking it as a draft as I still have some work to do around the documentation and experimental guarantees**
> Extend max rules per rule group limit to be supported per namespace

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
This one simplifies the internals of `Blockbuilder.NextConsumeCycle` by reducing the amount of calls to Kafka admin API. That it, all the data we require, when iterating over the partitions is already requested inside the `kadmClient.Lag` call.
> blockbuilder: refactor internals of next consume cycle

- pkg/frontend/querymiddleware/cardinality.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/model_extra_test.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
Get rid of `panic` calls in the newly introduced `remoteReadQueryRequest`
Related to https://github.com/grafana/mimir-squad/issues/2148 (internal)
> Remove panic calls from remoteReadQueryRequest

- pkg/mimirpb/compat_test.go
- pkg/mimirpb/query_response_extra_test.go
- pkg/util/test/shape.go
This will become even more important with the upcoming V2 of the protocol which has an additional field in histograms called custom_values for custom bucket native histograms.
https://github.com/prometheus/prometheus/blob/cdebf06ad97d19c5cf5ed4d1e384503adee7c0b7/prompb/io/prometheus/write/v2/types.proto#L228
> Add unit test to check remote write v1 histogram equivalence

- CHANGELOG.md
- pkg/streamingpromql/testdata/upstream/functions.test
- pkg/streamingpromql/testdata/upstream/range_queries.test
This PR brings in the test cases added in https://github.com/prometheus/prometheus/pull/14305 so that they are run against the Mimir query engine.
(none)
> Mimir query engine: Add PromQL engine test cases from Prometheus

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/storage/bucket/s3/bucket_client.go
- pkg/storage/bucket/s3/config.go
This one adds a new configuration `s3.dualstack-enabled=true`, that allows user to disable S3 client from resolving the endpoint into dual-stack endpoint. The https://github.com/grafana/mimir/issues/7382 and https://github.com/minio/minio-go/issues/1766 explain the use cases where this can be needed.
Fixes #7382
> s3: Allow disabling dual-stack endpoints

- pkg/distributor/distributor_test.go
- pkg/distributor/query.go
- pkg/frontend/querymiddleware/codec.go
- pkg/ingester/client/chunkcompat.go
- pkg/ingester/client/compat.go
- pkg/ingester/client/compat_test.go
- pkg/ingester/ingester_test.go
- pkg/mimirpb/compat.go
- pkg/mimirpb/compat_test.go
- pkg/querier/partitioner.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_chunks_test.go
- pkg/storegateway/series_refs.go
- pkg/storegateway/series_refs_test.go
- pkg/util/labels.go
This improves efficiency, mostly in tests but a couple of non-tests too.
Split into four commits:
* storegateway tests: re-use Builder when creating labels - this is more efficient, especially with dedupelabels.
* storegateway: retain Builder in loadingSeriesChunkRefsSetIterator - saves memory allocation when moving to next series.
* mimirpb: add FromLabelAdaptersToKeyString - avoid converting to labels and then to string.
* labels: avoid double-converting around FromLabelAdaptersToMetric 
Benchmarks (after changing the benchmark to match usage):
```
│ before.txt  │             after.txt              │
│   sec/op    │   sec/op     vs base               │
SeriesMap-28   46.13m ± 2%   22.93m ± 5%  -50.29% (p=0.002 n=6)
│  before.txt   │              after.txt              │
│     B/op …
```
> Refactoring: shift between Labels and LabelAdapters to align better with dedupelabels

- CHANGELOG.md
- tools/tsdb-series/main.go
This PR modifies `tsdb-series` to print series stats (min/max timestamp, samples, DPM). This is useful when tracking down series with high DPM.
> Enhance tsdb-series to print series stats (min/max timestamp, samples, DPM)

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_metrics.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/tsdb.go
- pkg/mimir/mimir.go
This one addresses some of the TODOs, adding initial set of metrics to `blockbuilder`.
JFI @codesome
> blockbuilder: Add initial set of metrics

- pkg/storegateway/indexheader/snapshotter.go
- pkg/storegateway/indexheader/snapshotter_test.go
This one updates `indexheader.Snapshotter` in a way so the calls to `Stop` waited until the goroutine inside Start finished. This resolves occasional issues we see on the CI
```
--- FAIL: TestLabelValues_Cancelled (0.07s)
bucket_test.go:2909: Creating 2 1-sample series with 1ms interval in /tmp/TestLabelValues_Cancelled3429144703/001/0
bucket_test.go:2909: Creating 2 1-sample series with 1ms interval in /tmp/TestLabelValues_Cancelled3429144703/001/1
testing.go:1231: TempDir RemoveAll cleanup: unlinkat /tmp/TestLabelValues_Cancelled3429144703/001: directory not empty
```
I think this is a simpler way to resolve the issue, and also I'm not sure #8434 actually solves it. I'm opening the PR just to remove extra burden from Marco.
Fixes #8428
Closes #8434
> indexheader: call to Snapshotter.Stop must wait for its Start to finish

- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/model_extra_test.go
- pkg/frontend/querymiddleware/results_cache_test.go
- pkg/frontend/querymiddleware/step_align_test.go
Use minT and maxT fields as cache in PrometheusInstantQueryRequest for GetMinT and GetMaxT
The values were calculated then ignored.
Makes the behavior the same as PrometheusRangeQueryRequest.
Added unit tests where relevant.
Related to https://github.com/grafana/mimir-squad/issues/2148 (internal)
> Use minT and maxT fields as cache in PrometheusInstantQueryRequest

- CHANGELOG.md
- integration/backward_compatibility_test.go
- integration/e2emimir/client.go
- integration/querier_remote_read_test.go
- integration/query_frontend_test.go
- integration/util.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/querier/remote_read.go
- pkg/querier/remote_read_test.go
Currently, Mimir ignored remote read requests hints. When Prometheus issue a remote read request, the time range in hints may be different than the start/end time range. For example, if you run `count_over_time(up[1h]) + count_over_time(up[2h])` (example query) in Prometheus you get 2 remote read requests with the following time ranges:
```
start: 1718859107525 (04:51:47) end: 1718869907525 (07:51:47) hints start: 1718862707525 (05:51:47) hints end: 1718869907525 (07:51:47)
start: 1718859107525 (04:51:47) end: 1718869907525 (07:51:47) hints start: 1718859107525 (04:51:47) hints end: 1718869907525 (07:51:47)
```
_Apparently, the start/end is always the max one, and hints may specify a smaller one (apparently, it looks the opposite than a normal query execution where start/end should be the …
> Honor start/end in the remote read request hints

- operations/mimir-tests/test-new-resource-scaled-object-generated.yaml
- operations/mimir-tests/test-new-resource-scaled-object.jsonnet
- operations/mimir/autoscaling.libsonnet
This PR modifies jsonnet function `newResourceScaledObject` and adds optional `container_name` and `pod_regex` arguments, to specify alternative container name and optionally match only selected pods in scaling query.
> Add optional container name and pod regex in newResourceScaledObject function

- CHANGELOG.md
This cuts the changelog as of r295.
> 2.13 release: tidy up & cut changelog

- pkg/querier/batch/batch.go
- pkg/querier/batch/batch_test.go
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/querier/partitioner.go
- pkg/querier/partitioner_test.go
- pkg/querier/querier.go
While working on #8463 I noticed that the chunk merge iterator takes the querier's min/max in input but it's never used. In this PR I'm cleaning it up.
N/A
> Chore: remove unused min/max in chunk merge iterator

- CHANGELOG.md
- integration/querier_remote_read_test.go
- pkg/querier/remote_read.go
- pkg/querier/remote_read_test.go
A remote read request executed in SAMPLES mode can return samples outside of the queried range. The reason is that, for performance reasons, in Mimir we don't have a strong guarantee that samples outside the queried time range are filtered out by the `Queryable`; at the end, PromQL engine will do it anyway. However, in a remote read request we may save on same returned data by filtering out samples out of the queried time range, which is what I'm proposing in this PR.
N/A
> Return only samples within the queried start/end time range when executing a remote read request using SAMPLES mode

- CHANGELOG.md
* cherry picked from commit 05c711d740d8cbcee00d70d495294b31274b2dae  (#8459)
* unmerged changes from https://github.com/grafana/mimir/pull/8476
* removes "unreleased"  section from changelog
> [release-2.13] 2.13 release: tidy up & cut changelog

- CHANGELOG.md
- pkg/storegateway/indexheader/stream_binary_reader.go
otherwise storing the sparse header can fail and leave a corrupted sparse header on disk
> store-gateway: atomically store sparse headers

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/overview.libsonnet
Fix bug in #7674 . Deployment with gateway enabled ended in:
```
valuating jsonnet in path ...': RUNTIME ERROR: Field does not exist: readRequestsPerSecondMetric
/vendor/github.com/grafana/mimir/operations/mimir-mixin/dashboards/overview.libsonnet:181:13-58
/vendor/grafana-builder/grafana.libsonnet:534:86-96   thunk from <thunk from <thunk from <object <anonymous>>>>
/vendor/mixin-utils/utils.libsonnet:78:17-23  object <anonymous>
<std>:773:15-21 thunk <val> from <function <format_codes_obj>>
<std>:780:27-30 thunk from <thunk <s> from <function <format_codes_obj>>>
<std>:604:22-25 thunk from <function <format_code>>
<std>:604:9-26  function <format_code>
<std>:780:15-50 thunk <s> from <function <format_codes_obj>>
<std>:785:24-25 thunk from <thunk <s_padded> from <function …
```
> mixin: fix naming consistency between gateway and query-frontend

- CHANGELOG.md
it's risky to backport this to 2.13 because it relies on a different version of thanos-io/objstore
it has already been included on the release branch via https://github.com/grafana/mimir/pull/8477
> changelog: move 8405 back into unreleased

- renovate.json
See title. 2.10 was left there for too long. The plan is to remove 2.11 once 2.13 has a promoted RC
> Update renovate.json with 2.13 release

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/multitenant.go
There's no need to pass a userID to `Alertmanager.ApplyConfig()`, the Alertmanager already holds that data internally.
> Alertmanager: Use the Alertmanager's userID in ApplyConfig

- integration/e2emimir/client.go
We're checking the same error twice, the second check is redundant.
> Alertmanager: Remove redundant error check

- CHANGELOG.md
- operations/mimir/ingest-storage-migration.libsonnet
Add config options to easily set partition ingesters replicas. The jsonnet tests output hasn't changed because 1 replica per StatefulSet is the default.
N/A
> Jsonnet: add config options to easily set partition ingesters replicas

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir/ingest-storage-migration.libsonnet
- operations/mimir/ingest-storage.libsonnet
Increase -distributor.remote-timeout when ingest storage is used. Depending on which Kafka-compatible backend is used, the latency ingesting write requests may be higher than classic ingesters.
N/A
> Jsonnet: increase -distributor.remote-timeout when ingest storage is used

- pkg/frontend/v1/frontend.go
- pkg/scheduler/queue/query_component_utilization.go
- pkg/scheduler/queue/query_component_utilization_test.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/scheduler.go
The use of a gauge was preventing us from almost ever seeing the peak values in the scraped data.
Using this summary instead with and querying like
```promql
sum by(query_component) (last_over_time(cortex_query_scheduler_querier_inflight_requests{quantile="0.99"}[1m]))
```
gives us a better look at real-time peak values for these statistics which will be used for query-scheduler load balancing decisions
previously, querying these metrics never reached their theoretical max, which is equal to all querier worker connections ever though we could see in logs that it was maxed out. This is fixed now:
> query-scheduler querier inflight requests: convert to summary metric

- pkg/scheduler/scheduler.go
mistakenly introduced in previous PR https://github.com/grafana/mimir/pull/8417
See before and after fix in this screenshot - restarted with new code around that 15:33 mark
Mass canceling requests no longer results in the inflight requests count exceeding the connected querier workers
> scheduler querier inflight request tracking fix: mark completed on frontend cancel

- CHANGELOG.md
- pkg/querier/blocks_store_queryable.go
This PR fixes an issue where store-gateway streams aren't immediately cleaned up once we no longer need them - either because the request resulted in no series, or because chunks streaming is not in use and all chunks have been received.
For example, if the querier is configured to stream chunks from store-gateways and a store-gateway returns no series, we would have held the stream open until the query was finished.
Amongst other things, this fixes the issue where trace spans for requests to store-gateways that return no series are misleadingly reported as having failed with a "context canceled" error. (This is because the stream is later closed when the overall query context is cancelled when the query is completed.)
(none)
- [n/a] …
> Close store-gateway streams as soon as they're not needed

- go.mod
- go.sum
- pkg/alertmanager/alertmanager.go
- vendor/github.com/prometheus/alertmanager/silence/silence.go
- vendor/modules.txt
This commit fixes a bug where per-tenant silence limits were not reloaded during runtime. This happened because per-tenant limits were read at initialization time for a per-tenant Alertmanager and then never again. Instead, silence limits are read each time they are needed. Mimir uses an in-memory cache for per-tenant limits, and silence limits are only checked when creating new silences or updating existing silences.
Fixes https://github.com/grafana/alerting-squad/issues/825
> Fix per-tenant silence limits not reloaded during runtime

- RELEASE.md
We agreed to update the release instructions with two changes
* make the helm release the responsibility of the Mimir release shepherd. The idea is that the OSS community can run the Mimir release candidate via a helm chart RC sooner and doesn't need to wait for the GEM release and a final helm chart release.
* change feature maturity right after cutting a release instead of right before a release. This gives more time to consider the changes and doesn't block the release.
> Update RELEASE.md: helm release & feature lifecycle

- pkg/storegateway/indexheader/snapshotter.go
- pkg/storegateway/indexheader/stream_binary_reader.go
- pkg/util/atomicfs/fsync.go
- pkg/util/atomicfs/fsync_test.go
The current atomicfs package exposes methods that operate on paths and write the entire contents of a file, buffering it in memory first. This means that they cannot operate on large files.
This change exposes an `os.File` like API so that the contents of a file can be written without needing to keep the entire file in memory. It also keeps a `CreateFile` method for simplicity  _but_ changes its implementation to not require reading the entire `io.Reader` into memory first.
This also changes the behavior of the atomicfs package so that files are _always_ renamed from a temporary file to the final path. The only place in Mimir using atomicfs that did not already make use of renaming these files is the shutdown marker functionality.
Related #8485
> Refactor atomicfs package to expose file-like API

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_index_postings.go
- pkg/storegateway/bucket_index_reader.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/header_test.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/lazy_binary_reader_test.go
- pkg/storegateway/indexheader/reader_benchmarks_test.go
- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
- pkg/storegateway/indexheader/stream_binary_reader.go
- pkg/storegateway/series_refs.go
- pkg/util/test/leak.go
Allows requests to abort waiting for lazy loading to complete if the request is cancelled. However, we don't want the `LazyBinaryReader` to abort loading the binary reader.
The main challenge with the current implementation was the usage of mutexes. Doing this with mutexes is impractical because they block until the mutex is acquired and there's no way to abort waiting (without doing busy loops with `TryLock()`).
Because of this challenge I chose to reimplement the synchronisation in the `LazyBinaryReader` with a control loop rather than a mutex (see `LazyBinaryReader.controlLoop`).
There is a single goroutine which ordered the reads and writes (load/unload) of the underlying binary reader.
Interacting with the state happens via sending a callback to a channel (a request).
The control …
> store-gateway: don't wait on lazy loading if queries are canceled

- Makefile
- mimir-build-image/Dockerfile
Updating mixtool to latest commit.
N/A
> Build image: update mixtool to latest commit

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
When doing a review of ingest storage alerts I noticed that the threshold for `MimirRunningIngesterReceiveDelayTooHigh` is pretty high (10m delay when running). If delay is > 10m, the Mimir cluster is already in a pretty bad state (e.g. data older than 10m is cached by default). In this PR I propose to significantly lower the threshold and split into 2 alerts (same name, since they alert on the same symptom):
1. delay > 2m for at least 3 minutes (when you get paged the delay should be up to 2+3+1 evaluation delay+1 evaluation interval=7 minutes, which is still quite high, but better than the current alert which is 10+5+1+1=17 minutes)
2. delay > 30s for at least 15 minutes (to catch the case an ingester is constantly delayed few tens seconds, but delay doesn't increase to trigger the …
> Alerts: tune MimirRunningIngesterReceiveDelayTooHigh to be more reactive

- pkg/alertmanager/distributor.go
The experimental, extended /receivers API provides information about the last
notification attempt for receivers, including the last error and duration.
Currently, because of how the Alertmanager ring is configured, we only require
a successful response from one replica. For the receivers API however this is
insufficient, because any of the 3 replicas could have sent notifications
recently. It's more likely that one of the replicas will (the replica in
"position 0"), but any replica could send any given notification, so asking
all replicas is arguably more robust.
> Alertmanager: Increase likehood of useful results from /grafana/receivers.

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
In this PR I propose to do small changes to improve dashboard panels about end-to-end latency and strong read consistency:
- Added query-frontend strong consistency queries ratio to "Mimir / Queries" dashboard. We already have a panel tracking it from ingester's PoV but I would like to track it from query-frontend PoV too. The query-frontend metric is tracked before the query is enqueued, while the ingester metrics are tracked only once the query hit ingesters.
- Added end-to-end latency panel to "Mimir / Queries" dashboard. We also have it in "Mimir / Writes" dashboard (where I suggest to keep it), but I propose to add it to "Mimir / Queries" dashboard too because this (along with "Reads" dashboard) are the main entrypoints when there's an issue on the read path.
- Converted hyphens to …
> Dashboards: improve end-to-end latency and strong read consistency panels

- pkg/storegateway/series_chunks.go
- pkg/storegateway/series_chunks_test.go
I discovered this while working on https://github.com/grafana/mimir/issues/8389. This shouldn't be a bug today because nothing above the preloading iterator looks at the context (IIRC this was the reason I didn't check the context in the first place). But it can become a problem in the future. I also verified in a few production clusters at GL and couldn't spot a gradual increase in the number of goroutines.
It's blocking detecting leaking goroutines in my work for https://github.com/grafana/mimir/issues/8389, so I'd like to fix it first.
> store-gateway: dont leak goroutines when preloading

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR adds a row of panels showing the behavior of ingester autoscaling, when NOT using ingester autoscaling. It is a counterpart to https://github.com/grafana/mimir/pull/7970.
The existing autoscaling uses `AverageValue` metrics, but for ingesters we want to use the `Value` type, so I renamed the existing helper function for the current replicas panel and added a `Value` counterpart.
The panels look like this:
> Add row for non-ingest-storage ingester autoscaling

- pkg/ruler/api.go
- pkg/ruler/namespace_protection.go
On my last commit of https://github.com/grafana/mimir/pull/8444, I refactored away the use of the `HTTPHeader` struct, I just forgot to remove it - so this PR does that.
N/A
> Remove unused `HTTPHeader` struct

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
Today we experienced a case where HPA has been inactive for an extended period of time due some issues. During this period, the autoscaling panels in dashboard reports 0 replicas, but that's not true. The fact that HPA is inactive (due some issues) doesn't mean we run 0 replicas, it just mean HPA can't take a decision whether what the desired number of replicas, and so the previous number of replicas is kept running.
In this PR I propose to remove the condition that was introduced in https://github.com/grafana/mimir/pull/4216 and causes the panels to display 0 current replicas if HPA is inactive.
Before this PR:
After this PR:
N/A
> Fix "current replicas" in autoscaling panels when HPA is not active

- CHANGELOG.md
- tools/wal-reader/main.go
This PR modifies `wal-reader` tool:
* Renamed `-series-entries` to `-print-series`
* Renamed `-print-series-with-samples` to `-print-samples` (it enables printing of individual samples, tombstones, exemplars or histograms)
* References to unknown series from Samples, Exemplars, histogram or tombstones records are now always logged.
> WAL reader changes

- pkg/alertmanager/sender.go
We're using the [default email sender from grafana/alerting](https://github.com/grafana/alerting/blob/5b0553a572d3b7890c7f50a2ec55841a6d65550e/receivers/email_sender.go#L75-L83), we don't need to implement the `EmailSender` interface in the `Sender` struct.
> Alertmanager: Remove unused SendEmail method from sender

- docs/sources/mimir/manage/tools/mimirtool.md
This commit improves the existing documentation for the migrate-utf8 command in mimirtool to make it easier for users to understand what the command does, how to use it, and it's relevance to the wider UTF-8 initative in Prometheus, Alertmanager and Mimir.
> mimirtool: Improve mimirtool docs for migrate-utf8

- docs/sources/mimir/_index.md
Updates the Mimir docs landing page to implement new page design and card grid layout.
> Docs landing page update

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/partitions.go
- pkg/blockbuilder/partitions_test.go
~~I'm still in the process of testing the corned cases against the changes, but so far they look promising~~
The primary idea of the changeset is to replace how a cycle works with the assigned partitions. Since now on, we look at the assignment as a queue, that we traverse start to end. Inside the partition processing, we now allow a rebalance between the subsequent calls to `kafka.PolRrecords`. If Kafka broker calls for rebalance, the partition processing bails, and the cycle continues with the next partition in the newly assigned queue. The "trick" is to make sure the cycle skips the partitions that had been already processed before the rebalance (refer to the implementation of `partitions.update()`).
> blockbuilder: improve how group handles rebalancing

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_metrics.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/partitions.go
- pkg/blockbuilder/partitions_test.go
- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
The flags were missing a `block-builder.` prefix.
I also fix the lint errors in this PR.
> Fix the flag names for BlockBuilder

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
This addresses [CVE-2024-24791](https://nvd.nist.gov/vuln/detail/CVE-2024-24791). [Golang release](https://go.dev/doc/devel/release#go1.22.5).
> Upgrade golang to 1.22.5

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
cherry picked from commit ddea70bd87fa40ad8654154280276de631fccea6 #8600
> [release-2.13] Upgrade golang to 1.22.5 

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
When commit record stays same as the previous cycle, we were handling it wrongly. Instead of keeping the old commit, we were taking the `lastRec` as the `commitRec` because of how `commitRec` was set. We identify that the first record was not fully processed, so the `commitRec` is set to the `lastRec` which is nil. So `commitRec` got wrongly overridden by the `lastRec` in this case.
In this PR what I am doing is passing around the last commit information. And when the first record is the one that is not fully processed, I am setting `commitRec` with the old commit info. That way comitting it correctly. We do need to re-commit in order to update the "last seen" timestamp in the metadata.
This was why the out-of-order test was failing (test was checking the right stuff apparently).
> Commit properly when we have to retain the old commit

- docs/sources/mimir/references/architecture/components/alertmanager.md
This commit adds documentation for how to enable UTF-8 strict mode in the Grafana Mimir Alertmanager, including both new and existing Mimir installations.
> Add documentation for UTF-8 strict mode

- docs/sources/mimir/release-notes/v2.12.md
This commit updates the release notes for v2.12 to include a missing experimental feature that adds support for UTF-8 in Alertmanager, released in Mimir v2.12.
> Update release notes for v2.12

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/bucket_stores.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/gateway.go
- pkg/storegateway/gateway_prepare_shutdown_http_test.go
- pkg/storegateway/gateway_test.go
This PR is the first in the refactoring for https://github.com/grafana/mimir/issues/8389. In this PR
1. `BucketStore` (single tenant) and `BucketStores` (multi-tenant) are now `services.Service`, which means they can be properly started and stopped
2. `BucketStore` currently does nothing on its lifecycle. This is because none of its dependencies are services.
3. `BucketStores` performs its initial sync in its startup routine and shuts down all of the `BucketStore` instances it hosts in its shutdown routine.
4. Add lifecycle handling to various tests
5. Break up `syncUsersBlocksWithRetries` into `ownedUsers` and `syncUsersBlocks`  so that  `TestBucketStores_ownedUsers` only tests what it needs to - user sharding - and not the whole startup procedure.
Related to …
> store-gateway: Add services for BucketStore(s)

- CHANGELOG.md
- pkg/continuoustest/metrics.go
- pkg/continuoustest/util.go
- pkg/continuoustest/util_test.go
- pkg/continuoustest/write_read_series.go
- pkg/continuoustest/write_read_series_test.go
This PR makes a number of small improvements to continuous-test:
* It changes the test series to not pass through 0. This makes it easier to tell if a series is missing or incorrect at timesteps that we would otherwise expect to have a 0 value.
* It initialises most of the test-specific metrics to 0 at startup. This ensures that the `MimirContinuousTestFailed` alert fires for the first failure after continuous-test starts.
* It adds human-friendly timestamps to the diffs included in failure messages.
(none)
> continuous-test improvements

- CHANGELOG.md
- docs/sources/mimir/manage/tools/mimir-continuous-test.md
- pkg/continuoustest/metrics.go
- pkg/continuoustest/write_read_series.go
- pkg/continuoustest/write_read_series_test.go
Add histograms metrics to measure latency of read and write requests.
This will allow us to better appreciate the performances of the underlying mimir cluster/instance
Read request latency metrics have a label to indicate if results cache is in use or not as this could have a huge impact on the performances.
This will allow us to setup SLO on an end-to-end write and read pipeline reflecting the normal behavior of our users.
> feat(continuous-test): Add histograms to measure latency of requests

- docs/sources/mimir/release-notes/v2.13.md
This is a draft PR with release notes. I've based this hugely on the changelog. The wording in the release notes is also largely influenced by the changelog as well.
There are a lot of enhancements and bug fixes in 2.13, so it was difficult to include everything. I tried to focus on user-visible changes, changes that are likely to impact more Mimir installations, or changes related to new features.
I'm open to feedback for mentioning other features or removing some of the ones mentioned.
> 2.13 release notes

- renovate.json
we keep only 2 releases updated
> Remove 2.13 release from renovate config

- CHANGELOG.md
- packaging/nfpm/mimir/mimir.service
Following #8541 this activate the necessary settings to use the sd_notify event.
Fixes #8220
> Type=notify and TimeoutStartSec to wait for ready when starting 

- CHANGELOG.md
- docs/sources/mimir/manage/tools/query-tee.md
- tools/querytee/proxy_endpoint.go
- tools/querytee/proxy_endpoint_test.go
- tools/querytee/proxy_test.go
This PR changes the behaviour of query-tee to always return the response from the preferred backend, if one is configured.
Previously, query-tee would only return the response from the preferred backend if it succeeded, or if all other requests failed and the response from the preferred backend was the first response received. This behaviour was somewhat surprising, and doesn't fit with the scenarios we usually use query-tee for, such as safely comparing a change to the query path.
Now, even if the response from the preferred backend is not successful, it will still be returned.
(none)
> query-tee: always return response from preferred backend if one is configured

- CHANGELOG.md
#8611 was merged and we will include it in a future patch release since it's only with low severity. But adding a changelog entry now so we don't forget later on
> 2.13: add changelog entry for updated dep

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_metrics.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
- Updating the lag metric more frequently
- During partition consumption
- Every 5 mins when consumption is not going on
- Add a metric to track time taken for compaction and upload
- Add logs for compaction and upload
- Made the processPartitionDuration metric to be per partition
- More info in some existing logs
> Updated metrics and logs for blockbuilder

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/config.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
This PR passes static headers to the Grafana email receiver at creation time. These headers come from Grafana.
> Alertmanager: Add static headers to Grafana email receiver

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
This PR updates the `mimir-distributed` Helm chart's default `values.yaml`. It adds the missing necessary container security context for running `continuous-test` under the restricted security policy.
Fixes #8653.
> helm: run continuous-test under restricted policy

- tools/grpcurl-query-ingesters/README.md
- tools/grpcurl-query-ingesters/download-chunks-from-ingesters.sh
- tools/grpcurl-query-ingesters/main.go
This PR fixes a number of small issues with `grpcurl-query-ingesters`:
* it is now possible to run the script from any directory
* the script is marked as executable
* I've fixed the incorrect path to `download-chunks-from-ingesters-query.json`
* I've extracted the output directory to a variable
* I've added @pstibrany's improvement to examine all responses in the given file, rather than just the first one
One thing I have not yet solved is running the script without making the following change to `pkg/ingester/client/ingester.proto`:
```diff
-import "github.com/grafana/mimir/pkg/mimirpb/mimir.proto";
+import "pkg/mimirpb/mimir.proto";
```
Without this change, `grpcurl` complains that it cannot resolve `mimir.proto`. @pracucci, you added this tool in …
> `grpcurl-query-ingesters` improvements

- RELEASE.md
- integration/backward_compatibility.go
> 2.13 release: update backward_compatibility.go

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/snapshotter.go
- pkg/storegateway/indexheader/snapshotter_test.go
- pkg/util/test/leak.go
This is the second PR for https://github.com/grafana/mimir/issues/8389. 
The changes here are:
1. `indexheader.Snapshotter` is now a `services.Service` with a simple timing loop
2. The BuketStore stops the snapshotter whenever it's shutting down
3. Make the interval of Snapshotter a hidden configuration flag for easier testing
> store-gateway: Make Snapshotter a service

- CHANGELOG.md
- integration/querier_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/querier/error_translate_queryable.go
Extend the "error translate" `Queryable` implementation to translate errors returned by any part of the `Queryable` type hierarchy. This ensures that all errors returned by queriers are API errors.
Fixes #8139
> Ensure read path errors use correct HTTP status codes

- pkg/blockbuilder/blockbuilder.go
This one is a follow-up to #8652
The changes here are the following:
- fix the KV pairs in the "done consuming partition" logs
- make sure we update the partition lag metric, when there is no lag
- rename internal variables to be more consistent
> blockbuilder: fix logging and metrics

- pkg/storegateway/indexcache/inmemory.go
- pkg/util/yolo.go
`strings.Clone` was added in [Go 1.18](https://go.dev/doc/go1.18)
`unsafe.Slice` and `unsafe.StringData` were added in [Go 1.20](https://go.dev/doc/go1.20)
> Use recent Go additions to reduce unsafety

- pkg/distributor/distributor_test.go
- pkg/querier/querier_test.go
- pkg/querier/tenantfederation/merge_queryable_test.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/series_refs_test.go
Under `-tags dedupelabels` there are hidden fields which don't compare equal.
~In some cases we can call `labels.Equal`, and in others~ can use `cmp.Equal` via a helper function in Prometheus.
> tests: work round assert.Equals not working on Labels any more

- docs/sources/mimir/manage/secure/securing-communications-with-tls.md
Mention that TLS configuration for Memcached exists and can be configured the same way as other clients.
N/A
> docs: update TLS documentation to mention Memcached

- pkg/scheduler/queue/queue.go
This was added for a time to evaluate the metrics we are considering using for query-scheduler load balancing between query components.
The metrics' accuracy have been validated, and while we will likely keep the metric exporting, we may not end up even using it for the load balancing.
> remove experimental logging overutilized query components

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/bucket_test.go
- pkg/storegateway/gateway.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/lazy_binary_reader_test.go
- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
- pkg/storegateway/indexheader/snapshotter.go
- pkg/storegateway/indexheader/snapshotter_test.go
This is the third PR for https://github.com/grafana/mimir/issues/8389
This PR does one major change: Move eager loading from `ReaderPool` to `BucketStore`. 
The problem with keeping eager loading in the `ReaderPool` is that it needs to have the list of previously loaded blocks injected. This is hard if we want to move the snapshotter and index reader pool to being services.
The PR also slightly changes the `Snapshotter` to receive its dependency (`BlocksLoader` which has the list of currently loaded blocks) via the constructor as opposed to via each snapshot iteration. This is now possible because there is no circular dependency between the `Snapshotter` and the `ReaderPool` (the snapshotter needed to pool to know what's loaded; the pool needed the snapshotter to know what to eager load). …
> store-gateway: Move eager loading to BucketStore

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts-utils.libsonnet
- operations/mimir-mixin/alerts/alerts.libsonnet
- operations/mimir-mixin/config.libsonnet
`MimirRingMembersMismatch` is firing during the migration to experimental ingest storage because it computes the expected number of members looking at all `ingester.*`, including `ingester-zone-[abc]-partition`. The `ingester-zone-[abc]-partition` are temporarily ingesters that join a different hash ring (same name, but different KV store prefix) and they shouldn't be counted towards the expected one.
In this PR I exclude the temporarily `ingester-zone-[abc]-partition` from the alert. I've back tested this alert and I wouldn't have fired last week during our 1st migration.
N/A
> Do not fire MimirRingMembersMismatch during the migration to experimental ingest storage

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/ruler.libsonnet
Add panels to show writes to experimental ingest storage backend in the "Mimir / Ruler" dashboard. The changes are visibile only when `_config.show_ingest_storage_panels` is set to `true` (default is `false`).
Previews:
N/A
> Add panels to show writes to experimental ingest storage backend in the "Mimir / Ruler" dashboard

- CHANGELOG.md
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/mimir/runtime_config.go
The setting has been moved to default and per-tenant `limits` since Mimir 2.12. The command line flag for the setting is not changing.
Related https://github.com/grafana/mimir/issues/6712
Related https://github.com/grafana/mimir/pull/6714
> Remove deprecated query-frontend align_queries_with_step YAML setting

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR adds support for comparing native histograms in query results to query-tee.
Previously, any native histograms in query results were ignored.
I've also taken this opportunity to clarify some of the error messages generated when results do not match, and to replace the use of `errors.Wrap` with `fmt.Errorf` in `response_comparator.go`.
(none)
> query-tee: add support for comparing native histograms in results

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR fixes an issue where query-tee considers two responses to be different if they have different numbers of series, but all of the samples are within the recent sample window and so would be ignored during comparison.
For example, imagine it is now T=10, and the recent sample window is 2. Backend A returns a vector with 11 series, all with samples at T=10, and backend B returns 12 series, all with samples at T=10. (This can happen if the two queries are racing with writes for the queried data.) 
Without this change, query-tee would consider the comparison failed, but if both responses had the same number of series, it would consider the comparison successful regardless of the sample values.
With this change, query-tee will consider both responses as equivalent.
(none)
- [n/a] …
> query-tee: ignore series count mismatches if all samples are within recent sample window

- .github/workflows/test-docs.yml
- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-grafana-enterprise-metrics.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
- docs/variables.mk
- operations/helm/charts/mimir-distributed/RELEASE.md
Use the latest writer's toolkit recommended link syntax in the helm chart docs: https://grafana.com/docs/writers-toolkit/write/links/#link-to-grafanacom-pages
Replaces the special parameter MIMIR_DOCS_VERSION that we introduced for this purpose. The new method cannot verify the links anymore in CI, but there's a daily check in the common docs repo that does that - which also includes the enterprise docs as well!
Fixes: #8744
> Use latest writers toolkit link conventions

- CHANGELOG.md
- cmd/mimir/main.go
- cmd/mimir/main_test.go
To support GoogleCloud Service account keys injected via env variables, the system has to manage multilines strings. Because YAML parsing is complicated, this PR assumes the multilines env variables can be flatten (removing `\n`) before injection. This is applied ONLY to multilines variables, so it won't break compatibility with already existing expanded variables.
Fixes #8704
> feat(config): multiline strings env variable are flatten during expansion

- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
mixin: add perInstanceLatencyPanelNativeHistogram util read/write panels
Related to : #8752 
> mixin: add perInstanceLatencyPanelNativeHistogram util read/write panels

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-writes.json
- operations/mimir-mixin-compiled/dashboards/mimir-writes.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
- operations/mimir-mixin/jsonnetfile.lock.json
Allow using  cortex_request_duration_seconds native histogram in
overview dashboard everywhere.
> Write dashboard: allow using cortex_request_duration_seconds native histogram

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
- operations/mimir-mixin/jsonnetfile.lock.json
- pkg/storegateway/storegatewaypb/gateway.proto
Enable switching between showing results from cortex_request_duration_seconds classic and native metric.
Related to #7154 
Depends on https://github.com/grafana/jsonnet-libs/pull/1285
> mixin: add native cortex_request_duration_seconds in Reads dashboard

- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
One liner fix for a critical bug. Because of use of a loop iterating variable in a goroutine, we were uploading the blocks to the wrong directory. This PR captures the loop variable before using it in the goroutine.
Added a unit test to test this part.
cc @narqo
> BlockBuilder: Ship blocks to the right tenant directories

- docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
As part of https://github.com/grafana/mimir/pull/8489, we [removed instructions for generating test metrics in Mimir](https://github.com/grafana/mimir/pull/8489/files#r1674528190). The thinking was that this functionality used the deprecated Agent Operator and that Mimir would eventually start generating metrics for itself anyways.
@krajorama  brought to my attention that it's actually only GEM that can self-generate test metrics, not Mimir. Now, until the [Helm chart is updated to use Alloy](https://github.com/grafana/mimir/issues/5860), there is no way to get test metrics in Mimir.
This PR replaces the instructions for generating test metrics with the additional caveat that Agent is deprecated and will EOL Nov. 1 2025. 
When the Helm chart is updated, we will update these docs again to …
> docs: re-adds instructions for generating test metrics

- development/mimir-ingest-storage/dev.dockerfile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
Currently debug does not work with our local development environments since our [toolchain uses](https://github.com/grafana/mimir/blob/main/go.mod#L5) a version of Go not supported by the delve we use:
```sh
Version of Delve is too old for Go version 1.22.5 (maximum supported version 1.21, suppress this error with --check-go-version=false)
```
This PR updates our delve.
> Upgrade delve to 1.22 in development environments

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin-compiled/dashboards/mimir-rollout-progress.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/rollout-progress.libsonnet
- operations/mimir-mixin/jsonnetfile.lock.json
Allow using  cortex_request_duration_seconds native histogram in
overview dashboard everywhere.
Related to #7154 
Depends on https://github.com/grafana/jsonnet-libs/pull/1285
> Rollout progress  dashboard: allow using cortex_request_duration_seconds native histogram

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/overview.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR is just a small refactoring of the code already used in the "Overview" in "Writes" dashboards. It removes remaining hardcoded occurrences of `cortex_request_duration_seconds` and `/distributor.Distributor/Push|/httpgrpc.*` from those dashboards.
> mixin: remove reduncancies in distributor route regex

- CHANGELOG.md
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/compactor.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
At Grafana Labs we're experimenting with compactor autoscaling. If successful, we'll upstream the support to OSS jsonnet and Helm. Until then, I would like to add compactor autoscaling panels in the "Mimir / Compactor" dashboard. Since it's disabled by default, there are no changes to compiled dashboard.
**Preview**:
N/A
> Dashboards: add compactor autoscaling panels

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/compactor.libsonnet
Alerting if there is any increase in the new metric `cortex_compactor_disk_out_of_space_errors_total` which has been added by https://github.com/grafana/mimir/pull/8237/ .
A Compactor running out of disk space is a non-transient condition which will likely keep failing until an operator resolves it, so it makes sense to alert on a single increase already.
> alert if compactor runs out of disk space

- pkg/scheduler/queue/queue.go
We've found internally that calling `ItemCount` is slow when there are many tenants and the queue is long. This is not necessary, so let's remove it to prevent a situation where the queue can't keep up.
> [r298] Remove `ItemCount` call from trySendNextRequestForQuerier

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/ruler.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR is a follow up of the work done in https://github.com/grafana/mimir/pull/8703, https://github.com/grafana/mimir/pull/8738, https://github.com/grafana/mimir/pull/8708.
In this PR:
- Added `MimirKafkaClientBufferedProduceBytesTooHigh` alert
- Added "Kafka produced records / sec" panel to "Mimir / Writes" dashboard
The panel I've added to Writes dashboard was already existing in the Ruler dashboard (but querying the metrics from ruler instead of distributor). I've moved them to a shared function. The panel is the same, but I've changed title and description to be closer to what the metric tracks.
**Preview of Writes dashboard**:
**Preview of Ruler dashboard**:
> Mixin: added MimirKafkaClientBufferedProduceBytesTooHigh alert and 'Kafka produced records / sec' panel

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin/dashboards/alertmanager.libsonnet
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
Allow using  `cortex_request_duration_seconds` native histogram in the Alertmanager dashboard.
> Alertmanager dashboard: allow using cortex_request_duration_seconds native histogram

- CHANGELOG.md
- docs/sources/mimir/configure/about-versioning.md
- pkg/mimirtool/commands/rules.go
preparing for the 2.14 release
> mimirtool: remove deprecated `--rule-files` flag

- pkg/storegateway/bucket_e2e_test.go
Lazy-loaded blocks would be loaded into memory after every restart as long as they have been loaded to memory at least once before.
This was a bug in r296 and earlier (probably dating [back to November 2023](https://github.com/grafana/mimir/commit/939f522c05bc72a81c4a04b539bd933884c7f59d) and r251) but fixed in r297 by https://github.com/grafana/mimir/commit/3e68842a093c3f931ad33e92d763693fd620a772 by setting the usedAt to 0 when we unload an index header. As a result the index header isn't included in snapshots https://github.com/grafana/mimir/blob/f89d319a774c0914537f91c56e93d73d9f873304/pkg/storegateway/indexheader/reader_pool.go#L184
This PR adds a test case for it
> store-gateway: add test for persisting unloaded blocks

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
Allow using  `cortex_request_duration_seconds` native histogram in the Remote ruler reads dashboard.
> Remote ruler reads dashboard: allow using cortex_request_duration_seconds native histogram

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
This is another preliminary to ease the review of https://github.com/grafana/mimir/pull/8808. In this PR I'm generalising the list of HTTP headers propagated by `PrometheusCodec.EncodeMetricsQueryRequest()`.
N/A
> Simplify HTTP headers propagation in PrometheusCodec.EncodeMetricsQueryRequest()

- CHANGELOG.md
- pkg/continuoustest/write_read_series.go
This PR adds additional logging to continuous-test: it will now log when a test run succeeds, not just when it fails.
This is useful when debugging failures, as it makes it easier to see if a test is consistently failing or not, and also provides information like trace IDs for successful runs.
(none)
> continuous-test: log when a test succeeds, not just when it fails

- CHANGELOG.md
- tools/grpcurl-query-ingesters/main.go
This PR adds counter hint reset to the data printed by `grpcurl-query-ingesters`.
> grpcurl-query-ingesters: print counter reset information for native histograms

- CHANGELOG.md
- tools/query-bucket-index/README.md
- tools/query-bucket-index/main.go
This PR adds a tool, `query-bucket-index`, that displays the blocks that would be used from a given bucket index for a given query time range.
The output is provided in CSV format.
Sample output:
```
$ go run . -bucket-index bucket-index.json.gz -start 2024-07-24T12:00:00Z -end 2024-07-24T13:00:00Z
Block ID,Min time,Max time,Uploaded at,Shard ID,Source,Compaction level,Deletion marker present?,Deletion time
01J3JW2VVE4HYNAQ5RGRAK54N9,2024-07-24T12:00:00Z,2024-07-24T14:00:00Z,2024-07-24T17:23:12Z,3_of_4,compactor,4,true,2024-07-25T01:41:46Z
01J3JWBDSEJ4K9MABF569E2E3Z,2024-07-24T12:00:00Z,2024-07-24T14:00:00Z,2024-07-24T17:27:40Z,4_of_4,compactor,4,false,
01J3JWMA3FGGB5253479FBCKYB,2024-07-24T12:00:00Z,2024-07-24T14:00:00Z,2024-07-24T17:31:40Z,2_of_4,compactor,4,true,2024-07-25T01:36:18Z …
```
> Add tool for querying a bucket index

- CHANGELOG.md
- pkg/querier/batch/batch.go
- pkg/querier/batch/batch_test.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/batch/merge.go
- pkg/querier/batch/merge_test.go
- pkg/querier/batch/non_overlapping_test.go
- pkg/querier/block.go
- pkg/querier/block_streaming.go
- pkg/querier/block_test.go
- pkg/querier/distributor_queryable_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/querier/partitioner.go
- pkg/storage/chunk/prometheus_chunk.go
- pkg/storegateway/storepb/custom.go
This PR fixes an issue where overlapping chunks for a single series from a single store-gateway can result in samples that exist in only some chunks being dropped from query results.
Fixes the issue in https://github.com/grafana/mimir/pull/8799
> Merge overlapping chunks for a single series from a single store-gateway

- pkg/storegateway/bucket.go
- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
- pkg/util/test/leak.go
This is the fourth PR for https://github.com/grafana/mimir/issues/8389
Makes `ReaderPool` a `service.Service`. Its lifecycle is controlled by the `BucketStore`. The `BucketStore` will stop the `ReaderPool` whenever it is shutting down. This prevents leaking goroutines.
related to https://github.com/grafana/mimir/issues/8389
> store-gateway: Make index reader pool a service

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/config.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
This PR enables Mimir to use a Grafana state if a Grafana configuration is being used to update the Alertmanager.
If a user is about to use a Grafana configuration in their Alertmanager, we check the database for Grafana state. We then use those entries to update the Alertmanager's notification log and silences.
After successfully merging states, we delete the Grafana state to avoid re-applying it. If we don't find Grafana state for a user, that (usually) means that we've already merged and deleted it, and the Alertmanager restarted, making its internal `promoted` flag equal to `false`.
To test this PR it's necessary to enable the Grafana Alertmanager compatibility (take the config in [this PoC](https://github.com/grafana/mimir/pull/8637/files) as a model) and a Grafana instance running …
> Alertmanager: Promote Grafana state

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
Even with LookbackOnNoCommit the first cycle would still consume records from far in the past. With this change, we will now discard records that are before LookbackOnNoCommit, hence make this config actually do what it was meant to do.
> BlockBuilder: Make the LookbackOnNoCommit actually effective

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- pkg/frontend/querymiddleware/read_consistency.go
- pkg/frontend/querymiddleware/read_consistency_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
This PR is a follow up of #8808. In this PR:
- [Renamed MimirIngesterFailsEnforceStrongConsistencyOnReadPath alert to MimirStrongConsistencyEnforcementFailed, and improved its runbook](https://github.com/grafana/mimir/commit/c02698a81c8cc775c5a3779e176b911c700cd8c3). Why? Because after https://github.com/grafana/mimir/pull/8808 this alert can also fire due to errors in query-frontend (now responsible to fetch offsets).
- [Added MimirStrongConsistencyOffsetNotPropagatedToIngesters](https://github.com/grafana/mimir/commit/d08aedec30faa68e19f29c4d0f32974531f37ec6) alert. Why? Because Mimir is a complex system and we may undetect if we stop propagating offsets from query-frontend to ingesters just relying on unit / integration tests. I feel more comfortable if we have an alert on it. It's a …
> Alerts: add MimirStrongConsistencyOffsetNotPropagatedToIngesters

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
This PR is a follow up of #8808. In this PR I'm adding panels to display metrics about strong read consistency enforcement in the query-frontend. We already have the same panels for ingesters, but since part of the enforcement is done in the query-frontend I'm adding them for it too.
**New panels** (query-frontend):
**Already existing panels** (ingester):
N/A
> Dashboards: add strong consistency panels for query-frontend in 'Mimir / Queries' dashboard

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/errors_test.go
- pkg/distributor/otel.go
- pkg/distributor/push.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
In #8699 we got rid of the `-ingester.return-only-grpc-codes` CLI option. This PR removes the legacy code that was present only because of the removed CLI flag.
Part of https://github.com/grafana/mimir/issues/6008 (migration plan)
> Removing legacy coded related to -ingester.return-only-grpc-errors

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir/ingest-storage-migration.libsonnet
- operations/mimir/ingest-storage.libsonnet
After https://github.com/grafana/mimir/pull/8808 we need to configure ingest storage (specifically Kafka and `-ingest-storage.kafka.last-produced-offset-poll-interval`) on query-frontend too. Ingest storage was already configured, but there are a couple of things that were missing and I'm fixing in this PR:
1. Set `-ingest-storage.kafka.last-produced-offset-poll-interval` like we do in ingesters
2. Configure ingest storage in query-frontend during a migration, when `ingest_storage_migration_querier_enabled` is `true`
N/A
> Jsonnet: configure experimental ingest storage on query-frontend too when enabled

- CHANGELOG.md
- pkg/ingester/circuitbreaker.go
- pkg/ingester/circuitbreaker_test.go
Before this PR, relevant errors for opening ingester server-side circuit breakers were per-instance limit errors and (push and read) requests that exceed the maximum configurable duration. This PR removes the per-instance limits errors from the condition, because these errors are already treated by grpc limiters implemented on ingesters' write path.
> Ingester circuit breakers open of timeouts only

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/mimir/_index.md
Otherwise defaults to current mimir or helm chart version, see https://grafana.com/docs/writers-toolkit/write/shortcodes/#about-version-substitution
> docs: define ALLOY_VERSION

- integration/ruler_test.go
Adds an end to ends test to ensure rule concurrency is working correctly. A follow up to https://github.com/grafana/mimir/pull/8146
N/A
> End to end test rule concurrency

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/helm/charts/mimir-distributed/values.yaml
Allow setting namespace name for Grafana dashboard config maps.
> Add support for setting namespace for dashboard config maps

- pkg/storegateway/bucket.go
There's no need for this verbose span that is almost always just a few microseconds log. We can just log on the parent span how much time we spent waiting.
I was also tempted to avoid logging at all if it was <1ms wait, but finally preferred to be consistent.
> Chore: replace store_query_gate_ismyturn span with a log

- CHANGELOG.md
- pkg/frontend/querymiddleware/shard_active_series_test.go
- pkg/frontend/querymiddleware/shard_by_series_base.go
Response shards for responses to the `/active_series` endpoint need to be accumulated in the querier to deduplicate series from ingesters, and there's a limit for the response shard size to protect queriers from OOMs. If this limit is exceeded, the query-frontend currently responds with a `400 (Bad Request)` status code. This PR makes it respond with `413 (Request Entity Too Large)` instead.
Clients can use this status code to detect the condition and resubmit the request with an increased shard size.
n/a
> Query-frontend: Return `413` if active series response is too large

- development/README.md
- development/mimir-monolithic-mode/config/config.alloy
- development/mimir-monolithic-mode/docker-compose.yml
Prepare to update https://grafana.com/docs/mimir/next/send/native-histograms/ .
Also fix deprecated use of enable_protobuf_negotiation = true scrape option.
Related to #8814 
Related to https://github.com/grafana/mimir-squad/issues/1334
> development mode: use alloy instead of agent for flow mode

- docs/sources/mimir/send/native-histograms/_index.md
Fix wrong flag:
```
$ ./prometheus --enabled-feature native-histograms
Error parsing command line arguments: unknown long flag '--enabled-feature'
prometheus: error: unknown long flag '--enabled-feature'
```
Related to https://github.com/grafana/mimir/issues/8814
Related to https://github.com/grafana/mimir-squad/issues/1334
> docs: fix prometheus feature flag flag

- pkg/alertmanager/config.go
- pkg/alertmanager/config_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
This PR updates the `computeConfig()` method to use the Alertmanager's default global configuration even if the current config is empty. This allows the Alertmanager to use the default SMTP configuration in the email sender.
> Alertmanager: Use default Mimir globals in Grafana configuration

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-hashicorp-vault-agent.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-cortex.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configuration-with-helm.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/monitor-system-health.md
You can use \`ref\` URIs in admonitions (or any shortcodes) because they are inline and not subject to the issues noted in the [\`admonition\` shortcode](https://grafana.com/docs/writers-toolkit/write/shortcodes/#code-shortcode:~:text=to%20core%20understanding.-,WARNING,For%20more%20information%2C%20refer%20to%20Markdown%20Reference%20Links%20in%20Shortcodes.,-Examples).
The \`ref\` URIs perform the same pattern matching as \`docs/reference\` but don't require the use of reference-style links and the destinations are ordinary (full) URLs that can include version substitution. Unlike \`docs/reference\`, the implementation doesn't use \`relref\` so you don't have to be careful with omitting trailing slashes and the links will follow redirects.
Documentation: …
> [mimir-distributed-release-5.1] Replace docs/reference shortcode with ref URIs

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11.jsonnet
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6.jsonnet
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir/ingest-storage-migration.libsonnet
We recently migrated a Mimir cluster to the new experimental ingest storage architecture and we noticed a couple of things to improve in the jsonnet-coded migration process:
- [change 'grafana.com/min-time-between-zones-downscale' value from '0s' to '0' to keep it consistent with the setting used when ingest storage ingesters autoscaling is enabled](https://github.com/grafana/mimir/commit/566f3d4704f34b1d625c41054c6f706b25c57b17) 
- [keep ingest_storage_migration_classic_ingesters_no_scale_down_delay:false until ingesters autoscaling is enabled](https://github.com/grafana/mimir/commit/97d132ca625d05d3aee5c591fe1eee4f2022578c) 
N/A
> Jsonnet: Improve min-time-between-zones-downscale setting during ingest storage migration

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-migration-step-10.jsonnet
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final.jsonnet
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
In this PR I'm changing the min/max ingester replicas setting to be per-zone when ingest storage is enabled. It makes it easier to reason, given in the ingest storage zones can be added and removed.
N/A
> Jsonnet: change min/max ingester replicas setting to per-zone when ingest storage is enabled

- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/util/globalerror/grpc_test.go
This PR is a simple no-op refactoring that renames `querier.shouldStopQueryFunc()` into `querier.shouldRetry()`.
The main reason for that is to make the code more intuitive.
More precisely, these usages:
```
err := ...
if shouldStopQueryFunc(err) {
return err
}
// log the positive outcome 
return nil
```
have been replaced with these usages:
```
err := ...
if shouldRetry(err) {
// log the positive outcome
return nil
}
return err
```
> Querier: rename shouldStopQueryFunc into shouldRetry

- CHANGELOG.md
- pkg/util/globalerror/grpc.go
- pkg/util/globalerror/grpc_test.go
This PR gets rid of usages of the deprecated `grpc.ErrClientConnClosing` error introduced in #8865.
Related to #8815
> globalerror: get rid of deprecated gprc.ErrClientConnClosing

- integration/ruler_test.go
- pkg/ruler/ruler_test.go
This removes assertions made during an integration test that validated configuration and instead tests this functionality in a unit test. This is faster and more reliable than starting a docker container to validate configuration.
N/A
> Move ruler configuration validation to unit test

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
#8749 fixed an issue where query-tee would consider two responses to be different if they contained a different number of series and all samples were within the recent sample window.
However, it did not consider the similar case where the number of series is the same, but the series are different. This PR fixes that issue.
(none)
> query-tee: don't fail response comparison if backends return different sets of series within recent sample window

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/indexheader/header.go
- pkg/storegateway/indexheader/lazy_binary_reader.go
- pkg/storegateway/indexheader/lazy_binary_reader_test.go
- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
- pkg/util/test/leak.go
This is the fifth and final PR for https://github.com/grafana/mimir/issues/8389. The base branch is that of https://github.com/grafana/mimir/pull/8603 and the idea is that we merge this PR after https://github.com/grafana/mimir/pull/8603.
This is a small PR, but I decided to not combine it with https://github.com/grafana/mimir/pull/8603 as in theory does more than refactor. See below.
Properly closes `LazyBinaryReader` and cleans up the control loop goroutine.
As part of that I realized that `LazyBinaryReader`'s `Close` claims that calling `Close` and later using the reader again is valid. However, the other implementation of `indexheader.Reader` - `StreamBinaryReader` does not satisfy the same contract - calling `Close` makes `StreamBinaryReader` unusable. Moreover, there is no code …
> store-gateway: properly close LazyBinaryReader on shutdown

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/mimir/mimir.go
These changes are the follow-up to #8823
Instead of configuring the number of instances and kafka partitions, as long as asking for a `POD_NAME` env, here we add two new flags
- `-block-builder.instance-id`, which defaults to the hostname;
- `-block-builder.kafka.partition-assignment`, which must be a mapping from the instance-id to a static list of partitions, assigned to the instance.
Example of usage (with docker-compose):
```yaml
mimir-block-builder-0:
command:
- /mimir
- -block-builder.instance-id=instance-0
- -block-builder.kafka.partition-assignment={"0":[0,1,2]}
mimir-block-builder-1:
hostname: mimir-block-builder-1
command:
- /mimir
- -block-builder.kafka.partition-assignment={"1":[3,4,5]}
```
When using in Kubernetes, we will generate the full assignment via jsonnet, and pass …
> blockbuilder: pass partition assignment via flag

- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/docker-compose.yml
- development/mimir-read-write-mode/docker-compose.jsonnet
- development/mimir-read-write-mode/docker-compose.yml
Remove version field from development/*/docker-compose.yml files, as it's [deprecated](https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313).
Currently the following type of warning is produced:
```console
WARN[0000] /Users/arve/Projects/grafana/mimir/development/mimir-monolithic-mode/docker-compose.yml: `version` is obsolete
```
> development: Remove version field from docker-compose.yml

- go.mod
- go.sum
- vendor/github.com/twmb/franz-go/pkg/kadm/acls.go
- vendor/github.com/twmb/franz-go/pkg/kadm/configs.go
- vendor/github.com/twmb/franz-go/pkg/kadm/misc.go
- vendor/github.com/twmb/franz-go/pkg/kadm/partas.go
- vendor/github.com/twmb/franz-go/pkg/kadm/topics.go
- vendor/github.com/twmb/franz-go/pkg/kadm/txn.go
- vendor/modules.txt
The PR https://github.com/twmb/franz-go/pull/775 has been merged and included in kadm v1.13.0. We can remove the import override and vendor kadm from upstream again.
N/A
> Vendor kadm from upstream

- pkg/streamingpromql/benchmarks/ingester.go
This PR reduces the time taken to load data into a test ingester during the MQE benchmarks.
It does this by reusing the same slices for spans and deltas for all samples, rather than allocating a new one for each sample.
(none)
> Mimir query engine: improve benchmark setup time by ~10% by reusing slices for histograms

- pkg/streamingpromql/benchmarks/comparison_test.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions/common.go
- pkg/streamingpromql/functions/rate.go
- pkg/streamingpromql/operators/function_over_instant_vector.go
- pkg/streamingpromql/operators/function_over_instant_vector_test.go
- pkg/streamingpromql/operators/function_over_range_vector.go
- pkg/streamingpromql/operators/metric_names.go
- pkg/streamingpromql/testdata/upstream/native_histograms.test
This PR builds on #8660, adding annotations for the following cases for `rate`:
* `rate` is called over a range with both floats and histograms
* `rate` is called over a series containing floats with a metric name that does not look like a counter
* `rate` is called over a range with gauge-type histograms
Performance is generally on par or better than `main`, with the exception of `rate` over native histograms which has regressed somewhat due to all the extra checks:
<details>
<summary>Benchmark results</summary>
```
goos: darwin
goarch: arm64
│   main.txt   │  step-3-without-lastatorbefore.txt  │
│    sec/op    │    sec/op     vs base               │
Query/rate(a_1[1m]),_instant_query/Mimir-10 …
```
> Mimir query engine: add support for some annotations emitted by `rate()`

- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
These PR updates the ingest storage's `PartitionReader` to shut down gracefully. That is, when its service enters the stopping phase, `PartitionReader` shouldn't try to interrupt the processing of the in-flight fetches batch. Also, it shouldn't commit if the processing didn't succeed and was cancelled due to stopping.
> ingest: make PartitionReader wait for in-flight fetches when it's stopping

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
We've noticed a corner case that is currently failing in `querytee`. The comparison should not fail, when 
1. "expected" and "actual" series has a different number of samples AND
2. the difference is within the `SkipRecentSamples` duration
> querytee: update compareMatrix to handle difference in series with recent samples

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
This one adds more logging to block-builder to help us to debug the lagging in the consumption.
jfi @codesome
> blockbuilder: more logging

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
This address two TODOs 
* handle errors when closing the consumer to make sure we've handled all errors from ingestion
* here we create a new consumer and retry the whole ingestion on each retry; the reason for that is that currently we can't use a consumer after closing it.
* This also changes how we record `cortex_ingest_storage_reader_records_batch_process_duration_seconds` - now it includes retries. IMO this is more informative because you'd see an increase in processing time as you start retrying to process; plus this currently isn't used in any alerts or dashboards, so changing semantics is ok
* remove redundant interfaces and add `Close(context.Context) error` to `recordConsumer`
> kafka replay speed: Handle errors from closing the pusherConsumer & simplify interface

- pkg/api/api.go
This one cleans up an outdated piece of code from the earlier prototype. Block-builder doesn't create its own hash-ring (for now). We may revisit that in the future.
> api: clean up outdated chunk from earlier block-builder prototyping

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR adds more information to the error messages produced by query-tee when comparing series from a matrix. 
Specifically, it will now include all samples for a series when a mismatch occurs.
(none)
> query-tee: log all samples for matrix series when a mismatch occurs

- pkg/blockbuilder/blockbuilder.go
This one fixes a corner case, when the block-builder app starts at around the time of the `nextCycle`. 
Right now the calculation causes a couple of problems:
1. block-builder delays its first cycle (after the startup cycle) by one hour causing the app to lag
1. because we add a `-1 second`, to the `cycleEnd`, the cycles splitting in `partition is lagging behind` skips the last hour, causing it to keep lagging.
I didn't manage to add any tests 'cause the logic in `running` is, currently, bound to wall-clock (`time.Now`). I suggest we reconsider it to be more tests friendly after we get the confidence that the current version works.
> blockbuilder: fix calculation of the next cycle time

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/tenants.libsonnet
Adds a "Out-of-order samples appended" panel to "Mimir / Tenants" dashboard.
> Mimir / Tenants dashboard: add "Out-of-order samples appended"

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
Yesterday I spent few hours investigating high end-to-end latency in a dev cell and it took me a while to figure out that the high reported latency was actually caused by 1 outlier ingester. In this PR I propose to add a panel to show outliers. It's not perfect, but it gives an hint. I also tried to compute outliers using a more complex approach (using stddev and z-score but I couldn't get better results, so I'm proposing the simple approach).
N/A
> Dashboards: add Kafka end-to-end latency outliers panel in the "Mimir / Writes" dashboard

- pkg/frontend/querymiddleware/astmapper/astmapper_test.go
- pkg/frontend/querymiddleware/astmapper/embedded.go
- pkg/frontend/querymiddleware/astmapper/instant_splitting.go
- pkg/frontend/querymiddleware/astmapper/sharding.go
- pkg/frontend/querymiddleware/astmapper/sharding_test.go
- pkg/frontend/querymiddleware/astmapper/subtree_folder.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/storage/sharding/label.go
Generalises astmapper's shardSummer, and make some functions public to allow reuse outside of query sharding
N/A
None as these are minor, non-user-facing changes.
> Generalise and make some functions of astmapper public

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- tools/kafka-dump/main.go
This small refactor cleans up a bit the code within pusherConsumer to address some dependency inversion of some of the components.
Some of the things I've done are:
- Move functions around to comply with Go code's standards e.g. Functions that are part of the public interface go after the struct definition
- Avoid passing individual metrics around and instead have a single metrics struct that is passed around to the different structs
- Simplify the `consumerFactory` definition  to push the construction of the `pusherCloser` to itself.
There are other things I want to do such as: Remove the "multitenant pusher" abstraction but I think this is a enough for a first PR.
NB: This does not the change the behaviour of the code at all.
N/A
> Code cleanup for `pusherConsumer`

- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/mimirpb/timeseries.go
- pkg/util/validation/limits_mock.go
Skipping the unmarshaling of exemplars if a user has exemplars disabled.
In our production environments we have seen users for whom the ingestion of exemplars is disabled, but in their write requests they are still sending very large amounts of exemplars, without this change we're decoding all the exemplars only to then drop them.
The line number looks larger than the PR really is, most of the lines are copy-pasted from protobuf generated files. I did not like having to copy-paste generated code, but I figured it's acceptable because we're already doing the same thing with the `.Unmarshal()` method of the type `LabelAdapter` [here](https://github.com/grafana/mimir/blob/7153e1874384efd56f710412ec0061f9abd6c4e8/pkg/mimirpb/timeseries.go#L620). Also, the only alternative that I have found to …
> Skip unmarshaling of exemplars when exemplars are disabled

- tools/doc-generator/main.go
- tools/doc-generator/parse/parser.go
- tools/doc-generator/write/writer.go
- tools/doc-generator/write/writer_test.go
- tools/doc-generator/writer.go
This PR fixes two issues in `tools/doc-generator`:
* config options that have `nocli` set do not have their default values included in the generated text
* config options that take slices do not include details of the slice elements in the generated text
It also exports the Markdown generation code so that it can be used in other repositories (eg. our enterprise product).
(none)
> doc-generator: include default values for config options decorated with `nocli`, fix formatting of slices, and export Markdown generation package

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/storage/bucket/client_test.go
- pkg/storage/bucket/s3/bucket_client.go
- pkg/storage/bucket/s3/config.go
- pkg/storage/bucket/s3/config_test.go
This PR exposes a new `s3.session-token` configuration option to enable using temporary security credentials.
Fixes #8832
> Add session_token to s3 config

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/backward_compatibility.go
- integration/e2emimir/services.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
The temporarily config option `-query-frontend.remote-read-limits-enabled` was introduced in https://github.com/grafana/mimir/pull/8375 while building remote read limits enforcement in the query-frontend. At Grafana Labs we've enabled it in all prod envs and now we fell comfortable to remove the config option and always enforce limits on remote read requests too.
Not updating the CHANGELOG because `-query-frontend.remote-read-limits-enabled` was never mentioned in the CHANGELOG.
N/A
> Remove temporarily config option -query-frontend.remote-read-limits-enabled

- pkg/storage/ingest/reader.go
Improve maxBytes estimations - now we make sure to not overflow int32 (it happened during testing) and generally keep the logic closer together in `fetchWant`.
> kafka replay speed: Improve fetch request size byte estimations

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/continuous_test/continuous-test-dep.yaml
- operations/helm/charts/mimir-distributed/values.yaml
allows setting a read and write URLs for continous-test, i recently deployed it in my org and since we dont use the gateway i had to hack it with extraArgs
> add read write values to continous-test

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer_test.go
It is based on #8967
1.  It uses concurrent fetchers in tests. This adds coverage to the concurrent fetchers. Because of that I also found two bugs
* we no longer ignore the first record with offset `0`
* when we reach the end of a partition we back off and try fetching again - currently with exponential backoff of 10ms, up to 1s
The latter actually unblocks using this code for regular fetching too (see 2.)
3. Use concurrent fetchers for regular consuming too. This required changes to handle the case where we're fetching after the last available offset, but the changes were minor. 
* This also unblocks undoing some changes compared to `main`: the changes in `processNextFetches` and in `processNextFetchesUntilTargetOrMaxLagHonored`
* When testing I realized that the metrics in …
> kafka replay speed: use concurrent fetchers for regular fetching too

- CHANGELOG.md
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue.go
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_test.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues.go
- pkg/scheduler/queue/tenant_queues_test.go
- pkg/scheduler/queue/tree_queueing_algorithms.go
This PR introduces the concept of "leaf nodes" to the experimental `MultiQueuingAlgorithmTreeQueue`, and enforces a couple of rules:
* Leaf nodes may only exist at a tree's maximum depth (`len(queuingAlgorithms)` at tree creation)
* Non-leaf nodes may not contain a local queue
* Leaf nodes may not have children (this is already enforced by tree's max-depth)
This lets us efficiently skip memory allocation for non-leaf nodes, saving memory and CPU cycles.
One structural change is required to enable this: previously, if `query-frontend.additional-query-queue-dimensions-enabled` was set and scheduler requests `AdditionalQueueDimensions` ([code](https://github.com/grafana/mimir/blob/035a8c44bfeb8fd376aa01f534b50064a8ceb235/pkg/scheduler/queue/queue.go#L54)) was _empty_, said requests would be …
> Introduce leaf nodes and "unknown" query component

- CHANGELOG.md
- tools/querytee/proxy.go
This PR improves the behaviour of query-tee when it receives a shutdown signal.
Previously, query-tee would immediately terminate all inflight HTTP requests on shutdown.
With this change, query-tee will now wait up to `-server.graceful-shutdown-timeout` before terminating any outstanding requests.
(none)
> query-tee: gracefully stop inflight requests when shutting down

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- pkg/ingester/ingester_test.go
- pkg/storage/ingest/config.go
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- tools/kafka-dump/main.go
This fixes up the tests in the ingest storage package. I needed to make two changes (in two commits) for this
1. include the tenant ID in each unflushed shard. This allows to propagate some valid context when we flush each shard on Close(). Missing tenant ID was failing some tests
2. modify `TestShardingPusher` and `newShardingPusher` so that we can configure the buffer we use for each shard. This allows to trigger blocking in tests and allow draining the errors from a shard
> kafka replay speed: fix sharding writer tests

- pkg/streamingpromql/benchmarks/comparison_test.go
- pkg/streamingpromql/benchmarks/ingester.go
This PR improves the performance of two MQE tests, `TestBothEnginesReturnSameResultsForBenchmarkQueries` and `TestBenchmarkSetup`.
It does this by only flushing the ingester used during these tests once, rather than after loading each batch of data.
On my machine, this cuts ~30s off the time taken to run each of these tests:
* `TestBothEnginesReturnSameResultsForBenchmarkQueries`: was 50.1, now 20.2s
* `TestBenchmarkSetup`: was 36.1s, now 6.0s
This does not have a dramatic effect on the performance of setting up the test data used during benchmarks, as this is dominated by the time taken to ingest the data.
(none)
- [n/a] …
> Mimir query engine: improve performance of `TestBothEnginesReturnSameResultsForBenchmarkQueries` and `TestBenchmarkSetup`

- .errcheck-exclude
- .golangci.yml
This PR fixes the use of two deprecated config options for `golangci-lint`:
```
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats`
WARN [config_reader] The configuration option `linters.errcheck.exclude` is deprecated, please use `linters.errcheck.exclude-functions`.
```
(none)
> Stop using deprecated config options for golangci-lint

- CHANGELOG.md
- docs/sources/mimir/references/http-api/index.md
I propose to clarify that `{namespace}` and `{groupName}` path segments in the ruler config API should be URL-escaped.
N/A
> Docs: clarify namespace groupName escaping in the rule config API path segments

- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
This PR gets rid of the `queryPerSecond()` function and the unused variables that call that function.
> mimir-mixin: get rid of unused functions and variables

- development/mimir-ingest-storage/compose-up.sh
- development/mimir-microservices-mode/compose-up.sh
- development/mimir-read-write-mode/compose-up.sh
In development/*/compose-up.sh files, execute Make in a certain directory instead of with a certain Makefile. This is because parts of Makefile depend on executing in the right directory when issuing e.g. find commands.
Prior to this fix, you'll see an error when executing the following:
```console
$ cd development/mimir-microservices-mode
$ ./compose-up.sh
find: ./pkg/distributor/otlp/: No such file or directory
[...]
```
The reason for the error (`find: ./pkg/distributor/otlp/: No such file or directory`) is the following variable definition in Makefile:
```Makefile
OTLP_GOS := $(shell find ./pkg/distributor/otlp/ -type f -name '*_generated.go' -print)
```
Since executing Make with a certain Makefile (via the `-f` flag) causes Make to execute with a particular Makefile, but in the same …
> development/*/compose-up.sh: Execute Make in root directory

- pkg/frontend/v1/frontend.go
- pkg/frontend/v1/frontend_test.go
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_test.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_querier_assignment.go
- pkg/scheduler/queue/tenant_querier_assignment_test.go
- pkg/scheduler/queue/tenant_queues.go
- pkg/scheduler/queue/tenant_queues_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
This PR introduces the querier-worker integer ID assignment by the `RequestQueue` via its internal querier-connection tracking `tenantQuerierAssignments`.
The goal is to assign querier-worker connections sequential integer IDs to allow modulo operations to distribute the workers across different request queues in the upcoming version of our request queue tree.
"Missing" IDs from previous disconnections will be allocated to the next connecting worker.
**Example:**
At time _t<sub>0</sub>_, workers, all from the same querier, with IDs 0, 1, 2, 3, and 4 (w<sub>0</sub>, ..., w<sub>4</sub>) are connected to the scheduler.
* _t<sub>1</sub>_: w<sub>0</sub> and w<sub>2</sub> disconnect. 
* Connected workers: w<sub>1</sub>, w<sub>3</sub>, w<sub>4</sub>
* _t<sub>2</sub>_: a worker connects to the …
> Query Scheduler: Assign Querier-Worker Connection Integer IDs

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
This is the first round of refactoring before we start implementing the settings to allow block-builder to consume from partition's end, when it catches up.
Here we simplify how the block-builder figures out its start up offsets but reducing the number of `FetchOffsets` calls. That is, on start, the block-builder gets the offsets for all group's partitions, and falls back to `kafkaOffsetStart`, if a group-partition doesn't have an offset (i.e. no commit).
> blockbuilder: reduce number of FetchOffsets calls on start

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
This PR extends alerts `RequestErrors` and `RulerRemoteEvaluationFailing` with their native histogram counterpart.
> Alerts: migrate RequestErrors and RulerRemoteEvaluationFailing to native histograms

- CHANGELOG.md
- pkg/querier/batch/batch.go
- pkg/querier/batch/chunk.go
- pkg/querier/batch/merge.go
- pkg/querier/batch/merge_test.go
mergeIterator.Seek() was skipping samples in some cases. This was happening because in the Seek() method we were discarding the current batch from mergeIterator if the batch's first sample was after the seek time.
> Fix mergeIterator.Seek()

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
~_This one seats atop the #8982 for now_~
These changes update block-builder making it to start consuming from a point, after the `-block-builder.lookback-on-no-commit` time, when there is no commit for a partition. That is, on the first deploy, instead of starting from the partition's earliest offset, the block-builder consume from the nearest offset after the `lookback-on-no-commit` from its start.
Note: in the future, I want to extend the `-block-builder.lookback-on-no-commit` to handle the value of `-1`, as a way to start from the partition's start. This may be useful when a user doesn't want to lose any historical data.
>  blockbuilder: consume from lookback when partition doesn't have commit

- CHANGELOG.md
- operations/mimir/ingest-storage.libsonnet
In this PR I propose a jsonnet refactoring to allow to easily override the Kafka client ID on a per-component basis. The idea is to configure the client ID as key-value pairs, which then gets serialised in a comma-separated string (e.g. `{keyA: 'valueA', keyB: 'valueB'}` gets serialised to `keyA=valueA,keyB=valueB`).
I've introduce config fields to set the Kafka client ID for specific Mimir components (distributor, ingester, query-frontend, ruler). By default, they inherit the default producer or consumer settings, but client ID values can be overriden in the per-component config field. Similarly to CLI args, a `null` value in the override removes that setting from the client ID.
The config fields are suffixed with `_settings`. They work similarly to `_args` ones, but since they're not …
> Jsonnet: allow to easily override Kafka client ID on a per-component basis

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
There's a couple of things going on here:
- Make `Consume` part of the public interface, it's a private struct so having a public method is OK in this package.
- Make the unmarshalling and pushing to storage process a bit easier to understand and document it.
> Refactor `pusherConsumer.Consume`

- pkg/ingester/downscale_test.go
This PR fixes an flaky ring downscale handler test, where instances may take more time than expected to converge on some ring state. 5s matches the time we use elsewhere for polling ring state changes (unfortunately).
https://github.com/grafana/mimir/actions/runs/10445776709/job/28922212642?pr=9039#step:8:72
- n/a `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
> Fix flaky ring downscale handler test

- tools/kafkatool/brokers.go
This makes it easier to work with the tool with local dev environments where the broker addresses are all `localhost`
> kafkatool: print leader port and node ID

- pkg/storegateway/bucket.go
I noticed that logs are now filled with lines like this one
```
ts=2024-08-19T14:44:32.753385487Z caller=spanlogger.go:111 user=10428 caller=log.go:168 level=info msg="waited for turn on query concurrency gate" duration=6.289µs
```
I don't think we need this as an info log.
> store-gateway: make concurrency gate logs debug

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/configs.go
- integration/e2emimir/services.go
- integration/querier_sharding_test.go
- integration/query_scheduler_test.go
- pkg/querier/engine/config.go
- pkg/querier/worker/worker.go
- pkg/querier/worker/worker_test.go
Docstring for constant should be a sufficient description, but will expand a bit here:
When we move to a new RequestQueue dequeuing algorithm, we will modulo querier-worker IDs to distribute them across 4 request queue dimensions, one each for the "expected query component" which is assigned to the query request: ingester, store-gateway, both, or unknown.
Having querier-worker connections < num queue dimensions will result in queue starvation unless not all 4 queue dimensions are active. In any minimally utilized cluster, we expect all 4 dimensions will exist at almost all times.
Because the queriers have no centralized knowledge or coordination of how many queriers exist in the cluster, we must set a minimum of 4 for each querier<->request queue instance connection, where a "request …
> querier: set minimum concurrency to 4 for query-scheduler's new querier-worker queue prioritization

- CHANGELOG.md
- pkg/scheduler/queue/queue.go
Makes the experimental `query-scheduler.prioritize-query-components` flag a no-op temporarily, while https://github.com/grafana/mimir/pull/9013#issuecomment-2303268475 gets merged. I'm not updating the flag docs for this PR because there won't be any releases between now and #9013 getting done.
> Temporarily make prioritize-query-components a no-op

- CHANGELOG.md
- docs/sources/mimir/configure/about-runtime-configuration.md
- go.mod
- go.sum
- vendor/github.com/grafana/dskit/httpgrpc/httpgrpc.go
- vendor/github.com/grafana/dskit/ring/replication_set.go
- vendor/github.com/grafana/dskit/runtimeconfig/manager.go
- vendor/modules.txt
This allows larger runtime configuration files without hitting the Kubernetes ConfigMap size limit.
Implemented in dskit in https://github.com/grafana/dskit/pull/571
Fixes N/A
> Update dskit to support gzip-compressed runtime configs

- go.mod
This reverts commit 86b8d6d41e3157dd6d8b9ad248fa152b33cd00c7.
Revert, as we don't want to require a newer Go toolchain than is in the build image. Also downgrading the toolchain version to v1.22.5 rather than v1.22.6, since the build image has the former.
> Revert "chore(deps): update dependency go to v1.23.0 (#9043)"

- Makefile
- go.mod
- mimir-build-image/Dockerfile
In mimir-build-image/Dockerfile, explicitly override environment variable `GOTOOLCHAIN` to be `local`, to make sure that the Docker image's bundled Go toolchain is used, rather than the one specified via the `toolchain` directive in go.mod. The same is already done in [official Go images](https://github.com/docker-library/golang/issues/472), but being explicit helps also to document.
> mimir-build-image: Explicitly set GOTOOLCHAIN=local

- Makefile
- mimir-build-image/Dockerfile
- pkg/distributor/distributor_ingest_storage_test.go
- pkg/distributor/otel.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/shard_active_native_histogram_metrics_test.go
- pkg/frontend/querymiddleware/shard_active_series_test.go
- pkg/frontend/transport/handler.go
- pkg/scheduler/scheduler.go
- pkg/storegateway/limiter.go
- pkg/util/objtools/bucket.go
- tools/tsdb-index-toc/main.go
Upgrades Go version in mimir-build-image.
This required an upgrade to `golangci-lint`. In turn, the upgrade of this introduced a new linter rule for constant format strings (which in rare cases can be a security thing). Fixed all violations of this new linter rule.
n/a
> mimir-build-image: Upgrade Go version to 1.23.0-bookworm

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
~_This one seats atop the https://github.com/grafana/mimir/pull/8989_~
This is part 3 of the internal's refactoring. Here we improve how `consumePartition` tracks the partition's lag and make the partition's lag, the high watermark of the cycles. I.e. a full cycle now is expected to consume at most `partitionInfo.Lag` records. This brings a couple of benefits:
1. Previously, we didn't take into account that the number of seen records isn't the same as number of processed records. In the case when the consumer catches up, it may incorrectly report lag `-1` in to logs (this didn't hurt but was confusing).
2. This simplifies the consumer loop, because we no longer need to care about occasional empty fetches. The consumer will retry fetching until the "initial_lag" records got consumed.
3. …
>  blockbuilder: consume partition up to its lag

- pkg/storegateway/bucket.go
- pkg/storegateway/gateway.go
This PR fixes a bug which resulted in a flaky test. 
BucketStores would get shut down immediately when we receive SIGTERM instead of waiting for ongoing bucket syncs to finish first. This sometimes results in leaving index header readers open before shutting down.
This made some tests flaky. It could possibly mean that `BucketStores` stop `BucketStore` instances before waiting for ongoing queries to finish, but I am not certain of this and couldn't find proof in 2 weeks worth of store-gateway and querier logs. Still this is a bug and we should fix it.
By using `context.Background()` we rely on the shutdown here to take effect instead of detecting the parent context being cancelled
https://github.com/grafana/mimir/blob/fcef902e727c603411614d41bdb5d95223ac539f/pkg/storegateway/gateway.go#L32 …
> store-gateway: gracefully shut down BucketStores

- CHANGELOG.md
- tools/grpcurl-query-ingesters/.gitignore
- tools/grpcurl-query-ingesters/download-chunks-from-ingesters-query.json
- tools/grpcurl-query-ingesters/download-chunks-from-ingesters.sh
In this PR I'm upstreaming some changes I did to `download-chunks-from-ingesters.sh ` over the weekend in order to query ingesters concurrently and significantly speed it up when there are many ingesters to query.
N/A
> Improve download-chunks-from-ingesters.sh to query ingesters concurrently

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/promql/engine.go
- vendor/github.com/prometheus/prometheus/tsdb/head.go
- vendor/modules.txt
Update mimir-prometheus in r302 to revert https://github.com/prometheus/prometheus/pull/14525. This PR is a follow up of https://github.com/grafana/mimir/pull/9096, and it's based on a different mimir-prometheus commit.
The change in this PR is due to the commit that was previous missing in mimir-prometheus. Reason is that GEM r302 mimir-prometheus was advanced to a following release, but it wasn't backported to Mimir, so Mimir `r302` was missing some changes that have been actually included in GEM r302.
N/A
> [weekly-r302] Cherry-pick TSDB Head series hash fix

- renovate.json5
Try to configure Renovate to Pin the Go version at 1.22.5. Following a solution provided in a [Renovate discussion](https://github.com/renovatebot/renovate/discussions/16922).
Also rename renovate.json to renovate.json5, so we can add a comment (supported in [JSON5](https://json5.org/)). [Renovate supports JSON5](https://docs.renovatebot.com/configuration-options/).
> Renovate: Pin Go to v1.22.5

- pkg/querier/batch/batch.go
- pkg/querier/batch/chunk.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/batch/stream.go
This PR is a follow up to https://github.com/grafana/mimir/pull/8992.
In that PR, we noticed that `chunkIterator` had similar logic to `mergeIterator`, but decided to merge the change without adding a test for `chunkIterator`. In this PR, I'm adding a test for that case.
This revealed that while `chunkIterator` would have behaved correctly without the change in #8992, it would unnecessarily skip the optimisation to satisfy the `Seek` from the current batch if the sought timestamp was before the first sample of the current batch.
Note that `Seek` is expected to only move forwards, and I've clarified the docstring for the interface to reflect this.
I haven't added a changelog entry given this PR only adds a test.
Relates to https://github.com/grafana/mimir/pull/8992.
- [n/a] Documentation …
> Add unit test for `chunkIterator.Seek()` when the current batch can satisfy the sought timestamp

- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
~_This is the part 2 or N, which is currently seats atop the #8978. I will move it out of the draft after the latter gets merged._~
This PR updates the block-builder's tsdb wrapper to properly handle non-terminal (soft) errors, raised while a record's samples are being appended. While block-builder is still an early experiment, we skip testing every possible case for a soft error. We can add more tests as we get more comfortable with the design.
>  blockbuilder: handle non-terminal errors when processing record samples

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-top-tenants.json
- operations/mimir-mixin-tools/serve/run.sh
- operations/mimir-mixin/.lint
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
- operations/mimir-mixin/dashboards/tenants.libsonnet
- operations/mimir-mixin/dashboards/top-tenants.libsonnet
The Queries dashboard doesn't offer a consistent view over queries. As supported by the OSS jsonnet, at Grafana Labs we currently have 2 read path stacks:
- one for user queries
- one for Mimir rule evaluations
The panels in the Queries dashboard show a mix of the two. For components shared between the 2 read stacks (ingesters and store-gateways) we show metrics related to all queries. For components specific to a stack, we don't query `ruler-*` components, so we miss rule evaluations from Queries dashboard. This is confusing to me.
The easy solution would be to always add `ruler-*` components to the query, but after a quick internal feedback loop looks like there's people liking the ability to see metrics for a specific read path (I see value as well).
In this PR I'm proposing to add a …
> Dashboards: add 'Read path' selector to 'Mimir / Queries' dashboard

- CHANGELOG.md
- operations/mimir-tests/test-all-components-with-custom-runtime-config-generated.yaml
- operations/mimir-tests/test-all-components-with-custom-runtime-config.jsonnet
- operations/mimir/common.libsonnet
- operations/mimir/config.libsonnet
I have an use case to remove a field from overrides in jsonnet. However, there's no easy way to do it. I propose to use a strategy similar to the one we use with CLI flags: setting a overrides config field value to `null` will remove it.
I've added a jsonnet test building on top of `test-all-components` so we can diff the two:
```
diff operations/mimir-tests/test-all-components-generated.yaml operations/mimir-tests/test-all-components-with-custom-runtime-config-generated.yaml
```
```diff
178c178,187
<     overrides: {}
---
>     overrides:
>         tenant-1:
>             max_global_series_per_metric: 1000
>             max_global_series_per_user: 100000
>         tenant-3: {}
>         tenant-4:
>             max_global_series_per_metric: 0
>             max_global_series_per_user: …
```
> Jsonnet: recursively remove null values from overrides config

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/manager.go
- pkg/ruler/manager_test.go
- pkg/ruler/ruler.go
Remove `-ruler.drain-notification-queue-on-shutdown` option, and enable it by default. We're doing this after successful rollout and usage of the feature in our production environment.
> Remove ruler.drain-notification-queue-on-shutdown option, and make enabled it by default

- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
This is a small cleanup to make error handling a bit more explicit. The basic idea is that we take different actions based on the response:
1. Back off and wait a bit
2. Adjust the range of records we want to fetch
3. (TODO) refresh broker metadata
In each action we look at the error we received and decide.
This is what is listed in the [franz-go package](https://github.com/grafana/mimir/blob/04df05d32320cd19281591a57c19cceba63ceabf/vendor/github.com/twmb/franz-go/pkg/kmsg/generated.go#L4705-L4745) for fetch responses. Next to each is how I think we should handle each. franz-go has more explanations for what each error means _I couldn't find official kafka docs which list this_.
<details> <summary>All errors we have to handle </summary>
```
// OffsetOutOfRange - already handled - modify …
```
> kafka replay speed: make error handling more explicit

- CHANGELOG.md
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/frontend/querymiddleware/sharded_queryable_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
This PR fixes an issue where some annotations would not be returned for sharded queries.
This would occur if the annotation was generated during the evaluation of one of the shards. 
For example, the query `sum(rate(foo[5m]))` should return a `metric might not be a counter, name does not end in _total/_sum/_count/_bucket: "foo"` info annotation. When this query is sharded, the annotation is generated during the evaluation of one of the `sum(rate(foo{__query_shard__="x_of_y"}[5m]))` shards on queriers, but the query-frontend would not combine annotations from individual shards into the final result.
This PR changes the behaviour of query-frontends to accumulate and return annotations from each sharded query.
(none)
- [n/a] …
> Fix issue where annotations would not be returned for sharded queries

- tools/benchmark-query-engine/main.go
Go 1.23 added printing the CPU name to benchmarks on macOS, which clutters the output from `tools/benchmark-query-engine`.
This PR fixes the behaviour of `tools/benchmark-query-engine` to print the CPU name just once per run.
Given this is just an internal tooling change I haven't added a changelog entry.
(none)
> Mimir query engine: don't include `cpu: ...` line before every benchmark run in `tools/benchmark-query-engine`

- CHANGELOG.md
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
Start and End times in Series, LabelNames, LabelValues calls are optional. When they're unset Prometheus defaults them to MinTime (effectively MinInt) and MaxTime (MaxInt).
Currently MaxQueryIntoFuture clamps the start time relative to now. After that the start time is clamped relative to the end because of the max_label_query_length limit.
However with PR #7496 we're preparing to remove that option, so we'll no longer be clamping max time relative to now. Without clamping the end time we end up clamping start to MaxTime, so the whole query is for some (e.g.) 30 days in the year 292277025, which usually returns no data.
In this PR we're only clamping start time when start, end, or both aren't provided. It's clamped to end time if that was provided or to now, otherwise.
We don't clamp end …
> querier: clamp start time for Series, LabelValues, LabelNames

- docs/sources/mimir/references/architecture/components/alertmanager.md
This commit adds a small improvement to the UTF-8 docs where users should check that UTF-8 mode is enabled in the Final steps.
> Small improvement to UTF-8 docs

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/api/handlers.go
- pkg/distributor/otel.go
- pkg/distributor/otlp/helper_generated.go
- pkg/distributor/otlp/metrics_to_prw_generated.go
- pkg/distributor/otlp/number_data_points_generated.go
- pkg/distributor/push_test.go
- pkg/querier/error_translate_queryable_test.go
- pkg/util/validation/limits.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
- vendor/github.com/prometheus/prometheus/web/api/v1/api.go
- vendor/modules.txt
This PR is introducing the changes from https://github.com/grafana/mimir/pull/9131 , that are not yet in main, into release r303 as a backport.
> OTLP: Convert start timestamps to Prometheus timestamps for r303

- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_benchmark_test.go
- pkg/scheduler/queue/tenant_querier_assignment.go
- pkg/scheduler/queue/tree_queue_algo_querier_worker_queue_priority.go
Updates `QuerierWorkerQueuePriorityAlgo` to use the `Node`'s `childrenChecked` field instead of keeping its own count of nodes checked; this lets the tree reset the count after the dequeue operation is completed. This also includes a small bugfix introduced to `tenantQuerierAssignments` by defining leaf nodes.
> Use node fields instead of custom queuing algorithm to count children checked

- CHANGELOG.md
- tools/grpcurl-query-ingesters/main.go
This PR makes some changes to `tools/grpcurl-query-ingesters`:
* the output series will now be sorted by their labels
* the output chunks for each series will now be sorted by their timestamp
* chunk timestamps will now include the date, not just the time
(none)
> grpcurl-query-ingesters: sort series and chunks and print full timestamps

- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue.go
- pkg/scheduler/queue/tenant_querier_assignment.go
- pkg/scheduler/queue/tree_queue_algo_querier_worker_queue_priority.go
- pkg/scheduler/queue/tree_queueing_algorithms.go
Previously, queuing algorithms were responsible for managing how to define `checkedAllNodes`, a condition to signal the tree to move on to a different subtree (e.g., after checking every child of the current node for a dequeue-able object and finding none).
This change moves the responsibility for managing `checkedAllNodes` out of the queuing algorithm and instead codifying the condition for moving on to the next subtree -- it happens when we have attempted a dequeue on every child of the current node and found no dequeue-able value.
> Move childrenChecked check out of queuing algorithms

- development/mimir-monolithic-mode/config/mimir.yaml
I was confused why the docker compose profiles yielded different metrics:
```
./compose-up.sh --profile otel-collector-otlp-push
```
had no unit suffix like milliseconds.
But
```
./compose-up.sh --profile otel-collector-remote-write
```
did. It was because we don't add the suffixes by default.
> development: enable metric suffixes by default on OTLP by default

- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
The suggestion in the PR was to make `concurrentFetchersMinBytesMaxWaitTime` a field on `concurrentFetchers`. But those are created and started by the `PartitionReader` in its `starting` function [here](https://github.com/grafana/mimir/blob/b5050f31e51b8b2224ae10983f5221c9368897e8/pkg/storage/ingest/reader.go#L196). So the tests don't have control over them.
This is another approach where we have the field on `PartitionReader` and pass it to the constructor of `concurrentFetchers`.
> kafka replay speed: address post-merge feedback from 9152

- CHANGELOG.md
- pkg/alertmanager/api.go
- pkg/alertmanager/api_test.go
Alertmanager config validation also checks for template correctness. In the API, only templates that are directly referenced under `alertmanager_config` are checked - unreferenced template content is not validated.
Upstream alertmanager does validate all template content, regardless of references: https://github.com/prometheus/alertmanager/blob/a6df704408ba303c5d1d4e8e751da227e0ab08bf/cmd/alertmanager/main.go#L418-L421
Mimir does the same when bootstrapping alertmanager - all template files are loaded (and eventually parsed) without checking references:
https://github.com/grafana/mimir/blob/f52911d917c8c52e0da6a59348a64dd7f7622072/pkg/alertmanager/api.go#L149
This PR solves this validation gap in Mimir's API - users can create bad templates by simply not referencing them, resulting in …
> Alertmanager: Fix config validation gap around unreferenced templates

- CHANGELOG.md
- cmd/query-tee/main.go
- docs/sources/mimir/manage/tools/query-tee.md
- tools/querytee/proxy.go
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR extends query-tee's response comparison to accept equivalent but non-identical error messages as the same.
For example, Prometheus' engine and MQE return slightly different error messages in some circumstances, and Prometheus' engine is non-deterministic when selecting example series in some error messages. Both of these situations can cause query-tee to consider a response as different, but we usually don't care as long as the errors are equivalent.
This new behaviour is enabled by default but can be disabled with `-proxy.require-exact-error-match=true`.
(none)
> query-tee: optionally consider equivalent errors the same when comparing responses

- CHANGELOG.md
- pkg/querier/blocks_consistency_checker.go
- pkg/querier/blocks_consistency_checker_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
This PR improves the logging done during consistency checks for queries to store-gateways.
Specifically, it attaches the log messages emitted by `BlocksConsistency.NewTracker` to the active trace span as events, so these can be viewed alongside the other related events emitted by `blocksStoreQuerier.queryWithConsistencyCheck`.
(none)
> Attach consistency check debug logs to trace spans

- CHANGELOG.md
- pkg/querier/blocks_consistency_checker.go
- pkg/querier/blocks_consistency_checker_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
This PR backports #9213 to r306.
(none)
> Backport #9213 to r306

- .github/workflows/test-build-deploy.yml
* run skopeo via docker in integration tests.
Signed-off-by: Peter Štibraný <pstibrany@gmail.com>
* Use fixed version.
Signed-off-by: Peter Štibraný <pstibrany@gmail.com>
* Add /tmp volume and path to docker.sock.
Signed-off-by: Peter Štibraný <pstibrany@gmail.com>
* Only map /tmp/images.
Signed-off-by: Peter Štibraný <pstibrany@gmail.com>
---------
Signed-off-by: Peter Štibraný <pstibrany@gmail.com>
(cherry picked from commit 24ae27e41b91f2091f2f6c11744d407ad80ab663)
> Run `skopeo` via docker in integration test jobs (#8355)

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/multitenant.go
Fixes https://github.com/grafana/alerting-squad/issues/872
As described, alerts should use the Grafana URL instead of the remote AM's. For regular alert notifications this was already done, this PR fixes for tests
> Use grafana URL to test receivers

- go.mod
- go.sum
- pkg/api/handlers.go
- pkg/distributor/otel.go
- pkg/distributor/otlp/helper_generated.go
- pkg/distributor/otlp/metrics_to_prw_generated.go
- pkg/distributor/otlp/number_data_points_generated.go
- pkg/querier/error_translate_queryable_test.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
- vendor/github.com/prometheus/prometheus/web/api/v1/api.go
- vendor/modules.txt
This PR updates weekly-r304 to introduce 
- https://github.com/grafana/mimir-prometheus/pull/684
- https://github.com/grafana/mimir-prometheus/pull/685
- https://github.com/grafana/mimir-prometheus/pull/689
> [weekly-r304] Cherry pick created timestamp fix

- CHANGELOG.md
- pkg/alertmanager/distributor_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- pkg/util/test/leak.go
When a tenant has bad config in the store and no prior running alertmanager, we start a new one and try to apply the bad config to it. When the apply fails, we forget to shut down the alertmanager we just started.
This means we leak an alertmanager every time we sync that user's config.
There is a check for config correctness earlier on when syncing configs, but it is only a partial check - for example, it does not check templates - so it is easily bypassed (nor should we trust it). This PR fixes the leak directly.
Contrib https://github.com/grafana/mimir/issues/73
> Alertmanager: Fix goroutine leak when stored config fails to apply and there is no existing tenant alertmanager

- CHANGELOG.md
- pkg/continuoustest/util.go
This adds more fluctuation to the byte contents of the the labels emitted by continuous-test, because if the only difference in the labels is a monotonically increasing integer, the resulting tokens are poorly distributed.
Histogram of 10K hashes before:
and after:
> Make continuous-test writes hash more uniformly.

- CHANGELOG.md
- pkg/scheduler/queue/query_component_utilization.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/queue/tenant_queues.go
This PR allows the `-query-scheduler.prioritize-query-components` flag to utilize the querier-worker queue priority algorithm at the root of the scheduler's tree queue. It does not enable it by default as the flag remains default false.
This follows various benchmark and profiling tests to ensure that the algorithm solves the desired issue and that we have not introduced any performance issues.
Our measure of success for this new queueing algorithm has been to keep moving queries to ingesters when the store-gateways experience a slowdown.
This has been simulated and compared between old and new queuing algorithms both in a Go benchmark unit test and in the docker-compose Mimir microservices mode dev environment.
This was covered extensively in [PR …
> Query Scheduler: Enable Querier-Worker Queue Priority Algorithm with prioritize-query-components

- pkg/ingester/errors.go
Fix a doc comment typo in `ingester.newPerMetricSeriesLimitReachedError`.
> `newPerMetricSeriesLimitReachedError`: Fix doc comment typo

- CHANGELOG.md
- pkg/continuoustest/util.go
Address a comment on #9218 to make the extra entropy land in a new independent label, rather than stuffing it into `series_id`, as querying on `series_id` is useful when reverse-engineering continuous-test failures.
> Continuous-test: Move extra hash entropy to separate label.

- CHANGELOG.md
- operations/mimir-rules-action/README.md
- operations/mimir-rules-action/entrypoint.sh
Adds a new input (`NAMESPACES_REGEX`) to `mimir-rules-action`. This input is applicable for `diff` and `sync` actions, and corresponds to the mimirtool [`--namespaces-regex` parameter for diff and sync](https://grafana.com/docs/mimir/latest/manage/tools/mimirtool/#diff).
Also adds a check to verify that at most only one of the `NAMESPACES` or `NAMESPACES_REGEX` inputs is set, as mimirtool docs specify that "only one of the namespace selection flags can be specified."
N/A
> add new NAMESPACES_REGEX input to mimir-rules-action

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/querier/blocks_consistency_checker.go
- pkg/querier/blocks_consistency_checker_test.go
- pkg/querier/blocks_finder_bucket_index.go
- pkg/querier/blocks_finder_bucket_index_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/storage/tsdb/config.go
- pkg/storage/tsdb/config_test.go
- pkg/storegateway/bucket_stores.go
This PR fixes an issue where both recently compacted blocks and their source blocks can be skipped during querying if store-gateways are restarting around the time of the query.
Prior to this PR:
- The default value of `-blocks-storage.bucket-store.sync-interval` is 15 minutes. Any blocks that have been uploaded within `3× -blocks-storage.bucket-store.sync-interval` are queried with best effort (ie. no retries if the first store-gateway queried doesn't have the block). So any block uploaded within the last 45 minutes was only queried with best effort by default. ([source](https://github.com/grafana/mimir/blob/d16f21ce30356d53f6882e71cc05f043266ff01a/pkg/querier/blocks_store_queryable.go#L254-L256))
- The default value of `-blocks-storage.bucket-store.ignore-deletion-marks-delay` is 60 …
> Fix issue where both recently compacted blocks and their source blocks can be skipped during querying

- pkg/distributor/otel.go
Pass `spanLogger` as logger for OTEL conversion. We want those debug messages to be part of the span.
> Pass spanLogger as logger for OTEL conversion.

- pkg/storage/ingest/partition_offset_reader.go
- pkg/storage/ingest/partition_offset_reader_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
When we're fetching records after the end of a partition or before the start Kafka returns OffsetOutOfRange errors. In those cases we have to choose whether to 
1. abandon the request in case it covers already deleted offsets due to retention
2. wait it out incase we're fetching offsets which haven't been produced yet
3. adjust our request in case only some of the records have been deleted due to retention 
1\. and 2. can be decided only by suing the first available offset of a partition (`LogStartOffset`). If we get `OffsetOutOfRange` and  neither 1. nor 2. is correct, then 3. must be. Therefore, we only need `LogStartOffset`. 
Previously I thought that we can make a decision when we receive `OffsetOutOfRange` using the information from a `FetchPartition` response - `HighWatermark` and …
> kafka replay speed: Handle offset out of range errors

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
When active series are purged the counts are inaccurate until the idle timeout elapses. During this time, we stop exporting the active series counts, which can be jarring to encounter on the Tenants dashboard if you don't have the context for what is happening.
This PR adds an annotation to three panels on the Tenants dashboard that indicates when active series for the tenant are being reloaded, as indicated by the `cortex_ingester_active_series_loading` metric.
The panel IDs are currently hard-coded, which means it will break if we change the order in the dashboard 😢 but I couldn't think of a way to be more clever here, without rewriting a chunk of the jsonnet dashboard scaffolding.
Fixes n/a
> Add active series reloading annotation to Tenants dashboard

- development/mimir-microservices-mode/dev.dockerfile
This PR upgrades Delve to a version compatible with Go 1.23.
(none)
> Upgrade Delve

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
For tenants with a lot of rule groups, the "Failed evaluations rate" panel on the Mimir/Tenants dashboard can end up loading gigabytes of data, eventually crashing the page. Limit the results to the top 50 rule groups, since that should be enough information.
> Limit rule failures panel on Tenants dashboard to 50 groups

- pkg/streamingpromql/aggregations/aggregations_test.go
I noticed there was a typo in a comment added in https://github.com/grafana/mimir/pull/9260. This PR fixes the typo.
https://github.com/grafana/mimir/pull/9260
> Fix typo in comment

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/query-scheduler/query-scheduler-pdb.yaml
Added a check for `query_scheduler.enabled` to ensure the query-scheduler `PodDisruptionBudget` is only created when the component is enabled in the Helm chart configuration.
N/A
> helm: create query-scheduler PDB only when enabled

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/ci/offline/metamonitoring-values.yaml
- operations/helm/charts/mimir-distributed/templates/metamonitoring/_helpers.tpl
- operations/helm/charts/mimir-distributed/templates/metamonitoring/metrics-instance.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/metrics-instance.yaml
Add for sigv4 for mimir metamonitoring from https://github.com/grafana/helm-charts/blob/main/charts/agent-operator/crds/monitoring.grafana.com_metricsinstances.yaml#L275-L307
> Add support for sigv4 in metamonitoring

- pkg/streamingpromql/benchmarks/comparison_test.go
- tools/benchmark-query-engine/compare.sh
- tools/benchmark-query-engine/main.go
This PR makes use of `benchstat`'s `-col` flag to simplify the benchmark comparison script used for comparing MQE to Prometheus' engine.
(none)
> Mimir query engine: simplify benchmarking comparison script

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/astmapper/pruning.go
- pkg/frontend/querymiddleware/astmapper/pruning_test.go
- pkg/frontend/querymiddleware/prune.go
- pkg/frontend/querymiddleware/prune_test.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
(Hackathon project) Query pruning optimises PromQL queries by rewriting them to avoid evaluating expressions that can't produce a result, which is particularly useful in [dashboards with toggles between native and classic histograms](https://github.com/grafana/jsonnet-libs/pull/1164/files#diff-040bce91f6d46ff86f067fe7e11934183b2ea095ff6d4c62c5e798f24b6d9269R86).
N/A
> Add query pruning middleware

- Makefile
- mimir-build-image/Dockerfile
Upgrades Go version in mimir-build-image.
n/a
> mimir-build-image: Upgrade Go version to 1.23.1-bookworm

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
Different architectures have a different implementation for `labels.Labels.Hash`, so CI runs with a different hashing implementation. This makes it hard to assert on how series are distributed.
> kafka replay speed: consistent label hashing in tests

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
Add some info about stalled compactor network block storage, which is one scenario that can be to blame for the `MimirCompactorHasNotSuccessfullyRunCompaction` alert.
> Include stalled network storage device info in compactor runbooks.

- CHANGELOG.md
- pkg/util/net/firewall_dialer.go
- pkg/util/net/firewall_dialer_test.go
In this PR I'm fixing the built-in Alertmanager receiver firewall detect `0.0.0.0` and IPv6 interface-local multicast address as local addresses, to be blocked if enabled via `-alertmanager.receivers-firewall-block-private-addresses`.
N/A
> Fix Alertmanager receiver firewal to detect 0.0.0.0 and IPv6 interface-local multicast address as local addresses

- go.mod
- go.sum
- pkg/distributor/otlp/helper_generated.go
- pkg/distributor/otlp/metrics_to_prw_generated.go
- pkg/distributor/otlp/number_data_points_generated.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- vendor/modules.txt
Update mimir-prometheus to latest `main`, which contains more logging in OTEL conversion code when adding samples due to recent creation timestamp. (https://github.com/grafana/mimir-prometheus/pull/695)
> Update mimir-prometheus, regenerate OTEL conversion code.

- go.mod
- go.sum
- pkg/distributor/otlp/helper_generated.go
- pkg/distributor/otlp/metrics_to_prw_generated.go
- pkg/distributor/otlp/number_data_points_generated.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/number_data_points.go
- vendor/modules.txt
Updates Prometheus and regenerates OTLP conversion code in `r307` branch to include https://github.com/grafana/mimir-prometheus/pull/697.
> r307: Update Prometheus, regenerate OTEL conversion code

- pkg/storage/ingest/reader_test.go
- pkg/util/test/logger.go
> Add locking around test logger to avoid data race

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/configure/configure-kafka-backend.md
- pkg/storage/ingest/config.go
- pkg/storage/ingest/reader.go
Normally all kafka flavours support the same API, except when they don't. Warpstream treats the `MaxBytes` field of a Fetch request as a limit on the uncompressed bytes of all the records. Apache Kafka treats it as a limit on the compressed bytes.
This difference in behaviour is quite significant and leads to very suboptimal performance when using the wrong interpretation.
This PR adds a config flag to be able to choose between the Kafka flavours. Open to feedback on what to call the flag and what to call the options.
This PR is based on #9203, but will also conflict with #9153 when merged. The conflicts should be tiny, so I think this is ready for a review. I'll rebase when the two PRs above are merged.
> kafka replay speed: compressed/uncompressed bytes for MaxBytes in fetch requests

- development/mimir-ingest-storage/config/datasource-mimir.yaml
- development/mimir-ingest-storage/config/mimir.yaml
- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/util.go
This PR is based on #9204 to avoid small paper-cut conflicts. The changes here are mostly independent of the changes there.
* Replaces `cortex_ingest_storage_reader_fetched_discarded_records_total` with  `cortex_ingest_storage_reader_fetched_discarded_bytes_total` so that we can better estimate whether overfetching is a real problem (avoid the question "are 1000 overfetched records too much?")
* Adds tracing for the fetch pipeline - there's a single trace for a single continuous section of records. My idea was to allow debugging increased e2e latency based on this. I want to add some events in the `PusherConsumer` that might help with debugging sharding performance, but I'll do that after #9133 is merged to avoid conflicts
* I tried including necessary information to be able to infer …
> kafka replay speed: instrument concurrent fetching pipeline

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- Introduce a new `BatchingQueue` to reveal the intentions of a queue per shard.
- Removed the need to call `Close` as we pushed data into TSDB from the main loop. This was really confusing given we were using close as a semantic to "no more items are coming" and ensure any incomplete batches were done.
- Renamed and moved the `noopPusherCloser` which is more of an alternative way to push data without any sort of concurrency.
- Inlined a few methods to get rid of certain level of indirection that made the code harder to understand.
N/A
> Refactor the `PusherConsumer` interactions

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
Add distributor middleware that checks if the underlying distributor service has started and if not, ~~blocks~~ rejects incoming requests until it has.
During normal startup this is not necessary because Mimir will not mark itself as ready until all its services have started.
However, if a distributor pod was already up and marked ready and then the distributor container restarted, k8s may still consider the pod ready before realizing that it is not and the pod may still end up receiving push requests.
In this state the push requests may end up being serviced incorrectly because other distributor middlewares expect their underlying services to already have started but they may not have been.
N/A
> Distributor: Add checkStartedMiddleware

- go.mod
- go.sum
- vendor/github.com/prometheus/alertmanager/notify/msteams/adaptive_cards.go
- vendor/github.com/prometheus/alertmanager/notify/msteams/msteams.go
- vendor/modules.txt
This PR updates the Alertmanager fork from commit https://github.com/grafana/prometheus-alertmanager/commit/66ec17e3aa454abc8d1fc5e374951fae5f594863 to commit https://github.com/grafana/prometheus-alertmanager/commit/60521fae6a4216431cdd73072457eae9fda32baa. This new version of the fork adds support for Adaptive Cards in the MS Teams integration.
> Alertmanager: Update AM fork to support Adaptive Cards in MS Teams

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/api_test.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
In some environments, it may be desirable to trade off increased resource usage for faster rule group updates.
- For the outbound queue - polling more often results in more gRPC calls to other rulers, but nothing else. I think reducing this below 10s could be valuable.
- For the inbound queue - polling more often results in more rule sync operations, which can be quite expensive for tenants with many rule groups. Reducing this is likely not a wise idea.
In a follow up PR, I want to experiment with making the sync operations more specific (e.g. include rule group), this would potentially allow more frequent inbound queue polling.
Part of https://github.com/grafana/mimir/issues/9329
> Ruler: Make the sync queue polling intervals configurable.

- pkg/distributor/distributor_ingest_storage_test.go
I suspect the 1s timeout can expire in CI. Let's inspect kafka in CI to check if that's the case or we have a bug.
Related to https://github.com/grafana/mimir/issues/9299
> distributor: add logs to flaky TestDistributor_Push_ShouldSupportWriteBothToIngestersAndPartitions

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Yesterday we found out a Kubernetes bug https://github.com/kubernetes/kubernetes/issues/127370 causing K8S service endpoints not getting updated when pods are stopped/started if there are more than 1K pods matching the service. This is badly affecting `gossip-ring` service, which includes all Mimir components.
In this PR I'm adding an alert + runbook specific to `gossip-ring` service.
N/A
> Add MimirGossipMembersEndpointsOutOfSync alert

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
I made 2000 up when we were flushing individual series to the channel. Then 2000 might have made sense, but when flushing whole WriteRequests a capacity of 1 should be sufficient.
> kafka replay speed: adjust batchingQueueCapacity

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR fixes an issue in https://github.com/grafana/mimir/pull/9143, where the pattern for binary operation conflict errors returned by MQE did not consider timestamps with millisecond precision.
https://github.com/grafana/mimir/pull/9143
> query-tee: fix error equivalence pattern for MQE binary operation conflict

- pkg/ingester/circuitbreaker_test.go
I believe there's a race between sending the first request and then collecting the metrics. It's possible that we collect the metrics longer than 200ms after the first request, at which point the CB has opened. I could reproduce https://github.com/grafana/mimir/issues/9052 by reducing the initialDelay to 10ms.
This PR increases it to 1 hour so that we're more sure that the delay hasn't expired when we're collecting the metrics.
Fixes https://github.com/grafana/mimir/issues/9052
> TestIngester_PushToStorage_CircuitBreaker: increase initial delay

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/writer_test.go
1. Parallelization based on: 
- The `parallelStoragePusher` now supports separate pushers for different write request sources (e.g., API, RULE) per tenant.
- This is necessary because the ingester keep track of metrics based on the source of the request.
- The tradeoff is that the config option for batch size isn't what it looks like - we have `2N` batches per tenant, not the `N` that's configured.
2. Metadata Handling:
- Added support for pushing metadata alongside time series data.
- Metadata is distributed across shards in a round-robin fashion.
> kafka replay speed: add support for metadata & source

- CHANGELOG.md
- tools/querytee/response_comparator.go
This PR builds on https://github.com/grafana/mimir/pull/9143 to add another class of equivalent errors.
https://github.com/grafana/mimir/pull/9143
> query-tee: add equivalent errors for string expression for range queries

- CHANGELOG.md
- pkg/util/objtools/s3.go
This is a rebased, fixed, and tested version of https://github.com/grafana/mimir/pull/8427. I'm opening a new PR since I let that one rot while it was waiting to be tested (sorry!).
The primary motivation of this change is allowing `undelete-blocks` to recover very large blocks in S3 where an `index` object may exceed 5GiB.
A server-side copy on S3 with minio's `CopyObject` fails if the object is greater than 5GiB in size. When testing the previous PR I found a bug that was fixable by supplying `MatchRange: true` in the `srcOptions` for `ComposeObject`. Upon further inspection I realized the byte ranges don't need to be created at all because `ComposeObject` already handles it.
I commented that I don't think this approach works cross-region. The minio code tries to double check the source …
> objtools: fix 5GiB+ server-side copies on S3

- integration/asserts.go
- integration/asserts_test.go
- integration/query_frontend_test.go
- integration/ruler_test.go
Add integration test assertion to ensure cortex_distributor_replication_factor is not exported when ingest storage is enabled. This covers a regression we recently had when running the experimental ingest storage at Grafana Labs.
N/A
> Add integration test assertion to ensure cortex_distributor_replication_factor is not exported when ingest storage is enabled

- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_benchmark_test.go
Fixes a race condition introduced to a test by https://github.com/grafana/mimir/pull/9190. This race condition is exposed by a idiosyncracy of the test, and would not happen under normal operating conditions.
`tenantQuerierAssignments.setup()` will (predictably) result in a race if you are reusing the same `tenantQuerierAssignments` value for multiple tree queues running in parallel.
There's an open question as to whether this test should run all the time, or if it should be changed to a benchmark which is only run at-will. I'm leaving that for @francoposa  to decide.
Fixes #9253
> Fix race in TestMultiDimensionalQueueAlgorithmSlowConsumerEffects

- pkg/storage/tsdb/bucketcache/caching_bucket.go
- pkg/storage/tsdb/bucketcache/caching_bucket_config.go
- pkg/storage/tsdb/bucketcache/caching_bucket_test.go
- pkg/storage/tsdb/caching_config.go
Invalidate content, existence, and attributes cached for a particular object when the object is modified or deleted.
Part of #9386
> Invalidate bucket caches on object modification or deletion

- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue.go
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_benchmark_test.go
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_test.go
- pkg/scheduler/queue/tenant_queues.go
- pkg/scheduler/queue/tree_queue_algo_querier_worker_queue_priority_test.go
At a leaf node, `QueuingAlgorithm` isn't used; we simply dequeue from the `Node`'s `localQueue`. To avoid confusion, we will use a `nil` `QueuingAlgorithm` in these cases, and append `nil` to the list of queuing algorithms at tree creation, so the leaf node behavior is always accounted for.
> Remove use of leaf-node round-robin algorithm

- pkg/querier/block_streaming.go
This PR fixes a flaky test, `TestStoreGatewayStreamReader_AbortsWhenParentContextCancelled`.
Theoretically this failure could also happen in the real world, but realistically it's unlikely to happen, and if it did, then a user would get a result for their cancelled query rather than an error saying it was cancelled. So there's no user-visible impact if the failure condition was triggered.
For this reason I don't think this is worthy of a changelog entry, open to other opinions though.
Resolves https://github.com/grafana/mimir/issues/8683
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/source …
> Fix flaky `TestStoreGatewayStreamReader_AbortsWhenParentContextCancelled`

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
So instead of getting `11000, 100000, 9000, struser`, we'll get `9000, 11000, 100000, struser`
None
> Tenant Dashboard: Use natural sort for "user" variable

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
Creates an experimental, most likely temporary, metric `cortex_distributor_label_values_with_newlines_total` used to track tenants who are sending newlines in their label values.
Fixes an internal request
> Create a metric to track users with newlines in ingested label values

- go.sum
- operations/mimir-mixin/dashboards/writes.libsonnet
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_metrics.go
- pkg/storage/ingest/pusher_test.go
* `cortex_ingest_storage_reader_processing_time_seconds` now records the time to process the whole batch of requests; this is useful in measuring the effectiveness of fetching from kafka vs ingesting
* `cortex_ingester_pusher_ingestion_shard_batch_age_seconds` to keep an eye on the performance of the queue
* `cortex_ingest_storage_reader_ingestion_shard_batch_processing_time_seconds` to know when popping form the queue slows down
> kafka replay speed: ingestion metrics

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_metrics.go
- pkg/storage/ingest/pusher_test.go
Previously, we'd let error bubble-up and only take decisions on whether to abort the request or not at the very top (`pusherConsumer`). This meant that we'd potentially buffer more requests before we detect an error.
This change extracts error handling logic into a `Pusher` implementation: `clientErrorFilteringPusher`. This implementation logs client errors and then swallows them. We inject that implementation in front of the ingester. This means that the parallel storage implementation can abort ASAP instead of collecting and bubbling up the errors.
> kafka replay speed: move error handling closer to actual ingestion

- CHANGELOG.md
- tools/querytee/proxy_endpoint.go
- tools/querytee/proxy_endpoint_test.go
- tools/querytee/proxy_test.go
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR fixes an issue in the behaviour of the `-proxy.compare-skip-recent-samples` CLI flag in query-tee.
Previously, when deciding whether to skip a sample, sample timestamps were compared to the time at the time the comparison was occurring. However, for a slow query, this may be well after the query was evaluated, and so may mean that `-proxy.compare-skip-recent-samples` is ineffective.
This PR changes the behaviour of query-tee to compare sample timestamps to the time at which the query request was sent. This reduces the number of unwanted comparison failures for recent data.
For example, let's say query-tee receives a query at 12:00, the query takes 3 minutes to evaluate through both backends, and `-proxy.compare-skip-recent-samples` is set to 5 minutes. Let's assume everything else …
> query-tee: fix behaviour of `-proxy.compare-skip-recent-samples` for long-running queries

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
~~_This one seats atop https://github.com/grafana/mimir/pull/9199 for now_~~
This is part of https://github.com/grafana/mimir/pull/8635; refer to it for more details.
Here we register the `block-builder` target in mimir. The block-builder is still in an earlier experiment, thus don't expose any documentation or changelog for now.
Also, the PR addresses the discussion we had with @dimitarvdimitrov in https://github.com/grafana/mimir/pull/9199#discussion_r1773600398 about a potential edge-case for a partition that has offset gaps. Here we refactor the internals of the consumer loop replacing the use of remaining lag with the reference to the partition end, at the time of the cycle.
> Register block-builder target in mimir

- pkg/storage/ingest/config.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_client.go
- pkg/storage/ingest/reader_test.go
* each concurrent fetcher no longer stops fetching when it's got 2 fetch results; it now continues fetching and combining the results (`fetchResult.Merge`)
* reduces MinBytesMaxWaitTime to 5s
* tracing improvements
* fixes a bug in tracking the last returned offset; this sometimes lead to returning the same record twice
> kafka replay speed: concurrency fetching improvements

- RELEASE.md
- renovate.json5
- update renovate's config to also manage the `release-2.14` branch
- update the RELEASE.md
> Update renovate to manage the release-2.14 branch

- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue.go
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_test.go
- pkg/scheduler/queue/tenant_querier_assignment.go
- pkg/scheduler/queue/tree_queueing_algorithms.go
With the introduction of leaf-node designations in #8871, we no longer need to maintain local queues on all nodes, and we can instead use `isLeaf()` to govern tree traversal decisions. 
Note that this introduces a subtle difference to the round-robin child queue ordering (`Node.queueOrder`) because all enqueued children will be enqueued "behind" the current `queueOrder[queuePosition]` node instead of maintaining a special case. This _does not_ change dequeue order, and is a no-op from the perspective of a caller to the tree.
> Remove localQueueIndex from QueuingAlgorithms

- CHANGELOG.md
This PR cuts the changelog for mimir v2.14, moving everything that isn't part of the r309 (~~or what we don't consider feature-ready~~) to the new unreleased section.
> Cut changelog for v2.14

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers.jsonnet
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger.jsonnet
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
This PR extends ingest-store support with ability to specify multiple triggers.
> Add support for multiple triggers in ScaledObject when using ingest-store ingester autoscaling.

- pkg/ingester/activeseries/active_labels_test.go
- pkg/ingester/activeseries/active_native_histogram_postings_test.go
- pkg/ingester/activeseries/active_postings_test.go
- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/activeseries/model/custom_trackers_config.go
- pkg/ingester/activeseries/model/custom_trackers_config_test.go
- pkg/ingester/activeseries/model/matchers.go
- pkg/ingester/activeseries/model/matchers_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/util/usage/usage.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
- tools/doc-generator/parse/parser.go
This pull request seeks to extract the CustomTrackersConfig struct from the activeseries package. The reason for this is that pkg/util/validation depends on github.com/grafana/mimir/pkg/ingester/activeseries. If we introduce any services invoked by activeseries, they won't be able to depend on validation.Overrides, since it would result in a circular import problem.
In this PR, I've introduced activeseriesmodel, which will be utilized by both activeseries and validation. The entire PR should be Noop
- na Tests updated.
- na Documentation added.
- na [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Chore: Extract CustomTrackersConfig from the activeseries package

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window.jsonnet
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
This PR adds `ingest_storage_ingester_autoscaling_scale_up_stabilization_window_seconds` and `ingest_storage_ingester_autoscaling_scale_down_stabilization_window_seconds` config options to make stabilization window for ingester autoscaling when using ingest-storage configurable.
> Jsonnet/ingest-storage: Make stabilization window for scaling ingesters configurable

- CHANGELOG.md
This is a fixup for #9427
The release-notes preparation script currently fails with
```
Generating the draft release notes...
Unable to find the section title '## 2.14.0-rc.0' in the ./tools/release/../../CHANGELOG.md
```
This PR fixes the typo in the changelog.
> Fix a typo in the release-2.14 changelog

- pkg/storage/ingest/partition_offset_reader.go
- pkg/storage/ingest/partition_offset_reader_test.go
This is the first of series of PRs to upstream the code for improving Kafka replay speed in the ingester.
In this PR I'm upstreaming a tiny change related to partitionOffsetReader. We need caching in the reader so that we can check the start offset of the partition. We don't need that to be very exact because we use it to find out if we're trying to consume from before the start.
> kafka replay speed: upstream partition_offset_reader.go

- integration/e2ehistograms/e2ehistograms.go
- integration/util.go
Minor refactor of integration/util.go to separate concerns more cleanly, moving the e2e histograms code to its own package, which will allow us to export it without exporting a lot of other unnecessary code.
N/A
None as these are minor, non-user-facing changes.
> Move the e2e histograms code to somewhere where it can be exported

- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
This PR marks the experimental support for Redis-based caching as deprecated.
Fixes https://github.com/grafana/mimir-squad/issues/2414
> docs: deprecate redis-based caching

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/alertmanager/api_grafana.go
- pkg/alertmanager/api_grafana_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- pkg/util/validation/limits.go
Remote AM already has limits in place for it's own configuration. However, when using grafana compat mode, it doesn't have any. This aims to add a new config limit for grafana configuration.
> Alertmanager: Add grafana config size limit

- CHANGELOG.md
- tools/copyblocks/README.md
- tools/copyblocks/main.go
Adds a flag to bypass the block duration check in `copyblocks` for blocks marked as no-compact.
It's a common pattern to use `min-block-duration` with the intent of targeting blocks that are fully compacted. This can miss blocks that are marked as `no-compact` that have a shorter duration. This flag makes it easier to not miss those blocks.
Fixes N/A
> copyblocks: add option to bypass duration check for no-compact blocks

- pkg/alertmanager/alertmanager.go
The intention here should be to initialize a slice with a capacity of len(am.templates) rather than initializing the length of this slice.
> fix: fix slice init length

- pkg/storage/ingest/reader_test.go
- pkg/util/test/logger.go
After https://github.com/grafana/mimir/pull/9326 we were using locks within a single test, but `Parallel()` tests were using difference instances of `testingLogger`, so there was no synchronization.
Fixes https://github.com/grafana/mimir/issues/9325
> ingest storage: synchronize logger access between parallel tests

- integration/e2emimir/client.go
- integration/getting_started_with_grafana_mimir_test.go
- integration/otlp_ingestion_test.go
- integration/querier_test.go
- integration/read_write_mode_test.go
Allow matchers for label names endpoint in e2emimir client
N/A
Minor non-user-facing change.
> Allow matchers for label names endpoint in e2emimir client

- pkg/querier/worker/scheduler_processor_test.go
- pkg/ruler/compat_test.go
- pkg/util/test/collect.go
This PR fixes `TestSchedulerProcessor_processQueriesOnSingleStream` flakyness reported in https://github.com/grafana/mimir/issues/7888. The explanation is in the code comment.
Fixes #7888
> Fix TestSchedulerProcessor_processQueriesOnSingleStream flakyness

- docs/sources/mimir/release-notes/v2.14.md
~~This is a draft PR that I'll populate with the 2.14 release notes.~~
These are the release notes for the 2.14 release.
> 2.14 release notes

- CHANGELOG.md
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
ingest-storage: Make label-selector in ReplicaTemplate configurable
> ingest-storage: Make label-selector in ReplicaTemplate configurable

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- operations/mimir-mixin/dashboards/writes.libsonnet
- pkg/storage/ingest/config.go
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_metrics.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer_test.go
This is the third of series of PRs to upstream the code for improving Kafka replay speed in the ingester.
In this PR we upstream push sharding. The basic idea is that instead of ingesting each record from Kafka sequentially, we can shard each timeseries and ingest them in parallel.
_I'm submitting the PR, but the work was done jointly by @gotjosh and myself_
1. `pusherConsumer`
- This component receives records from Kafka and pushes them to storage.
- It uses a separate goroutine for unmarshaling records while pushing the current record to storage.
- After unmarshalling each record is pushed to a `parallelStoragePusher`
2. `parallelStoragePusher`
- Manages parallel pushing of WriteRequests to storage.
- Tenant separation: It maintains a map of tenant IDs to `parallelStorageShards`. This …
> kafka replay speed: upstream push sharding

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_template.go
- pkg/alertmanager/alertmanager_template_test.go
- pkg/alertmanager/alertmanager_test.go
As we're using `[]io.Reader` for templates, we can read them only once. This is a problem because we use different structs to execute templates for Mimir and Grafana integrations, and both need the same templates. When we create the Grafana template struct, the templates have already been read, resulting in "template not defined" errors when trying to send notifications with custom templates.
Since we stopped reading templates from disk, there's no advantage in using an `io.Reader` besides using the interface  
`github.com/prometheus/alertmanager/template` expects in `template.Parse()`.
This PR replaces `[]io.Reader` for templates in favor of `[]TemplateDefinition`, converting them into an `io.Reader` when calling `template.Parse()`.
Fixes …
> Alertmanager: Fix custom Grafana templates not defined

- CHANGELOG.md
- pkg/streamingpromql/operators/vector_vector_binary_operation.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR fixes a bug in MQE's binary operation implementation where query results can be incorrect or incorrectly fail with "found duplicate series for the match group" errors.
`labels.Labels.BytesWithLabels` and `labels.Labels.BytesWithoutLabels` expect the list of label names they receive to be sorted. However, we weren't ensuring this was true when `BytesWithLabels` was called to generate the grouping key for a binary operation with `on`, so incorrect grouping keys were generated.
(none)
> MQE: fix incorrect query results or "found duplicate series for the match group" errors when binary operation has unsorted labels in `on`

- pkg/storage/ingest/reader.go
This `partitionCommitter` would be shut down via the services manager as soon as the service context is cancelled. This means that they shut down in parallel with the `PartitionReader`. The race comes when the `partitionCommitter` has already shut down while the `PartitionReader` is still processing some records. Then when the `PartitionReader` tries to `enqueueCommit`, that sets the atomic, but does not send this to Kafka.
As a result we may not always persist the latest commit to Kafka on shutdown.
Fixes https://github.com/grafana/mimir/issues/8697
> ingest storage: proper shutdown of partitionCommitter

- pkg/storage/ingest/reader_test.go
franz-go has its own retries and sometimes the call to the library just takes longer than 10s
test with debug logs: see when `partitionOffsetClient.fetchPartitionOffset done` runs compared to `partitionOffsetClient.fetchPartitionOffset` (up to 10s after it)
```
logger.go:38: 2024-10-02 11:59:42.429605 +0200 CEST m=+0.014903709 level info partition 1 msg starting consumption from partition start because no offset has been found start_offset -2 consumer_group test-group
logger.go:38: 2024-10-02 11:59:42.430251 +0200 CEST m=+0.015549793 level info partition 1 component kafka_client msg immediate metadata update triggered why querying metadata for consumer initialization
partitionOffsetClient.fetchPartitionOffset 2024-10-02 11:59:42.430466 +0200 CEST m=+0.015764626 …
```
> ingest storage: fix flaky TestPartitionReader_ConsumeAtStartup

- pkg/storage/ingest/fetcher.go
Without this we end up using a bad estimation for the whole fetch
> kafka replay speed: update fetch bytes estimation on multiple attempts

- pkg/storage/ingest/reader.go
This fixes a flaky `TestPartitionReader_Commit` because we'd shut down the reader right after receiving the records. That would return an error as if ingesting caused an error. The bug was introduced in #9454 where we did the opposite change. The opposite change isn't functionally necessary.
Related to #8697
> ingest storage: don't return an error when records are successfully ingested

- CHANGELOG.md
- operations/mimir/querier.libsonnet
This PR introduces `querier_only_args` to the Jsonnet library.
These CLI flags are applied only to queriers, not ruler-queriers, unlike `querier_args` which are applied to both queriers and ruler-queriers.
(none)
> Jsonnet: add config option for querier-only CLI flags

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/streamingpromql/config.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
This PR introduces separate feature flags for comparison operations between two vectors, two scalars and between a vector and a scalar.
I've found an issue in the implementation of comparison operations for two vectors which is not trivial to fix, so it'd be nice to be able to disable just those while keeping others enabled.
https://github.com/grafana/mimir/pull/9398
> MQE: separate feature flag for binary comparison operations

- CHANGELOG.md
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
This PR adds more information to the "query stats" log lines emitted by MQE.
Specifically, it adds the expression, query type, time range and step. 
This makes it easier to identify which query stats log line belongs to which query when the request trace is not sampled, as otherwise there is no identifying information beyond the time.
(none)
> MQE: include more information in query stats log lines

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/storage/ingest/config.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer_test.go
Striking the right configuration for ongoing fetching depends a lot on the characteristics of cluster. franz-go is better at adaptive concurrency, so we fall back to it until we've implemented adaptive concurrency and/or records-per-fetch.
> kafka replay speed: fall back to franz-go for ongoing fetching

- pkg/ingester/ingester.go
Relates to https://github.com/grafana/mimir/pull/9496 and https://github.com/grafana/mimir/pull/8695, this PR adds a comment with some context for why the feature is still experimental.
> ingester: comment on experimental status of owned series limits

- go.mod
- go.sum
- vendor/github.com/twmb/franz-go/pkg/kgo/compression.go
- vendor/github.com/twmb/franz-go/pkg/kgo/config.go
- vendor/github.com/twmb/franz-go/pkg/kgo/internal/pool/bucketed_pool.go
- vendor/github.com/twmb/franz-go/pkg/kgo/record_and_fetch.go
- vendor/github.com/twmb/franz-go/pkg/kgo/source.go
- vendor/modules.txt
Replacing current `franz-go` dependency with our own fork, based on `v1.17.1`, which includes the following changes:
- https://github.com/grafana/franz-go/pull/1
- https://github.com/grafana/franz-go/pull/3
- https://github.com/grafana/franz-go/pull/4
Fixes n/a
> use grafana/franz-go fork

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- pkg/alertmanager/api.go
- pkg/alertmanager/api_grafana.go
- pkg/alertmanager/api_grafana_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- pkg/util/globalerror/user.go
- pkg/util/validation/limits.go
Similar to #9402 , but for Grafana state
Fixes https://github.com/grafana/alerting-squad/issues/933
> Alertmanager: Add state size limit

- CHANGELOG.md
- Makefile
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/config.go
- pkg/streamingpromql/engine_concurrency_test.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/and_binary_operation.go
- pkg/streamingpromql/operators/binary_operation.go
- pkg/streamingpromql/operators/vector_vector_binary_operation.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
- pkg/streamingpromql/testdata/upstream/operators.test
- tools/find-unpooled-slice-creation.sh
This PR adds support for the `and` binary operation.
Compared to Prometheus' engine, latency is up to 90% lower and peak memory consumption is up to 48% lower in our benchmarks:
```
│  Prometheus   │                Mimir                │
│    sec/op     │    sec/op     vs base               │
Query/a_1_and_b_1{l=~'.*[0-4]$'},_instant_query-10                        723.5µ ±  0%   717.8µ ±  1%        ~ (p=0.310 n=6)
Query/a_1_and_b_1{l=~'.*[0-4]$'},_range_query_with_100_steps-10           744.2µ ±  2%   734.0µ ±  4%        ~ (p=0.818 n=6)
Query/a_1_and_b_1{l=~'.*[0-4]$'},_range_query_with_1000_steps-10          1.269m ±  1%   1.130m ±  1%  -10.93% (p=0.002 n=6)
Query/a_100_and_b_100{l=~'.*[0-4]$'},_instant_query-10                    1.613m ± 11%   1.609m ±  2%        ~ (p=0.485 n=6) …
```
> MQE: add support for `and`

- CHANGELOG.md
- pkg/streamingpromql/functions/rate_increase.go
- pkg/streamingpromql/testdata/ours/native_histograms.test
This PR fixes a panic in MQE when `rate` or `increase` is used over a range of native histograms that change schema multiple times.
(none)
> MQE: fix panic in `rate` or `increase` over native histograms with changing schema

- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/mimir/modules_test.go
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
- pkg/ruler/rulestore/bucketclient/bucket_client.go
- pkg/ruler/rulestore/bucketclient/bucket_client_test.go
- pkg/ruler/rulestore/local/local.go
- pkg/ruler/rulestore/store.go
- pkg/ruler/storage.go
- pkg/ruler/store_mock_test.go
Instead of using two different `RuleStore` implementations within the Ruler, use a single caching implementation and selectively disable caching when required.
This change removes the "direct" `RuleStore` implementation from the Ruler's gRPC and HTTP API layers. Instead, the caching implementation is used for all calls. In cases where caching returning stale results would not be acceptable, the caching is disabled _just_ for that call.
This allows rule group contents to be safety cached with the understanding that it is safe to cache them because they will correctly invalidated when deleted or modified.
Part of #9386
I had a bit of trouble getting my head around this change. I've found the following to be a good way of thinking about it:
* We allow `Bucket.Iter()` calls to be cached …
> Unify direct and caching `RuleStore`s in ruler

- CHANGELOG.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/and_unless_binary_operation.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
- pkg/streamingpromql/testdata/upstream/operators.test
- pkg/streamingpromql/testutils/utils.go
This PR adds support for the `unless` binary operation, building on the support for `and` added in #9507.
Compared to Prometheus' engine, latency is up to 60% lower and peak memory consumption is up to 48% lower in our benchmarks:
```
│  Prometheus   │               Mimir                │
│    sec/op     │   sec/op     vs base               │
Query/a_1_unless_b_1{l=~'.*[0-4]$'},_instant_query-10                        721.4µ ± 12%   716.4µ ± 1%        ~ (p=0.093 n=6)
Query/a_1_unless_b_1{l=~'.*[0-4]$'},_range_query_with_100_steps-10           777.4µ ±  4%   745.8µ ± 6%        ~ (p=0.180 n=6)
Query/a_1_unless_b_1{l=~'.*[0-4]$'},_range_query_with_1000_steps-10          1.310m ±  3%   1.184m ± 3%   -9.67% (p=0.002 n=6)
Query/a_100_unless_b_100{l=~'.*[0-4]$'},_instant_query-10 …
```
> MQE: add support for `unless`

- CHANGELOG.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions/label.go
- pkg/streamingpromql/operators/string.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours-only/functions.test
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/at_modifier.test
- pkg/streamingpromql/testdata/upstream/functions.test
- pkg/streamingpromql/testutils/utils.go
- pkg/streamingpromql/types/operator.go
> MQE: Add support for label_replace

- pkg/util/test/metrics.go
- pkg/util/test/metrics_test.go
Add tests for `pkg/util/test.AssertGatherAndCompare`. Also fix said function for when no `metrics` are provided.
> Add tests for `pkg/util/test.AssertGatherAndCompare`

- CHANGELOG.md
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
- pkg/frontend/querymiddleware/split_by_instant_interval_test.go
This PR fixes an issue where annotations could be returned to a user with incorrect position information if the query is sharded and the sharded legs generate annotations.
For example, running the query `avg(rate(up[1m]))` can produce two annotations:
- `PromQL info: metric might not be a counter, name does not end in _total/_sum/_count/_bucket: "up" (1:10)`
- `PromQL info: metric might not be a counter, name does not end in _total/_sum/_count/_bucket: "up" (1:12)`
...but `up` appears at position 10 on line 1, so the second annotation at position 12 is misleading or confusing. It comes about because `avg(...)` is rewritten as `sum(...) / count(...)` for sharding and the second annotation is generated by queriers for the sharded `count(rate(up[1m]))` legs.
Another example: running the …
> Don't return incorrect position information from annotations generated by sharded query legs

- CHANGELOG.md
- pkg/streamingpromql/functions/rate_increase.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/name_label_dropping.test
This PR fixes an issue in MQE's implementation of `rate` and `increase` that can cause it to return multiple series with the same labels instead of a single series or returning a `vector cannot contain metrics with the same labelset` error.
I have a more robust fix planned: moving `NeedsSeriesDeduplication` to a new `SeriesMetadataFunc` struct, so that `NeedsSeriesDeduplication` is always true for `DropSeriesName`, but I'd like to merge this simpler fix first as it will be far easier to backport.
(none)
> MQE: fix issue where `rate` or `increase` can return multiple series with the same labels

- CHANGELOG.md
- pkg/streamingpromql/functions/rate_increase.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/name_label_dropping.test
This PR manually backports https://github.com/grafana/mimir/pull/9553 to r310.
> Backport #9553 to r310

- pkg/ingester/ingester.go
I'm troubleshooting some label names API requests and I don't understand if, for some reason, the `Ingester.LabelNames()` gets any matcher or not. In this PR I'm proposing to add a span log.
Example with no matchers:
Example with matchers:
N/A
> Log Ingester.LabelNames() matchers in traces

- pkg/ruler/api_test.go
This change extends an existing test to validate the ruler API endpoints only accept a single tenant ID, not multiple tenant IDs joined via `|` pipes.
N/A
> Validate only a single tenant ID passed to ruler API

- tools/kafkatool/dump.go
- tools/kafkatool/dump_test.go
- tools/kafkatool/main.go
- tools/kafkatool/util.go
As part of the replay speed work I created a tool to import and export data from Kafka.
This PR adds two commands
* `kafkatool dump import`: this dumps some records from a kafka partition to a file
* `kafkatool dump export`: this takes the same file format from `import` and imports them into another kafka partition
> Add `kafkatool dump`

- docs/sources/mimir/configure/configure-tsdb-block-upload.md
This PR updates "Configure TSDB block upload" article to mention possibilty to decrease TTL for cache results.
> Doc: mention possibility to reduce TTL for cached results when uploading blocks

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin/dashboards/alertmanager.libsonnet
We skip exposing per-tenant metrics when they are zero to save cardinality (see https://github.com/grafana/mimir/pull/9359), so these dashboards need a little tweak to show success counts.
> Mixin: Fix Alertmanager dashboards to cope with absent failed metrics.

- CHANGELOG.md
- operations/mimir/ingest-storage.libsonnet
A small improvement to our jsonnet to validate the Kafka client ID before an invalid one will get deployed.
Manually testing size limit:
```
Error: evaluating jsonnet: RUNTIME ERROR: the Kafka client ID must be less than 256 characters (actual: test=asdfkjahsdfkjahsdfkahsdkjfhaskjfhakjshdfkjasdhfjkashdkfjhdasasdfkjahsdfkjahsdfkahsdkjfhaskjfhakjshdfkjasdhfjkashdkfjhdasasdfkjahsdfkjahsdfkahsdkjfhaskjfhakjshdfkjasdhfjkashdkfjhdasasdfkjahsdfkjahsdfkahsdkjfhaskjfhakjshdfkjasdhfjkashdkfjhdasasdfkjahsdfkjahsdfkahsdkjfhaskjfhakjshdfkjasdhfjkashdkfjhdasasdfkjahsdfkjahsdfkahsdkjfhaskjfhakjshdfkjasdhfjkashdkfjhdas)
```
Manually testing invalid chars:
```
Error: evaluating jsonnet: RUNTIME ERROR: the Kafka client ID contains invalid characters (actual: test=!!!)
```
N/A
> Jsonnet: validate Kafka client ID

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/modules.txt
This includes the fix https://github.com/prometheus/prometheus/pull/15120, cherry-picked in https://github.com/grafana/mimir-prometheus/pull/711.
I don't think we typically mention any fixes that come with vendored prometheus in the changelog, thus I'm skipping one here.
Relates to https://github.com/grafana/mimir/issues/9382
> 2.14:  Update mimir-prometheus with version that fixes "RANGEHEAD: not found"

- pkg/storage/ingest/reader_test.go
related to #8691; this PR fixes the race on `testing.T.Log()` mentioned in that issue. We don't wait for the fetchers to exit and as a result they use the logger after the parent test has exited.
<details><summary>Data race</summary>
<p>
```
WARNING: DATA RACE
Read at 0x00c000035563 by goroutine 45240:
testing.(*common).logDepth()
/usr/local/go/src/testing/testing.go:1024 +0x504
testing.(*common).log()
/usr/local/go/src/testing/testing.go:1011 +0x7d
testing.(*common).Log()
/usr/local/go/src/testing/testing.go:1052 +0x55
testing.(*T).Log()
<autogenerated>:1 +0x4f
github.com/grafana/mimir/pkg/util/test.(*TestingLogger).Log()
/__w/mimir/mimir/pkg/util/test/logger.go:38 +0x1[77](https://github.com/grafana/mimir/actions/runs/11188014503/job/31106091993?pr=9515#step:8:78) …
```
> ingest storage: add cleanup to TestPartitionReader_ConsumeAtStartup

- pkg/storage/ingest/reader.go
Otherwise, this causes a memory leak as we leave lingering around the resources we used to catch up as quickly as possible as the ingester was starting.
> bugfix: Stop the current fetcher before replacing it

- integration/backward_compatibility.go
- renovate.json5
Following the [2.14.0 release](https://github.com/grafana/mimir/releases/tag/mimir-2.14.0), here we update the minimum supported set of versions.
Relates to https://github.com/grafana/mimir/issues/9382
> 2.14 Update minimum supported versions

- go.mod
- go.sum
- pkg/ruler/rulestore/bucketclient/bucket_client_test.go
- pkg/ruler/store_mock_test.go
- pkg/storage/tsdb/bucketcache/caching_bucket.go
- pkg/storage/tsdb/bucketcache/caching_bucket_config.go
- pkg/storage/tsdb/bucketcache/caching_bucket_test.go
- pkg/storage/tsdb/caching_config.go
- vendor/github.com/grafana/dskit/cache/mock.go
- vendor/github.com/grafana/dskit/ring/partition_instance_ring.go
- vendor/modules.txt
This change makes use of `add` operations for special "lock" cache entries to ensure that when items in object storage are mutated, stale results are not immediately stored to cache again.
It does this by `set`ing "lock" cache entries with a short TTL when an item in object storage is about to be mutated. This prevents reads of the item from caching the results afterwards. After the item is mutated in object storage, its cache entries (excluding the lock entries) are deleted. After the lock entries expire, reads of the item are allowed to store results in the cache again.
Part of #9386
Follow up to #9387
At a high level the way this works is:
* `CachingBucket.Upload` starts a mutation operation on some item in object storage and special "lock" keys get set in Memcached with a short …
> Add more robust cache invalidation to CachingBucket

- operations/mimir/ingester-automated-downscale-v2.libsonnet
It's valid to downscale ingesters to 0 replicas, so don't require the value to be > 0 for ingester downscaling v2. The check for `multi_zone_ingester_enabled` should be sufficient.
Fixes #N/A
> [jsonnet] Allow multi_zone_ingester_replicas = 0 for downscaling v2

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
- vendor/github.com/grafana/dskit/kv/memberlist/tcp_transport.go
- vendor/github.com/grafana/dskit/ring/ring.go
- vendor/modules.txt
Bumps dskit to [latest](https://github.com/grafana/dskit/commit/8e7752e59bab3299908ea0b278ba9db2a0800428); regenerate references. Includes dskit changes:
* https://github.com/grafana/dskit/pull/525
* https://github.com/grafana/dskit/pull/592
> Vendor dskit 8e7752e59bab

- CHANGELOG.md
- pkg/streamingpromql/aggregations/aggregations_test.go
- pkg/streamingpromql/aggregations/avg.go
- pkg/streamingpromql/aggregations/sum.go
- pkg/streamingpromql/functions/math.go
- pkg/streamingpromql/operators/instant_vector_selector.go
- pkg/streamingpromql/operators/instant_vector_selector_test.go
- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/operators/series_merging_test.go
- pkg/streamingpromql/operators/vector_vector_binary_operation.go
- pkg/streamingpromql/types/data.go
This PR is an iteration on https://github.com/grafana/mimir/pull/8677. It changes the behaviour of instant vector selectors to not return the same `FloatHistogram` instance for successive points if they all select the same histogram.
This preserves the main optimisation of #8677 (avoiding creating copies of histograms in `sum`) without the complexity and associated bugs of needing to ensure that shared `FloatHistogram` instances are modified safely.
For example, I just found yet another issue related to this that was introduced in https://github.com/grafana/mimir/pull/9507, where shared `FloatHistogram` instances could be left in the unused portion of the histogram slice [here](https://github.com/grafana/mimir/blob/14bc627207af501e2a2b9fad17d0ea22ff76039b/pkg/streamingpromql/operators/and_ …
> MQE: don't reuse `FloatHistogram` instances for successive points in instant vector selectors

- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/operators/series_merging_test.go
This PR backports the less risky fix from #9588 to r311.
(none)
> Backport part of #9588 to r311

- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/operators/series_merging_test.go
This PR backports the less risky fix from #9588 to r309.
(none)
> Backport part of #9588 to r309

- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/operators/series_merging_test.go
This PR backports the less risky fix from #9588 to r308.
(none)
> Backport part of #9588 to r308

- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/operators/series_merging_test.go
This PR backports the less risky fix from #9588 to r312.
(none)
> Backport part of #9588 to r312

- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/operators/series_merging_test.go
This PR backports the less risky fix from #9588 to r310.
(none)
> Backport part of #9588 to r310

- pkg/frontend/querymiddleware/astmapper/embedded.go
- pkg/frontend/querymiddleware/astmapper/instant_splitting.go
- pkg/frontend/querymiddleware/astmapper/instant_splitting_test.go
- pkg/frontend/querymiddleware/astmapper/sharding.go
- pkg/frontend/querymiddleware/astmapper/sharding_test.go
- pkg/frontend/querymiddleware/astmapper/subtree_folder.go
- pkg/frontend/querymiddleware/astmapper/subtree_folder_test.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/frontend/querymiddleware/sharded_queryable_test.go
Adds a separate map to embedded query struct in query sharding so that other kinds of sharding can use extra info without needing to extract it through regular expressions which are less reliable.
N/A
Not a user-facing change.
> Update embedded query in query sharding to include a separate map

- operations/helm/charts/mimir-distributed/CHANGELOG.md
This is a fixup to #9591 where I forgot to update the final version number in the Helm chart's changelog.
Relates to #https://github.com/grafana/mimir/issues/9382
> helm: Fix typo in 5.5.0 changelog

- RELEASE.md
- operations/helm/charts/mimir-distributed/RELEASE.md
I've noticed a couple of points, that were not obvious in the release process. This PR updates the instructions, adding those for future release engineers.
1. Add a reminder on how to merge the release branch back into `main`.
2. Add a reminder to update the Helm chart's changelog during final release.
3. Fix typos.
> Update release instructions

- go.mod
- go.sum
- pkg/util/log/log.go
- vendor/github.com/grafana/dskit/concurrency/worker.go
- vendor/github.com/grafana/dskit/spanlogger/spanlogger.go
- vendor/modules.txt
This PR upgrades dskit to include the following changes:
* https://github.com/grafana/dskit/pull/607
* https://github.com/grafana/dskit/pull/604
This PR also modifies Mimir's logging configuration to make use of the new `SpanLogger`-aware `Caller` implementation added in https://github.com/grafana/dskit/pull/604. This fixes the issue where logs emitted with a `SpanLogger` have `caller=spanlogger.go:xxx` rather than the true caller.
I don't think these changes are worthy of a changelog entry given they are largely useful for engineers working on Mimir rather than operators or users of Mimir.
(none)
- [n/a] …
> Upgrade dskit and fix incorrect caller information on logs emitted with `SpanLogger`

- pkg/streamingpromql/README.md
This PR expands the readme for `pkg/streamingpromql` to explain how `histogram.FloatHistogram` instances are reused and what should be done to ensure this happens correctly and safely.
I've also taken this opportunity to update references to "the streaming PromQL engine" to "MQE" in the readme.
I have not added a changelog entry given this is not a user-facing change.
(none)
> MQE: add docs about native histogram memory pooling and safety

- CHANGELOG.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/engine_concurrency_test.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/and_unless_binary_operation.go
- pkg/streamingpromql/operators/binary_operation.go
- pkg/streamingpromql/operators/or_binary_operation.go
- pkg/streamingpromql/operators/or_binary_operation_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
- pkg/streamingpromql/testdata/upstream/aggregators.test
- pkg/streamingpromql/testdata/upstream/operators.test
- pkg/streamingpromql/testdata/upstream/range_queries.test
- pkg/streamingpromql/testdata/upstream/selectors.test
- pkg/streamingpromql/testutils/utils.go
This PR adds support for the `or` binary operation to MQE.
In comparison to Prometheus' engine, MQE runs up to 70% faster and with up to 40% lower peak memory utilisation in our benchmarks: 
```
goos: darwin
goarch: arm64
│  Prometheus  │               Mimir                │
│    sec/op    │   sec/op     vs base               │
Query/a_1_or_b_1{l=~'.*[0-4]$'},_instant_query-10                        724.9µ ± 1%   728.9µ ± 2%        ~ (p=0.937 n=6)
Query/a_1_or_b_1{l=~'.*[0-4]$'},_range_query_with_100_steps-10           750.8µ ± 1%   727.2µ ± 1%   -3.15% (p=0.002 n=6)
Query/a_1_or_b_1{l=~'.*[0-4]$'},_range_query_with_1000_steps-10          1.328m ± 3%   1.188m ± 1%  -10.54% (p=0.002 n=6) …
```
> MQE: add support for `or`

- CHANGELOG.md
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
Use a single set of panels on the "Mimir / Writes" dashboard for ingest-storage and standard ingester autoscaling.
Regular autoscaling:
Ingest storage:
Fixes #N/A
> [dashboards] Unify ingester autoscaling panels on writes dashboard

- CHANGELOG.md
- tools/querytee/proxy_endpoint.go
- tools/querytee/proxy_endpoint_test.go
This PR changes the behaviour of query-tee to not compare responses for cancelled requests.
If an incoming request is cancelled, that cancellation is propagated to the backends, but this is racy and can result in different responses from each backend. For example, one may finish processing the request before it observes the cancellation, and the other may observe the cancellation and abort processing. This then results in a response comparison failure, but this isn't interesting.
(none)
> query-tee: don't bother comparing responses for cancelled requests

- operations/helm/charts/mimir-distributed/RELEASE.md
Update Helm chart release notes, mentioning the need to have a changelog entry about Mimir and GEM releases. This was brought up in https://github.com/grafana/mimir/pull/9611.
> mimir-distributed: update RELEASE instructions

- development/mimir-monolithic-mode/docker-compose.yml
- development/mimir-read-write-mode/docker-compose.jsonnet
- development/mimir-read-write-mode/docker-compose.yml
Modify docker compose ports to avoid clashes between different mimir networks, making it possible to run them in parallel.
N/A
Only modifying docker-compose networks for dev.
> Modify docker compose ports so it's possible to run multiple different mimir networks in parallel

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Improves the command in the runbook to reduce the time to identify the issue.
I ran the previous command and the output is:
```
$ kubectl get endpoints gossip-ring
NAME          ENDPOINTS                                                                 AGE
gossip-ring   10.200.100.64:7946,10.200.100.65:7946,10.200.101.201:7946 + 979 more...   462d
```
While the new one just prints:
```
$ kubectl get endpoints gossip-ring -ojson | jq '.subsets[].addresses | length'
982
```
> Improve MimirGossipMembersEndpointsOutOfSync runbook command

- pkg/blockbuilder/metrics.go
- pkg/blockbuilder/tsdb.go
This one addresses an old TODO in block-builder, by adding a metric, that counts the total number of discarded samples.
> blockbuilder: add metrics for number of discarded samples due to non-terminal failures in kafka record processing

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/api.go
- pkg/distributor/distributor.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push_test.go
Drop _experimental_ distributor flag `-distributor.direct-otlp-translation-enabled` (default: true), since direct OTLP translation has now been in production for ~5 months and has proven itself problem free. Less code 🎉
> distributor: Drop experimental flag for non-direct OTLP translation

- CHANGELOG.md
- integration/query_frontend_test.go
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
This pull request adds bytes-processed statistics to the existing `Server-Timing` HTTP header in the query frontend. It provides information about the total bytes processed by Mimir for a query request that passes through the query frontend. This information will be useful for assessing user behaviour and applying rate limiting when users run expensive, long-range Mimir queries. It will help mitigate slow performance or occasional downtime in Mimir.
None
> Return server-side total bytes processed statistics as a header through query frontend

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Exclude alerts from firing about cache "add" operations failing since this is expected during normal operation.
Related #9386
> mixin: Exclude cache "add" operations from alerting

- CHANGELOG.md
- pkg/frontend/querymiddleware/error_caching.go
- pkg/frontend/querymiddleware/error_caching_test.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/roundtrip.go
Use an implementation of the CacheKeyGenerator interface instead of bare function to generate cache keys for error caching. This allows downstream consumers (GEM) to inject custom logic for caching based on LBAC rules.
Related #9028
> Use CacheKeyGenerator implementation in error caching middleware

- integration/e2emimir/client.go
Add options to e2e mimir client for metadata endpoints, which is only possible now that client_golang is updated. This allows us to set the limit parameter for label names/values and series endpoints in e2e tests.
N/A
Not a user-facing change, only affects e2e tests.
> Add options to e2e mimir client for metadata endpoints

- CHANGELOG.md
- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This PR improves the comparison failure messages emitted by query-tee to include human-readable versions of timestamps.
(none)
> query-tee: include human-readable timestamps in comparison failure messages

- CHANGELOG.md
- pkg/ingester/active_series.go
When iterating over postings to build the response for `/active_series`, it's not guaranteed that all series references will still be valid at iteration time. We should not error when hitting a stale reference but just build a response that does not include the series referenced by the stale posting.
Thanks to @bboreham for pointing this out.
> Skip stale postings in `/active_series`

- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
This is related to a problem we have: high e2e latency when fetching at the head of the partition. The current theory is that WS introduces extra delay when requesting an offset which doesn't exist.
Currently, we have two sets of flags: one for startup and one for ongoing fetching. This PR enables us to have just a single configuration which determines the max concurrency. We will limit concurrency by never requesting an offset which doesn't exist.
I tested using the same concurrency and records-per-fetch settings for startup and ongoing fetching:
```
'ingest-storage.kafka.startup-fetch-concurrency': '12',  
'ingest-storage.kafka.startup-records-per-fetch': '1000',  
'ingest-storage.kafka.ongoing-fetch-concurrency': '12',  
'ingest-storage.kafka.ongoing-records-per-fetch': '1000',  
``` …
> kafka replay speed: dont send requests for higher than the high watermark

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/metamonitoring/grafana-agent.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-agent.yaml
This PR fixes a broken indentation in the `topologySpreadConstraints` inside the `GrafanaAgent` CRD, introduced in #8670. The CRD's specification is defined [here](https://github.com/grafana/agent/blob/69e7872651069b20cf9b8b67d9d210c1db245885/operations/agent-static-operator/crds/monitoring.grafana.com_grafanaagents.yaml). It requires the field to be the direct child of the `spec` field.
Fixes #9638
Notes: this needs to be backported to the 5.5 release branch.
> helm: fix broken topology spread constraints in metamonitoring's GrafanaAgent

- tools/querytee/response_comparator.go
- tools/querytee/response_comparator_test.go
This is a follow up of https://github.com/grafana/mimir/pull/9515
It fixes the case where if a series was completely removed from matrix and if the remaining part would match, we would still fail comparison saying there is a mismatch in series.
> query-tee: Filter samples for matrix before checking number of series

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/metamonitoring/grafana-agent.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-agent.yaml
Backport 0d3f52f74245d6ee1e20e5a6b8453000108b6543 from #9669
Relates to https://github.com/grafana/mimir/issues/9638
> [mimir-distributed-release-5.5] helm: fix broken topology spread constraints in metamonitoring's GrafanaAgent

- pkg/ingester/downscale_test.go
This change increases the polling timeout while waiting for ring state to converge after in the downscaling tests.
Increases polling timeout in flaky unit tests.
Fixes #9494
> Increase timeout in ingester downscaling tests

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin/alerts/alerts.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
Remove backwards compatibility support for `thanos_memcached_` prefixed metrics that were removed over a year ago in favor of `thanos_cache_` metrics.
N/A
> mixin: Remove support for removed cache metrics

- docs/proposals/reduce-multitenancy-cost.md
This PR adds a new proposal that aims to reducing the cost of multitenancy
'm currently working on a usecase where I would like to store the metrics across several thousand of small tenants. The number of tenants to store in a given cluster is 400k and each tenant is expected to have from 50 to 200 actives series at a scrape interval of 15sec, this would make 80M actives series with a replication factor=3 (aka RF).
Mimir is known to efficiently scale for both active series and sample/sec, 80M is expected to be within Mimir working range. However the number of tenants come with an overhead which impact the performance/resources consumption which makes this scenario hard to run in production.
I've run the following proof-of-concept:
* Mimir 2.13.0 is deployed on k8s with …
> Add proposal for reducing the cost of multitenancy

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/config.go
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions/common.go
- pkg/streamingpromql/functions/range_vectors.go
- pkg/streamingpromql/functions/rate_increase.go
- pkg/streamingpromql/operators/function_over_range_vector.go
- pkg/streamingpromql/operators/range_vector_selector.go
- pkg/streamingpromql/operators/subquery.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/subqueries.test
- pkg/streamingpromql/testdata/upstream/aggregators.test
- pkg/streamingpromql/testdata/upstream/at_modifier.test
- pkg/streamingpromql/testdata/upstream/functions.test
- pkg/streamingpromql/testdata/upstream/native_histograms.test
- pkg/streamingpromql/testdata/upstream/subquery.test
- pkg/streamingpromql/testing.go
- pkg/streamingpromql/types/data.go
- pkg/streamingpromql/types/fpoint_ring_buffer.go
- pkg/streamingpromql/types/hpoint_ring_buffer.go
- pkg/streamingpromql/types/operator.go
- pkg/streamingpromql/types/ring_buffer_test.go
This PR adds support for subqueries to MQE.
Our benchmarks show mild latency improvements in most cases over Prometheus' engine, and improvements in peak memory utilisation in most cases:
```
goos: darwin
goarch: arm64
│ Prometheus  │               Mimir                │
│   sec/op    │   sec/op     vs base               │
Query/sum_over_time(a_1[10m:3m]),_instant_query-10                         156.0µ ± 4%   152.3µ ± 4%   -2.36% (p=0.015 n=6)
Query/sum_over_time(a_1[10m:3m]),_range_query_with_100_steps-10            165.6µ ± 2%   154.6µ ± 1%   -6.63% (p=0.002 n=6)
Query/sum_over_time(a_1[10m:3m]),_range_query_with_1000_steps-10           250.2µ ± 1%   245.1µ ± 2%   -2.03% (p=0.041 n=6) …
```
> MQE: subqueries

- CHANGELOG.md
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/ours/literals.test
This PR adds support for unary addition to MQE.
Unary addition is a no-op, but it's valid PromQL, so we have to support it too 🤷 
(none)
> MQE: add support for unary addition

- CHANGELOG.md
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions/math.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours-only/native_histograms.test
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/aggregators.test
> MQE: Add support for round

- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
These changes bump the chart's version in preparation for the 5.5.1. Note, the changelog was already updated in #9670 (_because I'd forgotten that one does it separately_).
Relates to https://github.com/grafana/mimir/issues/9638
> helm: prepare release 5.5.1

- integration/ooo_ingestion_test.go
This is a follow up to https://github.com/grafana/mimir/pull/9567 - that PR spotted an issue where the OOO native histograms disabled error was not being mapped to a client error.
Prior to that PR, we already had an integration test that checked that trying to ingest OOO NH samples when the OOO NH flag was disabled returned a 400 and that test actually passed. The reason why it passed was that another 400 error being returned (out of bounds) - this is as `-blocks-storage.tsdb.block-ranges-period`, which is used to determine if a sample is out of bounds, is set to a very low value in tests. I've increased this value the out of bounds check passes and the OOO NH disabled error is hit instead.
Note that the test expectations haven't changed - we check OOO NH samples error with a 400, but the …
> Increase block-ranges-period for OOO native histogram integration test

- development/mimir-ingest-storage/config/datasource-mimir.yaml
- development/mimir-ingest-storage/config/grafana-agent.flow
- development/mimir-ingest-storage/config/mimir.yaml
- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
This is the fourth of series of PRs to upstream the code for improving Kafka replay speed in the ingester.
This PR makes several changes to development/mimir-ingest-storage
* deploys a jaeger instance to collect traces
* deploys ingester-zone-c-61. This ingester is totally separate from the other two zones. The idea is to be able to feed its partition with old data and test replay speed. That ingester doesn't ingest metrics from the cluster itself, so being down doesn't affect the cluster's query availability
* deploys 3 kafkas with RF=2 so that we can bring down brokers and test how our code reacts to leader reelections
* optinally enabled dlv debugging for the Mimir images
* configures ingesters to use concurrent fetching
> kafka replay speed: upstream local development environment

- docs/sources/helm-charts/mimir-distributed/configure/configure-redis-cache.md
This PR adds a note to https://grafana.com/docs/helm-charts/mimir-distributed/latest/configure/configure-redis-cache/ to note the Redis caching is deprecated and set for removal in a future release.
See https://raintank-corp.slack.com/archives/C029912SXT8/p1729138524010979 for context.
Fixes https://github.com/grafana/mimir-squad/issues/2552
> docs: adds deprecation notice for redis caching

- CHANGELOG.md
- tools/querytee/proxy_endpoint.go
- tools/querytee/proxy_endpoint_test.go
Reverts grafana/mimir#9640
This change was not quite right: the request context will be cancelled as soon as query-tee sends the response from the preferred backend.
I'll follow this up with a fix later, but for now, I'd like to revert this until I have time to fix it.
> Revert "query-tee: don't bother comparing responses for cancelled requests"

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-compactor.json
- operations/mimir-mixin-compiled/dashboards/mimir-compactor.json
- operations/mimir-mixin/dashboards/compactor.libsonnet
This helps identify when the compactor is falling behind
> dashboards: add block max time delta panel
