- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/push_test.go
- pkg/util/requestbuffers.go
- pkg/util/requestbuffers_test.go
- tools/trafficdump/parser.go
This PR adapts the distributor code to remove the bucketed pool implementation in `util.RequestBuffers` when a maximum pool buffer size is defined.
Instead, the code for the default `util.bufferPool` type has been adapted to allow defining a maximum pool capacity.
The reason is that with the current implementatiom, bucketed buffers are used to decompress the incoming request acquiring the buffer based on the specified request size. However, since these buffers eventually end up being resized during the decompression process, they can later end up in a different bucket when returned to the pool, thus preventing subsequent reuse and leading to higher GC pressure.
This behavior has been observed in our dev environments when enabling the config parameter …
> distributor: fix pool buffer reuse logic when `distributor.max-request-pool-buffer-size` is set

- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards.libsonnet
- operations/mimir-mixin/dashboards/block-builder.libsonnet
The PR is the first iteration of a new experimental dashboard, with basic monitoring for the block-builder. The dashboard is disabled by default. It must be enabled via the `$._config.block_builder_enabled` config in jsonnet.
> mimir-mixin: add dashboard for experimental block-builder

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- development/mimir-microservices-mode/config/mimir.yaml
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/v1/frontend.go
- pkg/scheduler/queue/multi_queuing_algorithm_tree_queue_benchmark_test.go
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_broker.go
- pkg/scheduler/queue/queue_broker_test.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/scheduler.go
This PR removes the experimental `prioritize-query-components` flag, which was introduced in https://github.com/grafana/mimir/pull/9016. The only code path that remains will be the one introduced by this flag; query component will take priority over tenant fairness.
> Remove prioritize-query-components flag

- development/mimir-microservices-mode/config/prometheus.yaml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
Added continuous test to the docker compose development environment for ease/speed of development on it.
I also made the choice to remove load-generator being included by default - though I am not married to this choice, I use this development env a lot and always turn off the load generator.
Reasoning for this change being:
1. the continuous test will also create read and write load, though its read load is not as continuous as load-gen.
2. whichever of the prometheus/grafana-agent/otel-collector components is chosen also creates write load
3. continuous-test is a main supported part of mimir whereas the load-gen is a separate personal repo and container
4. load-gen has some noisy errors because it doesn't recover from gaps in writes as well as continuous-test
5. load-gen can still be …
> development: mimir-microservices-mode: add continuous-test

- CHANGELOG.md
- pkg/streamingpromql/operators/selectors/instant_vector_selector.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector_test.go
- pkg/streamingpromql/testdata/ours/selectors.test
This PR is a small optimisation for instant vector selectors in MQE. 
Previously, instant vector selectors would always use a slice with capacity for the number of steps in the range query.
However, if a series only has samples beginning part-way through the query range, this is wasteful: we know the series can't have more samples than remain in the query range, so we don't need such a big slice.
(none)
> MQE: create slices with capacity for number of steps remaining, not all possible steps

- pkg/distributor/query.go
While the write path has been carefully crafted to make sure that we don't keep references to the strings backed by arrays with data from grpc stream (because it would cause a memory leak), this doesn't seem to be the case in the query path, where some tests started failing after we started to reuse those backing arrays through the usage of memory buffers implemented in the new gRPC library.
This change reverts the buffer freeing, means that it won't be recycled (and will be garbage collected) to ensure data correctness, while we investigate where the data references are kept.
Follow up on https://github.com/grafana/mimir/pull/9401
> Don't free buffers after reading query stream

- CHANGELOG.md
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
Currently the querier expects to run queries against two storages only:
- Ingesters
- Store gateways
The queriers know when each queryable was applicable and queries the appropriate queryables.
This commmit introduces the TimeRangeQueryable struct which is a wrapper around Queryable. It ties the Queryable to the logic that deems it applicable to an incoming query.
This, in conjunction with the newly-added AdditionalStorageQueryables property on the Mimir struct, enables the querier to query optionally against more storages than just the ingesters and store gateways in the future.
N/A
> Allow querying against an expandable number of storages

- CHANGELOG.md
- operations/mimir-tests/test-multi-zone-etcd-generated.yaml
- operations/mimir-tests/test-multi-zone-etcd.jsonnet
- operations/mimir/mimir.libsonnet
- operations/mimir/multi-zone-etcd.libsonnet
In this PR I'm adding an config option to configure etcd pods to be scheduled multi-AZ. Details about how it works in the code comment.
N/A
> Jsonnet: add option to deploy etcd multi-AZ

- pkg/ingester/circuitbreaker.go
- pkg/ingester/circuitbreaker_test.go
- pkg/ingester/ingester_test.go
Add a `deactivate()` method to the ingester circuit breakers to allow them to be disabled and re-enabled dynamically.
> Ingester circuit breaker deactivate() function

- development/mimir-microservices-mode/config/mimir.yaml
- pkg/continuoustest/manager.go
Converts the timestamps fed into the runner to be in UTC, since all other timestamps encountered when attaching a breakpoint are in UTC.
Also expands OOO window config so the catchup writes from read-write continuous test don't all fail when you bring it up when metamonitoring is on.
> continuous-test: make debugging easier in docker compose env

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/exemplar.go
- vendor/github.com/prometheus/prometheus/tsdb/head_append.go
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Update mimir-prometheus to [5710f65f1444](https://github.com/grafana/mimir-prometheus/tree/5710f65f1444508a2d03d46e2db648ef2fa8d71f), brings in race condition fixes: 
* https://github.com/grafana/mimir-prometheus/pull/729
* https://github.com/grafana/mimir-prometheus/pull/730
* https://github.com/grafana/mimir-prometheus/pull/731
> Update mimir-prometheus to 5710f65f1444

- go.mod
- go.sum
- vendor/github.com/thanos-io/objstore/CHANGELOG.md
- vendor/github.com/thanos-io/objstore/objstore.go
- vendor/modules.txt
Specifically, pulls in https://github.com/thanos-io/objstore/pull/153 which fixes timing for get operations.
N/A
> chore: Update to latest thanos-io/objstore commit

- pkg/distributor/distributor_test.go
This avoids some conversions to and from Labels.  The motivation comes from testing with `-tags dedupelabels`, where comparisons are more complicated, but it seems overall better to match the data structures in tests against the real code.
> distributor tests: use LabelAdapters more, to match code being tested

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/modules.txt
Updating mimir-prometheus to get a couple of improvements to `PostingsForMatchersCache`:
- https://github.com/grafana/mimir-prometheus/pull/733
- https://github.com/grafana/mimir-prometheus/pull/734
N/A
> Update mimir-prometheus to get PostingsForMatchersCache improvements

- pkg/distributor/query.go
In `Distributor.queryIngesterStream`, free gRPC buffers when an error occurs in the `queryIngester` closure that gets passed to `ring.DoMultiUntilQuorumWithoutSuccessfulContextCancellation`. No attempt is made to free the buffers though if querying is successful, as the combined query response should retain references to said buffers. I add a comment for future reference as to why we don't free buffers in the success case.
See #9721 for background, as it reverts the `Distributor.queryIngesterStream` gRPC buffer freeing introduced in #9401 (due to race conditions essentially, as the combined query response retains gRPC buffer references).
I've run the `TestBothEnginesReturnSameResultsForBenchmarkQueries` tests in pkg/streamingpromql/benchmarks with race detection enabled, and no problems …
> Distributor.queryIngesterStream: Free gRPC buffers upon error

- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
This PR adds new alerts, that warns about possible scenarios, where the `block-builder` behaves abnormally. See the updated runbook for the details.
Note that I put the alert as warnings for now, since block-builder is still in its early experimental phase.
> blockbuilder: Basic alerts

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/enterprise-https-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/gateway-enterprise-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/gateway-nginx-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/keda-autoscaling-global-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/keda-autoscaling-metamonitoring-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/openshift-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/scheduler-name-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-enterprise-k8s-1.25-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-enterprise-legacy-label-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-ingress-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-oss-topology-spread-constraints-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-requests-and-limits-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-ruler-dedicated-query-path-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-vault-agent-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
Same as #9195, but now also for AlertManager. Fixes mimir chart showing constest diff due to server side changes that k8s makes but are not in the chart itself.
> fix alertmanager sts showing diff in argocd

- pkg/frontend/v2/frontend.go
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/frontend/v2/frontend_test.go
Instead of breaking the scheduler connection for malformed queries and eventually sending 500, instead send 400 and do not break the scheduler connection.
This is another version of what https://github.com/grafana/mimir/pull/9782 was trying to do.
> query-frontend: Do not break scheduler connection on malformed queries

- integration/querier_remote_read_test.go
- pkg/querier/batch/chunk_test.go
- pkg/querier/block_test.go
- pkg/querier/distributor_queryable_test.go
- pkg/querier/querier_test.go
- pkg/util/test/histogram.go
Do not ignore native histogram counter reset hint in tests
Ignoring the hint was convenient in the past, but we want to add a test case where the hint is actually calculated wrong. This commit simply updates the current tests to specify the expected output.
Related to #7175 
> test(histograms): do not ignore native histogram counter reset hint in tests

- CHANGELOG.md
- pkg/compactor/bucket_compactor.go
- pkg/storage/tsdb/block/index.go
- pkg/storage/tsdb/block/index_test.go
- tools/splitblocks/README.md
- tools/splitblocks/main.go
- tools/splitblocks/main_test.go
In #9517, a splitblocks tool was created to split blocks by time. But the tool doesn't rewrite chunks that are partially outside the time, causing block validation to complain.
This PR:
- Updates the splitblocks tool to rewrite chunks that are clamped to the block's time window
- Adds a `--verify-blocks` option to the splitblocks tool that runs block validation after each block is split
- Makes chunk "clamping" available for other block repair uses, though this PR doesn't enable it anywhere else for now (for example, in the compactor's usage of block repair)
- Split a 48h block into 2h blocks and ran a sample counting script on all of them to confirm the number of samples in the split blocks equals the total from the original.
- Confirmed a 48h block split into 2h blocks passes …
> Update splitblocks tool to handle partially outside chunks

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
Updated `KubePersistentVolumeFillingUp` runbook, including a sample command to debug the distroless image.
N/A
> Docs: update KubePersistentVolumeFillingUp runbook

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
This would previously panic after the query was closed
> MQE: Fix handling of string results

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Update mimir-prometheus (from main) to get the cherry-pick of https://github.com/prometheus/prometheus/pull/15242
N/A
> Improve lock contention affecting read and write latencies during TSDB head compaction (cherry-pick Prometheus PR 15242)

- CHANGELOG.md
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
This makes sure that when a label value fails validation due to invalid UTF-8 characters we don't return these invalid characters in the error, because including them can break the rendering of the error that should be returned.
> fix marshaling error on invalid label value

- CHANGELOG.md
- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Bring in https://github.com/grafana/mimir-prometheus/pull/740, fixing performance issue due to too much allocation.
> Update mimir-prometheus to revert MemPostings issue

- CHANGELOG.md
- development/mimir-ingest-storage/config/mimir.yaml
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
Few days ago, @gotjosh and I discovered that when the Kafka concurrent fetch is enabled (either during startup only or startup + ongoing) the Kafka client buffers records anyway internally. This is done automatically as soon as you configure `kgo.ConsumePartitions()`.
This is not a critical issue, but it's annoying because of a couple of reasons. When ongoing concurrency is enabled, these records buffered by the Kafka client will stay there forever. They consume a bit of memory (not much), and they also cause the `cortex_ingest_storage_reader_buffered_fetch_records_total` to continuously report these buffered records, like if some records are never processed by the ingester (these buffered records are not processed, but we don't even want to process them because when concurrent fetch is …
> Do not buffer records in the Kafka client when fetch concurrency is enabled

- CHANGELOG.md
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
As discussed [here](https://github.com/grafana/mimir/pull/9838#discussion_r1832391875), in this PR I'm fixing the ordering of call to `fetcher.Stop()`. As of today, it's not a real bug because when `switchToOngoingFetcher()` is called multiple times, the 2nd time instance of `fetcher` is `PartitionReader` and its `Stop()` implementation is empty, but this could lead to future bugs.
I've also took the opportunity to improve the unit tests modified in https://github.com/grafana/mimir/pull/9838 to add one more variant: "with startup and ongoing concurrency (different settings)".
N/A
> Fix ordering of call to fetcher.Stop() and improve unit tests

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
- Changes the type for the `alertmanager.max-grafana-state-size-bytes` and `alertmanager.max-grafana-config-size-bytes` flags / overrides to `dskit` [flagext.Bytes](https://github.com/grafana/dskit/blob/main/flagext/bytes.go#L13)
- This fixes the issue we have with big ints being converted to scientific notation, but also provides better readability
- We're aware this is a breaking change, check the linked deployment tools PR for how we're planning to release this
> use dskit flagext.Bytes for sizes

- docs/sources/helm-charts/mimir-distributed/configure/configure-native-histograms-ingestion.md
- docs/sources/mimir/configure/configure-native-histograms-ingestion.md
- docs/sources/mimir/send/native-histograms/_index.md
- docs/sources/mimir/send/otel-exponential-histograms/_index.md
- docs/sources/mimir/visualize/native-histograms/_index.md
Improve the documentation.
Clarify the status of the feature.
N/A
> docs: clarify native histograms visualization and mark as experimental

- CHANGELOG.md
- go.mod
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/util/http.go
This PR adds support for `lz4` algorithm to the distributor's OTLP endpoint.
Fixes #9259
> Add support for lz4 algorithm to OTLP endpoint

- CHANGELOG.md
- pkg/streamingpromql/operators/functions/common.go
- pkg/streamingpromql/operators/functions/range_vectors.go
- pkg/streamingpromql/operators/functions/rate_increase.go
- pkg/streamingpromql/operators/selectors/range_vector_selector.go
- pkg/streamingpromql/operators/subquery.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/data.go
- pkg/streamingpromql/types/fpoint_ring_buffer.go
- pkg/streamingpromql/types/hpoint_ring_buffer.go
- pkg/streamingpromql/types/limiting_pool.go
- pkg/streamingpromql/types/operator.go
- pkg/streamingpromql/types/pool.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/pool/bucketed_pool.go
This PR is a follow-up PR to https://github.com/grafana/mimir/pull/9664.
This PR improves the performance of subqueries when the parent query is a range query with many steps.
It does this by changing the behaviour of the ring buffer implementations to search forwards through the buffer to find the end of the range when a subquery is being evaluated, rather than backwards. Searching backwards makes sense for range vector selectors, where there is expected to only be one point, if any, at the end of the buffer outside the range, but for subqueries in range queries it is expected that there will be many points at the end of the buffer outside the range, so it is usually faster to search from the beginning of the buffer.
I'd suggest reviewing each commit separately, as each builds on the …
> MQE: improve performance of subqueries when the parent query is a range query with many steps

- CHANGELOG.md
- pkg/streamingpromql/operators/binops/or_binary_operation.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR fixes a bug in MQE's implementation of `or` where it could return incorrect results if both sides contained series with the same labels, and the series on the left side did not have a value for all time steps.
For example, in the expression `min(series_1) or min(series_2)`, both sides have a single series with no labels. Previously, `or` would have returned two series with the labels `{}`, rather than correctly returning a single `{}` series.
I've opted to use `DeduplicateAndMerge` here, as it's the simplest solution that is already well-tested. A more sophisticated option would be to modify `OrBinaryOperation` to handle this case itself, but this would come at the cost of increased complexity, and it would largely replicate the behaviour and logic of `DeduplicateAndMerge`.
The …
> MQE: fix `or` where both sides have series with the same labels

- CHANGELOG.md
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
There are two errors returned and we were only handling one of them.
> ingester: handle errors when getting topic ID

- renovate.json5
Updates the renovate config to include bumping changes to the small node project used to take screenshots of dashboards. The config validates but I'm not a renovate expert.
N/A
> Adding renovate config for the mimir-mixin-tools/screenshots node project

- pkg/storage/ingest/util.go
- pkg/storage/ingest/util_test.go
This is a minor thing, but could be useful to get insights if partitions auto-creation fail. Previously we were only logging an error if the partitions creation request fail, but it could also succeed and contain an error in the response. Now we do log the error in the latter case too.
N/A
> Log an error if the Kafka partitions auto-creation fail with an error in the Kafka response

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Cherry-picking https://github.com/prometheus/prometheus/pull/15242 into the 2.14 release.
This is the follow-up to the backport https://github.com/grafana/mimir-prometheus/pull/747
> [release-2.14] Cherry-pick Prometheus PR 15242

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
The alert `MimirIngesterStuckProcessingRecordsFromKafka` relied on the metric `cortex_ingest_storage_reader_buffered_fetch_records_total ` provided by the Kafka client to identify wether we had stuck buffers or not.
Now that we've implemented concurrent fetching from Kafka and bypass the client's polling function we needed an equivalent metric when using concurrent fetching. This PR does that; In addition to that - the metric also takes the client's buffered records In case we do use a mixture of non-concurrent fetching and concurrent fetching.
N/A
> fix `MimirIngesterStuckProcessingRecordsFromKafka`

- CHANGELOG.md
- development/mimir-microservices-mode/config/mimir_override.yaml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
This PR adds the initialization of the local cache of the ha_tracker
The investigation if this is needed has been done in a separate PR https://github.com/grafana/mimir/pull/9853
Check [conclusion](https://github.com/grafana/mimir/pull/9853#issue-2643760579) for TLDR
Relates with: https://github.com/grafana/mimir/issues/5796
> fix(distributor-ha): init cache on startup

- pkg/querier/blocks_finder_bucket_index.go
- pkg/storage/tsdb/bucketindex/loader.go
- pkg/storegateway/bucket_index_metadata_fetcher.go
- pkg/storegateway/bucket_index_metadata_fetcher_test.go
Adds logging of bucket index timestamps (updatedAt) after they're fetched, in queriers and store gateways. This allows better understanding of which exact bucket index queriers and store gateways are working off of.
> Log fetched bucket index timestamps

- CHANGELOG.md
- pkg/compactor/blocks_cleaner.go
- pkg/compactor/blocks_cleaner_test.go
- pkg/compactor/compactor.go
- pkg/storage/tsdb/bucketindex/storage_test.go
- pkg/storage/tsdb/bucketindex/updater.go
- pkg/storage/tsdb/bucketindex/updater_test.go
- pkg/storegateway/gateway_test.go
- pkg/storegateway/metadata_fetcher_filters_test.go
* compactor: concurrently get deletion marks for blocks
With a lot of blocks churn (for example a lot of OOO blocks) getting the deletion marks for newly discovered blocks can take a long time (13 minutes).
This PR introduces changes the bucket index updater to request 16 deletions marks concurrently (same as the number of block deleted in parallel).
Co-authored-by: Ganesh Vernekar <ganeshvern@gmail.com>
(cherry picked from commit 94255ac58ccfb68a82963d45ba912e17f3c784d0, #9881)
> [r314] compactor: concurrently get deletion marks for blocks

- pkg/ingester/circuitbreaker_test.go
This test would sometimes fail:
```
--- FAIL: TestIngester_Push_CircuitBreaker_DeadlineExceeded (2.00s)
--- FAIL: TestIngester_Push_CircuitBreaker_DeadlineExceeded/test_slow_push_with_initial_delay_disabled (2.00s)
circuitbreaker_test.go:1015: 
Error Trace:	/go/src/github.com/grafana/mimir/pkg/ingester/circuitbreaker_test.go:1015
Error:      	Received unexpected error:
circuit breaker open on push request type with remaining delay 9.999979667s
Test:       	TestIngester_Push_CircuitBreaker_DeadlineExceeded/test_slow_push_with_initial_delay_disabled
```
The test assumes that it will execute one successful request, and then 4 failing requests. However, sometimes the first request would take longer to execute than the configured `100ms` timeout, and the circuit breaker would close after the …
> Fix flaky TestIngester_Push_CircuitBreaker_DeadlineExceeded test

- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
I was looking at the flaky test reported in https://github.com/grafana/mimir/pull/9891. I actually reproduce it enabling the logging (and also increasing the number of records produced/consumed by the test). I personally think the main problem is that we log 'skipped records because already returned' for every single record, which looks a bit too much to me in case there are many skipped records.
In this PR I propose to just log the summary of all skipped records, logging the count, and the min/max offsets. With this change I can't get the test being flaky anymore. I also measured `'skipped records because already returned'()` timing and now it's in the order of microserconds when running the tests locally (with log enabled).
N/A
> Reduce 'skipped records because already returned' log frequency

- operations/mimir-mixin/dashboards/writes.libsonnet
With https://github.com/grafana/mimir/pull/9654, the `cortex_ingest_storage_reader_requests_total` metric has changed meaning. When concurrent fetch is enabled, it's no more the number of records / write requests processed, but number of write request **batches** processed.
This caused some confusion to me when we recently rolled out concurrent fetch and I observed this change at the time of the rollout:
In this PR I propose to change the panel title / description to something which is more accurate to the current state of the metric tracking.
N/A
> Dashboards: clarify write requests processed from Kafka

- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
This upstreams a config change we have deployed internally at Grafana Labs.
> [Ingest Storage] Update default ReplicaTemplate label selector

- operations/mimir-tests/test-new-resource-scaled-object.jsonnet
- operations/mimir/autoscaling.libsonnet
I have an use case where I need to add extra matchers to metrics used by `newResourceScaledObject()`. In this PR I'm replacing `pod_regex` with a generic `extra_matchers` to make it more flexible.
N/A
> Jsonnet: change newResourceScaledObject() signature to allow to pass extra_matchers instead of pod_regex

- pkg/storage/tsdb/bucketindex/loader.go
Adds logging of querier bucket index updates so we can inspect exactly which bucket index version/timestamp a particular querier is working off of. This can help investigate situations where queriers and store gateways appear to be working off of different bucket indices.
Using DEBUG level since I suspect this might be noisy.
> Log querier bucket index updates

- docs/sources/mimir/send/native-histograms/_index.md
This PR updates the `scrape_native_histograms` setting to `always_scrape_native_histograms` at https://grafana.com/docs/mimir/latest/send/native-histograms/. This update is based on a [change in Prometheus version 3.0](https://github.com/prometheus/prometheus/pull/15178).
Fixes https://github.com/grafana/mimir/issues/9695
> Docs: rename scrape_native_histograms setting based on prometheus update

- pkg/scheduler/queue/queue_broker.go
Fixes unneeded allocation seen during recent query-scheduler issues - this line was responsible for 1.3% of all allocations profiled.
This is a minor optimization compared to the [main fix](https://github.com/grafana/mimir/pull/9888), but the extra allocations contribute to main thread CPU usage as well as garbage collection pressure.
> query scheduler: optimize queueBroker.makeQueuePath to remove double slice allocation

- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
I realized that trimming `fetchWant`s can end up discarding offsets in extreme circumstances.
If the fetchWant is so big that its size would exceed 2GiB, then we trim it. We trim it by reducing the end offset. The idea is that the next fetchWant will pick up from where this one left off.
We trim the `fetchWant` in `UpdateBytesPerRecord` too. `UpdateBytesPerRecord` can be invoked in `concurrentFEtchers.run` after the `fetchWant` is dispatched. In that case the next `fetchWant` would have already been calculated. And we would end up with a gap.
It's hard to tell, but it's very unlikely. To reach 2GiB we would have needed to have the estimation for bytes per record be 2 MiB (with 1000 records per fetch). While these large records are possible, they should be rare and our rolling average …
> kafka replay speed: don't trim fetchWants

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/query.go
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/util/limiter/query_limiter.go
- pkg/util/limiter/query_limiter_test.go
Previously, queriers would hold two copies of the labels for each series from a store-gateway: once as a `[]mimirpb.LabelAdapter` (in the `storepb.StreamingSeries` held by `blockStreamingQuerierSeriesSet`) and again as a `labels.Labels` (passed to `newBlockStreamingQuerierSeries`). This means that queries that select many series use twice as much memory as they need to for labels, which can be problematic for queries that select many series with many labels.
This PR modifies the behaviour of queriers to only hold the labels as a `labels.Labels` instance.
It also fixes the issue where `[]mimirpb.LabelAdapter` instances are converted to `labels.Labels` multiple times when streaming chunks: once when applying the series limiter, and again for use when iterating through series. Multiple …
> Don't hold labels from store-gateways in two forms, and don't convert them multiple times

- go.mod
- go.sum
- pkg/distributor/ha_tracker_test.go
- vendor/github.com/grafana/dskit/kv/mock.go
- vendor/modules.txt
This PR updates the `TestHATrackerCacheSyncOnStart` to use the `MockCountingClient` that was introduced in dskit ([Ref](https://github.com/grafana/dskit/pull/618)). This will allow us to better test if the sync happened during the ha_tracker creation
Follow up of this: #9826 
Improve testing scenarios
> tests(distributor): improve checks during ha_tracker sync cache on startup 

- CHANGELOG.md
- docs/proposals/reduce-multitenancy-cost.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/ingester/metrics.go
This change was made in order to match err-mimir-sample-timestamp-too-old event logs
This PR replaces `cortex_discarded_samples_total` label from `sample-out-of-bounds` to `sample-timestamp-too-old`.
Fixes #5970
> change: replace cortex_discarded_samples_total label to sample-timestamp-too-old

- pkg/storage/ingest/fetcher_test.go
There's a race between produceCtx being cancelled and producing the record with it. So we increment the number of produced records, but then producing the record fails. In the end we expect to receive that record because we counted it.
This is the error that I saw in CI
```
--- FAIL: TestConcurrentFetchers (1.22s)
--- FAIL: TestConcurrentFetchers/update_concurrency_with_continuous_production (10.01s)
logging.go:33: level info component kafka_client msg immediate metadata update triggered why from user ForceMetadataRefresh
logging.go:33: level info component kafka_client msg producing to a new topic for the first time, fetching metadata to learn its partitions topic test-topic
logging.go:33: level info component kafka_client msg immediate metadata update triggered why forced load because …
```
> ingest: fix flaky TestConcurrentFetchers

- CHANGELOG.md
- pkg/mimir/modules.go
Removes the "invisible module" mark from `memberlist-kv` so it can be ran alone with `-target=memberlist-kv` and can be used for running seed memberlist nodes.
> Make MemberlistKV module targetable

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Updates the `MimirBucketIndexNotUpdated` runbook to more strongly hint at considering the mitigations when a tenant is experiencing consistency check failures at the same time.
> Update MimirBucketIndexNotUpdated runbook

- CHANGELOG.md
- tools/kafkatool/dump.go
I needed to print the write requests from a Kafka records dump. Adding a command to `kafkatool` to do it.
N/A
> kafkatool: add 'dump print' command

- operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
- operations/mimir-tests/test-single-to-multi-zone-distributor-migration.jsonnet
- operations/mimir/autoscaling.libsonnet
- operations/mimir/multi-zone-distributor.libsonnet
In #9548 we added support to deploy distributors in multi availability zones (AZ). One of the features of that PR was that deploying distributors in multi-AZ implicitly implies that they cannot be deployed in a single-AZ, and vice versa. 
This PR removes that constraint, and allow distributors to be deployed in both modes. This would be needed for migration from single to multi-AZ.
> Jsonnet: add support to deploy distributors in both single and multi AZ

- development/mimir-ingest-storage/config/mimir.yaml
- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/reader.go
Adds an alert and metrics to detect when we have bugs.
> kafka replay speed: add alert for when we miss records in Kafka

- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/model_extra_test.go
- pkg/frontend/querymiddleware/prune_test.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/stats_test.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/querier/querier_test.go
This PR includes the changes to querier and query-frontend tests to mirror the left-open interval change in Prometheus 3.
(none)
> Querier and query-frontend test changes for Prometheus 3 upgrade

- docs/sources/mimir/manage/mimir-runbooks/_index.md
This PR addresses one of the PIR action items related to PersistentVolume resizing. It introduces an additional step to the process for store-gateways
Addresses: https://github.com/grafana/pir-actions/issues/252
> docs: update KubePersistentVolumeFillingUp with prerequisite for store-gateways

- CHANGELOG.md
- pkg/storage/ingest/config.go
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/storage/ingest/writer_test.go
This PR fixed a data loss bug in the experimental ingest storage when a Kafka Fetch is split into multiple requests and some of them return an error.
**The bug**
Due to the `fetchResult.Merge()` we call in `concurrentFetchers.run()` we can merge records in a `kgo.Fetch` that also contains a `Err` (so it both has `Err` and some records). When this fetch is returned by `PollFetches()` to `PartitionReader`,  `PartitionReader` will filter out everything because of the `Err` set. We don't expect to both have an `Err` and some records set in the same `kgo.Fetch`, so I think `PartitionReader` is doing the right thing, and `concurrentFetchers` shouldn't mix `Err` with records.
**The fix**
A part from some small improvements / comments / new unit tests here and there, in this PR I address the …
> Fix data loss bug in the experimental ingest storage when a Kafka Fetch is split into multiple requests and some of them return an error

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/block.go
- vendor/github.com/prometheus/prometheus/tsdb/head_read.go
- vendor/github.com/prometheus/prometheus/tsdb/index/index.go
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/github.com/prometheus/prometheus/tsdb/ooo_head_read.go
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/github.com/prometheus/prometheus/tsdb/querier.go
- vendor/modules.txt
Cherry-pick query optimization (mainly for queries involving empty or non-empty labels) https://github.com/prometheus/prometheus/pull/14144. See Prometheus PR for benchmark stats.
> Optimize queries for (non-)empty labels

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-oss-logical-multizone-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/tests/test-oss-multizone-values-generated/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
The issue #4724 was fixed by configuring the idle timeout for the Alertmanager in #8192, however the fix was unfortunately included in the above else statement. This PR ensures the timeout is also set when using zone aware Alertmanager.
Fixes #4724
> helm: fix zone aware alertmanager http idle timeout

- pkg/storage/ingest/reader_test.go
In https://github.com/grafana/mimir/pull/9963 I've introduced `TestPartitionReader_ShouldNotMissRecordsIfFetchRequestContainPartialFailuresWithConcurrentFetcherIsUsed`. After merging, I realised locally that sometimes the test hang.
I spent 1h debugging it and it's related to the case the kfake control return an `error` (not a response with error). I'm quite sure the issue has not been introduced with the changes in https://github.com/grafana/mimir/pull/9963, but I still haven't understood if the issue is in kfake (can't find a proof there) or an issue in the franz-go library.
I need more time to further investigate it. In the meanwhile I suggest to remove that type of error: the error still make sense due to the error injected by "Simulate a 10% Kafka error rate".
N/A
> Fix TestPartitionReader_ShouldNotMissRecordsIfFetchRequestContainPartialFailuresWithConcurrentFetcherIsUsed flakyness

- CHANGELOG.md
- pkg/storage/ingest/reader_test.go
This PR is a follow up of https://github.com/grafana/mimir/pull/9963. In this PR I'm adding an extra test: `TestPartitionReader_ShouldNotMissRecordsIfKafkaReturnsAFetchBothWithAnErrorAndSomeRecords`
N/A
> Add TestPartitionReader_ShouldNotMissRecordsIfKafkaReturnsAFetchBothWithAnErrorAndSomeRecords

- pkg/storage/ingest/fetcher_test.go
Some of the tests assume that we'd fetch all produced records in one go. The Kafka protocol doesn't guarantee that and sometimes kfake also returns less than that. This means that sometimes the tests would finish early before we've fetched all records.
This PR introduced `logPollFetches` which loops over `fetchers.PollFetches` multiple times until a timeout or until we fetch the expected number of records.
I also changed all places which had this assumption and all places which already did some form of log polling.
I set the timeout to 2s because of the MinBytesMaxWait of 1s in tests ([code](https://github.com/grafana/mimir/blob/96c92c99ef5599d4507c2aa9f6d7ddf42d5beec2/pkg/storage/ingest/fetcher_test.go#L1373)):
* fetcher receives 1 record (1st request)
* fetcher sends the `fetchResult` …
> ingest: add long polling to TestConcurrentFetchers

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/modules.txt
NOTE: pointed to r315 branch
Brings in https://github.com/grafana/mimir-prometheus/pull/751 https://github.com/grafana/mimir-prometheus/pull/763
I will add the flag to enable this feature in a follow up PR
> Update mimir-prometheus with a fix

- CHANGELOG.md
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
follow-up to #9921 
The idea is to catch gaps as close as possible to where we consume fetches. With the previous alert we wouldn't have caught the bug fixed in #9963
> ingest: move missed record tracking to PartitionReader

- development/mimir-monolithic-mode/config/otel-collector-otlp-push-config.yaml
- development/mimir-monolithic-mode/config/otel-collector-remote-write-config.yaml
This allows the otel-collector containers available in monolithic development mode to write basic logs to the screen. With this, you begin to see output on the screen like this:
```
otel-otlp-1  | 2024-11-21T19:38:17.580Z	info	Metrics	{"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 1, "metrics": 20, "data points": 22}
```
... which is useful when testing locally. (Especially when writes are failing.)
> (devel) Enable otel-collector containers to emit logs under docker-compose

- CHANGELOG.md
- docs/sources/mimir/get-started/_index.md
The tutorial directory path has been changed to `docs/sources/mimir/get-started/play-with-grafana-mimir` after the release of the tutorial video. I added a small sentence to inform the reader.
There is no issue
> Inform reader about get started with mimir tutorial directory changes

- CHANGELOG.md
- pkg/mimir/modules.go
This appears to have been a bug ever since I plugged the setting into the prometheus codec.
It should be set directly from the querier engine config.
The frontend v2 config also sets it from the original source, the querier engine config. Since this codec module gets initialized before the frontend v2 config setting does, by referencing the uninitialized config value, it always ends up zero instead of the real value.
> fix incorrectly set query frontend codec lookback delta

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/api.go
- pkg/distributor/distributor.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push_test.go
- pkg/util/validation/limits.go
Add support for promoting OTel resource attributes.
The flag `-distributor.promote-otel-resource-attributes` (also a runtime config parameter) controls which set of resource attributes to eventually promote.
Additionally, `OTelResourceAttributePromotionConfig` can be set on the distributor configuration in order to specialize the configuration of which OTel resource attributes to promote. This is intended for our enterprise product.
> Add OTel resource attribute promotion feature

- pkg/distributor/otel.go
I noticed that I in a [previous PR](https://github.com/grafana/mimir/pull/8271/files#diff-14e8ab607c4c17393fbe8a314df6f1f2119867f5e121e5d41752b0b317d8c223R184) replaced the use of `spanLogger` with `logger` by accident in the call to `otelMetricsToTimeseries` in the distributor's OTLP endpoint. This PR restores the use of `spanLogger`.
> Distributor: Restore use of spanLogger in OTLP code

- CHANGELOG.md
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/subqueries.test
This PR fixes an issue where MQE could return invalid results if a subquery was evaluated as the top-level expression for an instant query.
If a series had all of its samples filtered out, MQE would return a series with no samples, for example the query `(avg(foo) > 100)[10m:30s]` could return a result like this:
```json
{
"status": "success",
"data": {
"resultType": "matrix",
"result": [
{
"metric": {
"env": "prod"
}
}
]
}
}
```
It should instead not return the series at all:
```json
{
"status": "success",
"data": {
"resultType": "matrix",
"result": [
]
}
}
```
(none)
> MQE: fix issue where subqueries could return series with no points

- CHANGELOG.md
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/subqueries.test
Manually backporting https://github.com/grafana/mimir/pull/9998 to r317.
> Backport #9998 to r316

- CHANGELOG.md
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/subqueries.test
Manually backporting https://github.com/grafana/mimir/pull/9998 to r315.
> Backport #9998 to r315

- CHANGELOG.md
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/subqueries.test
Manually backporting https://github.com/grafana/mimir/pull/9998 to r314.
> Backport #9998 to r314

- CHANGELOG.md
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/operators/functions/function_over_range_vector.go
- pkg/streamingpromql/testdata/ours/functions.test
This PR applies the same idea as https://github.com/grafana/mimir/pull/9717 to functions over range vectors.
https://github.com/grafana/mimir/pull/9717
> MQE: create slices with capacity for number of steps remaining, not all possible steps for functions over range vectors

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
This PR fixes the `serviceAccountName` field in the `alertmanager-statefulset` template in the helm chart.
Currently, using the `alertmanager.serviceAccount.name` field in the helm chart values doesn't work as the current `alertmanager-statefulset` template is using the default mimir service-account name.
No issues created for this.
> Helm : fix alermanager-statefulset serviceAccountName field

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
This changes the `EtcdAllocatingTooMuchMemory` alerts to use RSS memory rather than `working_set`.
The reason for this is etcd can use a **lot** of file cache memory for its file-backed database that will be dropped if it approaches the container's memory limit. This causes this alert to basically be scare-noise, at times. We had a situation where the Go process only had 50MiB of memory resident, but there was 700MiB of file cache memory.
RSS fits better with "AllocatingTooMuch" anyway.
> Use resident set memory for the etcd memory alert.

- integration/ruler_test.go
Simplify certain ruler integration test assertions, to make sure they're not ambiguous to the reader. Also fix a wrong comment.
> integration: Simplify ruler test assertions, fix comment

- CHANGELOG.md
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/aggregations/avg.go
- pkg/streamingpromql/operators/aggregations/sum.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/limiting_pool.go
- pkg/streamingpromql/types/limiting_pool_test.go
This PR extends MQE's tests to aid in catching native histogram use-after-return bugs, and fixes some issues they've uncovered.
Now, during tests in the `streamingpromql` package, any histograms in slices returned to the `HPoint` or `FloatHistogram` pools will immediately be mutated. This ensures that any possible use-after-return bugs are triggered deterministically.
(none)
> MQE: mangle native histograms in returned slices to catch use-after-return bugs + fix issues found

- CHANGELOG.md
- pkg/storage/tsdb/bucketcache/caching_bucket.go
- pkg/storage/tsdb/bucketcache/caching_bucket_test.go
When caching rule groups, the base64 encoded name of the rule group is used as part of the key for caching its contents. For long rule group names, this can exceed the max key length of Memcached. To solve this we use a cryptographic hash of the object name when the hashed version of the name is shorter than the full name. This is the same approach taken for postings in the store-gateway `indexcache`.
This has the added benefit of not invalidating most existing cache entries when rolling out this change. With the hash function picked, key generation is between 5 and 10 times slower than _not_ hashing the key but still dramatically faster than a network operation.
Related #9386
> Hash object names used as cache keys for CachingBucket

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/pusher_metrics.go
- pkg/storage/ingest/reader.go
We have a lot of metrics for the whole concurrent ingestion/fetching. I tried to add panels for either high-level metrics such as throughput and latency or places in the code where we rely heavily on assumptions (i.e. where we do estimations).
Added panels
* latency (time to process a batch or time to received a fetched batch)
* decompressed throughput from Kafka
* actual and estimated ingested samples
* actual and estimated bytes per record
Modified code
* I figured it'd be useful to see exemplars for when processing and batch wait time time take a long time, so I made small code changes too
**Before**
**After [^1]**
[^1]: Estimated bytes per records aren't working because the metric for that is in r318. R318 still hasn't been released in the environment I was testing against.
- [n/a] …
> ingest: add dashboard panels for concurrent ingestion/fetching

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/storage/tsdb/config.go
This PR adds a flag for the feature that has been already merged.
Fixes #9911
> Add `blocks-storage.tsdb.bigger-out-of-order-blocks-for-old-samples` flag

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling.jsonnet
- operations/mimir-tests/test-multi-zone-distributor.jsonnet
- operations/mimir/autoscaling.libsonnet
Similarly to https://github.com/grafana/mimir/pull/8874, in this PR I propose to rename `autoscaling_distributor_[min|max]_replicas` to `autoscaling_distributor_[min|max]_replicas_per_zone` to clarify that it's a per-zone setting when distributor is deployed multi-zone.
N/A
> Jsonnet: rename autoscaling_distributor_[min|max]_replicas to autoscaling_distributor_[min|max]_replicas_per_zone

- CHANGELOG.md
- pkg/mimirpb/timeseries.go
Today we found an ingester using much more memory than others. After some investigation we discovered that the memory utilization was caused by few requests with a very large number of samples per series. These requests poised the `TimeSeries` memory pool with very large slices.
In this PR I'm proposing to add a cap to the max slice size allowed to be put back in the timeseries pool, similarly to what I did for exemplars in https://github.com/grafana/mimir/pull/7936.
N/A
> Do not reuse labels, samples and histograms slices in the write request if there are more than 10x entries than the pre-allocated size

- operations/mimir/ingest-storage.libsonnet
Adding a generic `ingest_storage_kafka_client_id_settings` config option to Jsonnet, and then having both `ingest_storage_kafka_producer_client_id_settings` and `ingest_storage_kafka_consumer_client_id_settings` inherit from it. This is useful if you want to set a client ID for every Kafka client, both producer and consumer.
N/A
> Jsonnet: add ingest_storage_kafka_client_id_settings config option

- tools/benchmark-query-engine/main.go
This PR fixes an issue where the peak memory consumption of benchmarks run on Linux is off by a factor of 1024x.
I haven't added a changelog entry given this is not a user-facing change.
(none)
> MQE: fix incorrect peak memory consumption value reported for benchmarks run on Linux

- pkg/streamingpromql/testdata/upstream/functions.test
- pkg/streamingpromql/testdata/upstream/histograms.test
- pkg/streamingpromql/testdata/upstream/operators.test
- tools/check-for-disabled-but-supported-mqe-test-cases/main.go
This PR enables some upstream test cases that were previously disabled because they were not supported, but are now supported by MQE.
It also fixes an issue running `tools/check-for-disabled-but-supported-mqe-test-cases` when a test file uses the new `eval_info` command.
(none)
> MQE: enable supported upstream tests

- pkg/ruler/service_discovery.go
With Prometheus 3, it's required to register custom `discovery.Config` implementations, otherwise they [cannot be marshaled](https://github.com/prometheus/prometheus/blob/main/discovery/registry.go#L244). This currently causes Grafana Enterprise Metrics test failures in PRs to re-vendor Mimir.
> ruler: Register custom discovery config

- CHANGELOG.md
- go.mod
- go.sum
- pkg/distributor/otlp/helper_generated.go
- vendor/github.com/prometheus/prometheus/model/value/value.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/tsdb/head_append.go
- vendor/modules.txt
This PR updates mimir-prometheus dependency which brings the changes from:
- https://github.com/grafana/mimir-prometheus/pull/766
> OTLP: Handle StartTimeUnixNano with 'quiet zero' NaNs

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/db.go
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Backports https://github.com/prometheus/prometheus/pull/15426 to r315
This will switch mimir-prometheus replace to use weekly-r315 branch from that repo.
> [r315] Update mimir-prometheus to include prometheus#15426

- CHANGELOG.md
- docs/sources/mimir/send/native-histograms/_index.md
Send/Native Histograms: update the migration guide with the corrected dashboard query for switching between classic or native histograms queries.
Due to https://github.com/prometheus/prometheus/pull/15245 invalidating the old method.
Related to https://github.com/prometheus/prometheus/pull/15245
- N/A Tests updated. See #10026 
> fix(docs): update native histograms migration guide

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
- vendor/modules.txt
Updates mimir-prometheus weekly-r319 to https://github.com/grafana/mimir-prometheus/pull/779
This includes the cherry-pick of https://github.com/prometheus/prometheus/pull/15426
> [r319] Update mimir-prometheus to include prometheus#15426

- CHANGELOG.md
- pkg/frontend/querymiddleware/codec.go
I found this out while working on #10084, but since it's a slightly different change, I decided to open a separate PR because I wasn't sure if the header was left out intentionally.
> __Note to reviewers__: this change doesn't work without the changes in #10084, but the intent is different.
> query-frontend: propagate X-Read-Consistency-Offsets on labels requests

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/api.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_instance_ring.go
- pkg/usagetracker/tracker_partition_ring.go
- pkg/usagetracker/tracker_partition_ring_test.go
Add partition and instance rings support to usage-tracker.
N/A
> Add partition and instance rings support to usage-tracker

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/storage/tsdb/config.go
Backport https://github.com/grafana/mimir/pull/10035 to r317
> backport: Add blocks-storage.tsdb.bigger-out-of-order-blocks-for-old-samples flag

- CHANGELOG.md
- pkg/frontend/querymiddleware/astmapper/pruning.go
- pkg/frontend/querymiddleware/astmapper/pruning_test.go
- pkg/frontend/querymiddleware/prune_test.go
The current method of excluding/including sub query results in PromQL by comparing to -Inf or +Inf is no longer valid after https://github.com/prometheus/prometheus/pull/15245 due to comparison of native histograms to a float with < or > result in Jeanette's warning, not empty set.
To ease migration away from the old wrong logic, I'm adding the new logic first.
The new method uses logical AND operation to intersect the sub query with either a const vector() or an empty vector(). E.g.
```
subquery and on() (vector(1)==1)
```
which becomes:
```
subquery
```
and conversely 
```
subquery and on() (vector(-1)==1)
```
becomes
```
(vector(-1)==1)
```
We cannot just drop `(vector(-1)==1)` altogether , because of this example:
```
(other_subquery) and (subquery and on() (vector(-1)==1))
``` …
> frontend: update query pruning

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
We try to copy the headers from the internal request representation, but we never transfer it from the HTTP request to that representation  in the first place. This PR fixes that. 
https://github.com/grafana/mimir/blob/97f031939ce511e2d93a6e80634d9c5d9a5d8f90/pkg/frontend/querymiddleware/codec.go#L731-L741
Technically the list of headers to propagate is empty by default in Mimir, so there wasn't a bug for Mimir users, hence, not adding a changelog entry.
https://github.com/grafana/mimir/blob/451d592d6cd65171da4741564745ef105c1c475e/pkg/frontend/querymiddleware/codec.go#L53
> __Note to reviewers__: reviewing without whitespace is easier
> query-frontend: propagate headers on labels requests

- pkg/util/tracing/tracing.go
- pkg/util/tracing/tracing_test.go
The OTEL spec allows to close the span multiple times and that `End` should be idempotent. I think the jaeger implementation doesn't have the same guarantees, so we have to handle this in out bridge implementation.
Currently, we allow to call `Finish` multiple times and we end up reporting the span multiple times: once for exhausting the HTTP request body with `io.EOF` and once for `Close()`. For more details see https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6391
https://github.com/open-telemetry/opentelemetry-specification/blob/50027a1036746dce293ee0a8592639f131fc1fb8/specification/trace/api.md#end
> Implementations SHOULD ignore all subsequent calls to End and any other Span methods, i.e. the Span becomes non-recording by being ended (there might be exceptions when …
> tracing: finish OTEL bridge span only once

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
Upgrade to Go v1.22.9, in order to resolve [CVE-2024-34156](https://nvd.nist.gov/vuln/detail/CVE-2024-34156).
> [release-2.13]: Upgrade to Go v1.22.9

- go.mod
- go.sum
- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_instance_ring.go
- pkg/usagetracker/tracker_partition_ring.go
- pkg/usagetracker/usagetrackerclient/client.go
- pkg/usagetracker/usagetrackerclient/client_test.go
- pkg/usagetracker/usagetrackerclient/grpc_client_pool.go
- vendor/github.com/grafana/dskit/ring/partition_instance_ring.go
- vendor/modules.txt
Add UsageTrackerClient to track series. It will be used by distributor in a follow up PR.
UsageTrackerClient features:
- Preferred zone
- Hedge to other zone instances after 100ms (configurable) or on failure
N/A
> Add UsageTrackerClient to track series

- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
As the title says. Else block builder will be stuck on that partition forever until the partition retention kicks in.
This is how ingesters handles it as well.
> block-builder: Do not hard fail when native histogram is disabled and tried to ingest one

- tools/benchmark-query-engine/main.go
This PR fixes some typos in the GOOS values in `tools/benchmark-query-engine`.
I'm not adding a changelog entry given this is a development tool.
https://github.com/grafana/mimir/pull/10031
> MQE: fix GOOS values in `tools/benchmark-query-engine`

- CHANGELOG.md
Security update of github.com/rs/cors to v1.11.0 was placed under v2.13.0 in the changelog, move under v2.13.1 (it's not part of the v2.13.0 release, making v2.13.1 now).
> [release-2.13] CHANGELOG: Associate github.com/rs/cors update with right release

- integration/backward_compatibility.go
Update Mimir versions in integration/backward_compatibility.go, from v2.13.0 -> v2.13.1 and v2.14.0 -> v2.14.2.
> integration: Update backward compatibility versions

- pkg/usagetracker/tracker_store.go
When we're tracking series, the timestamp we're setting is `now` truncated to minutes. It's VERY unlikely that some other goroutine has updated this timestamp to something newer already.
Maybe there was a newer timestamp set from a snapshot, in which case we should overwrite it, as we cleanup based on *our* wall clock anyway.
> UsageTracker: don't CAS when tracking series

- CHANGELOG.md
- tools/copyblocks/README.md
- tools/copyblocks/main.go
Adds the option `user-mapping` to `copyblocks` to allow copying between tenants. Previously it was always assumed that blocks would be copied to a different bucket under the same tenant.
For example, passing `--user-mapping="foo:bar"` would map the blocks from tenant `foo` to the destination tenant `bar`.
Something I did not touch in this PR was the copy marker naming. It is of the form `markers/blockID-copied-target-bucket`. Now that different tenants can be copied to the marker can clash if you copy data from one tenant to multiple tenants in the same destination bucket. That seemed like a weird use case so I deferred to YAGNI.
N/A
> copyblocks: support copying between tenants

- pkg/usagetracker/tracker_store.go
Don't preallocate MaxUint64/128 if tenant has no limit set.
> UsageTracker: limit series preallocation

- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_store.go
- pkg/usagetracker/tracker_store_test.go
This adds a method to process series creation events, also a test that checks that it's compatible with the events produced.
> UsageTracker: process created series events

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- development/mimir-ingest-storage/config/mimir.yaml
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/mimir/mimir.go
- pkg/usagetracker/tracker.go
Adds bucket client config & client, still not used.
> UsageTracker: add bucket config/client for snapshots storage

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- development/mimir-ingest-storage/config/mimir.yaml
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/scheduler/scheduler.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/storage/ingest/config.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_client.go
- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_events.go
Init usage-tracker Kafka client. There are 2 different configs for writer and reader, because we'll need to address different brokers. The config is inherited by `ingest.KafkaConfig` that contains a bunch of extra stuff we don't need. To productionise the usage-tracker we'll have to decouple the basic Kafka client config from the rest used to configure the ingest storage, but this shouldn't be a blocker for the prototype.
N/A
> Init usage-tracker Kafka client

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_instance_ring.go
In this PR:
- Allow to configure usage-tracker zone
- Rename "ring" to "instance-ring" in the config
Now usage-tracker correctly register the zone in the ring:
N/A
> Allow to configure usage-tracker zone

- pkg/usagetracker/tracker_store.go
- pkg/usagetracker/tracker_store_snapshot.go
- pkg/usagetracker/tracker_store_test.go
The whole markForDeletion didn't work well, so I refactored it to track the number of ongoing requests and rely on that being 0 to perform deletions.
> UsageTracker: store.cleanup() test & refactor

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/notifier.go
- pkg/ruler/notifier_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_map.go
- pkg/util/validation/limits_map_test.go
- tools/doc-generator/parse/parser.go
This PR allows you to specify arbitrary URL parameters to send alongside OAuth token requests, when the Alertmanager client is configured in OAuth mode.
Some OAuth providers require extra fields here that are not normally part of the spec - for example, `audience` is a common one. The Go stdlib followed a similar convention for such fields: https://github.com/golang/oauth2/issues/216 where arbitrary extra URL values are allowed.
n/a
> Ruler: Add support for arbitrary extra URL parameters to Alertmanager client's OAuth config

- CHANGELOG.md
- tools/querytee/proxy.go
- tools/querytee/proxy_backend.go
- tools/querytee/proxy_backend_test.go
- tools/querytee/proxy_endpoint_test.go
- tools/querytee/proxy_test.go
One of my backends needs a specific header so that it returns "correct" results.
Currently we don't have a way to add per-backend configuration. This PR introduces a new flag which takes JSON and allows to configure each backend separately. It will be used like so
```
-backend.config='{"mimir.com": {"request_headers": "X-Some-Header": ["value1", "value2"]}}'
```
I'm open to suggestions in case this is not a route we want to go on.
> query-tee: add per-backend request headers

- pkg/storage/ingest/fetcher.go
This atomic is used to export `cortex_ingest_storage_reader_estimated_bytes_per_record`
https://github.com/grafana/mimir/blob/36da907adaf09db95f18c4427760bc6b9f2457b6/pkg/storage/ingest/reader.go#L1112
But until now it was never mutated. This was a bug.
> ingest: actually export estimated bytes per record

- CHANGELOG.md
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/request_validation.go
- pkg/frontend/querymiddleware/request_validation_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
This PR introduces early request validation for the majority of request types supported by the query-frontend.
This specifically does not introduce any new request parsing or validation logic, but it ensures that the validation that does exist is called in the first roundtripper, before any other work is done _and_ that a standardized 400 Bad Request APIError is returned.
The tests are largely focused on making sure we get a status 400 API Error when we expect one - each request validator roundtripper relies on existing validation codecs which have their own extensive test suites.
**Done so far** are the ones that have clearly defined validation code already in Mimir:
* instant query
* range query
* label names query
* label values query
* series query
* label names cardinality
* label …
> Early Request Validation in Query Frontend

- pkg/usagetracker/tracker_store.go
- pkg/usagetracker/tracker_store_bench_test.go
- pkg/usagetracker/tracker_store_snapshot.go
- pkg/usagetracker/tracker_store_test.go
This decouples trackerStore tests from the specific implementation by using a new seriesCounts() method and by decoding the snapshots rather than accessing to the data maps.
This will allow us to switch the implementation while keeping the same tests.
Also added `BenchmarkTrackerStoreTrackSeries` to compare future implementations to the current one.
> UsageTracker: decouple tests from implementation

- pkg/usagetracker/tracker_store.go
This is still good enough for our use case (we don't need to touch the 1h idle timeout limit) but this means that we only need 7 bits to store the timestamp.
This change is not backwards compatible on the wire (i.e. current SeriesCreated events are invalid).
> UsageTracker: switch to 2h clock face

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/usagetracker/tenantshard/event.go
- pkg/usagetracker/tenantshard/map.go
- pkg/usagetracker/tenantshard/map_nonsimd.go
- pkg/usagetracker/tenantshard/map_test.go
- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_events.go
- pkg/usagetracker/tracker_store.go
- pkg/usagetracker/tracker_store_bench_test.go
- pkg/usagetracker/tracker_store_collector.go
- pkg/usagetracker/tracker_store_snapshot.go
- pkg/usagetracker/tracker_store_test.go
This refactors the entire tracker.
There are two big changes here: how the map is implemented and how we interact with it.
How the map is implemented:
We're getting rid of usual maps storing atomic.Int32: it's an overkill to have 32bit int to store a byte, it's even more an overkill to store a 64bit pointer to that, let's not talk about map overhead.
Instead of that, we're building kind of swiss map, I based the implementation on the code from dolthub/swiss, you can read a blog post how that works here:
https://www.dolthub.com/blog/2023-03-28-swiss-map/
However, most of the code was replaced.
What did I do? Swiss map has a slice groups of hash suffixes, which are one byte, to quickly find the bucket where our element is, and it also has a slice of groups of keys. That's still a lot of …
> UsageTracker: use custom swiss map & channels

- pkg/frontend/querymiddleware/experimental_functions.go
Very minor change to not hardcode the PromQL experimental aggregation functions, and use a function defined in Prometheus instead (made possible with a recent sync).
Follow up to https://github.com/grafana/mimir/pull/9798 , part of https://github.com/grafana/mimir-squad/issues/2586
> Remove hardcoding for middleware checking for access to PromQL experimental functions

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/operators/functions/native_histograms.go
- pkg/streamingpromql/testdata/ours/native_histograms.test
- pkg/streamingpromql/testdata/upstream/native_histograms.test
https://github.com/grafana/mimir/issues/10067
> MQE: Add support for histogram_stddev function

- CHANGELOG.md
This PR cuts the changelog for Mimir 2.15. Everything beyond r320 has been moved to the new unreleased section.
Relates to https://github.com/grafana/mimir/issues/10151, full tracking issue for 2.15
> Cut changelog for 2.15

- pkg/streamingpromql/operators/functions/histogram_quantile.go
- pkg/streamingpromql/operators/subquery.go
- pkg/streamingpromql/types/fpoint_ring_buffer.go
- pkg/streamingpromql/types/hpoint_ring_buffer.go
- pkg/streamingpromql/types/limiting_pool.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/streamingpromql/types/pool.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/pool/bucketed_pool.go
- pkg/util/pool/bucketed_pool_test.go
This PR eliminates the use of loops in `BucketedPool`. This gives a very mild speedup (<1%) to queries with many steps and many series.
It also removes the panics in both ring buffer's `Append` and `Use` methods. It's possible that the conditions that previously would have caused a panic could happen in the real world if a subquery selected enough points that it exceeded the maximum size of a slice returned from the `FPoint` or `HPoint` pool, so it seems safer to return an error here rather than crashing the process.
(none)
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md …
> MQE: eliminate loops in `BucketedPool`

- pkg/querier/metadata_handler.go
- pkg/storage/ingest/util.go
We have a static security analysis tool which is complaining with "Potential Integer overflow made by strconv.Atoi result conversion to int16/32" in few places. In this PR I'm changing such parsing to use `strconv.ParseInt()` instead.
N/A
> Chore: use strconv.ParseInt() with 32bit when parsing 32bit numbers

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
We observed that the number of `gossipMessages` for the `ha_tracker key` in the memberList KVStore was significantly higher compared to other keys. For example, after 5 minutes of running Mimir locally with 2 distributors and 2 Prom-HA instances, we had:
**Keys**
- ha_tracker: ~24k messages
- alertmanagers/alertmanager: ~987 messages (the next highest)
This is causing several issues:
- A high number of messages being broadcasted between Mimir components, requiring more bandwidth.
- Unnecessary changes in the versions of the keys (ha_tracker).
We have observed that this is happening because of how the Merge function of ReplicaDesc was behaving. In order to check if there was a change or not it was comparing the two mergeable objects. However some gossip messages can have the same values …
> fix(ha_tracker): track when there is a change during merge of ReplicaDesc Components

- CHANGELOG.md
Some PRs got merged before notifying about the 2.15 release candidate being cut went out; this moves them to `main / unreleased`.
Relates to https://github.com/grafana/mimir/issues/10151
> Update CHANGELOG.md with PRs not in 2.15-rc.0 release

- CHANGELOG.md
- docs/sources/mimir/manage/tools/mimirtool.md
- pkg/mimirtool/commands/env_var.go
This PR documents the TLS-related environment variables and CLI flags for `mimirtool`, and fixes a stutter in the `MIMIR_HTTP_PREFIX` environment variable.
(none)
> mimirtool: document TLS environment variables and CLI flags, and fix stutter in environment variable name

- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-0-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir-tests/test-query-scheduler-memberlist-ring-and-ruler-remote-evaluation-generated.yaml
- operations/mimir-tests/test-ruler-remote-evaluation-generated.yaml
- operations/mimir-tests/test-ruler-remote-evaluation-migration-generated.yaml
- operations/mimir/ruler-remote-evaluation.libsonnet
This should match what the ruler-query-frontend is configured for.
> Ops: Also set server.grpc-max-send-msg-size-bytes on ruler-queriers

- pkg/distributor/otel_test.go
Rework the test to be more explicit and support testing for https://github.com/prometheus/prometheus/pull/15448 that's coming next.
Related to #10188 
Related to https://github.com/prometheus/prometheus/pull/15448
> chore(otel_test): rework test to prep for keep id resource attributes

- CHANGELOG.md
- go.mod
- go.sum
- pkg/distributor/otlp/helper_generated.go
- vendor/github.com/prometheus/prometheus/model/value/value.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/tsdb/head_append.go
- vendor/modules.txt
This PR updates mimir-prometheus dependency. It brings:
- Two reverts
- https://github.com/grafana/mimir-prometheus/pull/789
- https://github.com/grafana/mimir-prometheus/pull/790
There is another candidate that brings the rest of the changes here https://github.com/grafana/mimir/pull/10188 discussing with Krajo if we could combine the effort. Leaving as draft for now
- EDIT: Just rebased now that Krajo's PR is merged
> Vendor update mimir-prometheus at 0a0a41616520101ffd29c38f167b36898f08019d

- pkg/storage/ingest/config.go
A refactoring PR in preparation of another refactoring PR. In this PR I've moved the CLI flag prefix `.` in the prefix. The final CLI flags haven't changed.
N/A
> Refactoring: move the CLI flags prefix '.' in the prefix

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/scheduler/scheduler.go
- pkg/mimir/modules.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_client.go
I have an use case for Kafka unrelated from the ingest storage, but I would like to reuse the generic `NewKafkaReaderClient()` and `NewKafkaWriterClient()`. In this PR I'm refactoring `NewKafkaReaderClientMetrics()` to take the metrics prefix in input.
N/A
> Refactoring: allow to customize Kafka reader client metrics prefix

- pkg/streamingpromql/operators/selectors/selector.go
- pkg/streamingpromql/operators/selectors/selector_test.go
This PR fixes the behaviour of MQE to select only the data necessary for the query.
https://github.com/grafana/mimir/pull/9844 introduced an incorrect calculation for the time range required for a selector. The extra millisecond doesn't usually matter, except for range queries that run for exactly `max_partial_query_length`, where this incorrect value would result in us returning a `err-mimir-max-query-length` error incorrectly.
https://github.com/grafana/mimir/issues/10067
- [n/a - covered by generic entry for MQE that references #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versio …
> MQE: don't select more data than strictly necessary

- CHANGELOG.md
- pkg/distributor/otel.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
This PR prevents `distributor.OTLPHandler` and `distributor.Handler` from propagating errors containing non-utf8 characters.
The presence of non-utf8 characters in Mimir errors might break some crucial parts of distributor's logic. For example, if `httpgrpc.HTTPServer.Handle()` returns a `httpgprc.Error` containing a non-utf8 character, this error will not be propagated to `httpgrpc.HTTPClient` as a `htttpgrpc.Error`, but as a generic error, which might break some of Mimir internal logic.
This is because golang's `proto.Marshal()`, which is used by gRPC internally, fails when it marshals the `httpgrpc.Error` containing non-utf8 character produced by `httpgrpc.HTTPServer.Handle()`, making the resulting error lose some important properties.
> Distributor: do not propagate errors with non-utf8 characters

- pkg/ruler/api.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
Exposing `filterRuleGroupsByNotMissing()` to reuse it in GEM.
N/A
> Refactoring: expose filterRuleGroupsByNotMissing()

- CHANGELOG.md
- pkg/querier/querier.go
- pkg/querier/querier_test.go
follow-up of https://github.com/grafana/mimir/pull/9712/
This PR adds the necessary changes to propagate the passed matchers to the `TimeRangeQueryable.IsApplicable` function, which can be useful for upstream projects by allowing a custom queryable to be applicable only for a specific queried metric.
Fixes n/a
> Querier: pass query matchers to `TimeRangeQueryable.IsApplicable` function

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
Augment the `MimirAutoscalerNotActive` and `MimirAutoscalerKedaFailing` runbooks with an instruction to check whether Prometheus has enough CPU allocated.
> Runbooks: Add steps for checking Prometheus CPU

- go.mod
- go.sum
- pkg/ruler/manager_metrics.go
- pkg/ruler/rule_concurrency.go
- pkg/ruler/rule_concurrency_test.go
- vendor/github.com/prometheus/prometheus/rules/group.go
- vendor/github.com/prometheus/prometheus/rules/manager.go
- vendor/github.com/prometheus/prometheus/tsdb/querier.go
- vendor/modules.txt
This includes:
- https://github.com/grafana/mimir-prometheus/pull/807
- https://github.com/grafana/mimir-prometheus/pull/806
Also:
- https://github.com/grafana/mimir/pull/10189
> [r321] Update mimir-prometheus weekly-r321

- pkg/streamingpromql/testdata/ours/selectors.test
- pkg/streamingpromql/types/limiting_pool.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/pool/bucketed_pool.go
- pkg/util/pool/bucketed_pool_test.go
This PR solves two bugs:
BucketedPool would create pools in powers of two up to a set `maxSize`. That is, if `maxSize` isn't a power of two itself,
then the maximum bucket would be less than the maxSize.
However, when requesting a slice from the pool we were only checking against the maxSize, and not whether a bucket existed for that size. Now, instead, calculate the bucketIndex and check if that exists before using it.
This would cause panic's in range vectors of more than 65,536 samples.
This problem was introduced in https://github.com/grafana/mimir/pull/10199
If a requested slice size exceeded the size of the pools it would just be returned as the requested size. This caused a bug in the buffers which require the slices to be powers of two.
This PR ensures that the returned slice is …
> MQE: Fix panic in loading too many samples

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
This PR introduces native histogram support for `electedReplicaPropagationTime` in order to get better granularity and visibility on the tail latencies above 10s during the testing phase of memberlist as KvStore for ha_tracker
Relates to [ha_tracker][memberlist] Testing Phase
> distributor(ha_tracker): add native histogram for electedReplicaPropagationTime

- CHANGELOG.md
- operations/mimir-tests/test-multi-zone-with-store-gateway-automated-downscaling-generated.yaml
- operations/mimir/rollout-operator.libsonnet
Implements correct port specification for rollout-operator in deployment, service, MutatingWebhookConfiguration and ValidatingWebhookConfiguration
Fixes #10272
> jsonnet: fix rollout-operator ports

- .github/workflows/test-build-deploy.yml
Stop erroring when images are not included in page bundles. The image rules are documented in https://grafana.com/docs/writers-toolkit/review/doc-validator/errata/#image-does-not-exist. They insist that all images are stored in the repository in a page bundle and are only referenced by the containing page.
Assets should instead be stored in https://grafana.com/docs/writers-toolkit/write/image-guidelines/#where-to-store-media-assets to avoid bloating this repository and the website repository with binary files.
@tacole02 We'll probably want to migrate images as they are updated unless you want to do them all together?
> Skip image checks to match other repositories that use the asset server for images

- CHANGELOG.md
- pkg/mimirtool/commands/remote_read.go
Since https://github.com/grafana/mimir/pull/9156 probably, all the remote read commands return no data
I added a missing error return using `timeseries.Err()` and got this error: `mimirtool: error: chunkedReader: message size exceeded the limit 0 bytes; got: 361 bytes, try --help` which lead me to find that we need to pass in `ChunkedReadLimit` on the client
I set it at a default 1 MiB and configurable through a flag
> fix(mimirtool): Make remote-read actually return data

- operations/mimir-rules-action/entrypoint.sh
Signed-off-by: rasta-rocket <bruno.fernando@jobteaser.com>
Hey folks 👋
Small PR that fix/simplify the way the multiline is rendered in the output of the action mimir-rules-action
With the following pipeline:
```
name: mimir_rules_ci
on:
workflow_dispatch:
pull_request:
jobs:
mimir_rules:
name: Check Mimir Rules
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
- name: Check Mimir rules
uses: rasta-rocket/mimir/operations/mimir-rules-action@action_mimirtool_fix_multiline
env:
MIMIR_ADDRESS: "XXXXX"
MIMIR_TENANT_ID: XXXXX
ACTION: check
RULES_DIR: "./mimir/alert,./mimir/record"
- name: Diff Mimir rules
id: diff_rules
uses: rasta-rocket/mimir/operations/mimir-rules-action@action_mimirtool_fix_multiline
env:
MIMIR_ADDRESS: "XXXXX"
MIMIR_TENANT_ID: XXXXX
ACTION: diff …
```
> [mimir-rules-action] fix multiline output expression

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Delete operations are expected to fail when the key doesn't exist when keys are deleted as part of cache invalidation.
Related #9386
> mixin: Ignore cache delete errors for cache error alerts

- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/graphite-enabled-values-generated/mimir-distributed/templates/graphite-proxy/graphite-querier/graphite-querier-schemas-configmap.yaml
Fix the default graphite config in the mimir-distributed helm chart so the time specification is valid
Fixes https://github.com/grafana/mimir/issues/10275
There is unfortunately no test covering this config
> helm: fix default Graphite config

- docs/sources/mimir/manage/mimir-runbooks/_index.md
> Runbook: clarify MimirIngesterReachingSeriesLimit errors and retries

- pkg/blockbuilder/schedulerpb/client_test.go
Fixes a flaky test where map iteration order is sometimes different than the order expected by the test assertion.
One such failure can be seen here: https://github.com/grafana/mimir/actions/runs/12434636520/job/34718770602
> Fix inconsistent map iteration order flake in blockbuilder/schedulerpb TestSendUpdates

- CHANGELOG.md
- pkg/frontend/querymiddleware/read_consistency.go
- pkg/frontend/querymiddleware/read_consistency_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/partition_offset_reader.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
Adjust `readConsistencyRoundTripper` to take a map of header keys to offsets readers, allowing it to support the tracking of the produced offsets of multiple topics.
> query-frontend: Allow for multiple topics in readConsistencyRoundTripper

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ingester/ingester.go
- pkg/util/limiter/utilization.go
I don't see a reason why we might disable this. The memory footprint is miniscule and the CPU usage is minimal too. The samples give better granularity on what event in the past 60s might have triggered this: "did CPU increase just now or has it been increasing since 30s ago"
Since I think it's harmless, we also don't need a flag for it. The flag is experimental so we can just drop it without notice.
I'm using the occasion to also log the CPU samples both when enabling and disabling the CPU limiter
> ingester: always log CPU samples for CPU limiter

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Enhance runbook "Copying files from a distroless container" with note that container being used to copy files must still be running.
Thanks to @pstibrany for originally proposing this improvement.
> Runbooks: Clarify that container being used to copy files must still be running

- CHANGELOG.md
- pkg/util/limiter/utilization.go
Use a Go metric instead of calling `runtime.ReadMemStats`. Empirically this is much faster.
```
│ before.txt  │             after.txt              │
│   sec/op    │   sec/op     vs base               │
CombinedScanner-4   25.58µ ± 2%   12.41µ ± 3%  -51.48% (p=0.002 n=6)
```
In a trace from a large ingester; the stop-the-world pause was more like 1-5ms; see example in image.
(and this is called every 1 second)
> Limiter: avoid stop-the-world pause when reading heap size

- CHANGELOG.md
- pkg/storage/lazyquery/lazyquery.go
Fixes a bug where warning/info annotations are missing when we use lazy querier.
N/A
> Show warnings for lazySeriesSet

- .golangci.yml
- CHANGELOG.md
- tools/copyblocks/main.go
Disable pprof endpoint in tools/copyblocks, to satisfy gosec's [G108 rule](https://github.com/securego/gosec?tab=readme-ov-file#available-rules). Also enable gosec for said rule.
> tools/copyblocks: Disable pprof endpoint, to satisfy gosec's G108 rule

- .golangci.yml
- pkg/mimirtool/commands/alerts.go
- pkg/mimirtool/commands/loadgen.go
- tools/copyblocks/main.go
- tools/trafficdump/main.go
Enable gosec's [G114 rule](https://github.com/securego/gosec?tab=readme-ov-file#available-rules), and satisfy it by configuring HTTP servers w/ timeouts in:
* tools/copyblocks
* tools/trafficdump
* mimirtool
> Security: Enable gosec's G114 rule

- .golangci.yml
- pkg/ruler/api.go
Enable gosec linter for G109 rule.
> Security: Enable gosec linter for G109 rule

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Introduces a dashboard panel row showing the `cortex_query_scheduler_querier_inflight_requests` by query component against the total `cortex_query_scheduler_connected_querier_clients` metric.
The `cortex_query_scheduler_querier_inflight_requests` is a Summary metric designed to capture the _peak_ utilization of the query-scheduler <-> querier connections with inflight query processing in order to help identify saturation of the ingesters or store-gateways. The summary metric's lower percentiles are not particularly useful.
It also updates some of the tooltip descriptions about the query scheduler rows to be more accurate to the new design.
> update Mimir / Reads and Remote Ruler Reads dashboard with query scheduler metrics

- pkg/continuoustest/client_test.go
- pkg/distributor/otel.go
- pkg/storegateway/indexheader/stream_binary_reader.go
- pkg/util/http.go
I noticed that in most cases we don't close gzip readers after use, even though it's the [caller's responsibility](https://pkg.go.dev/compress/gzip#NewReader).
> Close gzip readers after use

- .golangci.yml
- pkg/frontend/frontend_test.go
- pkg/frontend/v1/frontend_test.go
- pkg/util/gziphandler/gzip_test.go
- pkg/util/instrumentation/metrics.go
Enable gosec G112 rule, configuring timeouts in `util/instrumentation.MetricsServer`, which is only used by tools.
> Security: Enable gosec G112 rule

- .golangci.yml
> Security: Enable gosec G104 rule

- docs/sources/mimir/release-notes/v2.15.md
Per https://github.com/grafana/mimir/issues/10151, this is a draft of the 2.15 release notes
> Draft 2.15 release notes

- docs/sources/mimir/release-notes/v2.15.md
Cherry-picks release notes for 2.15 onto release-2.15 branch
Relates to #10151
> 2.15 release notes (#10165)

- pkg/frontend/querymiddleware/roundtrip.go
- pkg/mimir/modules.go
Add a configuration for extra headers to propagate in `QueryFrontendCodec`. This is intended to be accessed programmatically by GEM.
> querymiddleware: Add config for propagating additional headers

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/config.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/aggregations/aggregation.go
- pkg/streamingpromql/operators/binops/binary_operation.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/vector_vector_binary_operation.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
- pkg/streamingpromql/testdata/upstream/collision.test
- pkg/streamingpromql/testdata/upstream/operators.test
- pkg/streamingpromql/types/limiting_pool.go
This PR adds support for `group_left` and `group_right` (aka many-to-one and one-to-many matching) in binary operations to MQE.
In our benchmarks, latency is up to 80% lower and peak memory utilisation is up to 30% lower with MQE compared to Prometheus' engine:
```
│  Prometheus  │               Mimir                │
│    sec/op    │   sec/op     vs base               │
Query/h_1_*_on(l)_group_left()_a_1,_instant_query-10                        321.8µ ± 2%   340.3µ ± 9%        ~ (p=0.065 n=6)
Query/h_1_*_on(l)_group_left()_a_1,_range_query_with_100_steps-10           452.3µ ± 1%   358.5µ ± 2%  -20.74% (p=0.002 n=6)
Query/h_1_*_on(l)_group_left()_a_1,_range_query_with_1000_steps-10         1651.5µ ± 0%   756.0µ ± 3%  -54.23% (p=0.002 n=6) …
```
> MQE: add support for `group_left` and `group_right` (aka many-to-one and one-to-many matching)

- .github/workflows/stale.yaml
- docs/internal/contributing/README.md
We just had a session going over PRs. For some of them we just followed up and asked if the author would like to continue working on it. We can automate that.
We chose a very conservative thresholds: 150 days (5 months) before `stale` label; 180 days (6 months) before closing. But these are very much open for discussion and suggestions.
> Label and close stale PRs

- .github/workflows/deploy-pr-preview.yml
- CODEOWNERS
for https://github.com/grafana/website/issues/10101
**What is this feature?**
This PR adds a workflow to deploy the output of the `make docs` command to a public deploy preview. The workflow posts a comment with a link to the preview after it has been deployed.
**Why do we need this feature?**
Docs contributors will no longer need to run `make docs` on their machine, as they will be able to view the deploy preview instead.
**Who is this feature for?**
Everyone.
> add deploy preview workflow

- CHANGELOG.md
In this PR I'm merging the release-2.14 branch to main branch. Please merge this PR using a **merge commit** or by using `tools/release/merge-approved-pr-branch-to-main.sh` script.
> Merge release-2.14 to main

- docs/sources/mimir/configure/configure-spread-minimizing-tokens/index.md
This PR adds clarity to step 2 of [shutting down ingesters on zone a](https://grafana.com/docs/mimir/latest/configure/configure-spread-minimizing-tokens/#step-2-shut-down-ingesters-from-zone-a) to also mention the need to flush all in-memory metrics to long-term storage when migrating to spread-minimizing tokens.
This PR addresses the support request, https://github.com/grafana/support-escalations/issues/11275.
> Docs: Adds clarity to step on shutting down ingesters

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/config.libsonnet
…
Fixes https://github.com/grafana/mimir/issues/9841
> fix MimirGossipMembersTooLow alert mixin: add query-frontend to ring members

- docs/sources/helm-charts/mimir-distributed/release-notes/v5.6.md
> Helm: Draft release notes for  5.6

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector_test.go
- pkg/streamingpromql/operators/selectors/range_vector_selector.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/hpoint_ring_buffer.go
- pkg/streamingpromql/types/stats.go
This PR adds support for tracking the number of samples processed in a query evaluated by MQE.
Resolves #10138
> MQE: track number of processed samples in each query

- pkg/storage/ingest/partition_offset_watcher.go
- pkg/storage/ingest/partition_offset_watcher_test.go
- pkg/storage/ingest/reader.go
Rename `partitionOffsetWatcher` to `PartitionOffsetWatcher` and `newPartitionOffsetWatcher` to `NewPartitionOffsetWatcher`, making them available for use outside of the `ingest` package.
N/A
> Rename partitionOffsetWatcher -> PartitionOffsetWatcher

- .golangci.yml
- pkg/mimirtool/commands/config.go
- pkg/util/activitytracker/activity_tracker.go
- pkg/util/shutdownmarker/shutdown_marker.go
> G302: Expect file permissions to be 0600 or less
Changes here are mostly noop except for a very niche mimirtool command for converting cortex config, which at this point probably nobody uses
> Fix G302 gosec issues

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/mimir/modules.go
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
The retries happen more aggressively than actual evaluations. With the current setup an error spike results in 3x the query rate - initial query, and two retries fairly quickly 100ms & 200ms after that.
Introduce a soft rate limit for the retries. The default is 170 retries/sec, which is half the average rate of rule evaluations in clusters at GL. If a retry is above the rate limit, we'd wait (`time.Sleep`) until it is within the limit, while also not exceeding a 2s backoff. The idea is not to overextend into the next evaluation.
> ruler: cap the number of remote eval retries

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/functions/rate_increase.go
This PR is trying to address suggestion in https://github.com/grafana/mimir/pull/9795 to extract delta function from rate. The diff will show how we have many more line additions if we extract the logic from rate.
How this different with #9795 
- We created a new step function called `delta` 
- Delta has no reset handling
- Delta will call `calculateFloatRate` and `calculateHistogramRate` to do extrapolation
My concern with extracting delta from rate is we create many line duplications, such as most of lines in delta(), floatDelta() and histogramDelta(). This is reflected from 118 line additions and 36 line removal in this PR diffs.
> Extract delta from rate function

- CHANGELOG.md
- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir/ingest-storage-migration.libsonnet
- operations/mimir/mimir.libsonnet
During the migration to ingest storage, there's a step during which we scale down 1 ingester zone and rename PVC. In that step we need to make sure PVCs are not deleted when the ingester statefulset is scaled down and deleted. To ensure it, in this PR I enforce persistentVolumeClaimRetentionPolicy Retain policy on partition ingesters during migration to ingest storage.
N/A
> Enforce persistentVolumeClaimRetentionPolicy Retain policy on partition ingesters during migration to ingest storage

- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
This PR fixes a panic, I've noticed in a flaky test. When the `TSDBBuilder` fails to upload a block, the code of `CompactAndUpload` goes into the branches, that try to close the block several times. Consider the following case:
1. block B1 is closed before uploading;
2. the uploading fails;
3. the deferred function, that cleans up the `tsdbs`, sees that B1 wasn't "done", and closes the block again;
4. the deferred function panics with `close of closed channel` and interrupts the clean-up;
4. ...
5. the deferred call to `TSDBBuilder.Close` tries to close the blocks in the `tsdbs` once again, and panics once again 🙈 
Also, I've notice there is a "race" condition, where the deferred clean-up function unlocks the mutex, that protects `tsdbs` before it cleans up the `tsdbs` map.
This PR fixes …
> blockbuilder: fix panic when closing tsdb after failing to upload block

- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/operators/binops/binary_operation.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR fixes two issues with the implementation of comparison operations between two vectors without the `bool` modifier in MQE:
* Queries would return incorrect results if the left side contained series with different metric names, and all results would be merged into a single series rather than returned in separate series for each metric name
* Queries would incorrectly fail with a conflict error if multiple series on the left side matched the same series on the right side, those left side series had points at the same timestamp, and one or none of those points remained after applying the comparison operation
Changes in latency and peak memory consumption of affected benchmarks are within the margin of error of our benchmarks.
I'd recommend reviewing each commit separately.
#10067
- …
> MQE: fix issues with vector/vector binary comparsion operations

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/operators/functions/rate_increase.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/functions.test
- na Documentation added.
- na [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> MQE: Add support for delta function

- CHANGELOG.md
- pkg/ruler/remotequerier.go
the previous limit of 2s is too small and doesn't end up spreading out retries for long enough
follow-up of #10375
> ruler: increase retries backoff limit to 1m

- pkg/ruler/remotequerier.go
#10403
(cherry picked from commit 8bedb97dd18aa7b12863caa4c413b52c81cbc8ec)
> [r321] ruler: increase retries backoff limit to 1m 

- pkg/ruler/remotequerier.go
#10403
(cherry picked from commit 8bedb97dd18aa7b12863caa4c413b52c81cbc8ec)
> [r316] ruler: increase retries backoff limit to 1m 

- .github/workflows/deploy-pr-preview.yml
The previous guard fails because `github.repository` resolves to the base repository on `pull_request` events.
> Fix only run on fork guard

- pkg/ruler/rule_concurrency.go
- pkg/ruler/rule_concurrency_test.go
The log added here: https://github.com/grafana/mimir/pull/10400/files#diff-3e8efecf11fa9185935eea3d3c9c7993f99422353a391190657877e902875a37R254 doesn't work for all loggers
When I tested it in dev, I got some of these errors:
```
ts=2025-01-10T17:26:37.207249729Z caller=rule_concurrency.go:254 level=debug component=concurrency-controller tenant=17065 group=mimir_querier_api msg="Batched rules into concurrent blocks" batches="unsupported value type"
```
I added a new `fmt.Stringer` type for the slice because I don't want the debug log to negatively affect performance (the added benchmark showed that stringing had a 25% performance hit)
> Rule Concurrency: Fix debug log

- pkg/streamingpromql/types/fpoint_ring_buffer.go
- pkg/streamingpromql/types/hpoint_ring_buffer.go
- pkg/streamingpromql/types/limiting_pool.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/streamingpromql/types/pool.go
- pkg/streamingpromql/types/pool_test.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/pool/bucketed_pool.go
- pkg/util/pool/bucketed_pool_test.go
Primarily from feedback on https://github.com/grafana/mimir/pull/10261
Rather than allowing an arbitrary maxSize in pools, require them to be a power of two since that is what happens internally anyway.
We keep the checks and protections around requiring it to be a power of two.
> MQE: Tidy up pool size handling

- .golangci.yml
- pkg/querier/worker/scheduler_processor_test.go
- pkg/ruler/ruler_test.go
- pkg/storage/tsdb/block/block_test.go
`gocritic` is too noisy to add as a whole, but we can add checks when we find non-controversial things that could've easily been fixed
> Add `gocritic/dupImport` check

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/validate.go
In #10145 we introduced a request validation at distributor level that, for each object of type `mimirpb.PreallocTimeseries` in a request, iterates all its float and histogram samples, and as soon as a sample with a timestamp that has already been visited is found, discards the corresponding sample from the timeseries. Once the validation is completed, the request without discarded samples is forwarded to ingesters. Discarded samples are tracked by the `cortex_discarded_samples_total` metrics with reason `sample_duplicate_timestamp`.
One of the problems introduced by #10145 is that if a distributor discards at least one sample due to a duplicated timestamp, it also returns an error reporting the name of the timeseries, and the number of discarded samples. This behaviour introduces a …
> Distributor: don't return errors when discarding samples with duplicated timestamps

- pkg/ruler/fixtures/rules_self_and_same_name_reference.yaml
- pkg/ruler/fixtures/rules_self_reference.yaml
- pkg/ruler/rule_concurrency.go
- pkg/ruler/rule_concurrency_test.go
After deployment of https://github.com/grafana/mimir/pull/10400 to dev, we are getting some of these warnings:
```
Cyclic rule dependencies detected, falling back to sequential rule evaluation
```
It turns out to be a recording rule that is self referencing (using `last_over_time` to fall back to its last value).
Whenever a rule's unevaluated dependencies consist of only itself, it is OK to be run. A caveat is that if there are two rules recording to a metric with the same name, but with different labels, the dependency tree cannot be built and concurrency is not possible
> Rule Concurrency: Support self references

- pkg/distributor/ha_tracker_test.go
It seems that 2 seconds was not enough to prevent the test from failing again, so I would like to increase it to 10 seconds to address edge cases that require more time. 
Relates https://github.com/grafana/mimir/issues/10350
> ha_tracker_test: Increase test polling duration to 10s

- CHANGELOG.md
- integration/distributor_test.go
- integration/e2emimir/client.go
- pkg/distributor/push.go
- pkg/distributor/rw2/utils.go
Reject remote write 2.0 request properly with HTTP status 415, based on [RW2.0 spec](https://prometheus.io/docs/specs/remote_write_spec_2_0/#2-x-vs-1-x-compatibility).
The current solution returns 2xx , but doesn't actually ingest the samples.
Prometheus does detect this
prometheus-1  | time=2025-01-13T13:01:35.028Z level=ERROR source=queue_manager.go:1670 msg="non-recoverable error" component=remote remote_name=150c10
url=http://mimir-1:8001/api/v1/push failedSampleCount=2000
failedHistogramCount=0 failedExemplarCount=0
err="sent v2 request with 2000 samples, 0 histograms and 0 exemplars;
got 2xx, but PRW 2.0 response header statistics indicate 0 samples,
0 histograms and 0 exemplars were accepted; assumining failure e.g.
the target only supports PRW 1.0 prometheus.WriteRequest, but does …
> fix(rw2.0): reject remote write 2.0 based on content type

- mimir-build-image/Dockerfile
This PR updates the Go version used in `mimir-build-image` to `1.23.4`.
> Mimir build image: Update Go version to 1.23.4

- CHANGELOG.md
- pkg/ingester/ingester_ring.go
- pkg/mimir/modules.go
When ingest storage is enabled, the ingester ring is used for service discovery but the partition ring is now used to match series to ingesters. This means the ingester ring's tokens are not used anymore. This PR hides token-related fields from the ingester ring status page when in ingest storage mode.
Leverages this dskit option (which has example screenshots): https://github.com/grafana/dskit/pull/633
Contrib https://github.com/grafana/mimir-squad/issues/2350
> ingester: Hide tokens in ingester ring status page when ingest storage is enabled

- development/mimir-microservices-mode/config/prom-ha-pair-1.yaml
- development/mimir-microservices-mode/config/prom-ha-pair-2.yaml
- development/mimir-microservices-mode/config/prometheus.yaml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/config/prometheus.yaml
- development/mimir-monolithic-mode/config/prometheusRW2.yaml
- development/mimir-monolithic-mode/docker-compose.yml
Update Prometheus and also add a profile for easy RW2.0 testing. To use:
```
development/mimir-monolithic-mode$ ./compose-up.sh --profile prometheusRW2
```
Going from 2.55.1 to 3.1.0
> chore(dev): update Prometheus to 3.1.0 and add prometheusRW2 profile

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/index.go
- vendor/modules.txt
Revert optimization https://github.com/prometheus/prometheus/pull/15455 in r321, as it has been linked to up to ~3x memory utilization increase in Mimir compactors.
> [r321] Revert Prometheus PR #15455

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/index.go
- vendor/modules.txt
Revert optimization prometheus/prometheus#15455 in r322, as it has been linked to up to ~3x memory utilization increase in Mimir compactors.
> [r322] Revert Prometheus PR #15455

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/index.go
- vendor/modules.txt
Revert optimization prometheus/prometheus#15455 in r324, as it has been linked to up to ~3x memory utilization increase in Mimir compactors.
> [r324] Revert Prometheus PR #15455

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/index.go
- vendor/modules.txt
Revert optimization prometheus/prometheus#15455 in r325, as it has been linked to up to ~3x memory utilization increase in Mimir compactors.
> [r325] Revert Prometheus PR #15455

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/tsdb/index/index.go
- vendor/modules.txt
Revert optimization prometheus/prometheus#15455 in r323, as it has been linked to up to ~3x memory utilization increase in Mimir compactors.
> [r323] Revert Prometheus PR #15455

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/astmapper/prom2_range_compat.go
- pkg/frontend/querymiddleware/astmapper/prom2_range_compat_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/prom2_range_compat.go
- pkg/frontend/querymiddleware/prom2_range_compat_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/util/validation/limits.go
Fix queries that have the same range and resolution since this will only return a single point when using Prometheus 3 selectors, left open and right closed (compared to Prometheus 2 left closed and right closed).
Internal incident
These names were the first things I thought of, please feel free to suggest better ones!
> Rewrite subqueries that have the same range and resolution

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/astmapper/prom2_range_compat.go
- pkg/frontend/querymiddleware/astmapper/prom2_range_compat_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/prom2_range_compat.go
- pkg/frontend/querymiddleware/prom2_range_compat_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/util/validation/limits.go
* Rewrite subqueries that have the same range and resolution
Fix queries that have the same range and resolution since this will only return a single point when using Prometheus 3 selectors, left open and right closed (compared to Prometheus 2 left closed and right closed).
* Changelog
---------
(cherry picked from commit b812677266850268b4b00dd689a3baedb13a87b2)
> Rewrite subqueries that have the same range and resolution (#10445)

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/util/validation/limits.go
From feedback https://github.com/grafana/mimir/pull/10459#discussion_r1918936622
Related #10445
> docs: Fix help text for query-frontend.prom2-range-compat flag

- CHANGELOG.md
- pkg/querier/querier.go
- pkg/querier/querier_test.go
This passes the request context into the `TimeRangeQueryable`'s `IsApplicable()` method, which will allow the queryable to decide based on values in the context whether the queryable is applicable.
> pass query context into Queryable's IsApplicable hook

- CHANGELOG.md
- pkg/storage/ingest/partition_offset_client.go
- pkg/storage/ingest/partition_offset_client_test.go
Add `topic` as a constant label for partitionOffsetClient's metrics. Without this, trying to use the partitionOffsetClient for multiple topics at once results in a panic.
> partitionOffsetClient: Add topic label to metrics

- pkg/mimirpb/compat_test.go
As far as I can tell we don't cast Prometheus Remote Write 1.0 histogram into mimirpb.Histogram anymore. On the flip-side this test fails in #10432 because we're going to store RW 2.0 extra field in mimirpb.Histogram.
Related to #9072
> refactor(mimirpb): delete TestRemoteWriteV1HistogramEquivalence

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_metrics.go
- pkg/alertmanager/alertmanager_metrics_test.go
Incorporates https://github.com/prometheus/alertmanager/pull/4210, which changes the helptext of `alertmanager_config_hash` to state that the hash is expected to collide.
Since that's documented in the hash we deliver to users, we can safely suppress g401 on the code generating the hash.
Since Mimir metrics layer their own helptext on top of the base alertmanager metrics, this can be done without updating the vendored code, which can be left to Alerting team.
n/a
> alertmanager: Sync metric documentation from upstream

- Makefile
- mimir-build-image/Dockerfile
This PR updates the Go version used in mimir-build-image to `1.23.5`.
> Mimir build image: Update Go version to 1.23.5

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-statefulset.yaml
- operations/helm/charts/mimir-distributed/templates/compactor/compactor-statefulset.yaml
- operations/helm/charts/mimir-distributed/templates/ingester/ingester-statefulset.yaml
- operations/helm/charts/mimir-distributed/templates/store-gateway/store-gateway-statefulset.yaml
- operations/helm/charts/mimir-distributed/values.yaml
This PR updates the chart StatefulSets templates, to allow configuring their PVC template names. E.g.
```yaml
store_gateway:
persistentVolume:
enabled: true
name: store-gateway-data
```
This is a noop change for the existing systems. But this'll allow us to minimise the discrepancies between the Jsonnet bundle and the Helm chart, when migrating our internal systems to use the chart.
Also, the PR simplifies the templates of the `volumeClaimTemplates` yaml sections.
> mimir-distributed: allow StatefulSets to configure their PVC template names

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
When a key entry at the ha_tracker expires it goes through this [code](https://github.com/grafana/mimir/blob/main/pkg/distributor/ha_tracker.go#L469), which:
- calls the `delete` operation of the `kvStore` client
- sets the `DeletedAt` timestamp of the expired ReplicaDesc
If another entry comes with the same `key` **before the expired ReplicaDesc is removed from the memberlist kvStore** it can fetch a replicaDesc entry with the below format from the kvStore during the CAS operation ([code](https://github.com/grafana/mimir/blob/main/pkg/distributor/ha_tracker.go#L613)):
```
&ReplicaDesc{ 
Replica:replica_0,
ReceivedAt:1736949099138
DeletedAt:1736949236956
ElectedAt:1736949084145
ElectedChanges:10,}
```
It will try to replace it with the new `replicaname` and `receivedat`  timestamp:
- …
> fix(ha-tracker): set electedAtTime to now when the received replicaDesc ha deletedAt higher than zero

- CHANGELOG.md
- operations/mimir-mixin/dashboards/rollout-progress.libsonnet
The route matcher wasn't being applied if the gateway is enabled.
> dashboards: fix latency comparison in "Mimir / Rollout Progress"

- CHANGELOG.md
- pkg/costattribution/sample_tracker_test.go
- pkg/frontend/querymiddleware/prom2_range_compat.go
- pkg/frontend/querymiddleware/prom2_range_compat_test.go
- pkg/frontend/querymiddleware/roundtrip.go
Follow up to #10445, add a metric when queries are rewritten for compatibility with Prometheus 3 range selector semantics.
Fixes #10464
> Add visibility when subqueries are rewritten

- docs/sources/mimir/configure/about-versioning.md
- pkg/api/api.go
Following on from https://github.com/grafana/mimir/pull/10153/ this PR changes the endpoint to match that of the [influx2cortex code](https://github.com/grafana/influx2cortex/blob/main/pkg/influx/api.go#L30) used as the basis for the influx write proxy.
This moves it from `/api/v1/influx/push` to `/api/v1/push/influx/write` (note change of order of `influx` and `push`, as well as the extra `/write` suffix).
Experimental feature, no further CHANGELOG or documentation updates required.
> influx: fix endpoint path to match existing proxy

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
We currently run an Alertmanager for each tenant in the database, no matter whether their configurations are usable or not. This results in many unused Alertmanagers consuming resources.
This PR adds the option to skip initializing Alertmanagers for Grafana Alertmanager tenants without a usable Grafana Alertmanager configuration.
The new `-alertmanager.grafana-alertmanager-conditionally-skip-tenant-suffix` argument takes a string that will be compared against tenants' IDs. If it matches, the Alertmanager will only be initialized if there's a promoted, non-default, non-empty Grafana Alertmanager configuration for that tenant.
I tested this by spinning up two Alertmanagers:
- `mimir-1` built from `main`
- `mimir-1-new` build from this branch
I added 600 tenants to each one:
- 200 with …
> Alertmanager: Skip starting the Alertmanager for Grafana tenants unless they have a promoted, non-default configuration

- CHANGELOG.md
- pkg/util/time.go
- pkg/util/time_test.go
Fixes a panic in `DurationWithJitter`, `DurationWithPositiveJitter`, `DurationWithNegativeJitter` when small inputs result in a variance of zero, because `rand.Int63n` panics on zero.
> Fix panics in DurationWithJitter utils when computed variance is zero.

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
Updated some warnings and add critical alerts to block builders.
* `BlockBuilderNoCycleProcessing` is a little sensitive. Meaning if a consumption ran a little longer than 5m compared to the earlier one (for duration is 5m), this alert will fire. Made the `for` period to be 20 mins
* `BlockBuilderLagging` current warning alert fires when the lag is over 4M for 75mins (basically lag went above 4M, but it stayed above 4M in the next cycle as well). We have a critical alert with for duration of 2h20m. Meaning once it went above 4M in a cycle, it remained about 4M in the next two cycles as well. If the cycle run was not successful, then `BlockBuilderNoCycleProcessing` will already fire much the lagging alert will fire. `BlockBuilderLagging` will catch other issues that is not just "not able …
> Block builder: update alerts and add critical alerts

- pkg/ingester/downscale_test.go
Fix flake in TestIngester_PrepareInstanceRingDownscaleHandler when tests were run before an ingester had actually joined the ring.
Fixes https://github.com/grafana/mimir/issues/9494
> test: Ensure ingester is active in ring before tests

- pkg/querier/querier_test.go
Use a consistent value for "now" to ensure the error message matches the expected error in tests.
Fixes #10094
> test: Fix flaky TestQuerier_ValidateQueryTimeRange_MaxQueryLength

- CHANGELOG.md
- go.mod
- go.sum
- pkg/ingester/metrics_test.go
- vendor/github.com/prometheus/prometheus/tsdb/postings_for_matchers_cache.go
- vendor/modules.txt
In this PR I'm updating mimir-prometheus to get a couple of improvements to PostingsForMatchers cache observability:
- https://github.com/grafana/mimir-prometheus/pull/824
- https://github.com/grafana/mimir-prometheus/pull/825
N/A
> Improve PostingsForMatchers cache observability

- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
This PR fixes an issue with the `clamp`, `clamp_min`, `clamp_max`, `round` and `histogram_fraction` functions in MQE: they could return multiple series with the same labels if multiple series with the same labels but different metric names were passed to the function.
This PR also adds a test to ensure we catch issues like these when new functions are added in the future.
#10067
> MQE: fix functions that could return multiple series with the same labels

- CHANGELOG.md
- operations/mimir-tests/test-automated-downscale-generated.yaml
- operations/mimir-tests/test-automated-downscale-v2-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-0-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
- operations/mimir/ingest-storage-migration.libsonnet
- operations/mimir/ingester-automated-downscale-v2.libsonnet
- operations/mimir/ingester-automated-downscale.libsonnet
The jsonnet bundle hardcodes the `prepare-downscale-http-port: 80` in all components, that use autoscaling and downscaling via the rollout-operator. This doesn't match the default HTTP port the bundle sets for the `*-http-metrics` container port, which is `:8080`.
Note we haven't noticed this previously, because internally all mimir components are run with `$._config.server_http_port=80`.
Fixes n/a
> jsonnet: pass downscale-http-port from config

- pkg/distributor/otlp/generate.sh
Saves some time to the next developer who has to run `make generate-otlp` and isn't familiar with the tools required.
> `make generate-otlp`: check that tools are installed

- CHANGELOG.md
- operations/mimir-tests/test-all-components-without-pod-topology-constraints-generated.yaml
- operations/mimir-tests/test-all-components-without-pod-topology-constraints.jsonnet
- operations/mimir/common.libsonnet
- operations/mimir/config.libsonnet
Allow to not configure `topologySpreadConstraints` by setting the following configuration options to a negative value:
* `distributor_topology_spread_max_skew`
* `query_frontend_topology_spread_max_skew`
* `querier_topology_spread_max_skew`
* `ruler_topology_spread_max_skew`
* `ruler_querier_topology_spread_max_skew`
```diff
diff /Users/marco/workspace/src/github.com/grafana/mimir/operations/mimir-tests/test-all-components-generated.yaml /Users/marco/workspace/src/github.com/grafana/mimir/operations/mimir-tests/test-all-components-without-pod-topology-constraints-generated.yaml
563,569d562
<       topologySpreadConstraints:
<       - labelSelector:
<           matchLabels:
<             name: distributor
<         maxSkew: 1
<         topologyKey: kubernetes.io/hostname
< …
```
> Jsonnet: allow to not configure topologySpreadConstraints at all

- CHANGELOG.md
- development/mimir-ingest-storage/docker-compose.jsonnet
- development/mimir-ingest-storage/docker-compose.yml
- development/mimir-microservices-mode/docker-compose.jsonnet
- development/mimir-microservices-mode/docker-compose.yml
- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/docker-compose.yml
- pkg/frontend/querymiddleware/error_caching.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
This change fixes the error mapping done in the query sharding middleware to correctly map all possible errors from the PromQL engine to an appropriate APIError type. This fixes an issue where `context.Canceled` was treated as an execution error and cached for subsequent requests.
As part of this, instrumentation for the error caching middleware was improved and Jaeger tracing in various Docker compose setups was fixed by pinning the image used.
Internal escalation.
> Fix instance where context cancellation error was cached

- go.mod
- go.sum
- vendor/github.com/prometheus/alertmanager/config/notifiers.go
- vendor/github.com/prometheus/alertmanager/notify/webhook/webhook.go
- vendor/github.com/prometheus/alertmanager/tracing/http.go
- vendor/modules.txt
This PR updates our Alertmanager fork to include the following commits:
- [ee06e515](https://github.com/grafana/prometheus-alertmanager/commit/ee06e515687c4b6c38c15213b2f2168b6b0b3581) Add timeout option for webhook notifier. (#4137)
- [950596bd](https://github.com/grafana/prometheus-alertmanager/commit/950596bde9af0ac9e18f3653e829e7e68e0efb52) Tracing: use events for http client detail
- [359d3a0e](https://github.com/grafana/prometheus-alertmanager/commit/359d3a0e170e9ceb7837b3bb2aa84f83b999f8e9) fix mispell
- [273b0103](https://github.com/grafana/prometheus-alertmanager/commit/273b0103910dda26d2b1b4a82046a8b1c35f0e00) add log param
> Alertmanager: Update Alertmanager fork

- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR fixes a bug where MQE's implementation of `group_left` / `group_right` could sometimes return incorrect labels for a series.
In particular, this could happen if the number of additional labels in the `group_left(...)` or `group_right(...)` modifier was not a power of two. `VectorMatching.Include` was effectively being mutated in `manySideGroupKeyFunc` to include `__name__` and drop the last label (rather than being copied to a new slice with `__name__` appended), and so the incorrect set of additional label names was used in `outputSeriesLabelsFunc`. 
If the list of additional labels had a length that was a power of two, then the `append` in `manySideGroupKeyFunc` caused a new underlying array to be created and so the bug was not triggered.
(none)
- …
> MQE: fix issue where `group_left` / `group_right` could return series with incorrect labels

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/autoscaling.libsonnet
While reviewing https://github.com/grafana/mimir/pull/10473 I noticed that the MimirAutoscalerNotActive alert is not working because of the missing `metric` aggregation. This PR fixes it.
To manually test it I've flipped the `{condition="ScalingActive",status="false"}` to `{condition="ScalingActive",status="true"}`, so that all HPAs match.
**Before** (no matching series):
**After** (231 matching series):
N/A
> Fix MimirAutoscalerNotActive alert

- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/operators/functions/timestamp.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/at_modifier.test
- pkg/streamingpromql/testdata/upstream/functions.test
This PR adds support for the `timestamp` function to MQE.
Compared to Prometheus' engine, `timestamp` runs up to 60% faster in MQE in our benchmarks:
```
goos: darwin
goarch: arm64
│  Prometheus  │               Mimir                │
│    sec/op    │   sec/op     vs base               │
Query/timestamp(a_1),_instant_query-10                     142.5µ ± 2%   139.4µ ± 1%   -2.16% (p=0.002 n=6)
Query/timestamp(a_1),_range_query_with_100_steps-10        163.6µ ± 1%   146.2µ ± 1%  -10.67% (p=0.002 n=6)
Query/timestamp(a_1),_range_query_with_1000_steps-10       361.5µ ± 4%   193.7µ ± 1%  -46.41% (p=0.002 n=6)
Query/timestamp(a_100),_instant_query-10                   931.7µ ± 1%   775.5µ ± 6%  -16.76% (p=0.002 n=6) …
```
> MQE: add support for `timestamp`

- development/mimir-monolithic-mode-with-swift-storage/docker-compose.yml
- development/mimir-monolithic-mode/docker-compose.yml
Revert update of jaegertracing/all-in-one, since it's supposed to be pinned at v1.62. This reverts commit e5d998b8a875aadb5bdf3c8dc52c0d0a756c1637.
> Revert "Update jaegertracing/all-in-one Docker tag to v1.65.0 (#10563)"

- renovate.json5
Configure Renovate to disable updating of the `jaegertracing/all-in-one` Docker image, since we want to stay at v1.62.0.
> Renovate: Disable updating of jaegertracing/all-in-one Docker image

- pkg/continuoustest/client.go
- pkg/continuoustest/client_test.go
This PR allows users to specify arbitrary additional headers for the continuous-test client's requests. This allows the client to set headers such as the `X-Filter-Queryables` header added in https://github.com/grafana/mimir/pull/10552.
> continuous-test: Add WithAdditionalHeaders req option to client

- pkg/distributor/distributor.go
- pkg/ingester/active_series.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/mimir/grpc_call_check.go
- pkg/mimir/grpc_call_check_test.go
- pkg/mimir/modules.go
This change:
- Updates ingesters to perform gRPC call checks for reads, similar to what they currently do for pushes. This allows read request checks, such as for circuit breaking, to be performed by a tap handle, similar to how push request checks are performed. Tap handles are preferable for limiting RPC calls since they allow rejection to take place before a goroutine is allocated to handle a request.
- Adds `ingesterReceiver` in addition to the existing `pushReceiver`.
- Removes the explicit start/finish ReadRequest calls that were previously being made in read RPC methods since these are now handled by the grpc_call_check.
- Adds Prepare methods to the receivers which will allow gRPC interceptors to be used with push/read calls.
> Update grpc_push_check to support reads in ingesters

- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/operators/functions/sort.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/functions.test
This PR adds support in MQE for `sort` and `sort_desc`.
Performance compared to Prometheus' engine is slightly better, and peak memory consumption is the same:
```
goos: darwin
goarch: arm64
│ Prometheus  │               Mimir               │
│   sec/op    │   sec/op     vs base              │
Query/sort(a_1),_instant_query-10      146.4µ ± 2%   142.4µ ± 2%  -2.71% (p=0.009 n=6)
Query/sort(a_100),_instant_query-10    839.6µ ± 1%   798.6µ ± 2%  -4.88% (p=0.002 n=6)
Query/sort(a_2000),_instant_query-10   11.14m ± 1%   10.78m ± 1%  -3.18% (p=0.002 n=6)
geomean                                1.110m        1.070m       -3.59%
│  Prometheus  │               Mimir                │
│      B       │      B        vs …
```
> MQE: add support for `sort` and `sort_desc`

- tools/flush-memcached.sh
This PR adds a script that gradually flushes all Memcached pods in a StatefulSet.
This is useful when a cache has been poisoned and all items need to be purged, but restarting all Memcached pods at once with `kubectl rollout restart` would cause too much cache churn at once. For example, purging all Memcached pods in the query results cache at once would cause too much load on ingesters and store-gateways.
I haven't added a changelog entry given this is primarily a debugging tool.
(none)
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated …
> Add script to flush all Memcached pods in a StatefulSet

- pkg/storage/ingest/fetcher_test.go
The test was failing because the control function was used up by the periodic fetch loop of the started `concurrentFetchers`. This meant that the test sometimes ran when we don't have a control function registered and didn't inject an error.
At the same time the test cases didn't retain their control functions so that they don't interfere with each other.
This change makes the test cases independent, so we can use `KeepControl`.
Fixes https://github.com/grafana/mimir/issues/9916
> Fix flaky `TestConcurrentFetchers_fetchSingle`

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/util/validation/limits.go
This PR introduces an experimental flag, `query-frontend.adjust-to-max-future-query-window`. When set with a duration, any range queries querying farther than `now + maxFutureWindow` into the future will be adjusted to query only up to `now + maxFutureWindow`. 
Fixes #
> Add a flag to adjust queries to some max future time

- CHANGELOG.md
- pkg/frontend/querymiddleware/codec.go
To make the functionality implemented in https://github.com/grafana/mimir/pull/10552 work, the HTTP header `X-Filter-Queryables` needs to be propagated.
> propagate HTTP header to filter queryables when querying

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/writes.libsonnet
This PR extends the 'Writes' dashboard to add two new rows showing incoming write requests - one for Prometheus remote write requests, and the other for OTLP write requests:
I've chosen to show this data from gateways as this is the easiest place to differentiate requests based on the route - distributors convert all requests to `/cortex.Ingester/Push` requests to ingesters, and distributors receive some requests over httpgrpc.
(none)
> Writes dashboard: show write requests broken down by request type

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/reads.libsonnet
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
This PR makes a number of changes to the 'Reads' and 'Remote ruler reads' dashboards:
* It clarifies that the existing ingester and store-gateway panels on the 'Reads' dashboard show data from all query requests to that component, not just requests from the main query path (ie. requests from the ruler query path are included as well)
* It adds those panels to the 'Remote ruler reads' dashboard as well
* It adds similar panels showing only requests from the respective dashboard's query path, as reported by queriers. For example, the 'Remote ruler reads' dashboard now has panels showing the ingester query request rate from ruler-queriers only.
This is what the 'Reads' dashboard looks like now (and the 'Remote ruler reads' dashboard is similar):
(none)
- [n/a] …
> 'Reads' and 'Remote ruler reads' dashboards: add ingester and store-gateway query request panels for respective query path

- CHANGELOG.md
- operations/mimir-tests/test-multi-zone-distributor-generated.yaml
- operations/mimir-tests/test-multi-zone-etcd-generated.yaml
- operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
- operations/mimir/multi-zone-distributor.libsonnet
- operations/mimir/multi-zone-etcd.libsonnet
- operations/mimir/multi-zone.libsonnet
In this PR I'm changing the default multi-AZ topology toleration from `multi-az` to `secondary-az`, but also making it configurable.
N/A
> Jsonnet: change default multi-AZ topology toleration

- pkg/compactor/block_upload_test.go
- pkg/compactor/compactor.go
We only ever increase these metrics. They should be counters, not gauges.
> Compactor: Turn block upload metrics from gauges to counters

- pkg/frontend/querymiddleware/astmapper/subquery_spin_off.go
- pkg/frontend/querymiddleware/astmapper/subquery_spin_off_test.go
- pkg/frontend/querymiddleware/spin_off_subqueries.go
- pkg/frontend/querymiddleware/spin_off_subqueries_queryable.go
- pkg/frontend/querymiddleware/spin_off_subqueries_test.go
Massive oversight in https://github.com/grafana/mimir/pull/10460
The downstream queries were all just `__query__` instead of the actual query. I also optimized the mapper so that it groups downstream queries further up the tree, which should reduce the number of queries that need to be run.
Most queries when testing were still passing since joining subqueries and non subqueries is pretty rare in practice, it seems
> frontend: Fix downstream queries in experimental subquery spin-off feature

- CHANGELOG.md
- integration/ruler_test.go
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
In this PR I'm adding the `user` and `reason` labels to the `cortex_ruler_queries_failed_total` and `cortex_ruler_write_requests_failed_total` metrics. The idea behind the change is to allow tenants segregate and track separately the failures, that happened due to issues on the server vs. those happened due to issues on the client-side (e.g. bad rule).
The exact list of "reasons" is up for a discussion. I've noticed that Loki uses `error` and `upstream_error` ([code](https://github.com/grafana/loki/blob/4df8c60b6ba9f89ee3c8965e78dfae376e0ed929/pkg/ruler/evaluator_remote.go#L260-L273)). I'm not sure if those are well translated into what we want. Opinions are welcome.
For now, I've chosen to have only two reasons: 
- `error` for everything 
- `4xx` for the case when there is *a client-side …
> ruler: add "user" and "reason" labels to ruler's queries metrics

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
- operations/mimir-mixin/dashboards/tenants.libsonnet
This PR expands the descriptions of dashboard panels for the query-frontend and query-scheduler to clarify when they are expected to show no data.
(none)
> Clarify when query-scheduler and query-frontend dashboard panels are expected to show no data

- CHANGELOG.md
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
This PR comes with mostly structural changes. The idea here is that, currently, `OTLPHandler` silently drops series, it couldn't parse. This makes it complicated for the users, who see the increase in the dropped OTLP series due to a parse error, but who don't have access to the internal logs (e.g. when Mimir is deployed in Grafana Cloud).
Here, the handler holds the errors received during the OTLP conversion, and, if there wasn't any explicit issues from the downstream push services, it returns the status 400 (_it's up for a debate if this new behaviour is more correct; refer to the internal discussion https://github.com/grafana/mimir-squad/issues/2716_).
> distributor: report OTLP parse errors back to client

- CHANGELOG.md
- pkg/frontend/querymiddleware/astmapper/subquery_spin_off.go
- pkg/frontend/querymiddleware/astmapper/subquery_spin_off_test.go
- pkg/frontend/querymiddleware/spin_off_subqueries_test.go
In cases where we aggregate the results of a subquery, sharding is faster in some cases, slower in some. Overall, the impact of the feature seems to be near-zero.
Since:
- we're not gaining anything
- subquery spin-off is the newer feature, and it would be preferrable not to introduce a regression on existing queries
- subquery spin-off has an additional overhead of running a second query
I think we can give query sharding the priority
> Subquery Spin-Off: Prioritize query sharding

- pkg/compactor/blocks_cleaner.go
While reviewing #10569 I noticed that this timestamp may be different from what's in the bucket index.
> compactor: set `bucket_index_last_successful_update` to same as bucket index

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_replicated_set.go
- pkg/storegateway/dynamic_replication.go
- pkg/storegateway/dynamic_replication_test.go
- pkg/storegateway/gateway.go
- pkg/storegateway/sharding_strategy.go
- pkg/storegateway/sharding_strategy_test.go
Instead of replicating blocks to all store-gateways when they are eligible for dynamic replication, adjust the replication factor by a multiple of the default. This reduces disk and memory requirements for large tenants.
Related #10382
Related #9944
> Use multiple of default replication factor for dynamic replication

- CHANGELOG.md
- pkg/frontend/querymiddleware/error_caching.go
Fixes an issue introduced in  where a counter was only incremented when a particular trace was sampled instead of always.
Related #10537
> fix: increment error caching counter when trace not sampled

- pkg/blockbuilder/blockbuilder.go
Here is an example of the issue this PR fixes, copy pasted from @narqo's message:
1. Block builder restarted around 10:10
2. It has been catching up until 10:17
3. because of (1) and (2) it skipped that cycle at 10:15
4. At 11:15 it woke up, and had to process two hours of work in one cycle (it managed, but the alert fired for NoCycleProcessing)
With this change, we will proactively consume the cycle of 10:15 on startup. This change is hard to test because of `time.Now()` in the picture. I think it is fine to not write a test for this specific thing.
> block-builder: Proactively consume on startup

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
Closes https://github.com/grafana/mimir/issues/1811
Optionally expose the current HA replica for each tenant in the `cortex_ha_tracker_elected_replica_status` metric. This is enabled with the `-distributor.ha-tracker.enable-elected-replica-metric=true` flag. The flag is there to prevent adding an unexpectedly high cardinality metric.
> Distributor: Optionally record elected HA replica in metric

- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/references/architecture/mimir-query-engine.md
This PR adds a page to the docs explaining what MQE is, how to enable it and some of the key differences between it and Prometheus' engine.
#10067
> MQE: add docs page

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts.libsonnet
- operations/mimir-mixin/alerts/distributor.libsonnet
- pkg/mimir/mimir.go
Add a warning severity alert for too high distributor garbage collection CPU utilization. The motivation is to be alerted if `GOMEMLIMIT` causes distributors to garbage collect too often.
Additionally, enable three CPU runtime metrics required by the alerts:
* `/cpu/classes/gc/total:cpu-seconds`
* `/cpu/classes/total:cpu-seconds`
* `/cpu/classes/idle:cpu-seconds`
> Add warning alert for too high distributor GC CPU utilization

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/_helpers.tpl
Current mimir-distributed helm chart creates in-cluster remote urls nginx service's cluster url even when nginx is disabled.
- https://github.com/grafana/mimir/blob/9144986d6b9a662508b44a07884d46dc2f3da73a/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L37-L43
- https://github.com/grafana/mimir/blob/9144986d6b9a662508b44a07884d46dc2f3da73a/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L551-557
This PR fixes this behavior. `mimir.remoteWriteUrl.inCluster` and `mimir.remoteReadUrl.inCluster` will be query-frontend and distributor's url when both gateway and nginx are disabled.
none
> helm: Fix in-cluster remote URLs when gateway and nginx are disabled

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/ruler.libsonnet
Include a row for ruler resources on the Ruler dashboard since the ruler doesn't have a corresponding "resources" dashboard.
N/A
> mixin: Include ruler CPU/memory resources on ruler dashboard

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/operators/functions/range_vectors.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/functions.test
This PR adds support for `stddev_over_time` and `stdvar_over_time` to MQE.
#10067
> MQE: add support for `stddev_over_time` and `stdvar_over_time`

- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/operators/functions/common.go
- pkg/streamingpromql/operators/functions/function_over_range_vector.go
- pkg/streamingpromql/operators/functions/quantile.go
- pkg/streamingpromql/operators/functions/range_vectors.go
- pkg/streamingpromql/operators/functions/rate_increase.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/functions.test
This PR adds support in MQE for `quantile_over_time`.
#10067
> MQE: add support for `quantile_over_time`

- operations/helm/charts/mimir-distributed/ci/offline/keda-autoscaling-values.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-querier/ruler-querier-dep.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-querier/ruler-querier-pdb.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-querier/ruler-querier-so.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-querier/ruler-querier-svc.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-frontend/ruler-query-frontend-dep.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-frontend/ruler-query-frontend-pdb.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-frontend/ruler-query-frontend-so.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-frontend/ruler-query-frontend-svc.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-scheduler/ruler-query-scheduler-dep.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-scheduler/ruler-query-scheduler-pdb.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-scheduler/ruler-query-scheduler-svc-headless.yaml
- operations/helm/tests/keda-autoscaling-values-generated/mimir-distributed/templates/ruler-query-scheduler/ruler-query-scheduler-svc.yaml
> helm: render ruler read path in autoscaling offline tests

- pkg/streamingpromql/engine_test.go
This PR makes some improvements to the mixed metrics tests (aka the gauntlet), with the aim of preserving coverage while dramatically reducing how long they take to run.
On my machine, running all of the tests in `engine_test.go` took 3m35s before these changes, and now takes 45s.
I've tried to build up these changes incrementally, I suggest reviewing each commit separately.
(none)
> MQE: improve runtime of mixed metrics tests

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/querier/querier.go
This is a follow-up to https://github.com/grafana/mimir/pull/10620
Here I'm updating the `MetricsForLabelMatchers` to adjust the `limit` parameter passed to the downstream ingesters, base on the replication sets. The idea, suggested by @pracucci is to approximate the limit as:
```
L / (<shard-size> / <replication-factor>)
```
Note that for ingest storage, the above formula is equivalent to `L / <partition-shard-size>`.
> querier: adjust requested limit parameter for downstream requests to series endpoint

- CHANGELOG.md
- Makefile
- operations/mimir-mixin-compiled-gem/dashboards/federation-frontend.json
- operations/mimir-mixin-tools/serve/run.sh
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards.libsonnet
- operations/mimir-mixin/dashboards/federation-frontend.libsonnet
This is based on #10690 just so that I could compile the mixin. The changes aren't related.
This PR also makes it possible to run `make serve-mixin` for arbitrary compiled dashboards
> mixin: add Federation-frontend dashboard

- pkg/distributor/ha_tracker_test.go
- Increases the check time from 2 to 10s for `waitForHaTrackerCacheEntryRemoval` in order to cover cases where test concurrency
- Should fix https://github.com/grafana/mimir/issues/10687
> test: increase check time for entryRemoval from the cache

- pkg/alertmanager/config.go
- pkg/alertmanager/config_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
Receiver names can be duplicated in Grafana Alertmanager configurations. Grafana handles this by logging a warning and only using the last receiver with a given name. Still, Mimir fails to start the Alertmanager for a tenant with duplicate receiver names.
This PR uses an approach similar to https://github.com/grafana/mimir/pull/10534 to de-duplicate receivers with the same name, leaving only the last one.
1. From `main`, start Mimir with `alertmanager.grafana_alertmanager_compatibility_enabled` and `multitenancy_enabled` set to `true` in `mimir.yaml`
2. Upload a configuration with a duplicate receiver name, the Alertmanager for the tenant should fail to start
<details><summary>Example `curl` command</summary>
```bash
curl http://localhost:8706/api/v1/grafana/config -H 'X-Scope-OrgID: …
```
> Alertmanager: De-duplicate Grafana receivers

- CHANGELOG.md
- pkg/costattribution/active_tracker.go
- pkg/costattribution/manager.go
- pkg/ingester/activeseries/active_series.go
- pkg/ingester/activeseries/active_series_test.go
- pkg/ingester/ingester.go
This bug was discovered during deployment. The issue occurs because while we compare configuration differences, we never update the tracker in the ingester. As a result, the tracker remains in conflict mode, continuously exporting `cortex_ingester_active_series_loading`. This fix ensures proper config consolidation and resolves the issue. Additionally, the unit test included in this PR would fail without the fixed code, confirming the correctness of the fix.
The test showed on dev with fix, similar to usage group update, after ttl, the active series sum is correct
without fix, the active series are just gone for good.
- na Documentation added.
- na [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental …
> Ingester: Ensure cost attribution tracker is updated when configuration changes

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/mimir/modules.go
- pkg/querier/engine/config.go
- pkg/querier/querier.go
Remove experimental configuration flags `querier.promql-experimental-functions-enabled` and `query-frontend.block-promql-experimental-functions` used for controlling access to experimental PromQL features. Instead enable experimental PromQL functions at the engine level by default, block access to them by default, and selectively enable them at a per-user level using the middleware introduced in https://github.com/grafana/mimir/pull/9798.
Justification for this change:
* There are currently 3 different settings that need to changed to allow customers to make use experimental functions in PromQL that need to be applied 3 different places (queriers, query-frontend, and per-tenant limits).
* The performance impact from always enabling but blocking via middleware experimental PromQL functions …
> Simplify how experimental PromQL functions are enabled

- docs/sources/mimir/configure/configure-resource-utilization-based-ingester-read-path-limiting.md
Memory limit number was ~18.75 GiB, not 16 GB per the dev comment.
> docs: Fix Read Path Memory Limit Example

- CHANGELOG.md
- docs/sources/mimir/configure/configure-experimental-promql-functions.md
> Docs: Explain how to enable experimental PromQL functions

- .github/workflows/publish-technical-documentation-release-mimir.yml
v2 includes an additional step to check out the HEAD of the release branch before syncing on tag events. This ensures that tags made to older commits on a release branch don't revert documentation.
https://github.com/grafana/writers-toolkit/blob/main/publish-technical-documentation-release/action.yaml#L65-L84
Fixes https://raintank-corp.slack.com/archives/C03Q42RLMRQ/p1736193190664809
> Use v2 of the publish-technical-documentation-release workflow

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
With this change we make the `updateCache` synchronous with the kvStore change. Since the KVstore is the source of truth , regarding the correct ha_tracker entry  it makes sense to update the cache immediately.
This change will add a few map accesses for Replicas that have an actual change. **Not for every Replica**.  This operation was already happening from [processKVStoreEntry](https://github.com/grafana/mimir/blob/c86963a119123161ca9f1deae538f8ac281b3a8a/pkg/distributor/ha_tracker.go#L380-L379), so we just do the change earlier.   So no impact is expected.
Thanks @dimitarvdimitrov  for pointing this out.
Fix
- https://github.com/grafana/mimir/issues/10350#issuecomment-2672294698
- https://github.com/grafana/mimir/issues/10688#issuecomment-2669235048
> feat: synchronize cache update with KV store modification.

- tools/benchmark-query-engine/main.go
This PR makes two small changes to `tools/benchmark-query-engine`:
* it adds some additional logging before long-running operations
* it adds support for setting the value of `-benchtime` passed to the test binary, which is useful when running slow benchmarks to ensure enough iterations are run with warm pools
#10067
> MQE: benchmark tool improvements

- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/operators/functions/label.go
- pkg/streamingpromql/testdata/ours-only/functions.test
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/functions.test
> MQE: Add support for label_join

- CHANGELOG.md
- pkg/api/api.go
- pkg/ruler/rule_groups.gohtml
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
- pkg/ruler/tenants.gohtml
This PR adds a new `/ruler/tenants` endpoint to list tenants, the `ruler` service discovered in its storage. The idea here is to provide an external operator-component a way to observe which tenants have rules, without asking Mimir to retrieve the actual rules.
The API endpoint is complementary to the existing `/store-gateway/tenants`, `/compactor/tenants`, and `/ingesters/tenants`.
> ruler: add /ruler/tenants service API

- tools/rule-group-evals/main.go
- tools/rule-group-evals/rule.go
We recently discussed that the 3s latency for rule evaluation with strong read consistency (which includes both enforcing the consistency + writing to the ingest storage) may be too pessimistic. In prod we actually see about 1s for consistency + 500ms for writing to ingest storage, on average. I propose to lower it to 1.5s.
N/A
> Reduce estimated duration for strong read consistency rule evaluations

- pkg/frontend/querymiddleware/model_extra.go
Add warnings and infos to PrometheusLabelsResponse and PrometheusSeriesResponse to match the [standard HTTP API response for Prometheus](https://prometheus.io/docs/prometheus/latest/querying/api/#format-overview), allowing us to include those fields for the label names/values and series endpoints.
N/A
> Add warnings and infos to metadata responses

- CHANGELOG.md
- operations/mimir-mixin-compiled-gem/dashboards/federation-frontend.json
- operations/mimir-mixin/dashboards/federation-frontend.libsonnet
This PR fixes the federation-frontend dashboard to not use the deprecated Angular panel type.
I've tested these changes locally and the dashboard behaviour is identical with the preferred replacement panel type.
Screenshot of updated dashboard:
#10697
> mixin: don't use deprecated panel type in federation-frontend dashboard

- operations/helm/charts/mimir-distributed/values.yaml
The PR fixes two occurrences of the same typo in the `zoneAwareReplication` doc comments.
Fixes #10662
> mimir-distributed: typo in zoneAwareReplication doc comments

- integration/query_frontend_test.go
Following https://github.com/grafana/mimir/pull/10742 
This test is failing for Mimir enterprise due to options interacting with the subquery spin-off, causing more ingester queries
> frontend: Fix integration test failure

- CHANGELOG.md
- operations/mimir/shuffle-sharding.libsonnet
This PR adds a new assertion to the mimir Jsonnet bundle, that verifies the value set in the `$._config.shuffle_sharding.ingester_partitions_shard_size` to be derived from the existing `ingester_shard_size`.
As outlined in the code comments, we, generally, assume that the `RF=3` (_replciation factor_) in the classic architecture, and so expect the `ingester_partitions_shard_size == ingester_shard_size / RF`.
Relates to #7804
> mimir: assert on unexpected value in ingester_partitions_shard_size

- pkg/util/validation/exporter/exporter.go
- pkg/util/validation/exporter/exporter_test.go
I did a rounding mistake in https://github.com/grafana/mimir/pull/10549 and the exported value is always 0 if the `ingestion_artificial_delay` is set to a value < 1s. This PR fixes it.
N/A
> Fix exported ingestion_artificial_delay

- development/mimir-microservices-mode/goland/TSDB Query-frontend (using scheduler).run.xml
- development/mimir-microservices-mode/goland/TSDB Query-scheduler.run.xml
- development/mimir-microservices-mode/goland/distributor-1.run.xml
- development/mimir-microservices-mode/goland/distributor-2.run.xml
- development/mimir-microservices-mode/goland/distributor.run.xml
- development/mimir-microservices-mode/goland/ingester-3.run.xml
- development/mimir-microservices-mode/goland/store-gateway-1.run.xml
- development/mimir-microservices-mode/goland/store-gateway-2.run.xml
- development/mimir-microservices-mode/goland/store-gateway-3.run.xml
Update the goland debug profiles in mimir-microservices-mode to match the ports used for each service in the jsonnet
N/A
> chore: Update goland debug config to match jsonnet

- CHANGELOG.md
- pkg/util/reactivelimiter/prioritylimiter.go
- pkg/util/reactivelimiter/prioritylimiter_test.go
This change improves on #10574 by adding an additional check for reactive limiter queue sizes that limits the amount of queueing in each limiter based on its individual settings. At present, rejections are based on the prioritizer's threshold, which is computed periodically and looks at queueing across limiters along with request priorities, but this doesn't prevent a large burst of requests from enqueueing before the next calibration takes place. This PR adds an additional guard against this.
> Add additional check on reactive limiter queue sizes

- pkg/storegateway/bucket.go
- pkg/storegateway/bucket_e2e_test.go
- pkg/storegateway/indexheader/reader_pool.go
- pkg/storegateway/indexheader/reader_pool_test.go
- pkg/storegateway/indexheader/snapshotter.go
- pkg/storegateway/indexheader/snapshotter_test.go
This PR introduces two key optimizations to the `indexheader.Snapshotter` 
1. Checksum Mechanism: Added a checksum-based optimization to avoid persisting unchanged JSON data, reducing unnecessary IOPS. We're using sha256 because the linters think sha1 is not secure
2. Simplified Snapshot Format: Changed the snapshot format from `map[ulid.ULID]int64` to `map[ulid.ULID]struct{}`, eliminating unused timestamp data.
In clusters with many tenants, the `Snapshotter` component can generate significant disk I/O by repeatedly writing identical JSON data to disk. This is particularly problematic on systems with low-performance disks. Additionally, the previous implementation stored timestamps that were never actually used in practice.
This approach maintains backward compatibility. …
> store-gateway: avoid unnecessarily writing lazy-loaded blocks snapshot

- Makefile
- pkg/mimir/modules.go
- tools/lint-sorted/main.go
_As someone once commented somewhere: we are not savages._
The lack of sorting in the modules.go modules constant definitions was bothering me big time, especially since CostAttribution was added after All.
This sorts them and adds a linter that is triggered by adding a // lint:sorted comment which would fail if lines aren't sorted.
The linter checks lines from the line containing the directive until the next white space or a line that only contains closing bracket.
Fixes my OCD
> Add a linter to enforce sorted lines using lint:sorted directive.

- pkg/streamingpromql/benchmarks/benchmarks.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/aggregations/count_values.go
- pkg/streamingpromql/operators/aggregations/count_values_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testdata/ours/aggregators.test
- pkg/streamingpromql/testdata/upstream/aggregators.test
This PR adds support for `count_values` in MQE.
Benchmark results are mixed. MQE's implementation always consumes less memory than Prometheus' engine in our benchmarks, but in some cases runs slower, and in others runs faster. MQE is up to 36% faster for the common case where many series have only a handful of values, but up to 20% slower for the uncommon case where every sample has a different value.
The `count_values('value', h_X)` cases exercise the scenario where every sample has a different value, resulting in `X × 100` output series. The `count_values('value', h_X * 0)` cases exercise the scenario where every sample has the same value, resulting in 1 output series.
```
goos: darwin
goarch: arm64
│ …
```
> MQE: add support for `count_values`

- pkg/streamingpromql/functions.go
- pkg/streamingpromql/functions_test.go
This PR makes use of the linter added in https://github.com/grafana/mimir/pull/10765 to enforce that the list of functions in MQE remains sorted.
#10067
> MQE: lint that list of functions is sorted

- Makefile
- pkg/streamingpromql/testdata/ours/aggregators.test
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/ours/histograms.test
- pkg/streamingpromql/testdata/ours/native_histograms.test
- tools/fmt-promqltest.sh
- tools/format-promql-test.sh
This PR adds a script to enforce consistent formatting of PromQL test files.
I've chosen two spaces as the default indentation given that seems to be what most of our existing test files already use.
I've introduced each of the changes incrementally in their own commit.
If we find this useful, I'll also propose adding it upstream in Prometheus.
#10067
> MQE: enforce consistent formatting for test files

- operations/mimir-mixin-compiled-gem/dashboards/federation-frontend.json
- operations/mimir-mixin/dashboards/federation-frontend.libsonnet
This works for more grafana versions. Some versions don't default to `All`
> mixin: make federation-frontend remote_cluster variable multi-select

- integration/query_frontend_test.go
This tests two aspects of the split and cache feature:
1. We can go above the partial query length (because queries are split)
2. The query is split into multiple 24h queries
This is in response to https://github.com/grafana/mimir/pull/10796
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
> frontend: Add integration test for split and cache middleware

- pkg/ruler/manager.go
- pkg/ruler/notifier.go
- pkg/ruler/notifier_test.go
- pkg/ruler/service_discovery.go
- pkg/ruler/service_discovery_test.go
Remove a dependency on dskit/cache that was used only for a DNS service discovery interface. Instead, define the expected interface where it is consumed in the ruler.
N/A
> ruler: Remove dependency on dskit cache package

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/util/validation/limits.go
Undoes (removes) the flag introduced in #10547, since it was previously removed in 2.14.
> Remove max future query window flag

- .github/workflows/grafanabot_reviewer.yml
Due to https://github.com/grafana/deployment_tools/tree/master/docs/platform/continuous-integration#avoid-pull_request_target the workflow had to be changed from `on: pull_request_target` to `on: pull_request`. However that is fine as Grot PRs are created in the upstream repository thus that only makes the workflow safer!
> Update grafanabot_reviewer.yml to use app token

- pkg/frontend/querymiddleware/limits.go
To use https://pkg.go.dev/context#WithTimeoutCause , we need to return the cause as error, which is the normal behaviour, except that when we use https://github.com/golang/sync/blob/master/semaphore/semaphore.go#L49 in this code, it does not use the cause as error. To fix that, we check the error returned from there and replace it with the cause if relevant. Without this change, using `WithTimeoutCause` has no effect when calling `Do` on `limitedParallelismRoundTripper`.
N/A
Minor change which by itself should not result in any user-facing changes, but this makes other changes possible.
> Return context.Cause(ctx) as error so we can use custom timeout errors

- go.mod
- go.sum
- integration/query_frontend_test.go
- vendor/github.com/grafana/e2e/metrics.go
- vendor/modules.txt
Following the changes in #10798, query-frontend integration tests can fail with:
```
query_frontend_test.go:375: 
Error Trace:	/home/runner/work/mimir/mimir/integration/query_frontend_test.go:375
/home/runner/work/mimir/mimir/integration/query_frontend_test.go:49
Error:      	Received unexpected error:
unable to find metrics [cortex_frontend_split_queries_total] with expected values. Last error: <nil>. Last values: [32]
Test:       	TestQueryFrontendWithBlocksStorageViaFlags
```
This happens when the test is being run between 00:00 and 01:00 UTC, as then the query touches data in 32 different days and so is split 32 ways. 
⚠️ This PR depends on https://github.com/grafana/e2e/pull/20.
#10798
- [n/a] `CHANGELOG.md` updated - the order of entries should be …
> Fix flaky query-frontend integration tests after #10798

- .github/workflows/helm-weekly-release-pr.yaml
This follows the documentation in https://github.com/grafana/shared-workflows/tree/main/actions/get-vault-secrets.
> Use the app token in helm-weekly-release-pr.yml

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/compactor/blocks_cleaner_test.go
- pkg/compactor/compactor.go
- pkg/util/validation/limits.go
Moves definition of `-compactor.max-lookback` from `pkg/compactor/compactor.go` to `pkg/util/validation/limits.go` and adds per-tenant overrides.
Follows: https://github.com/grafana/mimir/pull/10585
> Compactor: make -compactor.max-lookback a per-tenant option 

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Require at least 10 req/sec to the cache to consider alerting on request errors. This avoids noisy alerts in low-traffic clusters
Fixes #10831
> mixin: Add req/sec floor to `MimirCacheRequestErrors`

- go.mod
- go.sum
- vendor/golang.org/x/time/rate/rate.go
- vendor/modules.txt
Upgrade golang.org/x/time from v0.9.0 to v0.11.0. Contains one bug fix:
* [rate: prevent overflows when calculating durationFromTokens](https://go.googlesource.com/time/+/refs/tags/v0.10.0)
> Upgrade golang.org/x/time to v0.11.0

- CHANGELOG.md
Fix CHANGELOG.md ordering in the main / unreleased section, so that `[CHANGE]` entries come before `[FEATURE]` entries, as per our convention.
> CHANGELOG.md: Fix ordering

- Makefile
- mimir-build-image/Dockerfile
- pkg/alertmanager/alertmanagerpb/alertmanager.pb.go
- pkg/alertmanager/alertspb/alerts.pb.go
- pkg/blockbuilder/schedulerpb/scheduler.pb.go
- pkg/distributor/ha_tracker.pb.go
- pkg/frontend/querymiddleware/model.pb.go
- pkg/frontend/v1/frontendv1pb/frontend.pb.go
- pkg/frontend/v2/frontendv2pb/frontend.pb.go
- pkg/ingester/client/ingester.pb.go
- pkg/mimirpb/mimir.pb.go
- pkg/querier/stats/stats.pb.go
- pkg/ruler/ruler.pb.go
- pkg/ruler/rulespb/rules.pb.go
- pkg/scheduler/schedulerpb/scheduler.pb.go
- pkg/storage/indexheader/indexheaderpb/sparse.pb.go
- pkg/storegateway/hintspb/hints.pb.go
- pkg/storegateway/storepb/cache.pb.go
- pkg/storegateway/storepb/rpc.pb.go
- pkg/storegateway/storepb/types.pb.go
Upgrade [github.com/gogo/protobuf/protoc-gen-gogoslick](https://github.com/gogo/protobuf/tree/master/protoc-gen-gogoslick) to its latest version, i.e. v1.3.2.
It has the following bug fixes:
* skippy peanut butter
* proto/buffer: fix proto.Buffer marshaling.
* plugin/gostring: generate values instead of pointers when a field is repeated and non-nullable.
* protoc-gen-gogo/generator: Generate json and custom tags for oneof
* plugin/marshalto: Use ProtoSize() in MarshalTo when enabled for oneof fields.
> Upgrade github.com/gogo/protobuf/protoc-gen-gogoslick to v1.3.2

- docs/sources/mimir/configure/configure-otel-collector.md
This PR adds documentation for OTel resource attributes being automatically promoted to labels in Mimir.
Fixes https://github.com/grafana/mimir-squad/issues/2727
> updates doc on otel resource attributes promoted to labels

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
- pkg/distributor/errors.go
Modify distributor to return specific error message when burst size limit exceeded, including the item count.
Fixes #10833.
> Distributor: Return specific error message when burst size limit exceeded

- Makefile
- go.mod
- mimir-build-image/Dockerfile
This bumps the golang versions to patch releases that have fixes for the following CVEs:
* [CVE-2024-45336](https://nvd.nist.gov/vuln/detail/CVE-2024-45336)
* [CVE-2024-45341](https://nvd.nist.gov/vuln/detail/CVE-2024-45341)
* [CVE-2025-22866](https://nvd.nist.gov/vuln/detail/CVE-2025-22866)
> Bump go versions

- go.mod
- go.sum
- vendor/github.com/prometheus/alertmanager/dispatch/dispatch.go
- vendor/github.com/prometheus/alertmanager/store/store.go
- vendor/modules.txt
- Upgrades prometheus-alertmanager to include a race condition fix from upstream in the dispatcher code
- Upstream: https://github.com/prometheus/alertmanager/pull/3826
- Cherry-pick: https://github.com/grafana/prometheus-alertmanager/pull/98
> Alerting: upgrade alertmanager to apply dispatcher race condition fix

- docs/configurations/prometheus-frontend.yml
- docs/sources/mimir/configure/configure-the-query-frontend-work-with-prometheus.md
Instead of using an empty value for the Prometheus HTTP prefix on the query-frontend API, use the root path `/` which is the intended behavior. Using an empty value for the configuration resulted in the default value being used instead.
Fixes #10786
> docs: Use correct value for Prometheus HTTP prefix

- pkg/ingester/ingester_ring.go
It was deprecated in Mimir 2.2 and was removed in Mimir 2.4. Remove the code that warns when trying to use the flag.
> chore: Remove long-since deprecated `ingester.ring.join-after` flag

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- vendor/github.com/grafana/dskit/cache/memcached_client.go
- vendor/github.com/grafana/dskit/dns/miekgdns2/resolver.go
- vendor/github.com/grafana/dskit/dns/provider.go
- vendor/modules.txt
Update to https://github.com/grafana/dskit/commit/8abd91ce153f15ce4852d7f51e243816b3855eb8 to pull in grafana/dskit#660. This adds an additional experimental DNS backend for service discovery of Memcached servers that is disabled by default.
Notable changes:
* Does not use search domains
* Always uses TCP instead of UDP
* Keeps connections to the server open if possible
* Retries on timeouts and other network issues
Related grafana/dskit#660
> Update to latest dskit commit for DNS resolver improvements

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
Currently when a partition was active and goes idle, its kafka commit point stays in the past. Once that partition gets active, block builder will try to consume every 1h interval since the last commit.
For example if the last commit was on 2025-02-15 00:00 before it went idle, and then later it became active on 2025-03-05, then it would try consuming every hours since Feb 15 to Mar 5, which takes forever to catch up. 
This PR shortcuts this and once it finds that the first record is in the 'future', it shortcuts to the first consumable record or the latest consumption cycle - whichever is earlier.
> Catch up faster when an idle partition becomes active after some time

- development/mimir-ingest-storage/dev.dockerfile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
Increases the delve version for mimir-ingest-storage development since the current version is not compatible with go 1.24.
N/A
> Increase delve version for mimir-ingest-storage development

- docs/sources/helm-charts/mimir-distributed/get-started-helm-charts/_index.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-from-single-zone-with-helm.md
- docs/sources/helm-charts/mimir-distributed/migration-guides/migrate-helm-chart-4.x-to-5.0.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v3.2.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v4.0.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v5.0.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/configure-helm-ha-deduplication-consul/index.md
For https://github.com/grafana/website/issues/24017
Removes all relref shortcodes.
Created-By: reverse-changes
Repository: grafana/mimir
Website-Pull-Request: https://github.com/grafana/website/pull/24630
> [v5.5.x] Remove relref shortcodes

- CHANGELOG.md
- pkg/distributor/push.go
- pkg/distributor/push_test.go
We used to allow content type == text/plain for Prometheus remote write v1 push. Let's continue to not impact users.
Fixes : N/A (support case)
Follows: #10423 
> fix(distributor): relax content-type check

- RELEASE.md
2.16 release process is starting this week: #10917
> chore: Update release dates for 2.16 and 2.17

- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push_test.go
Modify OTLP distributor endpoint to set the `Content-Length` header on responses. Follow-up to #10852, where @charleskorn suggested we set also `Content-Length`.
Also improve OTLP tests to check for `Content-Type` and `Content-Length` headers, for both protobuf and JSON requests.
> OTLP: Set Content-Length header on responses

- .github/workflows/test-build-deploy.yml
**What this PR does / why we need it**:
It's mostly unmaintained now and its advice is often at odds with the guidance of Writers' Toolkit. New rules are written with Vale: https://grafana.com/docs/writers-toolkit/review/lint-prose/
> Remove doc-validator job

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/util/validation/limits.go
The feature to cache non-transient errors has been enabled in Grafana Cloud for months at this point with no issues. Marking the feature as stable.
Related #9028
> Mark error-caching feature as stable

- CHANGELOG.md
Add a version entry for 2.16-rc.0 so that all new entries in the changelog are in the unreleased section.
https://github.com/grafana/mimir/issues/10917
> Cut changelog for 2.16 RC

- CHANGELOG.md
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
Backport of https://github.com/grafana/mimir/pull/10915
* Fix goroutines and memory leak in parallelStorageShards
Signed-off-by: Marco Pracucci <marco@pracucci.com>
* Fix issues
Signed-off-by: Marco Pracucci <marco@pracucci.com>
* Fix issues
Signed-off-by: Marco Pracucci <marco@pracucci.com>
* Update CHANGELOG
Signed-off-by: Marco Pracucci <marco@pracucci.com>
---------
Signed-off-by: Marco Pracucci <marco@pracucci.com>
(cherry picked from commit 4226b7015112ac5576f09b9538ea7eaf7288be13)
> [release-2.16] Fix goroutines and memory leak in parallelStorageShards (#10915)

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-ruler.json
- operations/mimir-mixin-compiled/dashboards/mimir-ruler.json
- operations/mimir-mixin/dashboards/ruler.libsonnet
the rate of dropped notifications in the previous version was out of context so it was hard to determine if we were dropping all notifications or only a portion of them. This PR puts some absolute numbers and combines dropped with errors in a single panel
**Before** 
**After**
> mixin: include absolute value of ruler notifications

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
The warning can go unnoticed, so if we have deployments or statefulsets that are not fully deployed within 6h, we should send out a critical alert
> `MimirRolloutStuck`: critical if over 6h

- CHANGELOG.md
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-tenants.json
- operations/mimir-mixin/dashboards/tenants.libsonnet
The tenants dashboard previously used hardcoded values (`pod`) for the legends of the following panels:
- `In-memory series per ingester`
- `Owned series per ingester`
In baremetal deployments, the `per_instance_label` is often overridden with something more meaningful like `instance`. Since the `pod` label does not exist in such cases, the legend popup displayed all labels, making it unreadable.
By using a variable for the legend values, the dashboard now correctly handles both "cloud" and "baremetal" deployments.
None
> fix(mixin/dashboards/tenants): use 'per_instance_label' for legend

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/rulestore/config.go
- pkg/ruler/storage.go
When caching is configured for the ruler, cache the contents of rule groups. This removes the experimental CLI flag to enable or disable this specific functionality when caching was configured for the ruler.
Related #9595
> ruler: Cache rule group contents if caching is configured

- pkg/mimirtool/analyze/ruler.go
- pkg/mimirtool/commands/rules.go
- pkg/mimirtool/commands/rules_test.go
- pkg/mimirtool/rules/compare.go
- pkg/mimirtool/rules/compare_test.go
- pkg/mimirtool/rules/parser_test.go
- pkg/mimirtool/rules/rules.go
- pkg/mimirtool/rules/rules_test.go
- pkg/ruler/manager.go
- pkg/ruler/mapper_test.go
- pkg/ruler/ruler_test.go
- pkg/ruler/rulespb/compat.go
- pkg/ruler/rulespb/compat_test.go
- pkg/ruler/rulestore/bucketclient/bucket_client_test.go
- pkg/ruler/rulestore/local/local_test.go
Updates lots of things except the hard one so far. (rule.Validate())
Several buckets of tests now pass that didn't before - rulestore, isolated mimirtool tests, anything not in the chain of one of our two Validate calls.
Linter and CI should fail because it leaves compile errors around validate(). this pr should never target main branch
> Update ruler and mimirtool to deal with modified ruler core models

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/ci/offline/test-enterprise-values.yaml
- operations/helm/charts/mimir-distributed/templates/_helpers.tpl
- operations/helm/charts/mimir-distributed/templates/provisioner/provisioner-job.yaml
- operations/helm/charts/mimir-distributed/templates/provisioner/provisioner-rbac.yaml
- operations/helm/charts/mimir-distributed/templates/provisioner/provisioner-serviceaccount.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/provisioner/provisioner-job.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/provisioner/provisioner-rbac.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/provisioner/provisioner-serviceaccount.yaml
Grafana's Federal Cloud offering needs to utilize [enterprise provisioner](https://github.com/grafana/enterprise-provisioner) via configuration to ensure tenants are created properly in a security constrained environment. This change provides consistent tenant management across Grafana products (aligning with Loki and Tempo).
This PR adds an optional job that runs via helm post-install hook that calls the Grafana Enterprise Provisioner app to create tenants, access policies and tokens via the admin api based on configuration in the helm values.
Fixes #10864 
Fixes #deployment_tools/211067
- [ x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
> helm: adds optional provisioner job to helm chart

- .github/workflows/backport.yaml
- .github/workflows/helm-weekly-release-pr.yaml
- .github/workflows/scripts/helm-weekly-release.sh
This is the follow-up to #10819, #10820, etc.
The two workflows (backport and weekly-helm-release) don't need the private token to do the job. That is, these workflows only open a new PR, and, thus, don't act as a "maintainer". Switching the workflows to the temporal auto-generated `GITHUB_TOKEN` (ref [GitHub docs][1]) makes two things simpler:
1. We can use private Mimir token to auto-review the weekly PRs (this has been [broken since forever](https://github.com/grafana/mimir/pull/10254#issuecomment-2560989258)).
2. Backporting of the PRs opened by the contributors will just work, because the contributors won't try to access the private Vault — it's [broken now](https://github.com/grafana/mimir/actions/runs/13930549296)).
Closes #10828 (mine fixes the same problem but in a simpler way). …
> Simplify github workflows to use auto-generater CI token

- renovate.json5
Configure Renovate to exclude the `google.golang.org/grpc` dependency, since we pin it through a `replace` directive.
> Renovate: Exclude grpc dependency

- docs/sources/helm-charts/mimir-distributed/_index.md
- docs/sources/helm-charts/mimir-distributed/release-notes/v5.7.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/values.yaml
Update Mimir to 2.16.0-rc.0 image versions and update the chartversion to 5.7.0-rc.0. Note that the GEM RC version doesn't exist yet and so hasn't been updated.
> [mimir-distributed-release-5.7] Update Mimir and GEM image versions

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
This metric was added in #9400 to assess the Prometheus 3.0 changes.
It is not needed anymore.
Relates to #9400
> Remove `cortex_distributor_label_values_with_newlines_total`

- CHANGELOG.md
- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/tenants.libsonnet
- operations/mimir-mixin/dashboards/top-tenants.libsonnet
This allows us to see the amount of successful/failing requests for every tenant 
Also, panels were added to the "Top Tenants" dashboard so we can see the biggest contributors of gateway load
> mixin: Add dashboard panels for per-tenant gateway metrics

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
Adds a dedicated function that consumes between given start and end offset with no partially consumed region. This is only for the use of scheduler.
> block-builder: Dedicated consumePartitionSectionPullMode for the scheduler

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/state_replication.go
- pkg/alertmanager/state_replication_test.go
When the Grafana configuration is promoted, Mimir fetches the Grafana state from object storage and merges it with its own, incorporating any silences and nflog entries. After merging the Grafana state and broadcasting it to other pods, it deletes it from object storage. The resulting state is persisted as normal Mimir Alertmanager state.
As we use upstream code to perform the state merge, [oversized messages are dropped](https://github.com/grafana/mimir/blob/d6c7e94e46d51e7851b15dfa9522c7abfca9f13c/vendor/github.com/prometheus/alertmanager/silence/silence.go#L942-L967). As these oversized silences are not broadcasted, other pods that could not reach the Grafana state before it was deleted won't have those silences.
<details><summary>Grafana Alertmanager tenants with silences larger than …
> Alertmanager: Broadcast oversized Grafana state

- CHANGELOG.md
- pkg/ingester/metrics.go
- pkg/ingester/metrics_test.go
Expose per-user versions of prometheus metrics added in https://github.com/prometheus/prometheus/pull/16166
Metrics are only exported when non-zero, so overall increase in metric count should be minimal.
> Expose per-user metrics for unknown series references during WAL/WBL replay

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
This PR fixes the issue where the `parser.Statement` returned by a MQE `Query` does not have the correct lookback delta set if the engine default or global default is being used.
As far as I can see, nothing uses this information, so there was no impact to this, but wanted to tidy it up before it did cause a problem.
(none)
> MQE: set correct lookback delta on statement

- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/data.go
- pkg/streamingpromql/types/data_test.go
This PR refactors the `Query` type to avoid using the `EvalStmt` where possible.
This will make it easier to introduce queries based on query plans, as query plans may not have an equivalent PromQL statement.
(none)
> MQE: avoid using statement in `Query` where possible

- pkg/mimir/mimir.go
- pkg/usagetracker/partition.go
- pkg/usagetracker/tracker.go
- pkg/usagetracker/tracker_partition_ring.go
- pkg/usagetracker/tracker_test.go
Adds the readiness check endpoint to usage-tracker.
Also adds tests for usage-tracker partition assignment logic in order to keep this new code tested (as well as testing previously untested partition reconciliation).
I tried to make sure that they're not flaky:
```
~/w/github.com/grafana/mimir on  usage-tracker-partition-assignment-tests 11:19:43
$ go test -count=10 -run=TestUsageTracker_PartitionAssignment ./pkg/usagetracker
ok  	github.com/grafana/mimir/pkg/usagetracker	17.751s
~/w/github.com/grafana/mimir on  usage-tracker-partition-assignment-tests 11:20:37
$ go test -count=100 -run=TestUsageTracker_PartitionAssignment ./pkg/usagetracker
ok  	github.com/grafana/mimir/pkg/usagetracker	179.885s
```
Please note that this is going to be merged to `usage-tracker` branch, not `main`.
> Add readiness check and partition assignment tests to usage tracker

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
- pkg/ingester/ingester.go
- pkg/ingester/metrics.go
The `MimirIngesterFailsToProcessRecordsFromKafka` alert currently fires each time there a forced TSDB head compaction in progress, because samples older than the new "head min time" will fail to be ingested (will be retried over and over, until the head compaction completes).
I would like to have the alert not firing during forced head compaction, given it's not actionable, but we miss a metric to know when there's a forced head compaction in progress. In this PR I'm adding a metric and using it in the alert. The alert query has been changed so that it keep working even if the new metric has not been deployed it.
N/A
> Improve MimirIngesterFailsToProcessRecordsFromKafka to not fire during forced TSDB head compaction

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/storage/ingest/config.go
- pkg/storage/ingest/config_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_client.go
- pkg/storage/ingest/reader_test.go
I would like to experiment with an higher value of Fetch "max wait". In this PR I propose to add `-ingest-storage.kafka.fetch-max-wait` configuration option to configure the maximum amount of time a Kafka broker waits for some records before a Fetch response is returned.
N/A
> Add -ingest-storage.kafka.fetch-max-wait configuration option

- CHANGELOG.md
- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/reader.go
I'm trying to better understand what's the actual `MaxBytes` we specify in Fetch requests, but there's no metric tracking its distribution. In this PR I'm proposing to add the `cortex_ingest_storage_reader_records_batch_fetch_max_bytes` metric reporting the distribution of `MaxBytes` specified in the Fetch requests sent to Kafka.
Example from local dev env:
N/A
> Add cortex_ingest_storage_reader_records_batch_fetch_max_bytes metric

- pkg/distributor/distributor_test.go
The wrong error message was expected, making the benchmark fail.
The creation of the write request should not count in the benchmark because a) not part of Push() b) it will be different for remote write 2.0.
Related to #9072
> Fixes to the distributor push benchmark

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/storage/remote/client.go
- vendor/modules.txt
This updates mimir-prom to https://github.com/grafana/mimir-prometheus/pull/859
N/A
Very minor update.
> Update mimir-prom to v1.8.2-0.20250326171450-97c8191bd4dc

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
- pkg/blockbuilder/config_test.go
Fixes a panic when `OutOfOrderBlocksExternalLabelEnabled` is set for a tenant.
> block-builder: Fix a panic for out-of-order samples

- CHANGELOG.md
- docs/sources/mimir/manage/tools/mimirtool.md
- pkg/mimirtool/commands/analyse.go
- pkg/mimirtool/commands/promql.go
- pkg/mimirtool/commands/rules.go
Adds a flag to Mimirtool commands that parse PromQL expressions to enable the parsing of experimental PromQL expressions.
Fixes #10980.
> Mimirtool: Add flag for enabling experimental PromQL function parsing

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
As the title says. More info in the updated code comments.
> Block builder: fix an infinite loop when attempting fast catchup on an idle partition

- pkg/storage/ingest/fetcher_test.go
In #11014 I've added the `assertFetchMaxBytesMetric()` assertion in some tests. This introduced some flakyness for `TestConcurrentFetchers_fetchSingle/should_return_an_empty_non-error_response_if_context_is_canceled` because the request may or may not issued based on when the cancel is captured (running in a different goroutine it's non-deterministic). We don't really need the assertion for that specific test case (we do for others), so we can simply remove it.
Fixes #11034
> Fix TestConcurrentFetchers_fetchSingle flaky test

- .golangci.yml
- Makefile
- mimir-build-image/Dockerfile
- pkg/frontend/transport/handler.go
- pkg/ruler/notifier.go
Upgrade golangci-lint to v1.64.8 and faillint to v1.15.0. Fixing issues found by linters.
> Upgrade golangci-lint to v1.64.8

- pkg/ingester/client/streaming.go
- pkg/querier/block_streaming.go
This PR silences some log noise from ingester and store-gateway chunks streaming that occurs when a query request is cancelled or aborted.
Previously, messages like the following could be logged when a request was cancelled:
```
caller=streaming.go:109 method=SeriesChunksStreamReader.StartBuffering user=test level=error msg="received error while streaming chunks from ingester" err="rpc error: code = Canceled desc = context canceled"
```
These messages aren't helpful and can be a distraction when trying to understand what actually happened.
I don't believe this change is significant enough to warrant a changelog entry.
#10861
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, …
> Don't log context cancellation as an error while streaming chunks

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/_helpers.tpl
- operations/helm/tests/enterprise-https-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/large-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/small-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/test-enterprise-configmap-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/test-oss-k8s-1.25-values-generated/mimir-distributed/templates/mimir-config.yaml
- operations/helm/tests/test-oss-values-generated/mimir-distributed/templates/mimir-config.yaml
Fix the default memcached address to use `dnssrvnoa` instead of `dns` to avoid conflicts/rebalancing on the hashing algorithm when a memcached pod is restarted
This is the default in [Loki](https://github.com/grafana/loki/blob/b442d27fa6a0f9819d679c960ed5f396cbec199e/production/helm/loki/values.yaml#L210)
Thanks Gergely Madarász for raising this up on [Slack](https://grafana.slack.com/archives/C039863E8P7/p1742550271473749)
> fix: Use dnssrvnoa to connect to memcached instances

- renovate.json5
Mimir 2.16 is releases so 2.14 no longer gets automatic updates.
> chore: Remove release-2.14 from automated updates

- CHANGELOG.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
When tenant federation is used and a query request has multiple tenants with different retention period, we should clamp the request time range based on the tenant with the largest retention and not the smallest retention. This PR fixes it.
For more details, see: https://github.com/grafana/mimir/issues/9727#issuecomment-2761898142
Fixes #9727
> Fix blocks retention period enforcement in the query-frontend when a request has multiple tenants (tenant federation)

- pkg/storage/ingest/reader_test.go
This PR is a follow up of #9428. Assuming the direction in that PR is the right one, then we need to use the synchronized and shared logger in `newKafkaProduceClient()` (which is used by `TestPartitionReader_ConsumeAtStartup`) and other tests. This change may fix the race condition described in https://github.com/grafana/mimir/issues/10686 (I haven't been able to reproduce it, so I'm not sure it's enough to fix it).
Maybe #10686
> Maybe fix TestPartitionReader_ConsumeAtStartup race condition

- CHANGELOG.md
- pkg/compactor/bucket_compactor.go
- pkg/storage/indexheader/header_test.go
- pkg/storage/indexheader/lazy_binary_reader_test.go
- pkg/storage/indexheader/reader_pool.go
- pkg/storage/indexheader/reader_pool_test.go
- pkg/storage/indexheader/stream_binary_reader.go
- pkg/storage/indexheader/stream_binary_reader_test.go
- pkg/storegateway/bucket_test.go
This fixes an issue where the `thanos_objstore_bucket_operation_failures_total` metric is incremented when trying to access a sparse-index-header that's not expected to exist. This issue could cause the `MimirStoreGatewayTooManyFailedOperations` alert to fire unexpectedly, and particularly if when `compactor.upload-sparse-index-headers` is not set.
This change replaces `objstore.BucketReader` with `objstore.InstrumentedBucketReader` in several locations in `pkg/storage/indexheader` so that we can use `ReaderWithExpectedErrs(IsOpFailureExpectedFunc)` (see: [IsOpFailureExpectedFunc](https://pkg.go.dev/github.com/thanos-io/objstore#IsOpFailureExpectedFunc)) to ignore certain errors.
> Store-Gateway: Don't Increment thanos_objstore_bucket_operation_failures_total on failed Sparse Index Header GET 

- integration/backward_compatibility.go
Include Mimir 2.16 in the versions tested for backwards compatibility.
> test: Update backwards compatibility integration test for 2.16

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/querier/blocks_store_replicated_set.go
- pkg/querier/blocks_store_replicated_set_test.go
- pkg/querier/querier.go
- pkg/querier/store_gateway_client.go
This PR exposes CLI flags and config file options for configuring the store-gateway client used by queriers.
This makes it consistent with other gRPC clients, such as the one used for ingesters.
(none)
> Allow configuring all gRPC options for store-gateway client used by queriers

- CHANGELOG.md
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
This PR modifies the ruler to log the number of returned series for each query as part of the existing `query stats` log message.
This is useful when trying to identify the source of an unexpectedly high number of alert notifications being sent by a ruler instance.
(none)
> Log the number of series returned in ruler query stats messages

- pkg/streamingpromql/testdata/ours-only/aggregators.test
- pkg/streamingpromql/testdata/ours/aggregators.test
- pkg/streamingpromql/testdata/ours/binary_operators.test
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/ours/histograms.test
- pkg/streamingpromql/testdata/ours/native_histograms.test
- pkg/streamingpromql/testdata/ours/subqueries.test
- tools/format-promql-test.sh
https://github.com/prometheus/prometheus/pull/15995 introduced a new syntax for annotation assertions in PromQL test files.
This PR updates our test cases to use the new syntax, and updates the formatting script to enforce that the old syntax is not used.
(none)
> Update PromQL test syntax to use new style

- CHANGELOG.md
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
Instant queries don't set `Hints.TotalQueries` because they're not split by time (only range queries do). This means that we never enforce `-query-frontend.query-sharding-max-sharded-queries` when the query has 1+ binary operators. This PR fixes it, assuming that if `TotalQueries` is unknown then it's just 1.
N/A
> Fix -query-frontend.query-sharding-max-sharded-queries enforcement for instant queries with binary operators

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
There were two limits for cost attribution labels:
- One configurable per tenant which we added because at some point tenants would self-serve this configuration (I insisted), but it doesn't really make sense to have it _here_, because it's too late in the pipeline. If there's a component rendering the runtime self-served configurations, it should enforce the labels amount there. Checking it here just makes the overrides loading fail.
- The other one, hard limit of 4 labels, was enforced by some technical detail we had in the first implementation (somewhere we had an array and we had to have an upper bound on it?), but it doesn't exist anymore, so we can remove it.
Follow up on https://github.com/grafana/mimir/pull/10269
> Cost attribution: remove `max_cost_attribution_labels_per_user` limit

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/costattribution/manager.go
- pkg/costattribution/testutils/test_utils.go
- pkg/distributor/distributor_test.go
- pkg/ingester/ingester_test.go
- pkg/util/validation/limits.go
All limits/overrides are "per user", having a per-user config with per-user suffix is confusing and inconsistent, so I'm removing that suffix.
Fixes consistency.
> Cost attribution: remove suffix from max cardinality config

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/Chart.yaml
- operations/helm/charts/mimir-distributed/README.md
- operations/helm/charts/mimir-distributed/values.yaml
Bump chart version to rc.1 and include Mimir 2.16.0 final.
> [mimir-distributed-release-5.7] Update mimir version to 2.16.0

- pkg/distributor/distributor_test.go
This fixes the polling bit in this test that was intended to retry when not all `mockIngester`s had yet received the push. The problem was the initial asserts inside the poll had failed while the ultimate return value of the polled function _did_ match the expected values. So the Poll would exit with a failed assertion instead of retrying.
Would fail 1-5x per hundred runs before the fix.
Fixes #10935
> Deflake test `TestDistributor_LabelValuesCardinality`

- CHANGELOG.md
- pkg/frontend/config.go
- pkg/frontend/frontend_test.go
In https://github.com/grafana/mimir/pull/11010 we added support for configuring cluster validation label for HTTP clients called by the query-frontend. These HTTP clients are queriers, hence in case of cluster validation errors, the `client` label of the `cortex_client_request_invalid_cluster_validation_labels_total` metrics should be `querier`, and not `query-frontend`, as https://github.com/grafana/mimir/pull/11010 reported. The present PR fixes this.
> HTTP cluster validation: fixing wrong client name

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/blockbuilder_test.go
without this we were getting misleading error logs here
https://github.com/grafana/mimir/blob/961ad26da672ba89af27cd0d38190be9f807e73f/pkg/blockbuilder/blockbuilder.go#L520-L523
> block-builder: implement Is on errFirstRecordInFuture

- CHANGELOG.md
- Makefile
- go.mod
- mimir-build-image/Dockerfile
Upgrade Go in build image to v1.24.2 and alpine/helm base image to 3.17.2.
> Upgrade Go to v1.24

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/planning.go
- pkg/streamingpromql/planning_test.go
This PR builds on the query planner introduced in https://github.com/grafana/mimir/pull/11004 and introduces latency metrics for each of the query planning stages.
https://github.com/grafana/mimir/pull/11004
> MQE: emit query planning latency metrics

- Makefile
- mimir-build-image/Dockerfile
Upgrade build image to [google.golang.org/protobuf/cmd/protoc-gen-go](https://github.com/protocolbuffers/protobuf-go/tree/master/cmd/protoc-gen-go)@v1.36.6, since github.com/golang/protobuf/protoc-gen-go is deprecated.
> mimir-build-image: Upgrade to google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6

- pkg/alertmanager/notify_hooks_notifier.go
- pkg/alertmanager/notify_hooks_notifier_test.go
Extend the recently added experimental pre-notify hooks to include the tenant ID
in the X-Scope-OrgID header of the upstream request.
> Alertmanager: Propagate tenant to pre-notify hooks.

- pkg/streamingpromql/planning/core/aggregate_expression.go
- pkg/streamingpromql/planning/core/binary_expression.go
- pkg/streamingpromql/planning/core/function_call.go
- pkg/streamingpromql/planning/core/matrix_selector.go
- pkg/streamingpromql/planning/core/number_literal.go
- pkg/streamingpromql/planning/core/string_literal.go
- pkg/streamingpromql/planning/core/subquery.go
- pkg/streamingpromql/planning/core/unary_expression.go
- pkg/streamingpromql/planning/core/vector_selector.go
- pkg/streamingpromql/planning/plan.go
This PR introduces a `ResultType` method for the query planner `Node` interface.
This will allow optimization passes to correctly handle nodes that produce different kinds of values. 
I'm raising this as a separate PR in the interests of keeping the upcoming common subexpression elimination PR smaller.
(none)
> MQE: introduce `ResultType` method for query planner `Node`

- CHANGELOG.md
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
- pkg/querier/stats/stats.pb.go
- pkg/querier/stats/stats.proto
This PR adds cortex_query_samples_processed_total metric to keep track of actually processed samples per tenant.
> Query Frontend: Expose samples_processed in a metric

- pkg/storage/ingest/fetcher.go
- pkg/storage/ingest/fetcher_test.go
- pkg/storage/ingest/reader.go
`TestConcurrentFetchers_fetchSingle` is flaky because it races with the fetch run by the fetchers goroutine. Since we want to test `fetchSingle()` in isolation, we shouldn't start the goroutines. In this PR I propose to fix it adding an explicit `Start()` function to `concurrentFetchers`, so we can control when starting them.
Fixes #11085
> Fix flaky TestConcurrentFetchers_fetchSingle

- renovate.json5
Disable Renovate's dependency dashboard, as otherwise we have to manually approve for it to open PRs to make major version updates. We just want the PRs.
> Renovate: Disable dependency dashboard

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/query_frontend_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/spin_off_subqueries.go
- pkg/frontend/querymiddleware/spin_off_subqueries_test.go
- pkg/util/validation/limits.go
We have enabled the feature in all of our cells internally, and we don't use any regexp other than `.*`. It's unnecessary processing to run a regexp for each request
> frontend: Enable subquery spin-off with boolean instead of regexp

- CHANGELOG.md
The changes from https://github.com/grafana/mimir/pull/10216 were mentioned in the 2.15.0 changelog by accident. The PR landed into the main branch right around the time when the 2.15-rc.0 was in the cooks, so the change in the changelog got slipped into the file.
This is confusing to users, who expect the feature to be available. Refer to https://github.com/grafana/mimir/issues/11088
> Fix changelog for 2.15/2.16

- CHANGELOG.md
This is the backport of https://github.com/grafana/mimir/pull/11155 into relelase-2.15
> Fix changelog for 2.15.0

- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
This PR is a follow up of https://github.com/grafana/mimir/pull/10107. I have more uses cases where I need to conditionally enable the artificial delay (for testing purposes) on a large number of tenants that may change over time. The two specific use cases are:
- Add latency to tenants with a numeric ID greater than X
- Add latency to tenants with configured max global series < Y
In this PR I'm adding more config options to support such use cases (hidden from the doc, given they're for testing purposes).
N/A
> Add conditional artificial delay

- CHANGELOG.md
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
Adds an optional jsonnet field that allows overriding of the HPA behavior fields in the ingest storage ingester scaledObject. This allows for more flexible configuration of the scale up/down policies.
Fixes #N/A
> Make ingest-storage ingester HPA behavior configurable

- pkg/distributor/ha_tracker_test.go
…edDeletedThenKVStoreUpdateIsNotFailing
Adds logging so we can observe what is happening with TestHaTrackerWithMemberlistWhenReplicaDescIsMarkedDeletedThenKVStoreUpdateIsNotFailing
Part of https://github.com/grafana/mimir/issues/10687#issuecomment-2754747637
> test: add logging to TestHaTrackerWithMemberlistWhenReplicaDescIsMaredDeletedThenKVStoreUpdateIsNotFailing

- pkg/streamingpromql/types/limiting_pool.go
When getting a slice of histogram points from a memory pool, use an estimated size for each point that is closer to the actual size of a `FloatHistogram` even though the histogram is not stored directly in the slice, only a pointer to it. This makes tracked memory usage closer to reality even if not perfect.
We use a fixed size for each `HPoint` instead of tracking the size of `FloatHistograms` when they are created because float histograms can change size during usage. This would require updating the tracked memory usage accurately and constantly in many different places.
Internal issue
> MQE: use more accurate estimation of histogram point size

- operations/mimir-mixin/dashboards/writes.libsonnet
This PR changes the title in the ingester queued requests panel to use "queued" rather than "blocked" requests, as there's more precedent for queued and the meaning is more clear than blocked.
> Change title in ingester queued requests panel

- tools/benchmark-query-engine/main.go
This PR fixes an issue where the MQE benchmarking tool could run benchmarks that did not match the provided filter, or run multiple benchmarks in the same process, producing incorrect peak memory consumption data.
This happens because `go test`'s `-bench` flag takes the value provided and splits it on `/`, then treats each part as a separate regex. This is problematic when using a name like `BenchmarkQuery/a_100, instant query/engine=Mimir`, as this will match any benchmark with `a_100, instant query` in the second part (eg. `1 + a_100, instant query`). So we need to ensure that each part is set to match the full string of that part.
(none)
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, …
> MQE: fix issue where benchmark tool could run unexpected benchmarks

- pkg/streamingpromql/engine.go
- pkg/streamingpromql/operators/aggregations/quantile.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/range_query.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/or_binary_operation.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/operators/binops/vector_scalar_binary_operation.go
- pkg/streamingpromql/operators/deduplicate_and_merge.go
- pkg/streamingpromql/operators/functions/absent.go
- pkg/streamingpromql/operators/functions/absent_over_time.go
- pkg/streamingpromql/operators/functions/function_over_instant_vector.go
- pkg/streamingpromql/operators/functions/function_over_range_vector.go
- pkg/streamingpromql/operators/functions/histogram_quantile.go
- pkg/streamingpromql/operators/functions/sort.go
- pkg/streamingpromql/operators/operator_buffer.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector.go
- pkg/streamingpromql/operators/selectors/range_vector_selector.go
- pkg/streamingpromql/operators/test_operator.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/operator.go
This PR modifies MQE's behaviour when evaluating binary operations to close their inner operators as soon as they're no longer needed.
This allows those inner operators to then free resources that might otherwise remain until query evaluation has finished. This is particularly important for cases where only a subset of series from one side match the other side, and so some intermediate state might be unnecessarily held by inner operators until the query finishes.
This PR also clarifies that it is expected that calling `Close` on an operator multiple times should be safe, and extends pedantic mode to call `Close` on the query's root operator a second time to ensure this is true.
(none)
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should …
> MQE: close inner operators of binary operations as early as possible

- CHANGELOG.md
- pkg/distributor/distributor.go
- pkg/distributor/influx.go
- pkg/distributor/otel.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/distributor/request.go
This PR reports added `artificialDelay` as part of the `ServerTiming` header on push requests.
> Report `artificialDelay` on `ServerTiming` header for push requests

- CODEOWNERS
`grafanabot` is no longer with us, as all automation was moved to GitHub apps. We can kick the bot out of the list of code owners.
> codeowners: kick grafanabot out

- operations/mimir-mixin/dashboards/reads.libsonnet
Similar to #[11186](https://github.com/grafana/mimir/pull/11186), but for read requests.
- Renames the ingester queued requests panel title
- Fixes the inflight requests limits panel title
> Renames the ingester queued read requests panel title

- CHANGELOG.md
- docs/sources/mimir/manage/tools/listblocks.md
- tools/listblocks/README.md
- tools/listblocks/main.go
This adds a new `--format` flag for the `listblocks` tool which allows specifying an output format. The default `tabbed` format preserves the old behavior of the tool, while the new formats `json` and `yaml` allow for easier parsing.
The tricky part here was that `listblocks` supports a large number of flags that affect whether a field is in the output. In order to keep that the same between formats a `map[string]any` is first constructed for each block. If a field won't be in the output then it isn't in the map. The JSON/YAML marshal calls are then passed those maps directly and the more involved tabbed output generating function looks similar to before.
Overall this was motivated from my experience of trying to use `listblocks` to estimate the total size of blocks for a user. The …
> listblocks: add json/yaml output format

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin/dashboards/alertmanager.libsonnet
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- NPS panels for on-prem customers might display gaps since we've added `WithSkipZeroValueMetrics` for some metrics (e.g. [alertmanager_notifications_total](https://github.com/grafana/mimir/blob/main/pkg/alertmanager/alertmanager_metrics.go#L343-L343))
> Alertmanager: fix mixin queries for ignored zero value metrics

- CHANGELOG.md
- pkg/util/validation/exporter/exporter.go
- pkg/util/validation/exporter/exporter_test.go
This PR updates the overrides-exporter so it didn't expose the per-tenant `cortex_limits_overrides` metrics for the overrides, that have default values.
We've observed that in large shared cells, configuring tenants with the limits, explodes the number of `cortex_limits_overrides` series, even if the configured limits aren't in the set of configured `EnabledMetricNames`.
> overrides-exporter: don't export default value overrides as metrics

- pkg/streamingpromql/operators/functions/sort.go
This PR makes a minor improvement to the implementation of `sort` and `sort_desc` to allow series data to be garbage collected earlier.
(none)
> MQE: don't hold reference to data in `sort`/`sort_desc` for any longer than necessary

- pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/range_query.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/vector_scalar_binary_operation.go
- pkg/streamingpromql/operators/deduplicate_and_merge.go
- pkg/streamingpromql/operators/functions/absent.go
- pkg/streamingpromql/operators/functions/absent_over_time.go
- pkg/streamingpromql/operators/functions/histogram_quantile.go
- pkg/streamingpromql/operators/operator_buffer.go
It is safe to pass a `nil` slice to the `Put` method of a `BucketedPool` or `LimitingBucketedPool`, however some parts of MQE unnecessarily check if a slice is `nil` before calling `Put`. 
This PR makes all places consistent, removing the unnecessary checks.
Addresses https://github.com/grafana/mimir/pull/11162#discussion_r2035802201
> MQE: make `nil` checks consistent in operator `Close` methods

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-overview.json
- operations/mimir-mixin-compiled/dashboards/mimir-alertmanager.json
- operations/mimir-mixin-compiled/dashboards/mimir-overview.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- remove ruler changes introduced in #11197 
- fixes to the NPS panel queries
- [user without failed notifications](https://ops.grafana-ops.net/goto/C4xHbrAHR?orgId=1)
- [user with both total and failed notifications](https://ops.grafana-ops.net/goto/x3dhb90Hg?orgId=1)
> Alertmanager: further fixes to mixin panels for ignored zero value metrics

- pkg/compactor/parquet_compactor.go
- pkg/storage/parquet/cache.go
- pkg/storage/parquet/enc.go
- pkg/storage/parquet/enc_test.go
- pkg/storage/parquet/prometheus_parquet_chunks_encoder.go
- pkg/storage/parquet/reader.go
- pkg/storage/parquet/reader_test.go
- pkg/storage/parquet/row.go
- pkg/storage/parquet/stats.go
- pkg/storage/parquet/stats_test.go
- pkg/storage/parquet/tsdbcodec/reader.go
- pkg/storage/parquet/util_test.go
- pkg/storage/parquet/writer.go
- pkg/storage/parquet/writer_test.go
We want to be able to isolate & unit test this stuff and reading a TSDB block to parquet rows should be general enough that it does not need to be specific to the compactor.
Also updated `pkg/storage/parquet` files to be the package name `pkg/storage/parquet` rather than just `pkg/storage`, to match other storage subpackages.
> move readTsdb to parquet storage sub-package; rename method & vars for clarity & testability

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml
- operations/helm/charts/mimir-distributed/templates/graphite-proxy/graphite-querier/graphite-querier-dep.yaml
- operations/helm/charts/mimir-distributed/templates/graphite-proxy/graphite-write-proxy/graphite-write-proxy-dep.yaml
This PR fixes a helm templating issues when running alertmanager as a deployment and extraVolumes are set either in global or alertmanager sections. 
Fixes #9775
> fix(helm): fix indent for alertmanager-dep.yaml extraVolumes

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/streamingpromql/config.go
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/planning.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/testing.go
This PR removes the last remaining feature toggle for individual functions MQE, as we're now satisfied with the stability of all functions.
#11002
> MQE: remove flag to disable support for specific functions

- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/planning.go
- pkg/streamingpromql/planning_test.go
- pkg/streamingpromql/query.go
This PR changes the behaviour of MQE to create activity tracker entries while running planning or materialization (converting a query plan to operators).
(none)
> MQE: include query planning and materialization in activity tracker

- pkg/api/error/error.go
Add new function `apierror.IsNonRetryableAPIErrorType` so it can be used outside of Mimir.
N/A
Very minor, non-user-facing change.
> Add new function apierror.IsNonRetryableAPIErrorType

- pkg/streamingpromql/benchmarks/README.md
This PR adds a readme to the directory containing MQE's benchmarks, encouraging readers to use `tools/benchmark-query-engine` rather than using `go test` directly.
(none)
> MQE: add readme to benchmarks directory

- pkg/ruler/manager.go
- pkg/ruler/notifier.go
- pkg/ruler/notifier_test.go
- pkg/ruler/service_discovery.go
This is a refactor in support of https://github.com/grafana/mimir/pull/10816 which makes the Alertmanager client config fields (AM url, etc) per-tenant-configurable.
The change above means:
- We need the ability to build notifiers from something that's not necessarily the ruler service config struct (tenant limits, in the future)
- Per the [tenant limit migration process](https://github.com/grafana/mimir/blob/main/docs/internal/contributing/how-to-convert-config-to-per-tenant-limit.md), the fields in the ruler config struct need to be renamed as deprecated in the code. There's a huge number of references to these fields in tests, that are only used to carry fields in and out and aren't being tested directly.
This PR makes `buildNotifierConfig` and friends take their requested fields …
> ruler: Refactor notifier builder to not depend on ruler config struct

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/reactivelimiter.go
- pkg/util/math/ewma.go
- pkg/util/math/ewma_test.go
- pkg/util/math/median.go
- pkg/util/math/median_test.go
- pkg/util/math/windows.go
- pkg/util/math/windows_test.go
- pkg/util/reactivelimiter/blockinglimiter.go
- pkg/util/reactivelimiter/prioritylimiter.go
- pkg/util/reactivelimiter/reactivelimiter.go
- pkg/util/sync/semaphore.go
Since ingesters using ingest storage can become inactive when they switch to read only, and then active again, it makes sense to reset reactive limiters to their initial limit when transitioning back to active.
This PR improves the adaptive limiter implementation to support resetting back to the initial limit. It also updates ingesters using ingest storage and a read reactive limiter to activate or deactivate when the ingester changes state to read only mode or back to active. When deactivating, the limiter resets back to its initial value, which it will use if/when reactivated.
> Activate and deactivate reactive limiter with ingest storage

- CHANGELOG.md
- go.mod
- go.sum
- pkg/alertmanager/multitenant_test.go
- pkg/frontend/frontend_test.go
- pkg/ruler/client_pool_test.go
- vendor/github.com/grafana/dskit/middleware/grpc_cluster.go
- vendor/github.com/grafana/dskit/middleware/http_cluster.go
- vendor/github.com/grafana/dskit/middleware/metrics.go
- vendor/github.com/grafana/dskit/server/metrics.go
- vendor/github.com/grafana/dskit/server/server.go
- vendor/modules.txt
Upgrade to dskit@main ([15fe9b42d47ddac4d4c947def386494a5a39cc60](https://github.com/grafana/dskit/commit/15fe9b42d47ddac4d4c947def386494a5a39cc60)), to get https://github.com/grafana/dskit/pull/680. This adds the `cortex_server_invalid_cluster_validation_label_requests_total` metric.
> Upgrade to dskit@main

- pkg/alertmanager/config.go
- pkg/alertmanager/config_test.go
Previously, while removing duplicate receivers and intermediate map was used and original order was lost. Furthermore, the output order was undefined causing change detection on config syncs to continuously detect a spurious change.
> Grafana Alertmanager: Preserve order while removing duplicate receivers

- CHANGELOG.md
- go.mod
- go.sum
- pkg/alertmanager/multitenant_test.go
- pkg/frontend/frontend_test.go
- pkg/ruler/client_pool_test.go
- vendor/github.com/grafana/dskit/middleware/grpc_cluster.go
- vendor/github.com/grafana/dskit/middleware/http_cluster.go
- vendor/github.com/grafana/dskit/middleware/metrics.go
- vendor/github.com/grafana/dskit/server/metrics.go
- vendor/github.com/grafana/dskit/server/server.go
- vendor/modules.txt
Backport https://github.com/grafana/mimir/pull/11241 to r338, to get the `cortex_server_invalid_cluster_validation_label_requests_total` metric.
> Upgrade r338 to dskit@d8712729db54

- docs/sources/mimir/configure/configure-object-storage-backend.md
… name prefix
Document the s3 object storage endpoint must not prefixed with the bucket name.
Fixes #9177
> docs: update s3 doc to indicate endpoint shouldn't include the bucket name prefix

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Note that we expect distributors to use uniform GC CPU, and to check the underlying compute resources if they are not.
> Add note about saturated nodes in `MimirDistributorGcUsesTooMuchCpu` runbook.

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/e2emimir/client.go
- integration/otlp_ingestion_test.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/push_test.go
- pkg/util/validation/limits.go
This PR adds the ability to optionally translation OTel explicit bucket histograms into native histograms with custom buckets, using the flag added in https://github.com/prometheus/prometheus/pull/15850. 
Related to https://github.com/prometheus/prometheus/issues/13485.
> feat(otlp): Allow conversion of OTel explicit bucket histograms into NHCB

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Fix alerts for invalid cluster validation labels, so that the two components to the query both aggregate on `cluster` and `namespace` labels.
> Alerts: Fix alerts for invalid cluster validation labels

- go.mod
- go.sum
- vendor/github.com/prometheus/alertmanager/dispatch/dispatch.go
- vendor/modules.txt
Upgrade prometheus-alertmanager from `4563aec7a975` to `6d0f5436a1fb`, includes one change: 
https://github.com/grafana/prometheus-alertmanager/pull/107
> Upgrade prometheus-alertmanager from 4563aec7a975 to 6d0f5436a1fb

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Enhance the `MimirRolloutStuck` alert, so it checks whether rollout groups as a whole are changing (i.e. not stuck). Previously, it would look at rollout groups per kube-state-metrics instance. The latter might cause the alert to fire if the same rollout group has multiple kube-state-metrics instances, so that instances covering replicas that are done updating appear unchanging.
> Alerts: Enhance MimirRolloutStuck so it ignores kube-state-metrics instances

- integration/compactor_test.go
- pkg/compactor/compactor_test.go
- pkg/ingester/ingester_early_compaction_test.go
- pkg/ingester/ingester_test.go
- pkg/ingester/owned_series_test.go
- pkg/ruler/compat_test.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/gateway_test.go
- pkg/util/test/tsdb.go
- tools/splitblocks/main_test.go
- tools/tsdb-chunks/main_test.go
- tools/tsdb-index-health/main_test.go
- tools/tsdb-print-chunk/main_test.go
Lots of things in tests need a type that satisfies prometheus' `chunks.Sample` interface, and prometheus does not provide any public implementation.
We ended up with about 10 identical implementations, each private to a separate test file.
This makes them all one in our test utils package
> general cleanup: move all identical prom sample impls to test util

- development/mimir-ingest-storage/config/grafana-agent.flow
- development/mimir-ingest-storage/config/mimir.yaml
- pkg/blockbuilder/config.go
- pkg/blockbuilder/scheduler/config.go
- pkg/blockbuilder/scheduler/jobs.go
- pkg/blockbuilder/scheduler/jobs_test.go
- pkg/blockbuilder/scheduler/metrics.go
- pkg/blockbuilder/scheduler/scheduler.go
- pkg/blockbuilder/scheduler/scheduler_test.go
- pkg/blockbuilder/schedulerpb/client.go
This PR implements Kafka offset maintenance and job computation.
This is a replacement for #10105. Much of it is the same, but it pivots to a fairly different job detection strategy where we do not assume the results from `kadm.ListOffsetsAfterMilli` are stable over time. It is different in these ways:
1. During normal operation, this strategy asks Kafka for every partition's end offsets frequently, then uses those observations to detect when we can emit a job.
2. At startup time, there will be a potential multi-job backlog, so we do a one-time startup scan through [commit, end] and do a kind-of fast-forwarded observation scan, creating jobs in the same way.
3. As we only compute jobs once and we aren't yet ready to enqueue multiple jobs per partition, I needed a place to store these …
> Block-builder-scheduler: offset tracking, job computation (take 2)

- pkg/frontend/querymiddleware/roundtrip.go
This PR moves user-provided extra middleware for the query-frontend before the split and cache middleware. This is important because it's possible for user-provided middleware to mutate the query depending things that are not captured by the cache key (like headers).
> query-frontend: Move user middlewares before the caching middleware

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
Save the work of converting LabelAdapters to Labels just to compute a hash. This was about 6% of all garbage in one case.
There is no particular benefit to match the hash function used by TSDB; its main stripes are split by unique ID not label hash.
(The main ingester 'push' function will lock first by hash then by unique ID for each series, and there is only one set of stripe locks, so they will tend to bounce around anyway.)
NA, just general performance.
- NA `CHANGELOG.md` - not user visible.
> ingest: cheaper hash function for parallelStorageShards

- CHANGELOG.md
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
Fixes error messages returned by the date/time parsing methods to include the parameter name instead of the type of the validation being done.
N/A
> fix(query-frontend): Include time parameter name in error message

- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/api_grafana.go
- pkg/alertmanager/api_grafana_test.go
- pkg/alertmanager/config.go
- pkg/alertmanager/config_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
A combination of two issues was causing a bug when attempting to use the new template function introduced with [custom webhook payloads](https://github.com/grafana/mimir/pull/11195) in a Grafana AM tenant:
- The `SetUserGrafanaConfig` API endpoint was not validating templates (or receivers).
- `ApplyConfig` was validating against Cloud AM template functions for Grafana AM tenants (though it was correctly using Grafana AM template functions to create the integrations).
Together, these allowed a few ways to get invalid config persisted to the grafana config bucket. This invalid config would not successfully Apply so would cause the config to not sync until the invalid config was corrected.
Additionally, since `ApplyConfig` was using the wrong template validation, even valid config could …
> Grafana Alertmanager: Prevent invalid config and use correct template validation on Apply

- integration/integration_memberlist_single_binary_test.go
- pkg/parquetconverter/compation_marker.go
- pkg/parquetconverter/parquet_converter.go
- pkg/querier/parquet_blocks_finder_bucket_index.go
- pkg/querier/parquet_queryable.go
- pkg/storage/parquet/prometheus_parquet_chunks_encoder.go
- pkg/storage/parquet/reader.go
- pkg/storage/parquet/stats.go
- pkg/storage/parquet/tsdbcodec/reader.go
- pkg/storage/parquet/writer.go
- pkg/storage/tsdb/bucketindex/loader.go
- pkg/storage/tsdb/bucketindex/parquet_loader.go
* some minor lint fixes
* what looks like big changes in parquet-converter `starting`, `running`, and `stopping` funcs, but they are mostly just rearranged to mirror those in the compactor so that it's less weird to debug 
* some tweaks to the expected values for some ring member metrics in integration tests.
* there is still a bunch of expected ring member metric values to fix in integration tests because with the current configuration we are:
* still starting the store-gateways with its 512 ring tokens
* _not_  initializing the the store-gateway queryable, which would normally also see the 512 ring tokens for the store-gateway sharding ring and contribute a tombstone on shutdown
* now starting the parquet-converter, with _its_ 512 tokens and a tombstone on shutdown
There is a bunch to …
> [WIP] parquet-mimir fix tests and lints

- go.mod
- go.sum
- vendor/github.com/twmb/franz-go/pkg/kmsg/generated.go
- vendor/modules.txt
github.com/twmb/franz-go/pkg/kmsg v1.11.0 is marked as [retracted](https://pkg.go.dev/github.com/twmb/franz-go/pkg/kmsg@v1.11.0)
This caused issues with vendoring when I tried to do it locally (and might be broken). Bump to a non-retracted version.
n/a
> deps: Use a non-retracted version of github.com/twmb/franz-go/pkg/kmsg

- pkg/distributor/otel_test.go
Fix for flaky OTel explicit histogram to native histogram with custom buckets test.
Fixes #11302
> Fix flaky OTel histograms test

- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/split_and_cache.go
Remove double logging when `areEvaluationTimeModifiersCachable` evaluates to false due to an error in parsing or preprocessing the query expression.
Follow up to https://github.com/grafana/mimir/pull/11292#discussion_r2058968044
Minor change, should only affect logging and the reason recorded in a metric.
> Fix double logging in querymiddleware caching

- pkg/streamingpromql/operators/binops/and_unless_binary_operation.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/or_binary_operation.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/operators/operator_buffer.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/operators/test_operator.go
This PR is similar to #11171, but for binary operations.
(none)
> MQE: ensure binary operations release any intermediate state if they are closed before all series are read

- CHANGELOG.md
The changes from https://github.com/grafana/mimir/pull/10054 were mentioned in the 2.15.0 changelog by accident. The PR landed into the main branch right around the time when the 2.15-rc.0 was being prepared, so the change in the changelog got slipped into the file.
This is confusing to users, who expect the feature to be available. Refer to https://github.com/grafana/mimir/issues/1597#issuecomment-2838320307
> fix: changelog from 2.15 to 2.16 for memberlist kv store , ha tracker

- CHANGELOG.md
- tools/mark-blocks/README.md
- tools/mark-blocks/main.go
- tools/mark-blocks/main_test.go
A use case came up where blocks from multiple tenants needed to be marked. The input format for `mark-blocks` made this tedious since `--tenant` is required and it enforces a single tenant per run.
To make this easier, these changes maintain the old behavior when `--tenant` is provided, but now it is optional. When it is not provided the input is expected to be of the form `tenantID/blockID` rather than `blockID`.
I've updated the unit tests and manually tested these changes and they behaved as expected.
> mark-blocks: support multi-tenant input

- .github/workflows/deploy-pr-preview.yml
- docs/sources/mimir/get-started/_index.md
If `permissions` isn't set on the job, it uses the default permissions which may be too broad.
> Explicitly set required permissions with comments to explain them

- .github/workflows/snyk.yml
- .github/workflows/stale.yaml
- .github/workflows/test-build-deploy.yml
Remove uses of `actions/cache` flagged by zizmor due to cache
poisoning issues. This change also sets default permissions for
snyk, stale, and test-build-deploy workflows to only what is
required.
N/A
> ci: Disable caching in workflows triggered by PR

- pkg/streamingpromql/limiting/memory_consumption.go
- pkg/streamingpromql/limiting/memory_consumption_test.go
- pkg/streamingpromql/operators/aggregations/aggregation_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/topk_bottomk_test.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/operators/functions/common_test.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/limiting_pool_test.go
This change makes it safe to use `MemoryConsumptionTracker` from multiple goroutines. This is a prerequisite to tracking memory used by chunks loaded from store-gateways and distributors which is done in multiple goroutines in parallel.
N/A
> MQE: Make memory consumption tracker concurrency safe

- CHANGELOG.md
- pkg/util/objtools/bucket.go
- tools/undelete-blocks/README.md
- tools/undelete-blocks/main.go
- tools/undelete-blocks/main_test.go
Currently `undelete-blocks` is written in a generic way that relies on copying a noncurrent version's data to restore an object. 
When using S3-compatible object storage, copying data can be avoided by removing S3 delete markers instead (see https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManagingDelMarkers.html#RemDelMarker). This PR adds support for this  in `undelete-blocks`. This is a significant optimization when large amounts of data are involved.
It is important to note that deleting versions does introduce risk since it is irreversible. I made a choice to restrict the version deletion to only delete markers (which have no data). If an object is overwritten with a non-delete marker then data is copied like before. This felt like a good compromise to make since differing …
> undelete-blocks: avoid copies by removing S3 delete markers

- pkg/frontend/querymiddleware/roundtrip.go
- pkg/mimir/modules.go
- pkg/mimir/modules_test.go
Cleaning up how results cache config is set inside the middlewares configuration. No user facing changes.
N/A
> query-frontend: Don't embed results cache config

- pkg/mimir/modules.go
This PR fixes an issue introduced in #11004 where the query planner does not emit metrics or record activities in the activity tracker.
(none)
> MQE: fix issue where query planner does not emit metrics or record activities

- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
I found this while investigating a different bug.
Changed error handling for LabelValues and LabelNames in `blocks_store_queryable.go` to distinguish retriable and non-retriable errors. This matches the logic for series calls
https://github.com/grafana/mimir/blob/0676ed782eb07d5383093b822683923cb33bdca9/pkg/querier/blocks_store_queryable.go#L781-L788
> querier: handle non-retriable errors in `Labels*` calls

- docs/internal/contributing/how-to-convert-config-to-per-tenant-limit.md
- pkg/mimir/modules.go
- pkg/mimir/runtime_config.go
In the process of https://github.com/grafana/mimir/pull/10816, several ruler options are being migrated to per-tenant configs.
Normally, when yaml configuration containing the old values under `ruler:` is provided, we want to internally map it to the tenant default limits to preserve backward compatibility. This is typically done in `initRuntimeConfig()`.
This PR fixes a bug where this mapping fails on deployments with pure static config and no runtime config, and with the ruler alertmanager still configured via yaml in the old method. (i.e. Mimir deployments which use `-config.file` and not `-runtime-config.file`) In such deployments we never launch the runtime config service whatsoever, but we still need the mapping to happen as it might have been statically configured.
The fix is to …
> Ruler: Fix Alertmanager URL tenant config mapping in deployments when runtime config is disabled

- docs/sources/mimir/configure/configure-native-histograms-ingestion.md
- docs/sources/mimir/send/native-histograms/_index.md
- docs/sources/mimir/visualize/native-histograms/_index.md
This PR removes the note stating that native histograms are an experimental feature from the Mimir documentation. We already explain that it is a public preview, so the additional messaging is redundant and might serve to discourage Cloud customers..
See https://raintank-corp.slack.com/archives/C04AT2ANL90/p1745848572449149
Fixes https://github.com/grafana/mimir-squad/issues/2981
> Remove experimental flag for native histograms

- CHANGELOG.md
- operations/mimir/ingest-storage-ingester-autoscaling.libsonnet
Adds a second ingest storage ingester HPA trigger that targets a max number of owned series per pod. This trigger can be enabled in addition to or in place of the existing one that targets average active series per pod.
As it is possible to disable each of the triggers separately, also adds a check to make sure the HPA has at least one trigger when the configs are rendered.
> Add ingester HPA trigger targeting max owned series per pod

- .github/workflows/test-build-deploy.yml
This uses the shared workflow that reads DockerHub credentials from vault rather than from repo secrets, which were removed due to recent security incident.
Ref docs:
https://github.com/grafana/shared-workflows/tree/main/actions/dockerhub-login
> Login to DockerHub using creds from Vault

- .github/workflows/test-build-deploy.yml
This uses the shared workflow that reads DockerHub credentials from vault rather than from repo secrets, which were removed due to recent security incident.
Porting https://github.com/grafana/mimir/pull/11388 and https://github.com/grafana/mimir/pull/11389 from r341
> CI: Use dockerhub credentials from vault

- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/writer_test.go
@bboreham had feedback that we don't note that there's expected ordering between samples to be preserved. This PR adds a comment and a test. 
> ingest: Clarify we expect ordering between samples

- docs/sources/mimir/manage/mimir-runbooks/_index.md
Improve the runbook `MimirIngestedDataTooFarInTheFuture` with more details, specifically how to find a tenant with a bad sample. Also: Minor language improvements.
> Improve MimirIngestedDataTooFarInTheFuture runbook with more details

- pkg/storage/ingest/reader_test.go
I looked at https://github.com/grafana/mimir/issues/11180. I found the root cause of the deadlock, the deadlock is caused by a failure in metrics assertion, for which I have no clue yet (I would need to see the actual assertion failing, instead of the test timeout panic). This PR fixes the test timeout panic, which is a first step.
**What's the change in this PR?**
The `time.After(3 * time.Second)` was impossible to reach, because `blockedTicker` was always triggering earlier (100ms). This means that if an assertion failed, we didn't interrupt the consumer after 3s, but it was looping forever.
Part of https://github.com/grafana/mimir/issues/11180
> Fix deadlock in TestPartitionReader_ShouldNotBufferRecordsInTheKafkaClientWhenDone

- .github/workflows/helm-release.yaml
This PR updates the `helm-release` workflow to use the credentials of the "mimir-helm-release" from Vault, rather than GitHub secrets.
The PR requires https://github.com/grafana/helm-charts/pull/3696
> ci: bump update-helm-repo workflow to retrieve app secrets from Vault

- CHANGELOG.md
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/querier/blocks_store_replicated_set_test.go
- pkg/storegateway/dynamic_replication.go
- pkg/storegateway/gateway.go
- pkg/storegateway/sharding_strategy_test.go
follow-up of #11354. Thanks @56quarters for spotting this
This method should be returning the full replication factor including the factors from the sharding ring and the dynamic replication config. Without that retries here will not work properly when dynamic replication is off
https://github.com/grafana/mimir/blob/1140f7c6191b08a3f9078f6e45af166a1cf57e77/pkg/querier/blocks_store_queryable.go#L571
> querier: fix NopDynamicReplication.MaxReplicationFactor

- pkg/streamingpromql/operators/deduplicate_and_merge.go
This PR fixes an issue where a `SeriesMetadata` slice is used after being returned to the pool. This could lead to unexpected behaviour, including incorrect query results and panics.
(none)
> MQE: fix issue where slice is used after being returned to pool

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/operators/series_merging.go
- pkg/streamingpromql/query.go
This PR makes three minor changes to MQE:
* it removes some outdated comments in `operators.mergeOneSideFloats`
* it clarifies the logic in `Query.populateVectorFromInstantVectorOperator`
* it ensures the query result is not returned to the pool multiple times if `Query.Close` is called multiple times
(none)
> MQE: clarify logic and remove outdated comments

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Enrich alerts for invalid cluster validation labels with an additional label: `protocol`. The extra label means that the operator can differentiate between alerts firing for HTTP and gRPC requests.
I've tested the revised query and it gives the right results for me.
> Alerts: Enrich alerts for invalid cluster validation labels

- .github/workflows/test-build-deploy.yml
The runner already has Docker on it. The integration tests run directly on the runner and don't need to double install it. Double installing it with mismatched versions is documented as a possible cause of a CI error we've been seeing lately: https://github.com/docker/cli/issues/6023
The other 2 jobs run in the build image instead:
```
container:
image: ${{ needs.prepare.outputs.build_image }}
```
thus still need the docker install.
n/a
n/a
> ci: Don't install Docker for jobs that run directly on the host

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
Follow up #11311 , This PR fixes threshold check for the BucketIndexNotUpdated. 
This returns all the time series above 2100, and then calculates the minimum for each series individually. This defeats the purpose of the previous PR, which was intended to return the minimum across all pods.
```
min by (cluster, namespace) (time() - (max_over_time(cortex_bucket_index_last_successful_update_timestamp_seconds[15m])) > 2100)
```
```
min by (cluster, namespace) (time() - (max_over_time(cortex_bucket_index_last_successful_update_timestamp_seconds[15m]))) > 2100
```
After wrapping the whole query with the threshold 2100, its gonna return the value that is min across all pods and then check which is higher than 2100
> Alerts: fix threshold check at BucketIndexNotUpdated

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/provisioner/provisioner-job.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/provisioner/provisioner-job.yaml
This PR adds extraVolumes to the provisioner definition to ensure it can properly mount TLS certificates.  This PR also corrects the initContainer to use a single container with a call to /usr/bin/provisioner for each tenant, instead of an initContainer per tenant. 
Fixes #11400
> fix: Add support for mounting TLS certificates in provisioner

- pkg/ingester/ingester.go
- pkg/ingester/reactivelimiter.go
- pkg/mimir/modules.go
This PR:
- Uses the `IngesterPartitionRingWatcher` to reset the ingester's read reactive limiter when the ingester's partition changes to active state. 
- Removes the activatable limiter wrapper - so the limiter is now always active. This allows even an inactive ingester, which can still be processing read requests, to continue being limited if needed. Only when transitioning back to active will the limiter reset.
> Use IngesterPartitionRingWatcher to reset reactive limiter

- pkg/streamingpromql/planning.go
- pkg/streamingpromql/planning_test.go
This PR makes the capitalisation of the values for the `stage_type` label consistent. 
Given `stage` has capitalised, human-readable names, I've chosen to make `stage_type` follow that pattern as well.
https://github.com/grafana/mimir/pull/11127
> MQE: make capitalisation of `cortex_mimir_query_engine_plan_stage_latency_seconds` label values consistent

- pkg/alertmanager/multitenant.go
> Alertmanager: Add 'user' label to 'error applying/computing config' log lines

- go.mod
- go.sum
- vendor/modules.txt
It's been agreed upon offline with [prometheus/otlptranslator](https://github.com/prometheus/otlptranslator/) co-maintainers @ywwg and @ArthurSens, plus @armandgrillet, that Mimir will use its own fork: [mimir-otlptranslator](https://github.com/grafana/mimir-otlptranslator). The motivation is to allow for a higher pace of development of the upstream project, while we ensure that nothing breaks for Mimir. This PR makes the change through a corresponding go.mod `replace` directive.
There are at the current time no differences between the fork and upstream.
> Use Mimir fork of prometheus/otlptranslator

- CHANGELOG.md
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/experimental_functions.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/prune.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/spin_off_subqueries.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
- pkg/frontend/querymiddleware/stats.go
Avoid turning the parsed expression into a string only to immediately parse it again.
Based on observations like this, which is a heap alloc_space profile of query-frontend, that `ParseExpr` was getting called over and over again.
Here's `GetQuery` from the same profile:
So this change should save ~20% of garbage.
> Query-frontend: Avoid some re-parsing of PromQL

- CHANGELOG.md
- pkg/blockbuilder/metrics.go
- pkg/frontend/v2/frontend_scheduler_worker.go
- pkg/querier/worker/scheduler_processor.go
- pkg/scheduler/scheduler.go
The PR tries to resolve the conflict in how different pieces of code use the "client" label for the `cortex_client_invalid_cluster_validation_label_requests_total` metric definition. That is, because the `query-fronted` client name is used in several places, Mimir currently panics in the monolithic mode (ref https://github.com/grafana/mimir/issues/11436).
I'm not convinced the names I picked for the query-fronentd's fit the code best, so suggestions are welcome.
Also, I updated the "block-builder" client label, as it more accurately represents the client side of the request.
Fixes #11436
> Fix client labels used for cortex_client_invalid_cluster_validation_label_requests_total

- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/release-notes/v2.15.md
The experimental flag `-distributor.otel-promote-resource-attributes` is wrongly spelled as `-distributor.promote-otel-resource-attributes` in a few documents.
Fixes
> Fix doc: -distributor.otel-promote-resource-attributes wrong spelling

- CHANGELOG.md
- pkg/querier/block_streaming.go
- pkg/querier/block_streaming_test.go
- pkg/querier/blocks_store_queryable.go
- pkg/querier/querier.go
- pkg/querier/stats/stats.go
- pkg/streamingpromql/limiting/memory_consumption.go
- pkg/streamingpromql/limiting/memory_consumption_test.go
- pkg/streamingpromql/operators/selectors/selector.go
- pkg/streamingpromql/query.go
Include chunks streamed from the store-gateway that are currently in memory in the MQE memory usage estimate. The memory usage tracker for the current query is propagated through the read path using the context for the current request. This change takes advantage of the recent gRPC update that introduced a `FreeBuffer` lifecycle method.
N/A
> MQE: Include chunks loaded from store-gateway in memory estimate

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
- pkg/distributor/ha_tracker_test.go
In this PR there are two changes:
1. Simplify the `defaultHaTracker.updateKVStore()` `else` branch, removing a superfluous extra condition (the only case where the code wouldn't enter the extra condition `if desc == nil || (desc.DeletedAt > 0)` is if `DeletedAt` is negative, which can never happen
2. Add a small logic to set `ElectedAt` timestamp in case its value is zero. In the past we had a bug causing zero value to be stored. If a replica has never changed since then, the `ElectedAt` timestamp is still zero (we've seen it in prod). In this case we can just set it to "now": even if it's not true that it has been elected "now" (it was in the past), we do fix it to avoid misunderstandings when you look at the HA tracker web page.
N/A
> HA Tracker: fix old entries with zero valued ElectedAt timestamp

- CHANGELOG.md
- pkg/streamingpromql/operators/selectors/selector.go
- pkg/streamingpromql/query.go
Inject the memory consumption tracker into the context for the query when the query is executed instead of within a selector.
See https://github.com/grafana/mimir/pull/11453#discussion_r2092540847
Related #11453
> MQE: Inject memory tracker to context on query execution

- CHANGELOG.md
- pkg/distributor/query.go
- pkg/ingester/client/streaming.go
- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming.go
- pkg/querier/distributor_queryable_streaming_test.go
Include chunks streamed from ingesters that are currently in memory
in the MQE memory usage estimate. The memory tracker for the current
query is propagated through the read path using the context for the
current request.
Related #11453
> MQE: Include chunks loaded from ingesters in memory estimate

- pkg/distributor/distributor.go
- pkg/distributor/distributor_test.go
Simplifies the code.
The returned `bool shouldRemove` was only ever true if the returned `err` was non-nil, so we don't need the `bool`.
> Distributor: simplify code for validateSeries

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
Always return true to ensure WatchPrefix() is never interrupted, otherwise the HA tracker stops to receive updates.
(cherry picked from commit b70c1dac9d1639a592b0f80d0abac70309f9ce51)
> [r340] distributor(ha-tracker): WatchPrefix - handle error on type assertion gracefully

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
Always return true to ensure WatchPrefix() is never interrupted, otherwise the HA tracker stops to receive updates.
(cherry picked from commit b70c1dac9d1639a592b0f80d0abac70309f9ce51)
> [r337] distributor(ha-tracker): WatchPrefix - handle error on type assertion gracefully

- CHANGELOG.md
- pkg/distributor/ha_tracker.go
distributor(ha-tracker): WatchPrefix - handle error on type assertion gracefully (#11411)
Always return true to ensure WatchPrefix() is never interrupted, otherwise the HA tracker stops to receive updates.
(cherry picked from commit b70c1dac9d1639a592b0f80d0abac70309f9ce51)
> [r339] distributor(ha-tracker): WatchPrefix - handle error on type assertion gracefully

- CHANGELOG.md
- pkg/ruler/api.go
This is the fixup for https://github.com/grafana/mimir/pull/11321
The above changes missed the part that returned error is wrapped into a gRPC status error
```
rpc error: code = Unknown desc = all rule evaluation is disabled for user
```
This causes the ruler to reply with HTTP status 500.
Tested these new changes in a dev cluster:
```
› curl --no-progress-meter -g -v 'http://127.1:8080/prometheus/api/v1/rules' -H 'x-scope-orgid: 10637'
< HTTP/1.1 422 Unprocessable Entity
< Content-Type: application/json
< Server: GEM/vldmr-ruler-err-tenant-rule-eval-disabled-fe79082a-WIP
< Vary: Accept-Encoding
< Date: Tue, 20 May 2025 12:53:16 GMT
< Content-Length: 109
<
{"status":"error","data":null,"errorType":"execution","error":"rule evaluation is disabled for tenant 10637"}
```
> ruler: handle gRPC status error from when tenant has rules disabled

- pkg/frontend/querymiddleware/querysharding_test.go
Adds a new test case to test summing a histogram_sum, ensuring that it returns the same results with or without query sharding.
Relates to https://github.com/grafana/mimir/issues/11102
Only updating a unit test.
> Add new test case for query sharding to test summing a histogram_sum

- CHANGELOG.md
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/experimental_functions.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/prune.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/remote_read.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/spin_off_subqueries.go
- pkg/frontend/querymiddleware/split_and_cache.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
- pkg/frontend/querymiddleware/stats.go
Revert #11437, as we've found it can cause query-frontend panics. This reverts commit 7c71ae995027cdd835cc1180fbdfc0a9c1af4831.
> Revert "Query-frontend: Avoid some re-parsing of PromQL (#11437)"

- pkg/blockbuilder/tsdb.go
- pkg/ingester/errors.go
- pkg/ingester/errors_test.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/storage/soft_append_error_processor.go
This PR improves the `err-mimir-sample-duplicate-timestamp` error message. Currently, the error message doesn't say anything about the involved values. This is an example of an error message of this type:
```
the sample has been rejected because another sample with the same timestamp, but a different value, has already been ingested (err-mimir-sample-duplicate-timestamp). The affected sample has timestamp 1970-01-19T05:30:43.969Z and is from series test-series{cluster=\"my-cluster\", namespace=\"my-namespace\"}
```
On the other hand, Mimir returns this type of errors when it receives the `storage.ErrDuplicateSampleForTimestamp` error from Prometheus. Given that the latter already contains all the data that we need, i.e., both currently ingested value and the value that a write request is …
> Improve err-mimir-sample-duplicate-timestamp error message

- pkg/distributor/otel_test.go
- pkg/ingester/ingester_test.go
- pkg/mimirtool/commands/alerts.go
- pkg/ruler/mapper_test.go
- pkg/util/log/log.go
- pkg/util/log/slogadapter.go
- pkg/util/log/slogadapter_test.go
Expose log level through log wrappers, so that `Debug()` calls are fast when debug logging is disabled.
It works by making a `Log()` call so it reaches the bottom layer.
However, if `SlogFromGoKit` is used with a logger outside of this package, you will get a spurious log line.
Inspired by https://github.com/prometheus/prometheus/pull/15993
This is a competitor to #10604.  Credit @dimitarvdimitrov for the idea.
Before:
```
BenchmarkSlogFromGoKit/log-28             981555              1176 ns/op            1008 B/op         16 allocs/op
BenchmarkSlogFromGoKit/debuglog-28        949378              1175 ns/op            1008 B/op         16 allocs/op
BenchmarkDebugLog-28                    26430567                44.55 ns/op           96 B/op          2 allocs/op
```
After:
``` …
```
> Logging: detect log level through layers of wrappers

- .github/workflows/helm-weekly-release-pr.yaml
- .github/workflows/helm-weekly-release-reviewer.yml
This is another follow-up to #10986
~~Here, I update the Helm weekly auto-review so the "mimir-github-bot" merged the PR, approved by the "github-actions" bot. The theory is that this should allow the CI to bypass the codeowners review (see https://github.com/grafana/mimir/pull/11008).~~
I've updated the PR to
- open weekly Helm release PRs from `mimir-vendoring-bot`
- use `mimir-github-bot` to auto-review the PR
This should resolve the problems, where we couldn't use `github-actions-bot` to open a PR, because these PRs don't trigger further automations on GitHub. And we cannot use `github-actions-bot` to auto-review the PRs, because cannot be the code owner.
> github: use mimir-github-bot to auto-merge weekly helm releases

- integration/store_gateway_limits_hit_test.go
The existing test wasn't catching a bug (https://github.com/prometheus/prometheus/pull/16544) because 1) it was only querying a single store-gateway and 2) blocks were returning disjoin series.
This PR improves the test suite to make it more realistic:
- 3 ingesters instead of 1
- 2 store-gateways instead of 1
- overlapping series in each block so that we can merge series from different sources
> querier: improve e2e tests for error parsing

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This PR fixes the RPS panel of query-scheduler ("Mimir / Reads"). Because the metric behind the panel isn't split by the status codes, the panel currently renders "Value" in the legend.
**Before**
(note "Value" in the legend)
**After** 🤘
> dashboards: fix Query-scheduler RPS panel legend in "Mimir / Reads"

- CHANGELOG.md
- pkg/scheduler/queue/queue.go
- pkg/scheduler/queue/queue_broker.go
- pkg/scheduler/queue/queue_test.go
- pkg/scheduler/scheduler.go
and reproduce with test
Fixes #11337
> fix scheduler panic when serving dequeue request for disconnected querier-worker

- pkg/blockbuilder/tsdb.go
- pkg/mimirpb/compat_rw2.go
- pkg/mimirpb/compat_rw2_test.go
- pkg/mimirpb/timeseries.go
- pkg/storage/ingest/pusher.go
- pkg/storage/ingest/pusher_test.go
- pkg/storage/ingest/version.go
- pkg/storage/ingest/version_test.go
- pkg/storage/ingest/writer_test.go
- pkg/util/test/rw2.go
Introduces a new record version `V2`, and implements consumer-side support for it.
It's inspired by Prometheus Remote Write 2.0, but not strictly compatible with it. A notable difference is that the symbol refs are shifted up by 64. This reserves space for a future common symbols table, allowing us to completely avoid sending certain commonly used symbols through Kafka.
The format is internal to Mimir, it doesn't need to exactly match any external standard. Aside from within test code, there is currently no way to produce records of the V2 format. Therefore, we're still able to iterate on the format in the future and make breaking changes. I'm not adding this to the changelog for that reason; when we decide to "lock down" the format, the changelog will be updated at that time.
The …
> ingest-storage: Add consumer support for a new record version 2, based on Remote Write 2.0

- development/mimir-ingest-storage/config/mimir.yaml
- pkg/blockbuilder/blockbuilder.go
This change allows an assigned job to finish processing when the service's context is canceled.
> Block-builder: Gracefully shutdown pull-mode worker.

- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator_test.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/series_data_ring_buffer.go
This PR fixes an issue where a query containing a common subexpression that returned an error could also panic with `integer divide by zero` when the query was closed. 
This would occur if:
* the first series read by the duplication operator returned an error
* all consumers other than the one that made the first `NextSeries` call were closed before the first `NextSeries` caller
If these conditions were met, `SeriesDataRingBuffer.Remove` would panic when evaluating `b.startIndex % len(b.data)`.
As the query was closed after the HTTP response was sent, the user still saw the expected error message, but the querier would have crashed and restarted, so other inflight queries may have been affected.
#11189
- [covered by #10067] `CHANGELOG.md` updated - the order …
> Fix issue where a query containing a common subexpression that returned an error could also panic with `integer divide by zero`

- CHANGELOG.md
- cmd/metaconvert/Dockerfile
- cmd/mimir/Dockerfile.alpine
- cmd/mimir/Dockerfile.continuous-test
- cmd/mimirtool/Dockerfile
- cmd/query-tee/Dockerfile
- development/mimir-ingest-storage/dev.dockerfile
- development/mimir-microservices-mode/dev.dockerfile
- development/mimir-monolithic-mode-with-swift-storage/dev.dockerfile
- development/mimir-monolithic-mode/dev.dockerfile
- development/mimir-read-write-mode/dev.dockerfile
- tools/copyblocks/Dockerfile
Upgrade Alpine Linux in Dockerfiles to 3.20.6, to fix [CVE-2025-26519](https://security.alpinelinux.org/vuln/CVE-2025-26519).
> [release-2.15] Upgrade Alpine Linux in Dockerfiles to 3.20.6

- pkg/blockbuilder/scheduler/jobs.go
- pkg/blockbuilder/scheduler/scheduler.go
- pkg/blockbuilder/scheduler/scheduler_test.go
This PR fixes a bug in handling "initial" jobs computed at startup. Here's an example of the bug:
1. scheduler knows that its committed offset is 10.
1. a job J1 is computed over offsets (10, 20) and is assigned to a worker 1. it is in progress.
1. the scheduler restarts and learns about J1 in progress.
1. this new scheduler scans for initial jobs for all partitions, and it computes a job J2 (10, 30)
1. we only allow one outstanding job per partition so J2 goes into a feeder queue.
1. worker 1 completes J1. scheduler moves the committed offset to 20.
1. Now that there's room in the job queue, we can move J2 over there. But, there was a bug where we were [skipping feeder-queue jobs if `j.start < committed`](https://github.com/grafana/mimir/blob/cd4127dd571cc03c6edb3277ccd086b1e0045365/pkg/b …
> Block-builder-scheduler: fix bug where startup job is erroneously skipped based on commit movement

- pkg/frontend/querymiddleware/limits.go
This PR improves the traces emitted by query-frontends.
Previously, events related to the request being sent to the query-scheduler or querier were attached to the span for the last middleware in the chain, for example:
This makes them difficult to find, and is potentially confusing.
In this PR, I've added a separate span to the round-tripper to act as the parent for these events:
I haven't added a changelog entry given this is a minor improvement to the debugging experience.
(none)
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with …
> Create separate span for query-frontend request to query-schedulers / queriers

- go.mod
- go.sum
- pkg/ingester/shipper_test.go
- pkg/mimirtool/commands/bucket_validation.go
- pkg/storage/bucket/client_mock.go
- pkg/storage/bucket/delayed_bucket_client.go
- pkg/storage/bucket/error_injected_bucket_client.go
- pkg/storage/bucket/prefixed_bucket_client.go
- pkg/storage/bucket/sse_bucket_client.go
- pkg/storage/tsdb/block/block_test.go
- pkg/storage/tsdb/block/global_markers_bucket_client.go
- pkg/storage/tsdb/bucketcache/caching_bucket.go
- vendor/github.com/thanos-io/objstore/CHANGELOG.md
- vendor/github.com/thanos-io/objstore/README.md
- vendor/github.com/thanos-io/objstore/inmem.go
- vendor/github.com/thanos-io/objstore/objstore.go
- vendor/github.com/thanos-io/objstore/prefixed_bucket.go
- vendor/github.com/thanos-io/objstore/providers/azure/azure.go
- vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go
- vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
- vendor/github.com/thanos-io/objstore/providers/s3/s3.go
- vendor/github.com/thanos-io/objstore/providers/swift/swift.go
- vendor/github.com/thanos-io/objstore/testing.go
- vendor/github.com/thanos-io/objstore/tracing/opentracing/opentracing.go
- vendor/modules.txt
This is a manual backport for https://github.com/grafana/mimir/pull/11546 to r344 after the automated backport failed.
It also includes the changes from #10664, as separating just my changes from #11546 is too difficult, and r344 has only just been cut.
(none)
> Backport #10664 and #11546 to r344

- CHANGELOG.md
- integration/api_endpoints_test.go
- integration/configs.go
- integration/getting_started_single_process_config_test.go
- integration/getting_started_with_gossiped_ring_test.go
- integration/influx_ingestion_test.go
- integration/integration_memberlist_single_binary_test.go
- integration/ooo_ingestion_test.go
- integration/otlp_ingestion_test.go
- integration/querier_test.go
- integration/ruler_test.go
- integration/single_binary_test.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
If the ruler fails to complete its initial sync, it still transitions to the running state. In this case, the tenants, whose rules have been synced, observe a delay in their rule evaluation.
This PR addresses that by making sure the ruler fails to start on a failure during initial sync. During a rolling update, if a failure happens, the running rulers will continue to evaluate the rules, until the new replica manages to transition into the running state.
> ruler: Terminate on failires during initial sync

- CHANGELOG.md
- Makefile
- mimir-build-image/Dockerfile
Upgrade release-2.15 from Go v1.23.7 to v1.23.9, in order to fix [CVE-2025-22871](https://nvd.nist.gov/vuln/detail/CVE-2025-22871).
> [release-2.15] Build: Upgrade to Go v1.23.9

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
Here I'm updating the experimental block-builder alerts to rely on the metrics exposed by the block-builder-scheduler. Moving forward, we will completely get rid of the block-builder stand-alone mode.
> Update block-builder alerts

- operations/mimir-mixin/dashboards/block-builder.libsonnet
Some more improvements to the block-builder dashboard for the scheduler mode:
- Add "Pending Jobs by Partition" panel
- Mark the standalone-mode "Lag records panel" as deprecated
The "Pending Jobs by Partition" is a useful indicator, that tells that the block-builder struggles to keep up with the scheduler's per-partition job queue.
> block-builder: refactor dashboard

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- docs/sources/mimir/references/architecture/mimir-query-engine.md
- integration/query_frontend_test.go
- pkg/querier/querier.go
This PR enables MQE by default for queriers.
Note that I've left all of the MQE-related CLI flags as experimental, given we'll likely remove them at some point and only allow using MQE.
I've also removed the integration test that covers the case where the "max samples" limit is hit introduced in #499. MQE does not support this limit, and the functionality is covered by unit tests that were also introduced in that PR.
#10067
> MQE: enable by default for queriers

- renovate.json5
Configure Renovate to not update our thanos-io/objstore fork: github.com/charleskorn/objstore. For motivation, see https://github.com/grafana/mimir/pull/11585, which attempted to downgrade this dependency (to latest upstream).
> Renovate: Don't update charleskorn/objstore

- renovate.json5
As the `google.golang.org/grpc` dependency is no longer pinned, re-enable Renovate updates of it. Thanks to @charleskorn for pointing it out.
> Renovate: Re-enable google.golang.org/grpc

- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/stats.go
This PR modifies the behaviour of the query stats middleware to no longer create a `promql.Query` instance when computing query stats for remote read requests.
This is completely unnecessary, and also [doesn't work as expected with MQE](https://github.com/grafana/mimir/pull/11417#discussion_r2092556045).
I haven't added a changelog entry given this is just a refactoring.
#11417
> Don't try to create a `Query` instance just to compute stats for remote read requests

- renovate.json5
Switch Renovate configuration to use `config:recommended` preset, instead of `config:base`. `config:recommended` is the [preferred Renovate preset](https://docs.renovatebot.com/config-presets/#example-configs), I can't even find documentation on `config:base`. I'm going to guess it's legacy.
> Renovate: Use `config:recommended` preset

- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming_test.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/streamingpromql/operators/aggregations/aggregation_test.go
- pkg/streamingpromql/operators/aggregations/aggregations_safety_test.go
- pkg/streamingpromql/operators/aggregations/count_values_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/range_query_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/topk_bottomk_test.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/operators/deduplicate_and_merge_test.go
- pkg/streamingpromql/operators/functions/absent_test.go
- pkg/streamingpromql/operators/functions/common_test.go
- pkg/streamingpromql/operators/functions/function_over_instant_vector_test.go
- pkg/streamingpromql/operators/functions/histogram_function_test.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector_test.go
- pkg/streamingpromql/operators/selectors/selector_test.go
- pkg/streamingpromql/operators/series_merging_test.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator_test.go
- pkg/streamingpromql/planning.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/data_test.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/limiter/memory_consumption.go
- pkg/util/limiter/memory_consumption_test.go
MQE panics when the estimated memory consumption of a query goes negative, as this indicates that something was returned to a pool multiple times, which could lead to incorrect query results.
However, when this happens in a production environment, it can be quite difficult to debug this, as it's often difficult to determine which query was affected: the panic often happens when `Query.Close()` is called, which is not tracked by the activity tracker, and so the query doesn't appear in the list of inflight queries when the querier restarts.
So, in this PR, I'm adding the query expression to the panic message to make it a bit easier to figure out what happened.
#10067
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, …
> MQE: include additional information when panicking because estimated memory consumption is negative

- CHANGELOG.md
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_test.go
This PR fixes an issue where queriers can panic if the query is cancelled or fails while a `Select` call is running. 
This happens because queriers wrap the ingester and store-gateway `Querier` instances with a `LazyQuerier`. This can result in `Close` being called while the `Select` call is still running, creating a race to read from / write to `streamReaders` and causing `Close` to call `FreeBuffer()` on a nil reader instance if `Select` has not finished appending the new readers to `streamReaders`.
An alternative solution would be to modify `LazyQuerier` to wait for the `Select` to finish before calling `Close` on the wrapped `Querier`, but this may cause delays in closing the query if the `Select` does not complete promptly.
#11136
- [n/a] …
> Fix issue where queriers can panic if the query is cancelled while a `Select` call is running

- CHANGELOG.md
- pkg/querier/blocks_store_queryable.go
- pkg/querier/blocks_store_queryable_test.go
- pkg/querier/distributor_queryable.go
- pkg/querier/distributor_queryable_test.go
This PR manually backports #11613 to r345.
#11613
> Backport #11613 to r345

- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming_test.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/streamingpromql/operators/aggregations/aggregation_test.go
- pkg/streamingpromql/operators/aggregations/aggregations_safety_test.go
- pkg/streamingpromql/operators/aggregations/count_values_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/range_query_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/topk_bottomk_test.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/operators/deduplicate_and_merge_test.go
- pkg/streamingpromql/operators/functions/absent_test.go
- pkg/streamingpromql/operators/functions/common_test.go
- pkg/streamingpromql/operators/functions/function_over_instant_vector_test.go
- pkg/streamingpromql/operators/functions/histogram_function_test.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector_test.go
- pkg/streamingpromql/operators/selectors/selector_test.go
- pkg/streamingpromql/operators/series_merging_test.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator_test.go
- pkg/streamingpromql/planning.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/data_test.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/limiter/memory_consumption.go
- pkg/util/limiter/memory_consumption_test.go
This PR manually backports #11615 to r345.
#11615 
> Backport #11615 to r345

- go.mod
- go.sum
- vendor/modules.txt
The mimir-otlptranslator fork dependency (via `replace` directive) was temporarily dropped in #11607. It should be reinstated, since it was agreed on management level that Mimir will maintain its own fork to be able to ensure that no breaking changes enter the dependency chain. The fork is currently identical with upstream, so there are no code changes.
> Reinstate mimir-otlptranslator fork dependency

- pkg/ingester/client/streaming_test.go
- pkg/querier/block_streaming_test.go
- pkg/querier/distributor_queryable_streaming_test.go
- pkg/streamingpromql/operators/aggregations/aggregation_test.go
- pkg/streamingpromql/operators/aggregations/aggregations_safety_test.go
- pkg/streamingpromql/operators/aggregations/count_values_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/range_query_test.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/topk_bottomk_test.go
- pkg/streamingpromql/operators/binops/and_unless_binary_operation_test.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/binops/or_binary_operation_test.go
- pkg/streamingpromql/operators/deduplicate_and_merge_test.go
- pkg/streamingpromql/operators/functions/absent_test.go
- pkg/streamingpromql/operators/functions/common_test.go
- pkg/streamingpromql/operators/functions/function_over_instant_vector_test.go
- pkg/streamingpromql/operators/functions/histogram_function_test.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/operators/selectors/instant_vector_selector_test.go
- pkg/streamingpromql/operators/selectors/selector_test.go
- pkg/streamingpromql/operators/series_merging_test.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/operator_test.go
- pkg/streamingpromql/planning.go
- pkg/streamingpromql/query.go
- pkg/streamingpromql/types/data_test.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/streamingpromql/types/ring_buffer_test.go
- pkg/util/limiter/memory_consumption.go
- pkg/util/limiter/memory_consumption_test.go
This PR manually backports https://github.com/grafana/mimir/pull/11615 to r344.
https://github.com/grafana/mimir/pull/11615
> Backport #11615 to r344

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-queries.json
- operations/mimir-mixin-compiled/dashboards/mimir-queries.json
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/queries.libsonnet
This PR adds two panels to the Queries dashboard in the mixin:
* a heatmap of estimated per-query memory consumption
* a timeseries panel showing the rate of fallback to Prometheus' engine
This is how the affected area of the dashboard now looks:
#10067
> Add MQE-related dashboard panels to Queries dashboard

- pkg/ingester/client/streaming.go
- pkg/querier/block_streaming.go
- pkg/streamingpromql/operators/aggregations/quantile.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/instant_query.go
- pkg/streamingpromql/operators/aggregations/topkbottomk/range_query.go
- pkg/streamingpromql/operators/binops/one_to_one_vector_vector_binary_operation_test.go
- pkg/streamingpromql/operators/functions/common_test.go
- pkg/streamingpromql/operators/functions/histogram_function.go
- pkg/streamingpromql/operators/operator_buffer_test.go
- pkg/streamingpromql/types/limiting_pool.go
- pkg/streamingpromql/types/limiting_pool_test.go
- pkg/util/limiter/memory_consumption.go
- pkg/util/limiter/memory_consumption_test.go
This PR extends `limiting.MemoryConsumptionTracker` to track memory consumption by source.
This allows us to include more information in `Estimated memory consumption of this query is negative` panics, and also makes it easier to debug failures when MQE is running in pedantic mode during tests. 
(none)
> MQE: label each source of memory consumption to make it easier to identify where something is returned to the pool multiple times

- CHANGELOG.md
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
When evaluation of one rule type is disabled but the other is enabled, the sync logic makes a filtered copy of each rule group. The copy logic ignores newly added fields `QueryOffset` and `AlignEvaluationTimeOnInterval`. We then sync these groups with the fields blapped.
This PR changes the copy + tests to consider all fields as of today, and also be tolerant of newly added fields so it doesn't break again in the future.
n/a
> ruler: Fix QueryOffset being ignored when recording xor alerting rule evaluation is disabled

- CHANGELOG.md
- pkg/ingester/downscale.go
- pkg/ingester/downscale_test.go
- pkg/ingester/ingester.go
Stop ingesters leaving read-only mode while a forced compaction is pending or in progress. Leaving read-only mode during the compaction will cause write errors, because writes are blocked.
> Don't leave read-only mode if there is a forced compaction pending or in progress

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- integration/ruler_test.go
- pkg/ruler/api.go
- pkg/ruler/api_test.go
- pkg/ruler/compat.go
- pkg/ruler/ruler.go
- pkg/ruler/ruler_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
Introduces a new per-tenant limit, `ruler_min_rule_evaluation_interval`, which allows administrators to limit the speed at which rules may evaluate.
It defaults to zero, zero indicates no limit.
When the limit is raised and a rule already exists with an interval below the limit:
- The rule is still evaluated, but artificially slowed down to match the limit.
- The rule can't be edited until the limit is fixed.
This means administrators can use this as a knob to throttle a tenant's rule evaluations at runtime if needed. We still do a best-effort evaluation to avoid disrupting the tenant.
Rel https://github.com/grafana/mimir/issues/11272
> ruler: Add new limit on minimum rule evaluation interval

- pkg/mimirpb/compat_rw2.go
- pkg/mimirpb/compat_rw2_test.go
- pkg/mimirpb/timeseries.go
- pkg/storage/ingest/version.go
- pkg/storage/ingest/version_test.go
- pkg/util/test/rw2.go
**Note that record format V2 is still considered unstable.**
This PR introduces a shared table of frequently-used symbols. This starts to fill in the "reserved" symbol space from 0 to 64 in record format V2, that is never used by an ordinary request.
This means that producers need not send certain frequently symbols in the per-request symbol table at all - they can instead send the shared symbol and trust that the consumer will understand it.
Note that the contents of the table are subject to change as we do more analysis. As a first pass, it's populated with various frequently-used symbols from a test cell. The symbols chosen are based on a combination of length and frequency in sampled data, as well as cleaned to represent symbols from Mimir or software that Mimir is frequently used …
> ingest-storage: Add a common symbols table to record format V2

- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation.go
- pkg/streamingpromql/operators/binops/grouped_vector_vector_binary_operation_test.go
This PR fixes an issue where queriers could panic with `estimated memory consumption of this query is negative` while evaluating a query containing a one-to-many or many-to-one binary operation (aka `group_left` / `group_right`).
Specifically, the issue is triggered if all of the series with the same group matching labels on the "one" side are read and then the operator is closed before all of the corresponding output series have been emitted. (This can happen if, for example, the query contains further binary operations that only need a subset of the output series.)
In this case, the `matchGroup`'s `presence` slice would be returned to the pool multiple times: once in `updateOneSidePresence`, and again when `oneSide.Close` was called by the first remaining output series in that group. …
> MQE: fix possible panic while evaluating a query containing `group_left` or `group_right`

- cmd/mimir/main.go
- cmd/mimir/main_test.go
I wanted to understand which modules were ran in "read",  "write", and "backend" modes, but the `-modules` flag wasn't helpful, so I had to check the code to find out.
`-modules` already marks dependencies of `all` with a `*`. Now this is generalized to all dependents, with a explicit list.
<details>
<summary><b>Before</b></summary>
```
alertmanager
all
backend
block-builder
block-builder-scheduler
compactor *
continuous-test
distributor *
flusher
ingester *
memberlist-kv *
overrides-exporter
querier *
query-frontend *
query-scheduler
read
ruler *
store-gateway *
write
Modules marked with * are included in target All.
```
</details>
**After**
```
$ mimir -modules
alertmanager (in: backend)
all
backend
block-builder
block-builder-scheduler
compactor (in: backend, all)
continuous-test …
```
> Display all dependents in -modules message, not just "all"

- pkg/ingester/ingester.go
This PR improves the clarity of traces emitted during queries by removing unnecessary "Ingester.QueryStream" trace spans emitted by ingesters that are nested beneath "cortex.Ingester/QueryStream" trace spans also emitted by ingesters.
Instead, any events that were previously attached to the "Ingester.QueryStream" span are now attached to the "cortex.Ingester/QueryStream" span. 
The only major difference is that the list of tenant IDs will no longer be on a trace span emitted by ingesters, but this information is available on parent spans emitted by other components (eg. the "Distributor.queryIngesterStream" span emitted by queriers).
Before:
After:
I haven't added a changelog entry given this is a minor change to tracing.
(none)
- [n/a] …
> Don't emit unnecessary "Ingester.QueryStream" trace spans

- CHANGELOG.md
- pkg/distributor/distributor.go
Follow-up to #11159. I suspect that to avoid memory corruption/data races, we should clone metric name strings as they are originally unsafe gRPC unmarshalling buffer references. I think it ought to be fine performance wise, as we will emit events for a maximum of 10 metrics per write request.
> Distributor.prePushValidationMiddleware: Use safe strings for span event attributes

- pkg/alertmanager/api_grafana.go
This PR makes the template size limit restrictive for Grafana Alertmanager tenants.
> Alertmanager: Enforce Grafana template size limit

- pkg/storegateway/gateway.go
- pkg/storegateway/gateway_blocks_http.go
- pkg/storegateway/gateway_test.go
- pkg/storegateway/parquet_bucket_stores.go
- pkg/storegateway/stores.go
> parquet store-gateways introduce stores interface

- pkg/ingester/ingester.go
This PR fixes an issue introduced in #11712 where the parent trace span would be ended early by `QueryStream()`.
Fixes https://github.com/grafana/mimir/pull/11712#discussion_r2142233048
> Don't end trace span early in `Ingester.QueryStream`

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/alertmanager/alertmanager.go
- pkg/alertmanager/alertmanager_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
- `isGrafanaTenant` was added as a helper method for strict AM initialization
- But it relies on a specific flag to be set (`alertmanager.grafana-alertmanager-conditionally-skip-tenant-suffix`)
- If this is not set, the method will return false regardless if it's a Grafana tenant or not
- On https://github.com/grafana/mimir/pull/11609, we started using this in the template validation logic ([here](https://github.com/grafana/mimir/pull/11609/files#diff-8e36fbeb7a03da16fee1b491a126581d93b5dec3b8bd4e4d4398aed38232bbacR678))
- This causes the Grafana AM to error when applying the configuration if the user is using templates with functions which are not supported by Mimir templates
- There's a bool in the `amConfig` (`usingGrafanaConfig`) which indicates whether the tenant is using a Grafana …
> Alertmanager: stop using isGrafanaTenant

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/querier/querier-so.yaml
This PR adds the missing authModes field to the Querier ScaledObject definition when authentication is enabled. Without this field, enabling authentication results in 401 errors from the KEDA Operator when it attempts to authenticate for the trigger: cortex_querier_hpa_default_predictive
The error looks like:
` 2025-06-11T09:34:51Z	ERROR	scale_handler	error getting metric for trigger	{"scaledObject.Namespace": "mimir", "scaledObject.Name": "mimir-querier", "trigger": "cortex_querier_hpa_default_predictive", "error": "prometheus query api returned error. status: 401 response: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.25.5</center>\r\n</body>\r\n</html>\r\n"}`
N/A
> [BUGFIX] KEDA Autoscaling: Add authModes to the Querier ScaledObject if authentication is enabled

- pkg/alertmanager/api_grafana.go
This PR makes the template number limit restrictive for Grafana Alertmanager tenants.
Similar to https://github.com/grafana/mimir/pull/11574.
> Alertmanager: Enforce Grafana template number limit

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/config.go
- pkg/frontend/querymiddleware/prune_test.go
- pkg/frontend/querymiddleware/querysharding.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/querysharding_test_utils_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/frontend/querymiddleware/spin_off_subqueries.go
- pkg/frontend/querymiddleware/spin_off_subqueries_test.go
- pkg/frontend/querymiddleware/split_and_cache_test.go
- pkg/frontend/querymiddleware/split_by_instant_interval.go
- pkg/frontend/querymiddleware/split_by_instant_interval_test.go
- pkg/frontend/querymiddleware/stats.go
- pkg/frontend/querymiddleware/stats_test.go
- pkg/mimir/mimir_test.go
- pkg/mimir/modules.go
- pkg/querier/querier.go
- pkg/querier/querier_test.go
- pkg/streamingpromql/operators/selectors/selector.go
Introduce configuration to allow the Mimir Query Engine to be used instead of the Prometheus engine in the query-frontend when queries are rewritten to be shardable or subqueries are spun off.
Notable changes:
* New configuration for query-frontend to allow MQE to be used with an optional fallback to the Prometheus engine (same as in queriers).
* Context timeouts are now checked at least once in `Selector` and also every 128 series instead of only every 128 series.
* Query-frontend tests that used a query engine now run with both Prometheus and MQE engines. Results are expected to be the same in most cases, excluding some minor differences like error messages.
N/A
There are a lot of whitespace changes in test files: click "hide whitespace changes" when reviewing.
> mqe: Allow usage of Mimir Query Engine in query-frontend

- renovate.json5
This PR configures Renovate to update Go in all places as part of a single PR:
* `go.mod`
* the build image
* any GitHub Actions workflows that use `actions/setup-go`
(none)
> Configure Renovate to update Go version in all locations in one PR

- .golangci.yml
This uncaps the number of occurrences of the same issue that the linter will output. This should make it easier to address all issues in one go instead of pushing a change and running the linter again.
For example, if the `errcheck` has failed in 7 places in the PR, by default golangci lint will only show the first 3. With this change it will show all 7.
> golangci-lint: display unlimited same issues

- pkg/storegateway/parquet_bucket_block.go
- pkg/storegateway/parquet_bucket_store.go
- pkg/storegateway/parquet_bucket_stores.go
fix split between Parquet Stores and each tenant's Store - those two were accidentially combined in the previous PR.
The `Stores` (one object, plural name) keeps track of each tenant's `Store` and just dispatches to them to satisfy query calls.
The `Stores` also coordinates blocks syncing, keeping track of allowed and disallowed tenants and dispatching sync calls to each tenant's `Store`
The individual `Store` does most of the actual work.
Also broke out a new file to hold the parquet version of `bucketBlock`, now called `parquetBlockWithMeta`. It was named `parquetShardWithMetadata`, but it appears every usage of this code has punted on the idea of having more than 1 shard per block now, so I figured we would try to keep the names as analogous to the main store-gateway types as possible …
> fix split between Parquet Stores and individual tenant Store

- .github/workflows/changelog-check.yml
- .github/workflows/helm-weekly-release-pr.yaml
- .github/workflows/update-vendored-mimir-prometheus.yml
- renovate.json5
- Skip changelog check for automated PRs with specific labels
- Add appropriate labels to automated workflows
- **changelog-check.yml**: Skip validation for PRs with `dependency-update`, `vendored-mimir-prometheus-update`, or `helm-weekly-release` labels
- **helm-weekly-release-pr.yaml**: Add `helm-weekly-release` label to weekly helm release PRs
- **update-vendored-mimir-prometheus.yml**: Add `vendored-mimir-prometheus-update` label to vendored prometheus update PRs  
- **renovate.json5**: Configure Renovate to add `dependency-update` label to all dependency update PRs
> Skip changelog check for automated PRs

- pkg/streamingpromql/operators/functions/histogram_function.go
- pkg/util/limiter/memory_consumption.go
This PR fixes an issue introduced in #11654 where slices of `[]promql.Bucket` and `[]promql.Buckets` were categorised together.
https://github.com/grafana/mimir/pull/11654
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
> MQE: track memory consumption of `[]promql.Bucket` and `[]promql.Buckets` separately

- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_client_test.go
- pkg/storage/ingest/writer_test.go
I wanted to investigate how `MaxProduceRequestsInflightPerBroker` works in practice and I've added a test to easily see how it works. I have found that `MaxProduceRequestsInflightPerBroker` is not really honored if set to a value higher than 9 ([see here](https://github.com/twmb/franz-go/issues/1041)) but, on the other hand, I haven't found a proof that this could reduce the throughput in our case. I would like to commit the test I've added. It's a slow test (12s) but I think it's worth it.
N/A
> Add TestKafkaProducer_ProduceSync_LatencyShouldBeDrivenByKafkaProduceLatency

- .github/workflows/update-vendored-mimir-prometheus.yml
This pull request enhances the `update-vendored-mimir-prometheus.yml` workflow by introducing support for triggering updates via `repository_dispatch` events triggered by https://github.com/grafana/mimir-prometheus/pull/877
I addressed the zizmor checks, but I can't hide the comments
> Update mimir-prometheus on branch pushes

- CHANGELOG.md
- docs/sources/mimir/set-up/migrate/migrate-from-thanos-or-prometheus.md
Clarification to the migration guide, to include information about adding `__tenant_id__` label with tenant name as its value. Without this label, migrated data may not be queried correctly when tenant federation is enabled and Grafana data source is configured to query multiple tenants.
No issue  in Github. Question raised in Slack: https://grafana.slack.com/archives/C039863E8P7/p1745839615875179
> Update Thanos to Mimir migration guide with relabelling tip

- renovate.json5
This PR is a follow up to #11743 that fixes the issue where updates to the Go version in GitHub Actions workflows (eg. for `actions/setup-go` steps) weren't grouped together with the main Go version update PR.
#11743
> Really configure Renovate to update Go version in all locations in one PR

- CHANGELOG.md
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
- operations/mimir-mixin/dashboards/ruler.libsonnet
- pkg/storage/ingest/INTERNALS.md
- pkg/storage/ingest/writer_client.go
- pkg/storage/ingest/writer_test.go
In this PR I'm doing few changes to improve Kafka records production observability (used by ingest storage):
- Added `cortex_ingest_storage_writer_produce_remaining_deadline_seconds` metric, to measure the remaining deadline (in seconds) when records are requested to be produced.
- Added `cortex_ingest_storage_writer_produce_records_enqueue_duration_seconds` metric, to measure how long it takes to enqueue produced Kafka records in the client.
- Renamed `cortex_ingest_storage_writer_produce_requests_total` to `cortex_ingest_storage_writer_produce_records_enqueued_total` (reminder: `cortex_ingest_storage_writer_produce_records_total` also exists and is tracked by the franz-go client; it's the number of records sent over the wire). This metric has been renamed to clarify it's about records …
> Improve ingest storage Kafka records production observability

- cmd/mimir/main.go
`TestFlagParsing` is flaky because the list of dependents is taken from a map's keys, whose order is randomized.
```
--- FAIL: TestFlagParsing/user_visible_module_listing (0.06s)
main_test.go:246: Expected on stdout: "ingester (in: all, write)\n", stdout: alertmanager (in: backend)
...
ingester (in: write, all)
```
Use `slices.Sorted` instead of `slices.Collect` to make the output deterministic.
> Make output of -modules stable

- CHANGELOG.md
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
We've seen a rare panic on ruler shutdown. The stack trace is:
```
/__w/TRUNCATED/vendor/github.com/grafana/dskit/concurrency/worker.go:12 +0x98
created by github.com/grafana/dskit/concurrency.NewReusableGoroutinesPool in goroutine 1
/__w/TRUNCATED/vendor/github.com/grafana/dskit/concurrency/worker.go:16 +0x30
/__w/TRUNCATED/vendor/github.com/grafana/dskit/ring/batch.go:181 +0x98
/__w/TRUNCATED/vendor/github.com/grafana/mimir/pkg/distributor/distributor.go:1854 +0xf8
github.com/grafana/mimir/pkg/distributor.(*Distributor).sendWriteRequestToPartitions.func1({{0x3be65d6, 0x2}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x0, ...}, ...)
/__w/TRUNCATED/vendor/github.com/grafana/mimir/pkg/storage/ingest/writer.go:150 +0xb0
github.com/grafana/mimir/pkg/storage/ingest.(*Writer).WriteSync(0x4002130000, …
```
> Fix rare panic when the ruler is shutting down

- CHANGELOG.md
- pkg/blockbuilder/scheduler/scheduler.go
- pkg/blockbuilder/scheduler/scheduler_test.go
Backport 57235b06864d219026e1168f221efdf2b3be8d53 from #11785
(cherry picked from commit 57235b06864d219026e1168f221efdf2b3be8d53)
> [r347] Block-builder-scheduler: Bug: assigned job skipped if start < commit < end (#11785)

- .github/workflows/update-vendored-mimir-prometheus.yml
This PR extends the automated mimir-prometheus vendoring workflow to automatically run `make generate-otlp` before committing.
This will prevent build failures like those seen in https://github.com/grafana/mimir/pull/11791.
https://github.com/grafana/mimir/pull/11518
> Regenerate OTLP files when updating vendored mimir-prometheus

- go.mod
- go.sum
- pkg/distributor/otel_test.go
- pkg/distributor/otlp/helper_generated.go
- pkg/distributor/otlp/metrics_to_prw_generated.go
- vendor/github.com/prometheus/prometheus/config/config.go
- vendor/github.com/prometheus/prometheus/promql/parser/parse.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/helper.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
- vendor/modules.txt
Upgrade mimir-prometheus to a version that converts non-monotonic OTel sum metrics correctly, i.e. doesn't append a `_total` suffix. The reason is that non-monotonic OTel sums act like gauges (in that they can go up and down), and not counters (which only increase).
This got broken in https://github.com/grafana/mimir/pull/11607.
Fixes #11800.
> OTLP: Fix conversion of non-monotonic sum metrics

- go.mod
- go.sum
- pkg/distributor/otel_test.go
- pkg/distributor/otlp/metrics_to_prw_generated.go
- vendor/github.com/prometheus/prometheus/storage/remote/otlptranslator/prometheusremotewrite/metrics_to_prw.go
- vendor/modules.txt
Upgrade mimir-prometheus to a version that converts non-monotonic OTel sum metrics correctly, i.e. doesn't append a `_total` suffix. The reason is that non-monotonic OTel sums act like gauges (in that they can go up and down), and not counters (which only increase).
This got broken in https://github.com/grafana/mimir/pull/11607.
(cherry picked from commit cebf99cfca9fcb3b6913f16da676fa9a2f502325)
> [r346] Backport 11810 to r346

- CHANGELOG.md
- operations/mimir-mixin-compiled-gem/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/remote-ruler-reads.libsonnet
The ruler-query-frontends (query-frontends for the dedicated ruler read path) are autoscaled. Include a row for their autoscaling metrics.
N/A
> mixin: Add autoscaling row for ruler-query-frontend

- CHANGELOG.md
- operations/mimir/autoscaling.libsonnet
At Grafana Labs, we've noticed that querier deployments scale up and down asymmetrically.  Specifically, brief increases in read traffic, inflight requests, etc. can trigger the querier deployment to scale very quickly and then not scale down for some time even after the scaling metric has returned to baseline levels. In some cases, it’s helpful to be able to control the rate at which queriers scale up or down.
This PR introduces two new configurable options: `$_config.autoscaling_querier_scaleup_percent_cap` for the scale-up rate, and `$_config.autoscaling_querier_scaledown_percent_cap` for the scale-down rate. For example, setting `autoscaling_querier_scaleup_percent_cap` to 50 would allow a querier deployment to scale up by at most 50% of its pods every 2m. The 2m interval is fixed …
> Operations: Allow configuring Querier ScaledObject scaleUp/scaleDown percentages

- pkg/streamingpromql/operators/series_merging.go
This PR removes some outdated comments in `mergeOneSideHistograms`.
(none)
> MQE: remove outdated comments in `mergeOneSideHistograms`

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
Fix MimirGoThreadsTooHigh runbook. Toni just made me realise networking is implemented using async I/O under the hood (but disk I/O is not).
N/A
> Fix MimirGoThreadsTooHigh runbook

- CHANGELOG.md
- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
- Add warning alert that fires when level 1 blocks are queried for more than 1 hour
- Indicates potential compactor performance issues when store-gateway serves non-compacted blocks
- Verify alert compiles correctly in mixin
- Monitor for false positives in production environments
> Add alert for high volume level 1 blocks queried

- pkg/frontend/querymiddleware/model.pb.go
BufferHolder was added in this [PR](https://github.com/grafana/mimir/pull/11136) and mistakenly removed  later ina different [PR](https://github.com/grafana/mimir/pull/11568/files#diff-f460500f40606393884c046e42540c09ff5c7cd6146d2b1f59c6b3d7f2b320e6R85). I confirmed with @aknuds1 that it should be there.
- [N/A] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
> Bring BufferHolder back to PrometheusResponse

- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
This PR makes two changes to common subexpression elimination:
* Tests: I was worried we weren't handling the case where a expression has multiple children correctly, so added some tests to check. Turns out this case is OK, but I think it'd be valuable to retain so it's not broken in the future.
* Metric: the existing `cortex_mimir_query_engine_common_subexpression_elimination_duplication_nodes_introduced` metric is useful for gauging the impact of CSE, but doesn't tell us how much load on ingesters and store-gateways we've avoided. The new metric tells us the number of selectors eliminated and therefore gives us a better idea of the number of avoided ingester and store-gateway requests.
#11189 
- [covered by #10067] `CHANGELOG.md` updated - the order of …
> MQE: add tests for common subexpression elimination for expressions with multiple children, and add metric on number of selectors eliminated

- .github/workflows/update-vendored-mimir-prometheus.yml
- Makefile
This makes it easier to manage the dependencies of the script and upgrade them only in a single place. The build image already contains these dependencies. For this I also had to move the target into the targets that run in a build image.
example run https://github.com/grafana/mimir/actions/runs/15878851471/job/44773419103 and PR https://github.com/grafana/mimir/pull/11860 (the point is that the PR's CI passes and that the GH action completes)
> generate-otlp: run in build image

- docs/sources/mimir/references/http-api/_index.md
Adds documentation for the Influx endpoint (similar to that of the OTLP endpoint).
* https://github.com/grafana/mimir/pull/10153 (main PR for Influx endpoint)
* https://github.com/grafana/mimir/pull/10505 (fix to path)
> docs: Add influx section to HTTP api reference

- .github/workflows/scripts/run-unit-tests-group.sh
This PR fixes an issue where the second attempt to run unit tests would re-run all unit tests, including those that already passed.
This isn't necessary, and introduces the risk that a test that previously passed will flake and fail.
#11300
> CI: don't re-run unit tests that have already passed when retrying

- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
This PR builds on https://github.com/grafana/mimir/pull/11879, addressing https://github.com/grafana/mimir/pull/11879#discussion_r2172182055 and adding an additional "selectors inspected" metric.
#11879
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
> MQE: simplify logic for "selectors eliminated" metric in CSE, and add "selectors inspected" metric

- pkg/blockbuilder/metrics.go
- pkg/blockbuilder/tsdb.go
This PR adds a new metric to the `blockbuilder`: 
* `cortex_blockbuilder_tsdb_last_successful_compact_and_upload_timestamp_seconds` — tracks the per-partition timestamps of the last successful block uploading
The idea behind the metric is that we could fire an alert if the block-builder stopped shipping blocks for an extended period of time.
> blockbuilder: add cortex_blockbuilder_tsdb_last_successful_compact_and_upload_timestamp_seconds

- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
This PR fixes a broken test introduced by #11587 that did not take into account the changes from #11900.
#11587
> Fix broken test

- pkg/alertmanager/api_grafana.go
- pkg/alertmanager/api_grafana_test.go
This PR changes the handler that saves Grafana Alertmanager configurtion to preserve the original JSON string during unmarshaling, instead of re-marshaling the parsed Go struct before saving it.
If we do a JSON marshalling round-trip and the Grafana config contains an upstream Alertmanager configuration, secrets, [example](https://github.com/prometheus/alertmanager/blob/0ce3cfb962db3cbb1649d3e816a49a13c4036cd1/config/config.go#L56), in this configuration are lost during marshalling and saved to the storage as redacted strings. 
Instead this PR makes the handler use JSON unmarshalling to validate the configuration, and save the original JSON to the storage.
> Alertmanager: Save the original config string when updating Grafana configuration

- CHANGELOG.md
- pkg/frontend/querymiddleware/roundtrip.go
This PR moves the query pruning and experimental functions middlewares earlier in the query-frontend pipeline.
This has a number of benefits:
* these middlewares now run before splitting and sharding, so they are only applied once to the entire query rather than once per split and sharded leg
* these middlewares no longer run after sharding, which will make it easier to migrate sharding to a MQE query planner optimisation pass in the future
* the experimental functions middleware now runs immediately after the error caching middleware, so queries that will be rejected are rejected and cached before doing as much work as possible
(none)
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/ …
> Move query pruning and experimental functions middlewares earlier in query-frontend pipeline

- pkg/streamingpromql/operators/binops/binary_operation.go
- pkg/streamingpromql/testdata/ours/binary_operators.test
This PR changes the behaviour of MQE's implementation of binary operations to match Prometheus' query engine.
Specifically, it changes MQE to match how Prometheus handles binary operations with `on (__name__)`. Prometheus always drops the metric name label, even if it is listed in `on`, as discussed in https://github.com/prometheus/prometheus/issues/16631. Changing this in Prometheus is considered a breaking change, so [I've updated the Prometheus documentation](https://github.com/prometheus/prometheus/pull/16716) to explicitly state that the current behaviour is expected, and in this PR I'm updating MQE to match.
https://github.com/prometheus/prometheus/issues/16631
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, …
> MQE: adjust behaviour of binary operations with `on (__name__)` to match Prometheus

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/handlers.go
- pkg/mimir/modules.go
- pkg/querier/querier.go
- pkg/querier/remote_read.go
- pkg/querier/remote_read_test.go
- Added `-querier.max-concurrent-remote-read-queries` flag (default: 2)
- 0 or negative values mean unlimited concurrency
- Uses `concurrency.ForEachJob` pattern for implementation like @zenador suggested
Addresses discussion in https://github.com/grafana/mimir/pull/11732#discussion_r2148903080 with @charleskorn where unlimited concurrency could hold too much data in memory. Default limit provides safety while allowing GEM to configure unlimited when needed.
> querier: limit remote read parallelism

- pkg/streamingpromql/engine_test.go
follow-up of #11683
The memory estimations have peaks during different stages of query processing when running with `-tags stringlabels` and when running without.
When running without `stringlabels`, strings appear cheaper (because the plain `ByteSize()` doesn't account for slice overhead). Because of this, the peak is during floating point processing.
When running with `stringlabels`, strings appear more expensive. Then the peak is during labels processing.
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs …
> MQE: Fix estimations in TestMemoryConsumptionLimit_SingleQueries

- pkg/alertmanager/notify_hooks_notifier.go
- pkg/alertmanager/notify_hooks_notifier_test.go
We weren't correctly checking the error code, which was seemingly fine unless the
hook returned valid JSON, in which case this was parsed as a valid payload.
Additionally, allow the hook to return 204 (No Content) to indicate it did not
perform any processing, and do not log errors in this case.
> Alertmanager: Check error code fron pre-notify hooks, and ignore 204.

- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/series_data_ring_buffer.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/series_data_ring_buffer_test.go
This PR fixes an issue where common subexpression elimination (CSE) can cause a query to return incorrect query results.
The issue would occur if the ring buffer used to buffer data was in a state where the head of the buffer is at the end of the slice, and the tail was at the beginning of the slice. In this case, calling `Remove` for the item at the end of the slice would return the correct value, as would the subsequent call for the item at the beginning of the slice, but all following calls would return incorrect values.
#11189 
- [covered by #10067] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
- [n/a] …
> MQE: fix issue where a query with a common subexpression could return incorrect results

- pkg/storegateway/parquet_bucket_store.go
- pkg/storegateway/parquet_bucket_store_test.go
- pkg/storegateway/parquet_bucket_stores_test.go
Inefficient, but at least correct query sharding. The new test on sharding fails on the base branch. 
It's not trivial to add caching to the hashes like the main path does, because we don't have a `SeriesRef` to use as a cache key at the block level (to match what the main path does). We could in theory use something like the row number in the parquet file, but we don't have easy access to that in this part of the code. In any case, the priority right now is correctness, we'll work on optimizing later as appropriate.
For referece, see how query sharding is handled on the main path: https://github.com/grafana/mimir/blob/604775d447c0a9e893fa6930ef8f2d403ebe6757/pkg/storegateway/series_refs.go#L1021-L1047
> fix(parquet store gateway): obey query sharding matchers

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/alerts.libsonnet
Increasing scope of golang_alerts since labels as `namespace` are usually related to cloud deployments.
> Replace namespace with job label in golang_alerts

- pkg/blockbuilder/blockbuilder.go
- pkg/blockbuilder/tsdb.go
- pkg/blockbuilder/tsdb_test.go
Here is the follow-up to the #11643
The PR is a part of a refactoring in the block-builder's internals. Here I update the `TSDBBuilder.Process`, removing the legacy handling of stand-alone cases.
> blockbuilder: refactor TSDBBuilder.Process

- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-10-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-11-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-9-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir/ingest-storage.libsonnet
Exposes a config knob that controls and validates the experimental `ingest-storage.kafka.producer-record-version` arg. We default to 0, which is the current default if unsupplied.
It seems we don't support any `-ingest-storage.*` controls in the helm chart, so I didn't touch that.
Contrib https://github.com/grafana/mimir-squad/issues/2253
> operations: Add knob for controlling ingest-storage producer record version

- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
In #11872 we added the `cortex_blockbuilder_tsdb_last_successful_compact_and_upload_timestamp_seconds` metric, that the block-builder exposes to track its shipment of blocks.
In this PR we update the ingester alerts to not trigger if the mentioned metric exists. This is so we could safely stop the ingesters from uploading the blocks to the object store, while the block-builder is doing that.
Also, the PR updates related runbooks. It removes the references to alerts and metrics of the legacy stand-alone mode, and adds the new one.
> Update IngesterHasNotShippedBlocks to be block-builder aware

- pkg/alertmanager/alertmanager_metrics.go
- pkg/alertmanager/alertmanager_metrics_test.go
- pkg/alertmanager/notify_hooks_notifier.go
- pkg/alertmanager/notify_hooks_notifier_test.go
Adds duration metric, and adds status_code to the failed metric.
> Alertmanager: Improve metrics and add tracing for pre-notify hooks.

- CHANGELOG.md
- pkg/mimirtool/backfill/backfill.go
- pkg/mimirtool/commands/remote_read.go
- pkg/mimirtool/commands/remote_read_test.go
This PR fixes a number of issues in `mimirtool remote-read export` that could occur when querying a range longer than an hour, or that crossed block boundaries (which were hardcoded to 2h in size). In particular, queries that crossed block boundaries could omit some output blocks.
Key changes:
- Output blocks will now be 2h in length, not 1h, and this can be configured with `--block-size`.
- Time ranges that cross block boundaries are now handled correctly, including for cases where some series appear in only some output blocks.
- Long time ranges are now broken up into intervals that match the output block size, reducing the amount of data that must be held in memory by `mimirtool` and simplifying the logic of producing blocks in this case. 
- An alternative solution would be to create …
> Fix issues with `mimirtool remote-read export` and long time ranges

- pkg/streamingpromql/operators/subquery.go
- pkg/streamingpromql/operators/subquery_test.go
- pkg/streamingpromql/planning/core/subquery.go
Fixes a panic in the Subquery operator that could occur if `Close() `is invoked after a failed` Prepare()` call:
1. subqueryStats is initialized during Prepare()
2. if `Prepare()` fails, subqueryStats remains nil.
3. calling `Close()` result in a nil pointer dereference when attempting to call `subqueryStats.Close()`.
- [N/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
> mqe: init Subquery childStats in a NewSubquery to avoid panic 

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- development/mimir-ingest-storage/config/runtime.yaml
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/labels_query_optimizer.go
- pkg/frontend/querymiddleware/labels_query_optimizer_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/util/validation/limits.go
This PR introduces a new labels query optimizer middleware for the query-frontend that automatically removes
the ` __name__!=""` matcher from label names queries when the matcher is redundant. The PR also includes a bug
fix for the limit parameter validation in label queries: the value 0 was not supported previously, but it's actually a valid parameter in Prometheus (means unlimited).
I've tested the following matchers, comparing the result with and without the optimizer enabled and I've got the same exact results:
- No matchers
- With `{}` matcher (invalid)
- With `{__name__!=""}` matcher
- With `{__name__!="", container="mimir-write"}` matcher
- With `{__name__!="", __name__="up"}` matcher
- With `{__name__!=""}` and `{__name__=~"a.*"}` matchers
- With `{__name__!="", __name__=~"a.*"}` …
> Optimise label names API by removing __name__!="" matcher when redundant

- pkg/storage/tsdb/block/index.go
- tools/tsdb-index-health/main_test.go
The compactor's `GatherBlockHealthStats()` gather several stats. We never read many of them. We can clean them up.
N/A
> Chore: remove unused block stats in compactor's GatherBlockHealthStats()

- docs/internal/contributing/design-patterns-and-conventions.md
The fact that claude doesn't end comments with a period is driving me crazy 😄 It's part of the go styling guide, but looks ignoring it. Let's make it explicit, copying the sentence from the styleguide.
N/A
> Chore: instruct claude to end comments with a period

- CHANGELOG.md
- docs/sources/mimir/configure/configure-tracing.md
- go.mod
- go.sum
- pkg/frontend/v1/frontend_test.go
- pkg/querier/engine/query_tracker_test.go
- vendor/github.com/grafana/dskit/tracing/otel.go
- vendor/github.com/grafana/dskit/tracing/otel_jaeger.go
- vendor/modules.txt
This updates dskit to include https://github.com/grafana/dskit/pull/723
This will stop configuring the tracing libraries when no tracing environment variables were provided, as by default OTel libraries will try to export spans to `localhost` and complain because it would reject them.
Related to the migration to OTel tracing.
> Update dskit to skip tracing configuration when no env is defined

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- go.mod
- go.sum
- pkg/storage/parquet/chunk_querier.go
- pkg/storage/parquet/queryable_shard.go
- pkg/storage/tsdb/config.go
- pkg/storegateway/bucket_stores_test.go
- pkg/storegateway/parquet_bucket_store.go
- pkg/storegateway/parquet_bucket_store_test.go
- pkg/storegateway/parquet_bucket_stores.go
- pkg/storegateway/parquet_bucket_stores_test.go
- vendor/github.com/prometheus-community/parquet-common/convert/convert.go
- vendor/github.com/prometheus-community/parquet-common/convert/writer.go
- vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go
- vendor/github.com/prometheus-community/parquet-common/search/limits.go
- vendor/github.com/prometheus-community/parquet-common/search/materialize.go
- vendor/modules.txt
This PR is based on the upstream work https://github.com/prometheus-community/parquet-common/pull/81
The idea is to implement a set of basic quota limiters that can protect us against potential bad queries for the gateways.
Note we had to bring bits of the code available in the querier in upstream because we have our own chunk querier in Mimir.
> feature(parquet): Implement store-gateway limits

- cmd/mimir/config-descriptor.json
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/query_blocker_test.go
- pkg/frontend/querymiddleware/query_limiter_test.go
- pkg/frontend/querymiddleware/request_blocker_test.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/mimirtool/config/inspect.go
- pkg/util/validation/blocked_query.go
- pkg/util/validation/blocked_request.go
- pkg/util/validation/limited_query.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_test.go
- tools/doc-generator/parse/parser.go
- tools/doc-generator/write/writer.go
- tools/doc-generator/write/writer_test.go
This PR improves how the configuration of blocked requests, blocked queries and limited queries is displayed in the docs.
In particular:
* all fields are now shown as they would be for any other config block, rather than relying on a comment
* an example has been added for how to configure a blocked request
To achieve this, I've made two changes to the config doc generator:
* maps of structs are now shown expanded, instead of as `map of string to package.SomeStruct`
* examples (if available) are now shown for all types of fields
I've also changed the implementation of `ExampleDoc` for each type to use the Go type rather than a generic map, so these should stay in-sync with the actual configuration fields. I changed the blocked requests, blocked queries and limited queries slices to not …
> Improve docs for blocked requests, blocked queries and limited queries config options

- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/labels_query_optimizer.go
- pkg/frontend/querymiddleware/limits.go
This PR addresses the comment received [here](https://github.com/grafana/mimir/pull/12076#discussion_r2205602043). The idea is to move the X-Scope-OrgID HTTP header injection into `EncodeLabelsSeriesQueryRequest()` and `EncodeMetricsQueryRequest()` instead of doing it in the caller, right after encoding requests. The `EncodeLabelsSeriesQueryRequest()` and `EncodeMetricsQueryRequest()` are only called in places where `user.InjectOrgIDIntoHTTPRequest()` is called right after (and same in GEM, that I will take care of updating if this PR is accepted).
N/A
> Refactoring: move X-Scope-OrgID HTTP header injection into EncodeLabelsSeriesQueryRequest() and EncodeMetricsQueryRequest()

- go.mod
- go.sum
- vendor/github.com/prometheus/prometheus/storage/remote/write.go
- vendor/github.com/prometheus/prometheus/tsdb/wlog/live_reader.go
- vendor/github.com/prometheus/prometheus/tsdb/wlog/watcher.go
- vendor/modules.txt
This PR brings in https://github.com/grafana/mimir-prometheus/pull/936 (backported to the 2.17 branch with https://github.com/grafana/mimir-prometheus/pull/942), as this is needed for a bugfix included in GEM 2.17.
(none)
> [2.17] Update mimir-prometheus

- CHANGELOG.md
- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/templates/distributor/distributor-dep.yaml
- operations/mimir/distributor.libsonnet
Reduce the calculated value of `GOMAXPROCS` for distributors to be closer to the requested CPU. This upstreams a change we have been using and tesing internally.
N/A
> jsonnet, helm: Reduce distributor GOMAXPROCS

- docs/sources/mimir/references/architecture/deployment-modes/index.md
This PR adds a note to https://grafana.com/docs/mimir/latest/references/architecture/deployment-modes/ to caution against using monolithic mode for large-scale deployments.
Fixes https://github.com/grafana/mimir-squad/issues/2646
> add note about not using monolithic mode for large-scale deployments

- docs/sources/mimir/send/native-histograms/_index.md
- docs/sources/mimir/visualize/native-histograms/_index.md
The PR adds a cross-reference to the [Prometheus Native Histograms spec](https://prometheus.io/docs/specs/native_histograms/) from the following pages:
- https://grafana.com/docs/mimir/latest/visualize/native-histograms/
- https://grafana.com/docs/mimir/latest/send/native-histograms/
Fixes https://github.com/grafana/mimir/issues/10401
> Docs: Cross-reference native histogram specification

- CHANGELOG.md
- pkg/storage/tsdb/bucketindex/loader.go
- pkg/storage/tsdb/bucketindex/loader_test.go
- pkg/util/promtest/histogram.go
- Adds native histogram definition to `cortex_bucket_index_load_duration_seconds`, uses standard parameters:
- BucketFactor: 1.1
- MaxBuckets: 100
- MinResetDuration: 1h
- adds new `promtest` package with helpers to check if
-  a metric is native histogram
- a histogram has correct amount of samples
Part of: https://github.com/grafana/mimir-squad/issues/3077
> querier: add native histogram definition to cortex_bucket_index_load_duration_seconds

- development/common/config/nginx.conf.template
- integration/alertmanager_test.go
- integration/e2emimir/client.go
- pkg/alertmanager/api.go
- pkg/alertmanager/api_grafana.go
- pkg/alertmanager/api_grafana_test.go
- pkg/api/api.go
Currently, Grafana fetches entire configuration from the Mimir just to compare the currently active configuration with the desired one. The configuration could be large, which will take some resources from Grafana to unmarshall and compare it again. Instead alerting team decided to rely on the hash that Grafana will calculate and then compare. 
This pull request introduces a new endpoint `/api/v1/grafana/config/status` that returns just the bare minimum information needed to determine whether desired configuration needs to be pushed from Grafana to Mimir Alertmanager.
This PR does not affect the base Mimir Alertmanager functionality and exposes the new endpoint only if Grafana compatibility is enabled.
> Alertmanager: Grafana configuration status API endpoint

- CHANGELOG.md
- pkg/blockbuilder/scheduler/metrics.go
- pkg/blockbuilder/scheduler/scheduler.go
- pkg/blockbuilder/scheduler/scheduler_test.go
Backport 0a75686b7a7b555ee8e9bc15458b1899e2b067b5 from #12130
> [r351] Block-builder-scheduler: fix bugs in handling of partitions with no commit (#12130)

- Makefile
- pkg/ingester/shipper_test.go
- pkg/mimirpb/timeseries_test.go
Replace [sort.SliceIsSorted](https://pkg.go.dev/sort#SliceIsSorted) with [slices.IsSortedFunc](https://pkg.go.dev/slices#IsSortedFunc). `slices.IsSortedFunc` is generic instead of reflection based, and should generally be more performant.
> Replace sort.SliceIsSorted with slices.IsSortedFunc

- operations/mimir/ingest-storage.libsonnet
Allows V2 as a producer record version as of https://github.com/grafana/mimir/pull/12060.
V2 is still considered unstable at the time of writing. We might make breaking changes to the format.
Thus, we include a guard where you have to explicitly opt-in to experimental formats before setting v2.
Contrib https://github.com/grafana/mimir-squad/issues/2253
> operations: Allow ingest-storage record version to be increased to v2

- pkg/alertmanager/multitenant.go
Security is working on rolling out semgrep across our codebase. Because of some parser deficiencies in semgrep (the user-configurable rule engine runs after AST parsing, which discards comments), we can't just force it to respect #nosec, so this PR converts lines with valid gosec suppression directives into lines that also contain a valid equivalent semgrep suppression. I know it's ugly, sorry.
- [NA] Tests updated.
- [NA] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> chore: Autofix to make #nosec suppressions also legible to semgrep

- pkg/mimirpb/custom.go
- pkg/mimirpb/custom_test.go
- pkg/mimirpb/prealloc_rw2.go
- pkg/mimirpb/prealloc_rw2_test.go
- pkg/mimirpb/split.go
- pkg/mimirpb/split_test.go
- pkg/mimirpb/symbols.go
- pkg/mimirpb/symbols_test.go
- pkg/mimirpb/timeseries.go
- pkg/storage/ingest/version.go
- pkg/storage/ingest/writer.go
- pkg/storage/ingest/writer_test.go
This is the record format V2 equivalent of https://github.com/grafana/mimir/pull/8077. Kafka has a limit in payload size, here we break down extremely large requests into multiple records to work around it.
RW2 carries some complexity due to the symbols table. When splitting a request, we have to split the symbols as well. It's not reasonable to use all the symbols on each request, because symbols still dominate the overall request size.
This PR uses a similar bin-packing algorithm to RW1, but it also re-symbolizes each Timeseries as we move along, using a separate symbols table per sub-request. That means each Timeseries can re-use symbols from other timeseries in the same request as they're added, up until the point where the request is close to the max.
To determine when to split a …
> ingest-storage: Split very large RW2.0 requests into multiple Kafka records

- CHANGELOG.md
- cmd/mimir/Dockerfile
Debian 12 (which the base Distroless image for Mimir is based on) is using an outdated version version of Mozilla's CA bundle (v2.60) which is missing several root CA's. This change pulls an update bundle from Debian Testing to ensure outgoing requests to trusted domains will not fail during certificate verification.
Related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1108314
- n/a Tests updated.
> Build: Include updated Mozilla CA bundle from Debian Testing

- pkg/alertmanager/multitenant_test.go
This PR adds a test for _strict initialization_, checking that skipped Alertmanagers are started after requests and cleared out after the grace period elapses.
> Alertmanager: Add test for strict initialization

- CHANGELOG.md
- pkg/distributor/errors.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
Commit: https://github.com/grafana/mimir/commit/9bf900ec68c9b0ec217200cf10bdecff93005c8b
> [r352] Revert otlp: Stick to OTLP vocabulary on invalid label value length error

- CHANGELOG.md
- pkg/distributor/errors.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
This reverts commit 9bf900ec68c9b0ec217200cf10bdecff93005c8b.
> [r353] Revert "otlp: Stick to OTLP vocabulary on invalid label value length error (#11889)"

- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/query.go
The query-frontend emits a `query stats` log message after each query request is completed. 
MQE also emits a `query stats` log message after evaluation is completed. 
With MQE now running in query-frontends, this is potentially confusing, so I've changed the log message from MQE to `evaluation stats` to make it unambiguous.
https://github.com/grafana/mimir/pull/11417
> MQE: change log message to disambiguate from query-frontend query stats log messages

- CHANGELOG.md
- pkg/distributor/errors.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
This reverts #11889 which has a pooled memory re-use bug.
> revert #11889 and fix conflicts.

- pkg/streamingpromql/floats/kahan.go
See https://github.com/prometheus/prometheus/pull/16895 for further explanation. We've copied the code into MQE, so we need to apply the same change here as well.
https://github.com/prometheus/prometheus/pull/16895
> MQE: reduce numerical errors by not inlining `KahanSumInc`

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/ci/offline/test-enterprise-values.yaml
- operations/helm/charts/mimir-distributed/templates/gateway/gateway-ingress.yaml
- operations/helm/charts/mimir-distributed/values.yaml
- operations/helm/tests/test-enterprise-values-generated/mimir-distributed/templates/gateway/gateway-ingress.yaml
This update introduces a new `labels` field under the `gateway.ingress` section in the `values.yaml` file, allowing users to specify custom labels for the Ingress resource. The corresponding template in `gateway-ingress.yaml` has been updated to include these labels in the metadata.
- Added `labels: {}` to `values.yaml`
- Updated `gateway-ingress.yaml` to render labels if provided
This enhancement improves the flexibility of the Ingress configuration for users deploying the Mimir distributed system.
Checklist
> [HELM] Add labels configuration for gateway ingress

- CHANGELOG.md
- pkg/querier/worker/scheduler_processor.go
- pkg/querier/worker/scheduler_processor_test.go
Check the size of the entire response being sent to the query-frontend before sending it, not just the body. This fixes edge cases where a response body wasn't larger than the grpc limit but the entire request was. This resulted in timeouts in the query-frontend since the scheduler processor was never able to sent a response to the query-frontend.
This is the same issue as #10154 but in the querier worker that pulls from the query-scheduler instead of the query-frontend.
Related #10154
Required for #12200
> querier: check size of whole frontend response before sending it

- CHANGELOG.md
- pkg/distributor/errors.go
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
Manually backporting https://github.com/grafana/mimir/pull/12266 as there was a conflict in changelog and `validate_test.go`.
> Backporting #12266 to release 2.17

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/compactor/blocks_cleaner.go
- pkg/compactor/blocks_cleaner_test.go
- pkg/compactor/compactor.go
- pkg/storage/tsdb/bucketindex/storage_test.go
- pkg/storage/tsdb/bucketindex/updater.go
- pkg/storage/tsdb/bucketindex/updater_test.go
- pkg/storegateway/gateway_test.go
- pkg/storegateway/metadata_fetcher_filters_test.go
Parallelizes `updateBlock`. We having seen updating the block index take quite a while when there's a lot of new blocks. This seems like a naturally parallelizable problem. 
> Parallelize `updateBlock`

- docs/sources/helm-charts/mimir-distributed/release-notes/v5.8.md
This PR adds release notes for the Mimir Helm chart version 5.8 release.
Fixes https://github.com/grafana/mimir-squad/issues/3152
> mimir-distributed 5.8 release notes

- pkg/alertmanager/api_grafana.go
- pkg/alertmanager/config.go
- pkg/alertmanager/config_test.go
- pkg/alertmanager/multitenant.go
- pkg/alertmanager/multitenant_test.go
This PR refactors the `createUsableGrafanaConfig` function.
Three changes:
- Rename to `amConfigFromGrafanaConfig`: It's not clear what "usable" means. The name `amConfigFromGrafanaConfig` implies we're creating an `amConfig` from a Grafana configuration.
- Make it a method in the `MultitenantAlertmanager`: we can use the logger and fallback configs in the struct instead of always passing them as arguments
- Remove logger and config arguments: we're always using the same config and loggers, it's unnecessary for the caller to always pass these
Part of https://github.com/grafana/mimir/pull/12272
> Alertmanager: Refactor createUsableGrafanaConfig

- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/blocks.libsonnet
This is an alternative fix for the issue, https://github.com/grafana/mimir/pull/12314 wanted to address (_providing I understood the motivation for later_).
We observed a couple of cases, where the block-builder deployment was restarted right around the end of its hourly cycle. This reset its `successful_compact_and_upload_timestamp_seconds`, and delays the next update of the metric, until the updated block-builders catch up. In turn, this caused the `MimirIngesterHasUnshippedBlocks` to fire, because the mentioned metric wasn't set.
This PR updates the `MimirIngesterHasUnshippedBlocks` (and related) alerts, relaxing the `unless ...` hand, so it looked it for the past N minutes, when it checked for block-builder's `successful_compact_and_upload_timestamp_seconds`.
> mimir-mixin: relax the guard in IngesterHasUnshippedBlocks when block-builder is running

- pkg/api/api.go
- pkg/costattribution/testutils/test_utils.go
- pkg/distributor/distributor_test.go
- pkg/distributor/push.go
- pkg/distributor/push_test.go
- pkg/distributor/validate_test.go
- pkg/util/active_groups.go
- pkg/util/requestbuffers.go
The [recent incident](https://grafana.com/blog/2025/08/03/grafana-cloud-metrics-memory-corruption-issue-resolved/) introduced by https://github.com/grafana/mimir/pull/11889 would have been caught with a sufficiently exhaustive test suite.
* Change the distributor validation tests so that they submit actual gRPC write requests, which use the request buffer pool.
* Repeat each test a number of times to increase the likelihood of triggering use-after-release issues.
* Taint the buffers before returning them to the pool, so that even if the buffer isn't reused, lingering references still point to unexpected contents to make tests fail.
To demonstrate that these changes are enough to catch the issue, the original PR has been resubmitted (as a draft) on top of this branch, and [tests do …
> Trigger request buffer reuse in distributor validation tests

- CHANGELOG.md
- pkg/frontend/v1/frontend.go
- pkg/frontend/v1/frontend_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
Add native histogram definitions to
- `cortex_query_scheduler_queue_duration_seconds`
- `cortex_query_frontend_queue_duration_seconds`
with the following parameters:
```go
NativeHistogramBucketFactor:     1.1,
NativeHistogramMinResetDuration: 1 * time.Hour,
NativeHistogramMaxBucketNumber:  100,
```
Part of: https://github.com/grafana/mimir-squad/issues/3077
> Native histogram definitions for cortex_query_{frontend|scheduler}_queue_duration_seconds

- operations/helm/charts/mimir-distributed/CHANGELOG.md
- operations/helm/charts/mimir-distributed/values.yaml
This PR marks `metaMonitoring.grafanaAgent` as deprecated, and suggests users to switch to external system, that can capture meta-monitoring telemetry.
Ref to a detailed explanation in the comment https://github.com/grafana/mimir/issues/5860#issuecomment-3035319639
Part of https://github.com/grafana/mimir/issues/5860
> helm: deprecate metaMonitoring.grafanaAgent

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/config.go
We've been running query-frontends with MQE enabled in production at Grafana Labs for quite a while now, and have had no issues. 
So in this PR I'm making MQE the default. It's still possible to switch back to Prometheus' engine by setting `-query-frontend.query-engine=prometheus`.
Resolves https://github.com/grafana/mimir/issues/11882
> Make MQE the default query engine in query-frontends

- docs/internal/contributing/README.md
Introduces a section in our contributing guidelines in the hopes of raise awareness of yoloStrings and its perils.
This also updates CLAUDE.md, which is a symlink.
https://grafana.com/blog/2025/08/03/grafana-cloud-metrics-memory-corruption-issue-resolved/
> Document yoloStrings and buffer pooling in contributing/README.md

- CHANGELOG.md
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/mimir/runtime_config_test.go
- pkg/util/validation/limits.go
- pkg/util/validation/limits_mock.go
- pkg/util/validation/limits_test.go
Modify validation code to not configure default OTel metric and label name translation strategy, but instead leave that to the distributor's OTLP endpoint logic. This is because we found a bug connected to automatically deducing the translation strategy within `Limits.Validate`, and it might as well be done at the call site (in the OTLP endpoint).
> Distributor: Auto-deduce OTel translation strategy in OTLP endpoint if unset

- pkg/alertmanager/notify_hooks_notifier.go
Adds HTTP tracing to Alertmanager notify hooks by wrapping the HTTP client transport with `otelhttp.NewTransport`. Span is already created [here](https://github.com/grafana/mimir/blob/f095c6dbfb9449299568138ae6bb53b1a3559026/pkg/alertmanager/notify_hooks_notifier.go#L191).
> Alertmanager: Add HTTP tracing to notify hooks outgoing requests

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/about-versioning.md
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/util/validation/limits.go
Stabilize the setting introduced in #10660 to enable experimental PromQL functions per tenant using query-frontend middleware.
Related #10660
> chore: Stabilize setting to enable experimental PromQL functions

- CHANGELOG.md
- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-multi-zone-distributor-generated.yaml
- operations/mimir-tests/test-new-resource-scaled-object-generated.yaml
- operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
- operations/mimir/autoscaling.libsonnet
At Grafana Labs, we have encountered cases where rate() extrapolates a metric over missing values, underestimates CPU utilization, and triggers an unnecessary downscaling. This PR switches the default CPU scaler metrics to use `irate()` rather than `rate()` (see:`autoscaling.libsonnet`) and affects the scaling behavior of the following components: 
- alertmanager
- query frontend
- ruler
- ruler querier 
- ruler query frontend 
- distributor
This change makes the scaling metric more reliable when scrapes fail, because irate() only uses the last two data points rather than extrapolating over the full window. For example, consider the following chart where the target prometheus instance begins failing intermittently around 21:17. The `rate()` based scaling metric (in green) drops while the …
> Multiple Components: Use irate in CPU HPA query

- CHANGELOG.md
- docs/sources/mimir/configure/about-dns-service-discovery.md
Document that domain names used with DNS service discovery must be fully qualified after the changes from #12175
Related #12175
> docs: DNS service discovery domains must be fully qualified

- pkg/streamingpromql/engine.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/node.go
- pkg/streamingpromql/planning/core/aggregate_expression.go
- pkg/streamingpromql/planning/core/binary_expression.go
- pkg/streamingpromql/planning/core/function_call.go
- pkg/streamingpromql/planning/core/matrix_selector.go
- pkg/streamingpromql/planning/core/number_literal.go
- pkg/streamingpromql/planning/core/string_literal.go
- pkg/streamingpromql/planning/core/subquery.go
- pkg/streamingpromql/planning/core/unary_expression.go
- pkg/streamingpromql/planning/core/vector_selector.go
- pkg/streamingpromql/planning/materialize.go
- pkg/streamingpromql/planning/plan.go
- pkg/streamingpromql/planning/plan_test.go
This PR changes the responsibilities of MQE's `Materializer` type.
Previously, `Materializer.ConvertNodeToOperator` would materialize all of the given node's children and pass it to `Node.OperatorFactory`, and `OperatorFactory` would have no access to the `Materializer`. With the existing set of query plan nodes, this was not an issue, but it is problematic for some scenarios, for example:
* for remote execution, there's no point materializing operators for the parts of the query plan that will be executed remotely
* for caching and splitting, there's also no point materializing operators for cached results, but we'll then need to materialize the child operator if there is a cache miss, or only materialize the child operator for a subset of the time range
This PR also moves `Materializer` …
> MQE: shift responsibilities of `Materializer`

- CHANGELOG.md
- pkg/frontend/querymiddleware/astmapper/astmapper.go
- pkg/streamingpromql/optimize/ast/prune_toggles.go
- pkg/streamingpromql/optimize/ast/prune_toggles_test.go
- pkg/streamingpromql/planning.go
Add metrics for prune toggles optimization pass
Follow up to https://github.com/grafana/mimir/pull/12303
> Add metrics for prune toggles optimization pass

- CHANGELOG.md
- operations/mimir-mixin/dashboards/block-builder.libsonnet
Fix a typo'd name in the block-builder-scheduler dashboard errors panel.
- (n/a) Tests updated.
- (n/a) Documentation added.
- (n/a) [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.
> Fix incorrect metric name in block-builder errors dashboard.

- pkg/frontend/v2/frontend.go
- pkg/frontend/v2/frontend_scheduler_adapter.go
- pkg/frontend/v2/frontend_scheduler_adapter_test.go
This PR refactors parts of the query-frontend to make the introduction of remote execution of query plans in queriers easier.
I've tried to make each commit self-contained, and would recommend reviewing each separately.
This PR does not need a changelog entry as it makes no user-visible changes.
Related to #12302
> MQE: query-frontend refactoring to support remote execution of query plans in queriers

- operations/mimir-tests/test-autoscaling-custom-target-utilization-generated.yaml
- operations/mimir-tests/test-autoscaling-generated.yaml
- operations/mimir-tests/test-multi-zone-distributor-generated.yaml
- operations/mimir-tests/test-new-resource-scaled-object-generated.yaml
- operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
- operations/mimir/autoscaling.libsonnet
This PR follows https://github.com/grafana/mimir/pull/12386. The change to the CPU and memory HPA metrics must be re-worked to avoid breaking scaling when there are no OOMKilled pods. We previously [reverted](https://github.com/grafana/mimir/pull/12400) the CPU HPA and partially reverted the memory change.This PR fully restores the memory scaling metric (see comment: [here](https://github.com/grafana/mimir/pull/12386/files#r2276681205)).
> Multiple Components: Include vector(0) in Memory HPA Metric

- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/node.go
- pkg/streamingpromql/planning/core/aggregate_expression.go
- pkg/streamingpromql/planning/core/binary_expression.go
- pkg/streamingpromql/planning/core/function_call.go
- pkg/streamingpromql/planning/core/matrix_selector.go
- pkg/streamingpromql/planning/core/number_literal.go
- pkg/streamingpromql/planning/core/string_literal.go
- pkg/streamingpromql/planning/core/subquery.go
- pkg/streamingpromql/planning/core/unary_expression.go
- pkg/streamingpromql/planning/core/vector_selector.go
- pkg/streamingpromql/planning/plan.go
- pkg/streamingpromql/planning/plan_test.go
This PR introduces an `ExpressionPosition` method to `planning.Node`.
This is necessary to support remote execution, because the remote execution operator needs to be able to provide an expression position based on the node it will evaluate.
I have not added a changelog entry as this should have no user-visible impact.
(none)
> MQE: introduce `Node.ExpressionPosition()` method

- renovate.json5
Mimir 2.17 is released so 2.15 no longer gets automatic updates.
Part of https://github.com/grafana/mimir/issues/12039
> chore: Remove release-2.15 from automated updates

- pkg/querier/dispatcher.go
- pkg/querier/dispatcher_test.go
This PR fixes a potential issue with https://github.com/grafana/mimir/pull/12302. 
If a query-frontend requests remote evaluation of a query plan on a querier where MQE is not enabled, then the querier could panic.
https://github.com/grafana/mimir/pull/12302
> MQE: don't panic if remote execution attempted on querier with MQE disabled

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/ingester/api.go
- pkg/ingester/ingester.go
- pkg/ingester/ingester_activity.go
- pkg/ingester/ingester_profiling.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
Adds ability to include tenant ID in pprof labels for ingester operations. This helps debug performance issues when specific tenants are causing high CPU usage or slow queries.
Based on previous work in #8421, but simplified to just include tenant ID and made configurable via CLI flag.
The flag `-include-tenant-id-in-profile-labels` is disabled by default to avoid any overhead when not needed.
Uses a `ProfilingWrapper` pattern similar to `ActivityTrackerWrapper` to cleanly wrap all ingester methods.
> ingester: Add configurable tenant ID in profile labels

- pkg/compactor/blocks_cleaner_test.go
- pkg/compactor/compactor.go
- pkg/frontend/querymiddleware/querysharding_test.go
- pkg/frontend/querymiddleware/results_cache.go
- pkg/frontend/querymiddleware/sharded_queryable.go
- pkg/mimir/mimir.go
- pkg/mimir/modules.go
- pkg/querier/blocks_store_replicated_set.go
- pkg/scheduler/schedulerdiscovery/config.go
- pkg/storage/bucket/client.go
- pkg/storage/bucket/s3/config.go
- pkg/storage/tsdb/index_cache.go
- pkg/storegateway/bucket_stores_test.go
- pkg/usagestats/reporter.go
- pkg/util/strings.go
- pkg/util/validation/limits.go
- pkg/util/validation/notifications_limit_flag.go
This PR replaces `util.StringsContain` with the equivalent generic version from the standard library as of Go 1.21+.
- n/a Tests updated.
- n/a `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
> Replace StringsContain with slices.Contains.

- pkg/alertmanager/multitenant.go
We're currently logging `"merging configurations not implemented, using mimir config"` whenever a tenant has a custom Mimir configuration and a Grafana configuration that's not marked as default.
If the tenant doesn't have a Grafana config, the struct will have the `Default` field set to `false` (zero value for booleans), and the line will be logged. We can fix this by checking for promoted configs instead of non-default configs.
> Alertmanager: Fix computeConfig warning log

- pkg/mimir/mimir.go
- pkg/mimir/mimir_test.go
- pkg/mimir/modules.go
- pkg/mimir/sanity_check.go
This PR introduces a separate query planner for queriers and another for query-frontends.
Remote execution of query plans is implemented as an optimisation pass that identifies subtrees of the query plan that should be executed remotely. This optimisation pass must only run in query-frontends: queriers should not remotely execute parts of the query plan themselves.
Therefore, in order to behave correctly when running in monolithic or read/write mode, we need to have separate query planners for queriers and query-frontends.
I have not added a changelog entry given this is a refactoring.
(none)
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not …
> MQE: separate query planner for querier and query-frontends

- CHANGELOG.md
- pkg/mimirpb/compat_rw2_test.go
- pkg/mimirpb/mimir.pb.go
- pkg/mimirpb/mimir.pb.go.expdiff
- pkg/mimirpb/prealloc_rw2_test.go
- pkg/storage/ingest/version_test.go
Fixes a bug where we silently drop a metric metadata, if the type is `UNKNOWN`. Such metadata might still contain help/unit text that we want to store. This affects both the Remote Write 2.0 push API and ingest-storage V2 record format.
This happens because we normalize the metric name at the moment we parse the type. Since `UNKNOWN` is the default metric type, Proto often chooses to save a few bytes and never send the field at all. That means we also never parse the `type` field, thus we never normalize the name, thus the value of `normalizeMetricName` is always empty string. The parser now thinks the metric name is empty and drops the metadata as it maps to no series.
The fix simply normalizes the metric name a little later, outside of the `metricType` parsing branch.
Contrib …
> rw2: Do not silently drop metric metadata of type Unknown

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/manager.go
- pkg/ruler/ruler.go
This PR adds a CLI flag to the ruler to allow configuring the max Alertmanager notification batch size.
The default value (256) is the same as the value currently used, so users that don't set this flag should see identical behaviour to before.
(none)
> Add CLI flag to set max Alertmanager notification batch size

- pkg/streamingpromql/engine_fuzz_test.go
Slightly improve the error messages for the fuzz tests.
Before:
```
--- FAIL: FuzzQuery (76.73s)
--- FAIL: FuzzQuery/seed#3348 (0.00s)
engine_fuzz_test.go:126: 
Error Trace:	/__w/mimir/mimir/pkg/streamingpromql/engine_fuzz_test.go:126
/__w/mimir/mimir/pkg/streamingpromql/engine_fuzz_test.go:231
/usr/local/go/src/reflect/value.go:584
/usr/local/go/src/reflect/value.go:368
/usr/local/go/src/testing/fuzz.go:340
Error:      	Expected value not to be nil.
Test:       	FuzzQuery/seed#3348
```
After:
```
--- FAIL: FuzzQuery (76.42s)
--- FAIL: FuzzQuery/seed#3348 (0.00s)
engine_fuzz_test.go:124: 
Error Trace:	/__w/mimir/mimir/pkg/streamingpromql/engine_fuzz_test.go:124
/__w/mimir/mimir/pkg/streamingpromql/engine_fuzz_test.go:231
/usr/local/go/src/reflect/value.go:584 …
```
> MQE: Improve fuzz tests erorr messages

- CHANGELOG.md
- pkg/storage/tsdb/block/block.go
- pkg/storage/tsdb/block/block_test.go
This PR makes a small change to error handling in the block upload logic, updates all returns of `UploadError` in `Upload()` to use pointers (`&UploadError{...}`) instead of values.
When values are used, [errors.As()](https://github.com/grafana/mimir/blob/4dde21906feff9da2646bcbc22fa2572d847c150/pkg/compactor/bucket_compactor.go#L474) will not interpret the returned error as a `UploadError`, not updating the metric with the specific label values and always adding the label/value `type="unknown"`.
In addition, modifies the error wrapping in the `cleanUp` function to use `fmt.Errorf` with `%w` for improved error propagation, replacing the previous use of `errors.Wrapf`.
> Fix compactor_block_uploads_failed_total metric showing type="unknown"

- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
Here I'm updating the "run-production-environment-with-helm" docs with a new recommended approach for doing meta-monitoring. I'm using the same deprecation notice, we already use in https://grafana.com/docs/mimir/latest/manage/monitor-grafana-mimir/monitor-system-health/
Fixes #5860
> docs: update run-in-production following the deprecation of chart's meta-monitoring

- pkg/alertmanager/notify_hooks_notifier.go
- pkg/alertmanager/notify_hooks_notifier_test.go
Adds another field `ExtraData` to `hookData` which is a `json.RawMessage` - this additional data is then passed along via the context.
> Alertmanager: Add ExtraData field to experimental pre-notification hook

- pkg/streamingpromql/operators/selectors/range_vector_selector.go
This PR fixes an issue where errors returned by `NextPoint()` were ignored by `RangeVectorSelector.fillBuffer`.
(none)
> MQE: don't ignore error in `RangeVectorSelector.fillBuffer`

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/rewrite.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/querymiddleware/roundtrip_test.go
- pkg/streamingpromql/optimize/ast/reorder_histogram_aggregation.go
- pkg/streamingpromql/optimize/ast/reorder_histogram_aggregation_test.go
- pkg/streamingpromql/planning.go
Add reordering of histogram aggregations as an AST optimisation pass but run in query frontend rewrite middleware (so that it can be run before query sharding).
Fixes https://github.com/grafana/mimir-squad/issues/3027
Split from https://github.com/grafana/mimir/pull/11971
> Add reordering of histogram aggregations

- pkg/streamingpromql/evaluator.go
- pkg/streamingpromql/operators/functions/absent_over_time.go
- pkg/streamingpromql/operators/functions/function_over_range_vector.go
- pkg/streamingpromql/operators/selectors/range_vector_selector.go
- pkg/streamingpromql/operators/subquery.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/range_vector_operator.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/range_vector_operator_test.go
- pkg/streamingpromql/types/operator.go
This PR adds a `context.Context` parameter to `RangeVectorOperator.NextStepSamples()`.
This will be used by the remote range vector execution operator, as `NextStepSamples` may block waiting for the network, and so the context will allow it to abort if the query is cancelled or times out.
(none)
> MQE: add context parameter to `RangeVectorOperator.NextStepSamples`

- CHANGELOG.md
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
PR #11833 introduced a bug where retried ruler remote querier requests were sent with empty bodies, meaning retries would never succeed and end up with `unknown position: parse error: no expression found in input` errors.
This is because the same `http.Request` is being reused for the retries. This uses a `bytes.Buffer` for the body:
https://github.com/grafana/mimir/blob/9b1e82284bd07b51040e51bbec36609819c7fef6/pkg/ruler/remotequerier.go#L163
The first request will read the entire buffer and get to the end, meaning retries would then send empty requests as they would only start reading from the end of the buffer. 
Previously we were using `httpgrpc.HTTPRequest` with a `[]byte` body that can be read multiple times, which is why the retries used to work: …
> Fix ruler remotequerier request body consumption on retries

- CHANGELOG.md
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
Backport https://github.com/grafana/mimir/commit/898f6c10be98df02da772e1fa742d773aeba0c3c from https://github.com/grafana/mimir/pull/12514
>  [r355] Fix ruler remotequerier request body consumption on retries

- CHANGELOG.md
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
Backport 898f6c10be98df02da772e1fa742d773aeba0c3c from #12514
> [r354] Fix ruler remotequerier request body consumption on retries

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/manager.go
- pkg/ruler/ruler.go
Backports https://github.com/grafana/mimir/commit/9e9954481b6dced9bea1600ffe80b74d5ba2b5de from https://github.com/grafana/mimir/pull/12469 into r356
> [r356] Add CLI flag to set max Alertmanager notification batch size

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/manager.go
- pkg/ruler/ruler.go
Backports https://github.com/grafana/mimir/commit/9e9954481b6dced9bea1600ffe80b74d5ba2b5de from https://github.com/grafana/mimir/pull/12469 into r355
> [r355] Add CLI flag to set max Alertmanager notification batch size

- CHANGELOG.md
- pkg/ingester/ingester.go
Backport https://github.com/grafana/mimir/pull/12538 to r357
> [r357] Correctly decrement numCompactionsInProgress for periodic compactions

- CHANGELOG.md
- pkg/ingester/ingester.go
Backport https://github.com/grafana/mimir/pull/12538 to r355
> [r355] Correctly decrement numCompactionsInProgress for periodic compactions

- CHANGELOG.md
- pkg/ingester/ingester.go
Backport https://github.com/grafana/mimir/pull/12538 to r354
> [r354] Correctly decrement numCompactionsInProgress for periodic compactions

- CHANGELOG.md
- pkg/ingester/downscale.go
- pkg/ingester/downscale_test.go
The rollout-operator calls DELETE on the `prepare-instance-ring-downscale` endpoint for all ingesters constantly. We should only return an error if the ingester is in read-only mode and compacting; it should return OK if compacting while not in read-only mode.
> [ingester] Don't return a 409 from downscale endpoint if compacting while not in read-only mode

- pkg/mimirpb/prealloc_rw2.go
- pkg/mimirpb/prealloc_rw2_test.go
Occasionally RW1.0 requests will contain inconsistent metadata. That is, they might contain multiple metadatas for the same series that don't agree with each other, like a new and old description simultaneously. The prometheus behavior when accepting RW1.0 is to not choose a winner; both metadatas are stored and will appear in the metadata API until they both age out.
RW2.0 tends to prevent this by attaching metadata to series. However, for requests that were converted from 1.0 to 2.0 transparently, we want to preserve the original behavior and ensure both metadata make it through the system.
This PR adjusts the RW1.0 to 2.0 conversion to only deduplicate metadata whose fields are exactly equal during the timeseries matching process. The previous implementation would discard inconsistent …
> mimirpb: Preserve inconsistent metric metadata in RW1 to 2 conversion

- pkg/mimirpb/compat.go
- pkg/mimirpb/compat_test.go
This PR introduces two new methods to the `mimirpb` package, to convert from the `mimirpb` types to their `promql` equivalents.
This has been extracted from a larger PR to try to make that PR smaller and easier to review.
(none)
> Introduce `FromSamplesToFPoints` and `FromHistogramsToHPoints`

- docs/sources/mimir/configure/configure-shuffle-sharding/index.md
this is now ready for a review. 
* revisited the places in the doc which talk about instances to also mention partitions
* added a new section about ingest storage shuffle sharding
related to https://github.com/grafana/mimir-squad/issues/3164
> docs: Update shuffle sharding for ingest storage

- pkg/storegateway/parquetbench/README.md
- pkg/storegateway/parquetbench/bench_test.go
- pkg/storegateway/parquetbench/blockgen/README.md
- pkg/storegateway/parquetbench/blockgen/main.go
- pkg/storegateway/parquetbench/data.go
This PR is a follow up to https://github.com/grafana/mimir/pull/12532 
The previous PR was able to benchmark store-gateway current performance against the newly created parquet code however it would always have to generate the data before each run, slowing us down if we wanted to test with different configurations or block sizes.
In this PR:
- There is a new `blockgen` tool we can use to generate a tsdb + block directory for an user. Includes README documenting the opts.
- The existing benchmark now accepts a `-benchmark-tsdb-dir` argument accepting an entire tsdb. If set it won't generate data on the fly for the benchmark, if not set then it will.
Quick run:
```
$ cd pkg/storegateway/parquetbench
$ go run blockgen/main.go -zones 1000 -instances 10 -verbose -output benchmark-data-15M # …
```
> parquet: Update benchmark to reuse generated block

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/ruler/manager.go
- pkg/ruler/ruler.go
Backports https://github.com/grafana/mimir/commit/9e9954481b6dced9bea1600ffe80b74d5ba2b5de from https://github.com/grafana/mimir/pull/12469 into r354
> [r354] Add CLI flag to set max Alertmanager notification batch size

- pkg/frontend/querymiddleware/querysharding_test_utils_test.go
- pkg/mimir/modules.go
- pkg/querier/dispatcher_test.go
- pkg/querier/engine/config.go
- pkg/querier/querier.go
- pkg/streamingpromql/benchmarks/comparison_test.go
- pkg/streamingpromql/config.go
- pkg/streamingpromql/engine.go
- pkg/streamingpromql/engine_concurrency_test.go
- pkg/streamingpromql/engine_fuzz_test.go
- pkg/streamingpromql/engine_test.go
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass.go
- pkg/streamingpromql/optimize/plan/commonsubexpressionelimination/optimization_pass_test.go
- pkg/streamingpromql/optimize/plan/skip_histogram_decoding_test.go
- pkg/streamingpromql/planning.go
- tools/check-for-disabled-but-supported-mqe-test-cases/main.go
Pass a logger to MQE using engine options instead of as a parameter of the engine constructor. This makes it easier to pass loggers to the various parts of MQE (planner, materializer, engine).
Prerequisite for #12577
> refactor: change how loggers are passed to MQE

- docs/sources/mimir/manage/mimir-runbooks/_index.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/mixin-alerts.yaml
- operations/mimir-mixin-compiled-baremetal/alerts.yaml
- operations/mimir-mixin-compiled-gem/alerts.yaml
- operations/mimir-mixin-compiled/alerts.yaml
- operations/mimir-mixin/alerts/ingest-storage.libsonnet
This PR replaces the experimental `BlockBuilderLagging` alert with a new `BlockBuilderSchedulerPendingJobs`.
In our production, there is a huge difference between what a typical lag looks like in a small cell, comparing to a large one. So we noticed that alerting on lag against a fixed threshold doesn't work well in practice. That is, the block-builder consumes the backlog with a delay of one hour. The delta in the per-partition's lag between the beginning and the end of an hour, depends on how aggressively the distributors produce records to the partitions.
For an immediate alert, I propose we replace the `BlockBuilderLagging` with an alert that reports when the scheduler has "pending" jobs. If the number of such is positive for some period, this is an indicator that the block-builder …
> Replace BlockBuilderLagging alert with BlockBuilderSchedulerPendingJobs

- docs/sources/mimir/configure/about-versioning.md
Update about-versioning docs for removed deprecated HA tracker timeout configs.
Follow-up to https://github.com/grafana/mimir/pull/12321
> Update about-versioning for removed deprecated HA tracker timeout configs

- docs/sources/mimir/configure/about-versioning.md
Update about-versioning for experimental query frontend rewriting middleware
Follow up to https://github.com/grafana/mimir/pull/12304 and https://github.com/grafana/mimir/pull/12305
Ignoring https://github.com/grafana/mimir/pull/12303 as that is already covered under "all flags beginning with `-querier.mimir-query-engine`"
> Update about-versioning for experimental query frontend rewriting middleware

- CHANGELOG.md
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/about-runtime-configuration.md
- docs/sources/mimir/configure/about-versioning.md
- pkg/ingester/ingester.go
- pkg/ingester/ingester_test.go
- pkg/mimir/modules.go
- pkg/mimir/runtime_config.go
Remove the confusingly named setting that controls if chunks or samples are transfered between ingesters and queriers. Despite the name, there is no streaming involved. This setting has been deprecated since 2.17 and isn't in use anywhere in Grafana Cloud.
Related #11711
> chore: remove deprecated ingester chunk streaming setting

- pkg/ingester/circuitbreaker_test.go
- pkg/ingester/downscale_test.go
- pkg/ingester/ingester_early_compaction_test.go
- pkg/ingester/ingester_test.go
- pkg/ingester/lifecycle_test.go
- pkg/ingester/owned_series_test.go
- pkg/ingester/tenants_http_test.go
Replace often repeated boilerplate for starting and stopping ingesters in tests with a helper method. The helper method also uses a more reliable method to ensure the ingester is healthy in the ring than the boilerplate did.
Related #10528
> chore: replace ingester start/stop boilerplate in tests

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/util/validation/limits.go
This PR reduces the default value of the `-validation.max-cost-attribution-cardinality` limit from `10K` to `2K`.
This change is needed to reduce pressure on distributors and ingesters, and to preventing performance degradation.
> [cost attribution]: reduce max cost attribution label cardinality to 2000

- pkg/mimir/modules.go
- pkg/ruler/compat.go
- pkg/ruler/compat_test.go
- pkg/ruler/manager.go
- pkg/ruler/manager_test.go
- pkg/ruler/mapper.go
- pkg/ruler/ruler_test.go
The `mapper` interacts with the disk through a filesystem abstraction, https://github.com/spf13/afero. The mapped files are read by other components, notably the `GroupLoader`, which don't use the abstraction.
This PR expands use of the abstraction to fully cover the file interaction in the ruler, and allows a common FS instance to be injected among components.
We continue injecting an `OsFs` as before. Everything still interacts with the real filesystem without a change in behavior, but through the abstraction instead of directly.
This sets us up for a future replacement of the `afero.Fs` with an in-memory data structure. It may be an in-memory implementation of `afero.Fs` at first, or potentially a different thing altogether. The eventual goal is to speed up rule group syncs, because …
> ruler: Refactor GroupLoader to use the same filesystem abstraction as the mapper

- docs/sources/helm-charts/mimir-distributed/run-production-environment-with-helm/_index.md
Following https://github.com/grafana/mimir/pull/12411
Here I'm updating the run-production-environment-with-helm with the details related to ingest storage architecture, that is the default after https://github.com/grafana/mimir/pull/12495
- explain the embedded single-node Kafka for demo purposes
- note the classic-architecture preset
- explain how to configure user managed Kafka in Mimir
Also, fixed a couple of typos across the document.
> docs: update run-production-environment-with-helm with details about ingest storage 

- .github/workflows/scripts/run-unit-tests-group.sh
- .github/workflows/test-build-deploy.yml
Automatically notify MQE maintainers when `pkg/streamingpromql` tests fail on mimir-prometheus vendoring PRs by posting a GitHub comment with @mentions.
These tests usually fail because there are tests in `pkg/streamingpromql/testdata/upstream/*.test` which need updating. Usually there's also the need to update some other unit tests or fix functionality. This is hard to automate and needs human judgement.
This PR tags @charleskorn, @56quarters, @lamida, @zenador and @Konstantinov-Innokentii  when `pkg/stremingpromql` fails unit tests during vendoring PRs.
- **Modified `.github/workflows/scripts/run-unit-tests-group.sh`**:
- Capture test output using `tee` while preserving real-time display
- Extract all failed package names and store in `FAILED_PACKAGES` environment variable
- Maintain …
> CI: Notify MQE maintainers when pkg/streamingpromql tests fail on vendor PRs

- CHANGELOG.md
- pkg/storegateway/bucket_chunk_reader.go
- pkg/storegateway/bucket_chunk_reader_test.go
The PR adds a validation to the `BucketChunkReader` to make sure it doesn't panic, if the parsed chunk length exceed the allowed buffer length. See #12691 for the details.
Fixes #12691
> storegateway: BucketChunkReader to validate chunk data length

- CHANGELOG.md
- pkg/distributor/otel.go
- pkg/distributor/otel_test.go
- pkg/util/http.go
Support zstd decompression of OTLP messages.
Note the decompression in `pkg/util` is exercised by the zstd tests in `pkg/distributor`.
(I did not investigate why it needs to be implemented twice)
I couldn't find any documentation of lz4 so didn't document zstd.
> Distributor: support zstd decompression of OTLP messages 

- tools/tsdb-gaps/main.go
- tools/tsdb-print-chunk/main.go
- tools/tsdb-series/main.go
When running these tools we would see a log like:
```
probe="internal message: if you see this, probably log initialization has gone wrong"
```
This comes from [here](https://github.com/grafana/mimir/blob/main/pkg/util/log/slogadapter.go#L16), and is mentioned in https://github.com/grafana/mimir/pull/10646 as a side-effect of using a non `util_log` logger with `SlogFromGoKit`.
This PR changes the logger initialization to use `util_log` to avoid the spurious line.
I don't think a changelog is required for this.
Fixes #
> Use util_log to initialize logger in tsdb-* tools

- CHANGELOG.md
- pkg/storegateway/bucket_chunk_reader.go
As @dimitarvdimitrov brought in https://github.com/grafana/mimir/pull/12693#discussion_r2352625595 the `tsdb.EstimatedMaxChunkSize` is only an estimation, and we shouldn't use it as the parser's cap. The PR updates the code to cap it with a more relaxed value.
Follows https://github.com/grafana/mimir/pull/12693
> storegateway: safeguard chunk parser

- CHANGELOG.md
- pkg/mimirpb/timeseries.go
Backporting to 2.17 a 1-line fix that was part of a bigger PR (#12652). This fix an data corruption issue caused by memory pooling when a newer version is rolled out and the experimental
-distributor.otel-created-timestamp-zero-ingestion-enabled feature is enabled.
Related to #12652 
> [release-2.17] Fix Timeseries CT reset before putting back to the pool

- development/mimir-monolithic-mode/compose-down.sh
- development/mimir-monolithic-mode/compose-up.sh
Replaced `#!/bin/bash` with `#!/usr/bin/env bash` in compose-up.sh and compose-down.sh to improve portability across different environments where bash may not be located at /bin/bash.
> chore: update shebang to use env for bash in compose scripts

- CHANGELOG.md
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
If the bucket limit is set for native histograms then no NHCB passes validation due to a coding error.
Enabled bucket limit in test config to reproduce and fixed bug.
Related to RW2 compliance work. https://github.com/prometheus/prometheus/issues/16944
> fix(distributor): NHCB bucket count validation wrong

- CHANGELOG.md
- operations/mimir-tests/test-automated-downscale-generated.yaml
- operations/mimir-tests/test-automated-downscale-v2-generated.yaml
- operations/mimir-tests/test-consul-multi-zone-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-custom-stabilization-window-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-multiple-triggers-generated.yaml
- operations/mimir-tests/test-ingest-storage-autoscaling-one-trigger-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-0-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-1-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-2-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-3-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-4-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5a-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-5b-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-6-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-7-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-8-generated.yaml
- operations/mimir-tests/test-ingest-storage-migration-step-final-generated.yaml
- operations/mimir-tests/test-multi-zone-distributor-generated.yaml
- operations/mimir-tests/test-multi-zone-etcd-generated.yaml
- operations/mimir-tests/test-multi-zone-generated.yaml
- operations/mimir-tests/test-multi-zone-with-ongoing-migration-generated.yaml
- operations/mimir-tests/test-multi-zone-with-store-gateway-automated-downscaling-generated.yaml
- operations/mimir-tests/test-pvc-auto-deletion-generated.yaml
- operations/mimir-tests/test-single-to-multi-zone-distributor-migration-generated.yaml
- operations/mimir/ingest-storage.libsonnet
If we're running ingest storage and have enabled three zones there's no need to ship blocks from it. Because all ingesters consume data from the partitions, they all have the _exact_ same data.
Technically, we only need 1 zone shipping blocks, but we run two for redudancy - three would be a waste of resources at this point.
N/A
Signed-off-by: gotjosh <josue.abreu@gmail.com>
> jsonnet: Remove block shipping on the third ingester zone when running ingest storage

- CHANGELOG.md
- pkg/distributor/validate.go
- pkg/distributor/validate_test.go
If the bucket limit is set for native histograms then no NHCB passes validation due to a coding error.
Enabled bucket limit in test config to reproduce and fixed bug.
Related to RW2 compliance work.
https://github.com/prometheus/prometheus/issues/16944
> [release-2.17] backport fix(distributor): NHCB bucket count validation wrong (#12741)

- integration/query_frontend_test.go
This PR temporarily disables an integration test introduced in https://github.com/grafana/mimir/pull/12745 that is failing in GEM, similar to #12699.
#12745
> Temporarily disable remote execution integration test

- CHANGELOG.md
- integration/querier_tenant_federation_test.go
- pkg/querier/dispatcher.go
This PR fixes an issue where tenant federation queries fail with `bad_data: multiple org IDs present` if remote execution is enabled.
https://github.com/grafana/mimir/pull/12551
> Remote execution: fix issue where tenant federation queries fail

- pkg/streamingpromql/planning.go
- pkg/streamingpromql/planning_test.go
Vector-scalar comparison without bool modifier doesn't drop names, so it will not produce duplicates. Therefore, DeduplicateAndMerge is not needed.
- ~[ ] Documentation added.~
- ~[ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.~
- ~[ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.~
> Do not wrap vector-scalar comparison in DeduplicateAndMerge

- integration/query_frontend_test.go
This PR re-enables the integration tests disabled in https://github.com/grafana/mimir/pull/12699 and https://github.com/grafana/mimir/pull/12756.
(none)
> Re-enable disabled integration tests

- pkg/distributor/otel_test.go
- pkg/distributor/otlpappender/mimir_appender.go
- pkg/distributor/otlpappender/mimir_appender_test.go
- pkg/mimirpb/testutil/timeseries.go
Instead of allocating from heap.
Related to #12652
- N/A  `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`. If changelog entry is not needed, please add the `changelog-not-needed` label to the PR.
> perf(rw2): use mimirpb.TimeseriesFromPool()

- CHANGELOG.md
- pkg/ingester/ingester.go
- pkg/ingester/metrics.go
- pkg/ingester/owned_series_test.go
- pkg/ingester/user_tsdb.go
- pkg/ingester/user_tsdb_test.go
Introduce the `cortex_ingester_owned_target_info_series` metric, for counting of owned `target_info` series per tenant. The motivation is to make it possible to determine the amount of churn before relabeling of `target_info` series.
I don't think the changes to owned series recomputation should have any significant perf impact, especially considering this is only called every 15 seconds.
> Ingester: Introduce metric cortex_ingester_owned_target_info_series

- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- pkg/continuoustest/ingest_storage_record.go
This PR:
- Removes per-record statistics logs (anything per-record can generate spam) and replace them with metrics where appropriate.
- Tunes tuneables:
- The limit at which to skip a partition on the current run and just jump to the end. This was simply too small for large cells and we jump too often.
- Reduces `fetchMaxBytes` by 10x, to force more smaller fetches. Cells with a high partition count still grab a staggering number of records per fetch. Even with limits, this doesn't take advantage of parallelism very well.
contrib: https://github.com/grafana/mimir-squad/issues/2253
> continuous-test: Improve record test logging/metrics, adjust tuneables

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/storage/tsdb/config.go
I found this while working on https://github.com/grafana/mimir/pull/12752
> index planning: fix config defaults and validation

- CHANGELOG.md
- operations/helm/tests/metamonitoring-values-generated/mimir-distributed/templates/metamonitoring/grafana-dashboards.yaml
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-baremetal/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled-gem/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-reads.json
- operations/mimir-mixin-compiled/dashboards/mimir-remote-ruler-reads.json
- operations/mimir-mixin/dashboards/dashboard-queries.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
This PR fixes an issue where the querier panels on the "reads" and "remote ruler reads" dashboards would show no data if remote execution is enabled.
https://github.com/grafana/mimir/pull/12302 and https://github.com/grafana/mimir/pull/12551
> Fix empty querier panels on "reads" and "remote ruler reads" dashboards with remote execution enabled

- pkg/frontend/querymiddleware/astmapper/astmapper_test.go
- pkg/frontend/querymiddleware/astmapper/parallel_test.go
This PR replaces our `mustLabelMatcher` function with Prometheus' equivalent `labels.MustNewMatcher`.
(none)
> Cleanup: replace `mustLabelMatcher` with `labels.MustNewMatcher`

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- development/mimir-ingest-storage/config/runtime.yaml
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/codec_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/transport/handler.go
- pkg/frontend/transport/handler_test.go
- pkg/frontend/v2/frontend_test.go
- pkg/ingester/ingester.go
- pkg/mimir/modules.go
- pkg/querier/api/consistency.go
- pkg/querier/api/consistency_test.go
- pkg/ruler/compat.go
- pkg/ruler/remotequerier.go
- pkg/ruler/remotequerier_test.go
- pkg/ruler/rule_query_consistency.go
- pkg/ruler/rule_query_consistency_test.go
- pkg/storage/ingest/reader.go
- pkg/storage/ingest/reader_test.go
- pkg/util/validation/limits.go
In this PR I'm adding the experimental support to configure the max eventual consistency delay on a per-query basis. The max delay is currently propagated via a new internal HTTP header named `X-Read-Consistency-Max-Delay`, but in a follow up PR I will try to reuse the existing `X-Read-Consistency` header to both specify the level (as of today) and the max delay (new).
The max delay is intended to be used internally, and in particular by ruler. When a rule is evaluated with eventual consistency, we may want to specify a max delay to ensure it doesn't get executed on very stale data. I initially though to set the delay equal to the configured `ruler_evaluation_delay_duration`, but in this PR I'm introducing a new experimental configuration option called …
> Add support to configure max eventual consistency delay on a per-query basis

- pkg/costattribution/active_tracker.go
This piece of code duplicates the previous lines, and is never executed because the previous branches have their return statement.
No changelog or anything needed, this is a noop.
> costattribution.ActiveSeriesTracker: remove duplicate code

- CHANGELOG.md
- pkg/costattribution/active_tracker.go
- pkg/costattribution/active_tracker_test.go
- pkg/costattribution/manager.go
- pkg/costattribution/manager_test.go
- pkg/costattribution/testutils/test_utils.go
This fixes the continuous (every cooldown period) reloads of the active series trackers when the cost-attribution tracker is above the max cardinality.
When cost-attribution active-series tracker observes more than the maxCardinality label combinations, it enters the overflow and tracks the time when it entered the overflow mode.
After a cooldown period (20 minutes by default) we delete the tracker, which causes active-series tracker to reload (in order to correctly fill the cost atttribution active series tracker again), and this process starts again.
We will track up to `2*maxCardinality` label combinations internally, this way we can have some insights about the customer behavior, even though it's not absolutely precise.
After the cooldown period, we'll check whether the number of …
> Avoid continuous active series tracker reloads when cost attribution is in overflow

- pkg/ingester/ingester.go
- pkg/ingester/lookupplan/metrics.go
- pkg/ingester/lookupplan/planner.go
- pkg/ingester/lookupplan/query_stats.go
- pkg/ingester/lookupplan/query_stats_test.go
- pkg/ingester/metrics.go
- pkg/ingester/stats.go
Add infrastructure to track estimated vs actual cardinalities in query processing to improve observability of lookup planning accuracy. This enables monitoring how well the cost-based planner estimates match actual query execution.
There are 4 key metrics: 
* estimated/actual selected postings
* estimated/actual final series
We track the ratio between actual/estimated + ratio between actual postings/actual final series
- Add `lookupplan.QueryStats` tracker with atomic operations for thread-safe cardinality tracking
- Add 3 native histogram metrics for cardinality ratio analysis. Measurements there are observed with exemplars.
- Implement stats-tracking querier wrapper to measure actual cardinalities
- Integrate PostingsCloner to capture actual selected postings count
- Populate estimated …
> index planning: Add query cardinality metrics

- pkg/frontend/querymiddleware/astmapper/astmapper.go
- pkg/frontend/querymiddleware/astmapper/astmapper_test.go
@colega suggested fuzz testing `cloneExpr` in https://github.com/grafana/mimir/pull/12787#discussion_r2371969778.
Generating valid PromQL expressions through fuzzing is difficult and didn't produce a lot of useful results.
However, we do have a large corpus of PromQL expressions that are used to test MQE - both those we've written ourselves as well as those from upstream, so in this PR I'm exercising `cloneExpr` with these expressions. This should help catch any newly-added features, as these are very likely to be exercised with these test scripts.
This uncovered one case that was not being handled properly in `cloneExpr`, as well as some deficiencies in `requireNoSharedPointers`.
#12787
- [n/a] `CHANGELOG.md` updated - the order of entries should be …
> Use MQE and upstream test cases to further exercise `cloneExpr`

- CHANGELOG.md
- pkg/mimir/modules.go
- pkg/usagestats/report.go
- pkg/usagestats/report_test.go
- pkg/usagestats/stats.go
The PR updates the anonymous usage statistics, so it reported the Mimir architecture (mode), the installation runs with.
Note, I've picked the key `mode`, and not "architecture" because the stats already report "arch" for the CPU architecture. I find it confusing. We already used "ingest-storage mode" in some context in the docs and in changelog, so I find it fitting.
> usagestats: report "ingest-storage" or "classic" architecture mode

- CHANGELOG.md
- pkg/storegateway/bucket_chunk_reader.go
- pkg/storegateway/bucket_chunk_reader_test.go
This is the cherry-pick of changes https://github.com/grafana/mimir/pull/12693 + https://github.com/grafana/mimir/pull/12729 to r360
Relates to https://github.com/grafana/mimir/issues/12691
> [r360] storegateway: BucketChunkReader to validate chunk data length

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/parquetconverter/parquet_converter.go
Just another knob to filter the wanted blocks.
> parquet converter: add `parquet-converter.min-block-duration` flag

- CHANGELOG.md
- pkg/streamingpromql/optimize/ast/propagate_matchers.go
- pkg/streamingpromql/optimize/ast/propagate_matchers_test.go
- pkg/streamingpromql/optimize/ast/prune_toggles.go
- pkg/streamingpromql/optimize/ast/prune_toggles_test.go
- pkg/streamingpromql/optimize/ast/reorder_histogram_aggregation.go
- pkg/streamingpromql/optimize/ast/reorder_histogram_aggregation_test.go
- pkg/streamingpromql/optimize/ast/util_test.go
Pruning query toggles was broken with https://github.com/grafana/mimir/pull/12303 when it moved to AST optimization passes, as the query planner preprocess step wraps some parts of the expression in StepInvariantExpressions which we did not account for in the code and unit tests working on it in isolation instead of as part of the query plan.
This fixes that bug and adds preprocessing to the unit tests for some AST optimization passes. Will do testing with more of the query plan in another [PR](https://github.com/grafana/mimir/pull/12784) as that requires bigger changes to the planning code.
Follow up to https://github.com/grafana/mimir/pull/12303
> Fix bug with pruning toggles not working in query planner

- operations/mimir-mixin/config.libsonnet
- operations/mimir-mixin/dashboards/dashboard-utils.libsonnet
Reverts a [recent change](https://github.com/grafana/mimir/pull/12688) to set the mimir dashboard links via a $._config variable.
This change causes upstream vendoring issues.
Relates to https://github.com/grafana/mimir/pull/12688
> Revert moving dashboard links into config

- pkg/frontend/querymiddleware/limits.go
- pkg/querier/dispatcher.go
This PR fixes the issue where querier and query-frontend trace spans would be marked as failed if the request was cancelled.
#12302 and #12551
> Remote execution: don't mark trace spans as failed if request is cancelled

- CHANGELOG.md
- pkg/frontend/v2/remoteexec.go
This PR fixes an issue where query-frontends can panic if the stream from queriers ends unexpectedly.
This shouldn't be happening, but if it does happen for some reason, then we don't want the entire process to crash.
#12551
> Remote execution: don't panic if stream ends unexpectedly

- CHANGELOG.md
- pkg/streamingpromql/functions_test.go
- pkg/streamingpromql/operators/functions/factories.go
- pkg/streamingpromql/operators/functions/range_vectors.go
- pkg/streamingpromql/testdata/ours/functions.test
- pkg/streamingpromql/testdata/upstream/functions.test
This PR adds PromQL support for the experimental functions of ts_of_min_over_time, ts_of_max_over_time, ts_of_first_over_time and ts_of_last_over_time.
Fixes #3089
> Add support for ts_of_ promql functions

- cmd/mimir/config-descriptor.json
- cmd/mimir/help-all.txt.tmpl
- cmd/mimir/help.txt.tmpl
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/parquetconverter/parquet_converter.go
- pkg/parquetconverter/parquet_converter_test.go
Refactors the skipping logic out to make it testable. Ideally we'd test it end to end but that requires a more complex setup, for a code that will probably be discarded soon. For now this is enough.
Additionally, I'm removing the `parquet-converter.max-queue-size` flag. As it is now the flag does not fully limit the queue size, as the check is only done at the top of the discovery routine. Because we were leaving the default value of 5, this resulted in no blocks being added before the worker got to (roughly) the end of the queue, which skewed the real queue size for monitoring.  Also, with the current logic, it doesn't help with its original purpose of distributing load, probably because some things changed since it was added.
> parquet converter: test and refactor block conversion skip logic

- pkg/parquetconverter/parquet_converter.go
Failed or skipped blocks are usually processed instantly, so they skew the metrics
> parquet-converter: conversion latency metric to only look at successes

- pkg/mimirpb/compat_rw2_test.go
- pkg/mimirpb/custom.go
- pkg/mimirpb/mimir.pb.go
- pkg/mimirpb/mimir.pb.go.expdiff
- pkg/mimirpb/timeseries.go
The RW2 unmarshal uses a `map[string]*orderAwareMetricMetadata` that's injected everywhere, used to track and deduplicate metadata, and also store them as we convert back to RW1.
This PR is a refactor that puts this behind a `metadataSet` interface. We then introduce a `dedupingMetadataSet` implementation that just wraps the very same map. In the future we want to introduce alternate metadata handling strategies that don't deduplicate, this makes it easy.
Just converting it to a `map[string][]*orderAwareMetricMetadata` is too unwieldy and allocations inside the inner slices are difficult to control, this approach is more minimal. It also means we can move a little custom logic out of `mimir.pb.go` and into regular Go files, reducing the divergence of our edits to the generated code.
This …
> mimirpb: Refactor RW2 metadata handling out of generated code

- pkg/storegateway/parquet_bucket_store.go
- pkg/storegateway/parquet_bucket_store_test.go
Limit errors coming from parquet-common are currently mapped to Internal errors in gRPC. Those will be retried by queriers: https://github.com/grafana/mimir/blob/443ec0c7bb290e42e587a64697822e894cf96a28/pkg/querier/blocks_store_queryable.go#L1049-L1059
We should instead return a `422`, like the main path does: 
https://github.com/grafana/mimir/blob/443ec0c7bb290e42e587a64697822e894cf96a28/pkg/storegateway/limiter.go#L62-L73
A nicer way of fixing this would be introducing an interface in parquet-common for the limiter, so we can return our own errors. The simpler way I went with is by detecting the error type and wrapping it with the correct status, at the top level to catch all paths.
See parquet common: https://github.com/grafana/mimir/blob/443ec0c7bb290e42e587a64697822e894cf96a28/vendor/ …
> fix(parquet store gateway): map limit errors to UnprocessableEntity status

- pkg/frontend/querymiddleware/astmapper/sharding.go
- pkg/frontend/querymiddleware/astmapper/sharding_test.go
- pkg/frontend/querymiddleware/querysharding.go
Backport https://github.com/grafana/mimir/commit/d7c3c518562723dcb8e08e6aeb66f962c8a6ed75 from https://github.com/grafana/mimir/pull/12900
> [r362] Fix issue where binary expressions with one side containing parentheses aren't sharded

- pkg/frontend/querymiddleware/astmapper/sharding.go
- pkg/frontend/querymiddleware/astmapper/sharding_test.go
This PR is a follow up to https://github.com/grafana/mimir/pull/12900. It fixes a number of other similar cases that affect other expressions on one side of binary expressions. These were all caused by `canShardAllVectorSelectors` incorrectly returning false. 
I don't believe any of these would have caused incorrect query results, but instead would have caused sharding not to be applied when it should have been.
There is an opportunity to remove the "inspect only" mode introduced in #12677 and instead make use of `willShardAllVectorSelectors` when calculating the number of shardable legs, but I will do this in a follow up PR.
I haven't added a changelog entry for the same reason I did not add one in #12900.
#12900 and #12677
- [n/a] `CHANGELOG.md` updated - …
> Fix more issues where some binary expressions aren't sharded

- CHANGELOG.md
- cmd/mimir/config-descriptor.json
- docs/sources/mimir/configure/configuration-parameters/index.md
- pkg/frontend/config.go
- pkg/frontend/config_test.go
- pkg/frontend/querymiddleware/codec.go
- pkg/frontend/querymiddleware/error_caching_test.go
- pkg/frontend/querymiddleware/limits.go
- pkg/frontend/querymiddleware/limits_test.go
- pkg/frontend/querymiddleware/model_extra.go
- pkg/frontend/querymiddleware/prom2_range_compat_test.go
- pkg/frontend/querymiddleware/remote_read_test.go
- pkg/frontend/querymiddleware/roundtrip.go
- pkg/frontend/v2/frontend.go
- pkg/frontend/v2/frontend_test.go
- pkg/frontend/v2/remoteexec_test.go
- pkg/mimir/modules.go
This PR fixes the issue where the `max_query_parallelism` / `-querier.max-query-parallelism` option is not respected if sharding is running inside MQE.
⚠️ This PR is dependent on https://github.com/grafana/mimir/pull/12835 and https://github.com/grafana/mimir/pull/12885.
https://github.com/grafana/mimir/pull/12835
> Limit parallelism of sharded queries when sharding is running inside MQE

- docs/sources/mimir/set-up/jsonnet/configure-ingest-storage.md
Following https://github.com/grafana/mimir/pull/12411 https://github.com/grafana/mimir/pull/12624, etc
Here I'm adding a new documentation piece, that outlines the setup process of running a new Mimir cluster under the ingest storage architecture with Jsonnet.
> docs: document ingest storage jsonnet setup

- pkg/ingester/ingester.go
Updates the ingester to build postings cache factories once per ingester, for head and compacted blocks respectively, rather than once per userTSDB. This is the intended goal of the shared postings for matchers cache - where caches are multi-tenant.
> Build postings cache factories per ingester
